### ISSUE TITLE
API:routes on Lumen

### ISSUE THREAD

**Issue by AbbyLynn** [dingo/api#1000]
So with Lumen when trying to use the API:routes command which isn't easily accessible without adding it to my console kernel to begin with, I am getting an error.

>   Class 'Illuminate\Foundation\Console\RouteListCommand' not found  

The reason for this is that Lumen does not include the Illuminate\Foundation, It is also not available via composer because the github repo for it is no longer maintained. I am unsure why but idk if maybe just make a mention in the wiki docs.

**Comment by hskrasek** [comment]
Will look into documenting this being unavailable

**Comment by hskrasek** [comment]
Double checked the docs, adequate documentation exists already showing that the `api:routes` command is only available in Laravel and not Lumen. Closing
