### ISSUE TITLE
[DOCs] Authentication

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#1003]
Hey, 

in the docs for the authentication (oAuth) you state:

> This package makes use of a 3rd party package to integrate OAuth 2.0. You can either install league/oauth2-server and configure the server yourself or use the bridge package, lucadegasperi/oauth2-server-laravel.
> 
> For simplicity this guide will assume you are using the bridge package.

What one needs to do is to actually load the Service providers of the bridge package.

```
LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider::class,
LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider::class,
```

I know you said `install` but I read this as `composer require` and was wondering why I get a `Reflection` error.

Maybe you could add this to the example Service Provider, to make it more clear for people like me. :)

```php
    public function register()
    {
        $this->app->register(\LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider::class);
        $this->app->register(\LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider::class);
    }
```

Maybe in any case you could change it to this (or something like this):

> This package makes use of a 3rd party package to integrate OAuth 2.0. You can either install league/oauth2-server and configure the server yourself or use the bridge package, lucadegasperi/oauth2-server-laravel. If you use the bridge package you will still need to [configure](https://github.com/lucadegasperi/oauth2-server-laravel/tree/master/docs/getting-started) the package and create the database.
> 
> For simplicity this guide will assume you are using the bridge package.

In the docs for the packages it says I have to register some middleware and route middleware: https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/getting-started/lumen.md

I am assuming this is not necessary when using dingo?

**Comment by hskrasek** [comment]
@lukasoppermann Dingo contains a middleware that handles this already. As for the docs, I think we can update them to be more clear. I think it was assumed that install meant go through that packages installation steps, but that can be cleared

**Comment by lukasoppermann** [comment]
Thanks, clearing this up would be awesome. Would you need a PR or will y be doing it by yourself?

**Comment by hskrasek** [comment]
I'm not against a PR, but if you're not able to at the moment I can take care of it. If you do open one, just make sure to tag this issue in it.

Hunter Skrasek
817.937.7914
hunterskrasek@me.com

**Comment by lukasoppermann** [comment]
Okay, than I will **not** send in a PR and just wait for you to update it, since you wrote in some other issues that you will update part of the docs in any case.

**Comment by hskrasek** [comment]
Added further clarification to the documentation when using the bridge package. Closing out
