### ISSUE TITLE
Error in DOCs?

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#1008]
When I tried this (with an item):

https://github.com/dingo/api/wiki/Transformers#utilizing-the-callback
> If you're not using the parameters to pass a resource key you can omit the empty array and simply pass the callback as the third parameter.

```
return $this->collection($users, new UserTransformer, function ($resource, $fractal) {
    $fractal->setSerializer(new CustomSerializer);
});
```

I got an error, that the third parameter is supposed to be an `array`. Adding the array fixed it. Did I do something wrong? Or is this not possible anymore? (I do not think it needs to be possible, personally.)

**Comment by hskrasek** [comment]
This is infact an error in the docs. Need to either update the docs, or fix the method signature

**Comment by hskrasek** [comment]
@lukasoppermann Wound up updating the code to support what the docs say.
