### ISSUE TITLE
Cannot get authenticated user in controller's constructor

### ISSUE THREAD

**Issue by kerbylav** [dingo/api#1013]
This would cause circular reference to controller's constructor

```
class ActionController extends Controller
{
    use Helpers;

    /** @var null App\Models\Access\User\User */
    protected $currentUser = null;

    /**
     * @var Request
     */
    protected $request = null;

    /**
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        $this->currentUser = app('Dingo\Api\Auth\Auth')->user();
        $this->request = $request;
    }
```

**Comment by thomasisberg** [comment]
We have a similar problem right now. Code instantiates a new controller until PHP runs out of memory. Code works when user is accessed in any other function.

**Comment by pulkitjalan** [comment]
Having the same problem, traced it through to `Dingo\Api\Routing\Route@makeControllerInstance`.

Its when `$this->container->make($this->controllerClass)` is called and the ioc container calls the constructor of the same controller again, causing it to go through the whole process of authentication the user again which requires the route and scopes etc...

**Comment by designvoid** [comment]
Anyone figure this out??

**Comment by hskrasek** [comment]
This is sorta related to #987 and how the framework works when handling routing. At the moment, the best fix I have for you is to not get the authenticated user in the controllers constructor.

**Comment by hartantothio** [comment]
@hskrasek -- I also notice this issue. I'm on Laravel 5.2, as soon as I updated my packages, I experience this issue. I also tried the solution from the SO and it doesn't work for me.

Below are the updated packages:

  - Removing psr/log (1.0.0)
  - Installing psr/log (1.0.1)
    Downloading: 100%

  - Installing webmozart/assert (1.1.0)
    Loading from cache

  - Installing phpdocumentor/reflection-common (1.0)
    Loading from cache

  - Installing phpdocumentor/type-resolver (0.2)
    Loading from cache

  - Removing phpdocumentor/reflection-docblock (2.0.4)
  - Installing phpdocumentor/reflection-docblock (3.1.0)
    Loading from cache

  - Removing dingo/blueprint (v0.1.6)
  - Installing dingo/blueprint (v0.2.0)
    Loading from cache

  - Removing dingo/api (v1.0.0-beta3)
  - Installing dingo/api (dev-master 242411e)
    Loading from cache

**Comment by hskrasek** [comment]
See https://github.com/dingo/api/issues/987#issuecomment-242891252
