### ISSUE TITLE
Lumen 5.2 NotFoundHttpException

### ISSUE THREAD

**Issue by enginkartal** [dingo/api#1015]
I  upgraded  Lumen 5.1. to 5.2.  PATCH Request's are getting error like below. My query is too long(My string is 11325 characters long).  Is it related to that or timeout?  
**The error :**
`{"message":"404 Not Found","status_code":404,"debug":{"line":443,"file":"C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(381): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#1 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(629): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#2 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#3 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Routing\\Router.php(574): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(123): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(150): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#8 C:\\wamp\\www\\works\\yp-api\\vendor\\palanik\\lumen-cors\\LumenCors.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 [internal function]: palanik\\lumen\\Middleware\\LumenCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#10 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#11 C:\\wamp\\www\\works\\yp-api\\vendor\\lucadegasperi\\oauth2-server-laravel\\src\\Middleware\\OAuthExceptionHandlerMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 [internal function]: LucaDegasperi\\OAuth2Server\\Middleware\\OAuthExceptionHandlerMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#14 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#15 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#16 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(124): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#17 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(100): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#18 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#19 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#20 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#21 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#22 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#23 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#24 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(626): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#25 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#26 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(327): Laravel\\Lumen\\Application->dispatch(NULL)","#27 C:\\wamp\\www\\works\\yp-api\\public\\index.php(28): Laravel\\Lumen\\Application->run()","#28 {main}"]}}`

**Comment by hskrasek** [comment]
@enginkartal Not sure if you're still experiencing this issue, but based on the error response you sent me, it looks like the route you tried to hit is not found or missing. If thats not the issue you're facing though, I'd need more context.
