### ISSUE TITLE
[Doc] Method Response JSON array in Body gives Expected PlainValue, got '['

### ISSUE THREAD

**Issue by Deleugpn** [dingo/api#1017]
I'm trying to declare this sort of response in my method's doc block:

```
* @Response(200, body={"data":[{"id":1,"name":"Product Name","storeId":4,"count":1000,"reserve":0,"cost":6000,"image":"upload/prize/1/1.png"},{"id":2,"name":"2nd Product","storeId":4,"count":1000,"reserve":0,"cost":6000,"image":"upload/prize/1/2.png"}]})
```
But this gives me 

> [Doctrine\Common\Annotations\AnnotationException] [Syntax Error] Expected PlainValue, got '[' at position 111 in method App\Http\Controllers\v2\PrizesController::index().

In order to make it work, I have to remove the ```[``` and ```]``` and then the doc result is:

```
            {
                "data": {
                    ...
                },
                "0": {
                    ...
                }
            }
```

Am I doing something wrong here?

**Comment by tomcoonen** [comment]
Same issue here.

**Comment by Deleugpn** [comment]
Perfect, this solves it.
