### ISSUE TITLE
API Call caching, best practice

### ISSUE THREAD

**Issue by tomcoonen** [dingo/api#1018]
I'm trying to cache an API respons (item or collection), what is the best practice when using Dingo?
Simpy doing this doesn't work;

```
return Cache::remember('test', 60, function() {
    return $this->collection($this->products, new ProductTransformer);
});
```

**Comment by catalinux** [comment]
Usually this is prefered in you service. For exempla, let's say you have  a service called: `ProductService` with `getProducts` method. You will have a a ProductServiceCache  with the same method (practically you implement a common interface with `getProducts` method). Your `getProducts` will return a Collection. The transformer is part of you View-Controller part, and should stay in your Controller.  

```php
<?php


interface ProductServiceInterface
{
    function getProducts();
}

class ProductService implements ProductServiceInterface
{
}

class ProductServiceCache implements ProductServiceInterface
{

    protected $realService;
    
    function __constructor(ProductServiceInterface $realService)
    {
        $this->realService = $realService;
        
    }

    function getProducts()
    {
        return Cache::remember('test', 60, function () {
            $this->realService->getProducts();
        });
    }
}

**Comment by hskrasek** [comment]
@catalinux Is pretty much correct on this one. Even if you're wanting to cache a internal API call, you could just add caching to the internal API you are calling and accomplish the same thing.
