### ISSUE TITLE
Unable to catch exception thrown by the controller for internal api request

### ISSUE THREAD

**Issue by ajeeshcitrus** [dingo/api#1019]
I have the following code where I am doing an internal request

```php
try
        {
            $response = $this->dispatcher->version($version)->$type($payload)->$method($uri);

        } catch (Dingo\Api\Exception\StoreResourceFailedException $e) {
            
            return $response = $e->getResponse();
            
        }
```

This is how the internal API throws exception

```
}
        catch(ValidatorException $e)
        {
            throw new Dingo\Api\Exception\StoreResourceFailedException('Invalid input provided. ', $e->getMessageBag());
        }
```

I am unable to catch this exception. It showing the HTML with the exception errors and stacks. Why am I not able to catch the exception thrown in the API?

**Comment by jasonlewis** [comment]
I'm assuming you're running the top code from the root namespace? Otherwise you'll need to prefix the class...

```php
} catch (\Dingo\Api\Exception\StoreResourceFailedException $e) {
```

Or import it at the top.
