### ISSUE TITLE
Custom Exception Responses in laravel

### ISSUE THREAD

**Issue by SteveAzz** [dingo/api#1020]
In the wiki you see the following to register exception responses, this seems to be specific for lumen. Where and how to I do this in a laravel 5.2 installation. 
```
app('Dingo\Api\Exception\Handler')->register(function (Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException $exception) {
    return Response::make(['error' => 'Hey, what do you think you are doing!?'], 401);
});
```

**Comment by prazvan** [comment]
Hey, so here is how i did it :)

1. in app/Providers create a new ServiceProvider Ex: ExceptionsServiceProvider.php
2. in your config/app.php register the new provider App\Providers\ExceptionsServiceProvider::class,
3. in the register method of the provider just call the app('Dingo\Api\Exception\Handler')->register(function(){ ... });

Ex of provider:

`<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Routing\Router;

/**
 * Class ExceptionsServiceProvider - Hacky?!
 * @package App\Providers
 */
class ExceptionsServiceProvider extends ServiceProvider
{
    /**
     * @return void
     */
    public function boot(){}

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        app('Dingo\Api\Exception\Handler')->register(function (\Illuminate\Database\Eloquent\ModelNotFoundException $exception) {
            throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
        });
    }
}`

Razvan.

**Comment by SteveAzz** [comment]
That worked, thank you :)

**Comment by assembledadam** [comment]
You should close this issue if it's resolved - Jason already has a enough to go through!

**Comment by cona88** [comment]
Hi @SteveAzz, 
i did it the same but i have error:
Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler
Can you suggest solution?

**Comment by SteveAzz** [comment]
@cona88 Can you please show your code

**Comment by cona88** [comment]
@SteveAzz 
In my config/app.php
`   /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\ExceptionsServiceProvider::class,`

in Providers/ExceptionsServiceProvider.php
`<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;


class ExceptionsServiceProvider extends ServiceProvider
{
    /**
     * @return void
     */
    public function boot(){}

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        app('Dingo\Api\Exception\Handler')->register(function (Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException $exception) {
            return Response::make(['error' => 'Hey, what do you think you are doing!?'], 401);
        });
    }
}`
Please help!

**Comment by SteveAzz** [comment]
Hello, I have the following in my register method

```php
/**
 * Register the service provider.
 *
 * @return void
 */
public function register()
{
    app('Dingo\Api\Exception\Handler')->register(function (\Illuminate\Database\Eloquent\ModelNotFoundException $exception) {
        throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
    });
}
```

**Comment by cona88** [comment]
Hello,
I tried it, but still error :(

**Comment by cona88** [comment]
@SteveAzz 
I fixed it,
In the app.php: i move ` App\Providers\ExceptionsServiceProvider::class,` to the end of   'providers'

**Comment by sandysong** [comment]
@SteveAzz you should  put your code in 'boot()' method
