### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by gh81997167** [dingo/api#1022]
**How can i use the Serializer in dingo api? Please guide me how to use ,thank you!**
In fractal is :
use Acme\Model\Book;
use Acme\Transformer\BookTransformer;
use League\Fractal\Manager;
use League\Fractal\Resource\Item;
use League\Fractal\Serializer\DataArraySerializer;

$manager = new Manager(); 
$manager->setSerializer(new DataArraySerializer());

// Some sort of ORM call
$book = Book::find(1);

// Make a resource out of the data and
$resource = new Item($book, new BookTransformer(), 'book');

// Run all transformers
$manager->createData($resource)->toArray();

// Outputs:
// [
//     'data' => [
//         'id' => 'Foo',
//         'title' => 'Foo',
//         'year' => 1991,
//     ],
// ];

**Comment by kmaxat** [comment]
Read Docs: https://github.com/dingo/api/wiki/Transformers#utilizing-the-callback

**Comment by gh81997167** [comment]
thx,I'll try
