### ISSUE TITLE
How can I use 2 middlewares in a group?

### ISSUE THREAD

**Issue by morfin** [dingo/api#1023]
Currently I have:
`$api->group(['middleware' => 'auth'], function($api){......`

I need something like this:
`$api->group(['middleware' => ['auth', 'api.auth']], function($api){......`

So the routes inside this group will be accesible via session based authentication and oAuth 2. 

According to Laravel:

> Middleware are applied to all routes within the group by defining the list of middleware with the middleware parameter on the group attribute array. Middleware will be executed in the order you define this array:

> `Route::group(['middleware' => ['foo', 'bar']], function()`

If I try that with Dingo, I get an error.

Any idea?
Thanks.

**Comment by enbaby** [comment]
$api->group(['middleware' => 'oauth|api.throttle','limit' => 1, 'expires' => 1],function($api) 

I use oauth and rate limit middleware,it seems like works.

**Comment by jasonlewis** [comment]
Uh, what's the error you get with the first method you used? Working fine for me.
