### ISSUE TITLE
Token Signature could not be verified.

### ISSUE THREAD

**Issue by djoks** [dingo/api#1025]
Hello I am trying to authenticate a user and if login successful validate if a user is logged in one very request however I get this error: **401 Token Signature Could Not Be Verified**

This is my login code:
```
       $credentials = [
            "username" => $request->username,
            "password" => $request->password
        ];

        // Authenticating user
        if (!$token = JWTAuth::attempt($credentials))
        {
            // return the 401 authorized response
            return $this->response->error('Invalid username or password!', 401);
        }
```

And in my controller's constructor method I do this to check if the user is authenticated:
`$this->middleware('api.auth');`

**Comment by jasonlewis** [comment]
Authentication routes should not be placed under the `api.auth` middleware.
