### ISSUE TITLE
POST endpoints seem to fail, whereas identical GET endpoint does not.

### ISSUE THREAD

**Issue by ymhr** [dingo/api#1027]
I have two endpoints,
```
$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
	$api->group(['prefix' => 'events'], function ($api) {
		$api->get('{eventId}', 'App\Api\v1\Controllers\EventsApiController@get');
		$api->post('{eventId}', 'App\Api\v1\Controllers\EventsApiController@update');
	});
});
```

The `post` endpoint _always_ fails, and returns a 500 error - I cannot work out why - both endpoints run the same code:
```
public function get($id){
        return Event::findOrFail($id);
    }
```

I've tried changing the `post` to a `put` and an `any` as well, but even then, it does not work.

I figured there must be something I've missed, but I can't really find any specific documentation on posting to endpoints, so I can't think what it might be.

I've been using postman to test, but I have also tried posting from a client, to no avail.

**Comment by catalinux** [comment]
Error 500 means most probably you have a PHP error. You should look into lumen/laravel log

**Comment by ionut-tanasa** [comment]
Stacktrace? What does it say

**Comment by ymhr** [comment]
@catalinux I checked the PHP and Nginx error logs, but totally forgot that Laravel had it's own (I don't work on it too often!) - total brainfart, please close this issue, it's unrelated to Dingo.

**Comment by jasonlewis** [comment]
Is this still an issue @ymhr?

**Comment by ymhr** [comment]
No I was just an idiot.
