### ISSUE TITLE
the api version is not visited

### ISSUE THREAD

**Issue by fengyun8** [dingo/api#1030]
code:
`$api->version('v1', function ($api) {
    $api->get('two', 'App\Http\Controllers\Api\V1\FirstController@twoFunction');
});

$api->version('v2', function ($api) {
    $api->get('two', 'App\Http\Controllers\Api\V2\FirstController@twoFunction');
});`

postman:
![image](https://cloud.githubusercontent.com/assets/8663112/15294378/962146c2-1bbe-11e6-86da-f8387ac324a1.png)

question:
    the result is not true. I expect the result is "v2", but this is the "v1"

**Comment by apaleja** [comment]
Clear `api:cache` and make sure, you are using same `API_SUBTYPE`.

**Comment by fengyun8** [comment]
OK, I solve it, Thanks!
