### ISSUE TITLE
How i can extend api.auth middleware?

### ISSUE THREAD

**Issue by aios** [dingo/api#1031]
I maked a unique id of browser - and i want add some function to api.auth middleware to compare requests id. 

how i can make it?

**Comment by tobias-kuendig** [comment]
Create a new middleware that extends the existing Auth middleware:

```php
namespace App\Http\Middleware;

use Closure;
use Dingo\Api\Http\Middleware\Auth;

class CustomAuth extends Auth
{
    public function handle($request, Closure $next)
    {
        // Do your checks...

        return parent::handle($request, $next);
    }
}
```

Then register your middleware in your Http/Kernel.php

```php
protected $routeMiddleware = [
        // ...
        'auth.custom' => \App\Http\Middleware\CustomAuth::class
];
```

And use it in your routes:

```php
$api->version('v1', ['middleware' => 'auth.custom'], function ($api) {
    $api->get('users', 'Api\Controllers\UserController@index');
});
```

**Comment by aios** [comment]
GREAT!!! Thanks! Ymmd!

**Comment by rathinam90** [comment]
Working fine. While I am checking with,
php artisan api:route
It shows all apis with protected field value "NO"
