### ISSUE TITLE
Dingo with NeoEloquent (Neo4j)

### ISSUE THREAD

**Issue by suhaibmalik** [dingo/api#1032]
Has anyone got Dingo working with Neo4j? After setting up the first error I get is : 

`{"message":"preg_match() expects parameter 2 to be string, array given","status_code":500,"debug": ...`

It may h ave to do with the way NeoEloquent formats the output but as far as I know the purpose of that package is to mimic Eloquent.

**Comment by jasonlewis** [comment]
Never tried it myself...

But no idea where the error is occurring because the important part of the stack was trimmed off. If you can get that we might be able to debug this if you're still having issues.
