### ISSUE TITLE
I feel very confused，I can't find errors

### ISSUE THREAD

**Issue by gamelife1314** [dingo/api#1033]
After  configuring dingo and creating a route,I got result by executing `php artisan api:routes` as follows
+-----------------+----------+------------+------+---------+-----------+------------+----------+------------+
| Host            | Method   | URI        | Name | Action  | Protected | Version(s) | Scope(s) | Rate Limit |
+-----------------+----------+------------+------+---------+-----------+------------+----------+------------+
| api.laravel.app | GET|HEAD | /api/dingo |      | Closure | No        | v1         |          |            |
+-----------------+----------+------------+------+---------+-----------+------------+----------+------------+

and I got result by `php artisan route:list`
+--------+----------+-----+------+---------+------------+
| Domain | Method   | URI | Name | Action  | Middleware |
+--------+----------+-----+------+---------+------------+
|        | GET|HEAD | /   |      | Closure | web        |
+--------+----------+-----+------+---------+------------+

when I opened my browser and visited localhost:8000/dingo/api, server reponsed **404**, I really don't know reasons;

I configured dingo as follows:
```
API_STANDARDS_TREE=vnd
API_SUBTYPE=laravel
API_DOMAIN=api.laravel.app
API_NAME=LaravelApi
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true
API_PREFIX=api
API_VERSION=v1
```

**Comment by bahjaat** [comment]
remove API_DOMAIN from .ENV. Works with me after digging in for a while, or look over here https://github.com/dingo/api/issues/570

**Comment by apaleja** [comment]
as per [documentation](https://github.com/dingo/api/wiki/Configuration#prefixes-and-subdomains), You need to set either `API_DOMAIN` or `API_PREFIX` and not both. here. you are setting up both in env which is causing problem.
