### ISSUE TITLE
Possible to use a newer Fractal version?

### ISSUE THREAD

**Issue by marsd** [dingo/api#1034]
I'm in a situation where I require a new feature from Fractal (dev-master/0.13.x-dev) to be able to use parseExcludes(). Current Dingo 1.0.0-beta3 and dev-master both use Fractal >= 0.12. 

I just want to know if it's possible to force Dingo to use the newer Fractal, and what possible repercussions are there?

Additionally, if it's highly not-recommended to use Fractal dev-master, does anyone know a way to override a transformer's defaultIncldues?

**Comment by jasonlewis** [comment]
Will look at the latest changes to Fractal soon and try to get them incorporated.

**Comment by neoighodaro** [comment]
Did this ever get implemented?
