### ISSUE TITLE
Transformers not eager loading

### ISSUE THREAD

**Issue by mehrdaad** [dingo/api#1038]
I don't know if this is a problem for fractal or dingo, But I'm to state it here.  
I have 2 models and 2 transformers named ``Collection`` and ``Venue``.  
I get collections with eager loaded venues.  
I have checked if they are eager loaded and they are.  
While eager loading i filter ``venues`` and filter on them and their pivot table.  
My query looks like this:  

    $collections = Collection::where('active', 1)->where('starts_at', '<=', Carbon::now())->where(function ($query) use ($city)
		{
			return $query->where("city_id", $city->getKey())->orWhere('city_id', null);
		})->with(array('venues' => function ($q) use ($venueIds)
		{
    //eager loading and filtering
			$q->wherePivot('starts_at', "<=", Carbon::now())
				->wherePivot('ends_at', '>=', Carbon::now())
				->whereIn('venue_id', $venueIds)
				->take(1);
		}))->orderBy('city_id', 'desc')->orderBy('order')->get();

In my ``CollectionTransformer``, my `defaultIncludes`` is ``venues``.
But in ``includeVenues`` methods I notice that `venues`` are simply called on ``collection`` instance instead of loading the eager loaded and filtered results.  
I don't know if this is a bug or I have done something wrong.  

Please help, tnx.

**Comment by hskrasek** [comment]
@mehrdaad I would need some more context, what do your transformers look like?

Also this issue is old, so if you aren't experiencing this issue anymore, let me know.

**Comment by mehrdaad** [comment]
@hskrasek hi, I don't remember how, but I have solved the problem. tnx
