### ISSUE TITLE
Internal requests include?=XXX don't seem to work

### ISSUE THREAD

**Issue by movostudios** [dingo/api#1040]
Hi ya, thanks for the awesome package. Really nice.

I am having issues getting data when using the include feature. The following returns categories, but not with the products.
~~~
$data = $this->api->get('categories?include=products');

return $data;
~~~

I have tried several alternatives: `->with(['include' => 'products'])`, `->include('products')` plus many others.

If I hit the endpoint normally, it is all good.

Any ideas to what I am doing wrong or a work around?

Cheers

~~~
"laravel/framework": "5.2.*"
"dingo/api": "1.0.x@dev"
~~~

**Comment by tembra** [comment]
Did you have the `relationship` on your models? Categories and Products, I mean?
Did you have `Transformer` for each model?
On each transformer did you have `availableIncludes` array property?
For each `availableInclude` did you have the `include` method for it on the `Transformer`?

Or are you saying that ONLY on Internal Request the `?include=` is not working?

**Comment by jasonlewis** [comment]
The only way you're going to see the transformer included data is by getting the raw response.

```php
$response = $this->api->raw()->get('categories', ['include' => 'products']);
```

This will give you a `Response` instance which you can then use to get the `content`.

Without the `raw` method you'll be getting the untransformed/raw object that you're returning from your controller method.

**Comment by movostudios** [comment]
Super sweet. Just what I need. Thanks very much for both posts.
