### ISSUE TITLE
How to customize response format

### ISSUE THREAD

**Issue by xifat** [dingo/api#1044]
now I use $this->item($user,new UserTransformat) 
return 
`
{
   [
    {
      "user_id": 100009,
      "atie_id": "weixin_o4N8swCarL_aM11wX",
      "weixin": {
        "id": 2,
        "openid": "o5UpHvwxAl8cS7n",
        "nickname": "A-ZY",
        "headimgurl": "http://wx.qlogo.cn/mmopen/ajNVdqHZLLD8bFmgmO7zJQ",
        "sex": "1",
        "unionid": "o4N8swCarL_aM11w",
        "subscribe_time": 1449978617,
        "oper": "1"
      },
      "user": {
        "id": 100009,
        "nick_name": " ",
        "invite_num": 0,
        "last_login_time": "2016-05-30 16:13:09",
        "avatar": null
      }
    }
  ]
}`

but I want return 
`
{
  "hb_third_ouath_users": [
    {
      "user_id": 100009,
      "atie_id": "weixin_o4N8swCarL_aM11wX",
      "weixin": {
        "id": 2,
        "openid": "o5UpHvwxAl8cS7n",
        "nickname": "A-ZY",
        "headimgurl": "http://wx.qlogo.cn/mmopen/ajNVdqHZLLD8bFmgmO7zJQ",
        "sex": "1",
        "unionid": "o4N8swCarL_aM11w",
        "subscribe_time": 1449978617,
        "oper": "1"
      },
      "user": {
        "id": 100009,
        "nick_name": " ",
        "invite_num": 0,
        "last_login_time": "2016-05-30 16:13:09",
        "avatar": null
      }
    }
  ]
}
`

**Comment by tembra** [comment]
You will need to write your own serializer to do that (https://github.com/dingo/api/wiki/Configuration#response-transformer and http://fractal.thephpleague.com/serializers/ at the end of page) or maybe your own listener to morph the response (https://github.com/dingo/api/wiki/Responses#morphing-and-morphed-events).
