### ISSUE TITLE
Error: NotFoundHttpException in RoutesRequests.php line 443:

### ISSUE THREAD

**Issue by felipeardila1010** [dingo/api#1048]
Add lines:

.env
API_DOMAIN=localhost

bootstrap/app.php
$app->register(Dingo\Api\Provider\LumenServiceProvider::class);

routes.php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1',[], function ($api) {
    $api->get('users', 'App\Http\Controllers\ExampleController@show');
});

And nothing.

Help me

**Comment by tembra** [comment]
Did you set the `API_VERSION` on `.env` file?

**Comment by jasonlewis** [comment]
Lumen? Domain routing is not supported in Lumen. Use `API_PREIFX=/` instead.
