### ISSUE TITLE
Creating multiple versions

### ISSUE THREAD

**Issue by emmanesguerra** [dingo/api#1050]
Hi guys, 

I'm having a problem in versioning my project's module.

In the .env file my  API_VERSION is set to v1

> API_VERSION=v1

so all endpoints under this tag is working

> $api->version('v1', function($api) {(
> ...
>)};

but if i change the version to v2, like this

>$api->version('v2', function($api) {
>...
>});

all endpoints under the v2 version, is not working. 

What am I missing?

I'm doing this because a new module is added and we want to put that in version 2. 

Can anyone tell me what to do best.

Regards,

**Comment by emmanesguerra** [comment]
Sorry wrong button. BTW. If the issue has been raised before, please comment the link. Thanks a lot

**Comment by tembra** [comment]
When you change the version to `v2` you also need to do so on `API_VERSION`. Are you doing that?
Only the version set on `.env` file will be available. I guess if you need two or more versions working together you'll need multiple instances of your application running.

**Comment by emmanesguerra** [comment]
I'm so sorry I forgot to update this thread.

I have accessed different version using the ACCEPT Header

for example.

If I wanted to access the endpoints in below version

>$api->version('v2', function($api) {
>...
>});

all i have to do is to set the ACCEPT header like this.

>application/API_STANDARDS_TREE.API_SUBTYPE.TARGET_VERSION+json

To make it more clearer, in case my .ENV settings are like these and I want to access the version v2

>API_STANDARDS_TREE=vnd
>API_SUBTYPE=myapi
>API_VERSION=v1

My ACCEPT header should be 

>application/vnd.myapi.v2+json

For v1 endpoints, you may not include the ACCEPT Header to access the endpoints. 


Regards,
