### ISSUE TITLE
how to add custom actions on exceptions?

### ISSUE THREAD

**Issue by Varun-Varunesh** [dingo/api#1053]
Usually in Laravel we send exception detail to technical team by adding code in render method of handler.php file. How to do this here?

**Comment by tembra** [comment]
I had the same problem of you. I would like to give an application error code for more technical details. So I wrote my own error exception that extends `HttpException` and so put the error codes into `errors` key of `errorFormat` array (see in https://github.com/dingo/api/wiki/Configuration#error-format).

If you want to add stuff for every response, so try to use `Morphing and Morphed Events` (https://github.com/dingo/api/wiki/Responses#morphing-and-morphed-events) maybe you can write your own listener to add your stuff after the response has been morphed.
