### ISSUE TITLE
Response with custom message.

### ISSUE THREAD

**Issue by gantoday** [dingo/api#1059]
now,my code is:

    public function user($id)
    {
        $user = User::find($id);

        return $this->response->item($user, new UserTransformer);
    }

and i get response:

    {
        "data": {
            "id": 1,
            "name": "gantoday"
        }
    }

but i want response be:

    {
        "data": {
            "id": 1,
            "name": "gantoday"
        },
        "message": "get user success",
        "status_code": 200
    }

how to do?please help me.

**Comment by tembra** [comment]
I guess you are using `Fractal` and `DataArraySerializer`, so you need to use `addMeta` or `setMeta` function described here: https://github.com/dingo/api/wiki/Responses#adding-meta-data

It should be like
```php
$meta = array(
    'message' => 'get user success',
    'status_code' => 200
);
$this->response->item($user, new UserTransformer)->setMeta($meta);
```
and the answer will be like
```json
{
    "data": {
        "id": 1,
        "name": "gantoday"
    },
    "meta": {
        "message": "get user success",
        "status_code": 200
    },
}
```
so your stuff will be into JSON's `meta` object. If you dont want that you will need to write your own serializer or even your own transformer and set it on `setAdapter` function. You can find more help in these links:
https://github.com/dingo/api/wiki/Configuration#response-transformer
https://github.com/dingo/api/wiki/Transformers

I hope it helps you.

**Comment by gantoday** [comment]
@tembra but setMeta could not use in array

    $this->response->array()

**Comment by tembra** [comment]
Yeah. I got you. But your example was about `item`.

I had the same problem of you but was for error. I would like to give an application error code for more technical details. So I wrote my own error exception that extends `HttpException` and so put the error codes into `errors` key of `errorFormat` array (see in https://github.com/dingo/api/wiki/Configuration#error-format).

In your case you want to add stuff for every response I guess. So try to use `Morphing and Morphed Events` (https://github.com/dingo/api/wiki/Responses#morphing-and-morphed-events) maybe you can write your own listener to add your stuff after the response has been morphed.
