### ISSUE TITLE
[Laravel 5.1.39] Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by php-it** [dingo/api#1062]
Hi there!

I'm trying to install the Dingo/api package into a Laravel 5.1.39 project by running:

`composer require dingo/api`

However after doing so, I get the following error during the installation:

![error](https://cloud.githubusercontent.com/assets/9900754/16054538/ebf8fed0-326d-11e6-801c-01441b52acf1.png)

Does anyone know what's going wrong here? Thanks.

**Comment by drmyersii** [comment]
See #1060.

**Comment by php-it** [comment]
Thanks for your reply. Do you suggest using:

`composer require drmyersii/dingo-api:v1.0.*`

to install dingo/api to a Laravel 5.1 project?

**Comment by drmyersii** [comment]
It is available if you would like to use it, but I only plan to maintain until dingo/api and dingo/blueprint get to stable versions. I'm currently working on fixing the mentioned issue about API Blueprint generation, but for API uses, it should work as expected. If I get everything working, I will submit a PR to Dingo, but there is no guarantee that they will accept.

**Comment by php-it** [comment]
The installation succeeded, thanks a lot! Do you recommend also updating the `composer.lock` file?

**Comment by drmyersii** [comment]
@php-it the install should have handled that for you automatically, but feel free to update the lock file as well if it didn't!
