### ISSUE TITLE
Issue running api docs command

### ISSUE THREAD

**Issue by arasmit2453** [dingo/api#1065]
[ErrorException]                                                                                                                                                    
 Missing argument 4 for Dingo\Blueprint\Blueprint::generate(), called in C:\Users\developer\Google Drive\Caag\caag\vendor\dingo\api\src\Console\Command\Docs.php on  
 line 95 and defined

**Comment by drmyersii** [comment]
@arasmit2453 can you provide more information, please? Package version, code context, and possibly more explanation would all help. Thanks!

**Comment by arasmit2453** [comment]
Yes the issue is when running the command php artisan api:docs

there is one function that needs 4 parameters but only receive 3! 

Check this! https://github.com/dingo/api/blob/v1.0.0-beta3/src/Console/Command/Docs.php#L95

Is fixed on master but there is no a release for this!

**Comment by drmyersii** [comment]
You will probably have to wait until they decide to create another release. I ran into this same issue, and I ended up just forking the project into my own maintained copy, `drmyersii/dingo-api`. Feel free to use it with `composer require drmyersii/dingo-api` if you want. I plan to keep it maintained until the official stable release for `dingo/api` is out. Good luck!

**Comment by jasonlewis** [comment]
Should be working fine with latest `dingo/api` commits.

**Comment by kvlknctk** [comment]
Its not work.

**Comment by sliecer** [comment]
Its not working for me

**Comment by wayne5w** [comment]
Not working for me either.

**Comment by devpradip** [comment]
Also working for me.

**Comment by johannesschobel** [comment]
does not work for me..

**Comment by A7maDev** [comment]
Same issue, doesn't work!

**Comment by A7maDev** [comment]
same issue, doesnt work
[Solution]
vendor/dingo/api/src/Console/Command/Docs.php content replaced with https://github.com/drm2/dingo-api/blob/master/src/Console/Command/Docs.php
