### ISSUE TITLE
Error on transforming an array

### ISSUE THREAD

**Issue by jhayiwg** [dingo/api#1066]
Hello sorry I`m only new in laravel.

I have an array result from etrepat/baum(nested library) and I want to transform:
```php
		$systems = collect( System::getNestedList('name', null, $seperator));
		$collection = $systems->transform(function ($item, $key) {
			return array('id'=> $key, 'name'=>$item);
		})->values();
		return $this->response->collection( $collection , new SystemNestedTransformer, [] );
```
but I`m getting this error:
{
  "message": "get_class() expects parameter 1 to be object, array given",
  "status_code": 500,

if I use fractal manager it works fine, please see the code below.

	$fractal = new Manager();
        $fractal->setSerializer(new JsonApiSerializer);
		$seperator = '';
		if( $request->get('seperator') ) {
			$seperator = $request->get('seperator');
		}

		$systems = collect( System::getNestedList('name', null, $seperator));
		$collection = $systems->transform(function ($item, $key) {
			return array('id'=> $key, 'name'=>$item);
		})->values();

		$resource = new Collection($collection->all(), function(array $system) {
			return [
		        'id'      => (int) $system['id'],
		        'title'   => $system['name'],
		        'links'   => [
		            [
		                'rel' => 'self',
		                'uri' => '/system/'.$system['id'],
		            ]
		        ]
		    ];
		}, 'test');

	return	$fractal->createData($resource)->toArray();

I hope you can help me. Many thanks in advance :)

**Comment by tembra** [comment]
Put your app into debug mode and paste all lines below
```
"message": "get_class() expects parameter 1 to be object, array given",
"status_code": 500,
```
So we can give you more help.
And please, paste all this stuff into code bracket :)

**Comment by jasonlewis** [comment]
`$collection` is an instance of Laravel's `Collection` class, correct?
