### ISSUE TITLE
Transformers changes relationship camel case to lowercase with underscores

### ISSUE THREAD

**Issue by artukrap** [dingo/api#1075]
Controller

        $users = User::with('actualUser')->paginate(30);
		if($users)
    		return $this->response->paginator($users, new UserTransformer);

Transformer
```
public function transform(User $user):array
    {
        return [
            'id'            => (int) $user->id,
            'username'      => $user->actual_user['username'],
            'name'          => $user->actual_user['name'],
            'surname'       => $user->actual_user['surname'],
            'email'         => $user->actual_user['email'],
        ];
    }
```

I think its wrong, that transformer changes type of my variables from **actualUser** to **actual_user**.

**Comment by jasonlewis** [comment]
It shouldn't, did you try using the camelCase variant?

**Comment by artukrap** [comment]
Yes, but it seems its laravel bug. Sorry.

**Comment by jasonlewis** [comment]
I gave it a quick try on my side and it seemed to maintain the casing. Latest 5.2.

**Comment by artukrap** [comment]
Whoa, thats even more weirder. Ok, fine, thanks for your help.
