### ISSUE TITLE
Can't install dingo/api on a fresh install of Laravel

### ISSUE THREAD

**Issue by pongz79** [dingo/api#1076]
Hi,

I've tried to install this package as per the documentation on a fresh laravel installation and couldn't.
Here is the response that I get when trying to run composer require dingo/api:1.0.x@dev:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install dingo/api 1.0.x-dev
    - Conclusion: don't install dingo/api v1.0.0-beta3
    - Conclusion: remove laravel/framework v5.2.39
    - Installation request for phpdocumentor/reflection-docblock (locked at 3.1.0) -> satisfiable by phpdocumentor/reflection-docblock[3.1.0].
    - Conclusion: don't install laravel/framework v5.2.39
    - dingo/api v1.0.0-beta1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - dingo/api v1.0.0-beta2 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.39
    - Installation request for laravel/framework (locked at v5.2.39, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.39].
    - Installation request for dingo/api 1.0.x@dev -> satisfiable by dingo/api[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta2, v1.0.0-beta3].

Installation failed, reverting ./composer.json to its original content.

Can anyone help?

Thanks in advance.

**Comment by drmyersii** [comment]
See #1062.

**Comment by Selimcse98** [comment]
Add "phpdocumentor/reflection": "3.x@dev" under "require": { } in composer.json and run a composer update

"require": {

    "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "phpdocumentor/reflection": "3.x@dev"
    },

$ composer update
$ composer require dingo/api:1.0.x@dev

after successful command this will add "dingo/api": "1.0.x@dev" under require.

"require": {

        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "phpdocumentor/reflection": "3.x@dev",
        "dingo/api": "1.0.x@dev"
    }

**Comment by ratulcse27** [comment]
Thanks @Selimcse98

**Comment by davidmureithi** [comment]
Thank you @Selimcse98
