### ISSUE TITLE
None of php artisan commands are working

### ISSUE THREAD

**Issue by ajeeshcitrus** [dingo/api#1077]
I updated dingo to v1.0.0-beta3 version. After words, all my php artisan commands are failing with the following exception
```

 [Tymon\JWTAuth\Exceptions\JWTException]         
  The token could not be parsed from the request 
```

When I checked the log I could see that my API controllers had

```
$user               = JWTAuth::parseToken()->authenticate();
        $this->users_id     = $user->users_id; 
```

But those controllers are suppose to be run during an API call and not when I do a artisan command. This was working fine till now. But after updating composer, the latest dingo version made this like this.

I need quick help as my product is going live soon and I am stuck with this on the final day.

Please help! I will be very thankful for that!

**Comment by edbentinck** [comment]
Did you try downgrading dingo to see if that fixed it? Are you sure you didn't update other composer packages at the same time? For instance, if you used `composer update` then other packages, like `tymon/jwt-auth`, may have updated too.

**Comment by jasonlewis** [comment]
Are you doing that in the constructor?

You should be using the `api.auth` middleware to authenticate requests.

**Comment by ajeeshcitrus** [comment]
I am authenticating the request using the following middleware **[ 'middleware' => ['jwt.auth']]** But 
**$user               = JWTAuth::parseToken()->authenticate();
        $this->users_id     = $user->users_id;**  is used to retrieve the users_id from the token and not for authenticating. This was working till now, but the composer update had fetched the latest version and from then on this issue is coming.

There are around 15 controllers where I am fetching the users_id from the token by parsing it. Why is this error coming up?

**Comment by ajeeshcitrus** [comment]
@edbentinck  I tried downgrading, but it was not happening because of the package included with it (blueprint).
