### ISSUE TITLE
How to overwrite dingo's Handler exception class?

### ISSUE THREAD

**Issue by maojindao55** [dingo/api#1078]
I use lumen + dingo,
 now I want to custom handler exception, but the exception is handled by dingo.
so i want to extends the class and overwrite its method,  How do to do?

**Comment by tembra** [comment]
You need to register a custom error handle as stated on Dingo API documentation at https://github.com/dingo/api/wiki/Errors-And-Error-Responses#custom-exception-responses

**Comment by maojindao55** [comment]
@tembra think your reply, bwt, do you have a demo or a detail about the way?

**Comment by tembra** [comment]
Hello,
The documentation is clearly.
If you need to handle a custom exception you should register a handler on `app.php`. Like this:
```php
app('Dingo\Api\Exception\Handler')->register(function (Namespace\For\The\Specific\Exception $exception) {
    //do whatever you want with the $exception
    //finally you need to return a response on API format, maybe JSON?
    return Response::make(['error' => 'Hey, what do you think you are doing!?'], 401);
});
```

In this example we are handle a specific exception: `Namespace\For\The\Specific\Exception`. If you want to handle all exceptions you just need to use `\Exception` instead. So your callback function registered will be handle for every exception.

**Comment by hskrasek** [comment]
@maojindao55 @tembra's suggestions are the best way to handle this. If you want to create a custom handler class still, you'd want to create a handler that extends dingos handler, and then re-instance it in the IoC container.

**Comment by hskrasek** [comment]
Gonna close this out for now though, feel free to re-open if you're still having an issue
