### ISSUE TITLE
why using 'composer update ' makes dingo back to old release v1.0.0-beta3

### ISSUE THREAD

**Issue by GreatYYX** [dingo/api#1084]
Hi,

I was using dev version of dingo, today when I execute 'composer update', dingo' version points to the old release v1.0.0-beta3 on https://packagist.org, and the method api/src/Http/Response/Factory::created() in old version doesn't support setting response content.

My compose.json:
```
"require": {
　　．．．
        "dingo/api": "1.0.*@dev"
　　．．．
},
```

![2162835595 chatroom_1466653262193_2](https://cloud.githubusercontent.com/assets/8329846/16291996/d472daec-38c1-11e6-9932-9a44932984de.png)

How could I point my local dingo to the newest version?

Thank you

**Comment by GreatYYX** [comment]
There are some different solutions:
1. set `"minimum-stability": "dev",` to root of composer.json, but it will also cause all the package by using dev.
2. use a fixed commit, `"dingo/api": "dev-master#8cd1a6c"`
3. explicitly use dev version of dingo/blueprint (because dingo/api needs dev version of dingo/blueprint

**Comment by crynobone** [comment]
@GreatYYX you can use minimum stability dev with prefer stable true.

```json
    "minimum-stability": "dev",
    "prefer-stable": true
```

**Comment by GreatYYX** [comment]
Hi @crynobone , thanks for your reply. Your solution works.
Actually I tried to add `prefer-stable` and `minimum-stability`, but at that time I still got the stable version of dingo/api when I set it as ` "dingo/api": "1.0.*@dev"`. Does that mean `1.0.*@dev` is not the same as `dev-master`? I originally think they are same due to the stability flag.

**Comment by crynobone** [comment]
>  I originally think they are same due to the stability flag.

With `1.0.*@dev`, it would still consider that `1.0.0-BETA2` is a valid resolution, as for now I'm sticking my deps to `dev-master` until dingo/api has `v1.0.0` tagged.

**Comment by hskrasek** [comment]
Looks like this was worked out. Hoping to have a v1.0.0 tagged soon, which should alleviate issues like this. Closing out
