### ISSUE TITLE
Fatal error with throttling in the config file

### ISSUE THREAD

**Issue by stueynet** [dingo/api#1087]
routes.php:
```
$api->version('v1', ['middleware' => ['auth', 'api.throttle']], function ($api) {
...
```

config/api.php

```
    'throttling' => [
            'limit' => 100, 
            'expires' => 5
    ],
```

Error:
```
{"message":"Fatal error: Call to a member function match() on array","status_code":500}
```

Works fine if I inline the throttle parameters in the route.

**Comment by hskrasek** [comment]
Thats because the throttling value in the config is used to define custom throttling classes: https://github.com/dingo/api/wiki/Rate-Limiting#custom-throttles
