### ISSUE TITLE
Library is built under the assumption PDO fetch is FETCH_CLASS

### ISSUE THREAD

**Issue by themogly** [dingo/api#1089]
if you set  'fetch' => PDO::FETCH_ASSOC, it will break the library.

**Comment by hskrasek** [comment]
@themogly Where are you seeing where this assumption takes place? Could you give me an example of where it would break?

**Comment by themogly** [comment]
you can try it yourself..

{
  "message": "Trying to get property of non-object",
  "status_code": 500,
  "debug": {
    "line": 44,
    "file": "/vagrant_data/html/mynearyou/api/vendor/lucadegasperi/oauth2-server-laravel/src/Storage/FluentAccessToken.php",

**Comment by hskrasek** [comment]
@themogly That error is coming from the `lucadegasperi/oauth2-server-laravel` package. So I feel its not an assumption made by dingo/api. I'd raise this concern over at https://github.com/lucadegasperi/oauth2-server-laravel/issues
