### ISSUE TITLE
Wiki Clarification

### ISSUE THREAD

**Issue by kevinkhill** [dingo/api#1090]
Hello,
I'm not sure if it is just me not reading carefully, or maybe other people have had this same issue.

When I read this section:
#### JSON Web Tokens (JWT)

This package makes use of a 3rd party package to integrate JWT authentication. Please refer to the [`tymon/jwt-auth`](https://github.com/tymondesigns/jwt-auth) GitHub page for details on installing and configuring the package.

Once you have the package you can configure the provider in your `config/api.php` file or in a service provider or bootstrap file.

```php
'jwt' => 'Dingo\Api\Auth\Provider\JWT'
```

```php
app('Dingo\Api\Auth\Auth')->extend('jwt', function ($app) {
   return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

I had attempted to do both, not realizing they were the same thing. This gave me the ugly error of:
```php
Type error: Argument 1 passed to Dingo\Api\Auth\Auth::__construct() must be an instance of Dingo\Api\Routing\Router, instance of Tymon\JWTAuth\JWTAuth given, called in [redacted]/app/Providers/AppServiceProvider.php on line 22
```  
Once I removed the call to the extend method block from my service provider, and left just the ```'jwt' => 'Dingo\Api\Auth\Provider\JWT'``` line in the config, everything started working again.

Anyways, I propose modifying each section that is worded in that way, to have one minor change, like this:
#### JSON Web Tokens (JWT)

This package makes use of a 3rd party package to integrate JWT authentication. Please refer to the [`tymon/jwt-auth`](https://github.com/tymondesigns/jwt-auth) GitHub page for details on installing and configuring the package.

Once you have the package, you can configure the provider in your ```config/api.php``` file:
```php
'jwt' => 'Dingo\Api\Auth\Provider\JWT'
```
OR in a service provider / bootstrap file:
```php
app('Dingo\Api\Auth\Auth')->extend('jwt', function ($app) {
   return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

Thoughts?

**Comment by Deleugpn** [comment]
I didn't have this problem when I was first learning it because of the **or** word at `your config/api.php file or in a service provider or bootstrap file.`

But clarifications on Wiki are always a good thing, imo. 

I think it would be good to have a Git Repository for the documentation, so we could pull request it.

**Comment by kevinkhill** [comment]
It could have been that I just read over it too fast, and thinking I did it right, was getting frustrated. Upon re-reading it, I did catch that it said **or** and then it made sense. I just thought it could be helpful to break it up more.

**Comment by Deleugpn** [comment]
Although I don't have the exact issue that the OP had, I'm on this path of Wiki Clarification thing.

In my project I don't have any of the providers configured (`config/api.php` **or** `AppServiceProvider`) and yet, my project works fine. Why is that? What does this provider offer? When is it necessary? Why do I have a working project without any of this?

**Comment by hskrasek** [comment]
Will take a look at documentation and add clarification where needed.

**Comment by hskrasek** [comment]
@Deleugpn Not sure what you mean by the providers, if you mean the provider for Dingo or the one for JWT.

**Comment by Deleugpn** [comment]
@hskrasek I meant to say the JWT providers. The topic of discussion is about using one of the following snippet to setup the provider:

```
'jwt' => 'Dingo\Api\Auth\Provider\JWT'
```

or 

```
app('Dingo\Api\Auth\Auth')->extend('jwt', function ($app) {
   return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

What does this actually do? I'm not using any of them and I've been doing just fine in my project. What am I missing by not having one of those setup?

**Comment by hskrasek** [comment]
@Deleugpn If you specify the auth provider via one of those two methods, it'll work in conjunction with the `api.auth` middleware that will automatically authenticate the request for you.

**Comment by Deleugpn** [comment]
That seem to make sense, up to this point I haven't used that middleware, only the `Helpers` trait, `user` function.

**Comment by hskrasek** [comment]
I've reviewed the documentation for Authentication, and the section [Protecting Endpoints](https://github.com/dingo/api/wiki/Authentication#protecting-endpoints) goes into detail about using the `api.auth` middleware to authenticate the request, and from that section it leads into getting the authenticated user from the request.

I can't really add anything else, so I'm gonna close this out.
