### ISSUE TITLE
Blueprint members in parameters

### ISSUE THREAD

**Issue by mohammedibrahim** [dingo/api#1092]
I need to know what is the right syntax to enter a members for a paramater members

I tried 

  @Parameter("role_name", type="string", required=true, description="The name of role to list users by.", members="foo,bar") 

but it gives me an error that it must be an array. How I should fix it ?

**Comment by mirzap** [comment]
@mohammedibrahim check this conversation https://github.com/dingo/blueprint/pull/5

**Comment by hskrasek** [comment]
@mohammedibrahim The linked PR should answer your question for you. Closing this out
