### ISSUE TITLE
Issue with API_PREFIX/API_VERSION having characters other than [A-Za-z0-9] & "."

### ISSUE THREAD

**Issue by tintin64** [dingo/api#1098]
The Regular expression in dingo/api/src/Http/Parser/Accept.php doesnt match pattern when "-" is present in the version or prefix. "-" is also a valid character for url so the pattern can be changed as mentioned below.

        $pattern = '/application\/'.$this->standardsTree.'\.('.$this->subtype.')\.([\w\d\.\-]+)\+([\w]+)/';

Please help. Thanks.

**Comment by tintin64** [comment]
As a workaround we can override two classes to get this working before library fix. 
Create a class
   **App\Http\Parser\Accept** which extends **Dingo\Api\Http\Parser\Accept** 
   override method **parse** and change the regex according to your requirement.
and then create another class
   **app/Providers/DingoServiceProvider** extends **Dingo\Api\Provider\LaravelServiceProvider**
   override methods **boot** and **registerHttpValidation** and replace the Dingo\Api\Http\Parser\Accept usage with App\Http\Parser\Accept

This worked for me in my case where my **API_PREFIX** was "**web-api**".

Thanks,
Sandeep

**Comment by hskrasek** [comment]
Will look into this @tintin64

**Comment by hskrasek** [comment]
@tintin64 Are you sure this issue affects API_PREFIX? The `Accept` parser only cares about the standards tree, subtree and version.

**Comment by tintin64** [comment]
Yes, it does affect API prefix too.

**Comment by hskrasek** [comment]
@tintin64 Will have to look at it further in the morning. If you have an example/more context that be helpful. If you had a failing unit test, that'd be even better.

**Comment by tintin64** [comment]
sure. will attach it asap.
