### ISSUE TITLE
Start using dingo/api for Laravel 5.1

### ISSUE THREAD

**Issue by jgardezi** [dingo/api#1106]
Hi @drmyersii

I am using drmyersii/dingo-api package as a replacement for dingo/api package. I have switched because I was getting issue similar to this one https://github.com/dingo/api/issues/1062.

Is it stable now to revert back to dingo/api package for Laravel 5.1 version?

Kind regards,
Javed Gardezi

**Comment by hskrasek** [comment]
@jgardezi The package will run on both Laravel 5.1 and 5.2

**Comment by jgardezi** [comment]
@hskrasek Thank you for the update. I have update my composer and so far it running smoothly!!
