### ISSUE TITLE
Standards Tree Clarification

### ISSUE THREAD

**Issue by SERVANT14** [dingo/api#1110]
Continuing from #638, there doesn't seem to be much on the Web about what each of these standards trees are. I'm specifically having trouble with what it means for an API to distributed commercially. I also am not sure what it means for an API to be distributed at all :).

I'm guessing `vendor` means an API that's meant to be utilized by any number of 3rd parties and `personal` means an API meant to only be used by the application(s) _you_ are building. Is that correct?

**Comment by Deleugpn** [comment]
At the end of the day, I just assumed these are more of a judicial data than development. It may be more related to patent, copyright and stuffs like that than programming features. I might be totally and completely wrong, but in order to move on and work I just assumed `x`.

**Comment by hskrasek** [comment]
@SERVANT14 To be honest, I was looking at this and dont think it's as clear as it could be. Gonna update the docs to try and clarify this.

**Comment by SERVANT14** [comment]
Excellent! Thanks so much.

**Comment by hskrasek** [comment]
Alright @SERVANT14 and @Deleugpn. Tried to dig up more information, and didn't get far. I can't even find anything from the mailing list relating to Github registering their vnd.github stuff. So, the descriptions in the Wiki are as close as we can get. 

I'm thinking I can add a note that says when in doubt, you could always use the `x` standards tree. But at the end of the day, you could technically use whatever and be fine. Theres not really a media type police to get onto you for picking the "wrong one"

**Comment by hskrasek** [comment]
I updated the wiki to include a note about using `x` as a safe bet. If I find more information, I'll update the wiki. In the mean time, I'm gonna close this out, always open to re-opening this for further discussion though.

**Comment by SERVANT14** [comment]
Thanks hskrasek! I think that addition will be helpful.
