### ISSUE TITLE
Form Request Validation with additional parameter?

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#1111]
Hello,

I have this API response coming back from the user controller's store method when validation fails:
```
{
  "message": "422 Unprocessable Entity",
  "errors": {
    "email": [
      "The email field is required."
    ]
  },
  "status_code": 422
}
```

The store method looks like this:
```
public function store(StoreUserRequest $request){
    // The incoming request is valid...
    // Continue here...
}
```
The StoreUserRequest looks like this:
```
namespace App\Http\Requests;
use Dingo\Api\Http\FormRequest;

class StoreUserRequest extends FormRequest {
    public function authorize() {
        return true;
    }

    public function rules() {
        return [
          'email' => 'required|email',
        ];
    }
}
```
I have no idea how to add the `"error": true` to the API response, so it looks like this:
```
{
  "error": true, <-- trying to add this whenever there is any form request validation errors...
  "message": "422 Unprocessable Entity",
  "errors": {
    "email": [
      "The email field is required."
    ]
  },
  "status_code": 422
}
```
I typically do this to get `"error": true` in my custom responses:
```
if(!$user) {
    return $this->error('No user exists.');
}
```
But since the response comes out automatically with the errors for the form request validation, I am not sure how/where to wrap the response with the error.

Any idea how to get it to return the `"error": true` with the response?

**Comment by marsd** [comment]
Why not just check for `errors` not null and `status_code` = 422?

**Comment by MovingGifts** [comment]
It's a standard way I've been handling my errors, so I need to inject the "error": true to be part of the response.

**Comment by iamrutvik** [comment]
Configure your  error format in api.php config file.

`errorFormat' => [
            'error' => false,
            'message' => ':message',
            'errors' => ':errors',
            'code' => ':code',
            'status_code' => ':status_code',
            'debug' => ':debug'
    ]`

**Comment by Deleugpn** [comment]
Side note on this: whenever `status_code` is not 200, your `error` flag will be `true`. If this assertion holds up, you may want to consider dropping your standard and assuming a new one where you just check the  `status_code`.

**Comment by MovingGifts** [comment]
Thank you guys, will try to work with the standard 200 ok way!
