### ISSUE TITLE
SIGSEGV - core dumped when getting authenticated user

### ISSUE THREAD

**Issue by feelinc** [dingo/api#1114]
After using below code :

`$user = app('Dingo\Api\Auth\Auth')->user();`

Result below error in PHP-FPM log :

`WARNING: [pool www] child 29079 exited on signal 11 (SIGSEGV - core dumped) after 695.737992 seconds from start`

Routes : 

```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', [
    'middleware' => 'api.throttle', 
    'limit' => 100, 
    'expires' => 1
], function ($api) {

    $api->group(['middleware' => 'api.auth'], function ($api) {
        $api->get('orders', 'App\Http\Controllers\Api\v1\Order@getList');
        $api->get('orders/{id}', 'App\Http\Controllers\Api\v1\Order@getIndex');
    });

});
```

Controller : 
- App\Http\Controllers\Api\v1\Order extends Controller

`$user = app('Dingo\Api\Auth\Auth')->user();` called from parent "Controller" constructor

Everything fine if called from  App\Http\Controllers\Api\v1\Order

Laravel 5.2.x
Using PHP-FPM 7.0.8 Ubuntu

**Comment by hskrasek** [comment]
This seems to be the same issue that was raised by #1013.
