### ISSUE TITLE
ability to change the order of response data

### ISSUE THREAD

**Issue by acidjazz** [dingo/api#1115]
For general preference I would love to be able to move my meta above my data, this will make testing and inspecting my calls a lot easier, for example:

![image](https://cloud.githubusercontent.com/assets/967369/16814845/723eb950-48ec-11e6-977f-6622383c2dcd.png)

I'd love to somehow get this on top, is there any way possible?

**Comment by acidjazz** [comment]
bumping for hope, still would really like to know if this is possible

**Comment by hskrasek** [comment]
Not something we plan on doing, that order is controlled by fractal (based on the response, looks like you're using fractal transformers). You could always manually interact with fractal, and re-order the response array before creating the response.

**Comment by acidjazz** [comment]
@hskrasek yea i figured it wouldn't after the lack of response of 1 month, so i've moved on to better pastures where style is not restricted to the teams personal preference
