### ISSUE TITLE
I`m trying to install on a fresh new laravel 5.2, but not working.

### ISSUE THREAD

**Issue by richardfeliciano** [dingo/api#1116]
Problem 1
    - Installation request for dingo/api ^0.10.0 -> satisfiable by dingo/api[v0.10.0].
    - Conclusion: remove laravel/framework v5.2.39
    - Conclusion: don't install laravel/framework v5.2.39
    - dingo/api v0.10.0 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.39
    - Installation request for laravel/framework (locked at v5.2.39, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.39].

When it cames a version to 5.2?

**Comment by luisfer7192** [comment]
Same problem here

**Comment by oldskool73** [comment]
As covered in the install instructions, you need to add :
`"minimum-stability": "dev",`
to your composer.json, then
`composer require dingo/api:1.0.x@dev` will work fine.

**Comment by luisfer7192** [comment]
<img width="1277" alt="captura de pantalla 2016-07-14 a las 8 07 24 p m" src="https://cloud.githubusercontent.com/assets/13595748/16860526/a1be7324-49fe-11e6-9e18-4ca2a2e6fbe6.png">

**Comment by oldskool73** [comment]
@luisfer7192 sorry don't know what to suggest then, I had the same error literally 10 minutes before I saw this issue and doing that fixed it for me.

**Comment by cedamorim** [comment]
I first installed the Laravel (with "laravel new project-name" command), then in the composer.json I added the line "dingo / api": "1.0.*@dev" within the "require" and performed "composer update" and work (when I try from the command line does not work).


composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
		"dingo/api": "1.0.*@dev"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "laravel/homestead": "^3.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by lhmerino** [comment]
@cedamorim works for me

**Comment by luisfer7192** [comment]
I reinstall laravel in a ubuntu and i use

`"require": {
    "dingo/api": "1.0.*@dev"
}`

with out composer comand and it work fine.

In the Mac doent work.

**Comment by richardfeliciano** [comment]
It`s installed, but when i try to configure end points it give me this error:

BindingResolutionException in Container.php line 748:
Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Routing\Router].

-- 
Richard W. Feliciano

On July 14, 2016 at 3:01:41 PM, Luis Fernando Salazar Buitrago (notifications@github.com) wrote:

Same problem here

**Comment by dsposito** [comment]
@richardfeliciano I'm having the same issue with Lumen 5.2. Were you able to figure out a fix?

**Comment by dsposito** [comment]
@richardfeliciano Be sure to add the following to your bootstrap/app.php:

`$app->register(Dingo\Api\Provider\LumenServiceProvider::class);`

**Comment by hskrasek** [comment]
@richardfeliciano This should be working, are you still running into this issue?

**Comment by skcin7** [comment]
I was just getting a very similiar `BindingResolutionException` with message:
    `Target [Tymon\JWTAuth\Providers\JWT\JWTInterface] is not instantiable.`

Took me FOREVER but I fixed it by changing the order of my providers in `config/app.php`, by importing BOTH `Dingo\Api\Provider\LaravelServiceProvider` and `Tymon\JWTAuth\Providers\JWTAuthServiceProvider` BEFORE all of my other providers. Now it works like a charm.

The DingoAPI docs _do_ say to include the `Dingo\Api\Provider\LaravelServiceProvider` before the other providers, but it doesn't say anything about the order to bring in the `JWTAuthServiceProvider`. So this really is not an obvious thing.

Hope this helps others. Good luck.

**Comment by konohanaruto** [comment]
@luisfer7192 works for me. Thanks.
