### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by matthijsotterloo** [dingo/api#1121]
Hi everyone,

I was wondering if there's some kind of demo available to download and start right away?
So with some example endpoints and stuff?

Thanks!

**Comment by kharysharpe** [comment]
Hey @matthijsotterloo ,

Check these out

Laravel:
https://github.com/joselfonseca/laravel-api

Lumen:
https://github.com/0plus1/lumendingojwtapi

**Comment by hskrasek** [comment]
@matthijsotterloo No plans to add a demo at the moment, maybe further down the line? In the meantime, it looks like the examples @kharysharpe provided should get you headed in the right direction.

**Comment by kharysharpe** [comment]
You can check this out as well
https://github.com/kharysharpe/laravel-api-first-starter-kit
