### ISSUE TITLE
error register

### ISSUE THREAD

**Issue by luisfer7192** [dingo/api#1122]
I have and error when i try to use app('Dingo\Api\Exception\Handler')->register en el AppServiceProvider

```    
public function register()
{
    app('Dingo\Api\Exception\Handler')->register(function (ValidatorException $exception) {
        return \Response::make(['message' => 'Error de validación, corrija los siguientes errores:', 'errors' => $exception->getMessageBag()], 422);
    });
}
```

![seleccion_011](https://cloud.githubusercontent.com/assets/13595748/16933330/1c9cfaaa-4d12-11e6-98b8-e67d7ee3398b.png)

Could you help me please

**Comment by hskrasek** [comment]
@luisfer7192 Did you register the service provider for the package in app.php? If so, does it come before or after your `AppServiceProvider`? Or are you no longer having this issue?
