### ISSUE TITLE
Translate exceptions messages

### ISSUE THREAD

**Issue by oleynikd** [dingo/api#1123]
Hi,

First of all, thanks for such a great tool!

Is it possible to translate exception messages like:
`'You have exceeded your rate limit.'` [here](https://github.com/dingo/api/blob/b0491204a4f9c6ac305f344a0d30954175002364/src/Http/Middleware/RateLimit.php#L67)? 

Thanks.

**Comment by hskrasek** [comment]
@oleynikd When you say translate, do you mean utilize laravels translators? So that you could customize the message, etc.?

**Comment by oleynikd** [comment]
I guess this would be handy...

**Comment by hskrasek** [comment]
@oleynikd Was mainly asking what you meant, since wasn't sure if you meant that or translating to other languages. Either way, same need. 

Can't wait v1.0.0 will have it, but will keep it on the radar
