### ISSUE TITLE
artisan api:docs not working in latest version (Laravel 5.2)

### ISSUE THREAD

**Issue by tomcoonen** [dingo/api#1126]
[ErrorException]
Missing argument 4 for Dingo\Blueprint\Blueprint::generate(), called in /home/vagrant/Code/hofweb/vendor/dingo/api/src/Console/Command/Docs.php on line 95 and defined

The 4th parameter (includePath) is required but not used by the command handler, adding 'null' as a 4th parameter fixes the doc generation at least.

**Comment by georaldc** [comment]
This was fixed sometime after the latest tagged release (https://github.com/dingo/api/commit/5e1c0839067e82fdfa8472eb2e3f024a4c3b96ea) so until a new tag gets created, I guess one could stick to the master branch for now.
