### ISSUE TITLE
Questions regarding eager loading, paginating and resulting responses

### ISSUE THREAD

**Issue by georaldc** [dingo/api#1128]
So this is my first time using laravel and dingo and I have some question about whether I'm doing things right or not and if I'm understanding things right or not. So I wanted to return a collection of resources and figured I would eager load relations *if* they were requested via the includes query string parameter. So in my controller, I have the following:

```
$input = Request::input();
$includes = isset($input['include']) ? $input['include'] : null;
$paginationSize = 25;
if ($includes) {
    $products = Product::with(explode(',', $includes))->paginate($paginationSize);
} else {
    $products = Product::paginate($paginationSize);
}

return $this->paginator($products, new ProductTransformer());
```

Seems to work well but then I realized that Dingo\Api\Transformer\Adapter\Fractal does it's own eager loading as well by default. Does that mean that I didn't have to manually eager load on my controller?

Second question: is it normal that responses get built out twice? Having my eager loaded controller code actually made things slower as I was doing some random endpoint testing with large amounts of data being returned. I noticed that it was because the Factory::paginator() method creates a new Response class (and thus applies the morphToJson() method on my large content), then later calls Router::prepareResponse() which again recreates the Response object using Response::makeFromExisting() (and again calls morphToJson()). Didn't have time to look into it further but why would the Dingo Response need to rebuild itself if Response::makeFromExisting and/or Response::makeFromJson already have a working copy of the current response passed to them?

**Comment by georaldc** [comment]
Must have missed the wiki block about eager loading being a feature, so I guess that answers my first question.

**Comment by hskrasek** [comment]
@georaldc For you're first question, yea looks like you found that the package automatically handles eager loading for you. As for the second one, thats something I need to dig into more and see if I can resolve that.
