### ISSUE TITLE
Error in installation with Lumen

### ISSUE THREAD

**Issue by ps92** [dingo/api#1129]
![image](https://cloud.githubusercontent.com/assets/8271659/17080468/d5f8a6da-514e-11e6-86c6-a3f2b4ebc746.png)

Is there I can do something about it?

**Comment by Jordy-A** [comment]
It doesn't work with the composer require-command. Just add it manual to the json file `"require": { "dingo/api": "1.0.*@dev" }` and run composer update.

**Comment by ps92** [comment]
wow! I didn't think it that way! thanks @Jordy-A !
