### ISSUE TITLE
Weird 405 error when missing / on post to clients

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#1130]
I am totally freaked out by this.

Somehow, I get a 405 for a `post` request to `domain.com/clients` (the method I think shows get), however, I just figured out that a request to `domain.com/clients/` (notice the / in the end) works. This only happens for `clients` other post endpoints are fine and for e.g. `client_` works as well. 

Any Idea why? Is this a dingo bug, or did I do something wrong in my code? 405 is **NOT** thrown by my code. It is somehow thrown in the LumenController or even before. It also gets thrown if I add an anonymous function to the post route.

**Comment by lucasmichot** [comment]
@lukasoppermann , it seems you try to use a method (verb) which is not allowed, thus the raising of `\Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException`

**Comment by lukasoppermann** [comment]
Hey @lucasmichot can you explain this in more detail? I did notice that when using `$this->getMethod()` in the request it returns `GET` instead of post. However, why would it only do so for this one endpoint?

The endpoint is `POST clients` and there is no `GET clients` (only `GET clients/{id}`) so it would make sense, that a `405` is raised, if the request is detected as `GET`.

However I have been sending the Request via Postman so I am certain it was actually send as Post. 

Could this be messed up by some middleware that dingo introduces? Any ideas what I could check?

**Comment by Deleugpn** [comment]
Can you disclose your `routes.php` so we can try to locate the problem?

**Comment by lukasoppermann** [comment]
Sorry, I was on vacation with very spotty internet.

```
<?php

Debugbar::startMeasure('routes','Routing');
Route::group(['prefix' => env('APP_PREFIX')], function () {
    // login
    Route::get('/login','Auth\AuthController@showLoginForm');
    Route::post('/login','Auth\AuthController@login');
    Route::get('/logout','Auth\AuthController@logout');
    // Reset password
    Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
    Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
    Route::post('password/reset', 'Auth\PasswordController@reset');
    //
    Route::group(['middleware' => ['auth','isSetup']], function(){

        Route::get('/','Dashboard@index');

        Route::group(['namespace' => 'Collections'], function() {
            // Route::get('/collections', 'Collections@index');
            Route::post('/collections', 'Collections@store');
            Route::patch('/collections/{id}', 'Collections@update');
            Route::delete('/collections/{id}', 'Collections@delete');

            Route::get('/collections/{collection}/{page?}', 'Collections@show');
        });
        // Images
        Route::put('/images', 'Images@upload');
        Route::post('/images', 'Images@upload');
        Route::delete('/images/{id}', 'Images@delete');
        // Pages
        Route::group(['namespace' => 'Pages'], function() {
            Route::get('/pages', 'Pages@index');
            Route::delete('/pages/{id}', 'Pages@delete');

            Route::get('/pages/{page}', 'Pages@show');

            Route::post('/pages', 'Pages@store');

            Route::patch('/pages/{id}', 'Pages@update');
        });
        // Fragments
        Route::group(['namespace' => 'Fragments'], function() {

            Route::post('/fragments', 'Fragments@store');
            Route::patch('/fragments/{id}', 'Fragments@update');
            Route::delete('/fragments/{id}', 'Fragments@delete');

        });
        // Settings
        Route::group(['namespace' => 'Settings'], function() {
            Route::get('/settings', function(){
                return redirect('/settings/site');
            });
            // Site
            Route::get('/settings/site', 'Site@show');
            Route::post('/settings/site', 'Site@update');
            // Developers
            Route::get('/settings/developers/{item?}', 'Developers@show');
                // Developers / Client
                Route::post('/settings/developers/api-access', 'ApiAccess@store');
                Route::delete('/settings/developers/api-access', 'ApiAccess@delete');
                // Developers / Database
                Route::post('/settings/developers/database', 'Database@store');
                Route::delete('/settings/developers/database', 'Database@delete');
                // Developers / Database
                Route::post('/settings/developers/ftp', 'Ftp@store');
                Route::delete('/settings/developers/ftp', 'Ftp@delete');
        });
    });
});
```

**Comment by hskrasek** [comment]
@lukasoppermann I believe this is a trailing slash issue, and how Lumen's router behaves versus Laravel's. You could fix this by adding a server rule to rewrite the URL to remove the trailing slashes.

**Comment by hskrasek** [comment]
But, this issue doesn't seem to pertain to the package itself. So gonna close this out, can re-open if shown to be an issue with Dingo/API though
