### ISSUE TITLE
[Question]: Additional Maintainers

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#1131]
Hey @jasonlewis,

it seems like you are very busy currently. However, dingo is getting much attention and many issues, etc. recently. I think it might be good to add another maintainer to the project? What do you think? Maybe somebody like @lucasmichot or @vinkla?

I would really appreciate a little more stuff happening with dingo and I think people would be more eager to send in PRs if stuff actually gets merged. :)

**Comment by lucasmichot** [comment]
I would definitely agree - up to you @jasonlewis

**Comment by vinkla** [comment]
I think this is a great idea! Keeping an open source project active is hard when you're solo.

Though, I'm might not be a good fit since I don't have enough time to spare. Thanks for the consideration though.

**Comment by lukasoppermann** [comment]
Ahh, I see. Well, I think it might be good to have some people who can merge stuff with confident into the project, so maybe both of you could be good, so that it is not basically another solo-maintainer, since Jason is probably busy for a while. :)

Or maybe somebody else could help @lucasmichot so he does not have to do everything alone.

**Comment by lukasoppermann** [comment]
ping @jasonlewis any chance this could happen soon? As more and more issues snd PRs keep piling up. 😉

**Comment by hskrasek** [comment]
@lukasoppermann Currently in the process of going through all of the issues to catch up, tag everything, and work towards a 1.0.0 release. Hoping to finish going through them all by tonight/tomorrow so that I can start fixing bugs, etc.
