### ISSUE TITLE
Set Transformer Serializer based on API version 

### ISSUE THREAD

**Issue by nschirmer** [dingo/api#1135]
Hi,

Currently, I have my default "v1" API version. I have a `FractalSerializerServiceProvider` registered which binds to the Fractal Adapter and sets the serializer to `JsonApiSerializer`.

Now I am working on setting up some separate Admin API routes, which I've done by creating an "admin" API version. This allows me to segregate my controllers and transformers and anything else I need to.

However... for the Admin API, I want to use `DataArraySerializer` instead. Because of binding the `JsonApiSerializer` in a service provider, it's **always** the default.

What is the recommended way to easily toggle which serializer is used based on API versioning?

Thank you.

**Comment by nschirmer** [comment]
I found a working solution for now. Instead of having a Service Provider that sets the Dingo adapter and binds to the Fractal Manager to set the serializer, I simply have this within my base `App\Api\V1\Controllers\Controller.php` file:

```php
protected function __construct()
    {
		app('\Dingo\Api\Transformer\Factory')->setAdapter(function ($app) {
        	$fractal = new \League\Fractal\Manager;
            $serializer = new \League\Fractal\Serializer\JsonApiSerializer();
            $fractal->setSerializer($serializer);

		    return new \Dingo\Api\Transformer\Adapter\Fractal($fractal);
		});
    }
```

And then within my `App\Api\Admin\Controllers\Controller.php` file, I can do the same thing, but set a different serializer.

Since all of my V1 controllers inherit from that base V1 Controller, and the same thing for my Admin version, this will work perfectly!

**Comment by hskrasek** [comment]
@nschirmer No plans to formally add this, since typically you'd keep the same API response serializer between versions, and maybe change the resource structure itself. But your solution would work, and using fractal directly instead of the adapter would also work.
