### ISSUE TITLE
Append Data to Pagination Links

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#1137]
Hello,

In this closed [thread](https://github.com/dingo/api/issues/556):

@jasonlewis says that this should work to append data to pagination links:

```php
public function paginatorWithAppendedLinks(Paginator $paginator, TransformerAbstract $transformer){
    $paginator->appends(app('request')->except('page'));

    return $this->response->paginator($paginator, $transformer);
}
```

How/where would this be called? I normally respond with a list of users in my user controller's userList method like this:

```php
return $this->response->paginator($users, new UserTransformer);
```

The incoming url that hits this route is filtered by country like this:

`http://localhost:8000/users?country=us`

but the next page in the api response is this:

`http://localhost:8000/users?page=2`

which should look like this instead:

`http://localhost:8000/users?page=2&country=us`

How can I integrate the paginatorWithAppendedLinks function to return the correct paginator response without dropping the country parameter?

**Comment by MovingGifts** [comment]
Got it, [this method works!](https://github.com/dingo/api/issues/580)

**Comment by Cannonb4ll** [comment]
Could you provide an example? I have not been able to get this working. @MovingGifts
