### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Quatja** [dingo/api#1140]
Laravel 5.2.41

1) I added "dingo/api": "1.0.*@dev" to the composer.json
2) composer update

everything is fine, but when I add 
Dingo\Api\Provider\LaravelServiceProvider::class 
to 'providers' in config/app.php, project breaks.

If I try to use "php artisan", for example, "php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider" it throws me an exception:

[ErrorException]  
  Argument 1 passed to Dingo\Api\Exception\Handler::__construct() must implement interface Illuminate\Contracts\Debug\ExceptionHandler, instance of PragmaRX\Tracker\Support\Exceptions\Handler given, called in <project>/vendor/dingo/api/src/Provider/ApiServiceProvider.php on line 130 and defined

Every "php artisan" command throws this exception.

How can I resolve this issue?

**Comment by ssboopathi1991** [comment]
i am also get same issue

Updating dependencies (including require-dev)
  - Removing captcha-com/laravel-captcha (dev-master)


  [RuntimeException]
  Failed to execute git show-ref --head -d
  'git' is not recognized as an internal or external command,
  operable program or batch file.

here i have remove the laravel-captcha file that also show the error message like,

Warning: require(C:\wamp\www\proj_name\vendor/captcha-com/laravel-captcha/src/Support/helpers.php): failed to open stream: No such file or directory in C:\wamp\www\proj_name\vendor\composer\autoload_real.php on line 55

Call Stack:
    0.0003     231456   1. {main}() C:\wamp\www\proj_name\artisan:0
    0.0009     234360   2. require('C:\wamp\www\proj_name\bootstrap\autoload.php') C:\wamp\www\proj_name\artisan:16
    0.0016     236296   3. require('C:\wamp\www\proj_name\vendor\autoload.php') C:\wamp\www\proj_name\bootstrap\autoload.php:17
    0.0025     251992   4. ComposerAutoloaderInit0c78538a8a168466f498b626dc6cdfcd::getLoader() C:\wamp\www\proj_name\vendor\autoload.php:7
    0.0323    2010824   5. composerRequire0c78538a8a168466f498b626dc6cdfcd() C:\wamp\www\proj_name\vendor\composer\autoload_real.php:45


Fatal error: require(): Failed opening required 'C:\wamp\www\proj_name\vendor/captcha-com/laravel-captcha/src/Support/helpers.php' (include_path='.;C:\php\pear') in C:\wamp\www\proj_name\vendor\composer\autoload_real.php on line 55

Call Stack:
    0.0003     231456   1. {main}() C:\wamp\www\proj_name\artisan:0
    0.0009     234360   2. require('C:\wamp\www\proj_name\bootstrap\autoload.php') C:\wamp\www\proj_name\artisan:16
    0.0016     236296   3. require('C:\wamp\www\proj_name\vendor\autoload.php') C:\wamp\www\proj_name\bootstrap\autoload.php:17
    0.0025     251992   4. ComposerAutoloaderInit0c78538a8a168466f498b626dc6cdfcd::getLoader() C:\wamp\www\proj_name\vendor\autoload.php:7
    0.0323    2010824   5. composerRequire0c78538a8a168466f498b626dc6cdfcd() C:\wamp\www\proj_name\vendor\composer\autoload_real.php:45

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error


  [RuntimeException]
  Error Output:


help me

**Comment by rk87** [comment]
I try require dingo/blueprint before dingo/api, and it works.

1) composer require dingo/blueprint:0.2.*@dev
2) composer require dingo/api:1.0.x@dev

**Comment by hskrasek** [comment]
@Quatja Looks like the the framework is trying to construct the dingo handler, and when it tries to build out the "parent exception handler" it fails. Does you exception handler, `PragmaRX\Tracker\Support\Exceptions\Handler`, implement the interface `Illuminate\Contracts\Debug\ExceptionHandler`?
