### ISSUE TITLE
Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Routing\Router] error on Lumen

### ISSUE THREAD

**Issue by lakinmohapatra** [dingo/api#1143]
I was trying ti use Dingo package with Lumen. But unfortunately while setting up routes , its showing following error. Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Routing\Router] error on Lumen

Please let me know if anyone has any solution.

Routes.php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function($api){
    $api->get('users', function(){
       return 'test';
    });
});

**Comment by dsposito** [comment]
I'm having the exact same issue with Lumen 5.2. I have the following line in bootstrap/app.php and similar code above in routes.php.

`$app->register(Dingo\Api\Provider\LaravelServiceProvider::class);`

Error received:
```
'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Routing\Router].'
```

@jasonlewis Can you take a quick look?

**Comment by rk87** [comment]
`$app->register(Dingo\Api\Provider\LumenServiceProvider::class);` for lumen, 
but your is `LaravelServiceProvider`

https://github.com/dingo/api/wiki/Installation

**Comment by dsposito** [comment]
Thanks!

**Comment by hskrasek** [comment]
@lakinmohapatra @dsposito Y'all still having an issue with this?

**Comment by dsposito** [comment]
Nope, `$app->register(Dingo\Api\Provider\LumenServiceProvider::class);` did the trick for me.
