### ISSUE TITLE
Dingo define the same property as [$scope] Laravel controller

### ISSUE THREAD

**Issue by andela-iadeniyi** [dingo/api#1147]
This issue occurred when i host my app on cloudways, it works perfectly locally and on cpanel also.
`
[ErrorException]                                                                                                            
  App\Http\Controllers\Controller and Dingo\Api\Routing\Helpers define the same property ($scopes) in the composition of App\Http\Controllers\UsersController. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed
`

**Comment by Deleugpn** [comment]
you're defining a variable on your `App\Http\Controllers\Controller` class which is also defined on `Dingo\Api\Routing\Helpers` trait. I assume your `App\Http\Controllers\UsersController` extends your `App\Http\Controllers\Controller` and uses the `Helpers` trait. In which case, you're trying to define a variable that should be left exclusive for Dingo. Rename your variable.

**Comment by hskrasek** [comment]
@andela-iadeniyi @Deleugpn Is correct, if you are using the `Dingo\Api\Routing\Helpers` trait on your controllers, you'll need to rename your controllers variable.

**Comment by andela-iadeniyi** [comment]
@Deleugpn Thanks for your response, the issue occurs when I tried the app on cloudways but works perfectly on my local and heroku. I feel `Dingo\Api\Routing\Helpers` trait has a defined property `$scopes` and `App\Http\Controllers\Controller` with a default laravel config has the same `$scopes` property defined in either of its inherited method.

**Comment by Deleugpn** [comment]
Laravel doesn't have a `$scopes` variable at it's out-of-box `controllers` class and, if it did, it wouldn't give you an error pointing to `App\Http\Controllers\Controller`. It would much like point the error to `Illuminate\Routing\Controller`. The error specifically says that while trying to build **your** `UsersController`, PHP needs to include the Trait `Helpers` and the `App\Http\Controllers\Controller` and these two are conflicting. You should open your `App\Http\Controllers\Controller` and search for a `$scopes` variable and rename it.
The fact that you're not experiencing this in two types of servers, but is on one merely suggests a server configuration issue or a bad deploy.
