### ISSUE TITLE
How can I use fractal "include" functionality with dingo?

### ISSUE THREAD

**Issue by ratulcse27** [dingo/api#1154]
```
class ProjectTransformer extends TransformerAbstract
{

    protected $availableIncludes = [
        'resource'
    ];

    public function transform(Project $project)
    {
        return [
            'id' 	=> (int) $project->id,
            'title'  => $project->title,
            'description'	=> $project->description,
            'git_link'	=> $project->git_link,
            'budget'	=> $project->budget,
            'paid'	=> $project->paid,
            'project_type'	=> $project->project_type,
            'project_status'	=> $project->project_status,
        ];
    }

    public function includeResource(Project $project)
    {
        $resources = $project->resources;

        return $this->collection($resources, ResourceTransformer::class);
    }
}
```
what I have to do in my controller so that can i use this link "api/projects?include=resource" and get all the projects with the resourse? 

My controller code is here :
```
$project = Project::all();
        return $this->response->collection($project, ProjectTransformer::class, [], function($resource, $fractal){
            if(isset($_GET['include'])){
                $fractal->parseIncludes(explode(',', $_GET['include']));
            }
        });
```
getting this error

Call to undefined method Illuminate\Database\Query\Builder::resource()

**Comment by hskrasek** [comment]
@ratulcse27 The issue doesn't seem to be coming from Fractal's `includes` system, but with your Eloquent model itself.

**Comment by hskrasek** [comment]
@ratulcse27 I think you're issue might be related to this #986, which means Dingo is trying to eager load a relationship based on the include that doesnt exist on the class. If you rename the include to match the relationship, you should be good

**Comment by ratulcse27** [comment]
@hskrasek thanks you for guiding me in the right direction. It's working now. But one more question, https://github.com/dingo/api/issues/986 in this thread one of them told that 

> If the include key in the transformer is not different from the relationship function name, you can assign the key-value array in $defaultIncludes. The key is the relationship function name, the value is the include key name.

But for me this isn't working. Can you tell me is this possible with $availableIncludes.

**Comment by Deleugpn** [comment]
Does using `::class` instead of `new ...Transformer` actually work?

**Comment by ratulcse27** [comment]
@Deleugpn Sorry, It doesn't work with ::class, I fixed it in my code but forget to fix it here.

**Comment by hskrasek** [comment]
@ratulcse27 That doesn't seem to be possible with Fractal. Fractal just takes the include from `$availableIncludes` once it confirms its actually available, and uses it to call the include function (can see that [here](https://github.com/thephpleague/fractal/blob/master/src/TransformerAbstract.php#L183-L185)).

**Comment by ratulcse27** [comment]
@hskrasek I understand it now. Thanks for your help.
