### ISSUE TITLE
Laravel 5.2 > 5.3

### ISSUE THREAD

**Issue by wardwar** [dingo/api#1165]
when upgrade laravel into 5.3 I have a problem,
Method gatherRouteMiddlewares does not exist.

**Comment by wardwar** [comment]
`public function gatherRouteMiddlewares($route)
    {
        return $this->router->gatherRouteMiddlewares($route);
    }`
there is typo at here.
fixed with
`public function gatherRouteMiddlewares($route)
    {
        return $this->router->gatherRouteMiddleware($route);
    }`

**Comment by shez1983** [comment]
@wardwar how did you update dingo/api to use laravel 5.3? when i try to update it I get 

'Your requirements could not be resolved to an installable set of packages.'
dingo/api v0.10.0 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].

Thanks in advance

**Comment by wardwar** [comment]
@shez1983 I don't know, I just edited the file. and it work for me.
did you done composer update after require laravel 5.3?

**Comment by Kaukov** [comment]
https://github.com/dingo/api/pull/1152

Here's the PR that implements Laravel 5.3 support. I think the dev will soon pull it to the repo :)

**Comment by Deleugpn** [comment]
Any simple way to install it over Laravel 5.3?

**Comment by hskrasek** [comment]
Closed by #1152 being merged. Install `dev-master` or the latest tag (v1.0.0-beta6 at the time of this comment)

**Comment by rohitpaniker** [comment]
Even I am using Laravel 5.3
As @wardwar said, edit file at vendor/dingo/api/src/Routing/adapter/Laravel.php

Overwrite this line:

`public function gatherRouteMiddlewares($route)
     {
         return $this->router->gatherRouteMiddlewares($route);
     }`

in to this:

`public function gatherRouteMiddlewares($route)
    {
        return $this->router->gatherRouteMiddleware($route);
    }`

Thank you @wardwar , I owe you a beer for saving my day bud!

**Comment by crynobone** [comment]
@rohitpaniker the merged file already include this changes.

**Comment by rohitpaniker** [comment]
@crynobone Ohkay really? As I did a fresh install as well as update so I came across the same issue few minutes back. Anyway, thank you for pointing it out :)

**Comment by Tellurian7** [comment]
Using Laravel 5.4, the file isn't fixed :
https://github.com/dingo/api/blob/master/src/Routing/Adapter/Laravel.php
