### ISSUE TITLE
How to create blue print document in dingo ?

### ISSUE THREAD

**Issue by tankhit** [dingo/api#1167]

**Comment by catalinux** [comment]
Did you read https://github.com/dingo/api/wiki/API-Blueprint-Documentation ? Is something that did not work for you?

**Comment by wanglv** [comment]
`php artisan api:docs --output-file api.md`

**Comment by tankhit** [comment]
@catalinux  I have read this documentation but not getting idea, How it's look and fill on browser. If you having any reference please let me know.

**Comment by tankhit** [comment]
@wanglv for `php artisan api:docs --output-file api.md` what's happen. Can you please provide step by step flow of code ?

**Comment by catalinux** [comment]
When you run `php artisan api:docs --output-file api.md  --name 'Doc' in your directory a file called api.md will be generated. 

.md extenstion states for markdown format.

The command will gather all annotations that you filled in on your controllers (see https://github.com/dingo/api/wiki/API-Blueprint-Documentation) and put them in nice format, something like that

```md
FORMAT: 1A

# Doc

# Contact [/contact]

## Create a contact [POST /contact]


+ Request (application/json)
    + Headers

            X-Custom: FooBar
    + Body

            {
                "last_name": "foo",
                "first_name": "bar"
            }

## Show all contacts [GET /contact]
Get a JSON representation of all the registered users.
```

**Comment by tankhit** [comment]
@catalinux thank you for reply. Can you please share how it's look in browser. Thanks,

**Comment by hskrasek** [comment]
@tankhit Hard to do that, since there are many options available for turning the API Blueprint markdown file to browse-able documentation. One example of this is [https://apiary.io/](https://apiary.io/).

**Comment by petyots** [comment]
Hi, i tried generating docs with the following command : 
~~~~
$ php artisan api:docs --name Developer --use-version v1 --output-file ApiDocs.md
Output : Documentation was generated successfully
~~~~

But the ouput of the file is only with the title without my comments parameters etc... in controllers. It does not ouput any information in the doc file. Thanks in advance

**Comment by hlogeon** [comment]
+1 for @petyots 
I had the same problem and just switched to swagger. But it would be better if someone fix this issue or at least try to figure out what's wrong.

**Comment by abosami2000** [comment]
@petyots @hlogeon same problem 

the output file contain only title without any description

**Comment by petyots** [comment]
I was using v1 instead of V1 which was in my project file that was the error ;)

**Comment by aftab-currency** [comment]
@hlogeon please add annotation for Controller and also for Controller method.  This will solve your problem.

**Comment by asntcrz** [comment]
Few years after I found the issue, for future reference, documentation results empty because dingo/blueprint is missing, add it to your composer.json:

"dingo/blueprint": "^0.2.4",

**Comment by specialtactics** [comment]
It's there by default (now anyway).

Going to close this issue as it seems really old and potentially no longer relevant
