### ISSUE TITLE
How to protect route with specific auth provider?

### ISSUE THREAD

**Issue by ghprod** [dingo/api#1171]
Hi, 

i've defined two auth provider in `config.api.auth` like this

```
    'auth' => [
        'jwt' => 'Dingo\Api\Auth\Provider\JWT',
        'private_token' => 'App\Providers\PrivateTokenProvider',
    ],
```

And protect my route by use `['middleware' => 'api.auth']`. Its works for all type of auth. 

My question is how can i protect some route by specific auth method? Example i want to protect route `/api/some-resource` by only `private_token` provider, so when access that route using jwt, its blocked ..

I was imagine that i could do something like this

```
['middleware' => 'api.auth:jwt']

// or

['middleware' => 'api.auth:private_token']
```

Thanks

**Comment by hskrasek** [comment]
@ghprod Technically what you are aiming to do already exists. Whenever you use the `api.auth` middleware, it'll iterate over ever single provider you have configured to handle the authentication attempt.

**Comment by ghprod** [comment]
@hskrasek .. Thanks for your reply ,, yes dingo will automatically scan for available provider and call `authenticate` for each of them ..

actually i just want to specific route protect only by specific provider, not scan all of them. but I think maybe i need to redesign my code, so its not a problem anymore .. 

Thanks :+1:
