### ISSUE TITLE
Generating api urls broken

### ISSUE THREAD

**Issue by catalinux** [dingo/api#1172]
After this update https://github.com/dingo/api/commit/68eac66c5958135a064d5d82db774d09f494ef3d

my way of generating urls broken:

```php
    function api_route($routeName, $routeParams = [], $absoluteUrl = false)
    {
        return app('api.url')->version('v1')->route($routeName, $routeParams, $absoluteUrl);
    }

```

Question: what is the proper way?

**Comment by hskrasek** [comment]
@catalinux What exactly do you mean by broken? Are you getting an error? The test I added [here](https://github.com/dingo/api/commit/68eac66c5958135a064d5d82db774d09f494ef3d#diff-3cbf0fbd862b48aaceb71d6e79a6763dR32) is testing the exact usage you have above.

**Comment by catalinux** [comment]
There was an error like this `Class router does not exist`. I will investigate a little bit later for more details

**Comment by hskrasek** [comment]
@catalinux Should update to commit 3dc6189 and try it again. PHPStorm told me a method was missing in a service provider, but I didn't notice it and the tests dont test the providers (yet), so that might be what you were running into.

**Comment by catalinux** [comment]
Everything is back to normal. Tx

**Comment by catalinux** [comment]
Nope. It is not.

here it crashes:

`ReflectionException: Class router does not exist`

/var/www/api/vendor/illuminate/container/Container.php:734
/var/www/api/vendor/illuminate/container/Container.php:629
/var/www/api/vendor/laravel/lumen-framework/src/Application.php:206
/var/www/api/vendor/illuminate/container/Container.php:1178
/var/www/api/vendor/dingo/api/src/Provider/RoutingServiceProvider.php:51
/var/www/api/vendor/illuminate/container/Container.php:731
/var/www/api/vendor/illuminate/container/Container.php:629
/var/www/api/vendor/laravel/lumen-framework/src/Application.php:206
/var/www/api/vendor/laravel/lumen-framework/src/helpers.php:39
/var/www/api/bootstrap/helpers.php:76


variable `concrete` has value `router`

**Comment by catalinux** [comment]
I am using Lumen 5.2

**Comment by hskrasek** [comment]
@catalinux Ahh, that'll do it. Lumen and Laravel's UrlGenerators are significantly different. Will see if I have time at work today to come up with a new approach

**Comment by hskrasek** [comment]
@catalinux I've wound up reverting the changes made in the original commit. Thinking I'm going to abandon the idea of merging the routes so that a single UrlGenerator can be used, due to lumen and laravel being drastically different.
