### ISSUE TITLE
Endpoint with Query Parameters

### ISSUE THREAD

**Issue by vrdyquest** [dingo/api#1175]
Hi! I'm new to Dingo with Laravel and was going through the docuentation to create end points! The endpoints article talks a lot about path parameters and fetching them but does not about Query params for creating end points! Are they supported in any way or did I miss any part of the documentation.
Appreciate your help! Thanks

**Comment by hskrasek** [comment]
@vrdyquest That'd be because the router doesn't need to do anything with query params. All you'd do is `$request->input('query_param')` and be able to get the data. You can't really document those with the router though

**Comment by vambroise** [comment]
@vrdyquest You are free to use any query parameter without additional configuration. In your API controller you can use Request::input('param') as with any controller. Just make sure that you have some sort of validation.
