### ISSUE TITLE
Route Model Binding not working correctly with Laravel 5.3

### ISSUE THREAD

**Issue by dclawson** [dingo/api#1179]
I am having an issue with route model binding on my dingo (dev-master w/ L5.3 support) specific routes. On my Laravel web routes it works fine and returns the model with the correct data. It also works on Laravel 5.2.

**routes/api.php**

``` php
$api->get('users/{user}', ['as' => 'users.show', 'uses' => 'UserController@show']);
```

**UserController.php**

``` php
public function show(User $user)
{
    dd($user);

    return $this->response->item($user, new UserTransformer);
}
```

The `$user` object is empty. I have tried with another controller too with the same results.

I can only get it to work by using `first()`, which defeats the purpose of model binding.

``` php
public function show(User $user)
{
    $data = $user->first();

    return $this->response->item($data, new UserTransformer);
}
```

**Comment by jakubkratina** [comment]
+1

**Comment by az-iar** [comment]
Add `bindings` middleware to your route as such:
```php
$api->group(['middleware' => 'bindings'], function($api){
    $api->get('users/{user}', ['as' => 'users.show', 'uses' => 'UserController@show']);
});
```

**Comment by dclawson** [comment]
Thanks @az-iar that works well.

**Comment by jakubkratina** [comment]
@az-iar Oh, thanks, new to me.

**Comment by joshuaziering** [comment]
+1 for this working well. Thanks.

**Comment by phobos2077** [comment]
For those who find this solution not working - check your Kernel.php, $routeMiddleware should contain:
`'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,`

**Comment by RushabhJoshi** [comment]
Yes this bindings route middleware is there and still I am not able to get model object.
Its working for other controllers,

I am using laravel 5.3

**Comment by jakubkratina** [comment]
@RushabhJoshi Check your route parameter for the model if matches. For example: `$api->get('users/{users}')` vs `User` model (plural vs singular). If you dump your parameter, do you get the model's ID?

**Comment by RushabhJoshi** [comment]
My route is `api/products/{product}`. it listen to get request and My argument with typehint `Product $product`

**Comment by jakubkratina** [comment]
@RushabhJoshi What is the difference between your `ProjectController` and others? You said the problem is only with this controller.

**Comment by RushabhJoshi** [comment]
I see no difference both are resource controller one is only dedicated for api purpose.

**Comment by jakubkratina** [comment]
Does your 'api' middleware group have assigned 'bindings'? In `app/Http/Kernel.php`:

```
// For web routes
'web' => [
           ...
            \Illuminate\Routing\Middleware\SubstituteBindings::class
        ],
// For api routes
'api' => [
            'throttle:60,1',
            'bindings'
        ],
```

**Comment by RushabhJoshi** [comment]
Yes, I haven't changed any defaults

**Comment by jakubkratina** [comment]
Send here you Kernel, Controller and route please.

**Comment by RushabhJoshi** [comment]
Kernel.php
```php
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    protected $commands = [
        //
    ];

    protected function schedule(Schedule $schedule)
    {
        // $schedule->command('inspire')
        //          ->hourly();
    }
    protected function commands()
    {
        require base_path('routes/console.php');
    }
}
```

Controller
```php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Product;

/**
 * @Resource("products", only={"index", "show"}, names={"index"="api.products.index", "show"="api.products.show"})
 * @Controller(prefix="api")
 * @Middleware("auth.token")
 */
class ProductController extends Controller
{
    // here can't get product from route binding
    public function show($id)
    {
        $product = Product::findOrFail($id);
        $product->load('images', 'keywords', 'gardenTypes', 'partnerProducts', 'details', 'recommendedProducts');

        return response()->json($product);
    }

}

```

**Comment by jakubkratina** [comment]
@RushabhJoshi Http Kernel, not console Kernel. If you run the `route:list` command, do you have there `/api/products/{product}` route?

**Comment by RushabhJoshi** [comment]
Sorry 
My http kernel is 
```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'category' => \App\Http\Middleware\CheckCategroy::class,
        'admin' => \App\Http\Middleware\CheckAdminUser::class,
        'auth.token' => \App\Http\Middleware\ApiAuthorization::class,
    ];
}
```
and my route list
```
|        | GET|HEAD                       | api/categories                          | api.categories.index          | App\Http\Controllers\Api\CategoryController@index                         | auth.token                                                 |
|        | GET|HEAD                       | api/products                            | api.products.index            | App\Http\Controllers\Api\ProductController@index                          | auth.token                                                 |
|        | GET|HEAD                       | api/products/{product}                  | api.products.show             | App\Http\Controllers\Api\ProductController@show                           | auth.token
```

**Comment by RushabhJoshi** [comment]
I also realise now do I need web middleware?

**Comment by jakubkratina** [comment]
@RushabhJoshi no, you don't have to define the `web` middleware if using only `api`. If you pass the product model into the method, what do you get when you dump it?

`public function show(Product $product)`

+ what do you see when you dump `$product->id`?

**Comment by RushabhJoshi** [comment]
this is giving me `null`

**Comment by jakubkratina** [comment]
@RushabhJoshi There may be a problem in that annotation definition. Dingo has his own route, so if you want to define your api routes, you have to use Dingo's router like:

```
$api = app('Dingo\Api\Routing\Router');

		$api->version('v1', function ($api) {
			$api->group([
				'namespace'  => $this->namespace,
				'middleware' => 'api',
			], function ($api) {
				// your routes
			});
		});
```

If you execute the command `route:list`, these are Laravel's routes. For Dingo it is `api:routes`. 

Check this too.

**Comment by RushabhJoshi** [comment]
I think its laravel problem I should report them

**Comment by bespired** [comment]
I'm having the same issue moving the models from App to Package. Still searching for a solution.

**Comment by ihr-it-projekt** [comment]
Any solutions?

**Comment by iget-master** [comment]
This change should be on the Upgrade Guide from 5.2 -> 5.3!

**Comment by ahmadbadpey** [comment]
I have same @RushabhJoshi problem. Any solution. I'm using laravel 5.4

**Comment by ahmadbadpey** [comment]
I found that must to add `bindings` middleware in the same route group that added `auth.api` middleware instead adding it to each sub routes separately.  
means like this : 

		$api->group(['middleware' => 'api.auth|bindings'], function ($api) {
                });

**Comment by TheAkashRajput** [comment]
Anyone got the solution. This returns null:
`    $api->group(['middleware' => 'bindings'], function ($api) {

        $ctrlPrefix = "\App\Api\V1\Controllers";
        $api->resource('Institute', $ctrlPrefix.'\InstituteController');

    });
`
This is my controller:
`    public function show(Institute $institute)
    {
        
        return response()->json($institute);
    }
`
I'm 5.4 please help.

**Comment by danang-id** [comment]
For [implicit model binding](https://laravel.com/docs/5.4/routing#implicit-binding) to work, make sure your model have use `Illuminate\Notifications\Notifiable` trait.

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Project extends Model
{

    use Notifiable;

```

**Comment by Grummfy** [comment]
Well I got the same issue...

I think the documentation about this part could be improvements.

Most of the people think, naturally, that using \App\Providers\RouteServiceProvider::mapApiRoutes is the good approach for it. But it's a trap.

**Comment by DavidSprauel** [comment]
up i've the same problem in laravel 5.8

**Comment by VuongTran21** [comment]
Special thanks to @az-iar , add `bindings` to `middleware` solved my problem.

**Comment by namnguyen2091** [comment]
With laravel 8, I see bindings middleware exists in route but I dont know why I still add in route middleware:

    ```
protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```
