### ISSUE TITLE
How to use the pagination??

### ISSUE THREAD

**Issue by ssboopathi1991** [dingo/api#1180]
I have use the dingo with guzzlehttp. i have use the api for web and mobile app. here how can use the pagination. i am using the paginator.. but its not working

**Comment by bkintanar** [comment]
what's the problem? I'm using the paginator and it's working just fine.

**Comment by ssboopathi1991** [comment]
// This is my api controller
    public function sample_list(Request $data)
    {
    	$data_all = $data->all();
    	$page     = $data_all['page'];
    	if($page == '')
    	{
    		$page = 0;
    	}
    	$sample_list = Api_Model::sample_list($page);//model file i have using paginate()
   	if(count($sample_list) > 0 )
   	{
   		$i = 0;
   		foreach($sample_list as $samp)
    		{
    			$sample[$i]['sample_id']   = $samp->id;
    			$sample[$i]['sample_name'] = ucfirst($samp->sample_name);
    			$i++;
    		}
    		$result = array("response" => array("httpCode" => 200, "status" => "Success", "Message" => trans("messages.Sample List"), "sample_list" => $past_election));
	    }
	    else {
	    	$result = array("response" => array("httpCode" => 400, "status" => "Failure", "Message" => trans("messages.No Data Found")));
	    }
	    return json_encode($result);
    }

//here i have get the view controller
    public function sample_view()
    {
    	$page = isset($_GET['page'])?$_GET['page']:1;
    	$post_array_past = array("page"=>$page);

    	$response_past = $this->client->request('GET',url('/election/election_list'), [
    		'form_params' => $post_array_past
    	]);
    	$code = $response_past->getStatusCode();
    	$body = $response_past->getBody();
    	$sample_content = $body->getContents();
    	$sample_content_json_dec = json_decode($sample_content);
    	if($sample_content_json_dec->response->httpCode == '200')
    	{
    		$sample_data = "";
    		foreach($sample_content_json_dec->response->sample_list as $key => $row)
    		{
    			$sample_data .= '<div class="elect_common">';
    			$sample_data .= '<div class="col-md-4 col-sm-6 col-xs-12">';
    			$sample_data .= '<div class="sample_lst">';
    			$sample_data .= '<div class="sample_inner">';
    			$sample_data .= '<h2><a href="'.url('/sample/'.$row->sample_id).'" title="'.ucfirst($row->sample_name).'">'.substr(ucfirst($row->sample_name),0,26).'</a></h2>';
    			$sample_data .= '</div></div></div></div>';
    		}
    		$sample_data .= $sample_content_json_dec->response->sample_list->render();//Here i have using the render means show the error message
    	}
    	else
    	{
    		$sample_data  = '<div class="no_sample">'.trans("messages.No Data Found").'</div>';
    	}
    	return view('frontend.home')->with('sample_data',$sample_data);
    }
Now i have get the error message
**Call to a member function render() on a non-object**

**Comment by ssboopathi1991** [comment]
-
