### ISSUE TITLE
Cache command

### ISSUE THREAD

**Issue by jakubkratina** [dingo/api#1181]
I tried api:cache command to generate route cache, and figured out that this https://github.com/dingo/api/blob/master/src/Console/Command/Cache.php#L58
is returning empty array even though I have defined routes via`Dingo\Api\Routing\Router`.

Does it work for you? I have Laravel 5.3 and updated version of dingo `1.0.x@dev`

**Comment by hskrasek** [comment]
Possible side-effect of 5.3, will look into it.

**Comment by mmswiderski** [comment]
I cannot reproduce this behavior on same setup: Laravel 5.3 and dingo@dev.

**Comment by hskrasek** [comment]
@jakubkratina Loaded up a L5.3 project with recent version of dingo, setup a route in both dingo and laravel and was about to cache the routes correctly. Are you still having this issue? Have an example you can share that re-creates the example?

**Comment by jakubkratina** [comment]
There was a problem with`require_once` inside the `RouteServiceProvider` file. It has to be only `require`. I found this problem when debugging multiple api calls in a single test case. So it was the very same problem. Thank you for your assistance guys.

**Comment by farhanwazir** [comment]
@jakubkratina require is a best practice in it and you also needs to run
```php
Composer dump-autoload
```
