### ISSUE TITLE
request: allow JSON Pretty Print for output

### ISSUE THREAD

**Issue by davecarlson** [dingo/api#1182]
Currently, there's no ability in Http/Response/Format/Json.php to provide configuration to json_encode:

Current:

```
protected function encode($content)
{
    return json_encode($content);
}
```

I'd like the ability to pass in the options flag to format it, such as JSON_PRETTY_PRINT : 

http://php.net/manual/en/function.json-encode.php

```
protected function encode($content)
{
   if ( $someConfig['json_format'] ) {
      $options = $someConfig['json_format'];
   } else { 
      $options = 0;
   }
   return json_encode($content, $options);
}


```

**Comment by hskrasek** [comment]
@davecarlson Can't say this will make it into version 1.0.0, but something I'll look into and see if it makes sense.

**Comment by jasonlewis** [comment]
If it's just for the pretty print option just install a Chrome extension to do it for you.

If you need other options it's something that can be looked at. For now, if you really need this, just overwrite the existing JSON formatter with your own custom one.

https://github.com/dingo/api/wiki/Responses#custom-response-formats

**Comment by davecarlson** [comment]
We currently use: 

JSON_FORCE_OBJECT
JSON_PRETTY_PRINT
JSON_PRESERVE_ZERO_FRACTION
JSON_ERROR_SYNTAX

I simply use pretty print as an example as i though it would be the most useful for *other* people :)
