### ISSUE TITLE
Missing parameters on request in the middleware

### ISSUE THREAD

**Issue by catalinux** [dingo/api#1184]
Is it possible that the last commits remove the posibility to see parameters on requests in the middleware. Everything worked great with `cac67ab05da38c3de6d48c7146b700a13ed54cd0` but in the last commit I cant read parameters on request.?

I will check more in detail

**Comment by catalinux** [comment]
After a new `composer install` I could not replicate this problem. I will built some tests for the future and I'll get back

**Comment by hskrasek** [comment]
@catalinux Were you able to replicate this again?

**Comment by catalinux** [comment]
No. I should close this issue
