### ISSUE TITLE
Custom FormRequest rule not working with JSONAPI, help needed?!

### ISSUE THREAD

**Issue by oxodesign** [dingo/api#1192]
Hi Im using JSONAPI format and have created custom FormRequest to validate my data, here is how my FormRequest looks like:

```php
<?php

namespace App\Http\Requests;

use Dingo\Api\Http\FormRequest;

class CustomUserRequest extends FormRequest
{
    
    public function authorize()
    {
        return true;
    }
    
    public function rules()
    {
        return [
            'name' => 'required|min:3|max:50',
        ];
    }
}
```

And here is the payload I send to the server (on update):
`{"data":{"id":"1","attributes":{"name":"OXODesign"},"type":"users"}}`

But Im still getting validation error.
`{"message":"422 Unprocessable Entity","errors":{"name":["The name field is required."]} ...}`

Hope someone has a fix for this, do I need to configure something?

**Comment by hskrasek** [comment]
@oxodesign You need to update your rules to correctly target JSONAPI style requests. So instead of just `name`, you need to specify the rule as `data.attributes.name` for it to correctly validate.

**Comment by oxodesign** [comment]
@hskrasek well thanks a lot! Sometimes one just overthink everything! Im feeling dumb right now hehe
