### ISSUE TITLE
Access Dingo API Route via name in other controller

### ISSUE THREAD

**Issue by fzhan** [dingo/api#1194]
IndexController.php:

return route("api::v1.home");

Will show route doesn't exists.

How can we access the route from web controllers?

Thanks

**Comment by farhanwazir** [comment]
Wiki > [creating api endpoint](https://github.com/dingo/api/wiki/Creating-API-Endpoints) > Named Routes And Generating URLs
There you can find how to get url by route name

**Comment by hskrasek** [comment]
@fzhan What @farhanwazir suggested will get you what you need. You have to use Dingo's special UrlGenerator
