### ISSUE TITLE
laravle 5.3 use dingo/api not working

### ISSUE THREAD

**Issue by nodece** [dingo/api#1198]
# Development
laravel 5.3
php 7
# Code
![qq 20160918213458](https://cloud.githubusercontent.com/assets/16235121/18616054/cc4664ae-7de7-11e6-8860-9c805e093cfc.png)

**Comment by tkorsa** [comment]
With **Laravel 5.3** and **Dingo 1.0.0-beta6**, this should work

```php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('/', function () {
        return 'test';
    });

    $api->get('/protected', function () {
        return 'Let me tell you a secret';
    })->middleware('auth:api');
});
```

Running `php artisan api:routes` should show you the route.

**Comment by hskrasek** [comment]
@nodece Are you still having issues with the package and Laravel 5.3? If not can we close this?

**Comment by CreativeKoen** [comment]
I running php 7 and laravel 5.3 with dingo 1.0.0-beta6.
With the example above from @tkorsa.

This route should be protected
but `php artisan api:routes` doesn't show it as a protected route
```php
 $api->get('/protected', function () {
        return 'Let me tell you a secret';
    })->middleware('auth:api');
````

**Comment by johannesschobel** [comment]
can you access it via GET request (e.g, using postman)?!
