### ISSUE TITLE
API::route()

### ISSUE THREAD

**Issue by ryanhungate** [dingo/api#12]
Hey Jason, any chance you wanted to build in support for the route() call vs clunky url patterns? :)  I think it would be fantastic to do that, so in your internal API requests, they could be so clean.

**Comment by furey-imagination** [comment]
Is it possible to generate a URL for a **dingo/api** named route?

I've named an API route `'api.orders.show'`, and I can confirm that name was assigned by seeing it returned via `php artisan api:routes`.

When trying to generate the named route's URL via Laravel's `route()` helper, `Dingo\Api\Routing\UrlGenerator` throws an `InvalidArgumentException`:

    "Route [api.orders.show] not defined"

Any ideas?

**Comment by scheMeZa** [comment]
I'm confused as to how I'm supposed to access these routes natively, this provider uses its own router which doesn't allow me to use other packages that makes routing accessible in javascript or with the simple route() helper function... What a pain in the arse ;(
