### ISSUE TITLE
Laravel 5.3 artisan api:routes not working

### ISSUE THREAD

**Issue by zashme** [dingo/api#1212]
routes/api.php:
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->group(['middleware' => 'bindings'], function($api){
        $api->get('/user', function (Request $request) {
            return $request->fullUrl();
        });
    });
});
```
`artisan api:routes` output:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Type error: Argument 1 passed to App\Providers\RouteServiceProvider::{closure}() must be an 
instance of Illuminate\Http\Request, none given, called in 
/home/www/hk/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 865
```

calling url from web is working, output:
`http://localhost:8000/api/user`

**Comment by wouterNL** [comment]
I am getting the same error, how did you fix this?

**Comment by michabbb** [comment]
@zashme how did you fix this?!

**Comment by wouterNL** [comment]
If you still have that $request->user in your api routes you should delete that. I think thats how I fixed it.

(I am writing this from my phone and it has been a while so I am not entirely sure if that was it.)

**Comment by michabbb** [comment]
@wouterNL i get the same error with this:

```php
/** @var \Dingo\Api\Routing\Router $api */
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    /** @var \Dingo\Api\Routing\Router $api */
    $api->get('users/{id}',function($id) {
        return ['version' => 1];
    });
});
```

`php artisan api:routes`

 ```                                                                                                                                                                                                         
  [ErrorException]                                                                                                                                                                                        
  Missing argument 1 for App\Providers\RouteServiceProvider::{closure}(), called in /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 865 and defined
```

if i remove `$id` from `function($id)` it get: 

```
[ErrorException]                                        
  strstr() expects parameter 1 to be string, array given  
```

whats wrong ??? thanks for any hint....

**Comment by michabbb** [comment]
@hskrasek can you please help me ? its very hard to start with your framework if the basics don´t work ;-(

**Comment by wouterNL** [comment]
if you use route model bindings please use the middleware method: 
`$api->group(['middleware' => 'bindings'], function($api){});`

**Comment by michabbb** [comment]
@wouterNL pardon, why do i need a group or a middleware ? isn´t it possible to create a very simple rout like in my example ???

**Comment by wouterNL** [comment]
Yeah I dont understand why that is needed either. Also, it doesnt work well with laravel 5.3. I tried using Dingo for a while but there were just so many things that just do not work I ended up just using the normal laravel architecture.

**Comment by michabbb** [comment]
@wouterNL i guess i will stop here too ;-( so many websites say "its the best api framework for laravel" but when you start and get 5 problems after 10minutes, you will end up in solving problems you never would have, if you didn´t use it in the first place... i believe its a great framework, but if the most simple things, that are even mentioned in the docu, don´t work... i guess, this is a sign ;)

**Comment by michabbb** [comment]
@wouterNL btw... its very frustrating if people start issues and close them without any hint... i have seen this here several times... ;-(

**Comment by michabbb** [comment]
okay, for everyone else, who gets in contact with this...  this works with laravel 5.3

```php
/** @var \Dingo\Api\Routing\Router $api */
$api->version('v1',[], function ($api) {
    /** @var \Dingo\Api\Routing\Router $api */
    $api->get('users/{id}','App\Http\Controllers\Api\v1\ApiController@test');
});
```

`app/app/Http/Controllers/Api/v1/ApiController.php`

```php
namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;

class ApiController extends Controller
{

    public function test($id) {
        return ['version' => 1,'id' => $id];
    }


}
```

```bash
php artisan api:routes
+------------------------------------+----------+-----------------+------+------------------------------------------------+-----------+------------+----------+------------+
| Host                               | Method   | URI             | Name | Action                                         | Protected | Version(s) | Scope(s) | Rate Limit |
+------------------------------------+----------+-----------------+------+------------------------------------------------+-----------+------------+----------+------------+
| api.xxxxxxxxxxxxxxxxxxxxxxxxxxx.de | GET|HEAD | /api/users/{id} |      | App\Http\Controllers\Api\v1\ApiController@test | No        | v1         |          |            |
+------------------------------------+----------+-----------------+------+------------------------------------------------+-----------+------------+----------+------------+
```

**Comment by FedericoBiccheddu** [comment]
I had the same issue and solved by using `$api` instead of `$this` while declaring group routes; eg:
```php
use Dingo\Api\Routing\Router;
use App\Http\Controllers\MyController;

/** @var Router $api */
$api = app(Router::class);

$api->version('v1', ['prefix' => 'v1'], function (Router $api) {
    $api->post('my_route', MyController::class . '@myFirstMethod');

    /* 
     * If you use $this->group() instead of $api->group()
     * you will receive the error mentioned in this issue.
     */
    $api->group(['prefix' => 'my_prefix'], function (Router $api) {
        $api->post('my_group_route', MyController::class . '@mySecondMethod');
    });
});
```

**Comment by argentinaluiz** [comment]
I had the same issue too with Laravel 5.4, example:

``` php
ApiRoute::version('v1', function (){
    ApiRoute::group([
        'namespace' => 'CodeFlix\Http\Controllers\Api',
        'as' => 'api'
    ], function(){
        ApiRoute::group([
            'middleware' => ['api.throttle', 'api.auth'],
            'limit' => 100,
            'expires' => 3
        ], function (){
            ApiRoute::get('/user', function (Request $request){
                 return $request->user('api');
            });
        });
    });
});
```

**Argument 1 passed to Illuminate\Routing\Router::{closure}() must be an instance of Illuminate\Http\R
  equest, none given, called in C:\Users\Luiz\Documents\Code.education\Projetos alunos\CodeFlix\vendor
  \laravel\framework\src\Illuminate\Support\helpers.php on line 997 and defined**

**Comment by michabbb** [comment]
@argentinaluiz you said "had"... so is your code a example of something, that **is working** or **is not working** ? ;)

**Comment by argentinaluiz** [comment]
Hi @michabbb , is not working.

**Comment by michabbb** [comment]
@argentinaluiz so i would prefer to update your posting into *i* **currently have** *the same issue* to avoid misunderstandings here ;)

**Comment by argentinaluiz** [comment]
@michabbb Thanks!!
