### ISSUE TITLE
How to change Basic Auth "password" column?

### ISSUE THREAD

**Issue by Om3rCitak** [dingo/api#1213]
I want basic auth "password" is check the database "basic_token" column.

Database schema; id,name,email,password,basic_id,basic_token

I'm make it "email" column is "basic_id" use the code;

```
app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
   return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'basic_id');
});
```

But i don't change the "password" column -> "basic_token" column

**Comment by knox2** [comment]
Do you use the password field at all or the basic_token is the default?

**Comment by Om3rCitak** [comment]
@knox2 yes. unfortunately "password" column not editable on laravel. I'm solved to creating new middleware and using manuel login in middleware.

laravel manuel login: [http://laravel-recipes.com/recipes/221/manually-logging-a-user-in](http://laravel-recipes.com/recipes/221/manually-logging-a-user-in)

**Comment by knox2** [comment]
Indeed its not editable, though if you want to globally change the field you can add this method to your User model

```
public function getAuthPassword() {
    return $this->basic_token;
}
```
