### ISSUE TITLE
How to output API version in URL? 

### ISSUE THREAD

**Issue by Sogl** [dingo/api#1221]
Hello!

My configuration in `.env`:

```
PI_STANDARDS_TREE=x
API_SUBTYPE=drugs
API_PREFIX=api
API_VERSION=v1
API_NAME="Drugs project API"
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true
```

Routes in `api.php`:

``` php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['namespace' => 'App\Api\V1\Controllers'], function ($api) {
    $api->get('employees', 'EmployeeController@index');
    $api->get('employees/{id}', 'EmployeeController@show');

});
```

And finally my URL looks like this:

```
http://drugs.lar/laravel/public/api/employees
```

But I want to use `v1` in url, like this:

```
http://drugs.lar/laravel/public/api/v1/employees
```

How to do this?

**Comment by Sogl** [comment]
Did it with:
```php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['prefix' => 'api/v1', 'namespace' => 'App\Api\V1\Controllers'], function ($api) {
    $api->get('employees', 'EmployeeController@index');
    $api->get('employees/{id}', 'EmployeeController@show');
});
```

So... when I use version in URL, can I disable Accept header that described here in wiki?
https://github.com/dingo/api/wiki/Making-Requests-To-Your-API

**Comment by Sogl** [comment]
So... I found an error when use API calls in sequence: `Unable to boot ApiServiceProvider`.
Tried to fix by this comment:
https://github.com/dingo/api/issues/1074#issuecomment-236045896

I put line in `.env`:
```
API_PREFIX=api/v1
```

It works but now I can't use another API version in URL :disappointed: 

Example:
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['prefix' => 'api/v1', 'namespace' => 'App\Api\V1\Controllers'], function ($api) {

	$api->get('check', function(){
	    return 'Check';
	});

});


$api->version('v2', ['prefix' => 'api/v2', 'namespace' => 'App\Api\V2\Controllers'], function ($api) {

	$api->get('check', function(){
	    return 'Check';
	});

});
```

`v1/check` works, but `v2/check` show `Error 404`. 
Not works also when `API_PREFIX=api`

**Comment by Sogl** [comment]
Same without prefix and with `Accept` header. What I'm doing wrong?

**Comment by kingofswing** [comment]
It seems both ok when using Accept header with application/vnd.my_subtype.v1+json and ....v9+json, actually there is no v9 version api routes defined in api.php file .
