### ISSUE TITLE
Frontend / Backend totally separated. How do I authenticate my frontend

### ISSUE THREAD

**Issue by hosseinhkj** [dingo/api#1226]
My backend and frontend are totally separated. One using Laravel 5.3 the other using VueJS 2.

My frontend doesn't need to authenticate users (public website). however my backend should be able to recognize that the api requests and responses are being sent to my frontend and not some other client/frontend.

I know how to do this manually, but I would like to know if Dingo has such a feature to authenticate or approve requests based on the hostname making the calls?

**Comment by catalinux** [comment]
Yes, Dingo has auth trough tokens: https://github.com/dingo/api/wiki/Authentication

One problem is that Dingo is not fully compatible with l5.3. 

Other solution would be to use new feature from L5.3: https://laravel.com/docs/5.3/passport that is build specifically for API auth.

**Comment by hskrasek** [comment]
@catalinux The package should be fully compatible, just doesnt have Passport support yet. But @hosseinhkj you want to look into using either JWT based auth, or OAuth2, or any other auth that you can custom implement

**Comment by catalinux** [comment]
@hskrasek , sorry for missleading about l5.3

**Comment by hskrasek** [comment]
@catalinux no worries.
