### ISSUE TITLE
Laravel Policies, wrong status code

### ISSUE THREAD

**Issue by Germanaz0** [dingo/api#1229]
I am using Laravel policies, on my controller I call the method `$this->authorize('action')` , but when the user is unauthorised the system throws a 500 error status code, and it should be 401.

**Comment by catalinux** [comment]
Your code will probably throw a `Illuminate\Auth\Access\AuthorizationException` exception. You will have to setupa a handler for such an exception. For example in you appServiceProvider

```php
      $this->app->make('api.exception')->register(function (AuthorizationException$e) {
            abort(401, "Your message");
        });

**Comment by catalinux** [comment]
Otherwise you shold provide us your error logs

**Comment by Germanaz0** [comment]
@catalinux thanks, it worked

**Comment by Germanaz0** [comment]
@catalinux is there any way to replicate what you did, but using event handlers instead a cloujure in there ?

**Comment by hskrasek** [comment]
@Germanaz0 The dingo exception handle only allows registering closures. But those closures just dictate how to handle the exception, so technically you could use the closure/callback to pass the exception into Laravels event system
