### ISSUE TITLE
Authentication with jwt

### ISSUE THREAD

**Issue by m33ch** [dingo/api#1230]
Hi all,

i have latest version of laravel with jwt [package](https://github.com/tymondesigns/jwt-auth).
I read this [guide](https://github.com/tymondesigns/jwt-auth) to implement jwt on laravel 5.3.

In `config/api.php` i set dingo jwt provider : 

```
'auth' => [
        'jwt' => 'Dingo\Api\Auth\Provider\JWT',
],
```
Login function work correctly but when i try to access the protected route (with `$this->middleware('api.auth')` on construct on my controller) dingo response me with 401 code.

I don't know why this error occurs.

Where am I doing wrong?

Thanks

**Comment by knox2** [comment]
401 means unauthorized. Are you passing the token with your request

**Comment by catalinux** [comment]
Try adding your middleware in your route, not on your Controllers constructor. 

Also how do you pass your token to your request?

**Comment by m33ch** [comment]
Hi all, thanks for your reply.

> Are you passing the token with your request ?

Of course i added token on query `token={tokenString}` and on header `Authorization` with value `Bearer {tokenString}`

> Try adding your middleware in your route, not on your Controllers constructor.

I tried but same results.

Thanks

**Comment by catalinux** [comment]
Any errors on logs?

**Comment by m33ch** [comment]
Nothing ...

**Comment by m33ch** [comment]
Hi all,

i try to reinstall and reconfigure all. 
Now it's works!
I looked for the differences, but I found nothing.

Anyway thanks for your support.

**Comment by seuaCoder** [comment]
Interested on how to finx this

**Comment by prionkor** [comment]
Hello, 

Can you share your code how you are creating the login for jwt?
