### ISSUE TITLE
where should I add two facades shipped with the package

### ISSUE THREAD

**Issue by ahmadbadpey** [dingo/api#1231]
on the [Facade section of installation instruction](https://github.com/dingo/api/wiki/Installation#facades) , is said that there are two different Facades named `Dingo\Api\Facade\API` and `Dingo\Api\Facade\Route` that should be add.

But where? where can I add them?

**Comment by zemo20** [comment]
app/config.php

**Comment by hskrasek** [comment]
Like @zemo20 said, the `config/app.php` folder, should look something like this:

```php
'API' => Dingo\Api\Facade\API::class,
'Route' => Dingo\Api\Facade\Route::class, // You'll need to replace the Illuminate route facade for this one to work
```
