### ISSUE TITLE
Route Patterns Not Working

### ISSUE THREAD

**Issue by bbrink68** [dingo/api#1232]
Laravel 5.3
Dingo   1.0.*@dev

I've read in these issues: https://github.com/dingo/api/issues/741 & https://github.com/dingo/api/issues/724

That global defined patterns should work with Dingo API Router, but this is not the case.

``` php
    class RouteServiceProvider extends ServiceProvider {

        public function boot()
        {
            // Placed here - not working
            // Route::pattern('id', '[\d+]');

            parent::boot();
        }

        public function map()
        {
            // Tried here too, doesn't work.
            // Route::pattern('id', '[\d+]');

            $this->mapApiRoutes();

            $this->mapWebRoutes();
        }
    }
```

Has anyone gotten patterns to work with Dingo? How did you do it since I've read that it should work.

I've also tried injecting `Router` into the `map()` and `boot()` methods, still a no go.

**Comment by bbrink68** [comment]
Just found out that I needed to inject Laravel Router into the `map()` method in `RouteServiceProvider` like:

```
public function map(Router $router)
{
    $router->pattern('id', '[\d+]); // <-- Works
    Route::pattern('id', '[\d+]');    // <-- Does Not Work
}
```

**Comment by alexjose** [comment]
+1

**Comment by jasonlewis** [comment]
Can confirm they aren't working.

From a quick glance looks like the router patterns need to be merged in the Laravel routing adapter when the route is created.

**Comment by bitdagger** [comment]
Ran into this today myself. I was wondering why my route patterns weren't working, then I realized those routes were Dingo, not Laravel's router. A quick search later led me here.  

+1

**Comment by mehranhadidi** [comment]
so any fix? any suggestion?

**Comment by ntopulos** [comment]
Did anyone find some solution to this problem?

**Comment by specialtactics** [comment]
Hey guys

I've implemented this in the following PR, can you please try it and see if it works for you, without any unexpected results?

https://github.com/dingo/api/pull/1619

**Comment by christoph-kluge** [comment]
Hey @specialtactics, thanks for the support. I had this issue in the past and ignore it for a long time. Now I've tackled it again and discovered that we need to add the patterns already when adding the route to the adapter. Otherwise it will take the first route which is wrong. Here is an example:

```
$api->get('/entity/{uuid}')
$api->get('/entity/{slug}')
$api->get('/entity/{customIdentifier}')
```

I have a local working draft and forked the repo already. Will add the required changes soon.

**Comment by specialtactics** [comment]
Thanks @christoph-kluge - could you please pull latest and test again? If all good, we can close this one.

**Comment by christoph-kluge** [comment]
@specialtactics thank you for merging. I've briefly pulled and checked my usecases and the default laravel `Route::patterns()` does work out of the box now. 👍

**Comment by specialtactics** [comment]
Fantastic, closing.
