### ISSUE TITLE
how can i get current route name in dingo?

### ISSUE THREAD

**Issue by zhaohehe** [dingo/api#1235]
how can i get current route name in dingo?

**Comment by catalinux** [comment]
You have to use laravel/lumen own api.  I am not sure if you can get courent route name when you are in a middleware .

What error do you have?

**Comment by shibby** [comment]
this issue is related with laravel. with simple google search, you can find how to get name. 

for example; keyword: "laravel get current route name"
feeling lucky: http://stackoverflow.com/questions/30046691/how-to-get-current-route-name-in-laravel-5

:)

**Comment by zhaohehe** [comment]
thank you
