### ISSUE TITLE
Accessing the request in the Controller

### ISSUE THREAD

**Issue by tyteen4a03** [dingo/api#1237]
How do I access `$request` in the Controller? I used the normal Laravel method (`$request` as parameter of controller function) but nothing gets passed into that.

Nowhere in the wiki is there code to access `$request` as well.

**Comment by michabbb** [comment]
@tyteen4a03 so how do you get the request now?

**Comment by tyteen4a03** [comment]
@michabbb If you typehint `$request` as an instance of `Illuminate\Http\Request` it should get injected.
