### ISSUE TITLE
Add transformed results to meta

### ISSUE THREAD

**Issue by abhimanyu003** [dingo/api#1244]
I want some way to add random items with current request ( data ), so I decided to add them in `Meta`.

```
$randomItems = $this->collection(Item::orderByRaw('RAND()')->limit(5)->get(), new ItemTransformer($request));

return $this->response->paginator($collections, new ItemTransformer($request))
            ->setMeta([
                'random_items' => $randomItems
            ]);
```

But somehow I get result like this, which is including `Original` data and not the transformed one.

![image](https://cloud.githubusercontent.com/assets/265913/19839496/25bc4b1a-9f09-11e6-81f3-6dc04fbc4253.png)

Will be great if you can help in this.

**Comment by jasonlewis** [comment]
Meta doesn't isn't transformed. It's just meta data.

If you want to add associated resources then possibly look at Fractal includes.
