### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161: 

### ISSUE THREAD

**Issue by dhanabalanc** [dingo/api#1248]
Hi i have installed dingo package in laravel 5.1. If i access http://localhost:8000/hello

I got below error msg.
**NotFoundHttpException in RouteCollection.php line 161:**

**My Route Code:**
$api=app('Dingo\Api\Routing\Router');
$api->version('v1',function($api){
	$api->get('hello', 'App\Http\Controllers\HomeController@index');
});

How to fix ..

Regards,
Dhanabalan.c

**Comment by catalinux** [comment]
In your url you should add path api/ when testing

**Comment by dhanabalanc** [comment]
it is not working.. I have attached my routes list
![route](https://cloud.githubusercontent.com/assets/1265096/19921125/80f4034c-a102-11e6-8cec-102d05fbf535.png)

**Comment by catalinux** [comment]
What I am saying that if you add  a route like this: `$api->get('hello'` .. you should have a working url like this:

`GET /api/hello`. Testit in browser!

**Comment by dhanabalanc** [comment]
Thanks... 
http://localhost:8000/api/hello

But still it shows below error msg 

1/1
NotFoundHttpException in RouteCollection.php line 161:
in RouteCollection.php line 161
at RouteCollection->match(object(Request)) in Router.php line 750
at Router->findRoute(object(Request)) in Router.php line 659
at Router->dispatchToRoute(object(Request)) in Router.php line 635
at Router->dispatch(object(Request)) in Kernel.php line 236
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
at VerifyCsrfToken->handle(object(Request), object(Closure)

**Comment by catalinux** [comment]
Can you post your API_* variables defined in your .env file?

**Comment by shibamudi** [comment]
Same problem!

**Comment by shibamudi** [comment]
Same problem!

**Comment by shibamudi** [comment]
Same problem!

**Comment by shibamudi** [comment]
Same problem!

**Comment by shibamudi** [comment]
Same problem!

**Comment by andrietri** [comment]
same problem

**Comment by dhanabalanc** [comment]
Now Dingo Works Good ...

Please follow https://www.youtube.com/watch?v=r40yAZAi6PQ

To follow exact configuration in the video .. it works. Hope it helps.

**OR Try** 

php artisan cache:clear

Regards,
Dhanabalan.c

**Comment by asimshazad** [comment]
Same issue

**Comment by GoodJob** [comment]
Same issue, still not working ;(

**Comment by jasonlewis** [comment]
Make sure your environment variables are configured correctly. Check your prefix and domain (use one or the other, not both).

**Comment by jamesmaren** [comment]
none is working

**Comment by landrykapela** [comment]
Any fix?

**Comment by specialtactics** [comment]
@landrykapela This issue is quite old, please open a new issue if you have a problem. Make sure you are using the latest version of the package as well.
