### ISSUE TITLE
Api.auth vs Auth:api

### ISSUE THREAD

**Issue by BasConijn** [dingo/api#1251]
What is the difference between the dingo "api.auth" and the laravel's "auth:api"?

When an authorization exception is thrown, the "auth:api" returns http 500.

**Comment by seancheung** [comment]
`auth:api` refers to Laravel's `auth` middleware with `api` guard, which by default requires an `api_token` column in your user table. Missing that column may give you 500 internal error.

**Comment by jasonlewis** [comment]
If you're using Dingo I advise to use Dingo's authentication handling which is the `api.auth` middleware.
