### ISSUE TITLE
Missing argument 4 for Dingo\Blueprint\Blueprint::generate()

### ISSUE THREAD

**Issue by pabloalbrecht** [dingo/api#1252]
When trying to generate the documentation for an API, I get the following error message:
![image](https://cloud.githubusercontent.com/assets/1114806/20053371/16aa84bc-a4d0-11e6-8bd5-fc8aef30d98b.png)

my composer dingo require: "dingo/api": "1.0.x@dev"

**Comment by hskrasek** [comment]
This is closed by https://github.com/dingo/blueprint/pull/36 getting merged. Not an api package issue, but a blueprint package issue.
