### ISSUE TITLE
php artisan api:cache final if no Laravel routes

### ISSUE THREAD

**Issue by oleynikd** [dingo/api#1253]
If you have no pure Laravel routes in your app the `php artisan api:cache` will fail because of [this line](https://github.com/dingo/api/blob/master/src/Console/Command/Cache.php#L57) as Laravel's `route:cache` will return error in this case [here](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Console/RouteCacheCommand.php#L57)

**Comment by sevmardi** [comment]
I second this problem

**Comment by falstack** [comment]
I have this problem too

**Comment by zoulux** [comment]
I have this problem too

**Comment by specialtactics** [comment]
You should not be using api:cache, it actually causes performance problems even in vanilla laravel.
