### ISSUE TITLE
Multiple model transformers: Wrong transformer used

### ISSUE THREAD

**Issue by cweiske** [dingo/api#1267]
I've got a model and two transformer classes for that model (because depending on the controller, different data need to be returned).

Now I have the problem that I explicitely set a transformer to my controller's index method's paginator return value, but that one is not used:

    return $this->response->paginator($users, new \Foo\A\UserTransformer);

The app crashes because `\Foo\B\UserTransformer` is used instead, and the users do not fulfil some of the requirements the B transformer expects.

----

Debugging this issue leads to the following stages:

1. index action method returns result with transformer object
2. dingo saves model-class-to-transformer mapping in TransformerFactory
3. dingo creates instances of *all* controllers (while setting up the routes)
4. controller constructor registers transformation that is only required in his class) and overwrites the class-to-transformer mapping in TransformerFactory
5. wrong transformer is used to transform objects

----

Trace where the controllers are instantiated:

```
55. Dingo\Api\Provider\RoutingServiceProvider->Dingo\Api\Provider\{closure}()
56. Dingo\Api\Routing\Router->getRoutes()
57. Dingo\Api\Routing\Router->createRoute()
58. Dingo\Api\Routing\Route->__construct()
59. Dingo\Api\Routing\Route->setupRouteProperties()
60. Dingo\Api\Routing\Route->mergeControllerProperties()
61. Dingo\Api\Routing\Route->makeControllerInstance()
62. Illuminate\Foundation\Application->make()
63. Illuminate\Container\Container->make()
64. Illuminate\Container\Container->build() 
65. ReflectionClass->newInstanceArgs()
66. Immogic\Http\Controllers\Api\ProducerDb\ProducersController->__construct()
```

----

I could solve this issue by stop registering them at all and always explicitely use pass the transformer in every return statement in my action methods.

But I wish that I could register my transformers where I wanted and still have the option to pass a per-action transformer to the paginator.

**Comment by specialtactics** [comment]
Closing due to age, if still a problem, feel free to resubmit
