### ISSUE TITLE
Call to undefined method Illuminate\Routing\Router::api()

### ISSUE THREAD

**Issue by marcinlawnik** [dingo/api#127]
Today I wanted to try and make my first API using laravel and this package.

I have trouble configuring it to work properly.

First I've changed the version to the latest one on dev-master by using composer to walk around the issue #121 (There is no API route collection...)

I added the service provider.

Then I have published the configuration.
I also added aliases like so:

```
'aliases' => array(

    //API
    'API'             => 'Dingo\Api\Facades\API',
    //Controller class from Laravel
    //'Controller'    => 'Illuminate\Routing\Controller',
    //Controller from dingo/api
    'Controller'      => 'Dingo\Api\Routing\Controller',

),
```

After loading up my app, I encountered the following error:

```
PHP Fatal error:  Call to undefined method Illuminate\Routing\Router::api() in /home/marcin/phpStormProjects/DziennikLoginWebNew/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 211
```

It seems laravel tries to use it's own routing class instead of the one provided by the package. How do I configure it to resolve correctly?

**Comment by juanjolainez** [comment]
There's an incompatibility with Mcamara/LaravelLocalization package as well. 

No matter what order I set it up, it throws the error: 
````
Call to undefined method Illuminate\Routing\Router::api()
```

If I comment Mcamara library it's working just fine

**Comment by Braunson** [comment]
Any solutions to these incompatibilities?

**Comment by CreativityKills** [comment]
Okay I'm beginning to think there's something seriously wrong with the package but I cannot for the life of me figure it out.

One second it works, I shut down come back to my application and suddenly it no longer works. If i uncomment or reorder my service providers by moving it lower it works but my app breaks because the custom package's service provider relies on dingo. This is really frustrating

**Comment by potsky** [comment]
@juanjolainez Have you found a solution to support both `Dingo API` and `Mcamara/LaravelLocalization` ?

**Comment by juanjolainez** [comment]
@potsky no, I stopped using this package

**Comment by potsky** [comment]
@juanjolainez Thanx for your answer ! Have you found a better package or do you write it finally by yourself ?

**Comment by juanjolainez** [comment]
I wrote it myself...
