### ISSUE TITLE
Cannot Override Route

### ISSUE THREAD

**Issue by aldee07** [dingo/api#1272]
For some reason, I cannot override a route using dingo/api.  Please find my route code below.

```php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This is where you should define your controller routes. We make use of
| `dingo/api`'s `api.router` service to define our routings.
|
*/


$api = app('api.router');
$api->version('v1', function ($api) {

    $api->group(['namespace' => \Other\Places\Controllers::class], function ($api) {
        $api->post('/auth/login', 'AuthController@login');
    });

    $api->group(['namespace' => \App\Http\Controllers::class], function ($api) {
        $api->post('/auth/login', 'AuthController@login');
    });

});
```

I need something like this since the first group will be inside a separate package while the second will be the overridden route (in case of customization). 

Please advise.

**Comment by aldee07** [comment]
By the way I am using **"dingo/api": "1.0.*@dev",**

**Comment by hskrasek** [comment]
Dingo/API doesn't support the ability to override routes. Never had to override routes before, but I'm pretty certain that the last registered route is the one that would be picked. Aka your `\App\Http\Controllers::class` namespace would be the registered route.

If the other route is going to be in a package, you'd have to make sure your packages routes are registered before the frameworks routes are, by placing your service provider above the `App\Providers\RouteServiceProvider`
