### ISSUE TITLE
thephpleague/fractal - Include Parameters not possible on nested Includes

### ISSUE THREAD

**Issue by soubhikchatterjee** [dingo/api#1274]
I going through this http://fractal.thephpleague.com/transformers/ but unable to make the following endpoint work:

`book/?include=comment:limit(5)`

When I hit the above endpoint, i get the error 

`Call to undefined relationship [comment:limit(5)] on model [...]`

Basically I want to limit the number of comments per book to 5.

What am I missing here?

**Comment by weiwenhao** [comment]
@soubhikchatterjee You can try this [weiwenhao/tree-ql](https://github.com/weiwenhao/tree-ql)
