### ISSUE TITLE
Change format without header "Accept"

### ISSUE THREAD

**Issue by tjvanderende** [dingo/api#1278]
Hello,

Currently I can make a request to my endpoints with Postman client using "Accept: x.subtype.v1+xml".
Everthing works fine, the data displays in XML.
However, some other endpoints should display as JSON.

I use third party service to include my URL, so I have no control of adding the Accept header.
I did try to do it with the method `$this->request->withHeaders("Accept", "xxxx"`, The accept header changes, but the format type is still "application/json".

Is there anyway to set the format without using the Accept header?

**Comment by hskrasek** [comment]
There is not, the package determines the response format via the Accept header.

**Comment by tjvanderende** [comment]
Thank you for your answer.
I understand, but is there anyway I can call it internally?
It doesn't work with the function `withHeaders("Accept", "xxx" )`. Is that normal behavior?

**Comment by jasonlewis** [comment]
You would need to set the header internally VERY early, most likely in a middleware if you can.
