### ISSUE TITLE
invalid the before token after anthor user auth?

### ISSUE THREAD

**Issue by zhangyuxiao** [dingo/api#1289]
how can i do this ? tks~

**Comment by jasonlewis** [comment]
Can you elaborate on what you're trying to achieve? Cheers.

**Comment by zhangyuxiao** [comment]
Thank you very much for your concern.My problem has been solved.
My problem is:
I use dingo and OAuth 2.0 to configure my system，
After a user login will get a token1, when the user in another client login, the user will get a new token2, I hope that the previous token1 expired invalid

My solution is to update the database under the expiration of the time, if can configure the configuration of the configuration file，that will better
@jasonlewis
