### ISSUE TITLE
[REQUEST] make API version and API name visible in URL

### ISSUE THREAD

**Issue by christian-roggia** [dingo/api#1290]
API version and API name should be made available in the URL through the API config file _config/api.php_.

Google API URLs:
`https://www.googleapis.com/youtube/v3/activities`
`https://www.googleapis.com/urlshortener/v1/url`

More examples:
https://developers.google.com/apis-explorer/#p/

**Comment by jasonlewis** [comment]
This is where Dingo is fairly opinionated. Versioning should be done by content negotiation, not in the URI.
