### ISSUE TITLE
Two subdomain problem

### ISSUE THREAD

**Issue by nerijunior** [dingo/api#1292]
Hi,

That's the `.env`:
```ini
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://api.dev.app.com

API_DEBUG=true
API_STANDARDS_TREE=vnd
API_DOMAIN=api.dev.app.com
API_VERSION=v1
API_NAME="My App"
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=myapp
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

```

I don't know why but every request returns a 405 `Method Not Allowed`, but if I put the same code on the api.app.com ( without the `.dev` ) works fine.

**Comment by jasonlewis** [comment]
If this is a standalone Dingo API application then just use `API_PREFIX=/`, that's usually my preference.

**Comment by nerijunior** [comment]
@jasonlewis Using `API_DOMAIN` as I said or `API_PREFIX` i got the same error.

**Comment by jasonlewis** [comment]
Just did a quick test and it's working fine here using either method (though like I said, if it's standalone API use `API_PREFIX=/`).

**Comment by andrewmclagan** [comment]
ah ... `/` this has saved my life... 

We use docker to orchestrate all our Laravel apps that make up our API. DNS and service discovery is a little more complicated in this scenario and a simple environment variable with the domain just was not going to work.

This worked a charm

**Comment by nerijunior** [comment]
@jasonlewis Do u can send me all the API_* env configs? I'm using:

```
API_DEBUG=true
API_STANDARDS_TREE=vnd
API_PREFIX=/
API_VERSION=v1
API_NAME="My App"
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json
```

And the problem persist.
