### ISSUE TITLE
Auth guard driver [api] is not defined

### ISSUE THREAD

**Issue by drosendo** [dingo/api#1300]
On setting using lucadegasperi/oauth2-server-laravel, I get `Auth guard driver [api] is not defined` any help?

**Comment by kingsloi** [comment]
I'm going on a whim here, but I'm 99% sure you're missing an `api` entry in your `config/auth.php` file. 

Something like this:

```  
        ...      
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ]
```

Hope that helps @drosendo

**Comment by drosendo** [comment]
I was missing a file. :/ lololol
