### ISSUE TITLE
when doing an internal request, the data has not passed through the formatter

### ISSUE THREAD

**Issue by kife-design** [dingo/api#1303]
When i do a http request to an endpoint on the api, i get an object with a data key and the formatted items.

But when i do that same request through $this->api->get then the data that is returned has not passed through the formatter.

How do i make sure that the data that is returned has passed the formatter on internal requests?

**Comment by jasonlewis** [comment]
You probably want the raw responce object.

https://github.com/dingo/api/wiki/Internal-Requests#retrieve-raw-response-object
