### ISSUE TITLE
laravel 5.3 Auth::check() not working in api

### ISSUE THREAD

**Issue by Panigale** [dingo/api#1304]
I've been upgrade from 5.1 to 5.3 ,on 5.1 it's work fine ,but when I upgrade to 5.3 Auth::check() is always return false ,Here it my source code:

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {

    $api->any('/{classification}/{method}','App\Http\Controllers\Api\ApiController@createMethod');

    //when i call api ,Auth::check() will always return false
});

//ApiController

 public function createMethod(Request $request ,$classification ,$method){
    dd(Auth::check) -> print  false ,other routers will print true 
}

is this a bug or i should use Api auth?

**Comment by jasonlewis** [comment]
Make sure you're using the correct middlewares on your routes. If you're using Laravel's authentication then make sure that middleware is used. Otherwise make sure you're using Dingo's `api.auth` middleware.
