### ISSUE TITLE
Laravel 5.4 conflicts

### ISSUE THREAD

**Issue by mehrdaad** [dingo/api#1311]
Apparently, dingo version ``1.0.0-beta7`` has conflicts with Laravel 5.4.  
Most packages like ``illuminate/routing`` in dingo requires 5.3.  
When is that going to be fixed?

**Comment by vesper8** [comment]
+1

**Comment by andrewmclagan** [comment]
See https://github.com/dingo/api/pull/1314

seems to cover this.

**Comment by mehrdaad** [comment]
@jasonlewis when will the new branch be released?

**Comment by Elema82** [comment]
it work for me.
#1317

**Comment by andrewmclagan** [comment]
Also seems fine #1317
