### ISSUE TITLE
Any plans for Laravel 5.4 ? 

### ISSUE THREAD

**Issue by EmadAdly** [dingo/api#1318]

**Comment by imagine10255** [comment]
+1

**Comment by mifas** [comment]
+1

**Comment by bakerstreetsystems** [comment]
+1

**Comment by neoighodaro** [comment]
+1

**Comment by floodedcodeboy** [comment]
+1

**Comment by ledzgio** [comment]
+1

**Comment by gettosin4me** [comment]
+1

**Comment by asamaru7** [comment]
+1

**Comment by bryanrscott** [comment]
+1

**Comment by driesvints** [comment]
@jasonlewis @hskrasek can you perhaps tag a new beta release?

**Comment by ohanspace** [comment]
+1

**Comment by rsdev000** [comment]
What about Lumen 5.4.x ?

**Comment by cmzz** [comment]
+1

**Comment by justinatack** [comment]
+1

**Comment by francescomalatesta** [comment]
+1

**Comment by Wit3** [comment]
+1

**Comment by wlwr** [comment]
+1

**Comment by driesvints** [comment]
Please stop +1'ng this and use reactions. You're only spamming all of the people subscribed to this issue.

**Comment by hskrasek** [comment]
Gonna side with @driesvints on this one, I appreciate everyones excitement for using dingo/api with the most recent version of Laravel, but the email spam doesn't help out.

Apologies for the delay, @jasonlewis and I have been pretty busy but I just tagged beta8 which should cover Laravel 5.4 now.

**Comment by driesvints** [comment]
@hskrasek thanks! 👊

**Comment by rsdev000** [comment]
Is there any special reason to not upgrade lumen to 5.4.x ?

**Comment by alinasiri1367** [comment]
+10

**Comment by catalinux** [comment]
It works on lumen 5.4. Are there any problems in laravel 5.4?
