### ISSUE TITLE
Eager loading nested includes

### ISSUE THREAD

**Issue by renspoesse** [dingo/api#1327]
I'm not entirely clear on how to enable eager loading for nested includes in a Transformer.

```
class MyController extends BaseController
{
    public function index()
    {
        return $this->response->collection(Address::all(), new AddressTransformer());
    }
}

class AddressTransformer extends TransformerAbstract
{
    protected $defaultIncludes = ['country'];

    public function includeCountry(Address $obj)
    {
        return $obj->country ? $this->item($obj->country, new CountryTransformer()) : null;
    }
}

class CountryTransformer extends TransformerAbstract
{
    protected $defaultIncludes = ['languages'];

    public function includeLanguage(Country $obj)
    {
        return $obj->languages ? $this->collection($obj->languages, new LanguageTransformer()) : null;
    }
}
```

**The problem:** all countries belonging to addresses are eager loaded by Dingo, because it recognizes the defaultIncludes. However, languages that are nested within countries are still lazy loaded.

What would be the cleanest way to go about this?

**Comment by abhimanyu003** [comment]
@renspoesse are you able to find workaround over this.

**Comment by renspoesse** [comment]
@abhimanyu003 I just stopped using default includes. You'll probably find a way to do it if you look at the sources, but it will be hacky.

**Comment by alexgiuvara** [comment]
I found a fix for this issue if anyone bumps into `lazily loaded includes`: https://medium.com/@giuvara.alex/how-to-solve-the-n-1-problem-introduced-by-fractal-7ba7936b8b81
