### ISSUE TITLE
question of using HTTP Basic Authentication

### ISSUE THREAD

**Issue by alyadan** [dingo/api#1328]
I configuration  HTTP Basic Authentication follow the Wiki 

1. add below code to AppServiceProvider boot method
`app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
   return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
});`

2. add middleware to api router group
          `$api->version('v1',
            ['middleware' => 'api.auth'],
            function ($api) {
            $api->get('t1', 'App\Http\Controllers\TestApiController@test');
            });`

when I request the api , I get the below error tips
    `"message": "Call to undefined method Dingo\\Api\\Auth\\Auth::handle()",`
    `"status_code": 500,`

Do anyone know what's the wrong?

**Comment by cona88** [comment]
I same issue in Laravel 5.4

**Comment by cona88** [comment]
Hi all,
I custom Exception Responses, it have erorr: "message": "Call to undefined method Dingo\\Api\\Auth\\Auth::handle()",
"status_code": 500,
please help

**Comment by alyadan** [comment]
now I'm sure it's support issue for laravel 5.4. When I use laravel5.3 these problem is go away
