### ISSUE TITLE
use of transformations

### ISSUE THREAD

**Issue by physio** [dingo/api#1340]
hello, excuse my poor english.
I think this is a really very interested project developers API.

How i can work with the relationship?

I understand that the use of transformers is done about this:
from
```
return Author:all()->paginate(10);
```
to
```
$List = Author:all()->paginate(10);
return $this->response->withPaginator($list, new authorTransformer);
```

but if I need this?
```
return Author::all()->with( 'books', 'Pubblications');
```

in wiki documentation i cannot found info.

**Comment by physio** [comment]
I have resolved, sorry. 
For future i post an issue that explain how we must work with relationship: [https://github.com/spatie/laravel-fractal/issues/23](url)

thanks

**Comment by catalinux** [comment]
Your link does not work
