### ISSUE TITLE
global middleware is not terminate

### ISSUE THREAD

**Issue by miklcct** [dingo/api#1342]
Dingo does not check the global middleware list on Laravel when terminating in \Dingo\Api\Http\Middleware\Request::terminate(), therefore the global middlewares are not terminated.

**Comment by BAN1ce** [comment]
@miklcct Did you resolve this problem? I met same .

**Comment by miklcct** [comment]
> @miklcct Did you resolve this problem? I met same .

I've already ditched dingo in all my projects because dingo is heavy, cumbersome, and worse than plain laravel. I immediately got performance improvement after ditching dingo.

**Comment by BAN1ce** [comment]
@miklcct I find how to resolve, just re put the middleware in the Dingo/Lumen . So ,you use laravel original restful api ?

**Comment by specialtactics** [comment]
I think the best way to resolve this would be for Dingo to just use the Laravel router.

As a workaround, just put middlewares in the api routing.
