### ISSUE TITLE
Issue with UUID ids being cast to INT

### ISSUE THREAD

**Issue by fibble** [dingo/api#1343]
Hi,

When i am returning data from dingo i think Fractal is assuming the id fields it finds should be integers, but i am using UUIDs for all table PKs. Could someone provide an example or some guidance on the best way/place to override or instantiate Fractal to adjust the transformer/serializer responsible for this? I couldnt figure it out from the wiki documentation.

e.,g 

`id => 980a09e0-f913-11e6-b12d-e75d518b781a` 

becomes

`id => 980 `

Thanks

**Comment by catalinux** [comment]
What serialzer are you using?

**Comment by fibble** [comment]
default JSON one
e.g.

```
$user = Auth::user();
return $this->response->array(['user' => $user]);
```

**Comment by fibble** [comment]
My bad.

I had used my UUID trait on my BaseModel but hadnt included this property:

`public $incrementing = false;`

Adding this to my models has resolved the issue of UUIDs being cast as INTs in the JSON response.

**Comment by helipillo** [comment]
Thanks @fibble. It worked like a charm.
