### ISSUE TITLE
In global middleware method "currentRouteAction" is does't work

### ISSUE THREAD

**Issue by MrVokia** [dingo/api#1345]
```php
// The method is does't work, It's return null
app('Dingo\Api\Routing\Router')->currentRouteAction()
```

also, ```$route``` is undefined in this file, why?
https://github.com/dingo/api/blob/master/src/Routing/Router.php#L814-L818

**Comment by catalinux** [comment]
Why do you say $route is undefined?

**Comment by MrVokia** [comment]
Oh, sorry, I made a mistake. @catalinux
