### ISSUE TITLE
How to define a default version

### ISSUE THREAD

**Issue by MrVokia** [dingo/api#1350]
How to define a default version in the absence of `Accept`?

I try it:
```php
$app->group(['middleware' => 'api.version'], function ($app) {
    require __DIR__.'/../routes/api.php';
});
```

```php
public function handle($request, Closure $next)
{
   if( ! $request->header('Accept') ) {
        // $defaultVersion = config('api.standardsTree')...;
        $request->header('Accept', 'application/x.test.v1+json');
   }
   return $next($request);
}
```

but it's not work

**Comment by baijunyao** [comment]
You want this?

This version is the default version of your API and is used as a fallback in several circumstances whenever a version is not supplied. This version is also used as a default version for when generating API documentation.
You can also configure this in your .env file.
```
API_VERSION=v1
```
[https://github.com/dingo/api/wiki/Configuration](https://github.com/dingo/api/wiki/Configuration)
