### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes)

### ISSUE THREAD

**Issue by Mankeke** [dingo/api#1351]
Hello, I installed the latest version of dingo and when i add     **Dingo\Api\Provider\LaravelServiceProvider::class**  to the providers' section and then i try to run any php command such as artisan it crashes with an error of running out of memory rendering everything unusable.

`Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/productos/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 549
`

I am using Laravel 5.4, dingo and entrust, the project is a brand new one so there's nothing obscure as far as i can tell. If i remove the aforementioned line and rerun the commands, everything works perfectly.
My box is based on ubuntu server 16.04 with php 7 and nginx and is configured using vagrant initially with 1GB of RAM and i increased it to 2 just in case. I also tried the memory_limit modifications in the php config files.

`$ php -v                
PHP 7.0.16-3+deb.sury.org~xenial+1 (cli) (built: Feb 22 2017 10:05:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-3+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
`

[composer.txt](https://github.com/dingo/api/files/829888/composer.txt)

Has anyone else experienced something similar? Googling it many had problems with composer but this is not the case

**Comment by eshleebien** [comment]
Did you put it to the Package Service Providers section of providers?

```
// config/app.php
...
'providers' => [
        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        ...

        /*
         * Package Service Providers...
         */
        Dingo\Api\Provider\LaravelServiceProvider::class,

        ....

        /*
         * Application Service Providers...
         */


],

**Comment by mirko77** [comment]
You probably have a syntax error in your /config/app.php

I missed a comma on mine and it trashed the server!

**Comment by handyliu2000** [comment]
i just type php artisan clear:cache , php artisan clear, composer auto-dump and everthing is ok

**Comment by from2day** [comment]
Most of the times it comes down to syntax error.
Try suggestions of @handyliu2000
