### ISSUE TITLE
Request Methods?

### ISSUE THREAD

**Issue by andyslater99** [dingo/api#1358]
Hi,

Im working on creating some new Dingo API endpoints and everything was working well until I started trying to use different request methods. For example my routes file creates the following endpoints:

POST | /api/System/Orders | App\Http\Controllers\SystemApi\Service@runPostService | No | v1 |

DELETE | /api/System/Orders | App\Http\Controllers\SystemApi\Service@runDeleteService | No | v1 |

GET|HEAD | /api/System/Orders | App\Http\Controllers\SystemApi\Service@runGetService | No | v1

However, when sending requests to the endpoints via Postman the system never gets to runPostService or runDeleteService, noticing that via Xdebug every request method is being registered as a GET, therefore every request goes to the runGetService function.

Seems like I'm maybe missing something really simple, if anyone else has any experience with this?, Im using Laravel 5.4 and Dingo API

Andy

**Comment by rdpascua** [comment]
Can you share your `.env` file? did you configure it correctly? Mines looks like this

```
API_NAME=hello
API_PREFIX=api
API_VERSION=v1
API_DEBUG=true
```

**Comment by andyslater99** [comment]
Hi rdpascua,

API_STANDARDS_TREE=vnd
API_SUBTYPE=orders
API_PREFIX=api
API_VERSION=v1
API_NAME="Orders API"
API_STRICT=false
API_DEBUG=true
API_DEFAULT_FORMAT=json

Andy

**Comment by rdpascua** [comment]
Do you have any public route for this ? to test? I'm using Laravel 5.4 as well but it works flawlessly. I've been using this ever since.

**Comment by andyslater99** [comment]
Hi rdpascua,

https://github.com/postmanlabs/postman-app-support/issues/391

Actually looks like an issue with Postman on OSX, it works as expected using Boomerang, thanks for your help!

Andy

**Comment by andyslater99** [comment]
Hi All,

Just to follow this up it was actually redirecting the trailing slash on the API URL, Postman had a setting which followed the redirect, however in Laravel once redirect the request method was actually a GET. Hope this helps if anyone else comes across.

Andy
