### ISSUE TITLE
Where to put 'auth' => [ 'jwt' => 'Dingo\Api\Auth\Provider\JWT', ] ? Laravel 5.3

### ISSUE THREAD

**Issue by Drakota** [dingo/api#1364]
Hi, right now I have this problem where I can generate a token just fine, but I get this message `Failed to authenticate because of bad credentials or an invalid authorization header.`
I searched a little and found out people got this problem fixed by adding
`'auth' => [ 'jwt' => 'Dingo\Api\Auth\Provider\JWT', ]`
in config/api.php, but I don't have this file.
I'm using Laravel 5.3
Thanks for helping.

**Comment by diego-vieira** [comment]
https://github.com/dingo/api#support
