### ISSUE TITLE
Role based protected endpoints?

### ISSUE THREAD

**Issue by Drakota** [dingo/api#1368]
Hi, I wish to protect some endpoints if the client is a user or a manager. This does not work, but this is what I hope for without having to check if the client is a user in each endpoint manually.
![image](https://cloud.githubusercontent.com/assets/22665836/24940720/fdee0210-1f12-11e7-99ea-7903cd9e46af.png)

**Comment by vinterskogen** [comment]
That can be done by adding a standard Laravel middleware layer (one middleware class for each role). See the [middleware docs](https://laravel.com/docs/5.4/middleware) page. That middleware should check if the user has the specified role (user/manager/etc.) and passes only the proper requests next to the controllers' methods (all other requests may by responded with "403 Forbidden" page, or a redirected to "/" (home) page, or so). Then this middleware should be applied to the group of routes (Dingo supports routes groups, check the [Creating API Endpoints](https://github.com/dingo/api/wiki/Creating-API-Endpoints) page).

**Comment by specialtactics** [comment]
@Drakota Have a look at my project, it comes built-in with this feature, and uses dingo.

https://github.com/specialtactics/laravel5-api-boilerplate

**Comment by Drakota** [comment]
Will give a look, thanks!
