### ISSUE TITLE
API_PREFIX and API_DOMAIN

### ISSUE THREAD

**Issue by Doublemedia** [dingo/api#1369]
Hello,

I have an configuration issue.
When I have the following:

'prefix' => env('API_PREFIX', 'api'),
'domain' => env('API_DOMAIN', 'http://mlm'),

Everything works. The only issue is that DINGO also is seeing the routes/web.php as api endpoints.
So when I change api_domain to http://mlm/api DINGO doens't see them as api endpoints anymore.
But then another issues occurs. The api routes don't work anymore. I though this is due to the API_PREFIX, but when I remove this I still get 404 on the api routes that worked well with the old configuration.

Any thougs on this issue?

php artisan api:route is telling me that the routes are the same as i'm executing them.

What I want is GET http://mlm/api/products.

Kind regards,

Erwin

**Comment by Doublemedia** [comment]
Someone pointed out to me that they shouldnt be used together.
So i cleared the domain config item and everything is working as it should be.

**Comment by nehasharma1997** [comment]
What do you mean `cleared the domain config item`  I am facing the same issue.

**Comment by specialtactics** [comment]
Great to hear!
