### ISSUE TITLE
Error: Call to undefined method Dingo\Api\Http\Response

### ISSUE THREAD

**Issue by physio** [dingo/api#1372]
when i run phpunit from console, when my tests call an api, i give always the same response, independently by method tha i use: seeStatusCode(), seejson(), ecc.

i use PHPUnit 5.7.19, laravel 5.4, and "dingo/api": "1.0.*@dev".

can you help me?

**Comment by CLOUGH** [comment]
1+

**Comment by physio** [comment]
these method in 5.4 has changed.

**Comment by ChenAlon** [comment]
the `assertJson` method can be the answer.
Check the 5.4 documentation for [Testing JSON Api's](https://laravel.com/docs/5.4/http-tests#testing-json-apis).

**Comment by dynarizkihabibah** [comment]
i'm facing the same problem, when my tests call different api, with different method (delete, put, post), and always the same response:
    "message": "Undefined method Dingo\\Api\\Http\\Response\\Factory::message",
    "status_code": 500

i use:
phpunit/phpunit: ~4.0
laravel/lumen-framework: 5.3.*
dingo/api: 1.0.*@dev

can anyone help me?
