### ISSUE TITLE
POST method not allowed

### ISSUE THREAD

**Issue by tharakabimal** [dingo/api#1373]
I get "405 Method Not Allowed" only for POST methods

![screen shot 2017-04-18 at 11 59 27 am](https://cloud.githubusercontent.com/assets/3351988/25117204/98d16d56-242e-11e7-9641-e5191c57ff29.png)

**Comment by Samadhini** [comment]
I'm facing with same kind of issue. when we checked with api:routes it shows POST request. but when i tested using postman it give 405 error.

**Comment by FascistDonut** [comment]
Same here

**Comment by Samadhini** [comment]
I found the solution for this problem. The problem was post request rejected by the middleware. when the request is coming from api then we can ignore csrf token.using this way i fixed the issue.

**Comment by soclosed** [comment]
How do you do that? I have the same issue...
