### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by BartHuis** [dingo/api#1374]
Hi,
I'm about to use this package in a big project, as it's referred by jwt-auth that we wanted to use anyway, this package seemed very useful for us. This package is being developed since 2014, when i look to the past, there are some peaks in development, at this moment it's quit, does that mean everything runs smooth? If so, why isn't there a stable version yet? in the installation docs there's still the message: "At this time the package is still in a developmental stage and as such does not have a stable release. You may need to set your minimum-stability to dev.".
Why?
Bart

**Comment by vinterskogen** [comment]
Also really interested is the answer for the same question. Hope @jasonlewis or @hskrasek will pay attention on this issue to answer it.

**Comment by Mahmoudz** [comment]
#1383

**Comment by from2day** [comment]
Not stable yet. More details here #1436
