### ISSUE TITLE
Is Dingo API still alive?

### ISSUE THREAD

**Issue by trbsi** [dingo/api#1383]
I see a lot of opened issues and old commits. Is it still alive?

**Comment by a2htray** [comment]
it seems deadly

**Comment by lukasoppermann** [comment]
Pretty sure it is still alive, @hskrasek is maintaining it in his free time, so it may need some time. However, there was a commit in feb this year.

However, maybe there need to be some additional contributors with merge rights, as it is quite a lot of work to maintain a project like this alone.

**Comment by trbsi** [comment]
Cool then :)

**Comment by maj0rr** [comment]
I hope work will continue soon 👍

**Comment by aburakovskiy** [comment]
May be some donates https://beerpay.io/ will help?))

**Comment by catalinux** [comment]
First of all: it works. So for me, this means  it's alive.  I use it on Lumen projects

**Comment by Mahmoudz** [comment]
I've used this package for many projects and it's really cool. However, I've moved to using [APIATO](https://github.com/apiato/apiato) which is a framework for building API-Centric Apps on top of Laravel.

**Comment by trbsi** [comment]
Damn, I wish I knew about Apiato sooner

**Comment by peinhu** [comment]
it's gone

**Comment by from2day** [comment]
Closing this because we have answered here #1436
