### ISSUE TITLE
not work in laravel 5.4

### ISSUE THREAD

**Issue by arman666a** [dingo/api#1388]
hi 
i'm try to work this package on laravel 5.4 but routing not work!
Is this package of Laravel 5.4 support ؟

**Comment by jonathanlaflamme** [comment]
Is it possible to be more specific? I'm working with Laravel 5.4 and it works fine.

**Comment by silasrm** [comment]
Hi @arman666a,

I'm using with 5.4. But I've trouble with Transformer. First, is required exists setCurrentScope method in transformers and the documentation don't says that. After add this occurs other error:

```
Missing argument 2 for App\\Transformers\\UserMeTransformer::transform(), called in /app/vendor/league/fractal/src/Scope.php on line 376 and defined
```
What is your problem?

**Comment by silasrm** [comment]
Hi @arman666a,

I solve my problem with this https://github.com/spatie/laravel-fractal/issues/23

**Comment by bravist** [comment]
Use the version

```php
"dingo/api": "1.0.x@dev",
```

**Comment by huuhoa0506** [comment]
@silasrm What's version you using ?  5.4.?

**Comment by sourabhkum** [comment]
I'm using Laravel 5.4 with dingo/api": "1.0.x@dev" 
When am calling the api under the middleware middleware'=>'api.auth
got the error [Call to undefined method Dingo\Api\Auth\Auth::handle()", "status_code": 500,]

**Comment by bravist** [comment]
@sourabhkum you can paste the error stack

**Comment by sourabhkum** [comment]
{
    "message": "Call to undefined method Dingo\\Api\\Auth\\Auth::handle()",
    "status_code": 500,
    "debug": {
        "line": 148,
        "file": "C:\\Users\\sourabh\\Desktop\\api_demo\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
        "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",

**Comment by from2day** [comment]
For the Laravel 5.4 use `"dingo/api": "1.0.0-beta8"` version.
If anything try to create new issue and fill suggested details.
