### ISSUE TITLE
where is the status code(204) when noContent() is called?

### ISSUE THREAD

**Issue by 839891627** [dingo/api#1390]
after update a record, i `return $this->response->noContent()`, and the response headers status is `200 ok`, but can't find status code(204) in  response neither headers nor body. 

![qq 20170517134414](https://cloud.githubusercontent.com/assets/10300651/26139997/f3fc06a2-3b06-11e7-881a-2a84a1729c70.png)

where i'am wrong?

**Comment by meistocko** [comment]
Postman shows the response code on the right hand side. 

https://www.getpostman.com/docs/responses

**Comment by 839891627** [comment]
@meistocko yeah，i know，but it shows `200 ok`
![qq 20170525140418](https://cloud.githubusercontent.com/assets/10300651/26438068/5796fe4a-4153-11e7-979a-975026aa5a92.png)

**Comment by ebbbang** [comment]
I couldn't reproduce the error ...
Please describe how to reproduce this issue ...

**Comment by theNailz** [comment]
I also can't reproduce the error. Have you checked the noContent function in `src/Http/Response/Factory.php`?

```
    /**
     * Respond with a no content response.
     *
     * @return \Dingo\Api\Http\Response
     */
    public function noContent()
    {
        $response = new Response(null);

        return $response->setStatusCode(204);
    }
```

Should be fairly easy to debug.

**Comment by 839891627** [comment]
It was my environment problem,sorry

**Comment by striveu** [comment]
> It was my environment problem,sorry

May I ask what the problem is? I am struggling with it.
