### ISSUE TITLE
Is dingo/api still being maintained?

### ISSUE THREAD

**Issue by LaurentEsc** [dingo/api#1404]
One year ago, we decided to use dingo/api for a new api project. We have had several dingo-related problems in the past months, and today we are considering replacing it with a home made api solution.

Would be nice to get an answer.

Laurent

**Comment by toobulkeh** [comment]
https://github.com/dingo/api/issues/1383

https://github.com/dingo/api/issues/1374

**Comment by peinhu** [comment]
no

**Comment by thilanga** [comment]
Trying to get back on track :)
