### ISSUE TITLE
404 error on all the api routes.

### ISSUE THREAD

**Issue by doitonlinemedia** [dingo/api#1418]
I'm getting only 404's on all of my api routes.
While the command php artisan api:routes gives me the desired result it's of no use.
They still give 404's.

```
$api->version('v1', ['namespace' => 'Doitonlinemedia\Api\App\Controllers'], function($api) {
    $api->get('test', function() {
        return 'test';
    });
});
```

In the api.php config I have set prefix to api/v1 (while i rather set it iin the option in the routes file, but both don't work).

Screenshot of the routes.
http://i.imgur.com/xZsDJin.png

Yet when I visit: http://localhost:8000/api/v1/test or http://project.dev/api/v1/test I always get a 404.
Tried visting the routes in browser as with postman (with accept parameter).
I can't figure out what I'm doing wrong.

**Comment by sourabhkum** [comment]
Check the API_DOMAIN= setting in config/api.php or if you are setting in .env file

**Comment by huuhoa0506** [comment]
I have same issue and trying fix this by many way but not.
Someone helps me! 
Thanks!!!!!!!!

**Comment by doitonlinemedia** [comment]
In the meanwhile I've fixed my problem.
It had nothing to do with the dingo api.

I was loading an extra Kernel, well at least I wanted it to be extra, however it was overriding the default by Laravel. 

I was loading it like:
`$this->app->singleton(Kernel::class, RouteKernel::class);`
But had to be:
`$this->app->make(RouteKernel::class);`

**Comment by RoraxHan** [comment]
@sourabhkum Thanks a lot. I've lost lots of time to fix this. you solved my issue. Thanks.
