### ISSUE TITLE
Call For Maintainers

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#1428]
Hello all.

Sorry it's been so long. My time to manage this package has depleted to practically nothing now and keeping up with a large amount of issues is just never going to happen. This is largely due to not needing to use this package for both work/personal things on a day to day basis.

Months ago I had @hskrasek take on some more work with the package to help maintain it. But it is a lot of work.

I'm putting the feelers out there again for someone else to help with maintaining the package going forward. This would include getting the package up to date for Laravel 5.5.

Please ping me in this issue if you are an active user of the package and would like to be active in contributing and maintaining. This would obviously include managing issues/pulls, making updates, fixes, features, etc.

**Comment by edbentinck** [comment]
I could certainly help out from time to time. I wouldn't consider my knowledge of PHP/Laravel to be as advanced as yours, but alongside other maintainers I'd be happy to contribute.

I've submitted a couple of small PRs recently and actively use this package at work.

Let me know if you'd like a hand.

**Comment by Broutard** [comment]
Is it concern also dingo/blueprint ?
If necessary I can also give a hand.

Could you merge the @edbentinck PR at least please ? (it is necessary for Laravel 5.5)
https://github.com/dingo/blueprint/pull/65

**Comment by from2day** [comment]
Count me in. 
I've ended up using this package at work and it gave me a good start in building APIs.
For that reason it would be sad to see it fades away.

Let me know if I can help.

**Comment by therocis** [comment]
I'm in.

**Comment by RubtsovAV** [comment]
I also use the dingo api in my working project. If you need help, just let me know.

**Comment by thilanga** [comment]
I'm happy to give a hand on maintaining this project as it's the blood line of the project I'm working on :)

**Comment by blazeworx** [comment]
I'm happy to lend a hand whenever time permits - I also use this package in a project and would hate to see it fade away.

**Comment by BafS** [comment]
I could also help out from time to time if needed

**Comment by jasonlewis** [comment]
I'll be in touch with a few people over the coming days. Cheers for the replies all.

**Comment by M165437** [comment]
Hi Jason, does this call also apply to dingo/blueprint? I just released an [API Blueprint Renderer](https://github.com/M165437/laravel-blueprint-docs) that goes really well together with your API Blueprint generator. I'm interested to help out getting dingo/blueprint back on track.

**Comment by thilanga** [comment]
@M165437 Thanks for showing the interest on bringing the Blueprint on track, You reckon you can do a pull request to the repository ?

**Comment by from2day** [comment]
@M165437 what do you think it needs to be done for the Blueprint? How can we get back it on track?
Please create a new issue for future discussions.
