### ISSUE TITLE
routeMiddleware laravel-cors is not working?

### ISSUE THREAD

**Issue by allen-hxn** [dingo/api#1438]
I use laravel5.4 + dingoapi+ jwt build my api services.when i use laravel-cors in dingoapi ,i find something wrong. 
routes/api.php as:
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
  $api->post('login', function(){
      return response()->json(['code'=>20000, 'token'=>'fsdf234']);
  });
});
```
add \Barryvdh\Cors\HandleCors::class  kernel.php as follows:
```
    protected $middleware = [
       .....
        \Barryvdh\Cors\HandleCors::class,
    ];
```
I request http://myapi.app/api/login is success.

But laravel-cors is work for every route,i dont't want this. so i change kernel.php ：
```
    protected $middleware = [
       .....
       // \Barryvdh\Cors\HandleCors::class,
    ];
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'mycors' => \Barryvdh\Cors\HandleCors::class,
    ];
```
routes/api.php
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['middleware'=>'mycors'],  function ($api) {
  $api->post('login', function(){
      return response()->json(['code'=>20000, 'token'=>'fsdf234']);
  });
});
```
Then request http://myapi.app/api/login is failed. 
preflight request is failed,server return 404.

why?Thanks for any helps.

**Comment by LexBel-co** [comment]
This is not a Dingo Api Issue, and looks like a bad instalation/configuration of Laravel Cors.

According to the Laravel Cors documentation, "If you want to allow CORS on a specific middleware group or route, add the HandleCors middleware to your group:"

`protected $middlewareGroups = [
    'web' => [
       // ...
    ],

    'api' => [
        // ...
        \Barryvdh\Cors\HandleCors::class,
    ],
];`

Please look at:
[https://github.com/barryvdh/laravel-cors#group-middleware](url)
