### ISSUE TITLE
How to return text/plain from controller

### ISSUE THREAD

**Issue by byrnedo** [dingo/api#1442]
Hi, 
Silly question here but how would one go about returning plaintext from a controller? 
Everything returns json currently but I want plain text for a metrics endpoint (prometheus).

**Comment by from2day** [comment]
It depends on your setup. 
Return type is defined by Header

So in fresh Laravel 5.5 + dingo/api  => this route would give you `text/plain`
```
$api->version('v1', function ($api) {
	$api->get('/demo', function() {
		return response('Hello World', 200)
			->header('Content-Type', 'text/plain');
	});
});
```
