### ISSUE TITLE
[help] api:routes have some mistake  

### ISSUE THREAD

**Issue by hare2011** [dingo/api#1444]
php artisan api:routes
 the mistake happen :                                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError]                            
  Call to undefined method Illuminate\Foundation\Console\RouteListCommand::handle()

**Comment by bkintanar** [comment]
@hare2011 are you on 5.5? since 5.4 uses the fire method instead of handle (5.5)

**Comment by kk0501** [comment]
don't execute composer update command

**Comment by miaotaizi** [comment]
same mistake.

**Comment by eocene317** [comment]
How to resolve it?

**Comment by thilanga** [comment]
Please use the new issue template.

**Comment by MatteoMeil** [comment]
I'm using Laravel 5.2
I found a solution commenting lines from 82 to 87 (method `handle` ) in ` ./vendor/dingo/api/src/Console/Command/Routes.php`

**Comment by huxiang0306** [comment]
I met the same mistake ,
and i solved it by update my dingo\api version.
I'm using Laravel 5.4
[please see this](https://github.com/dingo/api/releases)

ps :I'm a freshman
