### ISSUE TITLE
Do you like to see Dingo\Api\Routing\Route.php extends from \Illuminate\Routing\Route.php? 

### ISSUE THREAD

**Issue by thilanga** [dingo/api#1446]
Dingo Route.php does similar routing handling like Illuminate core. I think it's better to go closer to the core as possible as we can. 

What do you think?

I was able to solve all these errors popped with Laravel 5.5. 

    …/laravel/app    master   docker exec -it laravel_web_1 php artisan api:routes
+----------------------------------+----------+------+---------+---------+-----------+------------+----------+------------+
| Host                             | Method   | URI  | Name    | Action  | Protected | Version(s) | Scope(s) | Rate Limit |
+----------------------------------+----------+------+---------+---------+-----------+------------+----------+------------+
| api.laravel.thilangapitigala.dev | GET|HEAD | user | profile | Closure | No        | v1         |          |            |
+----------------------------------+----------+------+---------+---------+-----------+------------+----------+------------+

Need to test against a full application.

**Comment by abhimanyu003** [comment]
This sounds good to me.
