### ISSUE TITLE
Are you using OAuth provider within Dingo?

### ISSUE THREAD

**Issue by thilanga** [dingo/api#1450]
I cannot get the OAuth provider working unless I do an over-whole to the provider. Previously package was recommending `lucadegasperi/oauth2-server-laravel`. But it doesn't support Laravel > 5.2.

Probably the best option would be for us to move forward with `laravel\passport`. But then the problem is `laravel/passport` > 2 doesn't support `lucadegasperi/oauth2-server-laravel` < 6

At this time I have 2 options.

1, Do a release without OAuth provider and add support later
2. Release with OAuth support + Laravel/Passport < 3 

This is something holding the release at the moment.

**Comment by from2day** [comment]
For current release I would go for option 1. 
Atm this project still needs some customization after installation. 

However more opinions are welcome.
