### ISSUE TITLE
Installation fails - now requires PHPv7 despite installation requirements saying PHP 5.5.9+

### ISSUE THREAD

**Issue by neilcrookes** [dingo/api#1452]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.2.45
| Package version   | 1.0.x-dev
| PHP version       | 5.6.30

#### Actual Behaviour

Install fails

> dingo/api 1.0.x-dev requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.

But the Installation page on the wiki states

> To install this package you will need:
> 
> Laravel 5.1+ or Lumen 5.1+
> PHP 5.5.9+
> You must then modify your composer.json file and run composer update to include the latest version of the package in your project.
> 
> "require": {
>     "dingo/api": "1.0.*@dev"
> }

#### Expected Behaviour

Install works if you meet the system requirements, by following the installation instructions

#### Steps to Reproduce

Follow the installation instructions in the wiki, using the framework, library and php versions described above

#### Possible Solutions

Update the Installation guide to describe separate installation for each Laravel ( and therefore PHP) version

**Comment by thilanga** [comment]
Thanks for the issue. We are just doing the release now and will update the wiki ASAP :)
