### ISSUE TITLE
New issues and existing issues

### ISSUE THREAD

**Issue by thilanga** [dingo/api#1454]
Hi everyone.

There are over 170 issues has been created against the project.

- Some of theme are really old but active
- Some them are gone cold.
- Most of issues are just console logs without any version and proper explanations.

To keep the project up and running again like it's golden days, it would be really helpful if you could create new issues in the new format.

If you have created an issue in the old format but still occuring in you project. Please create it as a new issue using the new format.

That way we can get everyone's help to solve issues that we face while using the Dingo API package.

I'll be closing all the old issues on 1st of October 2017. Hopefully that'll give you plenty of time to act on issues that you have created or particated.

**Comment by gazben** [comment]
@thilanga Will you close the issues? 
Can I help?

**Comment by specialtactics** [comment]
Sounds good @thilanga let us know if you need any help.
