### ISSUE TITLE
Accept header could not be properly parsed because of a strict matching process

### ISSUE THREAD

**Issue by hardikifuturz** [dingo/api#1460]
It is asking for accept header on all routes

local.ERROR: 400 - exception 
'Symfony\Component\HttpKernel\Exception\BadRequestHttpException' with 
message 'Accept header could not be properly parsed because of a strict 
matching process.' in 
/home2/bhuvamka/public_html/apcivilsupplies.com/protected/vendor/dingo/api/src/Http/Parser/Accept.php:66

I have enabled strict mode from env file. so now help me what can I pass in the header?

**Comment by thilanga** [comment]
Please use the new issue format.
