### ISSUE TITLE
Does not install package in version 5.5.13 LARAVEL

### ISSUE THREAD

**Issue by claytonferraz** [dingo/api#1464]
| Q                 
| ----------------- | ---
| Bug?              |yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.5.13
| Package version   | master
| PHP version       | 7.1.7

#### Actual Behaviour
When I will install the package this error appears: 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dingo/api ^0.10.0 -> satisfiable by dingo/api[v0.10.0].
    - dingo/api v0.10.0 requires league/fractal 0.12.* -> satisfiable by league/fractal[0.12.0] but these conflict with your requirements or minimum-stability.

#### Expected Behaviour

installation in version 5.5 laravel

#### Steps to Reproduce

I'm using the composer command.

composer require dingo/api or  composer require dingo/api:2.0.x@dev

**Comment by thilanga** [comment]
Try composer update not require, require don't update dependencies

**Comment by claytonferraz** [comment]
Thank you, now it worked.
