### ISSUE TITLE
Will there be a 1.0 stable version for Laravel < 5.5?

### ISSUE THREAD

**Issue by johannesschobel** [dingo/api#1471]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.1.x
| Package version   | 1.0.0-beta8
| PHP version       | 7.x.y

Just a friendly question:
Will there ever be a `1.0 version` of dingo available that is considered as `stable`. And will there be a version, that is capable of dealing with Laravel Applications `< 5.5`?

Thank you for your time and effort you put into `dingo/api` - i really appreciate it!

**Comment by thilanga** [comment]
@johannesschobel I'm under the weather these days. As soon as I feel better that's my priority. Need to sort out bugs that has been reported and then work on the stable release.

Hopefully before the next month.

**Comment by johannesschobel** [comment]
No problem! thanks for the very fast response!
Get well soon!
