### ISSUE TITLE
Multiple clients authorization

### ISSUE THREAD

**Issue by devil19891025** [dingo/api#1475]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.2
| PHP version       | 5.6

Hi, I use dingo api with OAuth2 to create an api authorization system.
If I have multiple client , example : A client and B client .
A client only can call A api, and B client only can call B api.
They can't call each other api.
How should I do?

**Comment by from2day** [comment]
Basically you need to implement some authorization mechanism: permissions, policies, etc. There are plenty of suggestions.
Laravel has some documentation: https://laravel.com/docs/5.5/authorization
It might be not so clear at first, but I suggest to stick to Laravel suggested one.
