### ISSUE TITLE
Ability to set few responses examples for API Blueprint docs

### ISSUE THREAD

**Issue by believer-ufa** [dingo/api#1477]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel|Lumen

#### Actual Behaviour

Now if we will generate documentation in api blueprint format, we can set only one response example to every request in our project.

#### Expected Behaviour

The need ability to set any count of responses examples that we need. Because we must describe to other developers how errors responses can be returned from every action in project, for example.

#### Possible Solutions

For example, i have `get password reset link` method in my project. I have next code:

```php
    /**
     * Get reset password link to email.
     *
     * @Post("/password-reset-link")
     * 
     * @Response(200, body={
     *      "status": "success",
     *      "message": "Link to reset password was sent!"
     *  })
     * 
     * @Parameters({
     *      @Parameter("email", type="string", description="Email address", required=true)
     * })
     */
    public function passwordResetLink()
    {
        // ...
    }
```

I think, we could add any count of `@Response` elements in description of our method. For example:

```php
    /**
     * Get reset password link to email.
     *
     * @Post("/password-reset-link")
     * 
     * @Response(200, body={
     *      "status": "success",
     *      "message": "Link to reset password was sent!"
     *  })
     *
     * @Response(200, body={
     *      "status": "error",
     *      "message": "Incorrect email!"
     *  })
     * 
     * @Parameters({
     *      @Parameter("email", type="string", description="Email address", required=true)
     * })
     */
    public function passwordResetLink()
    {
        // ...
    }
```

As we know, specification of API Blueprint supports describing of many response exmaples.

> An action should include at least one response from the server which must include a status code and may contain a body. A response is defined as a list item within an action. Lists are created by preceding list items with either a +, * or -.

**Comment by from2day** [comment]
It's already possible to do it with @Transactions: https://github.com/dingo/api/wiki/API-Blueprint-Documentation#transaction

The only caveat is when you need to define multiple "similar" responses that share the same HTTP status code. For that reason you need to differentiate like: @Response(**200xx**, body={"id": 10, "username": "foo"}),. 

Just to sum up:
```
/**
 * Register user
 *
 * Register a new user with a `username` and `password`.
 *
 * @Post("/")
 * @Versions({"v1"})
 * @Transaction({
 *      @Request({"username": "foo", "password": "bar"}),
 *      @Response(200, body={"id": 10, "username": "foo"}),
 *      @Response(422, body={"error": {"username": {"Username is already taken."}}})
 * })
 */
public function store()
{

}
