### ISSUE TITLE
Canno't install Dingo API / Laravel 5.5.19

### ISSUE THREAD

**Issue by rikemSen** [dingo/api#1479]
Hi there :),

I'm facing a problem while requiring `dingo/api:2.0.0-alpha1`:

> ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

 > Problem 1
    - Conclusion: remove laravel/framework 5.5.x-dev
    - Conclusion: don't install laravel/framework 5.5.x-dev
    - dingo/blueprint 0.2.2 requires illuminate/filesystem 5.1.* || 5.2.* || 5.3.* || 5.4.* -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - dingo/blueprint v0.2.0 requires illuminate/filesystem 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - dingo/blueprint v0.2.1 requires illuminate/filesystem 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/filesystem[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/filesystem 5.1.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem 5.2.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem 5.3.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem 5.4.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.1|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.13|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.16|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.2|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.20|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.22|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.25|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.28|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.30|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.31|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.41|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.6|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.1.8|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.19|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.21|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.24|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.25|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.26|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.27|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.28|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.31|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.32|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.37|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.43|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.45|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.6|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.2.7|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.3.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.3.16|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.3.23|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.3.4|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.13|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.17|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.19|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.27|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.36|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/filesystem v5.4.9|don't install laravel/framework 5.5.x-dev
    - Installation request for laravel/framework (locked at 5.5.x-dev, required as 5.5.*) -> satisfiable by laravel/framework[5.5.x-dev].
    - Installation request for dingo/api 2.0.0-alpha1 -> satisfiable by dingo/api[v2.0.0-alpha1].
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1|install dingo/blueprint 0.2.2|install dingo/blueprint v0.2.0|install dingo/blueprint v0.2.1
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1|install dingo/blueprint 0.2.2|install dingo/blueprint v0.2.0|install dingo/blueprint v0.2.1
    - dingo/api v2.0.0-alpha1 requires dingo/blueprint ^0.2 -> satisfiable by dingo/blueprint[0.2.2, 0.2.x-dev, v0.2.0, v0.2.1, v0.2.3].
    - dingo/blueprint 0.2.x-dev requires phpdocumentor/reflection-docblock ^3.1 -> satisfiable by phpdocumentor/reflection-docblock[3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - dingo/blueprint v0.2.3 requires phpdocumentor/reflection-docblock ^3.1 -> satisfiable by phpdocumentor/reflection-docblock[3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].

> Installation failed, reverting ./composer.json to its original content.

I just did a installation of laravel installer, created a projet and then required Dingo API.

Any help would be appreciated.

Best regards,
Guillaume R.

**Comment by airguillaume** [comment]
I'm sure i'll find a way to make it work these links. 

https://github.com/dingo/api/issues/1076
https://github.com/dingo/api/issues/1060

I'll keep you in touch

**Comment by rikemSen** [comment]
Ok, I managed to install it by adding `"minimum-stability": "dev"` && `"phpdocumentor/reflection-docblock": "3.x@dev"` to my composer.json.

**Comment by rikemSen** [comment]
Ok, I managed to install it by adding `"minimum-stability": "dev"` && `"phpdocumentor/reflection-docblock": "3.x@dev"` to my composer.json.
