### ISSUE TITLE
Laravel 5.4.* route not defined

### ISSUE THREAD

**Issue by danieluyo** [dingo/api#1480]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4.x
| Package version   | 1.0.0-beta8
| PHP version       | 7.1.10

#### Actual Behaviour

In the model i'm create a custom attribute, when DIngo "prints" the result show is an error "route not defined"

#### Expected Behaviour

Print the model result with the Url

#### Steps to Reproduce

```php
// ModelTest.php
class ModelTest extends Model
{
    protected $appends = ['endpoint'];
    protected $visible = [
     'foo',
     'bar',
     'endpoint'
   ];
    public function getEndpointAttribute()
    {
         return route('dingo.route.test');
    }
}


// DingoRoutes.php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['namespace' =>$this->namespace], function ($api) {
      $api->get('dingo', 'DingoTestController@index')->name('dingo.route.test');
     // More Dingo api routes works (post, get, put...)
});
```
The response:
```json
{
  "message": "Route [dingo.route.test] not defined.",
  "status_code": 500
}
```

**Comment by danieluyo** [comment]
I found the solution
```php
 app('Dingo\Api\Routing\UrlGenerator')->version('v1')->route('dingo.route.test')
```
This solution is so strange, might be cool if exist something like: 
```php
dingoRoute('dingo.route.test');
```

**Comment by urukalo** [comment]
is there any nice solution for this?

**Comment by vasarr** [comment]
this error how to solution?
```
>>> app('Dingo\Api\Routing\UrlGenerator');
BadMethodCallException with message 'Method setKeyResolver does not exist.'
```

**Comment by specialtactics** [comment]
@vasarr Please make a new issue if you are having this problem as it's unrelated.

So far as this issue, I think it will be done in https://github.com/dingo/api/issues/1606

Closing
