### ISSUE TITLE
php artisan api:routes undefined handle() in RouteListCommand for laravel 5.4

### ISSUE THREAD

**Issue by muhrifat** [dingo/api#1482]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.4
| Package version   | 2.0.0
| PHP version       | 7.1

#### Actual Behaviour

run php artisan api:routes, missing handle in RouteListCommand.

**Comment by kylestev** [comment]
Hi, be sure to take a look at [the release notes for `v2.0.0-alpha1`](https://github.com/dingo/api/releases/tag/v2.0.0-alpha1). Laravel 5.4 and below support has been dropped.
