### ISSUE TITLE
FormRequest Validation - does not describe which fields failed validation

### ISSUE THREAD

**Issue by simplenotezy** [dingo/api#1496]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Larave
| Framework version | 5.5.*
| Package version   | 2.0.0-alpha1
| PHP version       | 7.1.10

#### Actual Behaviour
When using FormRequest to validate input given by client, and validation fails, it simply returns:

    "message": "The given data was invalid.",

Along with status_code 500 + debug trace.

#### Expected Behaviour

I would expect it to give some more clues as to which validations that failed, and why.

**Comment by simplenotezy** [comment]
Solution, in your `FormRequest` use

    use Dingo\Api\Http\FormRequest;

Instead of

    use Illuminate\Foundation\Http\FormRequest;

**Comment by danijelk** [comment]
Sitting in the same boat, tried to do abstract class Form extends \Dingo\Api\Http\FormRequest, what error should be thrown?

Tried: $this->throwValidationException(request(), $validator) and: $this->failedValidation($validator)

**Comment by yangliulnn** [comment]
But the status code is still 500

**Comment by danijelk** [comment]
Indeed this should most definitely not be a 500

**Comment by yangliulnn** [comment]
#1519

**Comment by specialtactics** [comment]
Closing, PR was merged.
