### ISSUE TITLE
laravel5.5 api:docs make a mistake

### ISSUE THREAD

**Issue by ycp19940225** [dingo/api#1497]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.5.*
| Package version   | 2.0.0-alpha1
| PHP version       | 7.x.y

#### Actual Behaviour
When I generate an API document, I have an error. If there is no information that doesn't make a mistake, when you add the routing and the parameters, you make a mistake.

my controller
```
 /**
     * Login user
     *
     * Login with a `username` and `password`.
     *
     * @Post("register")
     * @Versions({"v1"})
     * @Transaction({
     * @Request({"email"="foo", "password"="bar"}, contentType="application/json"),
     * @Response(200, body={"access_token":"token","token_type":"bearer","expires_in":3600}),
     * @Response(401, body={"error":{"code":103,"message":"Email or password is incorrect."}})
     * })
     */
    public function register(Request $request)
    {}
```
terminal:
```
php artisan api:docs --name Example --use-version v1 --output-file D:/documentation.md

In Assert.php line 942:

  Expected a string. Got: boolean


```

**Comment by stojankukrika** [comment]
I got the same response :(

**Comment by stojankukrika** [comment]
Hi @ycp19940225 and other who have the same problem, here is solution.
Just add this before begin of your controller class (before Class XXXController extends Controller):

```
/**
 * Routes for login, register and all about auth
 *
 * @Resource("Auth", uri="/auth")
 *
 */
```
Replace all you need like comment and Resource params. After that generation documentation works well.

**Comment by ycp19940225** [comment]
@stojankukrika ok！thanks，It's good.

**Comment by chilio** [comment]
Hi @stojankukrika how do you get around with proper uri in methods?
Cause in my situation all gets overridden by resource uri...

**Comment by from2day** [comment]
Hi @chilio, 
when you define '@ Resource' before the class all the bottom routes should append to the defined uri:
This should come as `/api/login`

```
/**
 * # Group Authentication
 *
 * @Resource("", uri="/api")
 */
class AuthController extends ApiController
{
    /**
      *
      * Login
      *
      * @Post("/login")
      * @Versions({"v1"})
    */
    public function login(Request $request)
    {

    }
}

**Comment by from2day** [comment]
Closing as inactive. Reopen if needed.
