### ISSUE TITLE
Global middleware no longer runs on Laravel 5.x

### ISSUE THREAD

**Issue by tripper54** [dingo/api#1500]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework        |  Laravel
| Framework version | 5.2.45
| Package version   | master 312781d19ac6a424087ed29c97e8353f592343a4
| PHP version       | 7.1.5

#### Actual Behaviour

Since #1494, middleware registered in app/Http/Kernel.php in $middleware no longer runs. 

#### Expected Behaviour

As per earlier releases, I expect middleware registered in app/Http/Kernel.php 's $middleware to run.

#### Steps to Reproduce

1. Add a dd('this should run') to any of the handlers registered in app/Http/Kernel.php 's $middleware
2. Make a request

Expected: The dd message should be output
Actual: The dd message is not output. The route is executed as if the middleware has not been called.

#### Possible Solutions

Revert #1494 .

**Comment by thilanga** [comment]
This is a good example of reporting an issue +1
