### ISSUE TITLE
Route::namespace('') implementation ?

### ISSUE THREAD

**Issue by loic-lopez** [dingo/api#1518]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel|Lumen
| Framework version | 5.5.*
| Package version   | 2.0.0-alpha1
| PHP version       | 7.2.1

Hello, 
Can you implement namespace routing like laravel 5.5 : 

```
Route::namespace('Admin')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace
});
```

url : 
[https://laravel.com/docs/5.5/routing#route-group-namespaces](laravelrouting)

**Comment by Broutard** [comment]
Already implemented!

**Comment by loic-lopez** [comment]
But the docs does not describe how to do

**Comment by specialtactics** [comment]
@loic-lopez It does just like it does in Laravel, just that Laravel moved to the syntax you describe (but the old one still works).

```
        $api->group(['prefix' => 'payouts'], function (Router $api) {});
```

**Comment by Broutard** [comment]
@specialtactics prefix & namespace are two differents features.
```
$api->group(['namespace' => 'App\Http\Controllers\Admin', 'prefix' => 'admin'], function (Router $api) {});
```

**Comment by specialtactics** [comment]
Ah yeh sorry.

Point is the same though, you can pass all the static options as parameters in the old style, and it should work.
