### ISSUE TITLE
Routes return 404 and do not show in artisan route:list.

### ISSUE THREAD

**Issue by laclance** [dingo/api#1533]
| Bug?              |   yes
| New Feature?      |   no
| Framework         |    Laravel
| Framework version |   v5.5.35
| Package version   |   2.0.0-alpha1
| PHP version       |   7.1.14

Routes return 404 and do not show in artisan route:list.

**.env:**
```
API_PREFIX=api
API_VERSION=v1
```

**extension.php:**
```
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->get('/users222', function () {
        return 'testing';
    });
});
```

#### Steps to Reproduce

Add "dingo/api": "2.0.0-alpha1" to composer.json, run composer update and insert code from above. (minimum-stability is set to dev)

**Comment by laclance** [comment]
Apologies i needed to add https as http is the postman's default.

**Comment by simaguo** [comment]
set API_DOMAIN= hostname  like this
