### ISSUE TITLE
How to view Dingo Routes list 

### ISSUE THREAD

**Issue by rojonunoo** [dingo/api#1536]
If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.
i have implemented dingo into my  Lumen project and i can't seem to list/view my routes. How do i list or view all routes in the terminal with results like "php artisan route:list" command. I have installed a couple of packages but they seem not to work while some are deprecated other i think aren't compatible with Lumen 5.5. Been struggling for these days..

**Comment by bm2ilabs** [comment]
Hello were you able to get solution for this ?

**Comment by specialtactics** [comment]
I'm pretty sure this is in the wiki

```
./artisan api:routes
```
