### ISSUE TITLE
how to contribute to the wiki page?

### ISSUE THREAD

**Issue by vaxilicaihouxian** [dingo/api#1540]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.6
| Package version   | 1.x.y
| PHP version       | 7.1

#### Actual Behaviour

How to contribute to the wiki page? Because that I found if I follow the [Response Builder].(https://github.com/dingo/api/wiki/Responses)

```php
use Dingo\Api\Routing\Helpers;
use Illuminate\Routing\Controller;

class BaseController extends Controller
{
	use Helpers;
}
```

Then this controller is not an instance of  **Laravel\Lumen\Routing\Controller**.So some method can not work.Like **middleware()**.

#### Expected Behaviour

I think it should extends the **Laravel\Lumen\Routing\Controller** for lumen.Or just extends **App\HTTP\Controllers\Controller** for laravel and lumen.

#### Possible Solutions

So,if this is necessary to change the wiki page,could someone tell me how to contribute for wiki page?

**Comment by thilanga** [comment]
@vaxilicaihouxian clone `https://github.com/dingo/api.wiki.git` and do a PR

**Comment by vaxilicaihouxian** [comment]
@thilanga 

When I clone the repo (https://github.com/dingo/api.wiki.git) and change it.I push to the repo.
Then I got this error.

```
Username for 'https://github.com': vaxilicaihouxian
Password for 'https://vaxilicaihouxian@github.com': 
remote: Permission to dingo/api.wiki.git denied to vaxilicaihouxian.
fatal: unable to access 'https://github.com/dingo/api.wiki.git/': The requested URL returned error: 403

```

**Comment by vaxilicaihouxian** [comment]
Already make a pr.
PS: https://github.com/dingo/api-docs is the wiki project source.So I should clone that repo :)
