### ISSUE TITLE
cors error and laravel-cors

### ISSUE THREAD

**Issue by gotoin** [dingo/api#1551]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | 2.0.0
| PHP version       | 7.1

#### Actual Behaviour
```
response headers
Access-Control-Allow-Origin: 
```
#### Expected Behaviour
```
response headers
Access-Control-Allow-Origin: *
```

#### Steps to Reproduce

```
// config/api.php
'middleware' => [
        \Barryvdh\Cors\HandleCors::class,
    ],
```

```
// Kernel.php

'api' => [
            'throttle:60,1',
            'bindings',
             \Barryvdh\Cors\HandleCors::class,
],
```

#### Possible Solutions

first delete laravel-cors 

```
// add it to config/api.php
header('Access-Control-Allow-Origin:*');
header('Access-Control-Allow-Headers:*');
header('Access-Control-Allow-Methods:*');
header('Access-Control-Allow-Credentials:false');
header('withCredentials:false');
```
But this is not an elegant solution.

thanks.

**Comment by erayaydin** [comment]
Tested with Fresh Laravel Installation(Laravel5.5+Dingo2.0), CORS working. Are you published `config/cors.php` ?

**Comment by gotoin** [comment]
I use the laravel-cors package. and that problem with this package.

thank you.

@erayaydin
