### ISSUE TITLE
Wiki Installation Wrong Typo in Installation

### ISSUE THREAD

**Issue by erayaydin** [dingo/api#1554]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | -
| Framework version | -
| Package version   | -
| PHP version       | -

There is one typo mistake in [Installation](https://github.com/dingo/api/wiki/Installation) wiki page.

> If you'd like to make configuration changes in the configuration file you can pubish it with the following Aritsan command:

should be

> If you'd like to make configuration changes in the configuration file you can **publish** it with the following **Artisan** command:

**Comment by from2day** [comment]
Fixed. Thanks @erayaydin.
