### ISSUE TITLE
poser update

### ISSUE THREAD

**Issue by strakers** [dingo/api#1558]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

#### Expected Behaviour

Describe the behaviour you're expecting.

#### Steps to Reproduce

List all the steps needed to reproduce the issue you're having. Make sure to include code (affected models, configurations),
any screenshots and/or other resources that may help us understand what's going on.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by from2day** [comment]
Closing as invalid issue.
