### ISSUE TITLE
Return custom response code

### ISSUE THREAD

**Issue by qasimalbaqali** [dingo/api#1561]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel|
| Framework version | 5.5
| Package version   | 2.0.0-alpha1
| PHP version       |7.1

I'm trying to return a custom HTTP response code to detect different type of 'errors', for example a status code of 1002 for internal logic that would check if a current user is paying for a ticket, and 1003 response code if a user needs to pay for the ticket. When trying to set the custom response code in` ->setResponseCode(1002)` I get that it's not a valid response code. Is it possible to set custom response code through dingo?

**Comment by gazben** [comment]
@qasimalbaqali I think you should set this internal code in the response itself. The setResponseCode function is for HTTP status codes only.
Example response:
```
data: { ... },
success: true
http_status_code: (the returned http status code)
status_code: (your internal status codes)
```

**Comment by qasimalbaqali** [comment]
Good point. Thank you
