### ISSUE TITLE
Wrong  or Empty  Token is returning respose status code 500 

### ISSUE THREAD

**Issue by ferleal** [dingo/api#1566]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.25
| Package version   | 2.0.0-alpha2
| PHP version       |7.2.6

#### Actual Behaviour
When sending a Bearer Token the return response is {"message":"Unauthenticated."} with status_code 500 

I am using  laravel/passport **6.0.2**

#### Expected Behaviour

It should return {"message":"Unauthenticated."} with status_code 401

#### Steps to Reproduce
**routes/api** file:
```php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
  $api->group([
    'namespace' => 'App\Api\Controllers'
  ],
    function ($api) {
      $api->post('me', function () {
        return 'test';
      })->middleware('auth:api');
    });
}); 
```
Use the api with a wrong or empty token

#### Possible Solutions

I was testing using laravel routing
**routes/api**
```php
Route::post('me',function(){
  return 'test';
})->middleware('auth:api');
```
and it returns   {"message":"Unauthenticated."}  with status_code 401

**Comment by gazben** [comment]
@ferleal 
If I remember correctly I made a workaround for the Tymon\JWTAuth package.

app/Exceptions/Handler.php:
```

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        if ($e instanceof TokenExpiredException) {
            return response()->json(['token_expired'], $e->getStatusCode());
        } elseif ($e instanceof TokenInvalidException) {
            return response()->json(['token_invalid'], $e->getStatusCode());
        }

        return parent::render($request, $e);
    }
```

**Comment by specialtactics** [comment]
I am not sure this package and passport are overly compatible, if possible I would recommend not using passport.

Otherwise, I could take a look, though I wouldn't be surprised if there are other issues too.
