### ISSUE TITLE
primitive not work

### ISSUE THREAD

**Issue by laravuel** [dingo/api#1568]
```
protected $availableIncludes = ['articles', 'articlesCount'];

    public function includeArticles(ArticleCategory $category) {
        return $this->collection($category->articles, new ArticleTransformer);
    }

    public function includeArticlesCount(ArticleCategory $category) {
        return $this->primitive($category->articles()->count());
    }
```

`Call to undefined relationship [articlesCount] on model`

i need help

**Comment by gazben** [comment]
@laravuel Do you have the articlesCount relationship on the modell?

And please follow the issue template

**Comment by specialtactics** [comment]
Not really following what is going on here, there's no function "primitive" in this package at all?

**Comment by specialtactics** [comment]
Closing due to lack of template & response.

Please feel free to re-open with more info (and plz follow the issue template)
