### ISSUE TITLE
How to add custom field in transformer based on outside variables?

### ISSUE THREAD

**Issue by imageslr** [dingo/api#1577]
| Q                 | A
| ----------------- | ---
| Bug?              | no|
| New Feature?      | no|
| Framework         | Laravel|
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 7.x.y

Dear all, excuse for my poor English.

I am a starter of this framework. Now I have question: how to add custom field in transformer based on outside variables?

To be specific, when fetching `/users/:id`, I want to add a `following` field in the response JSON to show that whether current user is follow the fetched user.

Now I'm doing it like this:

```php
$currentUser = getLoggerdUserByRequest($request);
$user = User::find($id);
$user->following = $user->isFollowing($currentUser);
return $this->response->json($user);
```

I want to know **is there someway I can pass extra variables to transformer**? Currently I can only set TransformerClass like this:

```PHP
class UserTransformer extends TransformerAbstract
{
    public function transform(User $user)
    {
        return [
            'id' => $user->id,
            //...
            'following' => (boolean)$user->following,
            'created_at' => $user->created_at->toDateTimeString()
        ];
    }
}
```

And I hope I can set `following` like this, just inside the `UserTransformer`:

```PHP
class UserTransformer extends TransformerAbstract
{
    public function transform(User $user, User $currentUser)
    {
        return [
            'id' => $user->id,
            //...
            'following' => $user->isFollowing($currentUser),
            'created_at' => $user->created_at->toDateTimeString()
        ];
    }
}
```

Is there some better way to implement? Thank you!

**Comment by gazben** [comment]
@imageslr 
1. You can set fields of any eloquent model and pass it to the transformer as a collection
2. You can inject Services to the transformer

**Comment by imageslr** [comment]
Thank you! I am now using the first method, and I will look the second one. Thank you again!
