### ISSUE TITLE
Number / String issue

### ISSUE THREAD

**Issue by xyrintech** [dingo/api#1591]
Its a very common issue with every version I am using for this package with every version of laravel and also with every version of PHP. So, I did not the exact form you requested, please lemme know if you still want to.

Let's say we have a table 
websites
- id
- user_id
- name

When we return the record as Website::all() then its returns user_id as string, not number. This is there for every foreigne key is getting as string.

**Comment by DevMakoto** [comment]
in tranform use 
return [
  'user_id' => (int) $this->user_id
]

**Comment by specialtactics** [comment]
In my experience if you have a database field that's an integer, and it's being returned as a string from the transformer, it is an issue in PHP / DB driver. For example, if you are using the old mysqli instead of the new mysqlnd PHP module for MySQL, it will cause this problem.
