### ISSUE TITLE
[Suggestion/Question] Simplifying generation of URL's

### ISSUE THREAD

**Issue by scheMeZa** [dingo/api#1606]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      |yes
| Framework         | Laravel
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 7.x.y

Could the generation of URL's not be simplified using a Facade?

Currently we need to use:
`app('Dingo\Api\Routing\UrlGenerator')->version('v1')->route('users.index');`

This feels lengthly, from:
`route('api.v1.users.index');`

I'm thinking that something like this could be better:
`DingoRoute('users.index')` - Uses config.api.version to find the correct route in this case, or you could be more specific:
`DingoRoute('users.index', 'v1')`

**Comment by specialtactics** [comment]
Hi, I've made this PR to implement this suggestion;

https://github.com/dingo/api/pull/1641

Basically so long as you have your Dingo API facade set up in your app config, eg:
```php
        'API' => Dingo\Api\Facade\API::class,
```

You can write code like this:
```php
API::route('users.index');
```

Noting to import API into your file.
