### ISSUE TITLE
Error Route cache

### ISSUE THREAD

**Issue by khanhvu14** [dingo/api#1632]
| Q                 | A
| ----------------- | ---
| Bug?              |yes
| Framework         | Laravel
| Framework version | 5.7.28
| Package version   | 2.1.0
| PHP version       | 7.2.15

when I run artisan commmand "php artisan route:cache" then run "php artisan api:cache"
all api routes are still not found, api:routes not show any route.

**Comment by ianfortier** [comment]
I have the same problem after updating from 2 beta to 2.1

**Comment by khanhvu14** [comment]
I move mapApiRoutes() function from RouteServiceProvider to boot function. Currently bug is temporary fixed.

**Comment by khanhvu14** [comment]
Bug fixed in 2.2.2 thanks @specialtactics

**Comment by specialtactics** [comment]
Fantastic ! Closing.
