### ISSUE TITLE
Class Dingo\Api\Exception\Handler contains 1 abstract method and must therefore be declared abstract or implement

### ISSUE THREAD

**Issue by denept** [dingo/api#1633]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating dingo/api (v2.0.0-beta1 => 2.0.1): Downloading (100%)
  - Updating nikic/php-parser (v4.2.0 => v4.2.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Handler.php line 16:

  Class Dingo\Api\Exception\Handler contains 1 abstract method and must therefore be declared abstract or imple
  he remaining methods (Illuminate\Contracts\Debug\ExceptionHandler::shouldReport)

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
PS D:\qampp\htdocs\project\kindleNeptune_server> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Handler.php line 16:

  Class Dingo\Api\Exception\Handler contains 1 abstract method and must therefore be declared abstract or imple
  he remaining methods (Illuminate\Contracts\Debug\ExceptionHandler::shouldReport)

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by specialtactics** [comment]
Hi @denept please update your dingo package version to latest.

**Comment by SOSTheBlack** [comment]
update the package version (Y)
"dingo/api": "^2.1",

**Comment by ellisio** [comment]
@specialtactics Someone needs to update the wiki. People are having this happening because the following is on the (Installation page)[https://github.com/dingo/api/wiki/Installation]:

```
"require": {
    "dingo/api": "2.0.0-beta1"
}
```

**Comment by specialtactics** [comment]
Thanks @ellisio  - updated!

**Comment by php-writerman** [comment]
@specialtactics Is it possible to add `shouldReport` method in `2.0.0-alpha2` version?

**Comment by specialtactics** [comment]
Sorry @php-writerman that version is super old and is no longer supported. If you would like, there's nothing stopping you from making your own fork of that older version and implementing this fix there, until you update.
