### ISSUE TITLE
Laravel framework included event using lumen

### ISSUE THREAD

**Issue by lloricode** [dingo/api#1638]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.8.*
| Package version   | 2.2.0
| PHP version       | 7.3.3

#### Actual Behaviour

@specialtactics 
I think here
https://github.com/dingo/api/blob/v2.2.0/composer.json#L21
no need to include laraver/framework 

```
    "require": {
        "php": "^7.1",
        "dingo/blueprint": "^0.2",
        "illuminate/routing": "^5.5",
        "illuminate/support": "^5.5",
        "league/fractal": "^0.17",
        "laravel/framework": "^5.5"
    },
```

#### Expected Behaviour

```
    "require": {
        "php": "^7.1",
        "dingo/blueprint": "^0.2",
        "illuminate/routing": "^5.5",
        "illuminate/support": "^5.5",
        "league/fractal": "^0.17"
    },
```

**Comment by specialtactics** [comment]
Hi @lloricode 

I think this should work fine, approved.
