### ISSUE TITLE
RequestValidator is valid even if not all validators are valid.

### ISSUE THREAD

**Issue by Schnoop** [dingo/api#1647]
| Q                 | A
| ----------------- | ---
| Bug?              | maybe
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.45
| Package version   | 2.2.3
| PHP version       | 7.1.27

#### Actual Behaviour

The RequestValidator, which is validating if a request should be dispatched through the Dingo router or not, is returning true, if ANY of the used validators (Domain and Prefix) is true. Is this the expected behaviour?

#### Expected Behaviour

I think ALL validators should be valid instead of only a single on.

#### Steps to Reproduce

Install Laravel in menitoned version
Install Dingo in menitoned version
Install https://github.com/z-song/laravel-admin package
Try to access the admin section from laravel-admin and login.
The next GET for the admin tries to run the the Dingo Router and will fail.

Similar error has been reported on Laravel Admin Github page:

https://github.com/z-song/laravel-admin/issues/2509

#### Possible Solutions

I think the validators should be connected via logical AND instead of OR.

```
/**
 * Validate a request.
 *
 * @param \Illuminate\Http\Request $request
 *
 * @return bool
 */
public function validateRequest(IlluminateRequest $request)
{
	$passed = false;

	foreach ($this->validators as $validator) {
		$validator = $this->container->make($validator);

		if ($validator instanceof Validator && $validator->validate($request)) {
			$passed = true;
		}
	}

	// The accept validator will always be run once any of the previous validators have
	// been run. This ensures that we only run the accept validator once we know we
	// have a request that is targeting the API.
	if ($passed) {
		$this->container->make(Accept::class)->validate($request);
	}

	return $passed;
}
```

vs

```
/**
 * Validate a request.
 *
 * @param \Illuminate\Http\Request $request
 *
 * @return bool
 */
public function validateRequest(IlluminateRequest $request)
{
	$passed = false;

	foreach ($this->validators as $validator) {
		$validator = $this->container->make($validator);

		if ($validator instanceof Validator && $validator->validate($request)) {
			$passed = true;
		} else {
			$passed = false;
		}
	}

	// The accept validator will always be run once any of the previous validators have
	// been run. This ensures that we only run the accept validator once we know we
	// have a request that is targeting the API.
	if ($passed) {
		$this->container->make(Accept::class)->validate($request);
	}

	return $passed;
}
```

**Comment by specialtactics** [comment]
@Schnoop I think the reason is that Dingo is not compatible with that package - at least route wise.

If you set them up in the same project, probably you will want to separate out their namespaces in your route service provider.

It wouldn't make sense for validators to be connected with AND because that's not how the package works and it would break in many situations. The idea is that any match of a validator should trigger the router.
