### ISSUE TITLE
Issue on jwt-auth2.0.x-dev

### ISSUE THREAD

**Issue by boxshadow** [dingo/api#1648]
sorry about that I'm not good at English,
how can i use this with  "tymon/jwt-auth": "2.0.x-dev",
when I do [this step](https://github.com/dingo/api/wiki/Configuration#authentication-providers),
i got an exception: needs an instance of Tymon/JWTAuth/JWTAuth, 
but[ jwt-auth2.0.x-dev](https://packagist.org/packages/tymon/jwt-auth#2.0.x-dev) doesn't have this class now,
 I don't know how to resolve this

**Comment by specialtactics** [comment]
Hi, I don't think you should be using 2-dev with this package. You should use version 1.
