### ISSUE TITLE
include error Call to undefined relationship

### ISSUE THREAD

**Issue by mdeprezzo** [dingo/api#1650]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.8.*
| Package version   | 2.2.*
| PHP version       | 7.2

#### Actual Behaviour

When i try to include something, that isn't a model relationship got that error. This is strange, because on dingo 2.0.0-alpha1 i do that, and all works fine.

#### Expected Behaviour

Return the data from custom includes

#### Steps to Reproduce

Define a custom include. Meaning, that the data to includes comes to the custom incude define on 
```
$availableIncludes = [..]
```

**Comment by specialtactics** [comment]
Hey @mdeprezzo 

Can you please provide a more substantial example? Code snippets appreciated.

**Comment by mdeprezzo** [comment]
@specialtactics sure, maybe I misunderstood the availableIncludes option. 
But, if i tried to include something that isn't a model relation i got that error. Example:


i've a custom method inside model that return an array of files from s3.

So i define that:

```
$availableIncludes = [
  'images'
]

public function includeImages(Model $model)
{
  return $model->getImages()
}
```

**Comment by specialtactics** [comment]
Hi @mdeprezzo 

The includes actually get eventually passed to eloquent's with() function, so it won't work if it's just your own function that returns an array - they have to be actual relations.

Because you essentially just want to attach arbitrary data if a certain query param is set, so you can implement that logic yourself.

**Comment by mdeprezzo** [comment]
@specialtactics I'm sure, that in past version could add some custom includes, and i already did. Btw, thanks for reply
