### ISSUE TITLE
FormRequest->withValidator is never getting called

### ISSUE THREAD

**Issue by sudkumar** [dingo/api#1653]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.8.0
| Package version   | 2.2.3
| PHP version       | 7.2.14

#### Actual Behaviour

`withValidator` function gives us the ability the customise the validator instance before evaluating the rules. But [withValidator](https://github.com/dingo/api/blob/8f97fadae800202e618e0c3f678b4aab78e1dc05/src/Http/FormRequest.php#L105) is never getting called, because in [LumenServiceProvider](https://github.com/dingo/api/blob/14225351b2a9b652f6814851539370645c0c1fac/src/Provider/LumenServiceProvider.php#L58), we are directly calling the [$resolved->validate()](https://github.com/dingo/api/blob/8f97fadae800202e618e0c3f678b4aab78e1dc05/src/Http/FormRequest.php#L75) which never calls the `FormRequest->getValidatorInstance` method.

#### Expected Behaviour

`withValidator` should be called before evaluating the rules.

#### Steps to Reproduce

I am using the `withValidator` function to validate the `current_password` field when a `Change Password` request comes.
```php
<?php
namespace App\Http\Requests;

use Dingo\Api\Http\FormRequest;
use Illuminate\Validation\Validator;

class ChangePasswordRequest extends FormRequest
{
  public function authorize(): bool {
    return true;
  }

  public function rules(): array
  {
    return ["current" => "required|string", "password" => "required|string|confirmed"];
  }

  public function withValidator (Validator $validator): void
  {
    $validator->after(function ($validator) {
      if (!app('hash')->check($this->current, $this->user()->password)) {
        $validator->errors()->add("current", "Current password is incorrect");
      }
    });
  }
}
```
Here, `withValidator` function is never getting called and validation passes even when the current password in not correct.

#### Possible Solutions

As described in [FormRequestServiceProvider](https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L30), we should call `$resolved->validateResolved()` in the LumenServiceProvider.

**Comment by sudkumar** [comment]
PR #1654

**Comment by specialtactics** [comment]
Resolved in above PR.
