### ISSUE TITLE
Failed Force to HTTPS

### ISSUE THREAD

**Issue by cacing69** [dingo/api#1656]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.6.y
| Package version   | 2.0.0-alpha2
| PHP version       | 7.x.y

i can't access my api after change to https, i try add 
`URL::forceScheme('https');` on boot method from class `AppServiceProvider` but its not changed.

[error_image](https://imggmi.com/full/2019/5/13/8763045b270b410ac8b3752879912e30-full.png.html)
[try_change](https://imggmi.com/full/2019/5/13/4244b63038b7a53e59cf53ac6606e2a4-full.png.html)

**Comment by gazben** [comment]
@cacing69 I think this is a problem with the cert. The url itself is https and the application responds.

**Comment by specialtactics** [comment]
You are using quite an old version of the package, I think there have been changed to the url generator since, so you should update that and your laravel version as well actually.

If it is still a problem, please do let us know.

**Comment by cacing69** [comment]
I will try to create new app for try this.. but bassicaly can its work on lumen ?

**Comment by specialtactics** [comment]
I am not quite sure as I don't use lumen myself these days.

**Comment by cacing69** [comment]
i will try and confirm here :D
