### ISSUE TITLE
Cannot use [Class, 'action'] instead 'Calss@action' in routes

### ISSUE THREAD

**Issue by Zolotov88** [dingo/api#1660]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.8.18
| Package version   | 1.2.3
| PHP version       | 7.3.4

#### Actual Behaviour
Rote
`$api->post('signup', ['as' => 'signup', 'uses' => [AuthController::class, 'signUp']]);`
is not working. Rote
`$api->post('signup',  [AuthController::class, 'signUp']);`
is not working

#### Expected Behaviour
Expecting that it can work like laravel routes

**Comment by specialtactics** [comment]
Because Dingo uses it's own router, not everything that Laravel supports is available in Dingo.

Not going to address this because before too long the routing will be re-done anyway.
