### ISSUE TITLE
 No value(s) specified

### ISSUE THREAD

**Issue by grozwalker** [dingo/api#1665]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.23
| Package version   | 2.2.3
| PHP version       | 7.3

#### Actual Behaviour

When create documentation url with params package create md looks like:

```
+ Parameters
    + offset: (integer, optional) - The offset of results to start view.
        + Default: 0
```

But when it paste to apiary.io it validation thow error:
```
no value(s) specified
```

#### Expected Behaviour

Apiary validator expected parametr without colon:
```
+ Parameters
    + offset (integer, optional) - The offset of results to start view.
        + Default: 0
```

#### Possible Solutions

Maybe we can config outputs?

**Comment by grozwalker** [comment]
Fix it in https://github.com/dingo/blueprint/pull/77

**Comment by specialtactics** [comment]
Hi

How sure of this are you?

https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-uriparameters-section

The reason it says no value specified is because you are not giving an example value inside backticks. In your example, you need to do the following:

```
+ Parameters
    + offset: `100` (integer, optional) - The offset of results to start view.
        + Default: 0
```

**Comment by grozwalker** [comment]
But if you do not want to specify an example, the syntax is different

**Comment by specialtactics** [comment]
Ah nevermind, I read further into it, and I now realise your use case. I will merge the PR.
