### ISSUE TITLE
Must I use a domain name prefix?

### ISSUE THREAD

**Issue by StringKe** [dingo/api#1669]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.26
| Package version   | 2.3
| PHP version       | 7.3

I used IP as the site to access, this is to avoid the confusion of DNS resolution in China, my project will not use the domain name

**Comment by specialtactics** [comment]
You can leave the API_DOMAIN blank, but you will need to set the API_PREFIX, yes (in which case, you can use it with any domain, so long as the prefix is correct). One of those two must be set though.
