### ISSUE TITLE
dingo api response throw function makeFromJson changed my data type

### ISSUE THREAD

**Issue by nathanyyl** [dingo/api#1670]
hello  everyone,

i have a question: 
original data(json): {"message":"success","status_code":200,"data":{"userinfo":{"id":500,"phone":"***","headimgurl":{},"auth_code":"","org":{}},"score":28}}

new data:{"message":"success","status_code":200,"data":{"userinfo":{"id":500,"phone":"***","headimgurl":[],"auth_code":"","org":[]},"score":28}}

thanks

**Comment by specialtactics** [comment]
Can you please use the issue template, code block formatting and give a more detailed explanation.
