### ISSUE TITLE
Support for 'apiResource()'

### ISSUE THREAD

**Issue by xitianfz** [dingo/api#1676]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.8.34
| Package version   | 2.3.0
| PHP version       | 7.3.3

Please support `Route::apiResource()`: 
```php
$api->apiResource('foo', 'FooController');
```

**Comment by specialtactics** [comment]
Sure, I will take a look when I have a bit more time.

**Comment by exninja** [comment]
I've been using the following for my resource controllers without a hitch since I migrated to using dingo a week ago:

`$api->resource('foo', FooController');`

**Comment by specialtactics** [comment]
Yeh, that is actually in the Dingo router, so not sure what else there would be to do on this, closing.
