### ISSUE TITLE
Overriding Base Url Issue

### ISSUE THREAD

**Issue by kadircanerergun** [dingo/api#1686]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.x
| PHP version       | 7.1.x

#### Actual Behaviour

Im using route command to generate routes. In my local everything works fine. But in production server there is an .htaccess rule as  "RewriteBase /gw"

In production server routes are generated without rewrite rule "gw".

#### Expected Behaviour

when use route() function url should be http://{domain}//gw/{uri}

but in my case it has been generated as http://{domain}/{uri}

What should i do to add gw without breaking the original (without htaccess rule) route method.

**Comment by specialtactics** [comment]
Hi

You are using the old issue template, please use the new one - you need to specify your dingo version.
