### ISSUE TITLE
personalize message error UnknownVersionException to spanish

### ISSUE THREAD

**Issue by FuriosoJack** [dingo/api#1706]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.7.y
| Package version   | 2.4.y
| PHP version       | 7.2

#### Actual Behaviour

Add message language exeptions

**Comment by specialtactics** [comment]
Hi, this is not really the responsibility of the package, but yours as developer of the application.

There's a lot of exceptions that get thrown around, and most of them are not even inside of this package. If you need to return localised error messages, you should set the exception message yourself.

**Comment by FuriosoJack** [comment]
> Hi, this is not really the responsibility of the package, but yours as developer of the application.
> 
> There's a lot of exceptions that get thrown around, and most of them are not even inside of this package. If you need to return localised error messages, you should set the exception message yourself.


I disagree. For example, the exception when the Accept header is not sent. That exception is not documented so it is very tedious to look for the exceptions and know what is the class to make a hook according to the instanceof and so now that is with one but now with many it is a tedious task.

**Comment by specialtactics** [comment]
@FuriosoJack Yes but, these exceptions are not actually meant to be read by humans, they are meant to be read by either other APIs or developers debugging them.

You should not display these exceptions' messages to your end users - only things like validation errors (which are translated).
