### ISSUE TITLE
Laravel 6.18.2(PHP7.2.25) Installation failed.

### ISSUE THREAD

**Issue by lyongdee** [dingo/api#1725]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install dingo/api v3.0.0
    - Conclusion: don't install dingo/api v3.0.0-rc3
    - Conclusion: don't install dingo/api v3.0.0-rc2
    - dingo/api v3.0.0-rc1 requires dingo/blueprint ^0.4 -> satisfiable by dingo/blueprint[v0.4.0, v0.4.1].
    - Conclusion: don't install dingo/blueprint v0.4.0
    - Conclusion: remove laravel/framework v6.18.2
    - Installation request for dingo/api ^3.0 -> satisfiable by dingo/api[v3.0.0, v3.0.0-rc1, v3.0.0-rc2, v3.0.0-rc3].
    - Conclusion: don't install dingo/blueprint v0.4.0|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 3.1.0|install phpdocumentor/reflection-docblock 3.1.1|install phpdocumentor/reflection-docblock 3.2.0|install phpdocumentor/reflection-docblock 3.2.1|install phpdocumentor/reflection-docblock 3.2.2|install phpdocumentor/reflection-docblock 3.2.3|install phpdocumentor/reflection-docblock 3.3.0|install phpdocumentor/reflection-docblock 3.3.2|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install dingo/blueprint v0.4.0|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 3.1.0|install phpdocumentor/reflection-docblock 3.1.1|install phpdocumentor/reflection-docblock 3.2.0|install phpdocumentor/reflection-docblock 3.2.1|install phpdocumentor/reflection-docblock 3.2.2|install phpdocumentor/reflection-docblock 3.2.3|install phpdocumentor/reflection-docblock 3.3.0|install phpdocumentor/reflection-docblock 3.3.2|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Installation request for phpdocumentor/reflection-common (locked at 2.0.0) -> satisfiable by phpdocumentor/reflection-common[2.0.0].
    - Conclusion: don't install dingo/blueprint v0.4.0|remove phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 3.1.0|install phpdocumentor/reflection-docblock 3.1.1|install phpdocumentor/reflection-docblock 3.2.0|install phpdocumentor/reflection-docblock 3.2.1|install phpdocumentor/reflection-docblock 3.2.2|install phpdocumentor/reflection-docblock 3.2.3|install phpdocumentor/reflection-docblock 3.3.0|install phpdocumentor/reflection-docblock 3.3.2|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: don't install dingo/blueprint v0.4.0|don't install phpdocumentor/reflection-docblock 5.1.0|install phpdocumentor/reflection-docblock 3.1.0|install phpdocumentor/reflection-docblock 3.1.1|install phpdocumentor/reflection-docblock 3.2.0|install phpdocumentor/reflection-docblock 3.2.1|install phpdocumentor/reflection-docblock 3.2.2|install phpdocumentor/reflection-docblock 3.2.3|install phpdocumentor/reflection-docblock 3.3.0|install phpdocumentor/reflection-docblock 3.3.2|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Installation request for phpdocumentor/reflection-docblock (locked at 5.1.0) -> satisfiable by phpdocumentor/reflection-docblock[5.1.0].
    - Conclusion: don't install laravel/framework v6.18.2
    - dingo/blueprint v0.4.1 requires illuminate/support ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2].
    - Can only install one of: laravel/framework[7.x-dev, v6.18.2].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.0|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.1|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.2|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.3|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.4|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.5|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.6|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.7|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.0.8|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.1.0|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.1.1|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.1.2|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.1.3|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.2.0|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.2.1|don't install laravel/framework v6.18.2
    - don't install illuminate/support v7.2.2|don't install laravel/framework v6.18.2
    - Installation request for laravel/framework (locked at v6.18.2, required as ^6.2) -> satisfiable by laravel/framework[v6.18.2].

**Comment by specialtactics** [comment]
Hi

Dingo v3 is for Laravel 7
If you have Laravel 6, you will need to use v2.

I will update wiki to make this clear.
