### ISSUE TITLE
Question: Does this package use the JSON API as a default response?

### ISSUE THREAD

**Issue by SuperlativeEntity** [dingo/api#1726]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.x
| Package version   | latest
| PHP version       | 7.2

#### Question

Does this package use the JSON API as a default response?

#### Actual Behaviour

N/A

#### Expected Behaviour

N/A

#### Steps to Reproduce

N/A

#### Possible Solutions

N/A

**Comment by specialtactics** [comment]
Hey @SuperlativeEntity - what do you mean?

**Comment by SuperlativeEntity** [comment]
https://jsonapi.org/

**Comment by specialtactics** [comment]
I doubt it, but not sure. Best way is to try it and see!

**Comment by SuperlativeEntity** [comment]
okay, so in order to use the JSON API standard, you need to implement a different serializer:

E.g. https://github.com/dingo/api/issues/679

**Comment by catalinux** [comment]
There is a such serializer in fractal: https://github.com/thephpleague/fractal/blob/master/src/Serializer/JsonApiSerializer.php

**Comment by SuperlativeEntity** [comment]
100%, the link I provided explains how to use that serializer
