### ISSUE TITLE
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Auth\Auth, Dingo\Api\Routing\Router]. in vendor/laravel/framework

### ISSUE THREAD

**Issue by Uptron** [dingo/api#1731]
I am getting the error below when i try to run my laravel project.(larvel 7.0 and Php Version 7.2)

I have tried php artisan cache:clear and composer dump-autoload but the error still persists.
I have also added Dingo\Api\Provider\LaravelServiceProvider::class in config/app.php
 

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Auth\Auth, Dingo\Api\Routing\Router]. in /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Container/Container.php:1011
Stack trace:
#0 /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Container/Container.php(814): Illuminate\Container\Container->notInstantiable('Dingo\\Api\\Contr...')
#1 /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->build('Dingo\\Api\\Contr...')
#2 /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('Dingo\\Api\\Contr...', Array, true)
#3 /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Foundation\Application->resolve('Dingo\\Api\\Contr...', Array)
#4 /var/www/html/a in /var/www/html/adopt_a_farmer/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1011

**Comment by specialtactics** [comment]
Hi, please use the issue template - in particular, we need to know the version restriction of dingo you have in your composer file when updating.

**Comment by rlatkn** [comment]
I have a same issue while trying to use JsonApiSerializer according documentaion, dingo/api "version": "v3.0.0", laravel/framework v7.11.0

**Comment by fhferreira** [comment]
+1

**Comment by shijunti19** [comment]
+1

**Comment by shijunti19** [comment]
```php
//注册Dingo\Api
        if (class_exists(\Dingo\Api\Provider\LaravelServiceProvider::class)) {
            $this->app->register(\Dingo\Api\Provider\LaravelServiceProvider::class);
        }
```

**Comment by specialtactics** [comment]
No further info provided in a while.
