### ISSUE TITLE
Header values must be RFC 7230 compatible strings

### ISSUE THREAD

**Issue by juansebasleal** [dingo/api#1736]
In a Laravel Controller, I am returning `$this->response->noContent()`, which returns a Dingo Response.
Then, I'm running a validator on the response and I'm getting the following error:

> Header values must be RFC 7230 compatible strings

I see what is causing it is:
```
$defaultContentType = $this->headers->get('Content-Type');
$this->headers->set('Content-Type', $formatter->getContentType());
```
in the `Dingo\Api\Http\Response::morph()` method
https://github.com/dingo/api/blob/42c5b78d010fbd97dc73aa01b259f05b1f033ce6/src/Http/Response.php#L145

I think there should be a validation: `if ($formatter->getContentType()) { // Add content type }`

Our current Dingo version is 2.0.1

Thanks.

**Comment by specialtactics** [comment]
Hi @juansebasleal - can you explain why it is actually not valid and provide an example ?

**Comment by juansebasleal** [comment]
Hi @specialtactics  
Well, if the response has not actual body (HTTP 204 response), it should not have Content-Type because there's no content.

The example would be easy to setup: In any controller just respond with DingoResponse->noContent().
Also, here you can see an example of how we get Content-Type: (null)
![image](https://user-images.githubusercontent.com/525050/89214823-21a83c00-d58d-11ea-901e-35939b028939.png)

What I think is that it's happens because in api/src/Http/Response.php, method morph(), $formatter->getContentType() is null.

Additionally, this is more evident when we use a validator, in this case https://github.com/Nyholm/psr7, and we see that in fact it fails because of what said above.

My environment:
Laravel: 5.7.15
Dingo: 2.0.1
Validator: 1.3.0

Hopefully this helps clarify the issue.

**Comment by specialtactics** [comment]
Hey @juansebasleal thanks, that was quite detailed.

I believe I've fixed the issue now, you can try the latest master if you like to confirm, it will be tagged before too long but there are also other changes there for testing.
