### ISSUE TITLE
Laravel 8 Support?

### ISSUE THREAD

**Issue by khanhvu14** [dingo/api#1745]
Laravel 8 has just realeased, can add new tag support it?

**Comment by Vivian-A** [comment]
I can't get it to install on Laravel 8 unfortunately.

**Comment by specialtactics** [comment]
Would you guys mind pulling in this commit locally and testing with your project and Laravel 8?

I will do the same testing, but I want as many people as possible to test to find issues before we push support live.

https://github.com/dingo/api/commit/660fd77164fb4c61981f94d78e5cea67212a16ce

**Comment by zaher-code-07** [comment]
@specialtactics I face this issue when installing from source

php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"
Unable to locate publishable resources.
Publishing complete.

**Comment by bbashy** [comment]
@specialtactics Just tested with newly upgraded project using `"dingo/api": "dev-master#660fd77164fb4c61981f94d78e5cea67212a16ce",` and it works fine by the looks of it. Got a few routes with a custom guard (sanctum) and no errors.

**Comment by specialtactics** [comment]
Thanks for your help @bbashy 

Just in case people might be looking over this, I will set a deadline of **21st of September** of when I will tag it, assuming no errors are uncovered from testing.

**Comment by gazben** [comment]
@specialtactics Did you find any errors? Can you tag the next version?

**Comment by anardil** [comment]
@specialtactics any news about the support of Laravel 8?

**Comment by specialtactics** [comment]
Tagged here guys !
https://github.com/dingo/api/releases/tag/v3.0.2-rc1

**Comment by gtjamesa** [comment]
All API tests are passing on my application with custom guards 👍  Thanks for tagging @specialtactics

**Comment by khanhvu14** [comment]
Thanks @specialtactics  I tested about 2 weeks with small and medium projects. Everything seems work well.

**Comment by specialtactics** [comment]
If anyone ends up having any problems relating to laravel 8, feel free to report as a new issue.
