### ISSUE TITLE
PHP Fatal error:  Declaration of Dingo\Api\Exception\Handler::report(Throwable $throwable) must be compatible with Illuminate\Contracts\Debug\ExceptionHandler::report(Exception $e) in

### ISSUE THREAD

**Issue by littlestarsx** [dingo/api#1746]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel
| Framework version | 5.8.3
| Package version   | ^3.0
| PHP version       | 7.2.28

#### Actual Behaviour

Describe the behaviour you're experiencing. Do not just copy and paste a random error message and expect help.

#### Expected Behaviour

Describe the behaviour you're expecting.

#### Steps to Reproduce

List all the steps needed to reproduce the issue you're having. Make sure to include code (affected models, configurations),
any screenshots and/or other resources that may help us understand what's going on.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by specialtactics** [comment]
You are using the wrong version of the package for your laravel version. You need laravel 6 for version >=3.

You should really update your laravel version, it's quite old and we do not support it.
