### ISSUE TITLE
composer install dingo/api

### ISSUE THREAD

**Issue by aszymkiw** [dingo/api#1749]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.28.1
| Package version   | 3.0.0
| PHP version       | 7.4.3

#### Actual Behaviour
Hello everyone,

Thank you for advance for your help ! When i install dingo/api by composer, i get an error and it's impossible to install this module.

Here the message : 

`Argument 1 passed to Dingo\Api\Http\Response::setFormatters() must be of the type array, null given, called in /home/aszymkiw/project/SilverPredict/vendor/dingo/api/src/Provider/DingoServiceProvider.php on line 34
`

#### Expected Behaviour

I expected that it is installed without problem.

#### Steps to Reproduce

To reproduce this problem, to have the same system that mine and composer require dingo/api.

Thank you for your help !

**Comment by specialtactics** [comment]
Hi, you probably did not copy over the config file (config/api.php) or run the command that copies it. Please follow the install instructions.
