### ISSUE TITLE
Route regular expression constraints

### ISSUE THREAD

**Issue by kevinklinegargar** [dingo/api#1751]
Hi,
Dingo support Laravel route regular expression like in the stock Laravel ? 
I can't find in Dingo docs, does have a plan to integrate this ?

**Comment by specialtactics** [comment]
Hi, if you're talking about what I think you're talking about - ie;

```
Route::pattern('paramName', 'regexp');
```

Then yes it does, and in fact even that syntax is exactly the same as Laravel Routing, so just put that for example in the **boot** method of your route service provider, and it should work.
