### ISSUE TITLE
HTTP Status Code Above 500

### ISSUE THREAD

**Issue by philipborbon** [dingo/api#1754]
This line does not allow status code above 500.
https://github.com/dingo/api/blob/85866b76621d620fc8e1354e56a51ba0f082c9d8/src/Exception/Handler.php#L218

There's a whole range of status codes above 500.

What could be the reason 500+ is not allowed? 100 - 599 seems plausible.

**Comment by specialtactics** [comment]
@philipborbon Yep, I see what you mean, I will make it > 599

**Comment by specialtactics** [comment]
Fixed, tagged as v3.0.4
