### ISSUE TITLE
front-end when i call api then getting 405 Method Not Allowed

### ISSUE THREAD

**Issue by Narendra93** [dingo/api#1780]
I have pass in header.
```
URL: {{Base_URL}}/store-update
Method: POST
Accept: version10,
Content-Type: application/json
```
But not working.By default call version1.Can you please help me for that issue.
I have also create cors middlware but request header not setting.Also this api working fine in android,ios device but front-end not working.

**Comment by specialtactics** [comment]
If you are getting method not allowed, it means you there is no route with the requested method at the requested url path (endpoint).

Sorry but overall your question seems to have nothing to do with dingo - dingo has nothing to do with android, ios vs frontend, etc.

**Comment by Narendra93** [comment]
Hi
@specialtactics 
End point is there in v2 and default calling v1.So i have pass also header but not getting that request in backend always checked with v1 not in v2.

**Comment by specialtactics** [comment]
usually you would prefix /v2/path

Maybe worthwhile checking docs
