### ISSUE TITLE
Laravel 9 issue while try to install dingo

### ISSUE THREAD

**Issue by Elikar-KM** [dingo/api#1807]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 9
| Package version   | 3.0.8
| PHP version       | 8

#### Expected Behaviour

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api 3.0.8 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v3.0.8].
    - api-ecosystem-for-laravel/dingo-api v3.0.8 requires illuminate/routing ^7.0|^8.0 -> found illuminate/routing[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by specialtactics** [comment]
Hi, this is already addressed in api-ecosystem-for-laravel/dingo-api please use the latest version.
