### ISSUE TITLE
Dingo/api in Laravel 5?

### ISSUE THREAD

**Issue by alairock** [dingo/api#189]
Is dingo going to be available in Laravel 5? Or do you know if Laravel 5 will have some of this already built into it.

**Comment by ghprod** [comment]
wait for develop branch become stable for L5 .. :+1:

**Comment by torniker** [comment]
+1 need this package for laravel 5.1

**Comment by jasonlewis** [comment]
It's available for 5.1.

**Comment by torniker** [comment]
@jasonlewis  thanks

**Comment by silentFred** [comment]
+1

**Comment by jasonlewis** [comment]
I'm confused... What are you doing a +1 for? The package is available on
5.1.

**Comment by silentFred** [comment]
Excitement
