### ISSUE TITLE
Issue Router::setControllerDispatcher() after updating to latest version of Laravel 5.0

### ISSUE THREAD

**Issue by rowino** [dingo/api#211]
Hi,

I get this issue after updating to the latest version of Laravel 5.0. Any ideas?

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to undefined method Dingo\Api\Routing\Router::setControllerDispatcher()

Open: /home/vagrant/projects/api/vendor/dingo/api/src/Provider/RoutingServiceProvider.php

```
    $this->app->bindShared('router', function ($app) {
        $router = new Router($app['events'], $app);

        if ($app['env'] == 'testing') {
            $router->disableFilters();
        }

        $router->setControllerDispatcher(new ControllerDispatcher($router, $app));

        return $router;
```

Thanks for the help

**Comment by rodrigobendia** [comment]
This error persists after L5 release.

**Comment by GrahamCampbell** [comment]
Yes, L5 is NOT supported.
