### ISSUE TITLE
Consider putting pagination data in headers?

### ISSUE THREAD

**Issue by HipsterJazzbo** [dingo/api#246]
I've been wondering lately if it might be worth putting pagination data in headers. There are a lot of times when I just want to know how many of something there are, and it'd be sweet if I could do a `HEAD` request to find out.

[This article](http://otac0n.com/blog/2012/11/21/range-header-i-choose-you.html) has some interesting thoughts on using Range headers for this purpose.

Thoughts?

**Comment by Tom5om** [comment]
I am really interested in this feature, I am going to look into extending the package to do that as I really need it. If you guys have any tips on how to do it that would be greatly appreciated!

**Comment by Tom5om** [comment]
To do this as a quick and dirty solution i have added this in the morph function of the Response.php file:

         } elseif (is_array($content) || $content instanceof ArrayObject || $content instanceof ArrayableInterface) {

            //check if meta key exists for pagination data
            if(array_key_exists('meta', $content)) {

                //get the meta data
                $meta = $content['meta'];

                //set a header for each pagination item in the meta data
                foreach ($meta['pagination'] as $key => $val) {
                    $this->headers->set(camel_case('pagination_'.$key), $val);
                }

                //remove the meta data from the array
                unset($content['meta']);
            }

            $content = $formatter->formatArray($content);
        }

Obviously this is a quick and very dirty solution, but I am not very familiar with dingo yet, if any of you could point me in the right direction how this could be done more clean that would be much appreciated!

**Comment by jasonlewis** [comment]
I've decided against adding this to the core. I have just implemented some events that you can use to tweak the response before and after morphing.

Refer to docs for more: https://github.com/dingo/api/wiki/Responses#morphing-and-morphed-events

Going to close this now.
