### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by ryanhungate** [dingo/api#26]
Now the api wont return an array response...  I just did a DD under the $class = and it prints out my array that was returned in the response.

```
protected function hasTransformer($class)
    {
            $class = is_object($class) ? get_class($class) : $class;
            return isset($this->transformers[$class]);
    }
```

**Comment by Ortix92** [comment]
I'm experiencing this same issue with the following collection
```
return (\Illuminate\Support\Collection::make([['id' => '25429', 'title' => 'Some Title'], ['id' => '25429', 'title' => 'Some Title'], [3], [4]]));
```

I just ran a composer update with no effect.

Running dingo 0.8.* : `"dingo/api": "0.8.*"`

**Comment by bweston92** [comment]
Use the response builder.



—
