### ISSUE TITLE
Basic auth no longer working with 0.7

### ISSUE THREAD

**Issue by Ehesp** [dingo/api#261]
I've just upgraded to .7, and Basic Auth seems to have stopped working.

```
    'auth' => [
        'basic' => function ($app) {
            return new Dingo\Api\Auth\BasicProvider($app['auth'], 'email');
        }
    ],
```

I've got a web page login working, using standard Laravel Auth, however all requests sent to protected routes seem to be failing.

```
$ curl -X POST --user my.email@gmail.com:password http://myapp.app:8000/api/components
{"message":"Invalid authentication credentials.","status_code":401}
```

Using the same credentials works via the 'web login', also had this working yesterday too before upgrading. Am I missing something?

Laravel 4.2 by the way.

**Comment by Ortix92** [comment]
I'm having the same issue. No matter what I try, I can not use the laravel 4.2 basic auth functionality.

I protected my route in the constructor and this is the response after making a post request with postman:

`{"message":"Invalid authentication credentials.","status_code":401}`

I'm using `0.8.2`
