### ISSUE TITLE
Class 'Dingo\Api\ApiServiceProvider' not found after Composer Update

### ISSUE THREAD

**Issue by nielsiano** [dingo/api#262]
I'm getting an Error after running Composer Update to upgrade to 0.7, It's late and I might be missing something here. Any clues?

It's still present in the app.php config.

```
PHP Fatal error:  Class 'Dingo\Api\ApiServiceProvider' not found in /var/www/site/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
```

**Comment by tusharcoder** [comment]
But it is 'Dingo\Api\Provider\ApiServiceProvider' and it is abstract class, this gives error
                                                                          
  [Symfony\Component\Debug\Exception\FatalErrorException]                  
  Cannot instantiate abstract class Dingo\Api\Provider\ApiServiceProvider

**Comment by tusharcoder** [comment]
it is 'Dingo\Api\Provider\LaravelServiceProvider' and then to publish
php artisan vendor:publish

**Comment by darmie** [comment]
@tusharcoder  were you able to fix this? I am having the same problem

**Comment by jasonlewis** [comment]
You want to either use `Dingo\Api\Provider\LaravelServiceProvider` or `Dingo\Api\Provider\LumenServiceProvider`depending on the framework you're using.
