### ISSUE TITLE
Pagination response when no results are returned

### ISSUE THREAD

**Issue by bweston92** [dingo/api#263]
When there are no results being returned, the response structure is inconsistent.

Returned
---
```
{
    "total": 0,
    "per_page": 5,
    "current_page": 500,
    "last_page": 0,
    "from": 0,
    "to": 0,
    "data": []
}
```

Expecting
---
```
{
    "data": [],
    "meta": {
        "pagination": {
            "total": 0,
            "count": 5,
            "per_page": 5,
            "current_page": 500,
            "total_pages": 0,
            "links": {}
        }
    }
}
```

**Comment by bweston92** [comment]
So what is the status for this issue?

**Comment by jasonlewis** [comment]
Status is much the same... The response should be fine when using the response builder. The `TransformableInterface` is deprecated so avoid using that way of transforming models and what not.

**Comment by cweiske** [comment]
We still have this problem in december 2016 with dingo/api dc312a5.

Our controller action returns `$query->paginate(15)`, a `LengthAwarePaginator`.
Dingo's `Response::morph()` method then decides that the paginator without data is not transformable and thus stays the Paginator object (is not transformed). The paginator with data is transformed to an array, and the formatter's `formatArray` method is used on it.

So there are two code paths:
- no data: `LengthAwarePaginator->__toArray()`
- data: `Dingo\Api\Http\Response\Format\Json->formatArray`
