### ISSUE TITLE
Possible Package Incompatibilities

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#270]
If you come across a package incompatibility please report it here as well as any errors and a solution to solve the incompatibility (order of service providers, etc).

I'd like to get to the root cause of each incompatibility though so we don't need to order the service providers in any special way. I'll keep a running list of packages that are incompatible and mark them off once they are compatible.

- [x] ~~[Asset Pipeline](https://github.com/CodeSleeve/asset-pipeline)~~    
    This package works fine with the latest version of Dingo API.
- [x] ~~[Laravel Administrator](https://github.com/FrozenNode/Laravel-Administrator)~~    
    This has been fixed as of a2681c4. The routes were lost when the bound router was replaced.

**Comment by DeanWard** [comment]
Installing https://github.com/slampenny/Swaggervel causes dingo api to break with the error 
Call to undefined method Illuminate\\Routing\\Router::api()

**Comment by Gtskk** [comment]
Issue with "stevemo/cpanel": "dev-master"

**Comment by jasonlewis** [comment]
The latest `0.9.*@dev` version for Laravel 5 and Lumen *should* no longer conflict with other packages.

**Comment by jonaholsson** [comment]
Slampenny's Swaggervel still causes a conflict. Any news on this? I'd like to use the 1.*@dev branch of jlapp/swaggervel
