### ISSUE TITLE
Use of different Fractal Serializers

### ISSUE THREAD

**Issue by stelgenhof** [dingo/api#300]
Hi,

Is it possible to use different Fractal Serializers? I would like to use JSONAPI Serializer but couldn't find information how to. In the issues I could find some discussions around this topic however not a clear answer.

Thanks! Sacha

**Comment by iamrutvik** [comment]
@jasonlewis 

After adding your suggestion in config/api.php like this : 

'transformer' => function () {
        $fractal = new League\Fractal\Manager;
        $fractal->setSerializer(new \League\Fractal\Serializer\JsonApiSerializer);

        return new Dingo\Api\Transformer\FractalTransformer($fractal, 'include', ',');
},

then i fired : php artisan serve

I got this error : 

[ErrorException]
  Argument 2 passed to Dingo\Api\Transformer\Factory::__construct() must be an instance of Dingo\Api\Contract\Transfo
  rmer\Adapter, instance of Closure given, called in E:\wamp\www\projects\laravel\ridealong\trunk\apis\vendor\dingo\a
  pi\src\Provider\ApiServiceProvider.php on line 300 and defined

What is the issue? Only doing this will use json api Serializer?

**Comment by mehrdaad** [comment]
@same error here

**Comment by paishin** [comment]
@iamrutvik, I have the same issue, did you find a solution?

**Comment by edwsno29** [comment]
@iamrutvik , @mehrdad-shokri , @stelgenhof ,fix in app/Providers/AppserviceProvider.php, NOT in config/api.php->'transfomer' key:
`public function boot()
{
    $this->app['Dingo\Api\Transformer\Factory']->setAdapter(function ($app) {
        $fractal = new \League\Fractal\Manager;
        $baseUrl = url('V1/api/');
        $fractal->setSerializer(new \League\Fractal\Serializer\JsonApiSerializer($baseUrl));

        return new \Dingo\Api\Transformer\Adapter\Fractal($fractal, 'include', ',');
    }); 
}
`
