### ISSUE TITLE
User not available in controller constructor?

### ISSUE THREAD

**Issue by sebastiaanluca** [dingo/api#304]
The following should return the user, but it just returns `null`.

``` php
public function __construct(Dispatcher $api, Shield $auth, ResponseBuilder $response)
    {
        parent::__construct($api, $auth, $response);

        dd($this->auth->user());
    }
```

Moving `dd($this->auth->user())` to a controller function like `index` or `store` works. Same thing with `dd(API::user())`, `dd($this->api->user())`, etc btw, just to be clear.

**Comment by Quagh** [comment]
@jasonlewis Somehow it doesn't work anymore? Using `ControllerTrait`, but `$this->auth` is empty in constructor.

v0.8.2.

**Comment by jasonlewis** [comment]
It will always be empty in the constructor. It's not set until after the
controller is instantiated. You'll need to manually type hint and inject it
if you want it earlier.

**Comment by Quagh** [comment]
Yeah, as always I figured out the flow after I posted my message :) I was able to inject it, but then I understood that only once a user accesses a controller method the authorizer could know if it was protected or not.

**Comment by jasonlewis** [comment]
Also true. :-)
