### ISSUE TITLE
URL::route() - route not defined

### ISSUE THREAD

**Issue by ilumos** [dingo/api#307]
Hi there,

Loving the library, has saved loads of time!

When I call `URL::route('api.named.route')` I get a `InvalidArgumentException` "Route [api.named.route] not defined".

The route appears in `php artisan api:routes` no problem and is accessible via Postman but I can't generate a URL for it.

What steps can I take to narrow this down?

Many thanks

**Comment by thylo** [comment]
I had a similar problem, It seems that the problem comes from adding Barryvdh\Debugbar\ServiceProvider from
https://github.com/barryvdh/laravel-debugbar

**Comment by kevindierkx** [comment]
Using [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization) in combination with this package can be troublesome as well. Both do some spiffy injection stuff, even when not using the localization filter on your api routes it would break stuff.

**Comment by jasonlewis** [comment]
A quick look at both those packages would leave me to believe they shouldn't conflict with this package, am yet to fully test them out though.

**Comment by jasonlewis** [comment]
No longer supporting L4.x. At this time L5 and Lumen will not have a URL generator. It will be coming though.
