### ISSUE TITLE
Default JSON "message" key/value not working for strings.

### ISSUE THREAD

**Issue by howardroark** [dingo/api#311]
I have `dingo` configured with a fresh install of Laravel and no models or db configured (yet).  In [this video](http://vimeo.com/93736144#t=2m30s) around `2:30` @jasonlewis makes note that a string will return as the value of the key `message` in a JSON object by default.  This does not seem to be the case for me.

```
Route::api(['version' => 'v1'], function ()
{
    Route::get('stuff', function() {
     return "stuff";
    });
});
```

The http request only ends up returning a string. Here are the response headers...

```
Cache-Control:private, must-revalidate
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Wed, 24 Dec 2014 13:40:50 GMT
Server:nginx/1.4.6 (Ubuntu)
Set-Cookie:laravel_session=HASH...; expires=Wed, 24-Dec-2014 15:40:50 GMT; Max-Age=7200; path=/; httponly
Transfer-Encoding:chunked
X-Powered-By:PHP/5.5.9-1ubuntu4.5
```

Might I be missing anything?

Thanks for any help you can offer and happy holidays!

**Comment by lijinma** [comment]
I got the same issue, thanks.
