### ISSUE TITLE
Package Incompatibility: Swaggervel 

### ISSUE THREAD

**Issue by DeanWard** [dingo/api#318]
Installing https://github.com/slampenny/Swaggervel causes dingo api to break with the error 
`Call to undefined method Illuminate\\Routing\\Router::api()`

**Comment by jasonlewis** [comment]
Please add it to the existing incompatibility issue. Cheers.

**Comment by DeanWard** [comment]
Done :)

**Comment by Quagh** [comment]
Is this still an issue?

**Comment by BRupholdt** [comment]
This is still an issue in Laravel 4

**Comment by GrahamCampbell** [comment]
Laravel 4 isn't maintained anymore.

**Comment by BRupholdt** [comment]
Got it.  So I should forget ever adding anything to my *ancient* L4 apps and port them all to L5.

**Comment by DeanWard** [comment]
While I agree that abandoning L4 is a little premature at this point I think you could probably word your response better @BRupholdt - these guys don't owe you anything.

**Comment by jasonlewis** [comment]
I don't have the time to maintain a package across 2 major versions of the
framework.

**Comment by jasonlewis** [comment]
Also, it wouldn't be feasible considering the nature of the package and the
differences in how Laravel works internally.

**Comment by BRupholdt** [comment]
My apologies @jasonlewis   I took your initial response poorly when I was only meaning to add to the thread in what I thought was a polite way.  I shouldn't have been snarky about it.

**Comment by GrahamCampbell** [comment]
I'm saying Laravel 4 is not maintained, and already has known security vulnerabilities regarding its encryption component. I'd recommend upgrading to Laravel 5.1 ASAP.

**Comment by GrahamCampbell** [comment]
I was not saying this package should abandon L4, i'm saying L4 is already abandoned anyway, so why still support it if it doesn't even support itself if you see what I mean?

**Comment by BRupholdt** [comment]
That makes good sense.  I just read it in the wrong context.  I'm stuck on L4 until I can port to L5, hopefully soon.

**Comment by GrahamCampbell** [comment]
Sure. L5.1 is an LTS release, so you'll get bug fixes until May 2017 and security fixes until May 2018. Way better than the support L4.2 got. :)

**Comment by lightvision** [comment]
**Swaggervel** works without any issues on L5.1 + Dingo\Api.

I had tested and works great. Unfortunately Swagger-PHP doen't allow documentation for multiple api versions.
