### ISSUE TITLE
HTTP 429 when rate limits have been exceeded

### ISSUE THREAD

**Issue by stelgenhof** [dingo/api#319]
Currently a 403 HTTP code is issued when rate limits are exceeded. As per RFC http://tools.ietf.org/html/rfc6585, would 429 not be a better status code?

**Comment by Andreyco** [comment]
+1

**Comment by jasonlewis** [comment]
I'm not the best at deciding on status codes. I've used non-HTTP spec status codes in this package already so probably wouldn't hurt. I believe I went with 403 as that's what GitHub and many others are using for exceeded rate limits.

Send a PR though if you like.

**Comment by stelgenhof** [comment]
403 just means forbidden, whereas 429 means "Too Many Requests" which in my opinion serves much better the situation when rates have been exceeded. I agree it's a grey area :) By the way others like Twitter are using 429 as an error code for example.

Would it be an idea to make it configurable then?

**Comment by Andreyco** [comment]
No configuration please.

429 is more descriptive than 403 so lets settle with 429 only. I will take a look and send a PR.
