### ISSUE TITLE
Query String Filters

### ISSUE THREAD

**Issue by ahsenx** [dingo/api#320]
Is there a way to use query string filters like

/users/1/?_sort=asc&_limit=10

**Comment by Andreyco** [comment]
No, there is not. You need to implement this on your own.

**Comment by jasonlewis** [comment]
Aye it's up to you to implement.

**Comment by bart** [comment]
I know it's an old topic, but I asked myself the same. I found this package: https://github.com/marcelgwerder/laravel-api-handler Maybe it will help you, too.

**Comment by isometriq** [comment]
Just tried this "laravel-api-handler"
+++1
