### ISSUE TITLE
Scopes in router should be a array ?!

### ISSUE THREAD

**Issue by JasonXt** [dingo/api#321]
Route::api(['protected'=>true,'scopes'=>'student'],function(){});  This comes with a error  in LeagueOAuth2Provider.php Line 125  , the $scopes is just a string ,can not be foreach

when changed to below is ok!

Route::api(['protected'=>true,'scopes'=>['student']],function(){});

Is this  a bug?

**Comment by jasonlewis** [comment]
If the docs mention you can pass it in as a string then it should be able to accept the string. So it's most likely a bug. Feel free to send a PR if you can.

**Comment by jasonlewis** [comment]
Pushed a fix for this.
