### ISSUE TITLE
Autoload when using ?include on fractal collections

### ISSUE THREAD

**Issue by LeeMcNeil** [dingo/api#323]
When using the ?include option on endpoints which return a fractal collection the dingo API is trying to autoload the requested relation even if it has not been placed in the availableIncludes array. Entering an include which does not exist causes an exception due to it trying to access a method on the model which doesn't exist.

Thanks :)

**Comment by aikqzung** [comment]
+1
I think I'm facing this problem too.

**Comment by jasonlewis** [comment]
Will #324 solve this?

**Comment by LeeMcNeil** [comment]
As long as it checks if a method exists on the Eloquent model before attempting to call it, that PR should fix the issue.

**Comment by MetalMatze** [comment]
I'm running into the same problem.

**Comment by jasonlewis** [comment]
This should be fixed on `master` now.
