### ISSUE TITLE
Trying to get property of non-object with throw new UpdateResourceFailedException 

### ISSUE THREAD

**Issue by itwy** [dingo/api#326]
Hi,

Simply having this line in my controller:
```
throw new UpdateResourceFailedException('Could not update user.');
```
Returns unexpected exception:
```
ErrorException (E_UNKNOWN)
Trying to get property of non-object
Open: /home/***/vendor/dingo/api/src/Http/ResponseFormat/JsonpResponseFormat.php
    /**
     * Determine if a callback is valid.
     *
     * @return bool
     */
    protected function hasValidCallback()
    {
        return $this->request->query->has($this->callbackName);
    }
 ```
Why is that? That contradicts the documentation here: https://github.com/dingo/api/wiki/Errors-And-Error-Responses#resource-exceptions:

> The package automatically catches the thrown exception and will convert it into its JSON representation. The responses HTTP status code is also changed to match that of the exception. Resources exceptions result in an HTTP 422 status code and the following JSON representation.

Please help. Thanks.

**Comment by aikqzung** [comment]
The error occurs with me too when I use `JsonpResponseFormat`, but it's working properly when I use the default `JsonResponseFormat`.

**Comment by itwy** [comment]
@aikqzung THANK YOU very much. Adjusting what you mentioned fixed my problem.

@jasonlewis Still not sure if this is a bug or not though? Please close the issue if it's not.

**Comment by jasonlewis** [comment]
I'll investigate this when I can, probably won't be for a few days. Sounds like the request instance isn't being passed in though.

**Comment by jasonlewis** [comment]
Okay I've pushed a fix for this. Was an issue with how exceptions were being handled and the formatter was not getting the request and response instances set. Should be all good now.
