### ISSUE TITLE
Generate fractal items/collections without directly returning them

### ISSUE THREAD

**Issue by LeeMcNeil** [dingo/api#327]
Hi

I'm wanting to generate a Fractal collection/item object, however they only seem to work when directly returning them as a response.

For example the following does not work, the offers and events array keys are empty objects:

```
$search = $this->searchRepo->search($hub, $query);

$results['businesses'] = $this->response->collection($search['businesses'], new BusinessTransformer());
$results['offers'] = $this->response->collection($search['offers'], new OfferTransformer());

return $results;
```

However this does work:

```
$search = $this->searchRepo->search($hub, $query);

return $this->response->collection($search['offers'], new OfferTransformer())
```

Any ideas on how to go about this?

Thanks for the help

**Comment by Andreyco** [comment]
If I assume `$results` is type of array and you are returning it, this is logical behaviour - they are not transformed by Fractal.

You need to explicitly return Item or Collection of items to get them transformed and returned as response to request.

**Comment by jasonlewis** [comment]
You'd have to manually transform the data and return it if you want to do this. You're using the response builder which can only build a single response.
