### ISSUE TITLE
Error when accessing a route with a before filter

### ISSUE THREAD

**Issue by prapats** [dingo/api#328]
Hi,

I found the error when I have the following codes:

```
//routes.php
Route::api(['version' => 'v2', 'protected' => true], function () {
    Route::group(['prefix'=>'foo','before'=>'admin_only'],function(){
        Route::get('/bar',function(){
           var_dump('foo bar');
        });
    });
});
```

```
//filters.php
Route::filter('admin_only',function(){
	if(API::user()->user_type_id != 1){
		throw new AccessDeniedHttpException('Access denied.');
	}
});
```

Then I expect the API to return 401 when I try to access it without `access token`. However, I got the error, `Trying to get property of non-object`, that is caused by there is no user yet in the `API::user()`. 

So my assumption is the `before` filter got called before the API filter.

Am I doing anything in the wrong way?
Please suggest.

Thank you.

**Comment by jasonlewis** [comment]
Because authentication is done via a filter it's probably called after your filter. I can have a look about prepending the filters so that the authentication is done first.

**Comment by prapats** [comment]
Cheers @jasonlewis

**Comment by prapats** [comment]
Hi again @jasonlewis ,

I think I'm still facing the same error.

**Comment by jasonlewis** [comment]
@prapats Any more details you can provide? Authentication should be run first but really it shouldn't matter too much. Unless, of course, you're using middlewares. Then it might be a bit fiddly.
