### ISSUE TITLE
Where can I use cache with this api?

### ISSUE THREAD

**Issue by JasonXt** [dingo/api#329]
I want to cache my data to redis  But I used transformer to format my data   In api, it transform it in Router's dispatch method   I could not get the data after being transformed  then cache it  .I am a new guy   Hope someone can help me with that! Thankfully!

**Comment by jasonlewis** [comment]
Can conditional requests help out here? They are built in and should cache responses so that the server need to generate them again.

**Comment by JasonXt** [comment]
I just got the way:
$response = $this->response->item($paper, new PaperTransformer());
$cache= $response->build()->morph();//so I will cache this

BTW : Where can I get help of dingo/api  out of github?

**Comment by jasonlewis** [comment]
Don't really have any other help mediums. It's fine here until it gets to the point where there's a tonne of issues popping up or something. :grin:
