### ISSUE TITLE
Docs generation

### ISSUE THREAD

**Issue by Andreyco** [dingo/api#331]
You know it. You complete you API and then you need to write docs for it.
Which I don't like but I know I can't go without.
*Instead, I would like to have the docs generated by Dingo.*

API endpoints info would be defined in DocBlocks. It could contain info such as:
- request parameters (this could be used to autovalidate request params as well)
- possible includes
- ...
- response (JSON formatted response or reference to resource)

I know this is huge.
If you decide not to dump this immediately I would like to discuss this further.  
Surely, I can help with code.

**Comment by jasonlewis** [comment]
I don't think I'll dump the idea... it sounds nice, and could use some fleshing out and discussion for sure.

I'd imagine the DocBlock would look similar to an Apiary document or something along those lines. You'd want the request, body, etc, as well as all the response related things.

So... discuss away!

**Comment by bweston92** [comment]
+1 sounds great.

—

**Comment by tymondesigns** [comment]
:+1: Sounds useful

I suppose it would be an artisan command like `php artisan api:docs`

**Comment by Andreyco** [comment]
First of all, thanks for not dumping the idea :)

At the begining we should make an agreement on "where do we want do describe endpoints?".
Some users prefer to return response from `Route::get....`, others prefer to respond from Controller action assigned to route endpoint. Some other prefer configuration file (plain PHP, or YAML) instead.

Do we want to desctibe endpoints from YAML/PHP, from routes.php? Or both and combine them?

**Comment by michaelcurry** [comment]
Adding Documentation Generation would be the final step.  I would like using the doc blocks in controllers.  that way the routs file will not be HUGE! ...  Although a schema (YAML) does have home huge advantages.  (simplicity/easy of use and the ability to get as complex as needed)...

**Comment by Andreyco** [comment]
If docblocks, then I would allow them in controllers and route files as well. 
I know route file can get huge, but its up to programmer to make decision to move code from route file to controller to keep it clean.

Yes, yaml would allow even cleaner setup.

I dont mind either of them, I can go with docblocks/annotations and yaml (or other) as well.

**Comment by jasonlewis** [comment]
I'd be inclined to suggest that if you use docblocks then you use them throughout... Then, as an alternative to docblocks, you could write it up as a YAML document. I don't like the idea of mixing and matching YAML and docblocks. But having both options available would be nice.

**Comment by Andreyco** [comment]
I agree with you - user should use whatever he likes - but stick to one option only.
When generating docs he would be asked to specify source - either docblocks or YAML (or search for YAML spec and fallback to docblocks if not found)  
Command example
`artisan api:docs -s yaml` vs `artisan api:docs -s docblocks`

**YAML**: one file to rule them all.  

**Docblocks**: let users only write them in controllers. Since routes registration may be split into several route files it would be messy to process them all since they might be locate wherever possible.

**Comment by michaelcurry** [comment]
:+1:  If there were 2 options it would make everyone happy... well not every ones, but some people can't be pleased :-/

Is this something that is in a time frame ( next month or so ) are just an idea right now?

**Comment by Andreyco** [comment]
Yeah, you cannot please everyone.
We are discussing the idea. But I would like to have this implemented asap ;)

**Comment by jasonlewis** [comment]
I'm fine with having both options available but it would be a case of users using one and only one, like you've said @Andreyco.

We should flesh out a format though. I think it would be nice if the final generated docs are in an [API Blueprint](https://apiblueprint.org/). Thoughts?

**Comment by AOutStartups** [comment]
why you discuss it? is open source! go! write it!

**Comment by Andreyco** [comment]
@AOutStartups lol, are you serious?

@jasonlewis I agree with you. All we need is API Blueprint formatted output, nothing more.

**Comment by jasonlewis** [comment]
Well, we should get it fleshed out before anything is written. Saves a lot of headaches. That's for sure.

As for the format... For the docblocks, I'm not sure the best possible way. Annotations would probably be easier to parse as existing parsers would do a lot of the work. But it may be hard to format due to the docs needing to incorporate some form of response example and all that. Here's one way it may look.

```php
/**
 * Show all the users.
 *
 * GET /users (application/json)
 * Headers
 *     Accept: application/vnd.api.v1+json
 * Response 200 (application/json)
 *     {
 *         "data": [...]
 *     }
 *
 * @return \Dingo\Api\Http\ResponseBuilder
 */
public function index()
{
    //
}
```

Using annotations it might look like this...

```php
/**
 * Show all the users.
 *
 * @Get("/", request="application/json")
 * @Headers(accept="application/vnd.api.v1+json")
 * @Response(
 *     status="200",
 *     content-type="application/json",
 *     body="{
 *         "data": [...]
 *     }"
 * )
 *
 * @return \Dingo\Api\Http\ResponseBuilder
 */
public function index()
{
    //
}
```

I have no idea if that's a valid annotation format or not. Haven't really looked into the spec. I'd imagine the quotation marks would conflict with the body and the data.

**Comment by arnold-almeida** [comment]
Ive been using jsdoc atm.

Install

    npm install apidoc -g

Generate docs

    apidoc -i app/controllers/api/ -o docs/api/


Syntax is as below.

```php
  /**
     * @api {get} /api/users/xxx
     * @apiVersion 1.2.0
     * @apiName xxxx
     * @apiGroup User
     * @apiPermission scope1, scope2
     *
     * @apiDescription Lorem ipsum
     *
     * @apiParam {String} user_id
     *
     * @apiError Dingo\Api\Exceptions\ResourceException Lorem ipsum
     *
     * @apiChangelog 1.1.0 Added xxx
     * @apiChangelog 1.1.1 Use xxx if xxx
     * @apiChangelog 1.2.0 Added pagination support
     * @apiChangelog 1.2.1 Default to limit to {n} for now
     *
     * @todo  - Tests to ensure that user reviews are paginated
     */
    public function reviews()
    {
         ...
    }
```

**Comment by jasonlewis** [comment]
So I've been working on this a little bit and have some rough things working, nothing has been pushed yet. Just looking for feedback on the syntax. I'm using the `doctrine/annotations` library so I'm limited in some ways as to how it can look but for the most part I think it's pretty good.

It will only work with controllers. A controller is defined like so...

```php
/**
 * A resource representing user actions.
 *
 * @Resource("users")
 */
```

You can also give the resource a base URI.

```php
/**
 * A resource representing user actions
 *
 * @Resource("users", uri="/users")
 */
```

Now, each method in your controller can also contain some annotations that will provide further documentation on the actions performed.

```php
/**
 * Get all users
 *
 * Get all the users publicly available data. Optionally sort the returned users.
 *
 * @Get("{?sort}")
 * @Parameters({
 *     @Parameter("sort", default="created_at", description="Sort the returned users")
 * })
 * @Response(200, body={
 *     "users": {
 *        {"name": "bob", "email": "bob@bob.bob", "created_at": "2015-06-15"},
 *        {"name": "jack", "email": "jack@jack.jack", "created_at": "2015-06-17"}
 *     }
 * })
 */
public function index()
{
    return $this->users->all();
}
```

There's several other annotations you can use as well, such as `@Request` and `@Transactions`.

`@Transactions` is a special annotation that allows you to supply multiple `@Request` and `@Response` annotations for endpoints that may return different responses based on the request given.

As an example, the above generated class and method will look something like this when run with the command: `php artisan api:docs Example`

```
FORMAT: 1A

# Example

# Users [/users]
A resource representing user actions

## Get all users [GET /users/{?sort}]
Get all the users publicly available data. Optionally sort the returned users.

+ Parameters
    + sort (string, optional) - Sort the returned users
        + Default: created_at

+ Response 200 (application/json)
    + Body

            {
                "users": [
                    {
                        "name": "bob",
                        "email": "bob@bob.bob",
                        "created_at": "2015-06-15"
                    },
                    {
                        "name": "jack",
                        "email": "jack@jack.jack",
                        "created_at": "2015-06-17"
                    }
                ]
            }
```

Would love to hear some thoughts on how this is looking and any further ideas.

**Comment by lightvision** [comment]
It's quite nice and cleaner than swagger-php.
You should take into account the multiple versions of the api that mai exists, so at least @version should exits and match a defined version in the api.
That way we could have te api documentation in one place and browse by version.

**Comment by jasonlewis** [comment]
Yeah need to add in a version annotation. It'll accept an array of versions
and the command will take a version number to generate documentation for.

**Comment by jasonlewis** [comment]
Going to close this. If we need to discuss formatting or issues further feel free to start up a new issue, or post here, and we'll get it re-opened. I think for now it's fine.
