### ISSUE TITLE
RateLimiter without using ip-based limiting

### ISSUE THREAD

**Issue by rokde** [dingo/api#333]
Do you have any plans to provide another RateLimiter without limiting requests per IP instead of limiting by OAuth Client or user (used by authentication).

We need a client based rate limiting. I only see the possibility to re-assign 'api.limiter' in the IOC Container of laravel. Do you have any other trick? ;)

**Comment by stelgenhof** [comment]
:+1:

**Comment by jasonlewis** [comment]
I can certainly look into it. Perhaps allowing a user defined class the defines the limiter.

**Comment by rokde** [comment]
Yes, anything like that is fine.

**Comment by jasonlewis** [comment]
I've just pushed a change to master that should allow you to change the limiter key.

```php
App::make('api.limiter')->setRateLimiter(function ($container, $request) {
    return $container['example']->getRateLimiterKey();
});
```

Just make sure the resolver returns a string that can be used as part of the rate limiting key.

**Comment by Konafets** [comment]
Can you give an example where to put this and how to use it? I added the example from the [wiki](https://github.com/dingo/api/wiki/Rate-Limiting#changing-rate-limiting-key) to the AppServiceProvider but I got a `ReflectionException in Container.php line 738: Class cache does not exist`
exception back.

**Comment by tripper54** [comment]
@Konafets did you work this out? If so could you share?
