### ISSUE TITLE
Using domain instead of prefix?

### ISSUE THREAD

**Issue by canfiax** [dingo/api#334]
Instead of having http://domain.com/api/ as main endpoint, I wish to switch to http://api.domain.com.

I have edited the config, having "prefix" left empty, and domain set to "api", like so:

![image](https://cloud.githubusercontent.com/assets/3786627/5720905/030be2bc-9b2b-11e4-9d51-d6404752d487.png)

I have edited my hosts file like so:

![image](https://cloud.githubusercontent.com/assets/3786627/5720911/1ced53a0-9b2b-11e4-9fdb-6fc1dbdd46dc.png)

Now when I send a request to: http://api.domain.app/ i get a  `404 Not Found nginx/1.6.2` error.

What could be wrong?

**Comment by tymondesigns** [comment]
you shoiuld check your nginx config, as it looks like you haven't configured your subdomain to point to your app directory

**Comment by canfiax** [comment]
I am running a vagrant server (homestead), could you tell me where to look / what to do?

**Comment by tymondesigns** [comment]
with homestead you should be able to add another site block to `Homestead.yaml` as seen in the docs: http://laravel.com/docs/4.2/homestead

**Comment by jbrooksuk** [comment]
Don't you have to set `domain` to be `api.example.com` here?

**Comment by jasonlewis** [comment]
Yeah set `domain` to `api.example.com` in the API config file.
