### ISSUE TITLE
Class 'UserTransformer' not found

### ISSUE THREAD

**Issue by Michael-Brooks** [dingo/api#335]
I have been following the Wiki guide on getting started and I have hit a wall. On the responses section, it says that you can create the response builder by adding the ControllerTrait into your BaseController.

This is what my controller currently looks like...

    <?php

    use Illuminate\Routing\Controller;
    use Dingo\Api\Routing\ControllerTrait;

    class BaseController extends Controller {

	use ControllerTrait;

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

    }

I tried to remove the protected function just in case it was over riding anything, but I still got the same error message.

My UserController also extends my BaseController so it should be picking it up.

I am using the latest version (0.8.2) and have the providers and aliases all set up.

**Comment by tymondesigns** [comment]
What method are you attempting to call?

**Comment by Michael-Brooks** [comment]
Item and collection methods, both bring up the same error.

I have even tried copying and pasting straight from the wiki to see if this would work and got nothing.

**Comment by tymondesigns** [comment]
have you created a UserTransformer ?

**Comment by Michael-Brooks** [comment]
I haven't. I didn't know what you mean, but after checking the wiki, I see that there is a section on transformers.

Wouldn't it be wiser to learn how to set up a transformer before showing that code within the responses section?

You can call me stupid or silly or whatever, but surely having it as more of a step by step, it will be easier to see what is going on?

I probably should have checked the nav before opening an issue, but I'm sure there will be others like me at some point.

**Comment by tymondesigns** [comment]
I agree, the wiki could be more beginner friendly and/or possibly ordered in a more logical manner.

I think @jasonlewis mentioned that he would try to release some screencasts to accompany the wiki at some point.

**Comment by Michael-Brooks** [comment]
That will definitely help.

Thank you for commenting back and helping me out, I really appreciate it.

**Comment by markh1** [comment]
I'm stumped on this too.  There doesn't seem to be any example of how to create a UserTransformer class or any other Transformer class.  The Wiki doc on the Transformer topic is a bit scant.  I've been reading the Fractal package doc too, and am just overwhelmed at this point.  I appreciate any example someone may provide on how to create a Trasformer class for the User or any table record for use in Dingo.  TIA.

**Comment by jasonlewis** [comment]
That's because transformers aren't something that this package does, it merely supports them.

A very basic transformer class is as follows...

```php
class Transformer extends League\Fractal\TransformerAbstract
{
    public function transform(User $user)
    {
        return [
            'name' => $user->name
        ];
    }
}
```

**Comment by markh1** [comment]
Thanks lots for your reply Jason!  Like the author of this thread, I got stuck using some of the doc examples such as: 
   $users = User::paginate(25);
   return $this->response->paginator($users, new UserTransformer);

The 2nd param is not optional.  Is it possible to use the paginator or item methods without a Trasformer object? Or does it make sense to use these methods otherwise?  Thanks again. Every word in your doc and vimeo video is golden mate!
