### ISSUE TITLE
API Logging

### ISSUE THREAD

**Issue by stelgenhof** [dingo/api#339]
I would like to have the possibility to log all API requests. What is the best way to approach this? Meaning, where would I hook into this library? My application includes both a frontend and a REST API, so I would like only to log request to the API.

**Comment by kodeine** [comment]
Add a filter, i am using the filter below. 

```
Route::filter('api.logs', function ($route, $request) {
        $userId = (Sentry::check()) ? Sentry::getUser()->getId() : null;
        $action = 'API Query';
        $messages = (Session::get('messages')) ? Session::get('messages') : null;
        $description = (Session::get('description')) ? Session::get('description') : null;
        $payload = (Session::get('payload')) ? Session::get('payload') : null;
        Queue::push(
            '\Frapi\Repositories\ActionRepository@apiQuery',
            array(
                'action' => $action,
                'uri' => Request::path(),
                'method' => Request::method(),
                'description' => $description,
                'messages' => $messages,
                'payload' => $payload,
                'user_id' => $userId,
                'session' => Session::GetId()
            )
        );
    });
```

**Comment by stelgenhof** [comment]
Thanks @kodeine! I had already thought about using a filter, but was perhaps considering too complicated solutions :) How do you then separate API requests from other requests?

**Comment by stelgenhof** [comment]
I used the filter as suggested and works great!

**Comment by kodeine** [comment]
I'm glad it worked. Question, have you used any Filter query methods or search methods for your API?

**Comment by stelgenhof** [comment]
Sorry, what do you mean with Filter query methods or search methods?
