### ISSUE TITLE
Where to write transformers ?

### ISSUE THREAD

**Issue by ankur0101** [dingo/api#341]
While going though https://github.com/dingo/api/wiki/Responses#response-builder, it says about 

`return $this->response->item($user, new UserTransformer);`

But where exactly UserTransformer is stored ? I am getting error as Class 'UserTransformer' not found.

Also in which file we have to write [custom transformers] (https://github.com/dingo/api/wiki/Transformers#custom-transformation-layer) ?

Thanks

**Comment by bweston92** [comment]
You create a new class, for ease of use extend TransformerAbstract.

—

**Comment by dbonner1987** [comment]
@ankur0101 Create a new class anywhere in your application it makes logical sense to be. This could be in "app/Transformers/UserTransformer" or in the root of your application (same directory as "vendor" and "app" are located), "src/Foo/Transformers/UserTransformer". It is entirely dependant on the structure of your codebase.

With regards to the Transformer, an example of a UserTransformer would be:

```php
use League\Fractal\TransformerAbstract;

class UserTransformer extends TransformerAbstract
{

    /**
     * Turn this item object into a generic array
     *
     * @return array
     */
    public function transform(User $user)
    {
        return [
            'id'            => (int) $user->id,
            'name'          => $user->name,
            'phone'         => $user->phone,
            'email'         => $user->email,
            'group'         => $user->group,
            'website'       => $user->website,
        ];
    }

}
```

As @bweston92 mentioned, extend "TransformerAbstract" provided by Fractal (https://github.com/thephpleague/fractal).

**Comment by ankur0101** [comment]
That didnt work out. Still gives Class 'UserTransformer' not found.

I am using 
`return $this->response->item($user, new UserTransformer);`
in AuthController for testing.

**Comment by dbonner1987** [comment]
Where is your "UserTransformer" class located and is it within a namespace?

If it is within a namespace, you will need to add `use My\Namespace\UserTransformer` above your AuthController.

You will need to declare the class or namespace in your composer.json.

**Comment by bweston92** [comment]
In that "logical" namespace it may be best to version transformers too.


"My\App\Transformers\V1\EloquentUserTransformer"


—

**Comment by ankur0101** [comment]
Could you please explain more in details ?

**Comment by dbonner1987** [comment]
@ankur0101 where is your transformer located? 

Here are two examples of how to set up your Transformer.

### Classmap
Location: `app/transformers/UserTransformer`

Class:
```php
use League\Fractal\TransformerAbstract;

class UserTransformer extends TransformerAbstract
{

    /**
     * Turn this item object into a generic array
     *
     * @return array
     */
    public function transform(User $user)
    {
        return [
            'id'            => (int) $user->id,
            'name'          => $user->name,
            'phone'         => $user->phone,
            'email'         => $user->email,
            'group'         => $user->group,
            'website'       => $user->website,
        ];
    }

}
```
Then within the "classmap" array in your composer.json, add 'app/transformers':
```json
"autoload": {
    "classmap": [
        "app/commands",
        "app/database/migrations",
        "app/database/seeds",
        "app/transformers"
    ]
},
```
Your `AuthController` will then look similar to this (note the use of the `use` keyword).

```php
<?php 

use UserTransformer;

class AuthController extends Controller { //... }
```


### Namespace
Location (with @bweston92's versioning suggestion): `app/MyApp/Transformers/V1/UserTransformer`

Class:
```php
<?php namespace MyApp/Transformers/V1;

use League\Fractal\TransformerAbstract;

class UserTransformer extends TransformerAbstract
{

    /**
     * Turn this item object into a generic array
     *
     * @return array
     */
    public function transform(User $user)
    {
        return [
            'id'            => (int) $user->id,
            'name'          => $user->name,
            'phone'         => $user->phone,
            'email'         => $user->email,
            'group'         => $user->group,
            'website'       => $user->website,
        ];
    }

}
```
Then using "psr-4", in composer.json, add the namespace:
```json
"autoload": {
    "psr-4": {
        "MyApp\\": "app/MyApp"
    },
},
```
Your `AuthController` will then look similar to this (note the use of the `use` keyword).

```php
<?php 

use MyApp/Transformers/V1/UserTransformer;
use Illuminate\Routing\Controller;
use Dingo\Api\Routing\ControllerTrait;

class AuthController extends Controller 
{
    use ControllerTrait;
    //... 
}
```

After implementing either of these, run `composer dump-autoload`and the `php artisan dump-autoload`.

More info on namespacing can be found here:
* http://php.net/manual/en/language.namespaces.php
* http://www.sitepoint.com/php-53-namespaces-basics/

**Comment by jasonlewis** [comment]
Lots of helpful information here that should hopefully guide you on how to use transformers. As mentioned, make sure you refer to the Fractal documentation for more information on transformers.

**Comment by ankur0101** [comment]
@dbonner1987 Thanks. That helped.

**Comment by zjien** [comment]
THX,That help me out

**Comment by brickgale** [comment]
@dbonner1987 i think you forgot to put `use App\User` or to define the arguments passed on transform `User`. Thanks for this, really helped me.

**Comment by dbonner1987** [comment]
@brickgale you are correct. Thanks.

Comment has been updated.

**Comment by acfasj** [comment]
@dbonner1987 you are really patient and that helped me, thanks
