### ISSUE TITLE
where is a better place to register a custom handler?

### ISSUE THREAD

**Issue by ruanyl** [dingo/api#342]
I want to customize error info like this:

```php
API::error(function (Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException $exception) {
    return Response::make(['error' => 'Hey, what do you think you are doing!?'], 401);
});
```

But I dont know where to put it. Anyone has practical experiences?

**Comment by jasonlewis** [comment]
Anywhere you like really... `app/start/global.php` would be a good starting point, but you could place it in your own service provider as well. It's up to you.

**Comment by ruanyl** [comment]
thanks :) @jasonlewis
