### ISSUE TITLE
Screencast of setting up the API with Model, Controller, Transformer, Routes and Auth will be great 

### ISSUE THREAD

**Issue by saqueib** [dingo/api#343]
Hi, 

I have researched and found that this is the most suitable rest api package for Laravel, but if someone can produce a 5-10 min screencast of documentation will be great.

> A walkthrough of setting up Dingo API with Model, Controller, Transformer, Routes and Auth will be  awesome,  for Front-end you use something like Angular is which is very popular.

I have found only single video on [Dingo API: Basics on Vimeo](http://vimeo.com/93736144) which is pretty old. If someone knows any link of video tut please share 

Or create a **example** API using dingo.

as they said **A picture is worth a thousand words** so you can guess worth of a video

**Comment by jasonlewis** [comment]
Nothing that I know of. Hope to do a better video guide in the future. Cheers.
