### ISSUE TITLE
API internal request sets headers

### ISSUE THREAD

**Issue by slovenianGooner** [dingo/api#344]
Hi guys,

so the API internal request I make in my controller sets some headers to enable the request. But afterwards if I return a Redirect with the controller I get a Bad Gateway 502 error on nginx. Is there any way of resetting the headers after the API call is made?

Thanks for your answers.

**Comment by jasonlewis** [comment]
The headers are being set on the response you're creating as well?

**Comment by slovenianGooner** [comment]
Yeah, I'm just doing a basic return Redirect after making an internal API call.

**Comment by jasonlewis** [comment]
Roger, will investigate this now. Many thanks.

**Comment by jasonlewis** [comment]
Can you give me some example code? I can't seem to recreate this. It doesn't look as though the headers are also being set on the response that's being created.

**Comment by slovenianGooner** [comment]
```
    public function tryToRegister()
    {
        $input = Input::all();
        $successRedirect = Redirect::to(route('web.register.confirmRegistration').'?success=true');
        $errorRedirect = Redirect::to(route('web.home').'?error=true');
        $registrationEntry = API::with($input)->post('users');

        if ($registrationEntry['code'] == 200) {
            return $successRedirect;
        }

        return $errorRedirect;
    }
```

This is what I do right now to try to avoid the issue but it still remains.

This is what I had beforehand:

```
    public function tryToRegister()
    {
        $input = Input::all();
        $registrationEntry = API::with($input)->post('users');

        if ($registrationEntry['code'] == 200) {
            return Redirect::to(route('web.register.confirmRegistration').'?success=true');;
        }

        return Redirect::to(route('web.home').'?error=true');
    }
```

**Comment by jasonlewis** [comment]
I'm still not able to re-create this. What headers are being set exactly? And where are you setting them?

**Comment by slovenianGooner** [comment]
Well I'm not sure if it's a header issue but I'm guessing the internal API request creates some headers when making the request?

I just can't seem to find what the issue is, I've also tested it on 2 different servers and I always recieve a 502 Bad Gateway error on nginx.

If I do a redirect without making an internal API request it has no issues.

I read a bit about it and it seems like a buffer issue on PHP-FPM. Will investigate and let you know if it helps.

Thanks for your help.

**Comment by jasonlewis** [comment]
The internal request doesn't create any other headers other than the ones Symfony creates by default to perform a request. Aside from that, the headers shouldn't (the can't, I don't think) be set on the response you're creating. I tried creating an internal request with some bogus headers to confirm and the response does not include these headers.

I've tested this myself on Ngnix and still can't get it to 502 on me.

If you hit the API route directly does it work fine? Is it only with internal requests?

**Comment by slovenianGooner** [comment]
I've just consulted with one of my friends and confirms it's a buffer issue on nginx. Was automatically thinking it's a header issue, because it worked if I didn't make an internal request.

You can consider this "resolved"? :+1:

**Comment by LuisMejiaF** [comment]
Hi @slovenianGooner , can you tell me how did you solve it?

Here is my current configuration in .../nginx/sites-available/mysite.com

`client_body_buffer_size 64K;`
`client_header_buffer_size 4k;`
`client_max_body_size 20m;`
`large_client_header_buffers 2 1k;`

I think I'm already exaggerating with the values, but the 502 response is still there. 

I have a clean copy of Laravel, I just installed Dingo/Api, and Tymon/JWT, and this error just happens in the pages that I have set to use their middleware: 


	$api->version('v1', function ($api) {
		$api->get('/this_works', 'App\Http\Controllers\HomeController@show');

		$api->group(['middleware' => 'api.auth'], function ($api) {
			$api->get('/this_does_not_work', 'App\Http\Controllers\HomeController@show');
		});
	});
