### ISSUE TITLE
$this->response->collection throwing substr() expects parameter 1 to be string error

### ISSUE THREAD

**Issue by marlongichie** [dingo/api#346]
Whenever I use `$this->response->array` to return results, everything works as expected and I get a nice array of the results.

However, attempts to use the transformer via - `$this->response->collection($myCollection, new MyTransformer)`, I get `substr() expects parameter 1 to be string, object given`

A dump of the collection `dd($myCollection)` shows `$myCollection` is of type `object(Illuminate\Database\Eloquent\Collection)`, and everything seems to work all the way up to the Transformer outputting the data.

Has anyone else encountered this? Any suggestions?

**Comment by jasonlewis** [comment]
Can you paste all the error? What line? What file?

**Comment by jasonlewis** [comment]
@marlongichie, perhaps you didn't get an e-mail notification on my last message. Are you able to provide the full stack trace with the line and file that this is happening. Cheers mate.

**Comment by marlongichie** [comment]
Hello @jasonlewis ,

Thanks for following up. 

That bit was the entire stack trace which laravel outputted.

```
$this->response->collection($myCollection, new MyTransformer), I get substr() expects parameter 1 to be string, object given
```

It's seems a bit tricky to debug with laravel sometimes as it doesn't actually give fully detailed errors or traces all the time.
