### ISSUE TITLE
Type hinting is required for the first param of the method ResponseFactory::collection!

### ISSUE THREAD

**Issue by ivorobioff** [dingo/api#348]
```php
public function collection($collection, $transformer, array $parameters = [], Closure $after = null)
    {
        $class = get_class($collection->first());

        $binding = $this->transformer->register($class, $transformer, $parameters, $after);

        return new ResponseBuilder($collection, $binding);
    }
```

When calling this method from the controller it's not obvious what type of the object the method accepts as a collection. It will be very helpful to specify the "Illuminate\Database\Eloquent $collection" so that developers know what to put there in case when data retrieved from "Eloquent" not going directly there.

**Comment by bweston92** [comment]
Actually anything that is iterateable is a collection. A standard array, Illuminate\Support\Collection and its children (database collection), why limit it to just one type?

—

**Comment by ivorobioff** [comment]
Well, it's not all about the iteration over there. If you look at the first line of the method implementation you will notice that the method "first"  of the collection is called. Not all iterators in PHP or in general have this method. I would put something like this at the beginning of the method: 

```php
if (is_array($collection)){
	$first = reset($collection);
} elseif ($collection instanceof Collection){
	$first = $collection->first();
} elseif ($collection instanceof Traversable){
	$first = $collection->current();
} else {
	throw new \RuntimeException('Collection must be traversable object or array');
}
```

However, I assume that further code does not rely on actual "Collection" object

**Comment by jasonlewis** [comment]
I'd imagine most people are simply handing of an Eloquent collection to this method, so I'd be happy to type hint it as `Illuminate\Support\Collection. Seeing as the method itself utilizes methods on that class it's probably a smart idea.

**Comment by jasonlewis** [comment]
Have type-hinted in latest commit.
