### ISSUE TITLE
"ResponseFactory::collection" returns an empty array without the resource key if an empty collection is provided.

### ISSUE THREAD

**Issue by ivorobioff** [dingo/api#349]
I think it's not really logical to return an empty array in case if an empty collection is provided to "ResponseFactory::collection". I think the right way would be to return ["data" => []] assuming that no meta data is provided and the default resource key is used.

**Comment by jasonlewis** [comment]
It already does this. Was fixed in a02e506faec7eb7043b7d606ee94e0c9847a4f17 and is available since 0.8.2.
