### ISSUE TITLE
Cannot use Redirect::back() method

### ISSUE THREAD

**Issue by Ortix92** [dingo/api#350]
I found out that whenever I use the `Redirect::back()` method I get the following exception:

```
BadMethodCallException
Method [getFormatter] does not exist on Redirect. 
```
I'm using `use ControllerTrait`
How can I solve this?

**Comment by Ortix92** [comment]
After some tinkering I have come to the conclusion I cannot use the `Response` and `Redirect` class when using `ControllerTrait`

**Comment by jasonlewis** [comment]
Hm, what are you redirecting exactly?

**Comment by Ortix92** [comment]
Well even if I try to simply do `Redirect::back()` at the end of my method. it just throws that exception. I don't pass any data with it. I hope I understood your question.

**Comment by jasonlewis** [comment]
Is this in the API route?

**Comment by Ortix92** [comment]
It's in the API route yes. Here's code to reproduce the error
http://laravel.io/bin/mGYWq

**Comment by jasonlewis** [comment]
Just return `Auth::user()`. You shouldn't need to use `Response::json` at all.

**Comment by Ortix92** [comment]
Yes I figured that out, I'm just saying that those classes don't seem to work anymore when using the `ControllerTrait`

**Comment by jasonlewis** [comment]
I'll take a look. Cheers.

**Comment by jasonlewis** [comment]
I can use the `Response` class as per usual.

```php
return Response::make('foo');
```

Works fine. Redirects are another thing. I'm not so sure an API endpoint should be redirecting... I'd love to get clarification on this as to whether or not it's a done thing.

**Comment by Ortix92** [comment]
Sorry for the late reply, I didn't get a notification from Github. Either way, an API endpoint should indeed not redirect. It was for me just a temporary solution to use the API as an actual API and also as a regular controller to redirect upon form submission. I now separated the logic into separate controllers. But I thought I would just let you know that in the case the `ControllerTrait` is used, the Redirect doesn't work. Not sure if this kind of behavior should be wanted.

Primarily because as a trait you should be extending functionality and not breaking it IMO.

**Comment by jasonlewis** [comment]
Noted. I'll investigate as to why this is occurring. Cheers.

**Comment by Quagh** [comment]
Having the same issue. What's the situation?

**Comment by Braunson** [comment]
+1 Having the same issue as well.

**Comment by bweston92** [comment]
Can you explain why an API is redirecting anyway?



—

**Comment by Quagh** [comment]
@bweston92 For linking an external OAuth account (Google, MSLive), we need to know the API user by its API OAuth credentials, then redirect to the appropriate service, redirect back and link the external account to the current user. That involves multiple redirects, and those routes have to be in a Dingo/api API group.

**Comment by Ortix92** [comment]
>Independent of what we want, a package shouldn't break standard Laravel code and workflows imo.

**Comment by bweston92** [comment]
@Ortix92 It doesn't, it only happens in an `api` router group. Which actually is extra functionality that is available by the package to create specific to api end-points. If you don't use the `api` router group it works there-fore not breaking "standard" Laravel code.

**Comment by Quagh** [comment]
Yeah, but there's hardly a way to get the API user when using a regular route. So if the combination occurs, using a redirect does not work.
