### ISSUE TITLE
Issue using Jsonp format

### ISSUE THREAD

**Issue by jrmadsen67** [dingo/api#351]
Hi,

This might be a mixing from latest upgrade - for using the JsonP formatter, the docs say:

'json' => 'Dingo\Api\Http\ResponseFormat\JsonpResponseFormat'

but that sends a string which getContentType() chokes on. More correct would seem to be:

'json' => new Dingo\Api\Http\ResponseFormat\JsonpResponseFormat

but I am finding that in hasValidCallback(), $this->request is null & so the rest chokes. Debugging some more and will let you know if I find anything else.

**Comment by jasonlewis** [comment]
Sorry what do you mean when you say that `getContentType` is choking on the string?

You should be able to use that string in the config file to change or register the JSONP formatter. 

There was an issue where exception responses were not getting the request instance set on them properly but that has since been fixed. It is yet to make it to a tagged release though.

**Comment by jrmadsen67** [comment]
sorry, that wasn't very precise.

When I use it as a string, like: 
'json' => 'Dingo\Api\Http\ResponseFormat\JsonpResponseFormat'

I get the error:

Call to a member function getContentType() on a non-object

because Response->morph() is calling $formatter->getContentType() around line 64; it is assuming $formatter is an object, but it is coming in as the string above. 

It made sense to me that it should be passed as an object like the existing json default, so trying:

'json' => new Dingo\Api\Http\ResponseFormat\JsonpResponseFormat

is throwing "Trying to get property of non-object" on JsonpResponseFormat in:

 protected function hasValidCallback()
{
return $this->request->query->has($this->callbackName);
}

for some reason $this->request is null. I haven't been able to track anything yet beyond that.

Hope that's a little more helpful

**Comment by jasonlewis** [comment]
I can't recreate this issue. Using the string, as mentioned in the docs, works fine for me on 0.8.2. The service provider should instantiate the object automatically when it detects it as a string so you can pass it in however you like. A string should be fine though.

Are you running the latest version (0.8.2)?

**Comment by jrmadsen67** [comment]
Hey Jason,

Yep, on 0.8.2. I'll spend a little time this afternoon, see what else I can figure out about it

**Comment by linpar** [comment]
Hi @jasonlewis, 
Any update on this? Facing similar problem.

`'json' => 'Dingo\Api\Http\ResponseFormat\JsonpResponseFormat'`
works fine (falls back to json when callback is missing) when I am using 
`return $this->response->array($response);` 
but getting error (with and without callback) when using collection or item 
`return $this->response->collection($object, new ObjectTransformer, ['key' => 'object']);` 

Error -
`{"error":true,"code":0,"message":"Trying to get property of non-object","file":"\/vendor\/dingo\/api\/src\/Http\/ResponseFormat\/JsonpResponseFormat.php","line":33}`

Using 0.8.2 version.

**Comment by jrmadsen67** [comment]
@linpar - thanks for that fine - may help unravel it. I found a different project where ti worked fine, but wasn't spotting what I was doing differently. I'll be working on this project again next few days & will let you all know if I sort it out

**Comment by jrmadsen67** [comment]
ok, so first of all: Jason, don't worry about trying to sort this one. I've got so much dependency hell & older version of libs at the moment, sure there's does something in there you'd never dupe.

FIX:

If you do happen to run into the issue Limpar and I were having, solution is this:

1) create your own custom formatter, an exact copy of JsonpResponseFormat

2) $this->request is null for some reason I never determined. Do the dirty and make this change in your copy:

    protected function hasValidCallback()
    {
        return \Input::has($this->callbackName);
        //return $this->request->query->has($this->callbackName);
    }
    protected function getCallback()
    {
        return \Input::get($this->callbackName);
        //return $this->request->query->get($this->callbackName);
    }

3) in your config, set up:

'json' => new <myNamespace>\ResponseFormat\JsonpResponseFormat

Notice we are using the object, not a string.

4) Check by adding ?callback=test to your url

Crude hack based on I never really figured out what was wrong, but is already ok in later versions it seems. So, Screw it :-)
