### ISSUE TITLE
API routes not getting registered.

### ISSUE THREAD

**Issue by alwaysanirudh** [dingo/api#358]
I have just updated API. It is currently at version 0.8-dev.

But some how the routes are not getting registered now. They were working fine before the update.

If I run ```php artisan api:routes ``` I get all the registered API endpoints. But if I tried to hit the APIs it does not recognize the routes. Also the output of  ```php artisan routes``` does not have the API endpoints I have created.

for Reference I have created the Endpoints as follows:

```
Route::api(['version' => 'v1', 'domain' => Config::get('app.api-domain'), 'namespace' => 'API'], function()
{
   Route::get('products/{ids}', function($ids)
    {
        return Products::with('image', 'prices.currency', 'attributeVals.attribute')->whereIn('id', $ids)->get();
    })->where('ids', '[\d,]+');
    .
    .
    .
    .
}
```

**Comment by jasonlewis** [comment]
If they're showing up in `php artisan api:routes` then they're being registered... They won't show up in the regular routes command as they're not registered alongside Laravel routes.

Were you running `0.8.2` previously or an earlier version?

**Comment by alwaysanirudh** [comment]
Yes I'm facing this issue with version ```0.8.2```. The update message was as follows: 
```
- Removing dingo/api (dev-master 97fcff5)
- Installing dingo/api (dev-master fea28bf)
```

If I rollback the update it works fine.

I went on to investigate the issue further.  I have API endpoints at domains ``` api.xyz.com``` and ```xyz.com``` both in same project. The endpoints on ```xyz.com``` works fine but does not work on ```api.xyz.com```. I get an error as follows:

```
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
```

**Comment by koray-mobven** [comment]
Same error for me. I made a fresh install with Laravel 4 but doesn't work api routes.

**Comment by jasonlewis** [comment]
@alwaysanirudh, are you using the same version but different domains?

**Comment by alwaysanirudh** [comment]
Yes @jasonlewis. The version of API is the same on both the domains. Is that an issue? I think same version and two different domains should work and it did work for me. Its just the update that has an issue.

**Comment by jasonlewis** [comment]
Hm, I'll have a look at previous versions. I know I have made several changes to the way routes are registered. But at the moment I can say that this is the culprit.

**Comment by jasonlewis** [comment]
Can you try updating to the latest `dev-master` now, or `0.8.*@dev`? I've been doing some testing and it seems to be working now.

**Comment by alwaysanirudh** [comment]
The latest ``dev-master`` is working as expected but ``0.8.*@dev`` still has the bug.
