### ISSUE TITLE
Protected group inside a version group.

### ISSUE THREAD

**Issue by bweston92** [dingo/api#360]
I thought the following code used to work but maybe not.

```
Route::group(['version' => 'v1'], function ()
{
    // Declare some public routes here.

    Route::group(['protected' => true], function ()
    {
        // Declare some protected routes here.
    });
});
```

**Comment by jasonlewis** [comment]
Outside group must be `Route::api` not `Route::group`.

**Comment by bweston92** [comment]
Still doesn't work nested unless I put `version` again.

**Comment by jasonlewis** [comment]
Hm, I'll take a look. It should work fine.

**Comment by jasonlewis** [comment]
Seems to be working perfectly fine here.

**Comment by bweston92** [comment]
Error `Unable to register API route group without a version.`

```
Route::api(['version' => 'v1'], function ()
{
    // Declare some public routes here.

    Route::api(['protected' => true], function ()
    {
        // Declare some protected routes here.
    });
});
```

**Comment by bweston92** [comment]
Ahh I see what you said, `OUTSIDE` yes will try that.

**Comment by bweston92** [comment]
Thanks, worked.

**Comment by jasonlewis** [comment]
Yeah yeah. Outside must be `Route::api`, then inside can be `Route::group`. :smile:

**Comment by bweston92** [comment]
Thanks.
