### ISSUE TITLE
API routes fail with Debugbar enabled

### ISSUE THREAD

**Issue by EspadaV8** [dingo/api#363]
I've just installed barryvdh/laravel-debugbar and attempting to load a page with an API named route now fails with a 'Route not defined' error.

I'm filing the bug here and with the debugbar (https://github.com/barryvdh/laravel-debugbar/issues/290) since I'm not sure which project is doing something funky.

**Comment by jasonlewis** [comment]
Sample code? Works fine here mate.

**Comment by devmark** [comment]
maybe try to load api first.
~~~~
		'Dingo\Api\Provider\ApiServiceProvider',
		'Barryvdh\Debugbar\ServiceProvider',
~~~~

**Comment by EspadaV8** [comment]
I've created a minimal test case laravel install that shows the issue

https://github.com/EspadaV8/dingo-debugbar/tree/develop

**Comment by jasonlewis** [comment]
All good I'll give this a run when I can. Cheers.

**Comment by jasonlewis** [comment]
I'm no longer supporting Laravel 4.x. Try this in either Lumen or Laravel 5 and report back if there's still issues. Cheers mate.
