### ISSUE TITLE
Route model binding and API authentication.

### ISSUE THREAD

**Issue by Andreyco** [dingo/api#366]
When binding User model to route, authenticated user is not resolved yet. Which makes problems when you try to do following:

```php
Route::bind('user', function($value, $route)
{
	if ($value === 'me') {
		return API::auth()->getUser();
	}

	// ... other logic
});
```

Is it even possible to resolve authenticated user before Route-Model binding?

Will dig into code, reporting now as I have to go out.

**Comment by jasonlewis** [comment]
Hm, I'm not really sure with that one. Authentication is done on a before filter, so that's probably after the binding is done.

**Comment by Andreyco** [comment]
Yes, you are right.
Never mind, there is easy fix for this. I created separate route which catches `me` value and resolves User resource.

```php
// routes.php
Route::get('me/posts', 'UsersController@listMyPosts');
Route::get('{user}/posts', 'UsersController@listUsersPosts');

// UsersController.php
public function listMyPosts()
{
	$user = $this->auth->getUser();
	$resource = \Resources\User->findOrFail($user->id);
	
	return $this->listUsersPosts($resource);
}

public function listUsersPosts(\Resources\User $resource)
{
	// ...
}
