### ISSUE TITLE
Config setting "conditional_request" not compatible with Fractal transformers

### ISSUE THREAD

**Issue by davgothic** [dingo/api#375]
I'm using version 0.8.2 and if I set the `conditional_request` setting to true then the md5 hash for the ETag header seems to be generated from the model response and not from that of the [Fractal](https://github.com/thephpleague/fractal) transformer.

	public function transform(Venue $venue)
		{
			return [
				'id'               => (int) $venue->id,
				'name'             => $venue->name,
				'average_rating'   => $venue->averageRating(), // <-- this value may change
				...

From my example Fractal transformer method above the `average_rating` value can change but it doesn't exist in the request at the point in time that the ETag is generated so if nothing in the actual model has changed then the ETag stays the same causing the client to use a stale cached response.

I'm assuming the ETag generation needs to be set back to after the transformer has done its job or vice versa.

**Comment by jasonlewis** [comment]
Thanks for the report.

**Comment by xiphiaz** [comment]
+1, it appears that when using a Transformer, the `Router::getContent()` call returns null, when the actual content is present in `$response->original`. The result of this is that the Etag is the md5 hash of `null` (`"d41d8cd98f00b204e9800998ecf8427e"`)

**Comment by xiphiaz** [comment]
Update on my above comment, I was able to fix this by changing the object type I was returning from a `\StdClass` to a `\ArrayObject`. This caused the `$response->content` attribute to be filled, as `\ArrayObject` is `Jsonable` and `\StdClass` is not.

**Comment by jasonlewis** [comment]
This should be fixed for the L5 and Lumen version.
