### ISSUE TITLE
"conditional_request" config cannot be set on a route group

### ISSUE THREAD

**Issue by xiphiaz** [dingo/api#379]
In the config it says that 

```
/*
    |--------------------------------------------------------------------------
    | Conditional Requests
    |--------------------------------------------------------------------------
    |
    | Globally enable conditional requests so that an ETag header is added to
    | any successful response. Subsequent requests will perform a check and
    | will return a 304 Not Modified. This can also be enabled or disabled
    | on certain groups or routes.
    |
    */

    'conditional_request' => true,
```

However it does not seem possible to set the `conditional_request` key on a route group. (I have a need to have conditional routing as default, but disabled on some specific groups or routes).

Suggest applying `protected function setupGroupOptions()` to groups, not just `Route::api` calls.

**Comment by jasonlewis** [comment]
Noted. I'll see if I can work that in now.

**Comment by jasonlewis** [comment]
This has been fixed in the latest changes for Laravel 5 and Lumen. Sorry it took so long.
