### ISSUE TITLE
All requests are returning 404.

### ISSUE THREAD

**Issue by geofflancaster** [dingo/api#381]
Why would all requests return a 404 response?

**Comment by bweston92** [comment]
Show us your routes file.

**Comment by geofflancaster** [comment]
```
Route::group([
  'before' => 'useragent',
  'after' => 'session.cookie.remove'
], function() {
  Route::api([
    'version' => ['v1'],
    'namespace' => 'Api\V1'
  ], function() {
    Route::group([ 'before' => 'oauth' ], function () {
      Route::resource('assessments', 'AssessmentsController', [ 'only' => [ 'show' ] ]);
    });
  });

  Route::api([
    'version' => ['v2'],
    'namespace' => 'Api\V2'
  ], function() {
    Route::group([ 'before' => 'oauth' ], function () {
      Route::resource('assessments', 'AssessmentsController', [ 'only' => [ 'show' ] ]);
    });
  });
});
```

**Comment by geofflancaster** [comment]
It looks like when it gets to the Illuminate Router and calls "dispatchToRoute" it has a valid route. However, When it calls $route->run($request), it returns an exception which in turn results in a 404.

**Comment by bweston92** [comment]
Is that not your controller returning a 404?



—

**Comment by geofflancaster** [comment]
It does look like it's instantiating my controller but for some reason it's
not getting to the action.

**Comment by geofflancaster** [comment]
I have also removed the domain from the config and added it to the parent group. Since I am using a subdomain, I was unsure if that was causing the issue with it being in the config versus the route file.

```
Route::group([
  'before' => 'useragent',
  'after' => 'session.cookie.remove',
  'domain' => '{apisubdomain}.bsxinsight.com'
], function() {
  Route::api([
    'version' => ['v1'],
    'namespace' => 'Api\V1'
  ], function() {
    Route::group([ 'before' => 'oauth' ], function () {
      Route::resource('assessments', 'AssessmentsController', [ 'only' => [ 'show' ] ]);
    });
  });

  Route::api([
    'version' => ['v2'],
    'namespace' => 'Api\V2'
  ], function() {
    Route::group([ 'before' => 'oauth' ], function () {
      Route::resource('assessments', 'AssessmentsController', [ 'only' => [ 'show' ] ]);
    });
  });
});
```

**Comment by bweston92** [comment]
Add a `dd` as the first thing inside the show method see if it gets called.

**Comment by bweston92** [comment]
Also try without any filters.

**Comment by geofflancaster** [comment]
I have added the dd, it does not get called. Removing the filters does not change anything.

**Comment by bweston92** [comment]
You have sent the headers for the version to use?

**Comment by geofflancaster** [comment]
Accept: application/vnd.{vendor}.v2+json

**Comment by geofflancaster** [comment]
Any other thoughts on this?

**Comment by geofflancaster** [comment]
After continuing to dig through this, the request is able to find the correct route via Illuminate\...\Router::dispatchToRoute().

However, when it tries to fire the event 'router.matched' a 404 is immediately returned and the route is not run.

**Comment by geofflancaster** [comment]
Commenting out the ControllerReviser listening to that event gets me a step further. Still getting the 404 though.

**Comment by bweston92** [comment]
Can you dump your code anywhere? Or arrange a join.me for me to assist you?



—

**Comment by geofflancaster** [comment]
This issue was resolved by adding the Dingo ControllerTrait to my classes. The docs are not clear that this step is required. They make it seem like using the response builder is optional.

**Comment by geofflancaster** [comment]
I'm going to update the wiki and submit a pull request ASAP.

**Comment by bweston92** [comment]
@jasonlewis I believe the controller trait provides `getProperties` method which means that all API classes must use the ControllerTrait. The API Documentation makes this sound optional but in fact breaks if not used.

**Comment by natsu90** [comment]
Hey guys, I have the same error. I'm new to Lumen. Kindly take a look on my files and let me now what I'm missing. Thanks.
```
# app/Api/BaseApiController.php
<?php namespace App\Api;

use Dingo\Api\Routing\ControllerTrait;
use Laravel\Lumen\Routing\Controller as BaseController;

class BaseApiController extends BaseController {
    use ControllerTrait;

    protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}
}
```
```
# app/Api/AuthController.php
<?php namespace App\Api;

class AuthController extends BaseApiController 
{
    public function index()
    {
    	return ['foo' => 'bar'];
    }
}

```
```
# app/Http/routes.php
<?php

$app->get('/', function() use ($app) {
    return $app->welcome();
});

$api = $app['Dingo\Api\Routing\Router'];

$api->version('v1', function ($api) {

    $api->get('auth', 'App\Api\AuthController@index');
});
```
