### ISSUE TITLE
Cannot use Response class anymore

### ISSUE THREAD

**Issue by Ortix92** [dingo/api#385]
I'm not quite sure how Dingo is hooking into Laravel, but if the controller is called from within the API route group and when NOT even using the `ControllerTrait`, the `Response` class doesn't work anymore.

Error:
```
Call to undefined method Illuminate\Http\JsonResponse::getFormatter()
```
Stack Trace:
```
1. Symfony\Component\Debug\Exception\FatalErrorException
…/­vendor/­dingo/­api/­src/­Routing/­Router.php236
0. Illuminate\Exception\Handler handleShutdown
<#unknown>0
```

**Comment by bweston92** [comment]
Have you altered your dingo configuration? The format class for JSON is `Dingo\Api\Http\ResponseFormat\JsonResponseFormat`

**Comment by Ortix92** [comment]
Nope it's still set that way in the config

**Comment by jasonlewis** [comment]
Relating code please?

Sounds like a before filter or something might be returning a `JsonResponse`. A `JsonResponse` isn't currently supported as Dingo will handle the formatting of responses so you should always be returning a regular `Illuminate\Http\Response` instance.

**Comment by Ortix92** [comment]
Well something as simple as this does the trick:

```
Route::api('v1', function () {
    Route::get('test',function() {
        return Response::json(['test'],200);
    });
});
```

**Comment by jameswagoner** [comment]
Returning an array will format the response into whatever format you have setup. Eloquent models get converted just as if you use `Response::json()`
