### ISSUE TITLE
v0.8.3 upgrade issue

### ISSUE THREAD

**Issue by zeelorenc** [dingo/api#388]
Hi there

I was upgrading from v0.8.2 and noticed that this error came up:

    Argument 1 passed to Dingo\Api\Routing\ControllerReviser::revise() must be an instance of Dingo\Api\Routing\Route, instance of Illuminate\Routing\Route given, called in F:\xampp\htdocs\vendor\dingo\api\src\Event\RevisingHandler.php on line 51 and defined

In my controller:

    <?php namespace API;

    use \Illuminate\Routing\Controller;
    use \Dingo\Api\Routing\ControllerTrait;

    class LikeController extends \Controller {

        use ControllerTrait;

        public function like($id)
        {
            ...
        }
    }

I made it pretty much just as the docs say, but get the error. How can it be fixed?

**Comment by jasonlewis** [comment]
Can I see your routes file please?

**Comment by zeelorenc** [comment]
Route::api(['version' => 'v1', 'prefix' => 'api'], function()
    {	
	
        // Likes
        Route::get('like/{id}', array('as' => 'api.like', 'uses' => 'API\LikeController@like', 'before' => 'auth'));
    }

There you go

**Comment by tomvo** [comment]
I noticed this error as well after an upgrade, must be something that got left behind. Any clue on where to look?

**Comment by randomdrake** [comment]
Not upgrading, simply trying to use for the first time. Get the same error.

> Argument 1 passed to Dingo\Api\Routing\ControllerReviser::revise() must be an instance of Dingo\Api\Routing\Route, instance of Illuminate\Routing\Route given, called in /Users/randomdrake/Sites/smokereports/smokereports/laravel/vendor/dingo/api/src/Event/RevisingHandler.php on line 51 and defined

Downgraded from 0.8.* to 0.8.2 and it works just fine.

**Comment by Quagh** [comment]
Just upgraded from 0.8.2, same issue.

**Comment by LeeMcNeil** [comment]
+1 same issue after upgrading from 0.8.2 to 0.8.3

**Comment by gerardnll** [comment]
I get this error when i've got a route in the api endpoint with the same name as in the web endpoint. 
```
Route::api(['version' => 'v1'], function () {
    Route::get('/update', '\App\Controllers\Api\TestController@test');
});
...
Route::get('/update', array('as' => 'update-yourself', 'uses' => 'HomeController@getUpdateYourself'));
```
Breaks on version 0.8.3. works on 0.8.2

**Comment by jasonlewis** [comment]
Sorry guys but I'm no longer supporting Laravel 4.x going forward. Have to focus my attention on L5 and Lumen.
