### ISSUE TITLE
How do I fire a internal delete request?

### ISSUE THREAD

**Issue by Ortix92** [dingo/api#389]
I get `MethodNotAllowedException` if I do this:

```php
API::delete('api/screenshots/', $data);
```

but it works when I do this:

```php
API::delete('api/screenshots/1', $data);
```

Do I have to pass in the id in there instead of the `1`?

**Comment by bweston92** [comment]
This is because your routes setup doesn't have a handler for the following in the Api route group:




Route::delete('screenshots', 'handler');



—
