### ISSUE TITLE
How do I globally change the error response format?

### ISSUE THREAD

**Issue by cameron-fgx** [dingo/api#390]
Currently all error responses are returned as: 

```
{
    "message": "Message",
    "status_code": code
}
```

How can I configure this to be wrapped in an error tag, i.e.

````
{
    "error" : {
        "message": "Could not create new user.",
        "status_code": 422
    }
}
````

without having to create a Custom Exception Responses for each possible exception?

**Comment by cameron-fgx** [comment]
Any news on this?

**Comment by jasonlewis** [comment]
You can't at the moment. I'll work on something for the L5/Lumen version.

**Comment by vinkla** [comment]
It would be great if it were possible to override the default exception handler #411!

**Comment by jasonlewis** [comment]
Use app('api.exception')->setDefaultFormat. Look at the config as well.
