### ISSUE TITLE
lumen

### ISSUE THREAD

**Issue by devmark** [dingo/api#391]
I look forward to hearing about lumen with dingo/api   :)

**Comment by tristanpemble** [comment]
Background: [Lumen](http://lumen.laravel.com/) is a micro framework (think Silex, Slim) that was just announced by the Laravel team that is based off of the Illuminate libraries that Laravel is built on. Of note is that it provides a fairly trivial upgrade path from Lumen to Laravel, giving development teams flexibility as their application grows.

I am also interested to know if or how dingo/api will approach Lumen.

**Comment by kevindierkx** [comment]
Lumen doesn't support packages, would be kinda hard to make dingo compatible without rewriting allot of bootstrapping.

**Comment by GrahamCampbell** [comment]
Lumen does support packages. There's nothing special about a "package". Any repo on composer can be used in lumen just as in laravel. We just don't ship with all the publishing commands, but you can absolutely still get existing laravel packages to work. The services providers in luman are identical - they use the same illuminate component...

**Comment by kevindierkx** [comment]
Well in that case I must have misunderstood the limitations part on this page: http://lumen.laravel.com/docs/introduction#when-should-i-use-lumen

**Comment by GrahamCampbell** [comment]
@kevindierkx Right, what that's meaning is that if you want to use packages, you should probably choose laravel over lumen, but packages are still technically possible in lumen. Laravel is just the easier ride there. Lumen is fast because it's minimal. If you want packages, it's likely minimal is not for you. Just use laravel.

**Comment by bweston92** [comment]
I must say though implementing Lumen with Fractal transformers ect would be nice.



—

**Comment by foxted** [comment]
Why not just pull [Fractal](https://github.com/thephpleague/fractal) with composer and build your own transformers? 
And why not pulling [OAuth2 Server](https://github.com/thephpleague/oauth2-server) and build your own authentication? 

I agree with @GrahamCampbell if you want to use packages, just use Laravel.

**Comment by tristanpemble** [comment]
I'm in favor of pulling some of the features that exist within this library out into separate dependencies and letting this act as the all-in-one Laravel focused package, while letting Lumen users pull in whichever pieces they wish

**Comment by AndyWendt** [comment]
I think people just like to try to use whatever is new and see how it works.  I'm guilty often :smile:

**Comment by bweston92** [comment]
@foxted I like the response builder too. Also anything on composer is really a "package" in some form or another, isn't like if you use Lumen you're just going to keep your composer dependencies empty (apart from default of-course).

**Comment by jasonlewis** [comment]
Please see #213 for updates.
