### ISSUE TITLE
duplicate named routes with different version

### ISSUE THREAD

**Issue by geofflancaster** [dingo/api#392]
Is it possible to have multiple routes with the same name/url that are routed appropriately based on the version specified?

It looks like the last route that is defined is used regardless of version.

**Comment by jasonlewis** [comment]
Not possible currently. Will look into something for L5/Lumen release.

**Comment by geofflancaster** [comment]
Can you elaborate on how we should be using routes and versions in the current version? What good is a versioning system if you cannot share URLs between versions?

**Comment by jasonlewis** [comment]
You can share URLs between versions in the current setup. You just can't
share names because of how the router does the names. Hopefully with the
way I'm setting it up I'll be able to get around that.
