### ISSUE TITLE
jsonp_callback

### ISSUE THREAD

**Issue by Naranbat1123** [dingo/api#394]
http://example.com/api/ss?callback=JSON_CALLBACK

i need jsonp_callback some example some one help

**Comment by Naranbat1123** [comment]
Route::get("/test", function(){
    $test = [];
    for($i=0; $i<100; $i++){
        $test[$i] = new \stdClass();
        $test$i]->nane = "Hi".$i;
    }
    return Response::json(["test"=>$test])->setCallback(Input::get('callback'));
 });

to

Route::api(['version' => 'v1', 'prefix' => 'api', 'before' => ''], function () {

    Route::get("/test", function(){
        $test = [];
        for($i=0; $i<100; $i++){
            $test[$i] = new \stdClass();
            $test[$i]->name = "hi".$i;
        }
        return Response::json(["test"=>$test])->setCallback(Input::get('callback'));
     });
});

**Comment by tomvo** [comment]
Use the JSONP response format: https://github.com/dingo/api/wiki/Responses#custom-response-formats

**Comment by Naranbat1123** [comment]
my fault
