### ISSUE TITLE
Route problems

### ISSUE THREAD

**Issue by kabelo38** [dingo/api#397]
I am getting this from my log file can someone point me to the right direction plz

[2015-05-12 22:05:43] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\api\bootstrap\compiled.php:5738
Stack trace:
#0 C:\xampp\htdocs\api\bootstrap\compiled.php(5060): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\xampp\htdocs\api\bootstrap\compiled.php(5048): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\api\bootstrap\compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\api\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\api\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\api\bootstrap\compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\xampp\htdocs\api\bootstrap\compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\xampp\htdocs\api\bootstrap\compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\xampp\htdocs\api\bootstrap\compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\xampp\htdocs\api\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\api\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []

here is my route file
Route::api(['version' => 'v1', 'before' => 'api.logs'], function () {

	Route::get('/', function(){
		return View::make('hello');
	});

	Route::resource('/recipe', 'RecipeController@index');

});

and the controller file
<?php

use Illuminate\Routing\Controller;
use Dingo\Api\Routing\ControllerTrait;

class RecipeController extends Controller {

	use ControllerTrait;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index($format = '')
	{
		//
		$data = array();

		$data['breakfast'] =  array( 'Beacon', 'Eggs', 'Toast', 'Fat Cakes', 'Oyster', 'nothing');

		$data['lunch'] =  array( 'pizza');

		$data['dinner'] =  array( 'Beacon', 'Eggs', 'Toast', 'Fat Cakes', 'Oyster', 'nothing');

		$data['desert'] =  array( 'ice cream', 'pudding', 'nice staff');

		$data['kiddies_meal'] =  array( 'small burger', 'juice', 'chicken');

		return $this->response->array($user->toArray());

		//return json_encode($data);
	}

}

**Comment by camilstaps** [comment]
You're giving your Route the name of a function. For resource routes you should give it only the class: http://laravel.com/docs/4.2/controllers#restful-resource-controllers
