### ISSUE TITLE
Installing provider

### ISSUE THREAD

**Issue by akhedrane** [dingo/api#399]
to install in L5 should add LaravelServiceProvider to providers list right.
once appended provider, whole app was broken.

what wrong?

**Comment by jasonlewis** [comment]
Yes, that's correct. Add the provider in your `app.php` config file.

Can you please explain what is broken exactly. It's hard to guess without seeing any error reports.

**Comment by akhedrane** [comment]
i set debug to true but no error returned just a empty response.
all routes not work.

**Comment by jasonlewis** [comment]
Can you show me some sample code? Is this an existing project? Have you tried in a fresh project?

**Comment by camilstaps** [comment]
I have a similar problem. I'm developing a package which has Dingo as a dependency. In the `register()` of my ServiceProvider, I have:

    $this->app->register('Dingo\Api\Provider\LaravelServiceProvider');

I'm getting the error:

    FatalErrorException in Application.php line 541:
    Class 'Dingo\Api\Provider\LaravelServiceProvider' not found

The same when trying `ApiServiceProvider`.

I'm suspecting my composer.json:

    {
        ...
        "require": {
            "php": ">=5.5.0",
            "illuminate/support": "5.0.*",
            "dingo/api": "0.9.*@dev"
        },
        "autoload": {
            "classmap": [
                "src/migrations",
                "src/controllers"
            ],
            "psr-0": {
                "My\\Namespace\\": "src/"
            },
            "psr-4": {
                "Dingo\\Api\\": "vendor/dingo/api/src/"
            }
        },
        "minimum-stability": "stable"
    }

Could be a bug, but I think some mistake on my side is more likely.

**Comment by GrahamCampbell** [comment]
> I have a similar problem. I'm developing a package which has Dingo as a dependency. In the register() of my ServiceProvider, I have:

Your should never do that. You MUST always use the BOOT method if you're using ANY dependencies. This is true for anything in Laravel.

**Comment by camilstaps** [comment]
@GrahamCampbell thanks, that did it. I had it in the `register()` because of [this StackOverflow answer](http://stackoverflow.com/a/22749871/1544337).

**Comment by GrahamCampbell** [comment]
Oh, right. You're registering a service provider in there. Don't do that. Register it in your app.php config file...

**Comment by GrahamCampbell** [comment]
It's generally a bad practice for packages to register aliases and service providers in a forced way. Just give your package users instructions for what to do, and let them chose what to do. It's possible they want to customise things.

**Comment by camilstaps** [comment]
@GrahamCampbell Okay, that makes sense. Thank you!

NB: my last post was incorrect, in the `boot()` function I get the same problem.

**Comment by camilstaps** [comment]
@GrahamCampbell does that also mean I shouldn't mark Dingo as a dependency in my package's composer.json, but in the composer.json of the main laravel project?

**Comment by GrahamCampbell** [comment]
> does that also mean I shouldn't mark Dingo as a dependency in my package's composer.json

No, you should include the dependency, but not actually register it in your source code. Leave instructions in your readme.

**Comment by GrahamCampbell** [comment]
Example: https://github.com/GrahamCampbell/Laravel-Binput.

**Comment by jasonlewis** [comment]
Regardless, you shouldn't be getting a class not found if you're trying to register it in your provider. You shouldn't need to add anything in terms of autoloading to your `composer.json` file, the file within this package will handle that for you. So you can remove that.

**Comment by GrahamCampbell** [comment]
@jasonlewis That's probably what's causing the issue in the first pace tbh.

**Comment by jasonlewis** [comment]
I'm thinking so. I can register it fine in both the `app.php` file and from some other provider.

**Comment by camilstaps** [comment]
Hm, very strange. I believe I have everything as you say now.

* I'm not registering anything from my own service provider
* In config/app.php I have only added my own service provider and `Dingo\Api\Provider\LaravelServiceProvider` (in that order)
* In the main composer.json, the psr-4 autoloader has `App\` and my own service provider (without, *that* one can't be found) - nowhere am I autoloading Dingo's service provider
* In my package's composer.json, I have only my own service provider in the psr-4 autoloader.

When I try to add Dingo to the main composer.json, the LaravelServiceProvider *can* be found, but then I get the error `Uncaught exception 'ReflectionException' with message 'Class League\Fractal\Manager does not exist'`.

We can be quite sure it's not a bug, but any help would be appreciated nevertheless :)

**Comment by GrahamCampbell** [comment]
It looks like you've made a mess of this autoloading. Can you post the composer.json of your app and the one of your package please?

**Comment by camilstaps** [comment]
@GrahamCampbell thanks - here are my files: https://gist.github.com/camilstaps/5d76ec57425d7e8e3075

When I remove the everything but `App` from the psr-4 autoloader of the app, not even my own service provider can be found.

**Comment by GrahamCampbell** [comment]
Yeh, this is all wrong. Delete all the autoloading crap, then actually require the dependencies you need.

**Comment by camilstaps** [comment]
@GrahamCampbell but if I'd require it, I can't keep it in the same folder, can I? I would need a different location to store the package and then load it from there. This is my development environment, isn't it possible to not have to `composer update` for every change you make?

**Comment by GrahamCampbell** [comment]
> I can't keep it in the same folder, can I?

I literally have no idea what you're talking about?

**Comment by GrahamCampbell** [comment]
Ohh, I see. You're developing a package and want your changes live straight away. You'd have to rsync the folders after install or something.

**Comment by akhedrane** [comment]
so i tested some cases? i found that:

- if not add api route the other routes will not work (return empty).
...

**Comment by akhedrane** [comment]
- when add api route i get this error on all routes:
```json
{
"message": "404 Not Found",
"status_code": 404,
"debug": {
"line": 145,
"file": "app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",
"class": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
"trace": [
"#0 app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(729): Illuminate\\Routing\\RouteCollection->match(Object(Dingo\\Api\\Http\\Request))",
"#1 app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(652): Illuminate\\Routing\\Router->findRoute(Object(Dingo\\Api\\Http\\Request))",
"#2 app\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
"#3 app\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Laravel.php(52): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#4 app\\vendor\\dingo\\api\\src\\Routing\\Router.php(520): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
"#5 app\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(92): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
"#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#7 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#8 app\\vendor\\anlutro\\l4-settings\\src\\SaveMiddleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#9 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): anlutro\\LaravelSettings\\SaveMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#10 app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#11 app\\app\\Http\\Middleware\\VerifyCsrfToken.php(17): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#12 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#13 app\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#14 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#15 app\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#16 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#17 app\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#18 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#19 app\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#20 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#21 app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#22 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
"#23 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
"#24 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(101): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
"#25 app\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(93): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#26 app\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(74): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
"#27 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(125): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
"#28 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
"#29 app\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
"#30 app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(115): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
"#31 app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(84): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
"#32 app\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
"#33 {main}"
]
}
}
```

**Comment by camilstaps** [comment]
Since our issues turn out to be unrelated (and mine is merely a non-understanding of Laravel 5 package dev), I opened a question on StackOverflow for me: http://stackoverflow.com/q/30287651/1544337 ( @GrahamCampbell )

Apologies for the inconvenience.

**Comment by jasonlewis** [comment]
The API now requires you define either a `prefix` or `domain` in the configuration. If defining a domain you should ensure the only the API is running off of that domain or you'll get conflicts.

**Comment by akhedrane** [comment]
ok.
after last commits it work fine now.
thanks.
