### ISSUE TITLE
Unable to boot ApiServiceProvider, configure an API domain or prefix

### ISSUE THREAD

**Issue by vinkla** [dingo/api#406]
Then running the `vendor:publish` command I'm getting the following error returned.

```
Unable to boot ApiServiceProvider, configure an API domain or prefix.
```

I did solve this by specifying the `API_PREFIX` and `API_DOMAIN` in the environment file. Maybe we should keep default values?

**Comment by jasonlewis** [comment]
I'll have it not throw the exception under certain circumstances. You do
not need to provide both. Just one or the other.

**Comment by vinkla** [comment]
Okay, good. Wouldn't it be better if when the user register the package it wouldn't throw an exception?

**Comment by jasonlewis** [comment]
It would be but people will try and use it without configuring it and then
I'll get issues asking why it isn't working. Letting someone know it isn't
configured will hopefully get around that. I'll just have to not throw it
when running in the console.

**Comment by vinkla** [comment]
Aaah, okay. Then we're on the same page. Misunderstood you. Sorry.

**Comment by jasonlewis** [comment]
All good. I'll get a fix pushed up soon.

**Comment by vinkla** [comment]
Awesome!

**Comment by cvinothkumar** [comment]
@vinkla (thumbsup)
