### ISSUE TITLE
ErrorException in Laravel.php line 48:  Undefined index: v1

### ISSUE THREAD

**Issue by otherjohn** [dingo/api#408]
Ok getting an error. using Laravel 5.
ErrorException in Laravel.php line 48:
Undefined index: v1
 I get this when performing a get to the url http://app.dev/api/v1/

version and prefix are both set in config.
 'version' => env('API_VERSION', 'v1'),
 'prefix' => env('API_PREFIX', 'api'),

```
in Laravel.php line 48
at HandleExceptions->handleError('8', 'Undefined index: v1', 'APP/vendor/dingo/api/src/Routing/Adapter/Laravel.php', '48', array('request' => object(Request), 'version' => 'v1')) in Laravel.php line 48
at Laravel->dispatch(object(Request), 'v1') in Router.php line 526
at Router->dispatch(object(Request)) in Request.php line 92
at Request->Dingo\Api\Http\Middleware\{closure}(object(Request))
...
...
```
This is my routes file.

app('api.router')->version('v1', function ($api) {
Route::get('/', 'WelcomeController@index');
});

**Comment by jasonlewis** [comment]
Things have changed slightly...

You have to use the API router to register the routes as well.

```php
app('api.router')->version('v1', function ($api) {
    $api->get('/', 'WelcomeController@index');
});
```

Versioning is not done in the URL either so you shouldn't be including the `v1` in the URL. It'll default to `v1` as that's what you've provided in the configuration. You need to adjust the `Accept` header if you want to hit other versions.

**Comment by otherjohn** [comment]
Thanks, I get it now. But I am getting a 404 on this particular route.

app.dev/api/

app('api.router')->version('v1', function ($api) {
    $api->get('/', 'WelcomeController@index');
});

The welcomecontroller is in it's default spot AND resolves at app.dev/

**Comment by jasonlewis** [comment]
Is the controller namespaced? You'll need to add the full namespace as well
as the API routes won't inherit the one defined by Laravel.
