### ISSUE TITLE
Complex example 

### ISSUE THREAD

**Issue by KIVagant** [dingo/api#412]
Hello.

Is there somewhere a full example of the using this library? (Not wiki, just code)

Thank's.

**Comment by jasonlewis** [comment]
Not that I know of. I've not had time to overhaul the documentation yet.
I'm hoping those that will use it will go through the source.

If you have any questions sing out as there are a number of helpful folk
using it that may be able to give you a hand.

**Comment by KIVagant** [comment]
I'm looking for a way to combine this package with [laravel-api-generator](https://github.com/mitulgolakiya/laravel-api-generator/issues/40)
I was hoping to find an example of a controller for an object (eg, a user or an article) using dingo / api.

**Comment by KIVagant** [comment]
I ask someone from the developers to make a short example of "good practice" usage. For the REST API with normal HTTP response codes and simple Model.

**Comment by catalinux** [comment]
Something like that?
https://github.com/laravelista/Lissandra (I did not test it)

**Comment by KIVagant** [comment]
Lissandra does not uses dingo/api, but thank you. It can help me to understand Fractal

**Comment by jasonlewis** [comment]
Sorry I don't have time to write a complex example for you nor should I be required too. I'm working on documentation but you must realize that I do this in my free time and as such I'm not able to get it done in a couple of days.

So I ask that you be patient. Honestly, there's not a whole lot to this package and the older documentation on the Wiki is still somewhat relevant. Most differences are class names have changed and some methods may be different. My advice is to read over the old documentation, have a play with the package and flick through the source code.
