### ISSUE TITLE
Custom Response Factory

### ISSUE THREAD

**Issue by vinkla** [dingo/api#413]
Is it possible to overwrite the response factory? If I would like to add custom syntax for the http responses. Would be awesome if we could handle this outside of this package and use the default one that comes with the package out of the box.

**Comment by jasonlewis** [comment]
You can always extend `Dingo\Api\Http\Response\Factory` then simply rebind it in your own service provider. It's bound in the container as `api.http.response`.

```php
$this->app->singleton('api.http.response', function($app) {
    return new MyResponseFactory($app['api.transformer']);
});
```

**Comment by vinkla** [comment]
Aah okay, thanks!
