### ISSUE TITLE
Lumen working example

### ISSUE THREAD

**Issue by catalinux** [dingo/api#416]
After a few failures, I make it work. My problem was that in composer I had 

```    "laravel/lumen-framework": "5.0.*"```, instead of  ```    "laravel/lumen-framework": "5.0.*@dev"```

I am writing this "issue", taking in account it might help people to handle this packager. So, my full "receipe" was:

in .env file:

```
API_VENDOR=LumenApi
API_VERSION=v1
API_PREFIX=api
API_CONDITIONAL_REQUEST=true
API_STRICT=false
API_DEBUG=true
API_DEFAULT_FORMAT=json
```

in routes.php

```php
$api->version('v1', ['prefix' => 'api'], function($api) {
    $api->get('users', function() {
        return ['users' => 'all'];
    });
});
```
In app.php

```php
$app->register('Dingo\Api\Provider\LumenServiceProvider');
$app->register('App\Providers\AppServiceProvider');

// Get an instance of the API router so we can use it in the routes.php file
$api = $app['api.router'];
```

My working path

domain.com/api/users

My project was created wih

`composer create-project laravel/lumen my-project `

Question: can't be a constrain for `    "dingo/api": "0.9.*@dev"` to use '@dev' so that composer would tell you you need @dev for lumen framework?

**Comment by jasonlewis** [comment]
I did mention in my intial issue posted about Laravel 5 and Lumen support that you'd need to be on the develop branch of Lumen.

> Please note that if you're using Lumen you'll need to be using `lumen-framework 5.0.*@dev` for it to work correctly. These several routing changes that are yet to make it to a stable Lumen release.

**Comment by catalinux** [comment]
@jasonlewis : I know you did, it was my mistake, although I have read that notice a couple of times. I just wanted to emphasize that again. Can't be made that constrain from the composer.json?

**Comment by jasonlewis** [comment]
Not sure if you can but I don't think it's really worth it as Lumen should be bumping the version sometime soon.
