### ISSUE TITLE
Internal request dispatcher

### ISSUE THREAD

**Issue by lightvision** [dingo/api#417]
There is any chance to make the internal request dispatcher soon?

Or give me some hints to use it, if it's done.

Thank you

**Comment by jasonlewis** [comment]
It's not done as of yet. Soon though.

**Comment by lightvision** [comment]
Any chance with the internal dispatcher?

I know you've been bussy with exception handler but I build an app that self consumes the exposed api...

And some notices: the artisan route:list doesn't display the api routes in the command line.

**Comment by jasonlewis** [comment]
Dispatcher is still in progress. The command has also been removed for the
time being. It'll be back, probably once I get the dispatcher working.

**Comment by jasonlewis** [comment]
Just an update. I'm working on the final touches of the dispatcher and testing it so hopefully no nasties make it through.

**Comment by lightvision** [comment]
Great, I eggerly wait to test it!

**Comment by bweston92** [comment]
So glad, I'm porting my application over to L5 and this is only issue I have.

**Comment by xLink** [comment]
this is all im waiting for so i can wrap up upgrading my base to L5 :D

**Comment by Ortix92** [comment]
so close

**Comment by jasonlewis** [comment]
Dispatcher is live on the `master` branch which is now aliased to `0.9.*@dev` instead of the `develop` branch. Just `composer update` and let me know how you all get along with it.

**Comment by lightvision** [comment]
How can I call the dispatcher? Could you give me an example?

Thank you

**Comment by Ortix92** [comment]
I think you have to resolve it from the IoC container by 'making' and
instance of 'api'. On my phone so can't test

**Comment by jasonlewis** [comment]
Ha, good pick up. I never actually bound it to the container. Give me a few and I'll get that done. It'll be bound as `api.dispatcher`.

**Comment by lightvision** [comment]
On 08.06.2015 12:52, Jason Lewis wrote:
>
> Ha, good pick up. I never actually bound it to the container. Give me 
> a few and I'll get that done. It'll be bound as |api.dispatcher|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dingo/api/issues/417#issuecomment-109936333>.
>
Thanks.

**Comment by Ortix92** [comment]
Jason, you so silly

**Comment by jasonlewis** [comment]
Okay it's pushed, you may update.

Prefixes aren't automatically added so you'll need to specify that if you're using a prefix.

**Comment by lightvision** [comment]
On 08.06.2015 13:18, Jason Lewis wrote:
>
> Okay it's pushed, you may update.
>
> Prefixes aren't automatically added so you'll need to specify that if 
> you're using a prefix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dingo/api/issues/417#issuecomment-109942408>.
>
Under what key is the dispatcher? I cannot see any 'api.dispatcher'.

**Comment by lightvision** [comment]
What "dingo/api" version should be required in the composer.json?
I see the dispatcher on the master branch but not in the develop...

Thanks

**Comment by jasonlewis** [comment]
`0.9.*@dev` still, the alias has been updated to point to the `master` branch now. I'll remove the `develop` branch for now to avoid confusion.
