### ISSUE TITLE
Making same controller available under different endpoints (`/article` and `/user/{id}/article`)

### ISSUE THREAD

**Issue by camilstaps** [dingo/api#418]
Suppose I have a resource `user` and a resource `article`. I would like to have the following endpoints:

* `GET /article` - get all articles
* `GET /user/{id}/article` - list of articles of the indicated user

How would I define this in the routes, and in the controller? 

I'm thinking something like:

    $api->resource('article', 'My\NameSpace\ArticleController');
    $api->resource('user.article', 'My\NameSpace\ArticleController');

And then in the controller:

    public function index($user = null) {
        // ...
    }

Would that be the preferred way to do this?

**Comment by jasonlewis** [comment]
You could do it just like that, yes. You'd need a couple of checks in your controller as to whether or not the variable is defined and what have you. Obviously you can just run separate controllers to keep things organized if you wanted to as well. This is sort of up to you to decide.
