### ISSUE TITLE
Additional fields in error responses. Exceptions with the any additional data.

### ISSUE THREAD

**Issue by KIVagant** [dingo/api#419]
**Problem:**

I need to add some special fields to error request. The array 'errors' in Dingo custom Exceptions is not enough for me.

For example, i need to send error message:
```
"message": "Oops, some fields looks like incorrect!",
"system_message": "Validation error",
"something": "else",
"yet": ["another", "field"],
"code": 1234,
"status_code": 422,
```

**Resolution:**

In api.php setup new format:
```
'errorFormat' => [
        'message' => ':message',
        'system_message' => ':system_message', // this is a new one
        'errors' => ':errors', // this is an old, but can be used not only in ResourceException childs
...
    ],
```

Create the new Exception:

```
class TestException extends HttpException implements DingoException
{
    /**
     * @var \Illuminate\Support\MessageBag
     */
    protected $errors;
    protected $system_message = '';
    public function __construct($message = null, $system_message = '', $errors = null, Exception $previous = null, $headers = [], $error_code = 0)
    {
        $this->system_message = $system_message;
        if (is_null($errors)) {
            $this->errors = new MessageBag;
        } else {
            $this->errors = is_array($errors) ? new MessageBag($errors) : $errors;
        }

        parent::__construct(400, $message, $previous, $headers, $error_code);
    }

    // This is a new desired functionality
    public function getReplacements()
    {
        return [
            ':errors' => $this->errors,
            ':system_message' => $this->system_message,
        ];
    }
}
```

Than throw it from API

```
throw new TestException('Lovely bug', 'All is dead', [ 'humans' => 'dead', 'cockroaches' => 'dead' ], null, [], 123456);
```

And now, get this result:
```
{
    "message": "Lovely bug",
    "system_message": "All is dead",
    "errors": {
        "humans": [
            "dead"
        ],
        "cockroaches": [
            "dead"
        ]
    },
    "code": 123456,
    "status_code": 400
}
```

Pull request is coming.

**Comment by jasonlewis** [comment]
Just catch all errors thrown and deal with them yourself. You can use
app('api.exception')->register() with a call back that type hints the
global Exception class.

**Comment by KIVagant** [comment]
@jasonlewis , if I will catch exception before dingo, then I will need to rewrite all this logic:

```
 return $this->prepareResponse(
                $this->exception->handle($exception),
                $request,
                $accept['format']
            );
```

It is not good way.

Dingo/api has own special exceptions, it's already show, that default functionality is not enough. I propose remove this limitations. This library do a good job for REST supporting, but why it try to limit response data?

**Comment by jasonlewis** [comment]
It doesn't try to limit anything. It's just how it's done at the moment.

I've seen you sent the PR so I'm more then happy to look at it when I get
the chance. Doesn't look like a huge change according to the e-mail so I
can't see why not at this stage.

**Comment by KIVagant** [comment]
It's a not big patch. I tried to find a minimal way to get result, but in future, genericResponse method waiting to refactoring. I think, most correctly is to check any available fields from config in exception instead of writing hardcoded special exceptions, like ```$exception->hasErrors()``` in ResourceException. $replacements need to fetch from default trait or interface method.

P.S.: Sorry for bad english, hope you understand my proposition.

**Comment by jasonlewis** [comment]
I do and I thank you for your time. I'll get on it soon.

**Comment by KIVagant** [comment]
@jasonlewis , don't merge it now, I make some little changes for more accurate use.

**Comment by KIVagant** [comment]
@jasonlewis, ok I'm done.

Now it looks not like true-OOP-way. But usage is much more simple. 
Good news:
- You can use any Exception without extending.
- You can easily add properties what you need to response.
- You still have control on responses from config.

Usage:
1. Add new return fields to api.php errorFormat.
2. Throw exception from Api:
```
use  \Symfony\Component\HttpKernel\Exception;
$throw = new BadRequestHttpException('Lovely bug', null, 123456);

$throw->replacements = [  // Here is a new functionality
    ':errors' => [ 'humans' => 'dead', 'cockroaches' => 'dead' ],
    ':system_message' => $error['system_message'],
    // here you can add any fields, but don't forget to setup them in api.php
];
throw $throw;
```

---------------
**For example**, now you can change your ResourceException (and other) and make it more clear.

```
class ResourceException extends HttpException
{
    protected $replacements;
    public function __construct($message = null, $errors = null, Exception $previous = null, $headers = [], $code = 0)
    {
        if (is_null($errors)) {
            $this->replacements[':errors'] = new MessageBag;
        } else {
            $this->replacements[':errors'] = is_array($errors) ? new MessageBag($errors) : $errors;
        }

        parent::__construct(422, $message, $previous, $headers, $code);
    }
}
```
And then you can remove this if statement from Handler->genericResponse:
```
        if ($exception instanceof ResourceException && $exception->hasErrors()) {
            $replacements[':errors'] = $exception->getErrors();
        }
```

**Comment by KIVagant** [comment]
@jasonlewis, [PR in laravel-api-generator](https://github.com/mitulgolakiya/laravel-api-generator/pull/54) is depends to this issue.

**Comment by jasonlewis** [comment]
Let's move discussion over to the PR, #420. :smile:
