### ISSUE TITLE
Pagination in Laravel5/Lumen Version

### ISSUE THREAD

**Issue by stygiansabyss** [dingo/api#422]
I am giving this it's own issue so as not to clutter #398.  

I am currently working on getting pagination to respond like Fractal does, but I wanted to make sure that was the expected behavior.

```
{
    data: {...}
    meta: {
        pagination: {
            total: 207,
            count: 20,
            per_page: 20,
            current_page: 1,
            total_pages: 11,
            links: {
               next: "http://localhost/api/v1/video/?page=2"
            }
        }
    }
}
```

Can anyone let me know if this is how the response should be returned on a paginated resource?

**Comment by stygiansabyss** [comment]
@appkr's solution in the original issue does work.  Not sure if that should be the correct resolution though.

**Comment by jasonlewis** [comment]
See #448, we'll get a PR merged in for a fix on pagination soon.
