### ISSUE TITLE
What are the advantages of dingo/api over just having regular routes with jwt token authentication?

### ISSUE THREAD

**Issue by jrm2k6** [dingo/api#425]
I guess the question is pretty self-explanatory, but as we are moving to L5 and have to juggle with having dingo/api working, we might be considering going away from it as our API is still fairly small.

What are the pros of using dingo/api?

**Comment by bweston92** [comment]
Main one for me is internal requests, therefore your own front end controllers can use your API which is neat.




It utilises Fractal allowing transformers which keep consistency with data over versions of your API.



—

**Comment by jayhealey** [comment]
On top of that: documentation, community support and bug fixes. 

You can point any new developer on your team to the documentation, and they'll pick it up quickly.

**Comment by jrm2k6** [comment]
Thanks guys for answering.
I overlooked the point about internal request. That's a great advantage.
