### ISSUE TITLE
Rate Limiting error responses are plain text, not JSON.

### ISSUE THREAD

**Issue by jayhealey** [dingo/api#427]
I've noticed when using rate limiting (as below) the response is inconsistent with other responses. Preparing the route:
```
    $api->get('session/start', [
        'limit'   => 5,
        'expires' => 1,
        'uses'    => 'App\Http\Controllers\SessionController@getToken'
    ]);
```

And whilst it returns a HTTP 403 code, the body of the response is plain text, currently:
```
You have exceeded your rate limit.
```

Is there way to replace this with a JSON response?
```
{"message": "You have exceeded your rate limit.", "status_code": 403}
```

Any ideas? Thanks in advance.

**Comment by jasonlewis** [comment]
Hm yes, it should be that. Will fix this.

**Comment by jasonlewis** [comment]
Fixed.

**Comment by jayhealey** [comment]
Awesome, thank you!
