### ISSUE TITLE
Route::api don't work in Laravel 5

### ISSUE THREAD

**Issue by luizreginaldo** [dingo/api#432]
Hello, I am trying to use the API in Laravel 5 using the branch Develop but when configuring the route generates an exception "BadMethodCallException in Macroable.php line 87: Method api does not exist."

**Comment by GrahamCampbell** [comment]
Looks like the service provider isn't correctly registered or you've resolved the router too early in the application startup cycle.

**Comment by tymondesigns** [comment]
Don't you have to use the router resoved from `app('api.router'); anyway` ?

I had the same error at first and just added `$api = app('api.router');` to my `RouteServiceProvider`.

Then in the routes file...

```php
$api->version('v1', ['prefix' => 'api'], function($api) {
    $api->get('users', function() {
        return ['users' => 'all'];
    });
});
```

**Comment by GrahamCampbell** [comment]
> Don't you have to use the router resolved from app('api.router'); ?

That is true, yes. This has changed since the previous version of dingo api.

**Comment by tymondesigns** [comment]
@GrahamCampbell indeed it has :+1: 

@luizreginaldo If you follow this method, you will also have to add the namespace key if you want access your controllers without the full path. e.g.

```php
$api->version('v1', ['namespace' => 'App\Http\Controllers'], function ($api) {
    $api->get('users', 'UsersController@getUsers');
});
```

**Comment by luizreginaldo** [comment]
Hello guys, now worked for me.

Thank you =)

**Comment by bweston92** [comment]
I must say I'm having this issue.

```
/** @var \Dingo\Api\Routing\Router $api */
$api->version('v1', function ($api) {
    $api->get('time', function () {
        return ['now' => microtime()];
    });
});
```

I have the configuration setup with the group being `api` and the version being `v1`. However I'm getting a 404 when accessing `/api/time`.

**Comment by bweston92** [comment]
I've found that `Dingo\Api\Http\Request` the `$old` is fine and has everything yet `$new` is blank in terms of the path ect. This means that `Illuminate\Routing\RouteCollection@check` fails.

**Comment by bweston92** [comment]
![image](https://cloud.githubusercontent.com/assets/1764057/8035792/6032a704-0deb-11e5-8431-c40448760127.png)

**Comment by catalinux** [comment]
@bweston92 Are you using Lumen or Laravel? I had same problem with Lumen last week: routes won't work after Friday update. (for now I stopped using Dingo)

**Comment by bweston92** [comment]
Laravel version 5.1.

**Comment by bweston92** [comment]
Ok this isn't the issue, I just seen Symfony's `preparePathInfo` which fills it from `REQUEST_URI` but I'm still stuck with this one.

**Comment by lightvision** [comment]
On 08.06.2015 16:39, Bradley Weston wrote:
>
> Laravel version 5.1.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dingo/api/issues/432#issuecomment-109998121>.
>
Please configure properly. I've the same issues but it works.

**Comment by bweston92** [comment]
Enlighten me.. I've got `config/api.php` setup correctly.

**Comment by bweston92** [comment]
In actual fact it is the `prefix` config that isn't working for me, any ideas?

**Comment by lightvision** [comment]
Short answer: It is working, with prefix. If you want to use it with API_DOMAIN you must setup the subdomain properly first.

Long answer:

On app/Providers/RouteServiceProvider.php, I have the following code

```
public function register() {
        parent::register();
        
        # register the API V1 routes
        $this->app->register(\App\Api\v1\Providers\ApiRouteServiceProvider::class);
    }
```

The **ApiRouteServiceProvider.php** class is a **RouteServiceProvider** which will map the routes for api

Here is the content of the **\App\Api\v1\Providers\ApiRouteServiceProvider**:

```
class ApiRouteServiceProvider extends ServiceProvider {

    protected $namespace = 'App\Api\v1\Http\Controllers';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @param  Router  $router
     * @return void
     */
    public function boot(Router $router) {
        //

        parent::boot($router);
    }

    public function map(\Dingo\Api\Routing\Router $api) {

        $api->version(['version' => 'v1','namespace'=>  $this->namespace], function($api) {
            $api->group(['prefix' => 'api'], function ($api) {
                return require app_path('Api/v1/Http/routes.php');
            });
        });
    }

}
```

... and the content of the **Api/v1/Http/routes.php**:
```
$api->get('users', function() {
    return ['users' => 'all'];
```});

obviously I've omitted the **namespace** and the **use** declarations from the **ApiRouteServiceProvider** class.

I don't want to start a flame here with why I choose this kind of structure for my self api consuming app since I know that Phil Sturgeon disregard it but is the only option I've had...

On topic again, I hope it will help you

**Comment by bweston92** [comment]
I can ensure that the prefix doesn't work for me. If I specify it in my "group" then yes but the default config `API_PREFIX` doesn't work. I have opened an issue #458

**Comment by zmorris** [comment]
I am working through the Laravel 5 and Dingo installation and while it's fresh in my mind I wish to state that I'm disappointed that Dingo has gone with its own router.  I feel that this is a mistake and would much prefer the original Route::api() syntax for its elegance and integration with current Laravel contextual metaphors.  My current project is a pure REST API implentation in Laravel so forking the routes in this manner adds unnecessary mental load.  It's possible that I am just missing the command to provide the api() methods to Route.  Other than that, thank you for your efforts, Dingo looks very promising and I really appreciate how you have encapsulated the various errata that come with building out an API.
