### ISSUE TITLE
Retrieving Authenticated User in Laravel5 version

### ISSUE THREAD

**Issue by luizreginaldo** [dingo/api#433]
Hello all.
How do I get the authenticated user using the version 0.9.*@dev?

```php
$auth = app('api.auth');
$user = $auth->getUser();
```

This works, but is correct?

**Comment by jasonlewis** [comment]
That is indeed correct. If you're using a controller and using the `Dingo\Api\Routing\Helpers` trait you can use the helper method included.

```php
public function index()
{
    $user = $this->user();
}
```
