### ISSUE TITLE
JsonResponse not valid

### ISSUE THREAD

**Issue by slovenianGooner** [dingo/api#443]
So I got this while trying to pass through a JsonResponse:

```
Argument 1 passed to Dingo\\Api\\Routing\\Router::prepareResponse() must be an instance of Illuminate\\Http\\Response, instance of Illuminate\\Http\\JsonResponse given, called in \/api\/vendor\/dingo\/api\/src\/Routing\/Router.php on line 533 and defined.
```

Fixed it by adding this to line 528 in the Router.php file:

```
$response = $this->adapter->dispatch($request, $accept['version']);

if ($response instanceof JsonResponse) {
    return $response;
}

return $this->prepareResponse($response, $request, $accept['format']);
```

So basically just returning the response. I wasn't sure if it was the right thing to do, that's why I created the issue, not doing a pull request.

**Comment by jasonlewis** [comment]
You shouldn't really be passing back a JsonResponse. That's Dingo's job.

**Comment by GrahamCampbell** [comment]
@jasonlewis Surely you should allow any kind of response, including a symfony response?

**Comment by slovenianGooner** [comment]
True, but Dingo throws an error saying JsonResponse is not of correct instance. I get that Dingo prepares every statement. If it helps I'm working with the OAuth2 server returning an access token.

**Comment by jasonlewis** [comment]
Send a pull if you like but not how you've fixed it. Just don't morph the
response that's done in prepare response. If a Symfony response instance is
returned as well then it must also not be morphed.

Originally the strict type hinting was so I didn't get issues from people
asking why transformers are working and all that jazz because they were
returning symfony and or json responses.

**Comment by slovenianGooner** [comment]
Yeah, got no problem with that, will try to fix it and send in a pull request, was just wondering if I was doing something wrong.

**Comment by slovenianGooner** [comment]
Closing this. Solved it by parsing a simple array to Dingo.
