### ISSUE TITLE
How do you set a custom serializer?

### ISSUE THREAD

**Issue by catalinux** [dingo/api#444]
I could not find a way to change the serializer. I want to use a Custom JsonApi serializer for Controller responses.

**Comment by jasonlewis** [comment]
You can do this within your configuration.

```php
'transformer' => function ($app) {
    $fractal = new League\Fractal\Manager;

    $fractal->setSerializer(new YourSerializer);

    return new Dingo\Api\Transformer\Adapter\Fractal($fractal);
}
```

**Comment by catalinux** [comment]
I use .env file. Where do I put this config?

**Comment by BradleyDeLar** [comment]
If you don't already have it in your root directory put a `config` folder in there and copy the api config file into that folder, then you just need to load the config <i>before</i> you register the provider using `$app->configure('api');`
http://lumen.laravel.com/docs/configuration#configuration-files

**Comment by catalinux** [comment]
Tx @BradleyDeLar 

For now I used like this:

in my `.env` file I added my own 
`API_TRANSFORMER=App\Api\CustomFractal`

CustomFractal where extends 

```php
class CustomFractal extends Fractal
{
    public function __construct(FractalManager $fractal, $includeKey = 'include', $includeSeparator = ',', $eagerLoading = true)
    {
        $this->fractal = $fractal;
        $this->includeKey = $includeKey;
        $this->includeSeparator = $includeSeparator;
        $this->eagerLoading = $eagerLoading;
        $this->fractal->setSerializer(new CustomJsonApiSerializer());
    }

}
```

**Comment by vinkla** [comment]
@catalinux Do you have a working `JsonApiSeriaizer` to share?

**Comment by jasonlewis** [comment]
Fractal ships with one does it not?

**Comment by vinkla** [comment]
It does but sadly its not yet compatible with the new standards.

**Comment by jasonlewis** [comment]
I've not kept up with the standard. It was changing frequently when I first
implemented the serializer. Feel free to send a PR to the fractal
repository if you're able to fix it.

**Comment by vinkla** [comment]
I think @philsturgeon wanted to wait on the standard to hit `1.0`. I've opened a issue in their repo #187.

**Comment by catalinux** [comment]
@vinkla : nope, I do not have. Also, I do not think I will implement in the next future a "standard jsonapi".

**Comment by vinkla** [comment]
@catalinux Okay, too bad. Not sure what you mean in that last sentence. Are you saying you wont implement the latest standard?

**Comment by rossedman** [comment]
Thought I would paste this in here for anyone looking for it 

```php
use Illuminate\Support\ServiceProvider;

class FractalServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind('League\Fractal\Manager', function($app) {
            $fractal = new \League\Fractal\Manager;

            $serializer = new \League\Fractal\Serializer\JsonApiSerializer();

            $fractal->setSerializer($serializer);

            return $fractal;
        });

        $this->app->bind('Dingo\Api\Transformer\Adapter\Fractal', function($app) {
            $fractal = $app->make('\League\Fractal\Manager');

            return new \Dingo\Api\Transformer\Adapter\Fractal($fractal);
        });
    }
}
```

**Comment by ozanmuyes** [comment]
@rossedman Thanks for the code but there's a typo in the first call of bind() method. `$this->app->bind('League\Fractal\Manager', ...` should be `$this->app->bind('\League\Fractal\Manager', ...` - notice the '\' before 'League'.

**Comment by antfig** [comment]
@rossedman I try your service provider but is not working for me, I create the service provider and add it to app => providers, but not setting JsonApiSerializer by default.
I need to do something else?
