### ISSUE TITLE
[Feature Request] Better JSON API Support

### ISSUE THREAD

**Issue by vinkla** [dingo/api#446]
Currently we have no real http://jsonapi.org/ support. Would be awesome if we could implement it.

**Comment by catalinux** [comment]
I think it should me bade through a serializer used by the fractal manager. It used to have one, but it's not updated with the laste chanes of jsonapi.

**Comment by vinkla** [comment]
I think so too. Hope they'll update it soon.

**Comment by lucasmichot** [comment]
Isn't it a bit out of the scope of dingo/api ?
Everyone is free to use their own serializers and implements jsonapi, hateoas or any other one

**Comment by vinkla** [comment]
I just wanted to bring the issue up. In my opinion this package should strive to support at least some standards out of the box. Though this specific case should probably be fixed in the Fractal package. I've opened an issue there as well https://github.com/thephpleague/fractal/issues/187

**Comment by jasonlewis** [comment]
We'll leave this up to the Fractal folks. (I'm meant to be one, so busy though. I'll take a better look at it when I get the chance.)

**Comment by vinkla** [comment]
Okay, sounds good!

**Comment by avyas** [comment]
Looks like https://github.com/thephpleague/fractal/pull/205 added that support in Fractal , can someone confirm this?

**Comment by pelletiermaxime** [comment]
Yes, jsonapi support is much better in fractal's master. Hopefully they will tag a release with those enhancements soon.
