### ISSUE TITLE
composer update with lumen framework does not work

### ISSUE THREAD

**Issue by catalinux** [dingo/api#447]
```json
  "require": {
    "laravel/lumen-framework": "5.0.*@dev",
    "vlucas/phpdotenv": "~1.0",
    "dingo/api": "0.9.*@dev",
    "league/fractal": "*",
    "fzaninotto/faker": "1.4.*"
  },
```

```composer update```

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove dingo/api 0.9.x-dev|keep dingo/api dev-develop
    - dingo/api 0.9.x-dev requires illuminate/routing 5.1.* -> no matching package found.
    - dingo/api dev-develop requires illuminate/routing 5.1.* -> no matching package found.
    - Installation request for dingo/api 0.9.*@dev -> satisfiable by dingo/api[0.9.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by vinkla** [comment]
Try using `"laravel/lumen-framework": "5.1.*@dev"` instead.

**Comment by GrahamCampbell** [comment]
`"league/fractal": "*",` wildcard version constraints are always a bad idea

**Comment by catalinux** [comment]
Problem 1
    - Installation request for laravel/lumen-framework 5.1.*@dev -> satisfiable by laravel/lumen-framework[5.1.x-dev].
    - laravel/lumen-framework 5.1.x-dev requires illuminate/auth 5.1.* -> no matching package found.
  Problem 2
    - remove dingo/api 0.9.x-dev|keep dingo/api dev-develop
    - dingo/api 0.9.x-dev requires illuminate/routing 5.1.* -> no matching package found.
    - dingo/api dev-develop requires illuminate/routing 5.1.* -> no matching package found.
    - Installation request for dingo/api 0.9.*@dev -> satisfiable by dingo/api[0.9.x-dev].

**Comment by jrm2k6** [comment]
Same thing with Laravel 5.0: 
```
"laravel/framework": "5.0.*",
"illuminate/html": "~5.0",
```

Is there a way to work around that? As we don't want to upgrade from 5.0 to 5.1 yet.

**Comment by vinkla** [comment]
@jrm2k6 This package no longer supports Laravel 5.0 as of #440. Though, you could update to Laravel 5.1 today. They've said it will be released right after Symfony 2.7 which was some days ago.

**Comment by jrm2k6** [comment]
That's interesting. So the package supports 4.2, and supports 5.1 but not 5.0. It would have been sweet to know about this plan before. Will see what I can do

**Comment by vinkla** [comment]
The transition between Laravel 5.0 and [5.1 is almost none existing](http://laravel.com/docs/master/upgrade#upgrade-5.1.0), you should check it out.

**Comment by jrm2k6** [comment]
Cool thanks!

**Comment by slovenianGooner** [comment]
Yeah, even if changing to 5.1.*@dev it still returns an error. Any ideas?

**Comment by GrahamCampbell** [comment]
> Yeah, even if changing to 5.1.*@dev it still returns an error. Any ideas?

You need to correctly set the GLOBAL minimum stability.

**Comment by slovenianGooner** [comment]
Yes, seems to do the trick. Was just having the GLOBAL preferred-install set to dev. Thanks!

**Comment by GrahamCampbell** [comment]
"preferred-install" isn't right...

**Comment by GrahamCampbell** [comment]
`"preferred-install": "dist"` should be dist

**Comment by GrahamCampbell** [comment]
```json
    "minimum-stability": "dev",
    "prefer-stable": true
```

**Comment by GrahamCampbell** [comment]
> preferred-install

That's telling composer to download zips, or clone the repo.

**Comment by catalinux** [comment]
It works. Tx @GrahamCampbell

**Comment by slovenianGooner** [comment]
Are there any changes on how the API routes are registered? Can't seem to get it to work after the update.

**Comment by catalinux** [comment]
Same question here, such route does not work any more:

```php
$api->version('v1', ['prefix' => 'api'], function ($api) {

    $api->resource('contact', 'App\Http\Controllers\ContactController');

});
```

```
GET /api/contact/1 HTTP/1.1
```

NotFoundHttpException in Application.php line 1116:

**Comment by jasonlewis** [comment]
Looking at Lumen it seems some changes that made it to `5.0` haven't been merged into the master branch yet, not sure if they will any time soon. I'll raise this issue with Taylor. Hopefully then routing is restored for Lumen.

**Comment by jasonlewis** [comment]
https://twitter.com/jasonclewis/status/607019177065353216

I'll check shortly but it should be fine now if you're using Lumen. Just run an update.

**Comment by jasonlewis** [comment]
Can confirm, all should be sweet now folks. Let me know if you're still having dramas.
