### ISSUE TITLE
Why dingo is collecting my all routing information

### ISSUE THREAD

**Issue by dharmendrajadon** [dingo/api#451]
I see in my logs, all routes are collected by dingo and them further processed
Here is the Log:
-------------------------
[2015-06-05 02:05:33] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/lorgan/public_html/protected/bootstrap/compiled.php:5751
Stack trace:
#0 /home/lorgan/public_html/protected/vendor/dingo/api/src/Routing/Router.php(326): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /home/lorgan/public_html/protected/bootstrap/compiled.php(5061): Dingo\Api\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/lorgan/public_html/protected/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /home/lorgan/public_html/protected/vendor/dingo/api/src/Routing/Router.php(205): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /home/lorgan/public_html/protected/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#5 /home/lorgan/public_html/protected/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#6 /home/lorgan/public_html/protected/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#7 /home/lorgan/public_html/protected/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /home/lorgan/public_html/protected/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home/lorgan/public_html/protected/bootstrap/compiled.php(11045): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /home/lorgan/public_html/protected/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /home/lorgan/public_html/index.php(50): Illuminate\Foundation\Application->run()
#12 {main} [] []

**Comment by jasonlewis** [comment]
I'm not sure what your issue is here? You're getting a not found, perhaps paste your routes file and other related bits and pieces.
