### ISSUE TITLE
Api routes are not listed

### ISSUE THREAD

**Issue by lightvision** [dingo/api#457]
When I run php artisan route:list the registered api routes are not shown.
Am I missing something?

PS. I get the propper response from the controller with a test route.

I've also notet that with Ding/Api enabled the name of the Middleware is changed to the full namespaced middleware name instead of its key

**Comment by catalinux** [comment]
According to https://github.com/dingo/api/issues/398

"There is no route command at this point in time. It will be back."

You could var_dump the fastroute object to see some data

**Comment by lightvision** [comment]
On 08.06.2015 12:20, catalinux wrote:
>
> According to #398 <https://github.com/dingo/api/issues/398>
>
> "There is no route command at this point in time. It will be back."
>
> You could var_dump the fastroute object to see some data
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dingo/api/issues/457#issuecomment-109924033>.
>
Thanks, I already did that.

**Comment by jayhealey** [comment]
Investigating the FastRoute object gets messy quickly. 

I had a quick stab at building up the routes...

```
$api = app('api.router');

/** @var $api \Dingo\Api\Routing\Router */
$routeCollector = $api->getRoutes(config('api.version'));

/** @var $routeCollector \FastRoute\RouteCollector */
$routeGroups = $routeCollector->getData();
```

The value of `$routeGroups` is an array in two parts: first part listing the simple routes (without parameters) and the second part being the parametrised routes. 

The simple routes are easy to hack into a simple list:

```
 $routes = [];
        
foreach ($routesGroups[0] as $url => $routeDetails) {
    $route = ['url' => $url];

    foreach ($routeDetails as $method => $details) {
        $route['methods'][] = $method;
        $alias = isset($details['as']) ? $details['as'] : $url; 
    }

    $route['alias'] = $alias; // The alias doesn't change per method, so use the last one.

    $routes[] = $route;
}
```

However, the parametrised routes in FastRoute are more complicated, as the routes (e.g. `blog/{id}`) have been turned into regex (e.g. `~^(?|/blog/([^/]+)())$~`), and the parameters aren't set as named attributes. They appear to be by index, which changes per route depending on the settings of it.

So building those up into something nice is more complicated. I'd be keen to see how others might tackle that.

**Comment by lightvision** [comment]
Me too since hunting to the api routes is a nightmare, 'cause I have a lots of routes.

@jasonlewis I was looking to the Dingo\Api code for L4 and the only problem to make the artisan to show the api routes is a missing method ```getApiGroups()```

**Comment by jasonlewis** [comment]
I'm working on this at the moment along with something else.

**Comment by lightvision** [comment]
Thanks, it is working like a charm.

**Comment by catalinux** [comment]
@lightvision : how did you make to work for you? For now I made a command that show a friendly scrapping of route adapter but is not accurately (i could not acces the generator direct on routecollector). https://gist.github.com/catalinux/baa48f2a73372950cebd

**Comment by jasonlewis** [comment]
Use api: routes command, only available in Laravel. Refer to the
documentation for more.

**Comment by catalinux** [comment]
@jasonlewis: I omitted, I made that command for Lumen . @jayhealey was talking about FastRoute , so I assumed that everybody talked about Lumen.

**Comment by jasonlewis** [comment]
The only reason it doesn't work on Lumen is due to Lumen now having a
routes command. It's a part of the Laravel core. The API command extends
this command for the base functionality.

If you really need it you could install Laravel/framework and then remove
the if statement in the API service provider then prevents the commands
from registering. Or register the command yourself.

**Comment by jakubkratina** [comment]
You can try this little package: https://packagist.org/packages/jakubkratina/lumen-dingo-route-list
