### ISSUE TITLE
Default route prefix from config.

### ISSUE THREAD

**Issue by bweston92** [dingo/api#458]
I have the `config/api.php` filled out. I have my `prefix` as "api" so therefore the following route should be matched by `/api/time`.

```
/** @var \Dingo\Api\Routing\Router $api */

$api->version('v1', function ($api) {
    $api->get('time', function () {
        dd('Got here.');
        return ['now' => microtime()];
    });
});
```

However the `Illuminate\Routing\Matching\UriValidator` is returning false on the following comparison. `#^/time$#s` is matched by `/api/time`.

Am I doing something wrong? When I remove the `prefix` option the service provider throws an exception for not being configured properly.

Using `1f67727392`

**Comment by jasonlewis** [comment]
You need to specify the prefix in both the configuration and in your route declarations.

```php
$api->version('v1', ['prefix' => 'api'], function ($api) {
    $api->get('time', function () {
        dd('Got here.');
        return ['now' => microtime()];
    });
});
```
