### ISSUE TITLE
[L5] Laravel Adapter overrides all routes from base app

### ISSUE THREAD

**Issue by Anahkiasen** [dingo/api#460]
In the Laravel adapter you do this in the dispatch method:

```php
$routes = $this->routes[$version];
$this->router->setRoutes($routes);
```

This replaces all the base routes with the API's, which means if like me you have a controller that returns views per example (for components generation and stuff) all `URL::route` calls (and similar) refering to base routes will fail. 

Isn't there a way to merge the base + API routes? By doing a `getRoutes` on the original router and then re-adding the API routes or something?

**Comment by jasonlewis** [comment]
Yeah that should be what happens. Something I overlooked.

**Comment by jasonlewis** [comment]
Fixed, the old, existing routes will now be merged with the API routes.
