### ISSUE TITLE
Wiki: ControllerTrait does not exist

### ISSUE THREAD

**Issue by srph** [dingo/api#469]
I just checked the wiki, and I was wondering if the [Responses](https://github.com/dingo/api/wiki/Responses) wiki is a bit outdated. I was trying to find `Dingo\Api\Routing\ControllerTrait`, but it [does not exist](https://github.com/dingo/api/tree/master/src/Routing).

**Comment by catalinux** [comment]
in the dev version  there is a Helper trait.

**Comment by srph** [comment]
Alright, will test that out. Are the docs a bit outdated?

**Comment by jasonlewis** [comment]
Docs are yes, will be working on them soon once I sort a few more issues out.

**Comment by srph** [comment]
:+1:
