### ISSUE TITLE
[L5.1] How to use Response Factory

### ISSUE THREAD

**Issue by gdg87** [dingo/api#470]
Hi, I don't understand how to use the default response provided by dingo with the 0.9.*@dev version on laravel 5.1. 
How can I use it in a generic function of a controller?

**Comment by jasonlewis** [comment]
Use the `Dingo\Api\Routing\Helpers` trait in your controller. From there you have access to a number of helper methods that let you create responses.

```php
class MyController extends BaseController
{
    use Dingo\Api\Routing\Helpers;

    public function index()
    {
        return $this->response->array(['foo' => 'bar']);
    }
}
```

Not a great example but the `response` property will let you return certain responses.
