### ISSUE TITLE
Different Fractal Serializer on Each Response

### ISSUE THREAD

**Issue by vugtis** [dingo/api#475]
Hi,
Is it possible to set different serializer for fractal on each response? My front end use different plugin for displaying table. Each of them expect different format of json.

I was hoping something like :
```sh
return $this->response->setSerializer(new CustomSerializer())->collection($result, new UserTransformer);
```

I tried a workaround which I override api.transformer on dingo and set fractal serialize on the fly, but I think it is not very clean.

**Comment by tomschlick** [comment]
You could set a $serializer attribute on each class and automatically set the serializer in a base class.

**Comment by jasonlewis** [comment]
I've just implemented a method to let you grab the transformation layer adapter from the factory, so you can do something like this.

```php
app('api.transformer')->getAdapter()->getFractal()->setSerializer(new CustomSerializer);
```

Not elegant but should suffice.

**Comment by jasonlewis** [comment]
Actually I just made the callback receive the Fractal instance so you should be able to do something like this now.

```php
return $this->response->collection($result, new UserTransformer, function ($resource, $fractal) {
    $fractal->setSerializer(new CustomSerializer);
});
```

**Comment by vugtis** [comment]
Thank you. That should do the trick. I'll test it soon. Anyway, I've found another issue about transformer. But I guess I will open new thread about that. Cheers.
