### ISSUE TITLE
How to testing with header bearer Jwt in Laravel 5.1

### ISSUE THREAD

**Issue by ghprod** [dingo/api#476]
Hi, 

i use JWT for my auth and i'm trying to write some test to see json output when using expired token, but seems like i never success to pass `Header Authorization Bearer` through request, here's my code

```php
public function testRestrictedAreaWithExpiredToken()
	{
		$this->get('/api/users', [
				'Accept'		=> 'application/vnd.'. env('API_VENDOR', '') .'.v1+json',
				'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJzdWIiOjIsImlzcyI6Imh0dHA6XC9cL2xhcmF2ZWwtNS0xLmRldlwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6IjE0MzQ3MzkwODAiLCJleHAiOiIxNDM0NzQyNjgwIiwibmJmIjoiMTQzNDczOTA4MSIsImp0aSI6IjY1ODg5MDAwNzUyMzE5ODJkZWEzYTVlZTFlZDY5ZWNjIn0.OTAyNDI5NzRkMWMyYzY5ZWI2ZmZkNTIyYTJjMTY1NTAxMWNjYzdjZDQ5OTk1ZmUxMGIwZTU2M2ZiN2MxNGFkZQ',
			])
            ->seeJson([
                'message'		=> 'Token has expired',
                'status_code'	=> 401,
            ]);
	}
```

And this is my result test, with error output same with condition where there's no token given in header

```
There was 1 failure:

1) AuthTest::testRestrictedAreaWithExpiredToken
Unable to find JSON fragment ["message":"Token has expired"] within [{"message":"Failed to authenticate because of bad credentials or an invalid authorization header.","status_code":401}].
Failed asserting that false is true.
```

But when test it via Postman, everything is fine

![image](https://cloud.githubusercontent.com/assets/1922652/8287309/2579c0d0-1939-11e5-809e-137df0919fef.png)

I'm using Laravel 5.1, PHP 5.6.10

Any idea? Thanks

**Comment by vugtis** [comment]
Have you checked your failed request using debugging tools? If the issue is missing authorization header, you need to enable rewrite module and adding authorization header to your config.
You might want to check this : https://github.com/tymondesigns/jwt-auth/wiki/Authentication

**Comment by ghprod** [comment]
hi @vugtis  .. thanks for your reply, actually i can reproduce that with postman, and i'm using nginx, but still when write test code, i'm unable to get same result with postman :(

any idea to write the test?

**Comment by tomschlick** [comment]
That message means the token is valid but it has expired so you need to regenerate a new one. You'll have to bake it into your test to generate a new token for each run.

**Comment by ghprod** [comment]
@tomschlick Yes, thats expired, but why when i test it its always return 

```
There was 1 failure:

1) AuthTest::testRestrictedAreaWithExpiredToken
Unable to find JSON fragment ["message":"Token has expired"] within [{"message":"Failed to authenticate because of bad credentials or an invalid authorization header.","status_code":401}].
Failed asserting that false is true.
```

Expected result must same with postman result :)

Thanks

**Comment by jasonlewis** [comment]
I'll play around with this and see what's up. Have you debugged it to the point where you can confirm that the header isn't being sent or you're not too sure yet?

**Comment by ghprod** [comment]
@jasonlewis 

seems like my header being lost after this line https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/CrawlerTrait.php#L677

Thanks :)

**Comment by jasonlewis** [comment]
Okay having a dig through the code it seems you may need to pass your headers in a little differently.

For more details refer to PHP docs: http://php.net/manual/en/reserved.variables.server.php
It mentions a couple of the headers but looking at the Symfony source I'd say you can send others should you need to so long as you prefix them with `HTTP_`.

Basically, you need to prefix any headers `HTTP_` and keep it all uppercase.

So, in your case, the headers would be as follows:

```php
$this->get('/api/users', [
    'HTTP_ACCEPT'        => 'application/vnd.'. env('API_VENDOR', '') .'.v1+json',
    'HTTP_AUTHORIZATION' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJzdWIiOjIsImlzcyI6Imh0dHA6XC9cL2xhcmF2ZWwtNS0xLmRldlwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6IjE0MzQ3MzkwODAiLCJleHAiOiIxNDM0NzQyNjgwIiwibmJmIjoiMTQzNDczOTA4MSIsImp0aSI6IjY1ODg5MDAwNzUyMzE5ODJkZWEzYTVlZTFlZDY5ZWNjIn0.OTAyNDI5NzRkMWMyYzY5ZWI2ZmZkNTIyYTJjMTY1NTAxMWNjYzdjZDQ5OTk1ZmUxMGIwZTU2M2ZiN2MxNGFkZQ',
    ])
    ->seeJson([
        'message'       => 'Token has expired',
        'status_code'   => 401,
]);
```

**Comment by ghprod** [comment]
@jasonlewis Thanks a lot.. its works now :+1:  :100:
