### ISSUE TITLE
Questions regarding JWT Authentication

### ISSUE THREAD

**Issue by JoeDawson** [dingo/api#478]
Hey!

Nice to see this package has now made it into 5.1 - currently working with JWT and am having a couple of issues I thought I'd ask.

### 1. Why does my user not stay authenticated?

I'll quickly explain as far as I've managed to get.

Currently, I have all - barring one - of my API routes protected. The only route that isn't protected is my `/login` route that allows for authentication (my API will be used to authenticate from a mobile application).

When the user makes a `POST` request to the above route with valid credentials, it returns the token. So I believe I've got everything right up to that point?

I have a few of other routes in my API which are `/venues`, `/entries` and `/me`

When attempting to make a `GET` request to any of the above - **after successfully logged in** - it gives me the following;

```json
{
    "message": "Failed to authenticate because of bad credentials or an invalid authorization header.",
    "status_code": 401
}
```

Looking at the headers, I can see that there is **no** authorization header - is there a reason why this is not set? After a bit of reading, I was made aware that sometimes Apache have a similar issue and have to add the following to their `.htaccess`

```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

Which I have done but still have no luck.

**The only way I can make the request, is if token is passed as a URL param - is this how I'm supposed to make future requests?**

### 2. How do I refresh the users token?

As I'm aware, by default the `tymon/jwt-auth` package by default allows up to 60 minutes before a token expires. I've added the the middleware as suggested to a `group` but it doesn't appear to refresh my token.

Here's my routes with the inclusion of the middleware.

```php
$api->version('v1', ['prefix' => 'api', 'namespace' => 'App\Http\Controllers\Api'], function ($api) {
	
	// Login
	$api->post('login', 'ApiAuthController@login');

	// Protected
	$api->group(['protected' => true, 'middleware' => 'jwt.refresh'], function($api) {

		// Logout
		$api->get('logout', 'ApiAuthController@logout');

		// Me
		$api->get('me', 'ApiAuthController@me');

		// Entries
		$api->resource('entries', 'ApiEntriesController', ['only' => ['index', 'show', 'update']]);

		// Venues
		$api->resource('venues', 'ApiVenuesController', ['only' => ['index', 'show']]);

	});

});
```

So if I was to make a GET request on `http://localhost.dev/api/me?token=myToken` where `myToken` is my expired token. It doesn't refresh?

---

I'd **really** appreciate any help here. I'm fairly new to API development and this is the first time Ive used the JWT package above so sorry if some of these questions come across is blindly obvious to you!

Thanks!

**Comment by catalinux** [comment]
Hi,

You are saying that you do not want to send your request with your token in query string of GET request. Where do you add your token for your request? Can you  give us your api call (from JS or what ever you use)

When you make a request http://localhost.dev/api/me?token=myToken (from wget for example)  what refresh do you expect to happen?

**Comment by JoeDawson** [comment]
@catalinux that's my question, how do I refresh the token? Is it a standard to pass the token as a URL param for every call?

I don't have any JS making requests right now, I'm just using Postman for the time being to make my calls.

![screen shot 2015-06-23 at 14 58 30](https://cloud.githubusercontent.com/assets/1009696/8307808/918923cc-19b8-11e5-89bb-3012ea14adea.jpg)

With the above call, the token passed hasn't yet expired - once it has, I get this - which I know is expected:

![screen shot 2015-06-23 at 15 00 43](https://cloud.githubusercontent.com/assets/1009696/8307836/c9c70286-19b8-11e5-8210-410f90774817.jpg)

It's at this point, I'm unaware what I'm supposed to do? It appears that the middleware to refresh the token (https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/RefreshToken.php#L30) is meant to set the `Authorization` header with the `$newToken` but it does not.

I'm just checking in to see why it may not?

Again, I'm new to to the usage of tokens with this package. Sorry if these come across as stupid questions.

**Comment by tymondesigns** [comment]
Hi Joe, 

> When the user makes a POST request to the above route with valid credentials, it returns the token. So I believe I've got everything right up to that point?

Sounds good to me.

> Looking at the headers, I can see that there is no authorization header - is there a reason why this is not set?

I believe you need to add this snippet to your apache `.conf.` file as apposed to the `.htaccess` to make it work.

> So if I was to make a GET request on http://localhost.dev/api/me?token=myToken where myToken is my expired token. It doesn't refresh?

The included refresh middleware is intended for a single use token flow, meaning it will not refresh the token transparently. 

See my comment here - https://github.com/tymondesigns/jwt-auth/issues/127#issuecomment-109747049

**Comment by JoeDawson** [comment]
Hey @tymondesigns, thank you very much for getting back to me.

Back in the office tomorrow so will get that added to the Apache config. Thanks for clearing that up :)

Will take on board your comment tomorrow also and implement 2 routes as suggested. Appreciate the help!

**Comment by ryanwinchester** [comment]
so how do we handle refreshes? i can't find documentation regarding that on either `dingo/api` or `jwt-auth`

**Comment by tkant** [comment]
@JoeDawson In Postman the Header you need to pass
Authorizaion : Bearer TOKEN_GOES_HERE
