### ISSUE TITLE
dingo/blueprint 0.1.* -> no matching package found.

### ISSUE THREAD

**Issue by tanshiqi** [dingo/api#480]
Hi,
When I try to update the package i got this error:

Problem 1
    - dingo/api dev-master requires dingo/blueprint 0.1.* -> no matching package found.
    - dingo/api dev-master requires dingo/blueprint 0.1.* -> no matching package found.
    - Installation request for dingo/api dev-master -> satisfiable by dingo/api[dev-master].

PS: my laravel version is 5.1

**Comment by kevindierkx** [comment]
Try setting the ```"minimum-stability"``` to ```dev``` in your laravel project.
The last time I've checked the dingo/blueprint package wasn't tagged and the above was required for composer to get the dev-master branch.

**Comment by Frankisgek** [comment]
You can also just add dingo/blueprint to your composer.json like this:
    "require": {
        "dingo/blueprint": "dev-master",
        "dingo/api" : "dev-master"
    }

**Comment by jasonlewis** [comment]
Avoid using `dev-master`. Simply use `0.1.*@dev` and `0.9.*@dev` respectively.

I've also just tagged a `0.1.0` for the `dingo/blueprint` repository.

**Comment by tanshiqi** [comment]
It works. Thanks so much
