### ISSUE TITLE
[L5.1] Outdated wiki needs updated sample working code

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#481]
Due to the outdated instructions in the wiki, can someone put a clear working sample code for others to be able to get up and running on Laravel 5.1 from the composer installation issues scattered all over, to setting up the routes/controllers? Just a simple dummy working sample code, like Laravel 5.1 docs do. It is hard for people to use this out of the box when they are new and docs are outdated.

As a side note - I was thinking it would be awesome if Laravel merged dingo as part of core at some point. Development would be hand in hand on every new Laravel push, which would mean Dingo would always be compatible with the latest version as it's part of core, and not have to play catch up after every new release. Laravel having a solid API as part of its core would make it a much more amazing and robust product. Any thoughts on this?

**Comment by tymondesigns** [comment]
I highly doubt dingo will ever be merged into laravel's core; for many reasons.

**Comment by lightvision** [comment]
The Dingo/Api for L5 is still in development. Everybody (I am not included) works to this project in their spair time, so wiki (I think) is not on the road map yet.

There was already some working code posted. You have to search for it. I know it's hard to find to closed isses but if anybody which tries dingo/api and fails open an issue for a missed configuration on its side then will become even harder to find the usage.
It's already hard for me to find where I give the answer (see https://github.com/dingo/api/issues/432)

@jasonlewis Please delete my post if you find offending for somebody

**Comment by jasonlewis** [comment]
I'm working on the docs now. Hopefully get it done by the end of the weekend or earlier.

I'm doubtful that this would end up in the core of Laravel. It'd be cool. But I doubt it.
