### ISSUE TITLE
are  any reference document about version .0.9.*?

### ISSUE THREAD

**Issue by dakiquang** [dingo/api#482]
Hi @all,

I'm at a loss because there are not any document about version 0.9.*

**Comment by jasonlewis** [comment]
I'm working on updating the docs now. You can still review the [Wiki](https://github.com/dingo/api/wiki) but keep in mind some things have changed. #398 is the main thread about all the changes although it's getting a little cluttered. I'll get the docs updated as soon as I'm able. :smile:

**Comment by dakiquang** [comment]
Hi @jasonlewis, 

Thank for your response. We are looking forward to new document about 0.9.*.
