### ISSUE TITLE
Disable pagination on internal request

### ISSUE THREAD

**Issue by lightvision** [dingo/api#483]
There is any way to disable pagination on internal request?

I need this because the results are shown in dataTables() and using pagination give me only a partial results to be displayed.

Or there is any other way to achieve this?

**Comment by bweston92** [comment]
On the API request have the controller check something like `limit` and if `limit=0` in the request input then tell the repository not to paginate results?

**Comment by jasonlewis** [comment]
Yeah I'd opt for something like what @bweston92 has suggested. I usually use that parameter to also limit the number of items per page. A limit of 0 indicates that the items should not be paginated.
