### ISSUE TITLE
Catch No query results for model ...

### ISSUE THREAD

**Issue by lightvision** [dingo/api#486]
I know that this is a dummy question, but how could I catch No query results for model in the ``show($id)`` method when the specified id doesn't exist in the database?

I've tried the following, but no luck:
```
public function show($id){
        try {
            $client = \Client::findOrFail($id);
        } catch (Illuminate\Database\Eloquent\ModelNotFoundException $exc) {
            dd($exc);
        }
}
```
And whithin the catch block I want to send a custom error response.

Any help appreciated.

**Comment by jasonlewis** [comment]
That should work what you've posted. You should be catching it before Dingo
gets the chance. If it's not catching it then try adding a leading
backslash to your type hint. Not sure if you're using namespaces or not.
You can also register a custom handler with the API exception handler, this
will handle the exception everywhere it's thrown in your API.

app('api.exception')->register()

Give it a callback and type hint the exception class.

**Comment by lightvision** [comment]
The error is not from leading backslash, tried with or whithout it. I will try to see if it works with custom exception handler and I will report back.

**Comment by jasonlewis** [comment]
Well you'll need to import that class or reference it's full namespaced
name if you're using it within your own namespaces.

I'll take a better look when I get back to my computer.

Is the exception being handled by the package? Can you catch it? Errors?

**Comment by lightvision** [comment]
On 27.06.2015 08:19, Jason Lewis wrote:
> Well you'll need to import that class or reference it's full namespaced
> name if you're using it within your own namespaces.
>
> I'll take a better look when I get back to my computer.
>
> Is the exception being handled by the package? Can you catch it? Errors?
>
> On Sat, 27 Jun 2015 15:18 Marius Ionel <notifications@github.com> wrote:
>
> > The error is not from leading backslash, tried with or whithout it. 
> I will
> > try to see if it works with custom exception handler and I will 
> report back.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dingo/api/issues/486#issuecomment-115962779>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dingo/api/issues/486#issuecomment-115963247>.
>
It is imported. No dummy errors even the question is dummy :)

**Comment by catalinux** [comment]
This is how I did it:

```php
    function destroy($id)
    {

        try {
            $result = $this->repository->delete($id);
        } catch (ModelNotFoundException $e) {
            $this->response()->errorNotFound('Resource not found');
        }


        return ['success' => true];

    }

**Comment by jasonlewis** [comment]
So what happens? Nothing?

**Comment by lightvision** [comment]
@catalinux Thanks, it's working. But how should I catch the same error in my controller that self consume my api?

**Comment by jasonlewis** [comment]
Refer to the other issue.

Response builder will always yield an `InternalHttpException`. Throw your own `HttpException` instances to catch them where you internally call your endpoints.
