### ISSUE TITLE
Latest commits breaks Request::segment(2)

### ISSUE THREAD

**Issue by lightvision** [dingo/api#487]
After a recent update Request::segment(2) returns me the segment of the route api instead of the app routes when the api is called internally.

**Comment by jasonlewis** [comment]
Post an example of what you mean. I'll be back at my computer later.

**Comment by lightvision** [comment]
Oops, ``Route::currentRouteName()`` gives me the wrong answer.

The answer is "api.admin.clients.index" instead of "admin.clients.index"

**Comment by jasonlewis** [comment]
Okay no worries there's a few fiddly things with the internal dispatcher.
Can you paste exactly what you're doing so I can easily recreate and write
tests for it when it's fixed. Where you're calling currentRouteName, how
you're calling the dispatcher, etc. As much info as you can.

**Comment by lightvision** [comment]
Excerpt from the controller that self cosumes my api:

```public function index() {
        # nothing fancy here, just fetch the $clients through api internal request
        # and pass them to the view
        $clients = $this->apiDispatcher
                ->version($this->apiVersion)
                ->get(\Config::get('api.prefix') . '/admin/clients', $this->apiRequestParams);
        
        return view('admin.clients.index', ['clients' => $clients]);
    }
```

Excerpt from ``admin.clients.index`` view:
```
<li class="{{ Request::segment(2) == 'clients' ? 'active' : '' }}"> <a href="javascript:void(0)"><i class="fa fa-bar-chart-o fa-fw"></i> Clients<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li class="{{ Route::currentRouteName() == 'admin.clients.index' ? 'active-item' : '' }}">
                <a href="{{ route('admin.clients.index',[],FALSE) }}">List clients</a>
            </li>
            
            <li class="{{ Route::currentRouteName() == 'admin.clients.create' ? 'active-item' : '' }}">
                <a href="{{ route('admin.clients.create',[],FALSE) }}">Add client</a>
            </li>
        </ul>
        <!-- /.nav-second-level --> 
    </li>

```

Basically 'Route::currentRouteName()' should return the `admin.clients.index` but it returns `api.admin.clients.index`.

The code before was working before, even in L4 ;)

**Comment by jasonlewis** [comment]
Define before? Can you give an exact commit. I know it worked in L4 but a
lot has changed since then in terms of how routes are handled. It should be
an easy fix though I hope.

Also, FYI, a very recent commit will automatically add the prefix you
define in your config to internal requests if you don't specify it. So you
can remove that config call.

**Comment by lightvision** [comment]
On 771f81d commit was working.

Regarding the prefix, I've read this. It is put there because I don't want to change my controllers in case that my boss wants the public api to be with prefix and I have an 1:1 mapping between app routes and api routes, so admin.clients.index coresponds to api.admin.clients.index

**Comment by lightvision** [comment]
Fixed:

I catch the \Dingo\Api\Exception\InternalHttpException in the controller I've made internal request.

Not an ellegant way since dingo api should thrown errorNotFound and not InternalHttpException.

@jasonlewis any sugestions on this?

**Comment by jasonlewis** [comment]
It's only supposed to throw the `InternalHttpException` when the returned response is non-successful, i.e., any 4xx response.

You should be able to simply throw an exception from your API controller and it'll be re-thrown for internal requests. However, looking at the source, it's not doing that. I'll resolve that. If you'd like a not found exception to be thrown then you'll have to manually throw it yourself.

You can catch the `InternalHttpException` though and deal with that as you would normally. There's a `getResponse` method that allows you to get the actual response so you can inspect it further and take any action necessary.

**Comment by jasonlewis** [comment]
Okay resolved. You can throw exceptions from your controllers (you were supposed to be able to) and they'll be dealt with properly on regular API calls, however, internal calls the exception will fall through and you'll be able to catch and deal with it accordingly.

The reason the response builder methods behave differently is because they return an actual error response instance. They don't throw an exception. So the dispatcher simply throws a generic `InternalHttpException` that you can catch and deal with.

Hope this helps!

In regards to your other issue... Is it persisting? Is `currentRouteName` behaving as expected or no?

**Comment by jasonlewis** [comment]
Going to have to change things up a bit so that you can retrieve details regarding the current route and request as the Laravel router uses a hard-coded property instead of container instances.

**Comment by lightvision** [comment]
Thanks, I will keep an eye again since I'm back from holiday :)

**Comment by jasonlewis** [comment]
I've created issue #520 so I can properly keep track of it.
