### ISSUE TITLE
Cannot install from composer.

### ISSUE THREAD

**Issue by sicaboy** [dingo/api#489]
Hey guys, I failed to install api. Anyone can help with these?
According to the wiki, I tried the following command:
![qq20150627-1](https://cloud.githubusercontent.com/assets/2426114/8391969/c58239aa-1d1b-11e5-8ce5-e7dff5e7d583.png)

Then I tried by removing the version:
![qq20150627-2](https://cloud.githubusercontent.com/assets/2426114/8391971/e83ebcfc-1d1b-11e5-8a4d-b36594e8a697.png)
    - Installation request for laravel/framework == 5.0.33.0 -> satisfiable by laravel/framework[v5.0.33].

**Comment by vugtis** [comment]
Have you add this on composer.json? 
```sh
"minimum-stability": "dev"
```

**Comment by GrahamCampbell** [comment]
You can't use this with laravel 5.0.

**Comment by jasonlewis** [comment]
Looks like it's trying to install for 5.0 because you didn't specify the version. You'll need to either set your `minimum-stability` above or use `0.9.*@dev`, not sure you can do that via the command line though.
