### ISSUE TITLE
Serializer never reach item function

### ISSUE THREAD

**Issue by vugtis** [dingo/api#491]
Hi again,
I found this few days ago. When I am serializing my "collection", it works perfectly, but when I serialize an "item", it will throw an error.
Here is what I found from my digging.

On SerializerAbstract class (Fractal package), item function 2nd argument force the $data to be array. But since I return an item, it throws and error cause it needs an array.

Then I try to wrap my result item in an array. Okay, the error disappeared. But I think that cause the binding on Dingo\Api\Http\Response function item() to fail.
When I do my request, it returns my result as collection, not an item.
Here is the code I use  :
```sh
$this->response->item($result,new NullTransformer); 
```
 Here is my serializer :
```sh
    public function collection($resourceKey, array $data)
    {
        return array('Result' => 'OK' , 'Records' => $data);
    }

    public function item($resourceKey, $data)
    {
        return array('Result' => 'OK' , 'Record' => $data);
    }
```
It should return 'Record' , but instead it return 'Records'. This is tricky to test because on the existing DataArraySerializer, both item and collection function return the same thing.

Then I fix it the hard way. I modify SerializerAbstract class to remove array restriction on item function. It works, but I didn't like it since it means I need to change this everytime I update the package. I know Fractal is 3rd party package, but it might be nice if dingo package can modify the binding so we don't need to remove array restriction on item function on Fractal package.

**Comment by jasonlewis** [comment]
Hm, you shouldn't need to remove the `array` type-hint in the abstract class. An item is still an array. It's just not a multi-dimensional array.

I just tested this with the standard `DataArraySerializer` and returning both a collection and item work fine. What is `$result`? Is it an object or an array? Does your `NullTransformer` return an array that can be used by the serializer?

**Comment by vugtis** [comment]
I just tried again. I tried both returning Object and Array
Case A :
I use  ```$result = $this->model->where('_id', '=', $id)->get()``` ,
$result is :
```
Collection {#554 ▼
  #items: array:1 [▼
    0 => MyModel{#559 ▶}
  ]
}
```
and ```$this->response->item($result,new NullTransformer);``` gives unserialize data. I tried using ```dd(1)``` in both item and collection in DataArraySerializer, and the code didn't reach there.
If I use ```$this->response->collection($result,new NullTransformer);```, it gives correct serialized data, but it goes through collection function on DataArraySerializer. What I need is the item function.

Case B:
I use  ```$result = $this->model->where('_id', '=', $id)->get()->first()``` ,
$result is :
```
MyModel {#559 ▼
  #table: "MyModel"
  #fillable: array:4 [▶]
  ...etc...
}
```
and ```$this->response->item($result,new NullTransformer);``` gives ```Argument 2 passed to League\Fractal\Serializer\DataArraySerializer::item() must be of the type array, object given```

then I try ```$this->response->item(array($result),new NullTransformer);```. It gives ```{"Result":"Error","Message":"get_class() expects parameter 1 to be object, array given"}```

Note: My NullTransformer actually didn't do anything. The transform function just return the data as it is. I use that because 2nd argument on item and collection function in Response\Factory isn't optional. If I don't specify anything. It will throw an error.

**Comment by jasonlewis** [comment]
I'm sorry for the late reply. I'm still not sure I follow what your problem is here. I know something is working how you want it, but it sounds like you're trying to do something that isn't meant to be done.

Your transformer MUST return an array. That is a must. You're transformer is no doubt receiving an object (from Eloquent), that object must return a valid PHP array. Only then will the serialization work correctly.

**Comment by vugtis** [comment]
I hope this case below is clear enough :

My Serializer :
```
    public function collection($resourceKey, array $data)
    {
        return array('Result' => 'OK' , 'Records' => $data);
    }
    public function item($resourceKey, $data)
    {
        return array('Result' => 'OK' , 'Record' => $data);
    }
```
My NullTransformer :
```
class NullTransformer extends TransformerAbstract
{
    public function transform($data)
    {
        return $data;
    }
}
```
Query :
```
$result = $this->model->where('_id', '=', $id)->get();
$this->response->item($result,new NullTransformer);
```
What I expect from Query :
```
{"Result":"OK","Record":[{"_id":"559243abe78cf1cc55000029","sender":"user1","recipient":"admin","type":"Memo","message":"Message","status":"Unread","updated_at":"2015-06-30 14:22:19","created_at":"2015-06-30 14:22:19"}]}
```

What I got :
```
{"memos":[{"_id":"559243abe78cf1cc55000029","sender":"user1","recipient":"admin","type":"Memo","message":"Message","status":"Unread","updated_at":"2015-06-30 14:22:19","created_at":"2015-06-30 14:22:19"}]}
```

If I use $this->response->collection instead of $this->response->item, everything is correct except it uses 'Records' as the key instead of 'Record'.

**Comment by jasonlewis** [comment]
In your transformer return $data->toArray() and see if that helps.

**Comment by vugtis** [comment]
It didn't work.

**Comment by jasonlewis** [comment]
My only other suggestion would be to not use Fractal. From the looks of it
all you want to do is wrap a collection of models differently to a single
model. Take a look at the docs on implementing a custom formatter. You can
replaces the JSON formatter with your own that does this.

**Comment by vugtis** [comment]
Well, thank you for the suggestion. I'll take a look at it. Or I might stay at removing array type hint on fractal since it worked quite well. I just hope something could be done, but it's okay I think. Thank you for your time.
