### ISSUE TITLE
[L5.1] Transformer rendering blank

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#492]
I've setup everything as it should be for the response to return a collection transformation, but it just renders a blank page, no data what so ever. I have debug turned on but no errors show up. I am not sure if it has to do with this line not being in:

https://github.com/dingo/api/wiki/Transformers#register-a-transformer-for-a-class

Not sure where that should go, I had an old and working version of fractal that I used, but removed it so dingo uses it's lower compatible version. Any idea where that line goes or how to proceed to get the data?

**Comment by jasonlewis** [comment]
I'll clarify that line in the documentation a bit.

Usually you'd register the transformer for the class in your bootstrap file. Basically, all it's saying is when an instance of the `User` model is returned we want the `UserTransformer` to be used.

So anywhere where you return the `User` model it'll be transformed with the `UserTransformer`.

Can you paste some examples of what you're trying to do. It could well be something else.

**Comment by MovingGifts** [comment]
Yup sure, so here is where I am a little confused. I was able to get the data, but not using what the documention is showing, maybe you can explain a little what I am doing wrong, or not understanding about the not working document part or benefit of using it as opposed to the working data method from my previous fractal version file below.

So this is what I used when it was not working in the UserTransformer.php (which I found here in the docs https://github.com/dingo/api/wiki/Transformers#custom-transformation-layer):
    
    use Illuminate\Http\Request;
    use Dingo\Api\Transformer\Binding;
    use Dingo\Api\Contract\Transformer\Adapter;

    class UserTransformer implements Adapter
    {
        public function transform($response, $transformer, Binding $binding, Request $request)
        {
            // Make a call to your transformation layer to transformer the given response.
            // Not sure if the return here is what you mean as it just renders a blank page..
            return [
                'id'    => (int) $user->id,
                'name'  => $user->name
            ];
        }
    }

That rendered a blank page, but my previous fractal version renders data correctly:

    use App\User;
    use League\Fractal\TransformerAbstract;

    class UserTransformer extends TransformerAbstract
    {
        public function transform(User $user)
        {
            return [
                'id'           => (int) $user->id,
                'name'         => $user->name
            ];
        }
    }

**Comment by jasonlewis** [comment]
Okay you're getting a bit muddled here. That contract you're implementing
is for a transformation layer. Fractal is a transformation layer. You don't
need to worry about that contract. Just use Fractal as is described in the
Fractal documentation. I'll take a look at the docs to clarify it but I do
mention at the top the terminology that will be used. It is a tad confusing
though.

**Comment by MovingGifts** [comment]
Oh makes sense, yeah that confused me. I think if it's worded something like you can use the fractal as is described in their docs or implement your own version instead using this (code below).

Either way, thank you for clearing it up so quickly and thank you for all your hard work on this amazing plugin! You're awesome dude!

**Comment by jasonlewis** [comment]
Cheers! And thank you for using it. :)
