### ISSUE TITLE
Named routes (Lumen 5.1, Dingo 0.9.*)

### ISSUE THREAD

**Issue by camilstaps** [dingo/api#493]
I've recently started to rewrite my current code based on the Dingo API to work with Lumen 5.1 instead of Laravel 5.1. I'm using Dingo 0.9.*. My full current code can be found at https://github.com/Botleagues/API/tree/lumen.

On Laravel 5.1, I could use `route('user.show')` to get the `UserController@show` route, which I defined as

    $api->resource('user', 'CamilStaps\BotleaguesApi\Controllers\UserController',
        ['only' => ['index','show','store'],
         'names' => [
             'index' => 'user.index',
             'show' => 'user.show',
             'store' => 'user.store'
        ]]);

This doesn't seem to work in Lumen. I'm getting an error,

    Route [user.show] not defined.

Is there a way to use named routes in Lumen / are there plans to implement this?

I'm using this with POST / store requests. After storing a resource, I want to reply with 201 CREATED but also send a Location header with the GET / show URL. This is the code I'm using for that (from UserController.php):

	if ($this->user->save()) {
		return $this->response->created(route('user.show', $this->user->email));
	} else {
		throw new \Dingo\Api\Exception\StoreResourceFailedException;
	}

**Comment by jasonlewis** [comment]
Aye, I need to cover this in the documentation. It's on my todo list. The package has it's own URL generator. I'll need to create some helper methods to make these easier to use but for now you can do it like so...

```php
app('api.url')->version('v1')->route('user.show');
```

You must specify the version for it to work.

---

I've just pushed an update that fixes a couple issues with generating URIs in Lumen. Should be good to go now. :+1:

**Comment by camilstaps** [comment]
@jasonlewis thanks for the quick response. (On my installation) this seems to work for `*.index` routes alone, not for for example `user.show`. I did some testing and it seems that this closure from `ApiServiceProvider@boot` is never executed:

    $this->app->rebinding('api.routes', function ($app, $routes) {
        var_dump($routes);
        $app['api.url']->setRouteCollections($routes);
    });

When I do a `var_dump(app('api.url'))`, I only see (all the) `*.index` routes, not others.

This is a relatively clean install (that is, I installed Lumen yesterday and the only package that is there is the one I'm developing myself - link above -, which depends only on Dingo/API and Illuminate/Support. 

Any ideas?

**Comment by camilstaps** [comment]
It seems the only usage of `api.routes` is in `ApiServiceProvider@boot` and `Router@setAdapterRoutes`. The only usage of the latter is in `Cache@handle`, so if I'm not mistaken something's missing there. Although they could be used indirectly (where simple grep doesn't help). Obviously, you know the internals better than I.

**Comment by camilstaps** [comment]
@jasonlewis any ideas? (Sorry to buzz you if this is still on a todo list somewhere, wasn't sure if this just takes some time or this issue got forgotten because it's closed now)

**Comment by jasonlewis** [comment]
I'll reopen as a reminder. Sorry must've gotten lost. Cheers for the bump.

**Comment by jasonlewis** [comment]
Okay this should be fixed now. Remember, if you have a prefix, and you're using `resource` then the names will be `prefix.resource.method`.

**Comment by jasonlewis** [comment]
Wait, I'll leave this open until I can get a confirmation all is well.

**Comment by camilstaps** [comment]
Works like a charm, thanks a lot!
