### ISSUE TITLE
Accept header could not be properly parsed because of a strict matching process

### ISSUE THREAD

**Issue by dharmendrajadon** [dingo/api#494]
It is asking for accept header on all routes
local.ERROR: 400 - exception 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException' with message 'Accept header could not be properly parsed because of a strict matching process.' in /home2/bhuvamka/public_html/apcivilsupplies.com/protected/vendor/dingo/api/src/Http/Parser/Accept.php:66

**Comment by jasonlewis** [comment]
If you've got `strict` mode enabled then you won't be able to access your API via your web browser. You'll need to pass a valid accept header through either Postman or by using cURL from your console.

**Comment by dharmendrajadon** [comment]
Yes, I know! But my normal Routes are not working. "Accept header could not be properly parsed", even on webpages too.
$api = app('api.router');
$api->version('v1',['namespace' => 'App\Http\Controllers', 'protected' => true, 'prefix' => 'api'], function ($api) {
    $api->post('oxybiometric', 'Restcontroller@index');
});

**Comment by jasonlewis** [comment]
Ah I see! Roger, I shall re-open and investigate then.

**Comment by jasonlewis** [comment]
Can you run `composer update` and confirm all is well?

**Comment by dharmendrajadon** [comment]
It's working perfect. Thank You

**Comment by dharmendrajadon** [comment]
When do we expect Facade and stable version?

**Comment by jasonlewis** [comment]
Both hopefully soon. Still ironing out a few bugs as people stress test more things.
