### ISSUE TITLE
Trouble using response()->paginator - results aren't paginated.

### ISSUE THREAD

**Issue by jayhealey** [dingo/api#497]
I'm attempting to use the `paginator` response on a collection, but it's not paginating the results. 

Here's the code:

```
$paginator = new LengthAwarePaginator($performances, $performances->count(), 5, 1);

return $this->response()->paginator(
  $paginator,
  new PerformanceCollectionTransformer()
);
```

The `data` attribute contains all of the results, and whilst `meta` attribute data looks fine, the `total` is the same as `count`:

```
meta: {
  pagination: {
    total: 142,
    count: 142,
    per_page: 5,
    current_page: 1,
    total_pages: 29,
    links: {
      next: "/?page=2"
    }
  }
}
```

Am I missing anything here?

**Comment by jasonlewis** [comment]
Looking at the source of Fractal and Laravel I'd say that's what's to be expected with what you've passed in.

https://github.com/thephpleague/fractal/blob/master/src/Pagination/IlluminatePaginatorAdapter.php#L80
https://github.com/illuminate/pagination/blob/master/AbstractPaginator.php#L408

**Comment by jasonlewis** [comment]
Usually when manually constructing a paginator instance you're required to slice the items beforehand.

**Comment by jayhealey** [comment]
Ah, fair enough. I'll do that then - cheers.

**Comment by bweston92** [comment]
@jayhealey what's wrong with using `Illuminate\Pagination\Paginator` it will automatically slice for you.

https://github.com/laravel/framework/blob/5.1/src/Illuminate/Pagination/Paginator.php#L64

**Comment by lightvision** [comment]
@bweston92 In order to be compatible with dingo/api you must use LenghtAwarePaginator (because Fractal needs it). So simple pagination is out of discussion.

Digging further, you need to create LenghtAwarePaginator instance on your own if you want to disable pagination for your ow internal requests to your api.

**Comment by bweston92** [comment]
I don't see why Fractal has done that, both provide the same information. Anyhow will have to remember this one.

**Comment by lightvision** [comment]
Do a dd() of a resource with both paginator methods and see the results.

Also check http://laravel.com/docs/5.1/pagination.

Pay attention to `Additional Helper Methods`. By default Laravel will paginate using LenghtAwarePaginator in L5.1, so it's not the fault of dingo/api or fractal. They had to obey.
