### ISSUE TITLE
Unable to test API controllers. (PhpUnit)

### ISSUE THREAD

**Issue by revengel** [dingo/api#498]
Hi! I'm trying to test the API Controller's functionality. I find some method to do this.

```
$response = $this->action('POST', 'UserController@auth',  [
      'username' => 'user',
      'password' => 'user',
]);
```

But I received the follow error:

```
1) Vendor\Site\Controllers\Api\UserController\UserControllerTest::testAuth
InvalidArgumentException: Action Vendor\Site\Controllers\Api\UserController@auth not defined.
```

Are there some other ways to test this functionality? Thanks.

**Comment by catalinux** [comment]
first you need to tell us wheather you use Lumen or Laravel. I was able to test like this
```php
class ExampleTest extends TestCase {

    public function testBasicExample()
    {
        $response = $this->call('GET', '/');

        $this->assertResponseOk();
    }

}

**Comment by revengel** [comment]
I use Laravel 5.1. Do I can test controller dirrectly (without Route calling)? Thanks for ur answer.

**Comment by jasonlewis** [comment]
You can't call the routes with their action or name from tests.
