### ISSUE TITLE
[L5.1] Custom Request Class

### ISSUE THREAD

**Issue by Exelord** [dingo/api#499]
Hi,
I use own Custom Request class which is extended of illuminate\http\Request. And when I install dingo/api package my methods are "not found". Is the way to fix that? When I add my functions to yours Dingo\Api\Http\Request every things works OK, but I think its no correct solution.

**Comment by jasonlewis** [comment]
I'm guessing they're only not found for API requests. This package also utilizes it's own request class which you've seen. I might be able to tweak a few things so you can also extend this request class and then allow it to be rebound.

**Comment by Exelord** [comment]
OK, so I done something like this:

```
<?php

namespace App\Http;

use Dingo\Api\Http\Request as BaseRequest;
//use Illuminate\Http\Request as BaseRequest;
use Event;
use App\Events\RequestFalse;

class Request extends BaseRequest {

	public function __construct() {
		parent::__construct();
	}

	/**
	* Get a subset of the required items from the input data.
	*
	* @param  array  $required
	* @return array
	*/
	public function required($required, $notEmpty = true)
	{
			$status = true;
			$credentials = $this->only($required, $notEmpty);

			foreach ($required as $key => $req)
					if(!isset($credentials[$req])) $status= false;

			if($status)
					return $credentials;
			else
					return abort(411, trans('engine.no_required_credentials'));
	}
}
```

and then I also seeing 

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Dingo\Api\Http\Request::required()'
```

**Comment by jasonlewis** [comment]
The latest master has been updated to allow you to register a custom request class.

All you have to do is simply update the contract alias.

For example:

```php
app()->alias('YourCustomRequest', 'Dingo\Api\Contract\Http\Request');
```

Your custom request class should extend the `Dingo\Api\Http\Request` class, or simply implement the `Dingo\Api\Contract\Http\Request` interface and define the `createFromIlluminate` method. However, best to just extend, saves implementing it.
