### ISSUE TITLE
[Internal Request] Distpatcher to return transformed data

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#500]
I've setup an API end point and trying to use a regular route to return the transformed data, but only the pre-transformed data is returned by the dispatcher. Is there a way to return the transformed api data with the dispatcher?

**Comment by jasonlewis** [comment]
Can you please run `composer update` and try using the fixed `raw` method.

```php
$response = app('api.dispatcher')->raw()->get('users');
```

You should then be able to use the `getContent` method on the response object to get what you need. Note that this will be JSON.

**Comment by MovingGifts** [comment]
Yup works flawlessly now! Thanks for the quick fix!

**Comment by fbnigha** [comment]
Can you add a new function that will return the data that we expect without having to chain raw(), then call getContent() on that data, then call json_decode() on that data?

Imagine that I am creating an API call that calls another API call, currently I seem to have to do this to get the transformed data that I get when I call my 'userinfo' route externally.

```
        $response = $this->api->be(auth()->user())->raw()->get('userinfo');
        return [
            'token' => $token,
            'user' => json_decode($response->getContent())
        ];
```
