### ISSUE TITLE
Install dingo api on laravel 5

### ISSUE THREAD

**Issue by SnehalAmbab** [dingo/api#502]
Hello,

I would like to install dingo api on laravel 5.0

But its giving some error as

"Your requirements could not be resolved to an installable set of packages."

Please help me out.

**Comment by catalinux** [comment]
To install this package you will need:

Laravel 5.1+ or Lumen 5.1+
PHP 5.5.9+

**Comment by SnehalAmbab** [comment]
@catalinux can I do it on laravel 5.0?

**Comment by catalinux** [comment]
I do not think it should work. You might try put these dependencies, but you should upgrate your app to 5.1, as 5.0 has no LTS (Long Time Support)
     "illuminate/auth": "5.1.*",
        "illuminate/cache": "5.1.*",
        "illuminate/events": "5.1.*",
        "illuminate/database": "5.1.*",
        "illuminate/pagination": "5.1.*",
        "illuminate/console": "5.1.*",
        "illuminate/filesystem": "5.1.*",

**Comment by jasonlewis** [comment]
There's no support for 5.0. You'll need to upgrade to 5.1 should you want
to utilize the package.
