### ISSUE TITLE
[L5.1] Transformed relational data not returned

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#503]
I'm confused on how to return a post's comments paginated with dingo. Here is what I tried:

    class CommentController extends BaseController
    {
        public function index($postId)
        {
            // This works but not using transformers.
            $post = Post::find($postId);
            $comments = $post->comments;
            return $comments;

            // This doesn't work. Returns blanks page.
            $post = Post::find($postId);
            $comments = $post->comments->paginate(10);
            return $this->response->paginator($comments, new CommentTransformer);
        }
    }

Any idea how to get the transformed comments of that post? I also tried to return it as a collection via the response method without the paginate but I just got the same blank page.

Note: I'm trying to do it without includes, because I don't want to display the post data with the nested comments, just purely the comments without the post data.

**Comment by jasonlewis** [comment]
Are you using Lumen? Can you check your error logs to see if there's something weird happening. Make sure you check both the PHP and Lumen/Laravel error logs.

**Comment by MovingGifts** [comment]
Totally my fault, I had an error in my CommentTransformer on L5.1 that only showed up after I manually emptied my laravel.log! Not sure why it was returning blank until I emptied the log, but it's working perfectly now. Thanks for your suggestion Jason!
