### ISSUE TITLE
Cannot register two routes matching "/api/users" for method "GET"

### ISSUE THREAD

**Issue by oriceon** [dingo/api#504]
I try to use this package (dingo/api": "0.9.*) on lumen 5.1 and get a BadRouteException

`Cannot register two routes matching "/api/users" for method "GET"`

in routes i have

~~~php
$api = $app['Dingo\Api\Routing\Router'];

$api->version('v1', function ($api) {
    $api->get('users', 'App\Http\Controllers\v1\UserController@show');
});

$api->version('v2', function ($api) {
    $api->get('users', 'App\Http\Controllers\v2\UserController@show');
});
~~~

and in .env i have
~~~
API_VERSION=v1
API_PREFIX=api
API_CONDITIONAL_REQUEST=true
API_STRICT=false
API_DEBUG=true
API_DEFAULT_FORMAT=json
~~~

Where i`m wrong?
Thanks.

**Comment by jasonlewis** [comment]
I have a fix pending for this I just need to tidy up tests. Sorry about the delay, I got a bit distracted.

**Comment by jasonlewis** [comment]
All fixed now. Run `composer update` to grab the latest version.

**Comment by oriceon** [comment]
Thanks. I confirm now is workin`
