### ISSUE TITLE
Factory::setTransformer() is undefind

### ISSUE THREAD

**Issue by vanntian** [dingo/api#506]
$app['Dingo\Api\Transformer\Factory']->setTransformer(function ($app) {
    return new Dingo\Api\Transformer\Adapter\Fractal(new League\Fractal\Manager, 'include', ',');
});

**Comment by jasonlewis** [comment]
Sorry the method is setAdapter. If it's still setTransformer in the docs
can you make an issue on Dingo/api-docs please? Cheers.

**Comment by vanntian** [comment]
@jasonlewis and transform is not work

public function index()
    {
        $categories = Category::all();

        return $this->collection($categories,new CategoryTransformer);
    }

public function transform(Category $category)
    {
        return [
            'id' => $category->id,
            'name' => $category->name,
            'sort' => $category->sort,
            'is-show' => $category->is_show
        ];
    }
![default](https://cloud.githubusercontent.com/assets/10600430/8510979/2ac9edde-2335-11e5-8df5-38a84e565db6.PNG)

**Comment by jasonlewis** [comment]
Far as I can tell that looks correct and should be working fine.

**Comment by vanntian** [comment]
@jasonlewis thank you,i switched to api-response,it works fine
