### ISSUE TITLE
Lumen Sample Project

### ISSUE THREAD

**Issue by nickrouty** [dingo/api#509]
Hello,

I'm pretty new to Laravel/Lumen and even newer to this package. Does anyone have a sample project that they could share that utilizes this package with Lumen? Preferably one that incorporates some of the more advanced features of this package such as the auth (JWT Token) configuration, etc.

Thanks!

**Comment by nickrouty** [comment]
Does JWT auth package even work with Lumen? Going through their configuration it asks you to publish config, which Lumen doesn't seem to support. Anyone with prior experience here would be appreciated, trying not to waste time :)

**Comment by catalinux** [comment]
@nickrouty , yes it works. Publisihing is a simple copy of a config file. You need to create your own jwt config fille in config folder, and have a CustomJWTAuthServiceProvider to ask for it

```php
<?php

namespace App\Providers;

use Tymon\JWTAuth\Providers\JWTAuthServiceProvider;

/**
 * All we do here is forcing the JWTAuthServiceProvider to take
 * our custom config as the only config (force Lumen compatibility,
 * basically).
 */
class CustomJWTAuthServiceProvider extends JWTAuthServiceProvider
{
    /**
     * Boot the service provider.
     */
    public function boot()
    {
        $this->app['config']->set('jwt', require realpath(__DIR__ . '/../config/jwt.php'));

        $this->bootBindings();

        $this->commands('tymon.jwt.generate');
    }
}
```
Lumen is a thin App with Laravel Core that has not all the features of Laravel, so it will help you learn very well how Laravel/Lumen works. For example, publishing  feature, its a simple copy of a file

**Comment by nickrouty** [comment]
@catalinux Awesome - thanks for your help. Now I'm trying to configure it with dingo/api. The auth page seems to leave out some details for someone that is very new to the framework. For example, what file the code needs to be added to, and I'm guessing that there will be a slight difference from what it instructs since I had to create this customer provider?

**Comment by nickrouty** [comment]
I went ahead and switched over from Lumen to a fresh install of Laravel 5.1 - everything went smooth this time. I had initially switched from LV5 to Lumen, but I think there were some lingering issues with my upgrade from LV5 to LV5.1 that were causing my problems with using laravel in the first place.
