### ISSUE TITLE
API router instance - Laravel vs Lumen

### ISSUE THREAD

**Issue by riglar** [dingo/api#511]
Hi all,

I ran into issues when following this page with Laravel 5.1:
https://github.com/dingo/api/wiki/Creating-API-Endpoints

I spent ages trying to get this to work, but kept seeing method 'app' not defined.
`$api = $app['Dingo\Api\Routing\Router'];`

After hunting through the issues log it seems I actually have to use this..
`$api = app('api.router');`

Can anyone explain what the different is and why the top one doesn't work?

Many thanks,
Tom

**Comment by riglar** [comment]
Please can someone comment on this? I'm still confused by what is going on here.

Thanks,
Tom

**Comment by jasonlewis** [comment]
I'll update the docs. It's older Laravel 4 stuff where the application instance was available in the routes file. Use the `app` function like you are now.

Either of these methods is fine:

```php
$api = app('Dingo\Api\Routing\Router');

$api = app('api.router');
```

**Comment by riglar** [comment]
Ah, I see. Never used L4. Thanks Jason.
