### ISSUE TITLE
JWT with dingo api laravel 5.1

### ISSUE THREAD

**Issue by SnehalAmbab** [dingo/api#512]
Hello,

I am building an api for user login with JWT

I got token after login.

Is there any way that I can get authenticated user details?

Also I would like to protect my API's with access token plus user_id.

How can I do that?

**Comment by catalinux** [comment]
As @jasonlewis  stated in https://github.com/dingo/api/issues/510 , you could use in a controller ,that uses Helpers trait ,$this->user()  

Read more https://github.com/dingo/api/wiki/Authentication

**Comment by jasonlewis** [comment]
Hopefully the documentation covers all this for you. I'm a bit unsure on what you mean by also protecting by the `user_id`, care to elaborate?

**Comment by tymondesigns** [comment]
The user id exists within the subject claim of the token. This is what's then used to retrieve the authenticated user, accessible via `$this->user()` from the Helpers trait
