### ISSUE TITLE
explicitly expire token JWT

### ISSUE THREAD

**Issue by SnehalAmbab** [dingo/api#513]
Hello,

How can we explicitly expire the previous token on re-login or logout functionality?

Please let me know as soon as possible.

**Comment by catalinux** [comment]
The JWT protocol does not have a mechanism of expiring. It has a machanism of blakclisting, and https://github.com/tymondesigns/jwt-auth/wiki has this kind of mechanism

**Comment by SnehalAmbab** [comment]
@catalinux Can you please provide me some demo code for it?

**Comment by catalinux** [comment]
@SnehalAmbab that is the only code you need to. Having a token, you could invalidate. You could get that throug GET.

```php
 function deleteToken()
    {

        $data = Input::all();
        $token = $data['token'];
        \Tymon\JWTAuth\Facades\JWTAuth::invalidate($token);

        return json_encode(['response' => 'success']);
    }

**Comment by SnehalAmbab** [comment]
@catalinux I want to expire previous token on login.

How can we get previously assigned token to a user?

**Comment by catalinux** [comment]
I am not sure if there is any mechanism implemented on jwt-auth library. How you could do that depends on why you need that.

For instance in the validation process of the token you could check some info you put in the body of your token (for example token_creation), against a database where you have "last time token creation"

**Comment by jasonlewis** [comment]
You'd probably need to keep a running record of tokens assigned to a user and expire them if they're old or inactive.

Doesn't seem specific to this package. Going to close.
