### ISSUE TITLE
Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable.

### ISSUE THREAD

**Issue by wind930** [dingo/api#514]
hi 

###  i 'm coding one step by setp on the wiki

[Configuration](https://github.com/dingo/api/wiki/Configuration)
[Authentication](https://github.com/dingo/api/wiki/Authentication)
> 
Authentication Providers
By default only basic authentication is enabled. Authentication is covered in more detail in a later chapter.
You must configure this in a published configuration file or in your bootstrap file.
>
```php
$app['Dingo\Api\Auth\Auth']->extend('oauth', function ($app) {
   return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
});
```

---

### when i add the code which above in to bootstrap/app.php file
but got some error. who can tell me why?

```php
Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable.' in /Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php:744 
Stack trace: 
#0/Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\Container\Container->build('Dingo\\Api\\Contr...', Array) 
#1 /Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Dingo\\Api\\Contr...', Array) 
#2 /Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Foundation\Application->make('Dingo\\Api\\Contr...')
#3 /Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) 
#4 /Users/apple/wind/ in /Users/apple/wind/site/laravelProject/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 744
```

**Comment by lookapanda** [comment]
I'm getting this too. Help pls.

**Comment by tonyfunc** [comment]
I am as well getting this error! Can someone please help?

**Comment by jasonlewis** [comment]
I'll take a look at this today.

**Comment by tonyfunc** [comment]
I found the solution.

In your app/routes.php, add following followed by your endpoints...

```php
$api = app('api.router');
```

**Comment by wind930** [comment]
@tonyfunc you are right，the author has Responsed here https://github.com/dingo/api/issues/398

**Comment by jasonlewis** [comment]
Sorry, I should probably clarify the documentation a bit here. If you're using Laravel 5 you should do it in the configuration file. If you wanted to do it in a bootstrap file in Laravel you'd need to create a service provider and do it there in the `boot` method.

If you're using Lumen you can use the `bootstrap/app.php` file.

I'll clarify the documentation on this as I can see how it can be misleading.

**Comment by phpguru** [comment]
I am getting this error in a Laravel 5.4 project. I'm on Mac Sierra PHP 7.0.21 PHPunit 6.1.4 using Docker nginx & PHP 7 FPM; a colleague did some work in W10 PHP 7.1.0 PHPUnit 5.7.21 wrote some unit tests and they pass on his system. Even at composer install, during the php artisan optimize phase, I get
~~~
  [Illuminate\Contracts\Container\BindingResolutionException]                                                 
  Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Routing\Router].  
~~~
I am trying to figure out why and so far, haven't been able to.
