### ISSUE TITLE
The 'api' attribute not found in Dingo\Api\Routing\Helpers

### ISSUE THREAD

**Issue by prapats** [dingo/api#515]
Hi,

I tried to do an internal request by using:

`$this->api->get('api/test');`

I already added the `use Helpers;` trait, but the following error is shown:

```
ErrorException in Helpers.php line 175:
Undefined property App\Http\Controllers\Web\RfqFeedController::api
```

Please suggest what I am doing here.
Thank you

**Comment by jasonlewis** [comment]
Ah, the Dispatcher stuff hasn't been added in yet as it came after the
trait. I'll do that shortly.

**Comment by prapats** [comment]
Awesome @jasonlewis 

Thanks for your great work :D

**Comment by jasonlewis** [comment]
Just added it in now. Cheers.
