### ISSUE TITLE
Problem when creating new endpoint l

### ISSUE THREAD

**Issue by olezko46** [dingo/api#516]
When I'm trying to create new end point and typing  ```$api = $app['Dingo\Api\Routing\Router'];``` in routes.php, I'm  getting error ```#Undefined variable: app```

What I need to do? Sorry for my English...

**Comment by bweston92** [comment]
You could call app as a function or in the route service provider set $app = $this->app before the include of the routes file.



—

**Comment by jasonlewis** [comment]
The documentation on this was outdated (was still stuck in L4 days, so many moons ago). You'll need to use the `app` helper function instead. I've updated the docs.

```php
$api = app('Dingo\Api\Routing\Router');
```
