### ISSUE TITLE
Unable to boot ApiServiceProvider

### ISSUE THREAD

**Issue by studiomado** [dingo/api#517]
Hello,
I try to start a new Lumen project and I have made this steps:
- php composer.phar require dingo/api "0.9.*@dev"
- add `$app->register(Dingo\Api\Provider\LumenServiceProvider::class);` in bootstrap/app.php
- add `API_PREFIX=api` in .env file

but I have this error:
`lumen.ERROR: exception 'RuntimeException' with message 'Unable to boot ApiServiceProvider, configure an API domain or prefix.'`

Can you help me?

**Comment by jasonlewis** [comment]
Have you uncommented the Dotenv line in the bootstrap file?

**Comment by akmumu** [comment]
@jasonlewis if i use the Laravel Style config ,that is i copy the vendor/laravel/lumen/config to my root config

**Comment by joyon** [comment]
add $app->singleton(Dingo\Api\Provider\LumenServiceProvider::class); in bootstrap/app.php
add API_PREFIX=api in .env file
@studiomado  no(register)

**Comment by fureszk** [comment]
`lumen.ERROR: exception 'RuntimeException' with message 'Unable to boot ApiServiceProvider, configure an API domain or prefix.' in C:\www\_innostart\garmin-ZVS\garmin-zvs-backend\vendor\dingo\api\src\Provider\DingoServiceProvider.php:82`

I'm getting this error, I've tried everything... Its set in three places and STILL... Very frustrating. Also I'm occasionally NOT getting this error...

composer.json
`"require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.3.*",
        "vlucas/phpdotenv": "~2.2",
        "tymon/jwt-auth": "^1.0@dev",
        "iatstuti/laravel-cascade-soft-deletes": "1.0.*",
        "fish/eloquent-logger": "^1.0",
        "barryvdh/laravel-cors": "^0.8.2",
        "dingo/api": "1.0.x@dev"
    },`

bootstrap/app.php
`$app->register(Dingo\Api\Provider\LumenServiceProvider::class);`

.env
`API_DEBUG=true
API_PREFIX=api`

config/api.php
`'prefix' => env('API_PREFIX', 'api'),`

routes/web.php
`$api = app('Dingo\Api\Routing\Router');
$api->version('v1', ['middleware' => 'cors', 'namespace' => 'App\Http\Controllers', 'prefix' => 'api'], function ($api) {
    /**
     * Public routes
     */
    $api->get('environmentInfo', 'ApiController@environmentInfo');

    /**
     * Auth protected routes (JWT)
     */
    $api->group(['middleware' => 'api.auth'], function ($api) {
        //User related
        $api->get('/authenticate/user', 'AuthController@getAuthenticatedUser');
        $api->post('/logout', 'AuthController@logout');
    });

    /**
     * Auth protected and language dependent routes
     */
    $api->group(['middleware' => ['api.auth'], 'prefix' => 'languages/{language_id}'], function ($api) {
        //Glossaries
        $api->get('glossaries', ['uses' => 'GlossaryController@index']);
});`
