### ISSUE TITLE
What is the correct way to use paginator when doing an internal request?

### ISSUE THREAD

**Issue by prapats** [dingo/api#518]
Hi,

I'm now doing an internal request that calls the api route that returns `Paginator`. I found that when I call `{!! $rfqs->render() !!}` in my view,  the generated url in the pagination links to the api routes not the actual route of that page. 

So, I have to use the method `setPath()` after I got the `Paginator` object back from the `Dispatcher`, and that makes me to use that method in every method that the `Dispatcher` returns the `Paginator` object.

My question is that is the way I'm doing correct? or is there a standard way to do this kind of thing?

Please suggest,
Thank you

**Comment by lightvision** [comment]
This is the only option :)

**Comment by jasonlewis** [comment]
Yeah I'm afraid that's going to be your only option. You could create a class or method that does it for you so you're not copying and pasting the same code in all your methods.
