### ISSUE TITLE
Error and Success shortcuts by default?

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#519]
I was wondering if it's possible to by default return something like this with Dingo for success/error:

    return $this->response->success('Items was added.');
    return $this->response->error('Items not added.');

   Instead of:

    return $this->response->array(['success' => true, 'message' => 'Items was added.');
    return $this->response->array(['error' => true, 'message' => 'Items not added.');

Is there something that dingo already does that returns the same output as above with the success/error and message besides the number codes? This would be pretty cool to use out of the box. Any thoughts on this?

**Comment by jasonlewis** [comment]
You could add something like this to your own base controller.

```php
class BaseController extends Controller
{
    use Dingo\Api\Routing\Helpers;

    protected function success($message)
    {
        return $this->response->array(['success' => true, 'message' => $message]);
    }
}
```

And the same for an error.
