### ISSUE TITLE
Automatic support for OPTIONS and HEAD requests

### ISSUE THREAD

**Issue by hipsterjazzbo** [dingo/api#52]
I'd like to be able to respond to the `OPTIONS` and `HEAD` verbs. This could probably be handled automatically, since this package already knows all the details needed to respond to those requests.

An `OPTIONS` request to a given endpoint should respond with something like this:

```
HTTP/1.1 200 OK
Host: localhost:8000
Connection: close
Allow: GET,HEAD,POST
```

Where `Allow:` lists the other HTTP verbs that are valid for that endpoint.

And a `HEAD` request should be the same as a `GET` request, but should return just the headers, without the response body.

I had a go at doing it myself but I'm fairly new to Laravel and I don't think I have the understanding of the internals of the framework to do it well.

**Comment by johnnygreen** [comment]
I just recently updated an old L4.1 api to L4.2 and ran into an issue.  Laravel is now auto responding to OPTIONS request when one is not defined.  I used to be able to catch the NotFoundHttpException, check for OPTIONS and respond with it like so:

```php
$request = \Route::getCurrentRequest();
$request->setMethod($request->header('Access-Control-Request-Method'));
$routes  = \Route::getRoutes();
$route   = $routes->match($request);

return \Response::make('', 200, [
  'Access-Control-Allow-Origin'  => '*',
  'Access-Control-Allow-Methods' => implode(',', $route->methods()),
  'Access-Control-Allow-Headers' => 'accept, authorization, content-type'
]);
```
Curious... I know the spec still states "Allow" as the header (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), but I can only get "Access-Control-Allow-Methods" to work in FF, Chrome, Safari.... (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

So having Laravel respond with "Allow" automatically and creating a route is making it hard to do things in an efficient manner without having to manually define an OPTIONS route for all my resource routes.

Any thoughts? Could we support both headers? Am I doing it all wrong?

**Comment by jasonlewis** [comment]
Tried using an after filter to set the CORs headers?

**Comment by johnnygreen** [comment]
Got it!  Thank you.  This seems to have done the trick:

```php

// routes.php
<?php

Route::after('v1\Filter\CorsFilter');

// library/v1/Filter/CorsFilter.php
<?php namespace v1\Filter;

use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CorsFilter {

  public function filter($request, $response)
  {
    $response->headers->set('Access-Control-Allow-Origin', '*');
    $response->headers->set('Access-Control-Allow-Headers', 'accept, authorization, content-type');

    if ($request->isMethod('OPTIONS'))
    {
      $request->setMethod($request->header('Access-Control-Request-Method'));
      $routes = \Route::getRoutes();

      try
      {
        $route = $routes->match($request);
      }
      catch(NotFoundHttpException $exception)
      {
        $route = null;
      }

      if ( ! is_null($route))
      {
        $response->headers->set('Access-Control-Allow-Methods', implode(',', $route->methods()));
      }
    }
  }

}
