### ISSUE TITLE
Testing and route includes

### ISSUE THREAD

**Issue by tomvo** [dingo/api#521]
Here a small heads-up, I seem to be able to call api routes from tests using the following code:

        $this->actingAs($user)
            ->get('/api/users')
             ->seeJson([...]);

However, I'm also including the routes on the fly from different files using:

```
foreach(File::allFiles(__DIR__ . '/Routes') as $partial){
     require_once $partial->getPathname();
}
```
That last part doesn't seem to work, it only works on the first request. I guess it has to do with internal caching of the routes file. When I put alle definitions in a single file all seems to be ok.

**Comment by jasonlewis** [comment]
So the including of the files doesn't work but you can still call the route?

**Comment by tomvo** [comment]
sorry about being unclear, It does *not* work when I include the files, it *does* work when I put them all in ones `routes.php` file.

**Comment by jasonlewis** [comment]
Interesting, I don't see any reason as to why this wouldn't work. The files are being required correctly?

**Comment by jasonlewis** [comment]
@tomvo, any updates to this? Clearing your routes cache work?

**Comment by tomvo** [comment]
I didn't have time to look at it, pre-holiday stress, sorry about that. I've moved my route definitions into one single file and that solved it for me.

**Comment by jasonlewis** [comment]
Yeah righto, would no doubt have been a caching issue of some kind. I have recently implemented a caching feature for API routes that *should* be run as an alternative to the Laravel one. The API one runs the Laravel one as well but it prevents Laravel from excluding the API routes.

Perhaps you can take a look at that when you get back from your holiday and you're stress free! Have a good one mate!
