### ISSUE TITLE
Laravel 5 Controller not found

### ISSUE THREAD

**Issue by mrgodhani** [dingo/api#522]
When using this code I get reflection error Controller now found. Any idea how to resolve this issue ? I am using Laravel 5.1. All the code below is under routes.php

```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1',function($api)
{
    $api->get('hello','HelloController@show');
});

```

**Comment by jasonlewis** [comment]
Is `HelloController` namespaced? You'll need to provide the full namespace name to the controller.

**Comment by mrgodhani** [comment]
HelloController has default namespace with namespace App\Http\Controllers . I tried adding the whole namespace too but doesnt work.

**Comment by mrgodhani** [comment]
Same goes to custom created namespace extending base controller

**Comment by jasonlewis** [comment]
So the following isn't working for you?

```php
$api->get('hello','App\Http\Controllers\HelloController@show');
```

**Comment by mrgodhani** [comment]
Nope

**Comment by mrgodhani** [comment]
Gives 404

**Comment by jasonlewis** [comment]
If it's giving you a 404 then you're not hitting the right URL, as if you've set it up as I've shown above and your namespacing is all correct then it'll work fine.

If you've setup the package to use a prefix of `api` then the URL will be `your.app/api/hello`.

**Comment by mrgodhani** [comment]
How come than I get reflection error sayimg controller class does not exist when doing php artisan?

**Comment by mrgodhani** [comment]
Git gives 404 when accessing route but doing php artisan just says controller class does not exist and as reflection error

**Comment by jasonlewis** [comment]
You've most likely got something mis-configured. I just fired up a fresh Laravel 5.1 install with the package that's using a controller in the default namespace and it works fine. I can see the correct response at `/api/hello` and using `php artisan api:routes` lists it correctly.

Make sure you double and triple check the spelling on everything. Make sure your namespace for your controller is correct and is being autoloaded properly. Make sure your route references the controller correctly including the namespace.

**Comment by mrgodhani** [comment]
Ok I will give it a try again.

**Comment by mrgodhani** [comment]
It works. But I think it's not detecting API_PREFIX=api from .env .

**Comment by mrgodhani** [comment]
Now getting this error ""Class App\\User does not exist" I have set namespace too Custom\\User

**Comment by wind930** [comment]
hi @mrgodhani 
```php
$api->version('v1',function($api)
{
    $api->get('hello','HelloController@show');
});
```
You should set up the full path of the controller or set the namespace

**Comment by jeremybradbury** [comment]
@jasonlewis in my 5.1 testing, this only works with the default namespace, after moving and changing the namespace my routes show up properly in ```php artisan api:routes``` but it still looking to load the file from the default namespace.

**Comment by jeremybradbury** [comment]
Well not nevermind, but nevermind.

I still had some `use` statements that were referencing the old locations. 

This may also be tripping others up. 

I did a search folder search for 'Http\Controllers' to help me find the troubled statement.
