### ISSUE TITLE
API Documentation not rendering properly

### ISSUE THREAD

**Issue by mrgodhani** [dingo/api#523]
Hi Documentation isn't rendering properly. Following below is an example of function.

```
/**
 * User Resource representation
 *
 * @Resource("Users", uri="/users")
 * @package Source\Http\Controllers\Api\v1
 */
class UserController extends BaseController
{
    /**
     * Register and create new user
     *
     * @Post("/create")
     * @Versions({"v1"})
     * @Request({"name": "name","email": "email", "password": "password"})
     * @Response(200, body={"token" : "token" })
     */
    public function create(Request $request)
    {
    }
} 
```

And in documentation.md instead of getting ```[POST /user/create]``` I am getting ```[POST /usercreate]```. Am I doing it wrong ? or how to resolve this issue. Also is there any way to return custom success resource?

Thank you.

**Comment by lightvision** [comment]
Issue a ``composer update first`` to get the latest dingo/api and see if you still have the errors.

**Comment by jasonlewis** [comment]
My guess is it's incorrectly prefixing the actions URI. I'll take a look
when I'm home. Should be a relatively quick fix.

**Comment by lightvision** [comment]
@jasonlewis  I had some errors too but right now I'm focused on other part of my project. I will provide feedback very soon.

**Comment by jasonlewis** [comment]
Okay this should be fixed now, try running a `composer update` and make sure `dingo/blueprint` updates to `0.1.2`.

@lightvision If you could also try out the latest version, I fixed several issues as I added in several test cases. If you've still got issues please let me know what they are ASAP so I can get them fixed. Cheers!

**Comment by lightvision** [comment]
@jasonlewis I have tried the latest version and I have some issues with square brackets ([]) in the ``@Response`` annotation, even if the documentatio from https://apiary.io/blueprint allows them

**Comment by jasonlewis** [comment]
You can't use square brackets. If you need to use square brackets for a
JSON array change it to a curly brace, it'll enckde correctly. That's just
how annotations work with the library I'm using to parse.

I'll note this in the documentation so it's clearer.

**Comment by lightvision** [comment]
Thanks.

How can I document the `show ($id)` method patameter? I get :
```
[ErrorException]                      
  Trying to get property of non-object
```

**Comment by jasonlewis** [comment]
What have you got?

**Comment by lightvision** [comment]
Here is the complete code:
```
/**
     * Get an user by its id
     * 
     * @Get("/{id}")
     * 
     * @Parameters(
     *      @Parameter("id", description="The client id to get its details.")
     * )
     * 
     * @param type $id
     * @return type
     */
    public function show($id) {
        $id = $this->unobfuscateId($id);

        try {
            $client = Client::findOrFail($id);

            return $this->response()->item($client, $this->transformer);
        } catch (ModelNotFoundException $e) {
            return $this->response()->errorNotFound("Requested resource with id={$id} where not found. Further requests may be logged.");
        }
    }
```

**Comment by jasonlewis** [comment]
Hm, probably the lack of curly braces I'd say. Parameters definition is
like this: @Parameters({})

Then specify each parameter separated by a comma with @Parameter.

**Comment by jasonlewis** [comment]
I just took a quick look and it looks like this isn't how it's shown in the
docs. But check the test stubs for the dingo/blueprint repository, they
show how it should work.

**Comment by lightvision** [comment]
Thanks. I was looking into the source code but I forget that the tests are missing and I should take a look to github:)

An enhancement request: It should be nice to have a way to setup the name of documentation, the version(s) and the output with some defaults values in a config file.

That way I could trigger just trigger ``php artisan api:docs`` and setup an elixir task to watch on the output file.

**Comment by jasonlewis** [comment]
Yeah fair point. Probably can just default the version to the default
version in the config already. Will add an option for a default name as
well.

**Comment by lightvision** [comment]
Thanks

**Comment by jasonlewis** [comment]
Okay the command has been updated. You can define an `API_NAME` in your `.env` or set the `name` config property to a default name.

The command signature now takes the name and version as options. Unfortunetly the `--version` option is always taken... So, the signature is as follows:

```
$ php artisan api:docs --name Something --use-version v2 --output-file ~/Documents/API.md
```
