### ISSUE TITLE
Route model binding

### ISSUE THREAD

**Issue by lightvision** [dingo/api#525]
I have the following situation: I need to use obfuscated id's and I want to use Router::bind();

Here is a concrete example:

```
/* @var $router Illuminate\Routing\Router */

$router->bind('clients', function ($id,$route){
   # figure out if id id obfuscated
   if(!is_numeric($id)){
        $id=\HashIds::decode($id);
    }
    
    try {
        $client=  Client::findOrFail($id);
        
        return $client;
    } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
        # here I need a way to find out who is making the call: api andpoint or app endpoint in order to return a propper error response
        if('unfound solution'){
          $api=  app(\Dingo\Api\Http\Response\Factory::class);
          return $api->errorNotFound("Requested resource with id={$id} where not found. Further requests may be logged.");
}

\App::abort(404, 'Client ID not found.');
    } 
});
```

The problem is that there is no reliable way to figure out if this is an internal request to the api or an external one.
I use model binding only in the api controller.

Or there is and am I missing something?

**Comment by jasonlewis** [comment]
I don't even think model binding exists on the API router does it?

To answer your question... If you can get the current request instance with
app('request') you can check to see if it's an instance of InternalRequest.

**Comment by lightvision** [comment]
I found a solution but I don't know how reliable it is:

Here is the code excerpt from Api `ClientController`:
```
public function show(Client $client) {
        
            return $this->response()->item($client, $this->transformer);

    }
```

and here is the code from route model binding:

```
$router->bind('clients', function ($id,$route){
    
    # get the real id if it were obfuscated
    if(!is_numeric($id)){
        $id=  HashIds::decode($id);
    }
    
    # let's try to get the client
    try {
        $client=  RoboticAccounting\Client::findOrFail($id);
        
        return $client;
    } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
        
        # if it's an api call let's respond
        if(app()['api.router']->hasDispatchedRoutes()==TRUE){
            $api=  app(\Dingo\Api\Http\Response\Factory::class);
            return $api->errorNotFound("Requested resource with id={$id} where not found. Further requests may be logged.");
        }
        
        # abort
        app()->abort(404, 'Client was not found');
    }

});
```

This approach save me writing a code twice: one in the api controller and twice in the app controller.

Hope is helping some one.

I've tested with or without obfuscated Ids and it works.

**Comment by jasonlewis** [comment]
I'm still confused as to how route model binding is even working in an API call?

**Comment by jasonlewis** [comment]
Never mind, of course it'd work as the route is run through Laravel's router eventually.

I'd suggest grabbing the request instance and checking that. Probably better than checking the number of routes dispatched.

Something like this...

```php
if (app('request') instanceof \Dingo\Api\Http\Request) {
    // Request was API, or use \Dingo\Api\Http\InternalRequest to check if it's an internal request.
}
```
