### ISSUE TITLE
Middleware api.auth missing isProtected method (Lumen)

### ISSUE THREAD

**Issue by jayhealey** [dingo/api#527]
Just bumped up to `0.10.*` and applied the `api.auth` middleware to some routes and it's throwing the following error:

```
Fatal error: Call to undefined method Dingo\Api\Routing\Route::isProtected() in 
/api/vendor/dingo/api/src/Http/Middleware/Auth.php on line 49
```

The `Dingo\Api\Routing\Route` instance appears to be missing the `isProtected` method.

I've read through the updated docs, and can't find mention of any additional changes - am I missing something?

**Comment by jasonlewis** [comment]
Woops that's my mistake. Give me a minute.

**Comment by jasonlewis** [comment]
Update again.

I'm sure I had that changed. Oh well, should be sweet now.

**Comment by jayhealey** [comment]
Awesome stuff - cheers Jason!
