### ISSUE TITLE
response type - download

### ISSUE THREAD

**Issue by SergeyMiracle** [dingo/api#528]
Plz add support for download response.

**Comment by bweston92** [comment]
#86

**Comment by SergeyMiracle** [comment]
@bweston92 i don't see how to make response->download()... Can i see an example?

**Comment by bweston92** [comment]
What are you using? Laravel 4/5? Lumen?

**Comment by SergeyMiracle** [comment]
@bweston92 Laravel 5.1

**Comment by jasonlewis** [comment]
I've tweaked this again so you can return a binary response but I'd argue that you shouldn't. Your API should merely provide a downloadable URL to the file in question and not actually serve the file.

Of course, if files aren't statically available that might not be entirely impossible.

**Comment by SergeyMiracle** [comment]
@jasonlewis files are in protected folder, and can not be seen from public site, so i guess i need some way to provide binary response since i can not provide download link.

**Comment by jasonlewis** [comment]
It's possible now to return a binary response
