### ISSUE TITLE
Disabling Cookies

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#529]
Just a heads up for folks that are after this kind of functionality. 

Currently toying with an implementation that simply requires setting a config option to either `true` or `false`.

The only issue I'm facing is that Laravel actually sets some cookies in several places and doesn't always check whether or not it *should* set cookies.

For example, I can disable sessions by setting the `session.driver` to `array`, a non-persistent driver. However, in the `VerifyCsrfToken` middleware provided by Laravel it doesn't actually check if the driver is persistent. It just adds the cookie.

Going to talk with Taylor about possibilities.

**Comment by jasonlewis** [comment]
Giving it some more thought there is the possibility of simply removing cookies set on a response. This means they're still set at some point, however, before the response is set I simply remove them.

Seems a bit icky but entirely possible. I'll see what Taylor says and then make my decision.

**Comment by lightvision** [comment]
Great. I am looking for updates

**Comment by lightvision** [comment]
Any news from Taylor?

**Comment by jasonlewis** [comment]
Not yet. I've pinged him about out but I've been a bit busy last few days
so no chance to follow up. Most likely I'll be removing them manually I'd
say.

**Comment by lightvision** [comment]
Sorry for bother with this issue, but I've already tried all options to disable the cookies and no avail, the laravel_session cookie is still present.

Do you have any idea of what can I do to achieve this? At least a hint is much appreciated. I mention that I already tried to disable ALL middleware and no avail.

**Comment by catalinux** [comment]
I am using Lumen and I removed this middlewares, from app.php
```php
    'Illuminate\Session\Middleware\StartSession',
    'Illuminate\View\Middleware\ShareErrorsFromSession',
```

**Comment by lightvision** [comment]
I've tried this but for some strange reason Postman still shows me the 'laravel_session' cookie

**Comment by catalinux** [comment]
@lightvision : on any request? How about in Chrome for get pahts?

**Comment by lightvision** [comment]
The test was done for PUT request. Howewer I could determine the kind of request after I will found a solution to entirely disable cookies.
I've done in the same way fo csfr request, but only for api requests and not for my app.

**Comment by lightvision** [comment]
As I already said, for some strange reason Postman have strange behavior related with old cookies.

So here is what I've done in order to **disable cookies and csfr token for api requests** but leave the ON for the app:

*App\Http\Kernel.php : *
<?php namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel {

	/**
	 * The application's global HTTP middleware stack.
	 *
	 * @var array
	 */
	protected $middleware = [
		'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
                'App\Http\Middleware\ApiMiddleware',
		'Illuminate\Cookie\Middleware\EncryptCookies',
		'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
		'Illuminate\Session\Middleware\StartSession',
		'Illuminate\View\Middleware\ShareErrorsFromSession',
		'App\Http\Middleware\VerifyCsrfToken',
	];

	/**
	 * The application's route middleware.
	 *
	 * @var array
	 */
	protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
	];

}

The content of the *App\Http\Middleware\ApiMiddleware* class:
```
<?php

namespace App\Http\Middleware;

use Closure;

/**
 * 
 */
class ApiMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if($request instanceof \Dingo\Api\Contract\Http\Request){
            config()->set('session.driver', 'array');
        }
        return $next($request);
    }
}
```

The content of the *App\Http\Middleware\VerifyCsrfToken* class:
```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier {

    /**
     * The URIs that should be excluded from CSRF verification.
     * 
     * @var array An array of excluded URIs from CSRF verification
     */
    protected $except = [
        
    ];
    

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next) {
        if($request instanceof \Dingo\Api\Contract\Http\Request){
            
            # go the next middleware
            return $next($request);
        }
        
        return parent::handle($request, $next);
    }

}

```

Another way to disable cookies and avoid using the ApiMiddleware is to setup the *Accept* header to **Application/json** for dingo/request and that way the Illuminate\Request will return **true** for **wantJson()** method.

I don't know if this could be a path to follow since the api could return json but not only json.
@jasonlewis Please close this issue.

**Comment by jasonlewis** [comment]
You need to remember to clear existing cookies from your browser as simply disabling them will not remove the existing ones. :smile:

**Comment by lightvision** [comment]
Yeap, but I didn't find any option to clear them in Postman. Solved, anyway. Thanks for support. :+1:

**Comment by jasonlewis** [comment]
Chrome? Just clear them from your settings. Works for me. :+1:
