### ISSUE TITLE
the console command api:routes doesn't work anymore.

### ISSUE THREAD

**Issue by jinseokoh** [dingo/api#530]
As of 0.10.*, it complaints the isProtected() method is missing.

**Comment by jasonlewis** [comment]
Good pickup, cheers. Will need to tweak the command slightly to account for
the recent changes.

**Comment by yosvelquintero** [comment]
I have created a pull request to close this issue by adding the method Api\Routing\Route::isProtected()
- This method determine if the route is protected.

**Comment by rokde** [comment]
I have made a pull request on #538

**Comment by jasonlewis** [comment]
538 was merged however I I'll be amending it once I'm home so that the
protected column is still included.

**Comment by jasonlewis** [comment]
Have made some amendments to the command. Protection is now displayed and you can filter routes based on their protection, e.g., `php artisan api:routes --protected` will only show protected routes.
