### ISSUE TITLE
Last version of fractal

### ISSUE THREAD

**Issue by catalinux** [dingo/api#531]
How can I make dingo to use the last version of fractal? https://github.com/thephpleague/fractal/commits/master

I need to use `Add mergeIncludes() to SerializerAbstract and move merge logic away f…` commit

**Comment by jasonlewis** [comment]
If you need to get the latest commits to the `master` branch you *can* simply define it in your `composer.json`, like this, as far as I know.

```
"league/fractal": "dev-master"
```

Or you may need to alias it.

```
"league/fractal": "dev-master as 0.11.0"
```

**Comment by catalinux** [comment]
First option did not work. It would still give me the error:
`  Problem 1
    - dingo/api v0.9.0 requires league/fractal 0.12.* -> no matching package found.
    - dingo/api v0.9.0 requires league/fractal 0.12.* -> no matching package found.
    - dingo/api v0.9.0 requires league/fractal 0.12.* -> no matching package found.
`

But `
    "league/fractal": "dev-master as 0.12",
`
worked great!
