### ISSUE TITLE
Failed validator doesn't get transformed

### ISSUE THREAD

**Issue by DraperStudio** [dingo/api#535]
So I've just setup Dingo 0.9 on a new Project and it doesn't seem to transform failed validations or any exceptions besides ones with status code 500 anymore.

I send a request to an endpoint and if the validation fails I just want to return the errors nicely formatted like documented here https://github.com/dingo/api/wiki/Errors-And-Error-Responses.

```
$validator = validator()->make($request->all(), $rules]);

if ($validator->fails()) {
    throw new ValidationHttpException($validator->errors()); // also tried StoreResourceFailedException, same result
}
```

I just get the generic grey "Whoops, looks like something went wrong." error page for all exceptions besides ones that have a status code of 500.

On Dingo 0.8 it seemed to work just fine, now with Laravel 5.1 and Dingo 0.9 it won't handle the Exceptions anymore.

Any ideas what could be the issue that causes the exception not to be transformed?

**Comment by jasonlewis** [comment]
Can you share more of the stack trace? I'm on the road at the moment
heading home so I'll be able to give you more feedback once I'm in front of
a computer.

**Comment by DraperStudio** [comment]
That is the stack trace https://gist.github.com/DraperStudio/e6643da5fe07a12732cd

The ApiRequestTrait is what you once posted here in an issue.

```php
<?php

namespace App\Traits;

use Dingo\Api\Exception\ValidationHttpException;
use Illuminate\Contracts\Validation\Validator;
use Symfony\Component\HttpKernel\Exception\HttpException;

trait ApiRequestTrait
{
    protected function failedValidation(Validator $validator)
    {
        throw new ValidationHttpException($validator->errors());
    }

    protected function failedAuthorization()
    {
        throw new HttpException(403);
    }
}
```

```php
<?php

namespace App\Http\Requests;

class StorePostRequest extends ApiRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required',
        ];
    }
}
```

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use App\Traits\ApiRequestTrait;

abstract class ApiRequest extends FormRequest
{
    use ApiRequestTrait;
}
````
My first thought was that it might couldn't intercept the exception because the FormRequest was causing an issue but Dingo doesn't catch any HttpException. I tried to throw any Exception that is listed in the Wiki and it doesn't seem to catch them.

**Comment by DraperStudio** [comment]
I followed back to where the Exceptions go and they all go to the `report`-method in the Handler and that is the end.

Shouldn't they go into the `render`-method so that a rendered response is created?

**Comment by jasonlewis** [comment]
There was an issue with the `ValidationHttpException` which has now been resolved. I *think* this may have been the problem you were seeing. There is a difference between that exception and the `StoreResourceFailedException`. Make sure with the `StoreResourceFailedException` exception (and other resource exceptions) that the first parameter is a message and the second parameter the validation errors.

The `ValidationHttpException` only takes the validation errors as the first parameter.

Anyhow, try updating and checking now.

**Comment by DraperStudio** [comment]
Well, did an require `~0.10@dev` to get the fix and now authentication is broken. No matter if a route is protected or not I receive an `UnauthorizedHttpException` for every request.

Has anything been changed to JWT authentication in 0.10?

-----

Also I did apply the ValidationHttpException change manually but I still just get the normal exception page and as I wrote this for 99% of exceptions, except the NotFoundHttpException.

**Comment by jasonlewis** [comment]
Authentication changed slightly between 0.9 and 0.10. Refer to the [documentation](https://github.com/dingo/api/wiki/Authentication#require-authentication-on-specific-routes), but basically you just need to define the `api.auth` middleware on the routes and/or groups you want  protected.

As for the exceptions, I'm unable to reproduce what you're seeing. I've copied what you've pasted here and just filled in the gaps and I'm seeing a proper error response. Can you share all relevant code.

Routes, controllers, form request class, etc. Something seems amiss because it's working fine here on a fresh install.

**Comment by DraperStudio** [comment]
The API Route and Controller-method look like this.

```php
public function index()
{
   // authenticated = app('Dingo\Api\Auth\Auth')->user()
    if ($this->authenticated()) {
        $posts = $this->posts->findAllPaginatedForUser($this->getCurrentUser());
    } else {
        $posts = $this->posts->findAllPaginated();
    }

    // $this->pagination is just a shortcut to Dingo\Api\Routing\Helpers\Response->paginator()
    // https://github.com/DraperStudio/Domesticated/blob/master/src/Traits/TransformerTrait.php
    return $this->paginator($posts);
}
$api->version('v1', function ($api) {
    $api->group(['prefix' => 'posts'], function ($api) {
        $api->get('/', 'PostController@index');
    });
 });
```

The "Frontend"-route then looks like this.
```php
/**
 * @Get("posts", as="posts")
 */
public function posts()
{
    $posts = $this->api->get('posts'); // sometimes used with ->once($this->getCurrentUser())

    return view('posts')->with('posts', $posts);
}
```

Thats pretty much it and there is no authentication required for this route, it is optional, and still I receive the error that authentication is required no matter if a route is protected or not which is weird because I did the authentication changes.

**Comment by jasonlewis** [comment]
By default the `app('Dingo\Api\Auth\Auth')->user()` will attempt to authenticate. This is mentioned in the "[Optional Authentication](https://github.com/dingo/api/wiki/Authentication#optional-authentication) section.

You can, however, pass `false` as a parameter to instruct the authenticator to not attempt authentication.

```php
return app('Dingo\Api\Auth\Auth')->user(false);
```

**Comment by jasonlewis** [comment]
I've altered the default behaviour of the `check` method as I think it makes more sense in this case for it to check if authentication has occurred.

So you can use this instead:

```php
return app('Dingo\Api\Auth\Auth')->check();
```

**Comment by DraperStudio** [comment]
Did a few changes here and there and now it returns proper responses for all exceptions again.

Thanks for your help and thanks for the change to the `check`-method.

**Comment by jasonlewis** [comment]
All good mate glad things are back in the right gear. :+1:
