### ISSUE TITLE
Event Handlers

### ISSUE THREAD

**Issue by JoeDawson** [dingo/api#536]
Hello,

Me again :smile:!

I currently have an event that fires in my application to handle the amount of times the resource is viewed. 

```php
event(new PhotoWasViewed($photo));
```

This event has a handler that increments the view count of a photo. Now, this works fine in the front-end of my application.

When I'm using it with my API, the event itself is fired - but any handlers associated with this event don't seem to be called.

My endpoint is like so: `GET /photos/{id}`

```php
public function show($id)
{
    $photo = Photo::findOrFail($id);

    event(new PhotoWasViewed($photo));

    return $this->response->item($photo, new PhotoTransformer);
}
```

So my question is, should event handlers work in the same way as the with this package? Or should I look for an alternative way to handle it?

**Comment by jasonlewis** [comment]
They should work exactly the same assuming you're listeners are being
registered.

**Comment by JoeDawson** [comment]
Yep, they're registered

```php
protected $listen = [
	'InkedFemales\Events\PhotoWasViewed' => [
		'InkedFemales\Handlers\Events\IncrementThePhotoViewCount',
	],
];
```

The listener get's called when I view the resource in my existing application, but as for the API endpoint the event fires - but the listener does not. I understand you're on the road as you mentioned yesterday so I don't expect an immediate response but certainly curious as to why this isn't working for me.

**Comment by jasonlewis** [comment]
Strange. Dingo does nothing to events to shouldn't be a problem.

Yeah I should get home today, one more big drive to go. So I'll hopefully
be sorted by tomorrow.

If you're feeling game you can try and debug where the call is getting to.
Find out where the event function goes and make your way through the code.
Obviously something is getting lost at some point.

**Comment by JoeDawson** [comment]
No worries man, appreciate you taking the time out of your travels to respond! 

What's odd is that I use the exact same event for the `show()` method in my existing application;

```php
public function show($female_slug, $photo_id)
{
	$female = Female::where('slug', $female_slug)->firstOrFail();
	$photo = Photo::findOrfail($photo_id);

	$previous = Photo::previous($photo->id, $female->id);
	$next = Photo::next($photo->id, $female->id);

	event(new PhotoWasViewed($photo));

	$title = $female->name . '\'s Photo';
	return view('females.photos.show', compact('title', 'photo', 'previous', 'next'));
}
```

Which works there.

I done some debugging, I did a `dd('testing event gets called')` in the constructor for my event `PhotoWasViewed` which certainly works. I then proceeded to check my listener using the same approach by doing yet another `dd()` in the constructor for my listener `IncrementThePhotoViewCount` does it does not dd anything at all.

But as I previously mentioned, it works in my existing app and does indeed call the listener and display my dd'd message :(

**Comment by jasonlewis** [comment]
So I'm home now and I've just setup a fresh L5.1 install with the latest Dingo API. I have a very basic event:

```php
class ActionPerformed
{
    public $action;

    public function __construct($action)
    {
        $this->action = $action;
    }
}
```

And an equally basic listener:

```php
class LogAction
{
    public function handle(ActionPerformed $action)
    {
        Log::info(sprintf('Action performed: %s', $action->action));
    }
}
```

Registered it in my `EventServiceProvider`:

```php
protected $listen = [
    'ActionPerformed' => [
        'LogAction'
    ]
];
```

And, in an API route, I fired the event:

```php
event(new ActionPerformed('deleted user'));
```

My log file contains the following:

```
[2015-08-03 05:12:07] local.INFO: Action performed: deleted user  
```

So it seems to be working fine on my end.

I guess just check all your type-hints and configuration. I know you've said it's working in your main application but from my end everything is working fine. I'd be surprised if Dingo was interfering with events as it literally does nothing at all to touch them.

Some possible things for you to debug to see where things might be going wrong. In `Illuminate\Events\Dispatcher`, at line `270` (the `getListeners` method), try dumping out the merged results and also the event name to see if the listener is at least being grabbed. Check spelling and the like.

It sounds like the listener is never being fired. So something isn't right in this segment of the code. Again, the only likely cause of this is something being misspelled *or* not being registered correctly.

**Comment by JoeDawson** [comment]
Thanks Jason, hope you enjoyed your trip!

Here's my handler, does anything here stand out as to why it may not be working?

```php
<?php

namespace InkedFemales\Handlers\Events;

use InkedFemales\Events\PhotoWasViewed;

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldBeQueued;
use Illuminate\Session\Store;

use InkedFemales\View;

class IncrementThePhotoViewCount
{
    private $session;
    private $view;

    /**
     * Create the event handler.
     *
     * @return void
     */
    public function __construct(Store $session, View $view)
    {
        $this->session = $session;
        $this->view = $view;
    }

    /**
     * Handle the event.
     *
     * @param  PhotoWasViewed  $event
     * @return void
     */
    public function handle(PhotoWasViewed $event)
    {
        if (!$this->isPhotoViewed($event->photo))
        {
            $view = $this->view->create(['photo_id' => $event->photo->id]);

            $this->storePhoto($event->photo);
        }
    }

    /**
     * Determine if the photo has been viewed to avoid
     * repeating view counts.
     * 
     * @param  Photo  $photo
     * @return boolean
     */
    private function isPhotoViewed($photo)
    {
        $viewed = $this->session->get('viewed_photos', []);

        return in_array($photo->id, $viewed);
    }

    /**
     * Store the Photo's ID in session.
     * @param  Photo $photo
     * @return boolean
     */
    private function storePhoto($photo)
    {
        $this->session->push('viewed_photos', $photo->id);
    }

}
```

I hope this helps!

**Comment by jasonlewis** [comment]
Looks fine to me, I don't think it's the listeners problem.

It's just getting lost somewhere for some unknown reason that I can't pinpoint at the moment. I don't believe it's the fault of this package either, but I could be wrong.

Try the debugging steps I mentioned in my previous post. Let me know if the listener is even being grabbed by Laravel when you fire the event. It doesn't sound like it is.
