### ISSUE TITLE
Finding auth_token in Session also

### ISSUE THREAD

**Issue by revengel** [dingo/api#537]
Can I find Authorizaion token in user session or other place if they are not be provided by headers or query? Laravel 5.1

**Comment by jasonlewis** [comment]
Not that I know of. You shouldn't be using sessions. Are you not able to
send the header?

**Comment by revengel** [comment]
I have mixed application. Api and App realisation on the same laravel 5.1 instance. That's why: 
* when auth string is not provided by headers and by query I want to find it in the special place in Session
* if these data can not be finded in session - use anonym user token (put it to header)
* and then authentificate user

**Comment by revengel** [comment]
For that I come to a decision:
* create custom authentificate provider with custom **"authenticate"** realisation. I extended Dingo Api OAuth2 provider:
```
namespace Vendor\Site\Providers;

use Dingo\Api\Auth\Provider\OAuth2;
use Illuminate\Http\Request;
use Dingo\Api\Routing\Route;
use Session;

class OAuth2Custom extends OAuth2 {

  public function authenticate(Request $request, Route $route) {
    // headers manipulations mus be here
    parent::authenticate($request, $route);
  }
}
```
* change api configuration for using custom OAuth2 provider:
```
'auth' => [
        'basic' => function ($app) {
            return new Dingo\Api\Auth\Provider\Basic($app['auth']);
        },
        'oauth' => function ($app) {
          $provider = new Vendor\Site\Providers\OAuth2Custom($app['oauth2-server.authorizer']->getChecker());
          $provider->setUserResolver(function ($id) {
              try {
                  $user = Vendor\Site\Models\User::findOrFail($id);
                  return $user;
              } catch (Illuminate\Database\Eloquent\ModelNotFoundException $e) {
                  return false;
              }
        });

          $provider->setClientResolver(function ($id) {
              // Logic to return a client by their ID.
          });

          return $provider;
        },
    ],
```

**Comment by jasonlewis** [comment]
Make sure you `return parent::authenticate($request, $route);` in your custom authentictor. Otherwise it won't return the resolved user/client.
