### ISSUE TITLE
[ReflectionException]   Class Api\v1\ApiPlacesController does not exist

### ISSUE THREAD

**Issue by LarryEitel** [dingo/api#539]
I am using Laravel with:

routes.php
```
$api = app('Dingo\Api\Routing\Router');
//$api = app('api.router');

$api->version('v1', function ($api) {
    $api->get('places', ['as' => 'places.map', 'uses' => 'Api\v1\ApiPlacesController@map']);
});
```

I run: `php artisan api:routes` and get back:
```
 [ReflectionException]
  Class Api\v1\ApiPlacesController does not exist
```
I have a controller at:
`app/Http/Controllers/Api/v1/ApiPlacesController.php`

I am `assuming` that `Dingo` is looking for the controller in the `Controllers` directory. What am I missing here?

Seems like a trivial hurdle to overcome to move forward with this package. :)

Thanks for any thoughts/direction.

**Comment by rockymontana** [comment]
I've stumbled upon that one as well.
I sorted it out by setting the full namespace.

```
$api->version('v1', function ($api) {
    $api->get('places', ['as' => 'places.map', 'uses' => 'App\Http\Controllers\Api\v1\ApiPlacesController@map']);
});
```

**Comment by LarryEitel** [comment]
Thank you! :)

**Comment by rogierborst** [comment]
Would be nice though if you didn't have to use full namespaces. And it would make it more in line with standard Laravel routing, where the App\Http\Controllers namespace is assumed.

**Comment by lightvision** [comment]
Well @rogierborst actually this is quite good, beleave me. And there is no reason to not use the same standard Laravel routing.

Define an ApiRouteServiceProvider likeAppServiceProvider and inside the `map ()` function use Dingo Router instead Laravel Router.

Then add your namespace and all mapping will be relative to your api namespace.

**Comment by jadjoubran** [comment]
@lightvision Would it be possible to get a sample code?
Really appreciate your contribution. Thanks!

**Comment by lightvision** [comment]
Here is the stripped content of the **app/Providers/RouteServiceProvider.php**:
```
<?php

namespace App\Providers;

use Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider {
    protected $namespace = 'App\Http\Controllers'; # this is required for Laravel routes

    public function register() {
        parent::register();

        # register the API V1 routes
       $this->app->register(\App\Api\v1\Providers\ApiRouteServiceProvider::class);
    }

    # not copied the **boot()** and **map()** methods since they are laravel specific

}
```


Here is the content of the **app/Api/v1/Providers/ApiRouteServiceProvider.php**

```
<?php

namespace App\Api\v1\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Dingo\Api\Routing\Router as ApiRouter;
use Illuminate\Routing\Router;

class ApiRouteServiceProvider extends ServiceProvider {
    protected $namespace = 'App\Api\v1\Http\Controllers\Admin';
    
    /** This is not quite interesting since it's like laravel ... */
    public function boot(Router $router) {
        parent::boot($router);
    }


   /**
     * Define the API version v1 Application Routes
     * 
     * @param ApiRouter $apiRouter
     */
    public function map(ApiRouter $apiRouter) {
        $apiRouter->version('v1',function ($apiRouter) {
            $apiRouter->group([
                'prefix' => 'admin',# this was required for me; prefix them as required for you if any
                'namespace' => $this->namespace
                    ], function ($apiRouter) {
                require app_path('Api/v1/Http/api_routes.php');# here we load the api v1 routes
            });
        });
    }


}
```


Stripped content of the **app/v1/Http/api_routes.php**
```


# please note: The ClientController must be in the namespace declared in the app/Api/v1/Providers/ApiRouteServiceProvider.php protected $namespace property
$apiRouter->resource('clients', 'ClientController', ['except' => ['create']]);



```

This approach help me to have a clear separation of concerns, keeps api versions separate and app routes/api routes separated as well.

Please also note the my api routes are booted before laravel routes so my api routes are available to app routes (I build a mixed app).

**Comment by jadjoubran** [comment]
hi @lightvision 
I know that this is a very late reply, but thank you so much. This answer helped me fix a similar issue in my app.
When you posted the answer I had no clue what's going on.. but I was finally able to grasp what's going on :D
