### ISSUE TITLE
Not able to access api through site URL but through subdomain

### ISSUE THREAD

**Issue by coding-sunshine** [dingo/api#542]
Hi,
I have made a route like this
```php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->group(['middleware' => 'cors'], function($api){
        $api->get('users/', 'App\Http\Controllers\Api\UserController@index');
        $api->get('users/{id}', 'App\Http\Controllers\Api\UserController@show');
    });
});
```
and I have made a configuration through which I should be able to make api calls like:

http://base.dev/api/v1/users
or 
http://api.base.dev/api/v1/users

But I am getting 404 error on both the URLs
but when I use 
http://api.base.dev/api/users
this works fine and gives me results.

Am I doing anything wrong here?

**Comment by coding-sunshine** [comment]
My Configuration file

```php
return [

    'vendor' => 'base',

    'version' => env('API_VERSION', 'v1'),

    'prefix' => 'api'

    'domain' => 'api.base.dev',

    'conditionalRequest' => env('API_CONDITIONAL_REQUEST', true),

    'strict' => env('API_STRICT', false),

    'debug' => env('API_DEBUG', false),

    'errorFormat' => [
        'message' => ':message',
        'errors' => ':errors',
        'code' => ':code',
        'status_code' => ':status_code',
        'debug' => ':debug'
    ],

    'auth' => [
        'basic' => function ($app) {
            return new Dingo\Api\Auth\Provider\Basic($app['auth']);
        },
    ],

    'throttling' => [

    ],

    'transformer' => env('API_TRANSFORMER', 'Dingo\Api\Transformer\Adapter\Fractal'),

    'defaultFormat' => env('API_DEFAULT_FORMAT', 'json'),

    'formats' => [

        'json' => 'Dingo\Api\Http\Response\Format\Json',

    ]

];
```

**Comment by catalinux** [comment]
the version does not have to be send over the uri. v1 is the default version. If you need multiple version , i think you can make this by sending trough header the version needed.

**Comment by coding-sunshine** [comment]
My php artisan api:routes shows following

+--------------+------------------------------+------+-------------------------------------------------------------+------------+----------+
| Domain       | URI                          | Name | Action                                                      | Version(s) | Scope(s) |
+--------------+------------------------------+------+-------------------------------------------------------------+------------+----------+
| api.base.dev | GET|HEAD /api/users          |      | \App\Http\Controllers\Api\UserController@index              | v1         |          |
| api.base.dev | GET|HEAD /api/users/{id}     |      | \App\Http\Controllers\Api\UserController@show               | v1         |          |
| api.base.dev | GET|HEAD /api/blog/all       |      | \App\Modules\Blog\Http\Controllers\Api\BlogController@index | v1         |          |
| api.base.dev | GET|HEAD /api/blog/post/{id} |      | \App\Modules\Blog\Http\Controllers\Api\BlogController@show  | v1         |          |
+--------------+------------------------------+------+-------------------------------------------------------------+------------+----------+


But 

when I access
http://base.dev/api/blog/all
it gives me 404 error
but
http://api.base.dev/api/blog/all 
gives me proper results

**Comment by abcsun** [comment]
your domain is api.base.dev, and the uri is /api/blog/all, so the right url is api.base.dev/api/blog/all

**Comment by coding-sunshine** [comment]
Oh ok, means I can use one at a time. I thought I would be able to use both urls simultaneously.
Thanks for the help.
