### ISSUE TITLE
How to change default eloquent key?

### ISSUE THREAD

**Issue by Luddinus** [dingo/api#545]
Hi.

If I get a single user it returns "user" key (singular) with the user attributes

{
    "user": ...
}

I want always to change that word to "data",

How can I change this?

Thx.

**Comment by Luddinus** [comment]
Ok,

I see in the config/api.php I can change the class of json formatter, so I extend that class and override "formatEloquentModel" method.

**Comment by catalinux** [comment]
Can you be more explicit in what you want. i do not think you want to change de formatter as long you keep using json responses. You might want to change your serializer.

**Comment by Luddinus** [comment]
@catalinux serializer?

When you return a model, by default you get this (user model):

```php
public function show($id)
{
    return User::find($id);
}
```

```javascript
// model json
{
    "user": {
        "id": 1,
        // other attributes...
    }
}
```

The formatter automatically sets the key to the models singular name (user). I want ALWAYS to be "data", so I make a class which extends "Dingo\Api\Http\Response\Format\Json", and set that formatter in config/api.php
