### ISSUE TITLE
WIKI configuration variable has a wrong name

### ISSUE THREAD

**Issue by vincenzoraco** [dingo/api#546]
Here https://github.com/dingo/api/wiki/Configuration the vendor variable is wrong, instead to be API_VENDOR is API_PREFIX

Is nothing I know, but hope help people are following the documentation.

**Comment by mentos1386** [comment]
Commit pending.
https://github.com/dingo/api-docs/pull/7

**Comment by jasonlewis** [comment]
Merged, will merge to the Wiki soon.
