### ISSUE TITLE
memcached needed to use rate limiting feature ?

### ISSUE THREAD

**Issue by jmartigny** [dingo/api#547]
Hi,
I tried using the rate limiting feature for my api.
in my routes.php file I have:
```
$api->version('v4', ['prefix' => 'api', 'middleware' => 'api.throttle', 'limit' => 100, 'expires' => 5], function($api) {
    $api->get('members', 'App\Http\Controllers\MemberController@members_GET');
    $api->get('members/{id}', 'App\Http\Controllers\MemberController@member_GET');
    $api->patch('members/{id}', 'App\Http\Controllers\MemberController@member_PATCH');
});
```
When I try sending a request, I get an error about memcached...
```
{"message":"Class 'Memcached' not found","code":1,"status_code":500,"debug":{"line":51,"file":"\/var\/www\/sites\/testing-apiv4\/vendor\/illuminate\/cache\/MemcachedConnector.php","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":["#0 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}()","#1 {main}"]}}
```
There is this line in my .env file `CACHE_DRIVER=memcached` that came from the env.example I believe, but commenting it out has no effect.

Is it necessary to setup a memcached install in order to use the rate limiting feature ?

I'm sorry if this is not the proper place to inquire about such issues, please let me know and I will move this question where it's more appropriate.

Thanks

**Comment by catalinux** [comment]
As you can see in the Handler.php , limiting request rate of the api is made with the help of the CacheManager. For usage of any CacheManager you need a cache driver. If you choosed to use memcached driver: yes you need to install the memcached server.

**Comment by jmartigny** [comment]
Thanks for your help @catalinux, I saw in the lumen docs that cache drivers are memcached or redis. Am I right in thinking I need to setup either one of those to use the rate limiting feature? or is there another way to go ?

**Comment by catalinux** [comment]
@jmartigny : although I did not use that particular feature (RateLimit) your thinking is correct.
