### ISSUE TITLE
api routes error

### ISSUE THREAD

**Issue by omarkarray** [dingo/api#554]
[ReflectionException]
  Class Api\UserController does not exist  when running php artisan api:routes

my code in routes.php is : 

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('users/{id}', 'Api\UserController@show');
});

and my .env file is : 

API_VENDOR=app
API_PREFIX=api
API_CONDITIONAL_REQUEST=true
API_STRICT=false
API_DEBUG=true
API_DEFAULT_FORMAT=json

and created the UserController.php under Http/Controllers

im using the         "dingo/api": "0.10.*"
on laravel 5.1.4, with  composer.json
  "minimum-stability" : "dev",
"prefer-stable" : true

**Comment by jasonlewis** [comment]
Is that the full path to the controller? It's not in `App\Http\Controllers`?

**Comment by omarkarray** [comment]
Done thanks ! @jasonlewis, working now !

**Comment by SergioGregorutti** [comment]
Hi all,

Im dealing with the same problem. I tried setting the namespace, the full path, etc. and it's so frustrating for me. Maybe I'm doing something wrong, but it's not easy to debug.

I always get this error:
```
[ReflectionException]                     
Class Api\GuideController does not exist
```

My route file is:
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api)
{
    /*
     * Guide
     */
    $api->get('guide/categories', [
        'as' => 'api.guide.categories', 'uses' => 'Api\GuideController@getCategoriesLevel1'
    ]);
});
```

And also with "v1/" I get a 404 error when I hit the page (/api/v1/guide/categories). If I remove the "v1/" in the URL I get a 500 error code.

If someone can help me will be great. Thanks in advance!
