### ISSUE TITLE
Append data to pagination links

### ISSUE THREAD

**Issue by Luddinus** [dingo/api#556]
Hi.

It would be nice that paginator method would load url parameters by default. Something like this: (from Fractal documentation):

```php
// controller method using Helpers trait.
public function paginatorWithAppendedLinks(Paginator $paginator, TransformerAbstract $transformer)
{
    $queryParams = array_diff_key($_GET, array_flip(['page']));

    foreach ($queryParams as $key => $value) {
        $paginator->addQuery($key, $value);
    }

    return $this->response->paginator($paginator, $transformer);
}
```

So for example, if the url is /users?include=photos, next link page would be automatically set as /users?include=photos&page=2

**Comment by lightvision** [comment]
The paginator() method of dingo expects a LenghtAwarePaginator.

As so it's up to you to build $paginator according to your $_GET array.

**Comment by Luddinus** [comment]
@lightvision It only applies some "queries" to the paginator, so the object would be the same (LenghtAwarePaginator)

**Comment by jasonlewis** [comment]
Hm, but what if some people don't want all query string keys included but instead only want a subset of them. Or none at all. Since this is something you usually provide manually anyway I don't see why you can't include it yourself. Your code could be simplified quite a bit though.

```php
public function paginatorWithAppendedLinks(Paginator $paginator, TransformerAbstract $transformer)
{
    $paginator->appends(app('request')->except('page'));

    return $this->response->paginator($paginator, $transformer);
}
```

**Comment by MovingGifts** [comment]
Hello,

How/where would this be called? I normally respond with a list of users in my `user` controller's `userList` method like this:

`return $this->response->paginator($users, new UserTransformer);`

The incoming url that hits this route is filtered by country like this:

`http://localhost:8000/users?country=us`

but the next page in the api response is this:

`http://localhost:8000/users?page=2`

which should look like this instead:

`http://localhost:8000/users?page=2&country=us`

How can I integrate the `paginatorWithAppendedLinks` function to return the correct paginator response with the correct url?
