### ISSUE TITLE
InvalidArgumentException on api:docs command

### ISSUE THREAD

**Issue by TUNER88** [dingo/api#558]
I've got following error on `php artisan api:docs` command, using the latest composer version `0.9.0`.

```
[InvalidArgumentException]         
  The "file" option does not exist.
````

The problem seems to be on line `96` in `Dingo\Api\Console\Command\Dockes.php`

```php
if ($file = $this->option('file')) {
    $this->writer->write($contents, $file);

    return $this->info('Documentation was generated successfully.');
}
```

This bug seems to be fixed in current master branch, can you please release new composer version?

**Comment by jasonlewis** [comment]
Require 0.10.*@dev in your Composer.

**Comment by jasonlewis** [comment]
Will be tagging a beta today as well.
