### ISSUE TITLE
Unable to use json arrays in API Blueprint response

### ISSUE THREAD

**Issue by TUNER88** [dingo/api#559]
Example
```php
/**
 * Show all categories
 *
 * Get a JSON representation of all the categories.
 *
 * @Get("/{?page,pageSize}")
 * @Versions({"v1"})
 * @Parameters({
 *      @Parameter("page", description="The page of results to view.", default=1),
 *      @Parameter("pageSize", description="The amount of results per page.", default=20)
 * })
 * @Response(200, body={"data": "foo", "bar": []})
 */
public function index(Request $request)
{
}
```

Generates following error message:
```sh
[Doctrine\Common\Annotations\AnnotationException]                                                                            
[Syntax Error] Expected PlainValue, got '\' at position 407 in method App\Http\Controllers\Api\CategoryController::index().  
```

How can I escape `[` and `]`?

**Comment by lightvision** [comment]
It's a parser limitation. The answer was already here on closed issues, but instead of [] you must use {}.

**Comment by TUNER88** [comment]
@lightvision `array` and `object` are different datatypes, it so [dread API tests](#https://github.com/apiaryio/dredd) would fail.
Documentation and real API should return same responses, otherwise the documentation is incorrect.

**Comment by lightvision** [comment]
You must {} in documentation. When rendered it will have the correct [] for responses.
And to be complete: its an annotaion parser limitation. Check your generated md documentation file and you will see the correct formated response.

**Comment by jasonlewis** [comment]
As @lightvision has said it's a limitation of the parser. But the resulting documentation that's generated will be correct. You just need to use curly braces in your docblocks, even for arrays.

**Comment by jasonlewis** [comment]
Perhaps one day I'll see if I can find away around the limitation, but it's not a big issue right now.

**Comment by TUNER88** [comment]
Thx, I've got it.
Some notes about this limitation in docs would be really nice.
