### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by anilskalyane** [dingo/api#560]
Sorry to ask this here!
How to use sentinel instead of Auth?

**Comment by jasonlewis** [comment]
If you don't want the built-in Laravel basic authentication you can write your own simple authentication provide for another library.

See the documentation: https://github.com/dingo/api/wiki/Authentication#custom-authentication-providers

**Comment by njbarrett** [comment]
In case anyone runs into this issue.
Firstly I had to set the web middleware on my api routes. This enabled the sessions to work.
```
$api->version('v1', ['middleware' => 'web'], function ($api) {
// ...
});
```

I then made an Auth Provider for Sentinel:

```
<?php

namespace App\Auth\Provider;

use Sentinel;
use Illuminate\Http\Request;
use Dingo\Api\Routing\Route;
use Dingo\Api\Contract\Auth\Provider;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

class SentinelDingoProvider implements Provider
{
    public function authenticate(Request $request, Route $route)
    {
        if (Sentinel::check())
        {
            // User is logged in.
        }
        else
        {
            // User is not logged in
            throw new UnauthorizedHttpException('You need to be logged in for this request.');
        }
    }
}
```

In my AuthServiceProvider.php I added this auth provider
```
        app('Dingo\Api\Auth\Auth')->extend('custom', function ($app) {
            return new SentinelDingoProvider;
        });
```

Then in my controllers where I wanted authentication I added:
```
    public function __construct()
    {
        $this->middleware('api.auth');
    }
```

This doesn't handle logging in via the API or anything. But it works if you are calling the API from the site the user is logged into like I am.
