### ISSUE TITLE
[L5.1] API FormRequest working example?

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#562]
@jasonlewis Hi Jason, I tried to implement the FormRequest for creating a post, but not able to do so successfully. I basically used it like the Laravel form request, but instead used the API version you just added the same way. I checked out the documentation but didn't see a concrete example on how to do this. Do you mind putting together a working example to show how the API FormRequest is working for validation?

**Comment by sputinyk** [comment]
I wanna se too
Em 05/08/2015 1:06 PM, "MovingGifts" <notifications@github.com> escreveu:

**Comment by jochenmanz** [comment]
Hi,

just add this function to the Request you created:
```
    protected function failedValidation(Validator $validator)
    {
        throw new ResourceException("Error validating the request", $this->formatErrors($validator), null, [], $code = 422);
    }
```

**Comment by jochenmanz** [comment]
Hallo,

just change the extend of your Request to the Dingo FormRequest and use it like you used it before.

Best regards,
Jochen

```
namespace App\Http\Requests;

use Dingo\Api\Http\FormRequest;

/**
 * Class ApiRequest
 *
 * @package App\Http\Requests
 */
class TestRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            // your rules
        ];
    }
}
```

**Comment by jasonlewis** [comment]
Just like @jochenmanz has shown above. I'll document it a bit more though.

Let me know if you have any problems.

**Comment by omitobi** [comment]
Actually the documentation has not yet reflected this. is it going to be updated?

**Comment by MarksGui** [comment]
Thank you

**Comment by gazben** [comment]
Right now this method is not working: Class 'Illuminate\Foundation\Http\FormRequest'

In the FormRequest.php we want to extend the original FormRequest but lumen doesn't have this class.

```php
use Illuminate\Foundation\Http\FormRequest as IlluminateFormRequest;

class FormRequest extends IlluminateFormRequest
```
