### ISSUE TITLE
BadHttpException not catchable?

### ISSUE THREAD

**Issue by kirkbushell** [dingo/api#563]
I've just tried catching the exception thrown in Accept when the header/version is all wrong. It seems as though this exception is not catchable, either via a custom handler through dingo, or via Laravel.

Any ideas why?

**Comment by jasonlewis** [comment]
Hm, it *should* be catchable. Let me take a look see. I'll get back to you shortly.

**Comment by jasonlewis** [comment]
Hey Kirk it should be catchable now with the `app('api.exception')->register()` method, it will also, by default, return the response as JSON.

Basically it's now run through the API exception handler.
