### ISSUE TITLE
New Changes to the OAuth 2.0 Package

### ISSUE THREAD

**Issue by vinkla** [dingo/api#564]
Here some change to the OAuth 2.0 package released in the latest version `5.0`:

- Added middlewares
- Updated migrations
- Removed deprecated filters

I guess we've to take these changes to consideration before update the dependency to the latest version. Just wanted to let you know about this.

**Comment by jasonlewis** [comment]
Those sorts of changes shouldn't matter as Dingo uses its own middleware
for authentication.

**Comment by vinkla** [comment]
Okay, good. Then there is nothing to worry about. I guess we just need to update the composer file then. Do you want me to send a PR for 5.0?
