### ISSUE TITLE
Unable To Configure Dingo with laravel 5.1

### ISSUE THREAD

**Issue by pratikindia143** [dingo/api#565]
Hello All,

I've been trying to configure the dingo library, using the wiki.
I have install fresh version of laravel 5.1

In a laravel 5.1 installation, I've added "dingo/api": "0.10.*" to composer.json

Ran composer update
Added Dingo\Api\Provider\LaravelServiceProvider::class to the providers array in config/app.php

Ran php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"

Updated .env with API_DOMAIN=api.laravel.com
Added the Following code under route.php

```php
$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
	$api->get('/', 'Api\TestController@index');
});
```

Create Folder Called Api under Controllers Folder and Added TestController.php

```php
<?php
namespace App\Http\Controllers;
class TestController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {
    	return '';
    }
}
```

trying to access the routes using api.laravel.com/v1 or api.laravel.com
None of them are working. 
api.laravel.com/v1 is giving 404 and api.laravel.com is giving 
message: "Class Api\TestController does not exist",

I am new to laravel so please suggest if i am doing any thing wrong.

**Comment by stojankukrika** [comment]
I think that problem is in namespace of controller.You need add to namespace \Api after App\Http\Controller and try again.

**Comment by pratikindia143** [comment]
Even tried that but it is also not working

**Comment by stojankukrika** [comment]
Yea, I try it too but it doesn't work. Work only if I give him a full namespace in call: $api->get('index', 'App\Http\Controllers\Api\BaseController@index')

**Comment by stojankukrika** [comment]
Hi @pratikindia143 I just find that and try it. It's works :)

$api->version('v1', ['namespace' => 'App\Http\Controllers'], function ($api) {
    $api->get('users', 'UsersController@getUsers');
});

**Comment by jasonlewis** [comment]
Yes, make sure you provide the full namespace path to your controllers.

**Comment by pratikindia143** [comment]
Thanks @stojankukrika @jasonlewis  yeah its works fine.

**Comment by iamgp** [comment]
This was puzzling me, could you make sure you make this clear in your docs, please?

**Comment by lightvision** [comment]
It doesn't, necessary to be explained in wiki since it's the same behaviour as laravel

**Comment by jasonlewis** [comment]
I think it's confusing to some due to the fact that Laravel automatically adds that namespace in the `RouteServiceProvider`. And a lot of people aren't aware of that fact. So it probably *does* deserve a note of sorts.

**Comment by lightvision** [comment]
Yes, but api routes should be started from their own *Api ```RouteServiceProvider```* which have **$namespace** declared too.

I had to think to that kind of bootstrap because you never know when a new api version is required but you need to suuport the old one too.

More over its simpler because you just need to inject Dingo Router instead of Laravel Router.

**Comment by jasonlewis** [comment]
I know, but a lot of people that are new to this package and/or Laravel don't know the intricacies of the framework.

**Comment by lightvision** [comment]
:)

**Comment by iamgp** [comment]
Maybe, light vision, but as I worked through the wiki following the steps, I found that I was getting this error because this piece of information had been missed out.

Not everyone would trawl through the closed issues of a framework to find a solution.
