### ISSUE TITLE
Adding a '202: Accepted' helper to the response factory

### ISSUE THREAD

**Issue by kevindierkx** [dingo/api#569]
The response factory already supports '201: Created' and '204: No Content' adding a helper method for '202: Accepted' would make sense for asynchronous calls.

According to the HTTP spec you should return some kind of indicator of the current status of the request and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled. http://tools.ietf.org/html/rfc2616#section-10.2.3

Any thoughts about this subject and/or the message format it should return?

Some more information about the subject: https://benramsey.com/blog/2008/04/http-status-201-created-vs-202-accepted/

**Comment by jasonlewis** [comment]
I must say I don't think I've ever used a `201`, although I can see it's usefulness.

I guess the thing that needs discussing is whether or not the URI to the status indicator is included in the response body or a `Location` header. I would probably opt for the `Location` header as that's how the `201` is handled.

So, by that argument, the implementation would be nearly identical to a `201`. Probably would be best to include a response body with more details, like ETA, etc, however I'd leave that up to the developer to send along.

**Comment by kevindierkx** [comment]
I've added a pull-request!
