### ISSUE TITLE
Dingo alongside a normal app

### ISSUE THREAD

**Issue by kirkbushell** [dingo/api#572]
We're currently doing this as moving the API to its own package/application is a little too costly atm. Howver, as a result we've seen that the Dingo error/exception handler has taken over our one from our main application, which is a problem.

Is there any way we can have this setup so that our application exception handler handles exceptions for its own routes, and dingo uses its exception handler for its own routes? And finally, have laravel use its own for everything else?

We currently have weird requests coming in which generate 404s, which is causing issues as Dingo is picking this up as something else (due to the handler we have written there) and outputting the wrong content (should be a 404 template file we have setup in our other handler).

Any ideas?

**Comment by jasonlewis** [comment]
Do you have a custom exception handler that extends the default `App\Exceptions\Handler`? Or how are you doing that?

**Comment by kirkbushell** [comment]
For our main application, yes we do.

**Comment by jasonlewis** [comment]
Hey Kirk, can you try a `composer update` now and let me know how things look.

I've moved the overriding of the default exception handler to when the request is validated as an API request. So it should leave everything else intact now.

**Comment by kirkbushell** [comment]
@jasonlewis oooh, awesome! Will update and then close this if it's no longer an issue, thanks :)

**Comment by kirkbushell** [comment]
@jasonlewis this appears to be working nicely. Haven't seen Dingo pick up anything it shouldn't in the past 24 hours.

**Comment by jasonlewis** [comment]
Good to hear. Cheers mate.
