### ISSUE TITLE
The Vendor Tree

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#574]
As it stands Dingo uses content negotiation to determine the requested response format and version.

```
application/vnd.whatever.v1+json
```

This makes use of the [vendor tree](https://tools.ietf.org/html/rfc6838#section-3.2), which, if you take a look at the spec requires [registrations](http://www.iana.org/form/media-types). So say your application is called `dingo`, for `application/vnd.dingo.v1+json` to be *official* you are required to register it with the IANA.

That's fine. It's not a big deal. Registration isn't terribly hard if you read through the spec and lodge an application with the IANA. In fact, if you're developing a serious product I highly recommend you do this (will be mentioning this in the docs).

On the other hand, it may not be practical to register in the vendor tree. You may want to use the [personal tree](https://tools.ietf.org/html/rfc6838#section-3.3) (which also requires registration). Or, to avoid registration completely, you might want to use [unregistered tree](https://tools.ietf.org/html/rfc6838#section-3.4).

If you read the spec it does state that use of the `x` tree is discouraged. Which is fair because, as I said before, if you're developing a serious application you should really consider the vendor tree.

But, this brings me to the point of this issue (discussion), as at the moment we can only use the vendor tree. So, I'm going to allow the other trees (`prs` and `x`).

HOWEVER, should the default tree be the `x` tree, `prs` tree, or `vnd` tree?

I'm leaning more toward the `x` tree. It makes more sense from the outset. Updates to the documentation would reflect the importance of utilizing the `prs` and `vnd` trees for most applications. But using the `x` tree by default removes the immediate need to register your media type with the IANA.

So please, discuss. Vote. Whatever. Will make a decision in the coming days. :smile:

**Comment by agentphoenix** [comment]
How exactly would this work with a distributed app? Would the expectation be that every person who downloads and installs the software will also need to register the vendor tree? Is that more of a situation where a personal tree is a better option? Just trying to wrap my head around some of this stuff.

**Comment by jasonlewis** [comment]
No, so, from what I can gather when reading the spec is that you (the company/developer/whatever) would be responsible for registering the media type for your distributed application.

The spec states the following about the personal tree:

> media types created experimentally or as part of products that are **not distributed commercially**

I've highlighted the important bit there. That said, even if you do not distribute your application commercially you can still register in the vendor tree if, for example, it's publicly available (think GitHub).

**Comment by jasonlewis** [comment]
I've decided to use the `x` tree as the default so they'll be a couple of changes that may require folks to update some of their configuration files if they wish to continue using the vendor tree. Documentation will also be updated with links to vendor tree registrations and what considerations developers need to take into account when developing an API.

**Comment by jasonlewis** [comment]
Merged as a part of `1.0.0-beta2`.
