### ISSUE TITLE
Conflict with barryvdh/laravel-cors

### ISSUE THREAD

**Issue by jloosli** [dingo/api#576]
I don't know if this is a bug on dingo/api or barryvdh/laravel-cors side, or if it's just that I messed up with the implementation, but I built up an api using this package and wanted to use https://github.com/barryvdh/laravel-cors handle the CORS side of things. For some reason, couldn't ever get the OPTIONS requests to return the correct information when going through the dingo/api. For example, my routes file looked somewhat like the following:

```
$api = app( 'Dingo\Api\Routing\Router' );
$api->version( 'v1',['middleware'=>'cors', function ( $api ) {
    $pong = function () {
        return "pong";
    };
    $api->get( '/ping', $pong );
    $api->put( '/ping', $pong );
    $api->post( '/ping', $pong );
    $api->delete( '/ping', $pong );
}
Route::match(['get','put','update','delete','post'], '/test', ['middleware'=>'cors', 'uses' => function () {
    return "Test";
}] );
```

When running cors requests through the standard laravel route, I didn't have any problems. However, when running through the dingo api router (/ping), the OPTIONS preflight wouldn't return the correct information. I then tried adding `\Barryvdh\Cors\HandleCors::class` to the `$middleware` array in the kernel, and still no luck. I finally got it working by adding both HandleCors and `\Barryvdh\Cors\HandlePreflight::class` to the `$middleware` array, even though it looks like the boot process should be dynamically adding that anyway. Is there something that I should be doing to ensure that the routeMiddleware is functioning properly?

So, to sum things up, the fix for me is to forget using the routeMiddleware and make the middleware look like the following:

```
    protected $middleware = [
        \\ ... All the normal middleware stuff ... \\
        \Barryvdh\Cors\HandleCors::class,
        \Barryvdh\Cors\HandlePreflight::class
    ];
```

Also, the required composer items are as follows:

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "dingo/api": "~0.10",
        "tymon/jwt-auth": "~0.5",
        "doctrine/dbal": "~2.3",
        "watson/validating": "~1.0",
        "guzzlehttp/guzzle": "~5.0",
        "guzzlehttp/oauth-subscriber": "0.2.*",
        "barryvdh/laravel-cors": "0.7.x"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "barryvdh/laravel-ide-helper": "^2.0"
    },
```

**Comment by jasonlewis** [comment]
I seem to be having problems getting it to work with regular Lumen routes. Shall try Laravel shortly and report back.

**Comment by LeBlaaanc** [comment]
I was able to get this to work with the `\Barryvdh\Cors\HandleCors::class` global middleware and $api (dingo api) routes no problems.

**Comment by jloosli** [comment]
For what it's worth, I opened up the same issue at https://github.com/barryvdh/laravel-cors/issues/54

**Comment by jloosli** [comment]
Turns out it was an issue that was fixed on the laravel-cors side (see https://github.com/barryvdh/laravel-cors/issues/54) for more details.

**Comment by odranoelBR** [comment]
LeBlaaanc Solution works \o/ Tks
