### ISSUE TITLE
Inconsistent naming routes behaviour addition to #568

### ISSUE THREAD

**Issue by lightvision** [dingo/api#578]
@jasonlewis I was thinking 2 days if I should reopen this issue or not and I decided to reopen:

Think of the following situation, using ```API_PREFIX``` set to be used: 

For some of the routes I will use the resource declaration, but in order to avoid 'except' array I will declare them as need it. This will lead to inconsistent route namig since one of them will have API_PREFIX set automatically to the names and the others don't **whithout manually set this in advance**.

I don't ask some weird things. You already do this if I use API_DOMAIN instead, by prefixing the routes with API_DOMAIN under the host tab in *api:routes*.

I also ask this because I have no other way to add this than by manually add to each definition of the route. On a previous version I had the chance to define the version group for api routes using the second argument as array and all routes where automatically prefixed.

I hope you understand ...

**Comment by jasonlewis** [comment]
Can you provide some examples of where and how you think it's inconsistent?

**Comment by lightvision** [comment]
First routes declaration:

```
public function map(ApiRouter $apiRouter) {
        $apiRouter->version('v1',['prefix'=>'api'],function ($apiRouter) {
            $apiRouter->group([
                'prefix' => 'admin',
                'namespace' => $this->adminNamespace
                    ], function ($apiRouter) {

                $apiRouter->resource('clients','ClientController',['except'=>['create']]);

              $apiRouter->get('test', ['as'=> 'foo','uses'=>function (){
                  return ['test'=>'value'];
              }]);
            });
        });
    }
```
end the output of api:route
```
+------+------------------------------------------------+-------------------------------+--------------------------------------------------------------------------+-----------+------------+----------+
| Host | URI                                            | Name                          | Action                                                                   | Protected | Version(s) | Scope(s) |
+------+------------------------------------------------+-------------------------------+--------------------------------------------------------------------------+-----------+------------+----------+
|      | GET|HEAD /api/api/admin/clients                | api.api.admin.clients.index   | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@index   | No        | v1         |          |
|      | POST /api/api/admin/clients                    | api.api.admin.clients.store   | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@store   | No        | v1         |          |
|      | GET|HEAD /api/api/admin/clients/{clients}      | api.api.admin.clients.show    | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@show    | No        | v1         |          |
|      | GET|HEAD /api/api/admin/clients/{clients}/edit | api.api.admin.clients.edit    | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@edit    | No        | v1         |          |
|      | PUT /api/api/admin/clients/{clients}           | api.api.admin.clients.update  | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@update  | No        | v1         |          |
|      | PATCH /api/api/admin/clients/{clients}         |                               | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@update  | No        | v1         |          |
|      | DELETE /api/api/admin/clients/{clients}        | api.api.admin.clients.destroy | RoboticAccounting\Api\v1\Http\Controllers\Admin\ClientController@destroy | No        | v1         |          |
|      | GET|HEAD /api/api/admin/test                   | foo                           | Closure                                                                  | No        | v1         |          |
+------+------------------------------------------------+-------------------------------+--------------------------------------------------------------------------+-----------+------------+----------+
```
notice how all my names where prefixed, but my ```foo``` named route was untouched (and I have to admin that this is the Laravel behaviour too).

All I ask is that there is any chance that using the previous way to declare routes, and when prefix is equal with API_PREFIX then all named routes to be prefixed. This was working on a previous version and make my life easier in declaring the api routes using that convention than adding your suggestion (with name function) to every route.

**Comment by jasonlewis** [comment]
All that double prefixing looks wrong. What's going on there?

Do you remember which version this worked on? Because I don't think it should have ever behaved like that. That's unexpected. This is just how Laravel works and how the generated route names for resource controllers work. I don't want to fiddle with that because then I'll get people asking why their route name is prefixed with `api`.

Remember, not everyone runs the API alongside their other application, so there's not always a need to prefix.

**Comment by lightvision** [comment]
The double prefix is because I used the same prefix in the ```['prefix'=>'api']``` as for the ```API_PREFIX```.

**Comment by jasonlewis** [comment]
Hm, it shouldn't be doubling up on the prefix like that. That's very odd.

I'm just looking at testing out some previous versions of the package now. This functionality has never existed as far as I can tell. I just don't see when I would've altered the name of a route that you manually provide to include the prefix.

This is the result with `0.8.3`:

```
+--------+--------------------+-----------------+----------------------+------------+-----------+----------+
| Domain | URI                | Name            | Action               | Version(s) | Protected | Scope(s) |
+--------+--------------------+-----------------+----------------------+------------+-----------+----------+
|        | GET|HEAD api       | foo             | Closure              | v1         | No        |          |
|        | GET|HEAD api/users | api.users.index | UserController@index | v1         | No        |          |
+--------+--------------------+-----------------+----------------------+------------+-----------+----------+
```

Where the `api` route is a simple `get` and the `api/users` route is a resource controller.

`0.8.0` and `0.7.0` produce the exact same result.

If you *really* want to add this functionality in by default you *can* override the API router with your own, and simply replace the `addRoute` method. Something like this, although it's not tested:

```php
public function addRoute($methods, $uri, $action)
{
    if (is_array($action) && isset($action['as'])) {
        if (! starts_with($action['as'], $this->prefix)) {
            $action['as'] = $this->prefix.'.'.$action['as'];
        }
    }

    return parent::addRoute($methods, $uri, $action);
}
```

Then just rebind it in a service provider.

```php
$this->app->singleton('api.router', function ($app) {
    $config = $app['config']['api'];

    return new YourRouter(
        $app['api.router.adapter'],
        new Http\Parser\Accept($config['vendor'], $config['version'], $config['defaultFormat']),
        $app['api.exception'],
        $app,
        $config['domain'],
        $config['prefix']
    );
});
```
