### ISSUE TITLE
Pagination route problem

### ISSUE THREAD

**Issue by rlacerda83** [dingo/api#579]
Hello,

I'm having problems using paging Lumen .

The link returned by paging results in the 404 error .

My route:
```
$api->get('emails', 'App\Http\Controllers\EmailController@send');
```
Controller:
```
$emails =  Email::paginate(5);
return $this->response->paginator($emails, new EmailTransformer);
```

When access the data is successfully returned:
```
http://localhost:8000/api/emails/
{
  "data": [
    ...
  ],
  "meta": {
    "pagination": {
      "total": 24,
      "count": 5,
      "per_page": 5,
      "current_page": 1,
      "total_pages": 5,
      "links": {
        "next": "http://localhost:8000/api/emails/?page=2"
      }
    }
  }
}
```

But the next page link results in an error . 
```
http://localhost:8000/api/emails/?page=2
{
  "message": "404 Not Found",
  "status_code": 404
}
```

If I remove the last bar , it works.
```
http://localhost:8000/api/emails?page=2
```
Any idea?

Thank you!

**Comment by jasonlewis** [comment]
Currently looking into a fix. Lumen is a bit fiddly when it comes to how it handles URIs and such.

**Comment by jasonlewis** [comment]
Okay this should be good now, requests with trailing slashes will be handled correctly.

**Comment by rlacerda83** [comment]
Please , if possible create a new version of the package to install updates
via composer .

Nice work !
thks

2015-08-20 0:14 GMT-03:00 Jason Lewis <notifications@github.com>:

**Comment by jasonlewis** [comment]
New version will be tagged soon. You can use @dev in the meantime.
