### ISSUE TITLE
API::user() return false on Lumen

### ISSUE THREAD

**Issue by oriceon** [dingo/api#582]
Hello. I use this api with jwt token auth and have a problem retriving logged user.
If i dd(API::user()) on local dev server, user will printed corectly but when i`m trying to use it on production server, it returned false.

Any ideea what could be?

**Comment by catalinux** [comment]
Do you have same settings on PROD as DEV?

Do you have your user tables with data? For example, your dev token might work (due the fact of having same secret key) - but it might not match any user id from database

**Comment by oriceon** [comment]
Sure, i have same settings, have users and all what i need to log in. It`s log in but when i do a print of logged user it not shown, only false result...

**Comment by catalinux** [comment]
I have similar settings (i make my settings from config/api.php) and have no problem. The only time I had same problem that you have, it was when model User had no id in the database.

**Comment by oriceon** [comment]
could you share your entire code to see where i`m wrong? Please make an archive of it.

**Comment by catalinux** [comment]
Being a private repo I can't send you all the project. My config/api.php looks like this:
https://gist.github.com/anonymous/d5cb4d95598b4ad5bd7c

**Comment by oriceon** [comment]
Yap. Now is workin!

1) commented in bootstrap/config.php

//$app['Dingo\Api\Auth\Auth']->extend('oauth', function ($app) {
//    return new Dingo\Api\Auth\Provider\JWT($app['Tymon\JWTAuth\JWTAuth']);
//});

2) in app/config i had my custom api.php config file. Renamed it into myprojectname.php and added your api.php config.

3) in bootstrap/config.php changed order of $configure and now i have

$app->configure('myprojectname');
$app->configure('jwt');
$app->configure('api');

Thanks.
