### ISSUE TITLE
Setting the response format from url parameter

### ISSUE THREAD

**Issue by tr33m4n** [dingo/api#583]
Hello there,

I've created a custom output format for XML and I was wondering what the best way to set this as an optional url parameter would be? Eg. http://test.com/order?output=xml

I can change the output in my dotenv to XML, so I know that that's working correctly. Would this be something I'd have to put into my controllers or is there already a switch like this built into Dingo?

Cheers
Dan

**Comment by danherd** [comment]
The best way of doing this is to use a different 'Accept' header in your request.

    Accept: application/vnd.myapp.v1+json
    Accept: application/vnd.myapp.v1+xml
    Accept: application/vnd.myapp.v1+x-yaml
    etc.

**Comment by tr33m4n** [comment]
Ah ok thanks for that. So there's no simple way of specifying the output as an url parameter?

**Comment by jasonlewis** [comment]
Negative, ideally that should be avoided as it's not a great way of performing content negotiation.

On a side note, how well is your XML formatter working? I would love to see it and/or add it as a default formatter. (I'm not great with XML so have basically avoided it.)

**Comment by tr33m4n** [comment]
Ah ok, thanks for the help :) Re the xml formatter, it's a little bit hacky
and doesn't work as it should at the moment, I've got a bit of work to do
with it... Mainly making sure it's converting to an array correctly as at
the moment it's using numbers for the root node values which is incorrect
formatting. I'll maybe have another look today and get it working, then
post a version :)
