### ISSUE TITLE
User Authentication Broken?

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#585]
I have a protected route setup, linked to a controller, but I can still return data from the controller even if I am not jwt authenticated.. I used to get a json error message before indicating I am not allowed to view the response unless I'm authenticated since it's a protected route, but doesn't seem to work anymore. Anyone having this issue or know how to fix it?

**Comment by MovingGifts** [comment]
From @jasonlewis: That is correct, if you're running the latest 0.10.*@dev then protected is no longer used, you must manually specify the authentication middleware. This works now: 'middleware' => 'api.auth'

**Comment by MovingGifts** [comment]
So before the middleware change, where we can use protected, I had a route group with 'protected' => true and a few routes within the group the had 'protected' => false, to override the group true protection. How can I apply the old protected false on some routed like before, with a route group that uses the updated 'middleware' => 'api.auth'?

**Comment by jasonlewis** [comment]
You'll have to use another group for the routes that require authentication
and keep that ones that don't need it outside.

**Comment by MovingGifts** [comment]
Hmmm... The previous approach seemed better, any specific reason for the change?

**Comment by MovingGifts** [comment]
Okay sounds good, thank you!
