### ISSUE TITLE
Duplicated DB Queries when using API Router

### ISSUE THREAD

**Issue by lukeed** [dingo/api#588]
Hi there,

Fresh installation, basic Lumen 5.1 setup.
Running Clockwork to monitor db queries.

```php
// routes.php

$api = $app['api.router'];

$api->version('v1', ['namespace' => 'Api\V1\Controllers'], function ($api) {
	$api->get('test', function(){
	    return \App\Models\Test::find(3);
	});
});
```
Results in **two** queries:
```
SELECT * FROM `test` WHERE `test`.`id` = '3' LIMIT 1`
```
```
SELECT * FROM `test` WHERE `test`.`id` = '3' LIMIT 1`
```

As opposed to the standard router:

```php
// routes.php

$app->get('/', function () use ($app) {
    return \App\Models\Test::find(3);
});
```

Results in **one** query:
```
SELECT * FROM `test` WHERE `test`.`id` = '3' LIMIT 1`
```

Obviously this isn't ideal. I've stripped Dingo's router to its bare bones and the query is still duplicated.

**Comment by lukeed** [comment]
If others need more information than this to replicate the issue, please let me know as I'd be happy to provide more info.

Should be enough though. It was a clean install, with those 2 routes, and a Clockwork installation. That's it.

**Comment by catalinux** [comment]
Do you have two http requests? OPTIONS and GET? Can you see how many times goes into the method with a xdebug debugger or a logger?

**Comment by lukeed** [comment]
Literally, each of those two codeblocks serve as the entire the contents of my entire `routes.php` file.

Test 1: A single route to '/' using the `api.router` => 2 queries
Test 2: A single route to '/' using the default Lumen router => 1 query

**Comment by jasonlewis** [comment]
I have a feeling that this is something related to Clockwork and not this package. I've logged the DB results using the standard logger and even checked SQL statements executed in MySQL workbench and can confirm that only a single MySQL statement is executed per page load.

I'll see if I can figure out why Clockwork would be doubling up for these API requests only.

**Comment by lukeed** [comment]
Thanks!

To be honest, I forgot about Workbench logs. I'll check that out too

**Comment by lukeed** [comment]
Confirmed that SQL queries are only being logged once on the database.

It's just a Clockwork + Dingo incompatibility.

**Comment by jasonlewis** [comment]
Indeed, haven't had a chance to dive into the source, it's on my list though. Very weird that it would double it up.
