### ISSUE TITLE
[suggestion] Generate Api Blueprint doc from a controller interface

### ISSUE THREAD

**Issue by yuters** [dingo/api#593]
I already have a small implementation of this, and I understand that it adds a bit of complexity.

Basically, when generating the documentation, you would check if a specific controller implements an interface with a specific naming convention, let's say `{Resource}ApiDocContract` and pass that interface to the blueprint class instead of the controller.

The advantages are that it:
- keeps your controllers clean if the documentation gets too huge.
- allows you to exclude unwanted controllers from the API documentation.

What do you think? Is it worth it? :)

**Comment by jasonlewis** [comment]
Sounds like an interesting approach.

I think if it implements an interface that ends in Docs would make sense.
Any chance you can get a workable implementation. Not sure how the parser
would manager with an interface.

**Comment by yuters** [comment]
You can see how it works by adding the following code after this line in your blueprint package:
https://github.com/dingo/blueprint/blob/master/src/Blueprint.php#L67

```
if ($interfaces = $controller->getInterfaces()) {
    $controller = array_first($interfaces, function ($key, $value) {
        return ends_with($key, 'Docs');
    });
}
```

Basically the way I see it is to add this code and the `$controller = new ReflectionClass($controller);` line to the command Docs@getControllers() instead, so you don't need to pass all the controllers, only the ones with this particular interface.

**Comment by jasonlewis** [comment]
I'll take a look today. Ideally I'd like to keep it out if the blueprint
repository. It should only be concerned with receiving the instances.

**Comment by jasonlewis** [comment]
Okay I've made changes to both this repo and `dingo/blueprint` to allow this. Gone with the `Docs` suffix, but am open to suggestions until `1.0.0` is released.
