### ISSUE TITLE
Swagger / OpenAPI

### ISSUE THREAD

**Issue by Zyles** [dingo/api#594]
So. I know there is API blueprint but I am a lot more leaned towards Swagger 2.0 which is a huge improvement over 1.0.

Any thoughts on implementing?

**Comment by jasonlewis** [comment]
It really depends how similar they are as the way the annotations are named and work are pretty much how the API Blueprint spec describes them. Unless we go with an entirely new set of annotations for a Swagger implementation.

While it would be cool it's certainly not high on my todo. If you can get a working implementation or know of an existing implementation that uses annotations I'd love to see it though.

**Comment by lightvision** [comment]
Well, I actually tried the Swagger with swaggarel package and I was not entirely happy with it. The annotation is more complex than the one provided by dingo/api right now.

More over, it doesn't support multiple api versions (Let's say you have 2 api versions but for some endpoints nothing changed - how you would document that?).

I am not against the Swagger, but the Blueprint is quite nice. And you could generate documentation easy with `laravel-elixir-aglio`. An in-dept look to this package will show even how to setup different routes for different documentation versions to be browse-able from your server.

@jasonlewis Still will be fine to have in config some sensible defaults to generate documentation without the need to specify any parameters.

**Comment by jasonlewis** [comment]
@lightvision you can do that now, there's the `version` and `name` config keys that will be used if the command is run without any arguments.

**Comment by lightvision** [comment]
:+1: 
Thanks, I didn't check it. I am writing some tests for my app and I leave the docs after that.

**Comment by Zyles** [comment]
Another great thing with Swagger is the API explorer, demo: http://petstore.swagger.io ... does API blueprint provide something similar which you can self host?

The Symfony package NelmioApiDoc generates an interface for this automatically for your API when you visit something like /api/docs/. Something similar for Dingo would be nice.

This package uses Doctrine annotations: https://github.com/zircote/swagger-php

**Comment by jasonlewis** [comment]
Yeah, [API Blueprint](https://apiblueprint.org/) has a bunch of tools.

[Aglio](https://github.com/danielgtaylor/aglio) generates a static HTML explorable API

**Comment by yuters** [comment]
[There's this conversion tool](https://github.com/kminami/apib2swagger/), I haven't tried it but if it works maybe it might be a good solution. It would be nice to be able to generate doc not only in api blueprint and swagger but also [RAML](http://raml.org/). If you ask me it would make more sense to stick to just one.

**Comment by jasonlewis** [comment]
Yeah for now I'm just going to be sticking to API Blueprint.

**Comment by igorsantos07** [comment]
I would really +1 Swagger here. My first experience with it was while building a standalone API using [Restler](http://restler3.luracast.com/), and the [Swagger-based docs](http://restler3.luracast.com/examples/_008_documentation/explorer/index.html#!/authors/retrieve_get) just blew my mind. It's certainly the best way to provide developers with a comprehensive and interactive documentation.

The only tool available in the Blueprint website that seems to do similar job is [paid ](https://gelato.io/)

Also, I'm not sure if this would help in any way, but I find the Restler annotations much, much more leaner and easier to be used. Not sure if this is related to the conversor it uses or if it's just "proprietary tech".

**Comment by hskrasek** [comment]
I personally like the idea of this (use Swagger 2.0 at work), but at the moment the main focus is going to be tagging a stable 1.0. Once that's done, might be able to revisit this. And of course, PR's are welcome

**Comment by Zyles** [comment]
Swagger (now OpenAPI) seems more mature and has been adopted on a lot of places.

I *think* it is used more than Blueprint.

Maybe prioritize this as it seems to be the future of API specs? It should probably not be in the core package but rather as an extension in a separate repo.

**Comment by specialtactics** [comment]
Closing, this is unlikely to be done largely due to lack of resources and many other priorities. If anyone wants to take it up, please feel free !
