### ISSUE TITLE
Handle BadRequestHttpException using "strict" enabled

### ISSUE THREAD

**Issue by billmn** [dingo/api#595]
I have tried to enable the "strict" mode and handle this exception using a custom exception response.

I have used this code in "boot" method of my ServiceProvider, but it doesn't handle the exception:
```php
app('api.exception')->register(function (\Symfony\Component\HttpKernel\Exception\BadRequestHttpException $e) {
    return response(['message' => $e->getMessage(), 'status_code' => $e->getStatusCode()], $e->getStatusCode());
});
```

Where I'm wrong?

**Comment by jasonlewis** [comment]
Looks fine to me. You have the latest version of the API installed?

**Comment by billmn** [comment]
I'm using 0.10.*

**Comment by jasonlewis** [comment]
Working fine on my end.

Handler is definitely being registered?

**Comment by billmn** [comment]
If I throw BadRequestHttpException from a controller the registration works fine.

But If I enable "strict" mode and I don't send the "Accept" header it throw the exception but not the hanlder.

![schermata 2015-08-20 alle 13 56 08](https://cloud.githubusercontent.com/assets/779534/9382679/3e1e3976-4743-11e5-9fed-eab689842605.png)

**Comment by jasonlewis** [comment]
Yeah you're not on the latest version, `1.0.*@dev` is the latest.

**Comment by jasonlewis** [comment]
I'll update the docs.
