### ISSUE TITLE
api router cannot use in server and return 404

### ISSUE THREAD

**Issue by whoishoward** [dingo/api#596]
Dingo:api works pretty well in my local server, but it always return 404 error.

Normal router works well.
```php
Route::get('/', function () {
    echo 'sdf';
});
```
but api router will not response:  my ip/project-folder/public/api/test/ (my prefix is 'api')
```php
$api->version('v1', function ($api) {
	// echo 'test';exit;
	$api->get('test', function(){
		return view('welcome');
	});
}
```

**Comment by jasonlewis** [comment]
Lumen? Remove the trailing slash or update the latest 1.0.*@dev to get an
update that normalize the request URI.
