### ISSUE TITLE
Token mismatch.

### ISSUE THREAD

**Issue by bweston92** [dingo/api#598]
How are people handling this issue of posting to an endpoint with CSRF token?

**Comment by jasonlewis** [comment]
There's a couple of ways. You could add your prefix to to the `$except` array. Or, you can override the `handle` method like this:

```php
public function handle($request, Closure $next)
{
    if ($request instanceof \Dingo\Api\Http\Request) {
        return $next($request);
    }

    return parent::handle($request, $next);
}
```

So it won't apply to API requests.

**Comment by lightvision** [comment]
I know that @Jason Lewis closed this issue with correct answer but you would also need to disable the cookies for  your api endpoints as well.
