### ISSUE TITLE
[Lumen] Global middleware are executed twice

### ISSUE THREAD

**Issue by kylestev** [dingo/api#599]
I was trying to figure out why itsgoingd/clockwork#104 was duplicating queries it stored and ended up logging a stacktrace which showed all global middleware (`$app->middleware([...])`) is being called twice. This does not seem to impact route

I couldn't seem to find this in the documentation so I assume it's a bug.

---

### Dingo Versions

* `v0.10.0`
* `v1.0.0-beta1`
* `1.0.x@dev`

### Environment

Fresh install of Lumen and Dingo.

#### `composer.json`

```
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.1.*",
        "vlucas/phpdotenv": "~1.0",
        "dingo/api": "1.0.x@dev"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "fzaninotto/faker": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

#### `app/Http/routes.php`

```php
<?php

$app->get('hello', function () {
    return 'lumen route';
});

$api = app('Dingo\Api\Routing\Router');
$api->version('v1', function ($api) {
    $api->get('test', function () {
        return response()->json([
            'check' => 'logs',
        ]);
    });
});
```

#### `app/Http/Middleware/ExampleMiddleware.php`

```php
<?php

namespace App\Http\Middleware;

use Closure;

class ExampleMiddleware
{
    public function handle($request, Closure $next)
    {
        app('log')->debug('middleware ran for path: ' . $request->path());
        return $next($request);
    }
}
```

#### `bootstrap/app.php` (additions)

```php
$app->middleware([
    App\Http\Middleware\ExampleMiddleware::class,
]);

$app->register(Dingo\Api\Provider\LumenServiceProvider::class);
```

### Steps to Reproduce

1. Copy the changes above and run composer install
2. Visit `/hello`
3. Visit `/api/test`
4. Check `storage/app/lumen.log` and you'll see something like this:

```
[2015-08-23 08:24:25] lumen.DEBUG: middleware ran for path: hello  
[2015-08-23 08:24:26] lumen.DEBUG: middleware ran for path: api/test  
[2015-08-23 08:24:26] lumen.DEBUG: middleware ran for path: api/test  
```

**Comment by jasonlewis** [comment]
Okay, that's interesting, it's most probably something to do with the adapter then. I should be able to work with this. So it's just running the middlewares twice, not the route itself.

**Comment by kylestev** [comment]
@jasonlewis yes, it appears to only be running the middleware twice. Here's the stack trace of the second time Clockwork's middleware runs:

I also enabled the `EncryptCookies` middleware just to be sure it was running global middleware twice.

---

I made a repo you can clone to reproduce this: [kylestev/dingo-599-reproducer](https://github.com/kylestev/dingo-599-reproducer)

**Comment by jasonlewis** [comment]
Many thanks. I'll see how I go, hopefully it's just an issue with the adapter.

**Comment by kylestev** [comment]
No problem -- happy to help!

**Comment by jasonlewis** [comment]
Fixed! Was most certainly an issue with the adapter. Because Lumen's application life cycle is a little different I didn't notice that it runs the global middlewares during a dispatch. I should've noticed, but simply overlooked it.

So I'd done half the work by removing the `Request` middleware so it wasn't executed twice. I just didn't realise that it was executing the rest of the global middlewares twice as well.

Should be good now.

**Comment by jasonlewis** [comment]
Thanks again for the excellent debugging. Made squashing this that much faster. :+1:

**Comment by kylestev** [comment]
Woohoo! Thanks for the quick fix!
