### ISSUE TITLE
oAuth2 Authorization Header

### ISSUE THREAD

**Issue by headcastlab** [dingo/api#601]
I have implemented the oauth2 bridge (lucadegasperi/oauth2-server-laravel ) and found that while I can access using access_token on the query string I was unable to access using the "Authorization" header. I am using postman and in a standalone install of the oauth2 server all works fine. 

I have tracked the issue down and it appears that the "bearer" part of the "Authorization" is not needed but the dingo authorization explicitly checks for the "bearer" prefix to the token.

In dingo/api/src/Auth/Provider/Authorization.php

    public function validateAuthorizationHeader(Request $request)
    {
        if (Str::startsWith(strtolower($request->headers->get('authorization')), $this->getAuthorizationMethod())) {
            return true;
        }

        throw new BadRequestHttpException;
    }

I have replaced with:

    public function validateAuthorizationHeader(Request $request)
    {
        
        if( $request->headers->get('authorization') ) {
            return true;
        }

        throw new BadRequestHttpException;
    }

So as to simply check for the existence of the header. This does work for me but I have not submitted a pull request as I am unsure of the wider ramifications.

**Comment by jasonlewis** [comment]
Using Apache? Most likely the header is being stripped? You'll need something like this in your `.htaccess`:

```
RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

`Bearer` is a part of the spec.

**Comment by headcastlab** [comment]
Nope using nginx... I figured the bearer part was part of the spec but using Postman to send the Authorization header works for the oauth package on its own but not in conjunction with dingo?

i.e. In Postman the header "Authorization" has a value of "tokenstring0123456789" with no bearer prefix.

**Comment by jasonlewis** [comment]
You need the Bearer prefix. The OAuth package that this package utilizes [specifically checks for its existence](https://github.com/thephpleague/oauth2-server/blob/master/src/TokenType/Bearer.php#L47).

**Comment by headcastlab** [comment]
I understand that, but I don't understand why when I remove the check for the bearer in the Dingo file, everything starts working and the token Authorization works correctly. If the bearer was ommited, the phpleague package would fail, but it doesn't. I will do some further checks. I absolutely don't want to get into a debate without hard facts :). Thanks for your help.

**Comment by jasonlewis** [comment]
Sorry I'm a bit flat out with some other work so I can't give you a solid answer.

But you do raise a good point that seeing as the OAuth package specifically checks the header there's probably no real reason for Dingo to worry about checking it.

That said, `Bearer` is required still. Perhaps there's a compatibility issue with the version Dingo has support for that we need to look into.

If you have the time to debug then I'd very much appreciate it. There's no pressure though. I'll re-open this and take a look. My first stop would be checking the `Bearer` token type in the League's package that you have installed. See what's going on there.

**Comment by headcastlab** [comment]
OK, found it out...
The League package does look for the Bearer and if its found it gets stripped from the token and just the token gets passed on. So essentially, for the league package, the Bearer is optional. This is why when I was testing the standalone package it worked but when passed through your check it doesn't.

Close this issue again and many thanks for your time, effort and your excellent package.

**Comment by jasonlewis** [comment]
Awesome, no worries, I think in the newer versions the League package makes it mandatory and not optional. So best to include it for future proofing. :+1: 

Cheers mate!
