### ISSUE TITLE
Run Dingo API standalone?

### ISSUE THREAD

**Issue by LeBlaaanc** [dingo/api#602]
I am building only an api so I don't need to nest it in a url segment or specific domain. It'd be nice to be able to have dingo api just work standalone without having to specify a prefix or domain.

Any thoughts on whether this is something worth doing or are there just technical hurdles here worth the minor inconvenience of having to configure these things.

**Comment by jasonlewis** [comment]
Sure mate, just set the `API_DOMAIN` to your domain OR set the `API_PREFIX` to `/`.

**Comment by LeBlaaanc** [comment]
Ah! Didn't think to set the prefix to '/'. 

On Aug 25, 2015, at 9:07 PM, Jason Lewis <notifications@github.com> wrote:

Sure mate, just set the API_DOMAIN to your domain OR set the API_PREFIX to /.

**Comment by jasonlewis** [comment]
You might need to run an update, I did find a small issue with using `/` as the prefix. It might have only affected Lumen installs though because Lumen is very picky with routes.
