### ISSUE TITLE
Update broke things

### ISSUE THREAD

**Issue by alexcoffee** [dingo/api#603]
Just pulled in an update and framework won't start:
Call to undefined method Dingo\Api\Dispatcher::setSubtype()

commented out 
"$dispatcher->setSubtype($config['subtype']);" in registerDispatcher()
to make it run for now.

**Comment by jasonlewis** [comment]
Urgh, thanks for the update. Will fix ASAP.

**Comment by jasonlewis** [comment]
Can you try updating again?

**Comment by ndnam90** [comment]
I just updated but it show a error:
ErrorException in ApiServiceProvider.php line 190:
Undefined index: standardsTree
How to fix it, thanks

**Comment by jasonlewis** [comment]
You'll need to update your config file.

**Comment by jasonlewis** [comment]
Refer to the release notes for more details: https://github.com/dingo/api/releases/tag/v1.0.0-beta2
