### ISSUE TITLE
Undefined index: standardsTree

### ISSUE THREAD

**Issue by headcastlab** [dingo/api#604]
On composer update this morning (26/08/2015) composer fails with:

    [ErrorException]
    Undefined index: standardsTree

This looks to be related to a change last night.

Thanks

**Comment by jasonlewis** [comment]
Check out the release notes: https://github.com/dingo/api/releases/tag/v1.0.0-beta2

**Comment by headcastlab** [comment]
Sorry, I am retarded

**Comment by jasonlewis** [comment]
All good mate.
