### ISSUE TITLE
Moving oauth configuration to a service provider

### ISSUE THREAD

**Issue by headcastlab** [dingo/api#606]
Frustration abounds! Having configured oauth using closures in the config file and getting it working awesomely well, you have changed it to require a service provider setup instead! :)

Basically, I have setup a service provider App\Providers\OAuthServiceProvider with the following code:

    namespace App\Providers;

    use Illuminate\Support\ServiceProvider;

    class OAuthServiceProvider extends ServiceProvider
    {
        /**
         * Bootstrap the application services.
         *
         * @return void
         */
        public function boot()
        {

            app('\Dingo\Api\Auth\Auth')->extend('oauth', function ($app) {

                $provider = new \Dingo\Api\Auth\Provider\OAuth2($app['oauth2-server.authorizer']->getChecker(), false);

                $provider->setUserResolver(function ($id) {
                    // Logic to return a user by their ID.
                    return App\User::findOrFail($id);
                });

                $provider->setClientResolver(function ($id) {
                    // Logic to return a client by their ID.
                    return App\User::findOrFail($id);
                });

                return $provider;

            });

        }

        /**
         * Register the application services.
         *
         * @return void
         */
        public function register()
        {
                    
        }
    }

And the config set to "oauth", but receiving the error...

    BindingResolutionException in Container.php line 823:
    Unresolvable dependency resolving [Parameter #2 [ <required> array $providers ]] in class Dingo\Api\Auth\Auth

I know this is probably due to a lack of knowledge about Laravel service providers but as all the config providers now need to be used this way, any chance of an example service provider in the docs?

Many thanks

**Comment by jasonlewis** [comment]
> And the config set to "oauth", but receiving the error...

Can you clarify what you mean by that?

**Comment by headcastlab** [comment]
Sorry, when making any request to the api.
I should also mention that I have added the provider to config/app.php and performed dump-autoload.

**Comment by headcastlab** [comment]
And in config/api.php 

    'auth' => [
        'oauth'
    ],

**Comment by jasonlewis** [comment]
Could be related to the order of your service providers.

Also you don't need to define it in the config. That's why you're defining it in a service provider.

**Comment by headcastlab** [comment]
So I am using correctly in the boot method of the service provider?

**Comment by jasonlewis** [comment]
Yeah, fine, you also don't need that leading slash in the `app` function.

Should be: `app('Dingo\Api\Auth\Auth')`.

**Comment by jasonlewis** [comment]
Or if you prefer: `app('api.auth')`

**Comment by jasonlewis** [comment]
In the provider it can be this as well, since you have access to the application instance:

```php
$this->app['api.auth']->extend();

// or

$this->app['Dingo\Api\Auth\Auth']->extend();
```

**Comment by headcastlab** [comment]
Cracked it mate, many thanks...

For reference: the the complete service provider /app/Providers/OAuthServiceProvider.php is:

<?php

    namespace App\Providers;

    use Illuminate\Support\ServiceProvider;

    class OAuthServiceProvider extends ServiceProvider
    {
        /**
         * Bootstrap the application services.
         *
         * @return void
         */
        public function boot()
        {

            $this->app['api.auth']->extend('oauth', function ($app) {

                $provider = new \Dingo\Api\Auth\Provider\OAuth2($app['oauth2-server.authorizer']->getChecker(), false);

                $provider->setUserResolver(function ($id) {
                    // Logic to return a user by their ID.
                    return \App\User::findOrFail($id);
                });

                $provider->setClientResolver(function ($id) {
                    // Logic to return a client by their ID.
                    return \App\User::findOrFail($id);
                });

                return $provider;

            });

        }

        /**
         * Register the application services.
         *
         * @return void
         */
        public function register()
        {

        }
    }

May help in the future.

**Comment by jasonlewis** [comment]
Looks good mate. I'll clarify a few things in the docs. :+1:
