### ISSUE TITLE
$api->resource() doubles up slashes with API_PREFIX set to '/'.

### ISSUE THREAD

**Issue by LeBlaaanc** [dingo/api#607]
`./artisan api:routes` returns something like:
`|      | POST //application                        | application.store   | Closure | No        | v1         |          |`

**Comment by LeBlaaanc** [comment]
Using `API_DOMAIN` and setting `API_PREFIX` back to `null` makes the route contain no / (so just `application` in this example.

**Comment by jasonlewis** [comment]
Are you running the latest `v1.0.0-beta2`?

I said this in the other issue about running standalone:

> You might need to run an update, I did find a small issue with using / as the prefix. It might have only affected Lumen installs though because Lumen is very picky with routes.

Seems it also affected Laravel. So if you haven't updated since yesterday you'll need to update to the latest.
