### ISSUE TITLE
Use api without Dingo/Api/Router?

### ISSUE THREAD

**Issue by LeBlaaanc** [dingo/api#608]
Is it possible to use the default laravel router with dingo api? Would I just add in some middleware? I'm just not a big fan of it being abstracted out partially because I keep running into issues and because it doesn't really fit my use case as well to separate it.

**Comment by jasonlewis** [comment]
Nope, doesn't work like that anymore.

**Comment by jasonlewis** [comment]
Let me elaborate now that I'm back on my computer.

The problem with the Laravel router is that it's pretty tightly coupled to Laravel itself. Being able to extend it is really quite difficult. This never used to be the case, however, certain changes were made to Laravel between 4 and 5 that resulted in the router being hard coded into the core.

Aside from dealing with that it just wouldn't work to utilize the Laravel router for a Lumen application.

The idea of `Dingo\Api\Routing\Router` is to provide the same features across both Laravel and Lumen installs and allow the package to work properly with both frameworks.

Another reason is it just keeps things separated. The API router isn't concerned with the regular router. Routes are registered separately and everything has its place.

Honestly, from a users perspective, you shouldn't notice any difference. If you find something that doesn't work too well or seems buggy. Report it. This package has only recently made it to beta so I don't expect it'll be 100% bug free.

**Comment by LeBlaaanc** [comment]
Understood and will do! I'd like to help more too but I'm still trying to wrap my head around everything. 

On Aug 26, 2015, at 7:38 PM, Jason Lewis <notifications@github.com> wrote:

Let me elaborate now that I'm back on my computer.

The problem with the Laravel router is that it's pretty tightly coupled to Laravel itself. Being able to extend it is really quite difficult. This never used to be the case, however, certain changes were made to Laravel between 4 and 5 that resulted in the router being hard coded into the core.

Aside from dealing with that it just wouldn't work to utilize the Laravel router for a Lumen application.

The idea of Dingo\Api\Routing\Router is to provide the same features across both Laravel and Lumen installs and allow the package to work properly with both frameworks.

Another reason is it just keeps things separated. The API router isn't concerned with the regular router. Routes are registered separately and everything has its place.

Honestly, from a users perspective, you shouldn't notice any difference. If you find something that doesn't work too well or seems buggy. Report it. This package has only recently made it to beta so I don't expect it'll be 100% bug free.
