### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by Zyles** [dingo/api#609]
Trying to install latest Dingo on latest Lumen and when I run "php artisan" i get the following error:

```
 [Illuminate\Contracts\Container\BindingResolutionException]     
  Target [Illuminate\Contracts\Http\Kernel] is not instantiable. 
```

I can get Lumen to run without Dingo.

Also using HHVM 3.9.0.

**Comment by asantanacu** [comment]
Same issue with Laravel 5.1 
I had to roll back to the previous version 1.0.0-beta1  because after update to 1.0.0-beta2 the artisan command and the whole project start to fail with the message

     [ErrorException]                
     Undefined index: standardsTree

**Comment by jasonlewis** [comment]
@asantanacu please refer to the release notes for your issue: https://github.com/dingo/api/releases/tag/v1.0.0-beta2

@Zyles I'm going to need more information. How are you requiring it in `composer.json`? Have you added the provider in `bootstrap/app.php`? Have you set up your `.env` file?

**Comment by Zyles** [comment]
Composer.json:
```
{
    "name": "test/myapi",
    "description": "My API",
    "license": "MIT",
    "type": "project",
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.1.*",
        "vlucas/phpdotenv": "~1.0",
        "dingo/api": "1.0.*@dev"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "fzaninotto/faker": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

```

.env
```
API_NAME=Myapp
API_STANDARDS_TREE=vnd
API_SUBTYPE=myapp
API_PREFIX=api
API_VERSION=v1
API_DEBUG=true
```

Bootstrap/app.php
```
Dotenv::load(__DIR__.'/../');
$app->withFacades();
$app->withEloquent();
$app->register(Dingo\Api\Provider\LaravelServiceProvider::class);
```

The rest are default Lumen settings.

**Comment by jasonlewis** [comment]
Should be `LumenServiceProvider` not `LaravelServiceProvider`.

**Comment by Zyles** [comment]
Thanks. Not sure how that happened as I copy pasted from the docs (I think).

**Comment by asantanacu** [comment]
Thanks Jason 
Yes I forgot to include the standardsTree in the config/api.php file
This thread https://github.com/dingo/api/issues/606  helped me to setup the service provider.
