### ISSUE TITLE
$this->response->collection() with Transformer is very slow

### ISSUE THREAD

**Issue by refear99** [dingo/api#610]
this is my code
```php
    $list = \Cache::remember('bannerList', 120, function () {
            $bannerList = Event::get();

            return $bannerList;
    });

    return \Api::response()->collection($list, new Transformers\BannerTransformer);
```

this is BannerTransformer

```php
namespace App\Http\Controllers\Api\Slime\Transformers;

class BannerTransformer extends \League\Fractal\TransformerAbstract
{
    /**
     * @param \App\Models\Event $item
     *
     * @return array
     */
    public function transform($item)
    {
        return [
            'url'   => $item->url
        ];
    }
}
```

with cache, this take 300-500 ms to response, but use `\Api::response()->array()` or `\Api::response()->item()` or `response()->json()`, it's response in 30ms

but, when i change to this
```php
    $list = \Cache::remember('bannerList', 120, function () {
            $bannerList = Event::get();

            return collect($bannerList); //collect
    });

    return \Api::response()->collection($list, new Transformers\BannerTransformer);
```
it's OK
what am i doing wrong ?

**Comment by jasonlewis** [comment]
Lots of items?

**Comment by refear99** [comment]
@jasonlewis Only 2 items

**Comment by jasonlewis** [comment]
That's strange. Tried `php artisan optimize`?

**Comment by catalinux** [comment]
I have similar issues with collection (lots of items). Is there a way o caching all result (with json encoding also) instead of the models only?

**Comment by jasonlewis** [comment]
I'll do some benchmarking and see what I can come up with in the coming days.

@catalinux have you tried `optimize` as well?

**Comment by refear99** [comment]
@jasonlewis I tried `optimize` , it's not working.

**Comment by bcarroll22** [comment]
This is definitely happening. I don't know if it's necessarily this package's fault, but for instance I can have an Eloquent JSON result in roughly 2 seconds, the same results transformed with Fractal actually time out after 60 seconds on HHVM. We're talking about nested relationships though, stuff like companies with 3 nested relationships. But still, 2 seconds without Fractal, a timeout with Fractal... It's a pretty big difference worth looking into.

**Comment by jasonlewis** [comment]
Could be various things playing a part in seeing such a difference though. Personally I see no issues transforming several hundred objects per response. But I don't use HHVM. So perhaps there's something there? I will look at this some more but there's a lot of factors that need to be considered.

**Comment by bcarroll22** [comment]
In my specific case, the response is very fast with one level of includes. But if I try, say, ?include=locations.departments, speed drops drastically. Is there something specific I'd need to do in the transformer to make sure this is eager loaded? I suspect what's happening is on the second level of includes nothing is being eager loaded anymore, thus the slowdown.

**Comment by bcarroll22** [comment]
Also note this is unrelated to this package. This is a Fractal issue I think. I tried the responses with plain fractal and got the same results.

**Comment by bcarroll22** [comment]
After testing today, I can confirm that a second level of resources does not work with eager loading. So if I request locations.departments, only locations is eager loaded, then each department is lazy loaded. Maybe I just don't know how to implement this type of functionality, so any help would be appreciated?

**Comment by jasonlewis** [comment]
Is that how your relationships are set up in your models (same name, etc)?

**Comment by bcarroll22** [comment]
Sorry for the delayed response. Yes all of my models are set up correctly. If I bypass this package, the eager loading happens correctly.

**Comment by bcarroll22** [comment]
The problem is doing an array_intersect with requested includes and available includes. If you do that, and you have nested includes, and you don't define locations, locations.departments, and locations.departments.registration_stations as available includes on the top-level transformer, the array_intersect of available includes and requested includes will kick out legitimate includes. Is there a reason the intersect is necessary? Couldn't you just let an exception be handled if someone requests an invalid relationship?

**Comment by jasonlewis** [comment]
I've just done away with that intersect, we'll see what crops up from it and go from there I think.
