### ISSUE TITLE
304 modified header issue

### ISSUE THREAD

**Issue by Zyles** [dingo/api#614]
I have a really weird issue that I tried to debug for two hours. And it seems dingo randomly sends a 304 Not Modified header. Not on **every** subsequent request. It does it randomly. Because I refresh and swap between my routes until I get the header eventually.

And for some reason it sends status code 200 (according to Chrome), not 304. But if I dump($response) in my middleware the code is 304.

But I want to turn this off so I set .env API_CONDITIONAL_REQUEST=false. But it still keeps throwing the header there randomly.

What is worse is that it only does it when I have my middleware running (I think. I can't seem to throw header without it). If I disable the middleware there does not seem to be an issue.

So why would it send a 304 Not modified, and have $response->getContent() be empty randomly only when running this middleware?

How to replicate:

1. Running Lumen install this middleware globally in app.php:

```
$app->middleware([
    App\Http\Middleware\RouteMiddleware::class
]);
```

Put file in App\Http\Middleware\RouteMiddleware.php: http://pastie.org/10381582

2. Randomly keep hitting different routes until the error appears (do not refresh the same route, nothing will happen)

I also use eloquent for the data if it makes a difference.

Maybe it is my terrible coding, but I don't see why it would randomly give me an empty response with this code. Since it dies very early in the code.

I can package the entire project if needed, it is pretty small...

I can't really figure out what to do about this.

Nginx 1.4.6
HHVM 3.9.0

**Comment by Zyles** [comment]
Also if I edit vendor/dingo/api/config/api.php and set:

```
'conditionalRequest' => env('API_CONDITIONAL_REQUEST', false),
```
Since it does not seem to read .env file has no effect either.

dump($response) looks like this:
```
Response {▼
  #binding: null
  +original: null
  +exception: null
  +headers: ResponseHeaderBag {▶}
  #content: ""
  #version: "1.0"
  #statusCode: 304
  #statusText: "Not Modified"
  #charset: null
}
```

**Comment by Kyslik** [comment]
It is browser thing read this http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304

**Comment by Zyles** [comment]
@Kyslik

Ok, and?

The response content is still empty. In PHP and I can't turn off this "feature".

**Comment by jasonlewis** [comment]
Hey @Zyles it looks like this was an issue with the service provider not setting the configuration value of `API_CONDITIONAL_REQUEST` on the router itself. I've since pushed a patch for that.

You can also set the conditional requests on the API group itself.

```php
$api->version('v1', ['conditionalRequest' => false], function ($api) {
    //
});
```

Let me know how you go.

**Comment by Zyles** [comment]
Seems to work. Thanks.

**Comment by jasonlewis** [comment]
FYI you don't need to set it on the group if you update. :smile:
