### ISSUE TITLE
Custom exception with error messages

### ISSUE THREAD

**Issue by Zyles** [dingo/api#617]
Another newbie issue here.

How do you create a custom exception with the error message included?

I copied dingos ResourceException to App/Exceptions/ValidationException.php and changed the namespace etc.

But it will only display the error message, code and stacktrace, not the error message part like "name is required" from $validator->errors()

I found the code that does this in vendor/dingo/api/src/Exception/Handler.php
```
if ($exception instanceof ResourceException && $exception->hasErrors()) {
            $replacements[':errors'] = $exception->getErrors();
        }
```

But how do I implement this in my own handler?

All in all I simply want to create a custom exception that throws my custom HTTP status code with the messagebag. Maybe there is a better way to do it.

Thanks.

**Comment by jasonlewis** [comment]
Hey mate I've just pushed a new contract to make this even easier.

Just extend the `Symfony\Component\HttpKernel\Exception\HttpException` class and implement `Dingo\Api\Contract\Debug\MessageBagErrors`.

The interface let's you define the two methods to determine if errors exist and to fetch them. You can create your own exceptions from this so you can throw your own status codes.
