### ISSUE TITLE
Enum parameters in Api Blueprint documentation

### ISSUE THREAD

**Issue by stygiansabyss** [dingo/api#618]
Just curious, is there a way to handle the enum type for a parameter?

**Comment by lightvision** [comment]
Look in the api blueprint docs. I guess it have.

**Comment by stygiansabyss** [comment]
They do show this as an option.  I just don;t see how to get that functionality in the Dingo api:docs command.

**Comment by stygiansabyss** [comment]
Closing since this has 2 PRs open in blueprints.
