### ISSUE TITLE
JWT Authorization header

### ISSUE THREAD

**Issue by spawn-guy** [dingo/api#620]
although i do know, that this situation might not happen with base64 char-"set", but anyway.

I implemented a custom Auth provider, and copied parts of Dingo\Api\Auth\Provider\JWT
so one place took my attention:
`return trim(str_ireplace($this->getAuthorizationMethod(), '', $request->header('authorization')));`
https://github.com/dingo/api/blob/master/src/Auth/Provider/JWT.php#L87

problem is - it replaces ALL the occurrences. 

_in my case it was "device some-device-id" which replaced both "device" in the value_

proposed fix
`return trim(substr($request->header('authorization'), strlen($this->getAuthorizationMethod())));`
or even `strlen+1`

**Comment by jasonlewis** [comment]
Very valid points raised, thank you. I doubt it would ever become an issue though with a base64 string. If you like you can send a PR though, would happily merge it.
