### ISSUE TITLE
Advanced Transformer via config and Closure stopped working

### ISSUE THREAD

**Issue by spawn-guy** [dingo/api#621]
after update from **0.10** to **1.0.-beta2** Transformer configuration stopped working. (as still described in Docs)

`Argument 2 passed to Dingo\Api\Transformer\Factory::__construct() must be an instance of Dingo\Api\Contract\Transformer\Adapter, instance of Closure given, called in *removed*\vendor\dingo\api\src\Provider\ApiServiceProvider.php on line 288 and defined`

I suppose, due to removal of `is_callable()` check in `ApiServiceProveder->prepareConfigValue`

manually editing it back - solves the problem.

```
protected function prepareConfigValue($instance)
    {
        if (is_callable($instance)) {
            return call_user_func($instance, $this->app);
        } elseif (is_string($instance)) {
            return $this->app->make($instance);
        } else {
            return $instance;
        }
    }
```

if this is intended behavior - tell me the official way

**Comment by jasonlewis** [comment]
Sorry the docs have been updated in that section now. I've missed a few spots so I can understand the confusion. You can't use callbacks in configuration now due to how Laravel caches config files.

You can configure it in a service providers boot method.

```php
$this->app['Dingo\Api\Transformer\Factory']->setTransformer(function ($app) {
     return new Dingo\Api\Transformer\Adapter\Fractal(new League\Fractal\Manager, 'include', ',');
});
```

**Comment by dennisoderwald** [comment]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Dingo\Api\Transformer\Factory::setTransformer()

**Comment by muhammadshakeel** [comment]
$this->app['Dingo\Api\Transformer\Factory']->setAdapter(function ($app) {
        return new \Dingo\Api\Transformer\Adapter\Fractal(new \League\Fractal\Manager, 'include', ',');
    });

@dennisoderwald This worked for me (Use setAdapter method instead of setTransformer)

But still I am unable to include related objects, looking into it.

**Comment by igustafson** [comment]
I get the same error as @dennisoderwald on Fractal 0.13.0 trying to use the `setTransformer` method; `setAdapter` seems to work, though. Seems like this issue is real and shouldn't have been closed (at least without an update to the docs).
