### ISSUE TITLE
Issue with password reset 

### ISSUE THREAD

**Issue by thoskam** [dingo/api#624]
I'm trying to implement the password reset functionality that comes baked into Laravel. Based on Laravel's documentation and Dingo's I modified the routes to as follows: 

       $api->post('password/email', 'App\Http\Controllers\Auth\PasswordController@postEmail');
        $api->get('password/reset/{token}', 'App\Http\Controllers\Auth\PasswordController@getReset');
        $api->post('password/reset', 'App\Http\Controllers\Auth\PasswordController@postReset');

Except when I do a POST with email field to "password/email" and I get:
  "message": "Maximum function nesting level of '100' reached, aborting!",
"debug": {
    "line": 347,
    "file": "/home/vagrant/code/site/vendor/composer/ClassLoader.php",
    "class": "Symfony\Component\Debug\Exception\FatalErrorException",

I'm afraid i'm too much of a newbie to even begin to guess whats going on here . Any help?

**Comment by jasonlewis** [comment]
The baked in reset functionality won't work so well in an API environment, because, well, you can't fill out forms through API calls.

Do you plan on utilizing an e-mail address still that contains the token to authorize the reset?
