### ISSUE TITLE
Turn off eager loading.

### ISSUE THREAD

**Issue by bweston92** [dingo/api#625]
How am I able to turn off eager loading? It assumes just because I make a paginator instance that there is a method `load` on my personal paginator.

**Comment by jasonlewis** [comment]
When configuring the transformer adapter:

```php
app('Dingo\Api\Transformer\Factory')->setAdapter(function ($app) {
    return new Dingo\Api\Transformer\Adapter\Fractal(new League\Fractal\Manager, 'include', ',', false);
});
```

The last option disables eager loading.

Eager loading should only apply if your pagination contains a collection that is an instance of `Illuminate\Datbase\Eloquent\Collection`.

**Comment by bweston92** [comment]
Sorry but that last statement is false I don't use Eloquent collections anywhere in my code which is why it fails to call "load".




Also that's a little overkill to switch of a basic feature?



—

**Comment by bweston92** [comment]
You check if it is a Eloquent collection or a paginator instance, yeah a paginator doesn't have a `load` method.

https://github.com/dingo/api/blob/master/src/Transformer/Adapter/Fractal.php#L146

**Comment by bweston92** [comment]
Looks as if I don't have latest version, will checkout latest version and try again.

**Comment by jasonlewis** [comment]
You're right, I'll add a method to easily switch this off and on.

And yes, if you don't have the [`shouldEagerLoad`](https://github.com/dingo/api/blob/master/src/Transformer/Adapter/Fractal.php#L112) method then you'll need to update.

**Comment by starovoitovs** [comment]
Resolve the factory and call `disableEagerLoading()` on it:

    use Dingo\Api\Transformer\Factory;
    ...

    app(Factory::class)->disableEagerLoading();

See discussion here: https://github.com/dingo/api/issues/1096
