### ISSUE TITLE
Injected form request path is `/` but Request::path() is `my/path`

### ISSUE THREAD

**Issue by bweston92** [dingo/api#626]
I checked everything in the server array is all passed when creating the form request and it is, how-ever the path that is returned is always `/`put if I use the request facade I get the correct path.

**Comment by jasonlewis** [comment]
Can you explain that in a little bit more details, perhaps with some code?

**Comment by bweston92** [comment]
```
class MyController
{
  public function abc(MyRequest $request)
  {
    var_dump($request->path()); // `/`
    var_dump(Request::path()); // Correct path.
  }
}
```

**Comment by bweston92** [comment]
Seems like input isn't working too.

```
class MyController
{
  public function abc(MyRequest $request)
  {
    var_dump($request->get('limit')); // null
    var_dump(Request::get('limit')); // Correct value from request.
  }
}
```

**Comment by bweston92** [comment]
For some reason the container is building it and not using the `createFromIlluminate` method.

**Comment by jasonlewis** [comment]
I can't seem to be able to recreate this. I'm getting the correct path and inputs.

**Comment by bweston92** [comment]
Ok I know that `createFromIlluminate` doesn't get called, do you know where I can start debugging?

**Comment by bweston92** [comment]
Ok both input and path if I extend `Dingo\Api\Http\FormRequest` but not `Dingo\Api\Http\Request` however I'm not wanting the form request as I don't need validation or authentication checks.

**Comment by jasonlewis** [comment]
Working fine from my testing mate.

**Comment by bweston92** [comment]
Weird that it works on form request and then I just remove the word `form` and use the normal request it no longer works...

**Comment by jasonlewis** [comment]
Yeah I don't know what to tell you, it's working fine for me using `Dingo\Api\Http\Request` for both Postman, browser, and internal requests.

**Comment by bweston92** [comment]
Sorry but I've just done a fresh install will push it and link it.

**Comment by bweston92** [comment]
Reproduce:

- Clone https://github.com/bweston92/dingo-api-regular-request-issue
- Composer install. (I committed lock file just to be on safe side)
- Run artisan serve.
- Goto `http://localhost:8000/api/test1?a=1` (regular request)
- Goto `http://localhost:8000/api/test2?b=1` (form request)

**Comment by jasonlewis** [comment]
This seems to be just how Laravel handles requests in general that are type-hinted from what I can tell and from according to the source.

If you take a look at the following provider you'll see the magic performed that sets up a `FormRequest` instance by initializing it, etc: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php

If you just want a `Request` instance then just type-hint a `Request` instance. Unless you need specific functionality on your own instance in which case you'll need to bind it to the container and initialize the request manually much like how Laravel is doing it automatically for form requests.

**Comment by bweston92** [comment]
Ahh, so how was it already working for you, as stated "Working fine from my testing mate.".

**Comment by jasonlewis** [comment]
I wasn't extending a form request, I was just injecting a regular request.
