### ISSUE TITLE
JWT Token Refresh

### ISSUE THREAD

**Issue by jamiehd** [dingo/api#628]
I'm trying to set up token refreshing using dingo/jwt-auth. I've found that if I use both the api.auth AND jwt.refresh middleware I can achieve this, however I would like to avoid having to use both as it feels a bit clunky. At the moment it performs its checks twice and I also have to list both middlewares on all of my protected routes.

Ideally I'd like a way to just specify one middleware. I have tried just using jwt.refresh, but when I use the artisan routes command it is not properly identified as a protected route. It also means I have to specify the particular method of authentication I am using everywhere rather than just in the config of dingo.

Is there a way round this or do I need to continue using both sets of middleware?

**Comment by jasonlewis** [comment]
I'll investigate and see if we can't get better support for it built-in.

**Comment by jamiehd** [comment]
Wonderful! Thank you.

**Comment by stojankukrika** [comment]
:+1:

**Comment by tommy7600** [comment]
+1

**Comment by Kyslik** [comment]
+1

**Comment by mwaa** [comment]
+1

**Comment by lemonCMS** [comment]
+1

**Comment by jlien-calwater** [comment]
What is the correct way to setup the current refresh route?

Like so?
```php
$api->version('v1', ['middleware' => ['api.auth', jwt.refresh]], function ($api) {
    // Routes
});
```

**Comment by ryanwinchester** [comment]
+1

**Comment by aios** [comment]
So what is best way to refresh token?

**Comment by zjien** [comment]
So what is best way to refresh token????? +1

**Comment by khairahmanplus** [comment]
+1

**Comment by Luddinus** [comment]
+1

**Comment by morenDev** [comment]
+1

**Comment by ljieyao** [comment]
no update on this?

**Comment by manyeung** [comment]
+1

**Comment by isneezy** [comment]
+1

**Comment by specialtactics** [comment]
I'm a bit confused here.

Wouldn't a refresh route just be a normal authenticated route which has the logic (in controller) to issue a fresh token?

Which authentication provider package are you using?

I am using Tymon JWT, and here's my example (authenticated auth routes group)

```php
        $api->group(['prefix' => 'auth'], function ($api) {
            $api->group(['prefix' => 'jwt'], function ($api) {
                $api->get('/fresh', 'App\Http\Controllers\Auth\AuthController@refresh');
                $api->delete('/token', 'App\Http\Controllers\Auth\AuthController@logout');
            });

            $api->get('/me', 'App\Http\Controllers\Auth\AuthController@getUser');
       });
```

And for the controller function - 

```php
    /**
     * Refreshes a jwt (ie. extends it's TTL)
     *
     * @return Response
     */
    public function refresh()
    {
        return $this->respondWithToken(auth()->refresh());
    }
```
