### ISSUE TITLE
PHPunit Test

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#629]
Hey, 

I did not find an answer in the questions asked before. So should this work with lumen and dingo?
```php
    /**
     * @test
     */
    public function get_something()
    {
        $response = $this->call('GET','/');
        $this->assertEquals(self::HTTP_OK, $response->getStatusCode());
    }
```
With this in routes:

```php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('/', function(){
        return 'test';
    });
});
```

Phpunit says: `Failed asserting that 404 matches expected 200.` But in the browser it works fine. I suspect this is a problem due using a custom router? Can this somehow be done, or do I need to use guzzle?

Just fyi, this works fine in phpunit:

```php
$app->get('/test', function () use ($app) {
    return 'test';
});
```

Should this be known and "intended" maybe you could add something to the wiki.

**Comment by jasonlewis** [comment]
Should work fine. Have you configured a prefix or domain? If so you'll need to include that in the URI.

```php
$response = $this->call('GET','/api');
```

**Comment by lukasoppermann** [comment]
Hmm, no I am using the domain, this is in my phpunit.xml

```xml
        <env name="API_STANDARDS_TREE" value="vnd"/>
        <env name="API_SUBTYPE" value="myapi"/>
        <env name="API_DOMAIN" value="api.myapi.app"/>
        <env name="API_VERSION" value="v1"/>
```

Those are my tests:

```php
    /**
     * @test
     */
    public function get_something()  // does not work
    {
        $response = $this->call('GET','/');
        $this->assertEquals(self::HTTP_OK, $response->getStatusCode());
    }
    /**
     * @test
     */
    public function get_something_else() // works
    {
        $response = $this->call('GET','/test');
        $this->assertEquals(self::HTTP_OK, $response->getStatusCode());
    }
```

And this is in my route.php

```php
$app->get('/test', function () use ($app) {
    return 'test';
});

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('/', function(){
        return 'test';
    });
});
```

**Comment by jasonlewis** [comment]
So you'll need to include the domain for all your tests.

```php
$response = $this->call('GET', 'http://api.myapi.app');
```

**Comment by lukasoppermann** [comment]
Wow, thats an easy solution, thanks. :) Is this documented somewhere? Because I did not find it? Fixed my problem thought, thanks.

**Comment by jasonlewis** [comment]
It's not, but this behaviour is consistent with how Laravel handles sub-domain routing in general.

For example:

```php
Route::get('/', ['domain' => 'foo.bar', function () {
    return 'hello world';
}]);

Route::get('/', function () {
    return 'hello universe';
});
```

To test the first route you would need to supply the domain:

```php
$this->call('GET', 'http://foo.bar/');
```

And the second, no domain is required:

```php
$this->call('GET', '/');
```

This may be documented on Laravel's side of things. I'm not sure. It's Laravel specific though and is in no way something special that Dingo is doing. :smile:

**Comment by lukasoppermann** [comment]
Ahh, I see, okay. I don't think it is mentioned on the lumen docs http://lumen.laravel.com/docs/testing, but I guess now people can at least find this issue and retrieve the right solution form it. :smile:

I would guess not everybody has used a subdomain in tests before. At least with the lumen testing router & wrapper. Cheers.

**Comment by jasonlewis** [comment]
You're using Lumen? Lumen doesn't even support sub-domain routing...

**Comment by lukasoppermann** [comment]
Why is it working than? Also what do you mean by subdomain routing exactly? Because the subdomain api.myapi.com is pointed directly at the installation. Is this going to blow up? I hope not. :smile: should I provide you with some info of something?

**Comment by jasonlewis** [comment]
Okay, okay, it's fine. I wasn't aware that you had the sub-domain pointing at the Lumen installation.

When I say sub-domain routing I mean with Laravel it allows you to use like wildcard sub-domains on specific route groups or routes, etc. Like what I demonstrated above.

If this Lumen install is just going to be for your API, don't bother setting an `API_DOMAIN`, just set `API_PREFIX` to `/`.

**Comment by lukasoppermann** [comment]
Hmm, the `API_PREFIX ` actually kills it.

With `API_DOMAIN=api.myapi.app` it works fine with a `API_PREFIX=/` I get a 404. Any Idea what I am doing wrong?

**Comment by jasonlewis** [comment]
404 where? In your tests or web browser?

**Comment by lukasoppermann** [comment]
Sorry, in my browser & in my tests.

**Comment by jasonlewis** [comment]
Hm, working fine on my end. What do your routes look like?

**Comment by lukasoppermann** [comment]
Hmm, so using this routes `/` works but `test` does not work

```php
$api = app('Dingo\Api\Routing\Router');
$api->group([
    'version' => 'v1',
    'namespace' => 'App\Api\V1\Controllers',
], function($api)
{
    $api->get('/', function(){
        return 'Test';
    });
    $api->get('test', function(){
        return 'Test 2';
    });
});
```

**Comment by jasonlewis** [comment]
What version of this package are you using?

**Comment by lukasoppermann** [comment]
Ahhh, apparently I was using `0.1.0` now using `@dev` it works. Thanks.
