### ISSUE TITLE
Get route parameters in middleware

### ISSUE THREAD

**Issue by Zyles** [dingo/api#630]
I want to get route parameters in my middleware. Not just the query string parameters but also the URL parameters such as /api/{namespace}/users for example into $namespace.

I tried to use the actions listed here: http://laravel.com/api/5.0/Illuminate/Routing/Route.html

For example:
```
$request->route('namespace')
or
$request->route()->getName()
```

But get error:
```
 Call to a member function getName() on a non-object (array)
```

die(get_class($request)); returns
```
Dingo\Api\Http\Request
```

So I assume it is a Dingo request issue that I can't use any of these commands?

Thanks.

**Comment by jasonlewis** [comment]
You won't be able to do that until you call `$next($request)` because the route hasn't been initialized yet. This doesn't just apply to the API but Laravel in general.

Or you can use a route based middleware instead of a global middleware. That way the route is initialized and you can access the parameters.

**Comment by Zyles** [comment]
I am, it is not working since Dingo returns an array.

```
    public function handle($request, Closure $next)
    {

        $response = $next($request);

        dd($request->route()->getName());
```

```
Call to a member function getName() on a non-object (array)
```

**Comment by jasonlewis** [comment]
If you're using Lumen then that's what the route looks like I'm afraid.

You can always use `app('api.router')->current()` to have Dingo make a `Route` instance for you.
