### ISSUE TITLE
Class App\\Api\\Controllers\\UserController does not exist

### ISSUE THREAD

**Issue by phoenixg** [dingo/api#632]
For creating endpoints in `https://github.com/dingo/api/wiki/Creating-API-Endpoints`

```php
$api->version('v1', function ($api) {
    $api->get('users/{id}', 'App\Api\Controllers\UserController@show');
});
```
When I use the  `'App\Api\Controllers\UserController@show'` same as doc, it got error:

` Class App\\Api\\Controllers\\UserController does not exist `

I've no idea where to put this UserController, although if I changed it to `App\Http\Controllers\UserController@showProfile'` it works. But how I can use it like the doc said?

seems similar to this:   [ https://github.com/dingo/api/issues/398]( https://github.com/dingo/api/issues/398)

**Comment by jasonlewis** [comment]
It just comes down to how you want to organise your controllers. The docs assume you're going to place your API controller separate from your regular Http controllers. So, you would need to create the folders at `app/Api/Controllers`, and then add your `UserController` there with a namespace of `App\Api\Controllers`. Again, this assume you haven't changed the name of your application, in which case the namespace would also be different.

**Comment by maojindao55** [comment]
@jasonlewis  I had this problem too, and do as your method, but it not work.  need controller register in lumen?

**Comment by Sennik** [comment]
@jasonlewis: great, thanks!

**Comment by shahzadafridi** [comment]
Hi jasonlewis,

Thanks man you just saved my day! I have spent hours to encounter the error and solve but your short description help me alot in resolving the issue. Thanks man.
