### ISSUE TITLE
Trailing slash in API_DOMAIN

### ISSUE THREAD

**Issue by MetalMatze** [dingo/api#633]
The last few hours I've been struggeling to get the routes to work.

Making a `dd($api);` in the routes.php revealed that a slash is missing:
```
"krautreporter.dev:8000authors" => Route {#133 ▶}
"krautreporter.dev:8000authors/{id}" => Route {#134 ▶}
"krautreporter.dev:8000articles" => Route {#135 ▶}
"krautreporter.dev:8000articles/{id}" => Route {#136 ▶}
```

My .env entry for `API_DOMAIN` is:
```
API_DOMAIN=krautreporter.dev:8000
```
This is just like in the wiki: https://github.com/dingo/api/wiki/Configuration#prefixes-and-subdomains

Next step was to add the missing trailing slash to `API_DOMAIN`. Now `dd($api);` produces:
```
"krautreporter.dev:8000/authors" => Route {#133 ▶}
"krautreporter.dev:8000/authors/{id}" => Route {#134 ▶}
"krautreporter.dev:8000/articles" => Route {#135 ▶}
"krautreporter.dev:8000/articles/{id}" => Route {#136 ▶}
```

This looks fine. 
Removing the `dd` and hitting the first route sadly returns a `NotFoundHttpException in RouteCollection.php line 143:` :disappointed: 

Am I missing something?

**Comment by MrHexagon** [comment]
Try using API_PREFIX and leaving API_DOMAIN null. That's what I do.

**Comment by MetalMatze** [comment]
Thanks for the hint. `API_PREFIX=/` works now. It just feels like I'm misusing `API_PREFIX`.

**Comment by jasonlewis** [comment]
You shouldn't need to worry about the trailing slash. The array key isn't
actually used to grab the route, it's just used as an identifier of sorts I
suppose.

Did it not work just as krautreporter.dev:8000?
