### ISSUE TITLE
Auth Returning 405

### ISSUE THREAD

**Issue by JustinLien** [dingo/api#634]
I have been struggling with authenticating issue for the past few days.

I have this setup:

Setup:

```php
'auth' => [
		'basic' => function ($app) {
			return new Dingo\Api\Auth\Provider\Basic($app['auth']);
		},

		'jwt' => function ($app) {
			return new Dingo\Api\Auth\JWTProvider($app['tymon.jwt.auth']);
		},
	],
```

My autthentcation route:

```php
$api->get('authenticate/user', ['middleware' => 'api.auth', 'providers' => ['jwt'], function () {

		// This route requires authentication.
		$user = app('Dingo\Api\Auth\Auth')->user();
		return $user;

	}]);
```

POSTMAN error:

![image](https://cloud.githubusercontent.com/assets/688800/9742007/8b1be7f4-5612-11e5-9dec-e796798a62bb.png)

I don't know this makes any differences if I am running local PHP server.

I have confirmed the route is protecting correctly.

![image](https://cloud.githubusercontent.com/assets/688800/9742090/05e01a14-5613-11e5-9df0-87a31dd5c3a2.png)

What am I doing wrong?

I am using version 0.10.0.

**Comment by sunel** [comment]
@JustinLien  the ``` api/authenticate/user ``` accepts only ```GET``` but your trying it using ```POST``` method update your postman to send ```GET``` request

**Comment by JustinLien** [comment]
@sunel I feel really stupid right about now. =X

I fixed that and it complains about "JWTProvider" not found.

Update that to new path:

```php
'auth' => [
		'jwt' => function ($app) {
			// return new Dingo\Api\Auth\JWTProvider($app['tymon.jwt.auth']);
			return new Dingo\Api\Auth\Provider\JWT($app['tymon.jwt.auth']);
		},
	],
```

We're golden. Thanks sunel!!!

**Comment by jasonlewis** [comment]
Note that in the newest version you can't use closures in your config file.

**Comment by sunel** [comment]
:+1:

**Comment by jasonlewis** [comment]
Did you re-open this for a reason @JustinLien?

**Comment by JustinLien** [comment]
@jasonlewis sorry, no it was an accident. Must have happened when I was viewing it on the phone. Closing!

Thank you for an awesome package BTW!

Thanks for the heads up about closures in config file.

<hr>
Some feedback: I wish there were some sort of feature list or upgrade history and more example (if not complete) in your documentation. (I can help with that if needed)

For an example, Facades in the installation section.

You gave example for the providers:

```php
'providers' => [
    Dingo\Api\Provider\LaravelServiceProvider::class
]
```

But in your Facades section you gave just the class.

```php
Dingo\Api\Facade\API
Dingo\Api\Facade\Route
```

For consistency and clarity I would use the same approach. (you can disagree with me)
```php
'DingoApi' => Dingo\Api\Facade\API::class,
'DingoRoute' => Dingo\Api\Facade\Route::class,
```
Then perhaps followed by an example.
```php

// App\Http\routes.php

DingoRoute::version('v1', , function ($api) {

   // routes here

});

```
Another area is the API Endpoints.
```php
$api->version('v1', function ($api) {

});
```
Would be nice to provide example of what this route would be.
At first, I thought this would give us an URL of api/v1/your_route_here.

Sorry, it was my first time going through your documentation and those were some (not all) of the questions I had while I was reading them.

Again, awesome work here!
