### ISSUE TITLE
Route Model Binding on the API Router

### ISSUE THREAD

**Issue by DraperStudio** [dingo/api#636]
Is there any way to use Route binding on the API Router out of the box?

I couldn't really figure out a way to do it and neither an elegant way of extending/replacing the API Router.

What would be the best way to put Route Model Binding into the API Router?

**Comment by DraperStudio** [comment]
Nevermind, solved.

**Comment by Remade** [comment]
@DraperStudio  What was your solution? I am at this stage at the moment
