### ISSUE TITLE
Rename 'Dingo\Api\Http\Response\Factory::array'

### ISSUE THREAD

**Issue by mrgrain** [dingo/api#637]
Hello,
first awesome package, I love it! :smile: 

Second, I would suggest to rename the pseudo method [`Dingo\Api\Http\Response\Factory::array()`](https://github.com/dingo/api/blob/master/src/Http/Response/Factory.php#L251) to something else.

Why? Because `array` is a [reserved keyword](http://php.net/manual/en/reserved.keywords.php) in PHP. It might not cause any troubles right now, but it just can't be guaranteed. Plus there are numerous good reasons to follow this 'standard':
* You have to use a hack to make it work
* One (not so advanced user) might mistaken it with the actual array language construct
* You don't have a proper class method to inspect, reflect, etc.
* IDEs get confused about it
* Any static code analyser might get confused

Also the naming is actual incorrect, because the method is not responding with an array, but rather with the raw content. Just compare the result of those two controller methods:
```php
    public function raw()
    {
        return array(); // Response: []
    }

    public function asArray()
    {
        return $this->response->array(array()); // Response: []
    }
````

Thus, I suggest to rename said method to `raw` or something similar, unless you don't want to drop it anyway (cause it is rather superfluous).

**Comment by jasonlewis** [comment]
I'm all for a name change, because yes, it is a reserved word in PHP.

My only argument is that the name of the method isn't what it's returning but what you're giving it. Because there's `Factory::collection`, `Factory::paginator`, etc, etc.

When it comes down to it you can simply return an array as is without the response builder. The only reason that method is there is because people like consistency.

So I'm not too sure about the `raw` name either.

**Comment by mrgrain** [comment]
Fair enough, but as far as I get the method, the argument will only be passed through to [`Illuminate\Http\Response::setContent`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Http/Response.php#L41) which actually accepts more than just arrays (to be specific: `array` `ArrayObject` `Jsonable` `Renderable`) and later on in [Symfony's response](http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Response.html#method_setContent) it even accepts anything that can be casted to a string. 

So maybe something like `jsonable` or `stringable`?

But at the end it would probably suggest to remove (deprecate) it at all and tell the user to just return the plain thingy. It would even be more consistent, as the other methods provide functionality within dingo/api, where `array` does not.

**Comment by jasonlewis** [comment]
Yeah that's a fair point. I think deprecating would probably be the best approach here, because really, it isn't needed. Will go with that.

**Comment by jasonlewis** [comment]
It's now deprecated.
