### ISSUE TITLE
What is Standards Tree and what does it functions

### ISSUE THREAD

**Issue by lanffy** [dingo/api#638]
Hello,forgive me asked this question,but I am not understand that what is Standards Tree and what does it functions.
I read [RFC4288](http://www.ietf.org/rfc/rfc4288.txt) but still do not konw it functions.
Please give a example I you can.
Thank you very much:)
```
Standards Tree

There's three different trees: x, prs, and vnd. The standards tree you use will depend upon the project you're developing.

The unregistered tree (x) is primarily meant for local or private environments.
The personal tree (prs) is primarily meant for projects that are not distributed commerically.
The vendor tree (vnd) is primarily meant for projects that are publically available and distributed.
Subtypes using the personal or vendor trees are technically meant to register with the IANA.
You can configure this in your .env file.

API_STANDARDS_TREE=vnd
```

**Comment by Deleugpn** [comment]
I'm currently having this exact doubt. I just installed Dingo API in my Laravel Project and I'm going through the Configuration on Wiki and I have no clue on what Standard Trees are suppose to mean.

**Comment by mohislm** [comment]
Same here. I don't understand it either!!!

**Comment by zjien** [comment]
Same,what is it?

**Comment by NicksonYap** [comment]
I bumped into this, it lsits and describes the types of trees:
https://tools.ietf.org/html/rfc4288#section-3.1

**Comment by Deleugpn** [comment]
I read that before bumping this topic and I gotta say that it helped me with nothing.
