### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by reatang** [dingo/api#639]
If I want see api error log, how to go to the Log record？

**Comment by sunel** [comment]
@reatang there is no serrate log file for apis , everything will be logged in default application (laravel or lumen ) log 

[Laravel](http://laravel.com/docs/5.1/errors)
[Lumen](http://lumen.laravel.com/docs/errors)

**Comment by jlien-calwater** [comment]
Also you want to enable debug mode:

https://github.com/dingo/api/wiki/Configuration#debug-mode

And have all your errors and error responses at your dispoal:

**Comment by reatang** [comment]
@jlien-calwater  I set the API_DEBUG=true, but there is not written error to the logfile `storage/logs/laravel.log` . _(:3」∠)_

**Comment by reatang** [comment]
@sunel Error only send to browser, not written error to the logfile.

**Comment by sunel** [comment]
@reatang Can you check with file permission

**Comment by reatang** [comment]
@sunel  yes,777  ! QAQ , and I can't use try {} catch () {}  capture exception ，trouble...... . My program directly out of the race。

**Comment by jlien-calwater** [comment]
@reatang 

You can write an exceptions handler to write to to your log.

```php
// App\Exceptions\Handler.php

public function render($request, Exception $e)
{
    if ($e instanceof ModelNotFoundException) {
        $e = new NotFoundHttpException($e->getMessage(), $e);
    } else if ($e instanceof Dingo\Api\Exception\StoreResourceFailedException) {
        Log::error('StoreResourceFailedException error');
    }

    return parent::render($request, $e);
}

```

You can add these exceptions if you like: https://github.com/dingo/api/wiki/Errors-And-Error-Responses#resource-exceptions

Re: "Error only send to browser, not written error to the logfile."

What is that error? It sounds more like you have other issue rather than the log file.

**Comment by reatang** [comment]
@jlien-calwater  yes , your right!  log file was fine. error (syntax error or exception) content not written to log file, only show to the browser . 
(my english is not good ~)
