### ISSUE TITLE
CORS issue when responding with error

### ISSUE THREAD

**Issue by gerob** [dingo/api#64]
Using Angular to create a SPA, it works fine as long as my API isn't responding with an error. Take for example this code:

``` php
try {
     return User::findOrFail($user_id);
} catch (ModelNotFoundException $e) {
     throw new ResourceException("No user record found.");
}
```

If the user is found, Angular successfully retrieves the data. However if the record does not exist then this error is thrown.

```
XMLHttpRequest cannot load http://api.example.com/users/. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://my-angular-site.com' is therefore not allowed access. 
```

Successful requests have these headers:

```
Access-Control-Allow-Origin →*
Cache-Control →no-cache, private
Connection →keep-alive
Content-Type →application/json
Server →nginx
Transfer-Encoding →chunked
X-Frame-Options →SAMEORIGIN
date →Fri, 23 May 2014 13:27:26 GMT
```

Responses provided by throwing an error have these headers:

```
Cache-Control →no-cache, private
Connection →keep-alive
Content-Type →application/json
Server →nginx
Transfer-Encoding →chunked
X-Frame-Options →SAMEORIGIN
date →Fri, 23 May 2014 13:31:29 GMT
```
## UPDATE:

If I use the following code then returning the errors works. 

``` php
try {
     return User::findOrFail($user_id);
} catch (ModelNotFoundException $e) {
     header('Access-Control-Allow-Origin: *');
     throw new ResourceException("No user record found.");
}
```

**Comment by kabelo38** [comment]
works well for me using .htaccess file

<IfModule mod_headers.c>
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Access-Control-Allow-Origin "*"
    Header set Pragma "no-cache"
    Header set Expires 0
</IfModule>

$user = User::findOrFail('1');
try {
return 'User not found ' ;

		} catch (ModelNotFoundException $e) {

			throw new ResourceException("No user record found.");
		}

**Comment by Deleugpn** [comment]
I'm currently facing this problem when making calls from AngularJS to my Laravel API. Does Dingo still have no way to address this? Do I need to appeal to another library such as barryvdh/laravel-cors?

**Comment by joshstrange** [comment]
I'm also interested in what the "Agreed upon" way to handle CORS within dingo is.
