### ISSUE TITLE
Defining duplicate URIs for two different subdomains (web app & API)

### ISSUE THREAD

**Issue by swvjeff** [dingo/api#643]
I've configured Lumen and Dingo to separate my API and web app into two different subdomains (api.example.com and www.example.com). In doing so, I noticed that I can't create an API endpoint that has the same URI as one of my app route URIs (e.g. http://api.example.com/users and http://www.example.com/users). 

Ideally my front-facing website would have the same endpoint/route URIs as my API, but I'm not sure if it's possible. Is there any way to get this working?

**Comment by lightvision** [comment]
I don't know for Lumen but in Laravel is posible.

**Comment by jasonlewis** [comment]
Lumen doesn't natively support subdomain routing so I'm not sure how you're achieving it. But I'm going to say that that is your problem. Two separate application here would be the solution. Or use Laravel.
