### ISSUE TITLE
Api Blueprint annotation Response doesn't accept lists

### ISSUE THREAD

**Issue by kadinho** [dingo/api#644]
Hello,

Im trying to use lists in my method annotation to generate documentation but seems to be unsupported:

@Response(200, body={"data" : [{"id": 10, "username": "foo"},{"id": 10, "username": "foo"},{"id": 10, "username": "foo"}]})

Got: 

[Doctrine\Common\Annotations\AnnotationException]
  [Syntax Error] Expected PlainValue, got '[' at position 6
  9 in method App\Http\Controllers\Api\v1\UsersController::
  index().

Thx
CV

**Comment by elceka** [comment]
You must use another syntax, not pure JSON syntax ([] => {}).

@Response(200, body={"data": {{"id": 10, "username": "foo"},{"id": 10, "username": "foo"},{"id": 10, "username": "foo"}}})

**Comment by kadinho** [comment]
right! thx :)
