### ISSUE TITLE
calling internally returns a JsonResponse not a Response

### ISSUE THREAD

**Issue by astroanu** [dingo/api#645]
I'm trying to call the api internally from a seeder. here's my code

```
class DeviceSeeder extends Seeder
{
    private $api;

    public function run()
    {
        $attributes = [
            'device' => [
                'uuid' => '',
                'name' => ''
            ]
        ];

            print_r($this->api->json($attributes)->get('devices'));

    }

    public function __construct()
    {
        $this->api = app('Dingo\Api\Dispatcher')->be(User::find(1));
    }
}

```

the api controller method just does this

```
    public function all(DeviceRepository $devices)
    {
        return Response::make($devices->paginate(10));
    }
```

and this exception gets thrown 

```
Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an insta
nce of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in c:\project\vendor\dingo\api\src\Dispatcher.php on line 513 and defined in ..

```

it appears the Dispatcher needs to throw a Response object but it receives a JsonResponse object. Where is this happening from . The api alone seems to be working fine. This happens only with internal requests.

**Comment by jasonlewis** [comment]
I'll take a look but it does appear as though an exception is being thrown from your internal request.

**Comment by hasokeric** [comment]
i am getting the same issue when trying to call the API inside routes.php not sure what i am doing wrong.

**Comment by agkunz** [comment]
Was originally experiencing this issue on 0.9, https://github.com/dingo/api/issues/462.
I had extended FormRequest myself, general consensus on the above issue seemed to be to use the one included in the package.  I updated to this branch to get it.

Now, I'm getting this issue.

Here's how I'm calling it.
```
// dd('test') // good

$customer = $this->api
    ->be($user)
    ->with($billing)
    ->put('customers/' . $user->id . '/billing');

// dd('test2') // error thrown before here
```

Here's what the internal request actually looks like.
```
public function billing (UpdateAddressRequest $request, $cid)
{
    // dd('hi') // good
    $customer = $this->customers->find($cid);
    // dd('hi') // good
    $this->customers->useBillingAddress($customer, $request->all());
    // dd('hi') // good
    $response = $this->response->item($customer, $customer->getTransformer());
    // dd($response) // good, Dingo\Api\Http\Response
    return $this->response->item($customer, $customer->getTransformer());
}
```

Had it working fine the other day with the old version.  Could maybe have gone backwards and left it but I figured updating the package probably wasn't a bad idea.

Any insight would be helpful.
Thanks.

**Comment by specialtactics** [comment]
Closing due to issue age
