### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by lein00** [dingo/api#648]
im getting this error while visiting my endpoint api/users
{"message":"Undefined method App\\Api\\Controllers\\v1\\UserController::getAfterFilters","status_code":500}
$api->version('v1', ['prefix' => 'api'], function($api) {
    $api->get('users','App\Api\Controllers\v1\UserController@index');
});
here is my User Controller

namespace App\Api\Controllers\v1;
use App\User;
use Dingo\Api\Routing\Helpers;
class UserController
{
    use Helpers;
    public function index()
    {
        $users = User::all();
        return $users;
    }
}
however if i do this
$api->version('v1', ['prefix' => 'api'], function($api) {
    $api->get('users', function() {
        return User::all();
    });
});
works fine

and also
For creating endpoints in https://github.com/dingo/api/wiki/Creating-API-Endpoints
Viewing Routes In The Console
when i typed 
php artisan api:routes
i get Undefined method App\Api\Controllers\v1\UserController::getMiddleware 

any help is appreciated

**Comment by lein00** [comment]
my bad just my stupid mistake

**Comment by vailancio** [comment]
I am having similar problem. What was the mistake?

**Comment by vailancio** [comment]
Indeed it was a stupid mistake. In dingo documentation some snippets of code do not extend Illuminate\Routing\Controller. You need extend the controller from this. 

UserController extends Controller{}
