### ISSUE TITLE
API blueprint documentation in different language

### ISSUE THREAD

**Issue by cupit** [dingo/api#649]
Hi,

is there any way to write API documentation in two languages?

My comments in the code are in english, but I need to create API documentation in different language.

Any ideas? 

So far I can only translate the output from api:docs manually and then generate HTML file, but maybe somebody had already this problem and knows better solution?

For example when I create "@Response(422, body={"error": {"username": {"Username is already taken."}}})" 

tis that possible that this string "Username is already taken" will come from Laravel lang file?

thank you!

**Comment by jasonlewis** [comment]
I don't think I want to over complicate the doc generation process too much.

Feel free to investigate how plausible it would be and send a PR.
