### ISSUE TITLE
ErrorException on 1st install? (Expects array, receives null)

### ISSUE THREAD

**Issue by webkenny** [dingo/api#650]
Hi there,

First time user of this package and I followed the installation instructions. When I get to the end of the line and composer tries to call `php artisan clear-compiled` I get the following fatal error:

```
[ErrorException]
Argument 2 passed to Dingo\Api\Exception\Handler::__construct() must be of the type array, null given, called in /home/vagrant/Code/iris/api/vendor/dingo/api/src/Provider/ApiServiceProvider.php on line 125 and defined
```

I tried publishing the config thinking that was my issue but even that command produces this error. Did I do something wrong? Here's what I did:

- Added the package via composer (1.0.x@dev)
- Added the ServiceProvider to app.php
- Added the Facades

Here's the relevant pieces of my app.php:

```
Dingo\Api\Provider\LaravelServiceProvider::class
```

```
// Dingo
'API'       => Dingo\Api\Facade\API::class,
'Route'     => Dingo\Api\Facade\Route::class,
```

**Edit**: I followed this https://github.com/dingo/api/wiki/Configuration to try and publish the configuration because I'm using Laravel 5.1 but this is where the error sacks me.

Thanks! 

P.S. Big fan of Phil's book so it's fantastic to see a package take care of most of that for us. Can't wait to contribute and help out. Once I can get it working, of course. :)

**Comment by webkenny** [comment]
Fussing around a bit more and thinking maybe it had to do with the config values, I did a gradual add to my config/app.php. Meaning this:

- I added the Service Provider
- Ran `php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"`. So far, so good. This created `config/api.php`.
- Now I ran `php artisan clear-compiled` just to check for any weirdness.
- I get a new error. This time it reads" `Undefined index: version`

**Comment by webkenny** [comment]
Ok, so note to those who might drop this into an existing API you're building... make sure you convert all your routes before doing anything. :) Closing. Sorry for the noise.

**Comment by tanbrian** [comment]
Just in case the above answer isn't totally clear, I just want to add that if you're building an API alongside the main website then there's actually already a facade with the same name route: `'Route'     => 'Illuminate\Support\Facades\Route'`, so you'll have to either not use the Dingo facade or just rename it to avoid the `Undefined index: version` error.
