### ISSUE TITLE
API returns error messages in DEBUG false

### ISSUE THREAD

**Issue by cupit** [dingo/api#651]
Hi,

I think it should't return this kind of errors in production env, for example:

{
"message": "SQLSTATE[HY000] [2003] Can't connect to MySQL server on '0.0.0.0' (113)",
"status_code": 500
}

APP_DEBUG=false
API_DEBUG=false

is there any simple way to hide that message?

**Comment by jasonlewis** [comment]
Fix the error? Debug mode will only show the full stack trace.

**Comment by hallids** [comment]
I know this is a bit old, but I wanted the same type of thing. Here is my solution, although it doesn't feel particularly elegant. I put this in AppServiceProvider::boot()

```php
app(\Dingo\Api\Exception\Handler::class)->register(function (\Exception $exception) {
    if (!env('API_DEBUG') && !$exception instanceof \Symfony\Component\HttpKernel\Exception\HttpException) {
        // Whatever other handling you want..

        return \Response::make([
            'message'     => 'Internal server error',
            'status_code' => 500,
        ], 500);
    }
});
```
