### ISSUE TITLE
Eager load in polymoprhic does not work (n+1 problem)

### ISSUE THREAD

**Issue by Luddinus** [dingo/api#652]
Hi.

I have an album which have photos and photos have tags.

When I get an album
```
api/albums/1?include=photos.tags
```

It runs one query per each tag.

```
SELECT `tags`.*, `taggables`.`taggable_id` as `pivot_taggable_id`, `taggables`.`tag_id` as `pivot_tag_id` FROM `tags` inner join `taggables` on `tags`.`id` = `taggables`.`tag_id` WHERE `taggables`.`taggable_id` = '1' and `taggables`.`taggable_type` = 'App\Photo'

SELECT `tags`.*, `taggables`.`taggable_id` as `pivot_taggable_id`, `taggables`.`tag_id` as `pivot_tag_id` FROM `tags` inner join `taggables` on `tags`.`id` = `taggables`.`tag_id` WHERE `taggables`.`taggable_id` = '2' and `taggables`.`taggable_type` = 'App\Photo'

// etc
```

Am I missing something?

**Comment by Luddinus** [comment]
up

**Comment by Luddinus** [comment]
I guess I have to not use "include" in this case.

**Comment by jasonlewis** [comment]
Sorry about the delayed reply. I've been very busy with other things, just now getting a chance to go over a lot of the issues on the repository.

Taking a look at this now. :+1:

**Comment by jasonlewis** [comment]
Can't reproduce mate. Everything is being eager loaded correctly on my end.

Are you registering the Fractal adapter yourself?

**Comment by Luddinus** [comment]
What do you mean registering the Fractal adapter myself?

**Comment by jasonlewis** [comment]
You can register it yourself to disable eager loading. Sounds like you're not doing that though.

I tested both polymorphic and many to many polymorphic relations. It was running a single query with a `WHERE ... IN` fine for me.

**Comment by Luddinus** [comment]
I don't know, these are my transformers, I think they're ok.

AlbumTransformer
´´´
class AlbumTransformer extends TransformerAbstract {

	protected $availableIncludes = [
		'photos',
	];

	public function transform(Album $album)
	{
		return $album->toArray();
	}

	public function includePhotos(Album $album)
	{
		$photos = $album->photos()->orderBy('created_at', 'DESC')->get();

		return $this->collection($photos, new PhotoTransformer);
	}
	
}
´´´

PhotoTransformer
```
class PhotoTransformer extends TransformerAbstract {

	protected $availableIncludes = [
		'tags'
	];

	public function transform(Photo $photo)
	{
		return $photo->toArray();
	}

	public function includeTags(Photo $photo)
	{
		$tags = $photo->tags;

		return $this->collection($tags, new TagTransformer);
	}
	
}
```

TagTransformer
```
class TagTransformer extends TransformerAbstract {

	protected $availableIncludes = [
		// 
	];

	public function transform(Tag $tag)
	{
		return [
			'id' => $tag->id,
			'name' => $tag->name
		];
	}
	
}
```

**Comment by Luddinus** [comment]
Well, I have in composer to use version 0.10.*... I see that is a 1.0@dev version. I'll check with that version.

**Comment by jasonlewis** [comment]
I see you edited...

```php
$photos = $album->photos()->orderBy('created_at', 'DESC')->get();
```

That won't work. That will load each albums photos individually. You've since changed that line of code though, so which are you using?

**Comment by Luddinus** [comment]
Yep, but I changed to "album->photos" and it's the same. I have updated to 1.0@dev but the problem stills there.

I don't know where else it can be...
