### ISSUE TITLE
Requiring Dingo from a Laravel 5.1 app with api driven sub-packages.

### ISSUE THREAD

**Issue by vp-gcoutu** [dingo/api#653]
Hey,

I'm trying to make my application's api driven packages to require Dingo on their own. I can't seem to make it work.

I have the main application repo with Laravel 5.1 installed, Dingo normally work flawless in packages while developing (we're using a workbench folder with psr-4 autoloading the classes). We get a composer error, when we're trying to actually deploy the packages to what would be the normal use case in a production environnement (loading packages from a satis repository). Here is some part of the composer.json files..

Main app require example
"require": {
  "php": ">=5.5.9",
  "laravel/framework": "5.1.*",
  "vp/common": "dev-master",
  "vp/api-package1": "dev-master",
  "vp/api-package2": "dev-master"
},

Package require example
"require": {
  "php": ">=5.5.9",
  "dingo/api": "1.0.*@dev"
},

I assume Dingo when required from a sub-package should be added to the vendor list as normal packages do. Do Dingo need to be only required in each of our main-apps instead of inside the api packages (which would be included in a few main-apps)?

I don't think it's a bug, you're the one that can tell me if it's intended to be that way or not. 
Our solution for now is to add dingo to the main-app's composer.json, I just feel it should be in packages. Am I wrong?

**Comment by jasonlewis** [comment]
Assuming that package is being required properly then it should be installed fine. What's the Composer error your seeing?

**Comment by vp-gcoutu** [comment]
That's what I thought too. In order to work, i need to put Dingo into the main composer.json file.

![screen shot 2015-09-22 at 8 19 37 am](https://cloud.githubusercontent.com/assets/14619508/10018197/cb4d2ee6-6102-11e5-83dc-d810515cb5e7.png)

**Comment by vp-gcoutu** [comment]
Fixed, my bad I

**Comment by vp-gcoutu** [comment]
I thought we had solved the problem, we still had the issue because we have still have to keep it in the main composer.json. Here's the output.

![screen shot 2015-09-22 at 8 19 37 am](https://cloud.githubusercontent.com/assets/14619508/10054280/554930da-61fe-11e5-8b56-ad4aa8c0c895.png)

**Comment by jasonlewis** [comment]
Should be `"dingo/api": "v1.0.*@dev"`. Note the asterisks, or you can use an `x`.
