### ISSUE TITLE
Mention some Laravel specific incompatibilities in the wiki

### ISSUE THREAD

**Issue by jadjoubran** [dingo/api#655]
Hi,

I've been using dingo/api in many applications and I noticed that users of dingo/api might need to know about the following issues in the wiki (and maybe at least about their workarounds or a link to the github issue):
* Form Validation breaks routing - I know this is mentioned in the docs for Exceptions, but the solution is not. This might be the [solution](https://github.com/dingo/api/issues/584) (I tried it and it works)
* `withoutMiddleware` in tests returns 404 - This is something that can't be fixed, but I think it's worth noting. #571 

This is the only thing mentioned in the [wiki page](https://github.com/dingo/api/wiki/Package-Incompatibilities)
> The API will generally work with all other packages, however, some Laravel specific packages may conflict with the API as it integrates itself heavily with the Laravel router to provide the needed functionality.

Let me know what you think!

**Comment by jasonlewis** [comment]
Feel free to send suggestions and PRs to the [dingo/api-docs](http://github.com/dingo/api-docs) repository.
