### ISSUE TITLE
php artisan api:routes wrong Action

### ISSUE THREAD

**Issue by oleynikd** [dingo/api#663]
Hi,

First of all thank you for such a great tool!

Here's my route:
```php
$api = app('Dingo\Api\Routing\Router');
$api->version('v3', function ($api) {
    $api->post('auth/register', 'App\Http\Controllers\API\AuthController@postRegister');
});
```

And here's the result of `php artisan api:routes`:
![screenshot 2015-09-24 19 34 57](https://cloud.githubusercontent.com/assets/3976868/10079526/3a7d5664-62f3-11e5-8a9a-2e03c43a467e.png)

Why is Action = Closure?

I'm using:
* HHVM Version 3.8.0
* Laravel 5.1.17 (LTS)
* dingo/api (dev-master 4468b88)
* tymon/jwt-auth (0.5.5)

Thanks.

**Comment by jlien-calwater** [comment]
@oleynikd could be result of your controller?

I just tested this in my route.

![image](https://cloud.githubusercontent.com/assets/3473846/10107510/7dc28822-6370-11e5-9dc9-afce1e98a551.png)

Try referencing it to a plain vanilla controller.

```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

class AuthController extends Controller
{
   
    public function postRegister(Request $request)
    {
        return $request->all();
    }

}
```

**Comment by oleynikd** [comment]
I tried plain vanilla controller - that did not helped.

**Comment by oleynikd** [comment]
I'm also using [laravel/spark](https://github.com/laravel/spark)... Not sure if this changes something?

**Comment by rossedman** [comment]
I am having the same problem. If I change the controller to a class that does not exists it throws an error, but it does not register the method when set correctly.

**Comment by jlien-calwater** [comment]
@oleynikd not sure if it is supported at this time. Current support is Laravel 5.1+ or Lumen 5.1+ from what I understand. Best create a test case with plain vanilla?

**Comment by rossedman** [comment]
My problem seemed to be with subdomain vs domain. You can not set your subdomain equal to the domain. That is as far as I have got. Begs the question what if you want an API on its own domain?

**Comment by oleynikd** [comment]
I also have my API on separate subdomain using API_DOMAIN env variable, but removing it did not helped.

I tried new plain installation of laravel and dingo/api - result is the same!

Here's the simple repo to illustrate the issue: https://github.com/oleynikd/laravel-dingo-routes-test
There are 3 commits to describe changes I made.
If I do:
```
git clone https://github.com/oleynikd/laravel-dingo-routes-test.git
cd laravel-dingo-routes-test/
composer install
php artisan api:route
```
I get:
![screenshot 2015-09-28 23 27 35](https://cloud.githubusercontent.com/assets/3976868/10147717/699d1a18-6638-11e5-9bf3-b48a4b90e7ab.png)

Hope this will help.

P.S.
If you skip this step:
```
php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"
```
after `dingo\api` installation you'll get:
```
[ErrorException]
Argument 2 passed to Dingo\Api\Exception\Handler::__construct() must be of the type array, null given, called in .../vendor/dingo/api/src/Provider/ApiServiceProvider.php on line 125 and defined
```
But on [Wiki page](https://github.com/dingo/api/wiki/Installation#laravel) this step is described as optional...

Thanks.

**Comment by jasonlewis** [comment]
Just pushed a fix.

As for the exception you're see @oleynikd, place the API service provider above the application ones. That way everything is being registered and booted before your application providers are registered and booted. Will mention this in documentation.

**Comment by oleynikd** [comment]
Thank you @jasonlewis
