### ISSUE TITLE
Remove 'data' from fractal transformer includes

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#664]
Hello,

I am facing an issue where I need to keep the 'data' keyword on default top level data returned by transformers but remove 'data' keyword from all includes returned by transformers. How can I accomplish this?

**Comment by bweston92** [comment]
No but in your client that parses the data can do that.


https://github.com/legalweb/Hive/blob/master/src/base/models/model.coffee





Look at parse method.



—

**Comment by MovingGifts** [comment]
Hmm... I would think since we have control over the server output that there should be a way to do it, yeah?
