### ISSUE TITLE
Calling Transformer Subset Includes?

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#665]
Hello,

Here is a scenario I am wondering how to tackle with transformers. I have a user transformer with 10 fields. Depending on which of the other 2 transformers are default including it, I want to include only a few of those fields (so not all 10 fields should be returned from user transformer in those 2 includes). I want to default include 2 of those user transformer fields only in transformer#2, and default include 6 of those fields in transformer#3.

How would I do this? I feel it's the wrong approach to create 2 additional user transformer variations with only that data (one would return 2 fields for transformer#2, the other would return 6 fields for transformer#3). Is there a way to make a selection of the necessary subset of required data from user transformer depending on which transformer is calling the include?

**Comment by bweston92** [comment]
I don't fully understand what you want but from what I can gather, have explicit transformers for each outcome you want.

**Comment by MovingGifts** [comment]
I think that makes sense, thanks
