### ISSUE TITLE
Rate Limiting Documentation

### ISSUE THREAD

**Issue by jlien-calwater** [dingo/api#666]
##### Questions:

* Is limit and expires required?
* Does limit and expires have a default?
  * if so what are the defaults?

Suggestion for clarification: 

Current:
### Enabling Rate Limiting 

To enable rate limiting for a route or group of routes you must enable the api.throttle middleware. Once rate limiting is enabled you must have configured some throttles or configured route specific throttling.

Suggestion:
### Enabling Rate Limiting

To enable rate limiting for a route or group of routes you must add these to your middleware:

* api.throttle
* limit
* expires

```php
$api->version('v1', function ($api) {
    $api->get('users', [
        'middleware' => 'api.throttle',
        'limit' => 100,  // optional? required? default = ?
        'expires' => 5,  // optional?  required? default = ?
        function () {
            return User::all();
        }
    ]);
});
```

Current example requires horizontal scrolling.
![image](https://cloud.githubusercontent.com/assets/3473846/10143439/3bfc3ab4-65cd-11e5-96cd-0b510ac182e9.png)

Don't mind other people's opinion/enhancement.

**Comment by jasonlewis** [comment]
Feel free to make suggestions and send PRs to the documentation repo: [dingo/api-docs](https://github.com/dingo/api-docs)

**Comment by jlien-calwater** [comment]
@jasonlewis will do.

Could you help with the question?

Is limit and expires required?
Does limit and expires have a default? if so what are the defaults?

**Comment by arnabrahman** [comment]
just figured out that limit & expires parameters are required
