### ISSUE TITLE
Api on a subdomain should leave errors on main domain intact

### ISSUE THREAD

**Issue by jeroenverfallie** [dingo/api#671]
When I use a subdomain, `api.example.com` without a prefix, this works fine, and my main, non-api, routes on `example.com` behave as expected.

However, when I go to a non existing route like `example.com/jqsdfjqjsdf` it gives me the `404` response dingo would give, and not my custom 404 page.

I expect the error handling to be restful only on the subdomain? Or am I wrong?

**Comment by jeroenverfallie** [comment]
With a prefix, this behaves as I expect. Restful error responses only happen on the prefix.

**Comment by jasonlewis** [comment]
Will investigate when I can. Thanks for the report.

**Comment by frankkessler** [comment]
I was struggling with something similar.  Make sure that you are only defining a prefix or a domain, but not both.  The code was designed to only handle one or the other.  So one of them must always be null.  I was going to submit a pull request for this, but after digging into the unit tests and the docs, the code was designed this way.  It's clear in the docs, but easy to miss.

**Comment by jeroenverfallie** [comment]
Hey @frankkessler thanks for the info, but it was indeed using just the one or the other.

This is a better explanation:

**When using a subdomain: api.domain.com**
:white_check_mark: Trigger error on `api.domain.com/route` results in restful error.
:x: Trigger error on `domain.com/route` results in restful error.

**When using a prefix: domain.com/api**
:white_check_mark: Trigger error on `domain.com/api/route` results in restful error.
:white_check_mark: Trigger error on `domain.com/route` results in default laravel behaviour.

**Comment by jasonlewis** [comment]
Are you able to confirm if this issue still persists @jeroenverfallie?
