### ISSUE TITLE
response headers with content-type json?

### ISSUE THREAD

**Issue by csrui** [dingo/api#680]
Quick question...

isnt dingo supposed to return responses with content-type application/json? I'm getting text/html; charset=UTF-8 Anyone has any clues about this?

**Comment by csrui** [comment]
Just figured it out. 
The issue was not on the Dingo package.

**Comment by ernestova** [comment]
What was it ?

**Comment by csrui** [comment]
Dumb ass me somehow inserted a white space before the headers and they were getting screwed up.
