### ISSUE TITLE
Git Version Controlled Documentation

### ISSUE THREAD

**Issue by rowino** [dingo/api#682]
It would be nice to have the docs within the repo so we can always look back at how things were/are done for a specific tag. This helps a lot when one is using an older version and the wiki docs are updated to the current version. For instance those of us who started using the package in Laravel 4 and are not planning to upgrade to 5.1 any time soon suffer from little to no docs at all. Also happens with new releases when the docs are behind.

It would also help as we could make pull requests against the documentation to help with updating them.

**Comment by jasonlewis** [comment]
Docs are available as a separate repository: [dingo/api-docs](https://github.com/dingo/api-docs). You can send PRs there and I'll merge it to the Wiki as well.
