### ISSUE TITLE
Response constructor content default value

### ISSUE THREAD

**Issue by mogadget** [dingo/api#683]
```
public function __construct($content, $status = 200, $headers = [], Binding $binding = null)
    {
        parent::__construct($content, $status, $headers);
        $this->binding = $binding;
    }
```
When I inject Dingo\Api\Http\Response into my class constructor Im getting Unresolvable dependency resolving error .  This is some to do with the $content need to have value otherwize the Laravel IoC cannot type hint do its binding.

I think it's better to have this parameter with default value like $status, $headers, et.al

**Comment by jasonlewis** [comment]
I guess it can have an empty default. Feel free to PR it.
