### ISSUE TITLE
api:docs generate escaped unicode

### ISSUE THREAD

**Issue by coldmake** [dingo/api#684]
When use api:docs, if the response contains unicode characters, the output document display the escaped unicode rather than the character.

Example: 
`@Response(200, body={"message":"你好"})`
will be like this in generated document
```
Response 200 (application/json)
    + Body
        {
             "message":"u4f60u597d"
        }
```
Reason: The default behavior of json_encode that escape the unicode

Suggestion: In Dingo\Blueprint, 

Change

```
protected function prepareBody($body, $contentType)
    {
        if ($contentType == 'application/json') {
            return json_encode($body, JSON_PRETTY_PRINT);
        }

        return $body;
    }
```

to

```
protected function prepareBody($body, $contentType)
    {
        if ($contentType == 'application/json') {
            return json_encode($body, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        }

        return $body;
    }
```

Hope this helps

**Comment by jasonlewis** [comment]
Feel free to send a PR to [dingo/blueprint](https://github.com/dingo/blueprint) and I'll happily merge it in.
