### ISSUE TITLE
validate a route scopes bug

### ISSUE THREAD

**Issue by argb** [dingo/api#692]
This method "protected function validateRouteScopes(AccessTokenEntity $token, Route $route)" in about line 118 of Provider/OAuth2.php ,is wrong logic.
it should be all scopes satisfy the requirement ,not any of scope exist.
maybe the right codes are : 
$scopes = $route->scopes();

protected function validateRouteScopes(AccessTokenEntity $token, Route $route)
    {
        $scopes = $route->scopes();

        if (empty($scopes)) {
            return true;
        }

        foreach ($scopes as $scope) {
            if (!$token->hasScope($scope)) {
                throw new InvalidScopeException($scope);
            }
        }
        return true;
    }

**Comment by pulkitjalan** [comment]
Agreed, created pull request #698

**Comment by argb** [comment]
@pulkitjalan Just from this bug i can assert Dingo api should have many bugs,so obvious bug should not be occur.

**Comment by jasonlewis** [comment]
This was actually decided on a long time ago because it's very implementation specific. (See #146)

It initially required ALL scopes to be present for it to validate. I'm happy to have another discussion about it. But don't assume it's a bug just because it's not behaving how you think it should behave. Again, you might want a different implementation than someone else.

Best course of action here would be to make it configurable I suppose.

> Just via this bug i can assert Dingo api should have many bugs,so obvious bug should not occur.

If that's what you believe @argb then don't use the package. It's pretty simple.

**Comment by pulkitjalan** [comment]
Fair enough, do you think configurable via the config file or configurable per route?

**Comment by pulkitjalan** [comment]
I have made what I think should work and added tests. Can you take a look before I submit a pr. https://github.com/pulkitjalan/api/commit/481c9ad3ff3a322a0e3d8cda68257e63b85ac51c. It adds a new option to the routes `requireAll` which is used to validate if all scopes are required or defaults to false which is any scopes are required.

**Comment by jasonlewis** [comment]
I like the implementation but I think `requireAll` is a little vague.

Other possibilities:

- `scopeAll`
- `strict` (also vague, already have a `strict` config option for Accept header)
- `scopeStrict`

I hate naming things. Definitely need some input for the name.

**Comment by pulkitjalan** [comment]
How about scopeStrict to some what match the strict accept header functionality?

**Comment by jasonlewis** [comment]
Okay, submit the PR and we'll move this discussion there. :+1:

**Comment by argb** [comment]
@jasonlewis I admit that I am a bit of angry with that problem and the tone is a little strong,but just hope to this this package could be better,there is no nothing. Say sorry for my inappropriate words.
