### ISSUE TITLE
Basic Auth - where do I configure it?

### ISSUE THREAD

**Issue by sommarnatt** [dingo/api#694]
Been following the guide on setting up Dingo/api on Laravel 5.1.

I've got a default laravel users table with email and password field and am using postman to try it out.
Works without auth middleware but when adding api.auth as middleware it gives me a 401.

> HTTP Basic
> This provider uses the default basic authentication built into Laravel and Lumen. You will need to configure this provider in a service provider or bootstrap file. The second parameter is the identifier used to authenticate.

Could you give a laravel 5.1 example or point me towards docs?

**Comment by jlien-calwater** [comment]
@sommarnatt are you using JWT for authentication? 

From the error msg it looks like you are using [HTTP Basic](https://github.com/dingo/api/wiki/Authentication).

For L5.1 you'll need to add the configs in the provider.

```php
// App\Providers\AppServiceProvider.php
public function boot()
{
   app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
      return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
   });
}

```

**Comment by sommarnatt** [comment]
@jlien-calwater Thanks! Yes I'm using HTTP Basic for now.
I've added it to the configs, however it can't seem to find the class.
I've just come back to Laravel after using 4.2 like a year ago so I might not be up to speed.. :) Any pointers would be appreciated.

Here's my conf/app.php providers and I've run `php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"`
```php
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Foundation\Providers\ArtisanServiceProvider::class,
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Routing\ControllerServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

	/*
	 * Custom providers
	 */
	     Dingo\Api\Provider\LaravelServiceProvider::class,

    ],
```

**Comment by sommarnatt** [comment]
Ok I moved ´Dingo\Api\Provider\LaravelServiceProvider::class´ above the rest of the providers, seems that was in the docs ;) Still nothing.

Ok, seems it works with `return new \Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');`

**Comment by JustinLien** [comment]
@sommarnatt you want to put the code in this provider:

![image](https://cloud.githubusercontent.com/assets/688800/10706877/13aa5eec-79a0-11e5-85dd-9383277fc0df.png)

```php
// App\Providers\AppServiceProvider.php
public function boot()
{
   $this->app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
      return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
   });
}
```

Sorry, the initial code for registering is incorrect since it was a copy-paste from documentation. 
Please read up on [Laravel Providers](http://laravel.com/docs/5.1/providers).

**Comment by jasonlewis** [comment]
You can't place complex configuration (anything with a closure) in the configuration file anymore. Needs to be done in a provider like your original example (which was fine).

Let me know if you're still having issues @sommarnatt.

**Comment by discountry** [comment]
Try this:
```
'auth' => [
         'basic' => 'Dingo\Api\Auth\Provider\Basic'
    ],
```
