### ISSUE TITLE
erorr with api:docs when use json array

### ISSUE THREAD

**Issue by liyu001989** [dingo/api#696]
/**
     * @Get("/user/posts")
     * @Transaction({
     *      @Response(200, body={"data":[{"id":1},{"id":2}]})
     * })
     */
    public function index()
    {
    }

there is an error 

      [Doctrine\Common\Annotations\AnnotationException]
      [Syntax Error] Expected PlainValue, got '[' at position 224 in method App\Htt
      p\Controllers\Api\V1\UserPostController::index().

what can I do with it

**Comment by jmartigny** [comment]
Replace square brackets by curly braces....not sure if this how it should be working though but it fixes the problem for me. The generated blueprint will be outputting correct json

**Comment by liyu001989** [comment]
@jmartigny thank you, it works.
