### ISSUE TITLE
Dingo routes don't use the RouteServiceProvider $namespace

### ISSUE THREAD

**Issue by amouillard** [dingo/api#701]
When setting up a new route like $api->get('route', 'MyController@method'), the full namespace is needed for MyController instead of resolving the common namespace set in the RouteServiceProvider.

**Comment by jasonlewis** [comment]
That's correct. It utilizes a completely different router so it has nothing to do with the namespace set in your `RouteServiceProvider`.

You can configure this yourself with a group and the `namespace` option.
