### ISSUE TITLE
How to get current version in header "Accept"

### ISSUE THREAD

**Issue by refear99** [dingo/api#702]
The method 
```
\Api::getVersion()
```
get the `API_VERSION` in .env, I think it's mean "default version".

But how to get current version?
```
application/x.myapi.v1+json
application/x.myapi.v2+json
```

Thanks.

**Comment by jasonlewis** [comment]
Good point, I don't think there's a way for you to grab it right now without a few steps.

Would require grabbing an `Accept` parser instance and parsing it yourself. I'll add this information on to the router so you can grab it for the current request.

**Comment by jasonlewis** [comment]
This was added in.

With the current request instance you can grab the current version, subtype, and format.

```php
$request->version(); // v2
$request->subtype(); // myapi
$request->format(); // json
```
