### ISSUE TITLE
APP_DOMAIN not working with specific IP?

### ISSUE THREAD

**Issue by ludo237** [dingo/api#703]
Hello everyone.

I'm using Dingo API for a while but I'm struggling getting this thing done.
I have an API server, completely dedicated to serve the data to the outside world using a static IP with `8888` port, let's say `1.1.1.1:8888`

Locally I've an application that want to consume the same APIs but it can connect through the local IP, something like `192.168.1.115:8888` 

I've set up the `.env` file like so
```
API_DEBUG=false
API_STANDARDS_TREE=vnd
API_VERSION=v1
API_SUBTYPE=myapp
API_STRICT=true
API_PREFIX=null
API_DOMAIN=1.1.1.1:8888
```

The problem is that neither the external world nor the local application has access to the API with this configuration because I receive this response (i've changed the ip in the response to match the example

```
*   Trying 1.1.1.1...
* Connected to 1.1.1.1 (1.1.1.1) port 8888 (#0)
> GET / HTTP/1.1
> Host: 1.1.1.1:8888
> User-Agent: curl/7.43.0
> Accept: application/vnd.myapp.v1+json
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.8.0
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache
< Date: Tue, 27 Oct 2015 17:21:48 GMT
< Set-Cookie: laravel_session=RemovedKeyNotImportant; expires=Tue, 27-Oct-2015 19:21:48 GMT; Max-Age=7200; path=/; httponly
< 
* Connection #0 to host 1.1.1.1 left intact
{"message":"404 Not Found","status_code":404}
```

Which means that my local application doesn't have access to the APIs. But this happens even with the external test (from outside the local area). 

Does the APP_DOMAIN accept ip address ad domain?

**Comment by jasonlewis** [comment]
Is this API a stand alone application?

**Comment by ludo237** [comment]
Yes

**Comment by jasonlewis** [comment]
I'd just go ahead and set the `API_PREFIX` to `/` then and not worry about `API_DOMAIN` at all.

**Comment by alexw23** [comment]
Just to confirm is API_DOMAIN essential?

**Comment by jasonlewis** [comment]
`API_DOMAIN` shouldn't include ports AFAIK. It's main use is when you want to run your API/app from the same Laravel install but want to run the API from a subdomain.

**Comment by Maykonn** [comment]
For me 127.0.0.1 not works for API_DOMAIN, just the public IP of my AWS EC2 instance.
