### ISSUE TITLE
Success response

### ISSUE THREAD

**Issue by marijang** [dingo/api#704]
Is there method for success response?

for example
I update or create some record (POST,PATCH or whatever)
and i want to call
```
$this->response->success($message)
```
to get
```
{
  "data": [],
  "message": "Succesfuly unfollowing user",
  "meta": {
    "code": 200
  }
}
```
Maybe like this
```
$this->response->success('Items was added.',$data,$location);
```
and in config api to add
```
    'successFormat' => [
        'message' => ':message',
        'success' => ':success',
        'code' => ':code',
        'status_code' => ':status_code',
        'debug' => ':debug',
    ],
```

What do you think?
I can create my own in BaseController but it is not nice:D
i cant then use $this->response->success i need to use something like this $this->respondWithsuccess ....

**Comment by jasonlewis** [comment]
There's a number of helper methods, including a `created` helper that accepts a `location`.

```php
return $this->response->created();
```

These responses are fairly generic. If you'd like custom messages and what not along with the response then you'll need to just implement this yourself.
