### ISSUE TITLE
getPrefix() or getLastGroupPrefix()

### ISSUE THREAD

**Issue by bh-rat** [dingo/api#705]
I cannot get getLastGroupPrefix to work in my project. It returns null.

So this is my BaseController

    public function isAdminRequest()
    {
        return Route::getLastGroupPrefix();
    }

and in my routes, I have

    $api->group(array('prefix' => 'admin'), function($api)
    {
        $api->resource('users', "App\Http\Controllers\UsersController");
    });

But this the isAdminRequest just returns null.
when using Laravel Router (or Illuminate Router) like 

    Route::group(array('prefix' => 'admin'), function($api)
    {
        Route::resource('events', "Events\EventsController");
    });

and 

    $request->route()->getPrefix()

this returns "/admin" like it should have.

**Comment by jasonlewis** [comment]
Is the `Route` facade the Laravel or Dingo API one? Because this method is shared across both.

**Comment by bh-rat** [comment]
Route facade is the Dingo API one. If I do this 

    public function getLastGroupPrefix()
    {
        if (empty($this->groupStack)) {
            return '';
        }

        $group = end($this->groupStack);
        dd($group['prefix']);
        return $group['prefix'];
    }

it returns 'api/admin'. But returns null on return.

**Comment by jasonlewis** [comment]
For what you were trying to do you'd be better off using `Request::is`.

```php
Request::is('*admin*');
```
