### ISSUE TITLE
Can I encrypt the call

### ISSUE THREAD

**Issue by snky1987** [dingo/api#706]
For additional security I would like to encrypt the call to receive the token using PasswordGrant.

I managed to do that but completeFlow() functionality takes "client_id" and "client_secret" directly from Request and try to receive the Client based on that data.

If I encrypted client_id and client_secret I received "InvalidClientException" response.

Is there a way to override this functionality and Decrypt the response credentials first (and then try to get the client) without messing with Vendor ?

**Comment by bh-rat** [comment]
I guess you could write a middleware which decrypts the response and add it to your $middleware array.

**Comment by jasonlewis** [comment]
Send it over a secure connection if you're concerned.
