### ISSUE TITLE
Custom Exception on internal request

### ISSUE THREAD

**Issue by m33ch** [dingo/api#708]
Hi all,

first of all i want to say thank you for this awesome package! 
It's very very usefull!

Well, on my <code>routes.php</code> i add this for custom exception when i use <code>findOrFail()</code> method :
```
app('Dingo\Api\Exception\Handler')->register(function (Illuminate\Database\Eloquent\ModelNotFoundException $exception) {
    return Response::make(['error' => 'Not Found'], 401);
});
```
In 'Sample' controller i have this code on index method :
```
$todo = $this->api->get('todos/'.$todoId);
```
In 'Todo' controller i have this on show method
```
$todo = $repository->findOrFail$id);

return $this->response->item($todo, new TodoTransformer);
```

Is there a system to override previous custom "not found" message?

I tried to add <code>try ... catch</code> on 'Sample' controller like this but not work.
```
try {
    $todo = $this->api->get('todos/'.$todoId);
} catch(Exception $e) {
    return Response::make(['error' => 'Custom message']);
}
```

Thank you for your support!

Ps Sorry for my bad english

**Comment by ionut-tanasa** [comment]
Caro Alessandro,

You are catching the wrong exception. Not **Exception**, but  **ModelNotFoundException**

**Comment by m33ch** [comment]
Hi,

thank you for your reply!
I tried to use ModelNotFoundException but not work!
