### ISSUE TITLE
Route parameter constraints

### ISSUE THREAD

**Issue by pengyuanzhao** [dingo/api#713]
In Laravel, we can set the route parameter using where method:

    Route::get('user/{name}', 'UserController@show')->where('name', '[A-Za-z]+');

How to do this in Dingo API? 

Thanks!

**Comment by joaorobertopb** [comment]
How to do this in Dingo API?

**Comment by jasonlewis** [comment]
If you're using Laravel then it's exactly the same as what you've just demonstrated. Lumen has it's own format for setting these as well.

```php
$api->version('v1', function ($api) {
    $api->get('user/{name}', 'UserController@show')->where('name', '[A-Z]+');
});
```
