### ISSUE TITLE
api.auth middleware calling all constructor twice

### ISSUE THREAD

**Issue by Luddinus** [dingo/api#714]
Hi.

I'm using JWT provider to protect the routes.

My routes are defined like this:

```
// $api->version()...
$api->group(['middleware' => 'api.auth'], function($api) {
   $api->get('users', 'UserController@index');
});
```

Controller
```
class UserController extends Controller {
   public function __construct()
   {
      var_dump('contruct called');
   }

   public function index()
   {
      return User::all();
   }
}
```

The controller construct is calling TWICE, but if I use middleware "jwt.auth", it works at expected.

Which are the advantages of using "api.auth" instead of "jwt.auth"? Why is this happening?

Thx.

**Comment by Luddinus** [comment]
up

**Comment by hthabet** [comment]
:+1:

**Comment by jasonlewis** [comment]
Two instances were being created. I've gone ahead and patched this so that the initial instance is bound to the container so it'll only be instantiated once.
