### ISSUE TITLE
Routes resource not working

### ISSUE THREAD

**Issue by rdehnhardt** [dingo/api#716]
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', ['middleware' => 'api.auth'], function ($api) {
    $api->group(['prefix' => 'band', 'namespace' => 'App\Band\Http\Controllers'], function ($api) {
        $api->resource('discs', 'DiscController', ['except' => ['create', 'edit']]);
    });
});

When perform a GET on /discs everything works normally, but when I run a POST /discs get this message:

[2015-11-07 21:09:10] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/vagrant/Code/webstage/wbs/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:161

**Comment by jlien-calwater** [comment]
Try running php artisan api:routes and see your routes.

I just tested this and the route resource loads fine.

![image](https://cloud.githubusercontent.com/assets/3473846/11313466/e499fc90-8f91-11e5-8fc3-6b4b1606257e.png)

![image](https://cloud.githubusercontent.com/assets/3473846/11313477/ef9e4646-8f91-11e5-858e-298b5314e1bd.png)

**Comment by jasonlewis** [comment]
You said **except** **create** and **edit**, which means the `POST /discs` route would not have been configured.

**Comment by jasonlewis** [comment]
Ignore previous message, I read that wrong. Hold tight.

**Comment by jasonlewis** [comment]
Unsure what your issue is but it's working fine on my testing. Will need any more information you can provide.
