### ISSUE TITLE
Class 'Illuminate\\Foundation\\Http\\FormRequest' not found"

### ISSUE THREAD

**Issue by Amrit01** [dingo/api#717]
while tyring to extend Dingo\Api\Http\FormRequest class in lumen i am getting this error

**Comment by hthabet** [comment]
I believe <code>Illuminate\\Foundation\\Http\\FormRequest</code> is only available with Laravel and not Lumen.

**Comment by jasonlewis** [comment]
That's correct, only available in Laravel.
