### ISSUE TITLE
Eloquent::findOrFail() returning 500 error? is this right?

### ISSUE THREAD

**Issue by leemason** [dingo/api#718]
Im working on the begginings of an api, and its going well, this package is great!

However something ive noticed is using ::findOrFail() on an eloquent model results in the following error:

```
{
    "message": "No query results for model [......\\Model].",
    "status_code": 500
}
```

shouldnt this return a not found exception/error? and not an internal server error?

if this is expected, what would you suggest i do to change it?

**Comment by leemason** [comment]
Is there a way within the package to convert:

```Illuminate\Database\Eloquent\ModelNotFoundException``` into a ```Symfony\Component\HttpKernel\Exception\NotFoundHttpException``` ?

**Comment by leemason** [comment]
ok, after a bit of digging ive found out how to convert the ModelNotFound exception into a response the api will understand.

in the boot method of a service provider i have this:

```php
public function boot(ExceptionHandler $handler)
{

        $handler->register(function(ModelNotFoundException $e){
            throw new ResourceException($e->getMessage(), null, $e);
        });
}
```

This does infact reformat the response into something the api handles better, however this returns a 422 status code (better than the 500 i was getting, but still not right).

would you consider a pull request to:

1. add a new exception ```ResourceNotFoundException``` which is the same as standard resource exception, but sets the code to 404.

2. optionally via config option (if needs be) auto catch ModelNotFoundExceptions and rethrow them as ResourceNotFound.

As you can see im doing this anyway, but i think it would be a good addition to the package.

**Comment by igustafson** [comment]
+1. ModelNotFoundException is converted to a NotFoundHttpException in the Laravel 5.1 default handler; anyone who uses exceptions this way int he controller would expect dingo's handler to conform to that.

**Comment by jasonlewis** [comment]
You don't need to throw a resource exception there. Just throw a not found exception like you're expecting. A resource exception is for things like creating, updating, and deleting resources, hence the 422.

I'd be open to a default handler that catches a `ModelNotFoundException` and throws a `NotFoundHttpException`.

**Comment by pierrocknroll** [comment]
I don't understand why dingo returns a 500 instead of a 404 when not found, it's not standard. I don't want to throw a custom Exception in all my models ! Laravel without dingo returns correctly a 404.

**Comment by codetrash** [comment]
I use this in Handler.php

```
 /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        // return parent::render($request, $e);

        // return as JSON instead
        $statusCode = method_exists($e, 'getStatusCode') 
                      ? $e->getStatusCode() : 500;
        $statustext = Lang::get('messages.error._' . $statusCode);

        //check for Eloquent model execption
        if(get_class($e) == 'Illuminate\Database\Eloquent\ModelNotFoundException') {
            $statustext = Lang::get('messages.error._404');
            $statusCode = 404;
        }

        $response = [
            'status_text' => $statustext,
            'status_code' => $statusCode,
            'message' => $e->getMessage()
        ];
       
        return response()->json($response, $statusCode);
    }
```

**Comment by paishin** [comment]
why was this issue closed? It is still not in line with how Laravel handles this and I think it should get resolved.

**Comment by specialtactics** [comment]
It is possible to fix it in Dingo by putting this on top of the exception handler:

```php
        if ($exception instanceof \Illuminate\Database\Eloquent\ModelNotFoundException) {
            $trace = $exception->getTrace();
            $exception = new NotFoundHttpException($exception->getMessage(), $exception);
        }
```

However the problem there is that you will actually lose the proper stack trace that led to the problem, and only see vendor functions in the new stack trace.

A better solution is to override Laravel's findOrFail() function, however this is probably outside of the scope of dingo because you need to have your own class extending laravel's model class.

This is an example of how I'm doing it in my API boilerplate - 
https://github.com/specialtactics/l5-api/blob/master/src/Models/Builder.php

This method preserves the original track trace leading to the findOrFail()

**Comment by specialtactics** [comment]
Actually, I figured out one way to address it in this package by changing only the exception handler, PR here - https://github.com/dingo/api/pull/1597

**Comment by specialtactics** [comment]
Hey guys, good news - the PR for this has been merged !

**Comment by jourdon** [comment]
```
"message": "No query results for model [.....\\Model] 44",
"status_code": 404,
```
the code is 404,
Why should I care about what the message is?  "not found " is enough

**Comment by specialtactics** [comment]
> ```
> "message": "No query results for model [.....\\Model] 44",
> "status_code": 404,
> ```
> the code is 404,
> Why should I care about what the message is? "not found " is enough

It's just there for the sake of being helpful (especially when debugging). If it only threw a 404 it wouldn't be clear for example why (it could be that the route itself couldn't be found for instance).

You don't have to worry about it at all.
