### ISSUE TITLE
Multi Auth Providers Problem 

### ISSUE THREAD

**Issue by chekun** [dingo/api#719]
Say we need to auth with ['oauth', 'custom']

If oauth passes, custom will never be used even if the class itself has been instanced.

Looking into the code ,the line 86  on Dingo\Api\Auth\Auth ```return``` causes this.

```
public function authenticate(array $providers = [])
    {
        $exceptionStack = [];

        // Spin through each of the registered authentication providers and attempt to
        // authenticate through one of them. This allows a developer to implement
        // and allow a number of different authentication mechanisms.
        foreach ($this->filterProviders($providers) as $provider) {
            try {
                $user = $provider->authenticate($this->router->getCurrentRequest(), $this->router->getCurrentRoute());

                $this->providerUsed = $provider;

                return  $this->user = $user;
            } catch (UnauthorizedHttpException $exception) {
                $exceptionStack[] = $exception;
            } catch (BadRequestHttpException $exception) {
                // We won't add this exception to the stack as it's thrown when the provider
                // is unable to authenticate due to the correct authorization header not
                // being set. We will throw an exception for this below.
            }
        }

        $this->throwUnauthorizedException($exceptionStack);
    }
```

Is this intended to behave like this or  something else ??

**Comment by jasonlewis** [comment]
Yeah that's intended. It's to allow multiple avenues of authentication, but you only need to be authenticated by a single provider. I mean, I could run it through the remaining providers, but is there a need if you're already authenticated through the first provider?

**Comment by chekun** [comment]
@jasonlewis 

Yes, due to our platform reasons, i need to use oauth2 client-credentials to auth for the client, and use an custom auth provider to check the user login status.

But, i've created a patch, use both providers, and both getUser and getClient available to use later on. 

Thanks.
