### ISSUE TITLE
Middleware terminate() not being called

### ISSUE THREAD

**Issue by aleemb** [dingo/api#721]
This might be related to https://github.com/laravel/framework/issues/9357

With Dingo, the `terminate()` method on middleware is not called. This breaks all sorts of core app functionality, a basic example of which is  Sessions which rely on `SessionStart` whose `terminate()` method does the work of persisting sessions.

**Comment by aleemb** [comment]
Forgot to mention but I have noticed this on Lumen.

**Comment by hthabet** [comment]
:+1: :+1: @aleemb
I'm using Lumen too and I have been all day long trying to debug my problem with session data not being persisted using a custom authentication provider. I end up to the same conclusion.

**Comment by hthabet** [comment]
I made a little workaround in <code>src/Routing/Adapter/Lumen.php:229</code> to make it work
replacing:
<code>$property->setValue($this->app, []);</code>
by:
<code>$property->setValue($this->app, ["Illuminate\Session\Middleware\StartSession", "Illuminate\View\Middleware\ShareErrorsFromSession"]);</code>
But by doing this, these middlewares are executed twice as it is initially said in the method description. 
The problem of having code executed twice when using middleware is also happening with controllers in #714

**Comment by jasonlewis** [comment]
I'll investigate this. From a quick look it seems as though it'll need to be implemented by me since it's not handled automatically (it is if the middlewares are registered with Laravel/Lumen).

What happens though is that middlewares are stripped from Laravel/Lumen and run independently of either framework because of some inconsistencies between the two (hence you're seeing them being run twice @hthabet).

**Comment by jasonlewis** [comment]
There were some issues with route-based middleware not terminating on Laravel as well. Have gone ahead and made several changes.

Patch should now terminate application middleware on Lumen and route middleware on Laravel.

**Comment by bryannielsen** [comment]
I'm hitting this issue again with Lumen 5.1.6 and the latest Dingo commit (8cd1a6).

I just have a simple terminable middleware that writes to the log.  It is not being run on Lumen routes or Dingo routes but when I pull the dingo router and api routes out and just run a standard lumen route the middleware is executed properly.

Should I open a new issue or can this one be re-opened?

**Comment by christaggart** [comment]
@bryannielsen I too am seeing this as well w/Lumen 5.2.6 and Dingo. Did you find a solution? I'm running dev/master.

**Comment by Maxeee09** [comment]
I noticed the same issue using Laravel 5.3 and route middleware. Terminate method is never called

**Comment by diegofalciola** [comment]
Same thing here, termine method is not being called. Lumen 5.3

**Comment by wayanjimmy** [comment]
Same here, I need terminate method for logging all response

**Comment by diegofalciola** [comment]
Since I cannot reopen issues, I will create a new one associated to this ticket.
