### ISSUE TITLE
Is it possible to define route patterns just line in the default router?

### ISSUE THREAD

**Issue by jadjoubran** [dingo/api#724]
I understand that dingo/api is completely different than the original Laravel router.

However I want to ask if specifying a route pattern is possible:

`$api->pattern('id', '[0-9]+');` [Laravel docs](http://laravel.com/docs/5.1/routing#required-parameters)

instead of having to define it on every single route:

`$api->get('users/{id}', 'UsersController@get')->where('id', '[0-9]+');`

Thanks

**Comment by joaorobertopb** [comment]
I'm also this doubt. This package of support routes patterns?

**Comment by jasonlewis** [comment]
Not integrated currently. Going to move discussion to #741 (even though this one is older, I just read newest first though).

**Comment by phoenixg** [comment]
I want this feature!
