### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $standardsTree ]] in class Dingo\Api\Http\Parser\Accept

### ISSUE THREAD

**Issue by canfiax** [dingo/api#725]
I am getting the following error:

    Unresolvable dependency resolving [Parameter #0 [ <required> $standardsTree ]] in class Dingo\Api\Http\Parser\Accept

This is how I call:

		$api = app('\Dingo\Api\Routing\Router');

		$api->version('v1', function(){
				$api->get(''); // etc

Whats up?

Using

    "dingo/api": "1.0.*@dev",

**Comment by canfiax** [comment]
Anyone know what causes this?

I have also tried with:

    "dingo/api": "1.0.0-beta2",

Same issue.

My standardsTree is set to `vnd` and subtype `myproject`

**Comment by jlien-calwater** [comment]
@canfiax make sure you have vendor configuration published.

https://github.com/dingo/api/wiki/Installation#laravel

**Comment by arthurkirkosa** [comment]
@jlien-calwater I see you have quite some knowledge about dingo api; can you take a look @ https://github.com/dingo/api/issues/733 and tell me what you think? Have you tested the api with PHPUnit before?

**Comment by canfiax** [comment]
@jlien-calwater I do. Since I have set standardsTree amongst others. It is called "api.php"

**Comment by jlien-calwater** [comment]
@arthurkirkosa I'm just a normal like you. I haven't dug deep into the API so I wouldn't consider myself knowledge at all. I'll take a look at it, but can't promise anything. It is just close to the holidays in the US.

@canfiax minimally you need to set at least set the API_PREFIX in the .env file. I have at least 4 of them configured.

It is null by default which will throw an error:

![image](https://cloud.githubusercontent.com/assets/3473846/11374429/e2f580c0-928a-11e5-8c51-94ff74146fe1.png)

```php
#dingo
API_SUBTYPE=MyAwesomeAPI
API_NAME=My Awesome API
API_PREFIX=api //required
API_VERSION=v1
```

It might be faster if you post your api.php and your config.php. I can tell you the API is working for me.

**Comment by canfiax** [comment]
This is my config:

    <?php

    return [

        /*
        |--------------------------------------------------------------------------
        | Standards Tree
        |--------------------------------------------------------------------------
        |
        | Versioning an API with Dingo revolves around content negotiation and
        | custom MIME types. A custom type will belong to one of three
        | standards trees, the Vendor tree (vnd), the Personal tree
        | (prs), and the Unregistered tree (x).
        |
        | By default the Unregistered tree (x) is used, however, should you wish
        | to you can regsiter your type with the IANA. For more details:
        | https://tools.ietf.org/html/rfc6838
        |
        */

        'standardsTree' => env('API_STANDARDS_TREE', 'vnd'),

        /*
        |--------------------------------------------------------------------------
        | API Subtype
        |--------------------------------------------------------------------------
        |
        | Your subtype will follow the standards tree you use when used in the
        | "Accept" header to negotiate the content type and version.
        |
        | For example: Accept: application/x.SUBTYPE.v1+json
        |
        */

        'subtype' => env('API_SUBTYPE', 'myapp'),

        /*
        |--------------------------------------------------------------------------
        | Default API Version
        |--------------------------------------------------------------------------
        |
        | This is the default version when strict mode is disabled and your API
        | is accessed via a web browser. It's also used as the default version
        | when generating your APIs documentation.
        |
        */

        'version' => env('API_VERSION', 'v1'),

        /*
        |--------------------------------------------------------------------------
        | Default API Prefix
        |--------------------------------------------------------------------------
        |
        | A default prefix to use for your API routes so you don't have to
        | specify it for each group.
        |
        */

        'prefix' => env('API_PREFIX', 'api-dingo'),

        /*
        |--------------------------------------------------------------------------
        | Default API Domain
        |--------------------------------------------------------------------------
        |
        | A default domain to use for your API routes so you don't have to
        | specify it for each group.
        |
        */

        'domain' => env('API_DOMAIN', null),

        /*
        |--------------------------------------------------------------------------
        | Name
        |--------------------------------------------------------------------------
        |
        | When documenting your API using the API Blueprint syntax you can
        | configure a default name to avoid having to manually specify
        | one when using the command.
        |
        */

        'name' => env('API_NAME', 'myapp'),

        /*
        |--------------------------------------------------------------------------
        | Conditional Requests
        |--------------------------------------------------------------------------
        |
        | Globally enable conditional requests so that an ETag header is added to
        | any successful response. Subsequent requests will perform a check and
        | will return a 304 Not Modified. This can also be enabled or disabled
        | on certain groups or routes.
        |
        */

        'conditionalRequest' => env('API_CONDITIONAL_REQUEST', true),

        /*
        |--------------------------------------------------------------------------
        | Strict Mode
        |--------------------------------------------------------------------------
        |
        | Enabling strict mode will require clients to send a valid Accept header
        | with every request. This also voids the default API version, meaning
        | your API will not be browsable via a web browser.
        |
        */

        'strict' => env('API_STRICT', false),

        /*
        |--------------------------------------------------------------------------
        | Debug Mode
        |--------------------------------------------------------------------------
        |
        | Enabling debug mode will result in error responses caused by thrown
        | exceptions to have a "debug" key that will be populated with
        | more detailed information on the exception.
        |
        */

        'debug' => env('API_DEBUG', false),

        /*
        |--------------------------------------------------------------------------
        | Generic Error Format
        |--------------------------------------------------------------------------
        |
        | When some HTTP exceptions are not caught and dealt with the API will
        | generate a generic error response in the format provided. Any
        | keys that aren't replaced with corresponding values will be
        | removed from the final response.
        |
        */

        'errorFormat' => [
            'message' => ':message',
            'errors' => ':errors',
            'code' => ':code',
            'status_code' => ':status_code',
            'debug' => ':debug',
        ],

        /*
        |--------------------------------------------------------------------------
        | Authentication Providers
        |--------------------------------------------------------------------------
        |
        | The authentication providers that should be used when attempting to
        | authenticate an incoming API request.
        |
        */

        'auth' => [
            'custom' => function ($app) {
                return new \myapp\Providers\Auth\AuthTokenAuthenticationProvider($app['auth']);
            },
        ],

        /*
        |--------------------------------------------------------------------------
        | Throttling / Rate Limiting
        |--------------------------------------------------------------------------
        |
        | Consumers of your API can be limited to the amount of requests they can
        | make. You can create your own throttles or simply change the default
        | throttles.
        |
        */

        'throttling' => [

        ],

        /*
        |--------------------------------------------------------------------------
        | Response Transformer
        |--------------------------------------------------------------------------
        |
        | Responses can be transformed so that they are easier to format. By
        | default a Fractal transformer will be used to transform any
        | responses prior to formatting. You can easily replace
        | this with your own transformer.
        |
        */

        'transformer' => env('API_TRANSFORMER', 'Dingo\Api\Transformer\Adapter\Fractal'),

        // 'transformer' => function ($app) {
        //     $fractal = new League\Fractal\Manager;

        //     return new Dingo\Api\Transformer\FractalTransformer($fractal);
        // },

        /*
        |--------------------------------------------------------------------------
        | Response Formats
        |--------------------------------------------------------------------------
        |
        | Responses can be returned in multiple formats by registering different
        | response formatters. You can also customize an existing response
        | formatter.
        |
        */

        'defaultFormat' => env('API_DEFAULT_FORMAT', 'json'),

        'formats' => [

            'json' => 'Dingo\Api\Http\Response\Format\Json',

        ],

    ];

**Comment by jlien-calwater** [comment]
Try removing the dash:

```php
'prefix' => env('API_PREFIX', 'apidingo'),
```

**Comment by canfiax** [comment]
Same

**Comment by jasonlewis** [comment]
Provider being configured correctly in `config/app.php`?

**Comment by zjien** [comment]
hey,hello,I have a question
what is standards tree?
