### ISSUE TITLE
Lumen only returning API Default Format

### ISSUE THREAD

**Issue by kubacode** [dingo/api#727]
I've created a custom XML formatter, however when using with Lumen, it seems that only the default format is returned even if the requested format is specified in the header.

I've included the below line in bootstrap\app.php after the API provider has been registered:
```php
Dingo\Api\Http\Response::addFormatter('xml', new App\SMS\xml);
```
If I add an accept header specifying an XML response (Accept: x.smsservice.v1+xml), I'm still receiving a JSON response. If I set the API_DEFAULT_FORMAT=xml in my .env file, I then ONLY get an XML response, even if JSON is specified in the header.

Is this a bug or am I setting something incorrectly?

**Comment by kubacode** [comment]
I think I've figured it out and this issue is not specific to Lumen.

In order to specify the response format, the accept header must match the strict mode format (even if strict mode is not enforced). In addition, an API_VENDOR must be specified in the config and the API_STANDARDS_TREE must be set to vnd.

**Comment by jasonlewis** [comment]
That's correct, although the standards tree does not need to be set to `vnd`, either of the accepted standards trees can be used. Just make sure you set the standards tree and subtype in your header to match those in your configuration.
