### ISSUE TITLE
Fractal update to 0.13.* to aviod conflicts with other libraries

### ISSUE THREAD

**Issue by thomasthep** [dingo/api#728]

**Comment by jasonlewis** [comment]
You can depend on Fractal `0.13.*` yourself as this package should work with `0.12` and `0.13`. Just add it to your `composer.json`.

**Comment by lightvision** [comment]
@jasonlewis Actually it doesn't. I've already tried out myself and it's a strict dependency for fractal 0.12.*

**Comment by pelletiermaxime** [comment]
Dev version doesn't have the strict dependency. I used a workaround when using the stable version:

"league/fractal": "0.13.0 as 0.12.0"
