### ISSUE TITLE
Why Response Builder must require transformer?

### ISSUE THREAD

**Issue by ethaizone** [dingo/api#730]
I like transformer. It's better that we have layer for have time to modify best output for it but sometimes I think we don't want to have transformer. Just cast array and let it out. User should use Response Builer without depend on transformer.

```php
class UserController extends BaseController
{
    public function index()
    {
        $users = User::paginate(25);

        return $this->response->paginator($users);
    }
}
```

For second situation. I want to enable or disable transformer as global.

Currently we have transformer and can register it to factory.
```php
app('Dingo\Api\Transformer\Factory')->register('User', 'UserTransformer');
```

This will work if we return model from controller or route but it's useless when use with Response builder. I think when user add transformer at controller. It's mean user want force to use in this call only.

```php
// I can comment this line and disable all transformer usage.
app('Dingo\Api\Transformer\Factory')->register('User', 'UserTransformer');

class UserController extends BaseController
{
    public function index()
    {
        $users = User::paginate(25);
        // this one will use UserTransformer as default
        // and not use when UserTransformer is not register.
        return $this->response->paginator($users);
    }

    public function index2()
    {
        $users = User::paginate(25);

        // I force to use UserAlternativeTransformer.
        return $this->response->paginator($users, new UserAlternativeTransformer);
    }
}
```

I hope Response Builder can use as standalone without depend on Transformer. Please don't set API and Fractal as package together.

PS. My english is not good. Sorry.

**Comment by JoeDawson** [comment]
You can simply return the `$users`.

```php
public function index2()
{
	$users = User::paginate(25);

	return $users;
}
```

**Comment by jasonlewis** [comment]
What Joe said. It'll look for a registered transformer for the `User` model, if none found, then it'll treat it as a regular type casted array.

**Comment by ethaizone** [comment]
Thanks. I will try it.
