### ISSUE TITLE
allow non-numeric versions or throw an error

### ISSUE THREAD

**Issue by ceejayoz** [dingo/api#731]
When attempting to use an API version `internal`, we received an odd `array_combine` error in `Http/Parser/Accept.php`. Upon further examination, the pattern for the version string is `v?[\d\.]+`.

I'd love to be able to have `api/internal/<verb>` for our SPA's internal API, but barring that, a user-friendly error should be thrown when a version string that's invalid is attempted in the route configuration.

**Comment by jasonlewis** [comment]
Yeah, most definitely, I thought I'd actually added this in. Feel free to send a PR, I'll try to get some of the new requested stuff in when I can.
