### ISSUE TITLE
Internal API call paginator base url not currect, getting as localhost

### ISSUE THREAD

**Issue by saqueib** [dingo/api#732]
I am getting this issue where I have used internal call to another endpoint in my api which is on my virtualbox domain `http://mycoolproject.app/api`

If I directly hit the url I get the proper `next_page_url` which is `http://mycoolproject.app/api/posts/?page=2`

but when I used same in internal call like this.

    ...
    use Helpers;
    ...
    'posts' => $this->api->get('posts')

and this is giving me `http://localhost/api/posts/?page=2`

***What I have tried***

So I opened the config `app.php` and replaced url from `localhost` to `http://mycoolproject.app` but problem is still there.

I also tried changing the `API_DOMAIN=http://mycoolproject.app` and `http://mycoolproject.app/api` in config `api.php` its giving me 404

Here is my config of `api.php`

     API_NAME=My Cool Project API
     API_STANDARDS_TREE=vnd
     API_DOMAIN=http://mycoolproject.app
     API_PREFIX=api
     API_VERSION=v1

I am on L5.1 homestead

**Comment by saqueib** [comment]
@jasonlewis no one has any answer for that guys :disappointed: please help.

**Comment by jasonlewis** [comment]
Sorry @saqueib, lots of things going on! I've patched the dispatcher which should hopefully have fixed this issue. Can you update and see if you're still seeing this?

**Comment by saqueib** [comment]
@jasonlewis Thanks for reply, its now working but a little issue, the url has a extra trailing `/` after domain name.

      "http://mycoolproject.app//api/questions?page=2"

**Comment by jasonlewis** [comment]
Thought I trimmed it all, must've missed one. Give me a sec!

**Comment by jasonlewis** [comment]
Update now and see how you go.

**Comment by saqueib** [comment]
updated but getting same issue. here is the change I made to make it work in Dispatcher.

     $uri = rtrim($this->getRootRequest()->root(), '/').ltrim($uri);

**Comment by a-komarev** [comment]
@saqueib How did you solved replacing localhost with your domain name?

**Comment by a-komarev** [comment]
Ah... I found a feature in Dispatcher that haven't seen in documentation about internal requests:
```php
$dispatcher = app('Dingo\Api\Dispatcher');
$dispatcher->setDefaultDomain('my.domain.int');
```
Will replace all `http://localhost` to `http://my.domain.int` in all of the links returned from internal requests! I haven't tried such a trick with https...
