### ISSUE TITLE
Ignore strict mode

### ISSUE THREAD

**Issue by clarkeash** [dingo/api#734]
Hi Jason, great work on dingo mate :smile: 

I have strict mode enabled for my API, however I'd like to have a single route (the root uri) that just returns a message telling the users to go visit the docs. Would it be possible to have this without specifiying a version and without disabling strict mode?

Thanks

**Comment by jasonlewis** [comment]
Just wire up a regular Laravel/Lumen route.

**Comment by clarkeash** [comment]
I get "undefined index: version" on regular routes, but its not that important so dont worry

**Comment by guido-manta** [comment]
Just as @clarkeash said, I'd like to have a single route without strict mode. I tried to set up a regular Laravel route, but it's not working. It seems like Dingo Router is getting in the middle and is being called right after the Illuminate Router. Any advise on this matter? Thanks a lot

**Comment by jucau** [comment]
Hello, I have the same problem than @guido-manta  and @clarkeash  said. Any help ? 

`$app->get('google-oauth-callback', 'GoogleCallbackController@getAuthCode');

$api = app('Dingo\Api\Routing\Router'); 

...`

My route isn't in the $api instance, normally it should work but it doesn't.

**Comment by guido-manta** [comment]
@jucau I solved manipulating my single route request header, setting the Accept header manually. 
It seems weird though, 'cause wiring up a regular Laravel route doesn't seem to work at all.

**Comment by jucau** [comment]
@guido-manta  unfortunatly I can't use the same solution : the route has to handle Google authentication callback. It's not possible to set custom headers in request.

Or maybe I didn't undertand what you explain ?

**Comment by guido-manta** [comment]
@jucau I understand what you mean. Even my route has to handle with an external callback.
What I mean is to handle the request inside my project and "attach" the Accept header manually, in order to avoid "Accept header could not be properly parsed because of a strict matching process." error
