### ISSUE TITLE
Laravel Cors Issue

### ISSUE THREAD

**Issue by clarkeash** [dingo/api#736]
Hi, I am using the popular [laravel cors package](https://github.com/barryvdh/laravel-cors) and it seems to be conflicting with dingo/api as I get a cross origin error, and when disabling dingo I everything works fine.

Happy to provide any additional info but as I dont get any actual PHP errors I am not sure what else would be useful to you.

Thanks

**Comment by jasonlewis** [comment]
Going to need a bit more information. How have you configured both packages? Order of the service providers? What errors? Anything in your log file?
