### ISSUE TITLE
Redirecting to newly created resource using internal API

### ISSUE THREAD

**Issue by michaelstivala** [dingo/api#737]
I've got a resource handled by the API, and a separate controller using the internal API:

```
public function store(Request $request)
    {
        $this->getAuthenticatedApi()->post('/tags', $request->all());  
    }
```

This works fine, my problem is redirecting to the newly created resource - I'm wondering if anyone has dealt with this issue and has a neat solution to it.

My API's store method returns a 201 response, with the location header set - I can access this location header if I were to access the "raw" response from the api (using the `->raw()` notation). I thought about using the location to access the newly created resource via the internal API, and then use it to redirect as I see fit. The problem here is that the location header links to 'localhost', not my app's URL (separate bug?)

Does anyone have any guidance?

**Comment by jasonlewis** [comment]
The `created` method accepts a location which is returned as it as given. Nothing special happens to it, so how are you generating the URI that you're giving to the created method?

Using `raw` would be the way to go to fetch the location. You can then use that location to make the next request.

**Comment by michaelstivala** [comment]
Thanks for the reply Jason.

Great - I'll stick to the `raw` method. In that case, it seems that the wrong URL is being generated for me, this is the line:

```return $this->response->created(app('Dingo\Api\Routing\UrlGenerator')->version('v1')->route('api.tags.show', $tag->name));```

Regardless of the URL of the app, it always returns `localhost`. Am I missing something?

**Comment by jasonlewis** [comment]
This is definitely an issue with the internal dispatcher. Will work on a fix.

**Comment by jasonlewis** [comment]
Let me know how it's going now once you pull down the changes.
