### ISSUE TITLE
Add patterns and pattern methods as in Illuminate Router to Dingo Router.

### ISSUE THREAD

**Issue by roquie** [dingo/api#741]
Look at boot method.

```php
<?php

namespace App\Providers;

use Dingo\Api\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to the controller routes in your routes file.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @param \Illuminate\Routing\Router $router
     */
    public function boot(\Illuminate\Routing\Router $router)
    {
         //of course, will be not work
        $router->patterns([
            'id'       => '[0-9]+', 
            'test'     => '[0-9]', 
        ]);

        //maybe create methods? 
        //app('api.router')->patterns([ ... ]);

        parent::boot($router);
    }
//...
```

routes.php
```php
get('v1/{test}/{id}', function() { dd(1); })

// http://api.example.com/v1/non_digit_input123/string_as_is - work. It's bad, if patterns array has been added.
```

**Comment by jasonlewis** [comment]
I'll think about it and see how an implementation looks.

**Comment by jadjoubran** [comment]
Is this still planned? 😄

**Comment by hskrasek** [comment]
@roquie Based on how the routing is handled, if you setup a pattern on the laravel router, it should correctly handle the pattern matching. I tested this in a personal project, and it worked as expected. Trying to add a unit test to confirm this is the case, but well, if testing was easy everyone would be doing 😛.

Will update this if I can get a test up that confirms this.

**Comment by hskrasek** [comment]
@roquie Added tests that confirm you can define patterns using Laravel's router, and they will apply to the routes declared with dingo/api as well.

**Comment by hskrasek** [comment]
Gonna give you time to see this, and check it out. If theres no further activity after a while, I'll close out.

**Comment by roquie** [comment]
@hskrasek Wow, How fast! I didn't even finish the sentence... for answer to previous comment. One moment, please.

**Comment by roquie** [comment]
@hskrasek may add `getPatterns` method?
https://github.com/laravel/framework/blob/153af5cf27aaae42b21776633258b39677ab3865/tests/Routing/RoutingRouteTest.php#L965

**Comment by roquie** [comment]
> Gonna give you time to see this, and check it out.

Dummy object works fine.

**Comment by hskrasek** [comment]
@roquie I opted to not add any methods to Dingo's Router, since adding the params to Laravel's Router still applies to routes registered with Dingo. The tests I added confirms that this is working, or should be anyway, I emulated a lot of laravel's router stack with the stub classes. 


I'm gonna close this out, if theres still an issue with it, let me know or re-open and I'll look into it.

**Comment by phoenixg** [comment]
Is this feature still planed?

**Comment by anardil** [comment]
Hello,

Is there anyone who found how to use the patterns?

Thank you.
