### ISSUE TITLE
Tests broken or I'm doing something wrong?

### ISSUE THREAD

**Issue by ijin82** [dingo/api#742]
Hello guys. 
I'm currently using phpUnit in my L5 app with dingo. In some cases i want to send response data from one tests to another using *@depends*. So I'm doing something like this:
```php
        $url = route(config('api.prefix') . '.auth');
        $r = $this->post($url, [
            'email' => $u->email,
            'password' => $passwordDefault,
        ])->response->getData();

        $this->assertTrue(!empty($r->token), 'No token was found! Auth Error!');

        return (object) [
            'token' => $r->token,
            'id' => $u->id
        ];
```
And got this
```
PHPUnit 4.8.18 by Sebastian Bergmann and contributors.

.FSPHP Fatal error:  Call to undefined method Dingo\Api\Http\Response::getData() in /home/ijin82/projects/php/myapp/tests/TestCase.php on line 46
PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /home/ijin82/projects/php/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php:745
Stack trace:
```
Please help me to find out how to fix that. Looks like Dingo Response object has no such method, but i can't understand why in this case dingo Response used instead of usual L5 Response object.
Nothing special attached to tests, api calls using app models in some cases.

**Comment by jasonlewis** [comment]
The Dingo response object extends from the Illuminate response object (which extends from Symfony's). I don't think either have a `getData` method do they? What are you trying to get exactly? The content?

**Comment by ijin82** [comment]
@jasonlewis yup. I'm trying to get content from response, check it, and pass that to other tests.

**Comment by jasonlewis** [comment]
You can use `getContent` to get the content.

**Comment by ijin82** [comment]
@jasonlewis thank's, I'll check that out then report here

**Comment by jasonlewis** [comment]
How'd you go @ijin82?

**Comment by ijin82** [comment]
@jasonlewis frankly speaking I'm not sure what's happened. After I've reinstalled composer components.. that work's fine. I haven't fix code for Request object at all. Now methods **->response->getData()** available again. I think you can close this issue.
