### ISSUE TITLE
Can't add transformers within response

### ISSUE THREAD

**Issue by muhammadshakeel** [dingo/api#743]
Want to add a transformed object along with other response, I have used following code:

    $accessToken = Authorizer::issueAccessToken();

        $user = User::where('email', $request->get('username'))->with('profile')->first();
        if ($user) {
            $accessToken['user'] = $this->response->item($user, new UserTransformer);
        }

        return $accessToken;

Expected Response:

    {
        "access_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "token_type": "Bearer",
        "expires_in": 31536000,
        "data": {
          "id": 1,
          "email": "xxxxx",
          "profile": {
            "data": {
              "id": 1,
              "first_name": "Muhammad",
              "last_name": "Shakeel",
            }
          }
        }
    }

but not getting transformed object, there must be some better way to add multiple transformed objects with response. Am I missing something?

PS: Returning only the transformed object as following works correctly and sends transformed object:

    return $this->response->item($user, new UserTransformer);

**Comment by jasonlewis** [comment]
The only way you could do this at the moment would be to reverse that. So you'd return the response item, then add in the access token data, probably as meta data.

So, something like this.


```php
return $this->response->item($user, new UserTransformer)->setMeta($accessToken);
```

The response will then contain a meta data key which will contain your access token data.

**Comment by muhammadshakeel** [comment]
@jasonlewis thanks for your reply.

I guess we can add public transform method which only returns transformed object rather than response object and then we can add this to the response. 

I will further look into it when get some time.
