### ISSUE TITLE
Add response codes to documentation

### ISSUE THREAD

**Issue by andrewhl** [dingo/api#744]
I've taken the liberty of creating a table of all the Symfony HttpKernel exceptions, with corresponding response codes. Can you update the Errors and Responses wiki page with this table?

| Exception                                                                | Status Code |
|--------------------------------------------------------------------------|------------:|
| `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException`         |         403 |
| `Symfony\Component\HttpKernel\Exception\BadRequestHttpException`           |         400 |
| `Symfony\Component\HttpKernel\Exception\ConflictHttpException`             |         409 |
| `Symfony\Component\HttpKernel\Exception\GoneHttpException`                 |         410 |
| `Symfony\Component\HttpKernel\Exception\HttpException`                     |         500 |
| `Symfony\Component\HttpKernel\Exception\LengthRequiredHttpException`       |         411 |
| `Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException`     |         405 |
| `Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException`        |         406 |
| `Symfony\Component\HttpKernel\Exception\NotFoundHttpException`             |         404 |
| `Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException`   |         412 |
| `Symfony\Component\HttpKernel\Exception\PreconditionRequiredHttpException` |         428 |
| `Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException`   |         503 |
| `Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException`      |         429 |
| `Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException`         |         401 |
| `Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException` |         415 |

**Comment by jasonlewis** [comment]
You're more than welcome to submit a PR to [`dingo/api-docs`](http://github.com/dingo/api-docs) and I'll merge it in. :smile:

**Comment by andrewhl** [comment]
Okay, done.
