### ISSUE TITLE
How to set type of json response ?

### ISSUE THREAD

**Issue by seebosmile** [dingo/api#745]
How to set type of json response, so always return  as null.

```json
{
    "data": [
        {
            "type": null,
            "id": "1",
            "attributes": {
                "name": "fsdfsdsfsdfsd",
                "description": "sdfsdfsdfsd sdfsdfsd sdfsd sdfsdfsdfsd ",
                "date_created": "2015-08-23 19:39:29",
                "date_modified": "2015-08-24 04:04:41",
                "is_ready": 2,
                "status": "active",
                "latitude": "0",
                "longtitude": "0",
                "distance": "1.0 km",
                "user_like": 29
            }
        }
}
```

**Comment by jasonlewis** [comment]
Could you elaborate a bit please, I'm not entirely sure what you're after.

**Comment by b-hobbs** [comment]
It looks like he is using JSON-API serializer with fractal and am assuming they want to add a value for the type instead of it always being null.

If this is the case then you will want to pass a key to the item or collection for the third parameter, like:
```php
return $this->response->item($user, new UserTransformer, ['key' => 'thisIsAUserType'], function ($resource, $fractal) {
            $fractal->setSerializer(new \League\Fractal\Serializer\JsonApiSerializer());
});
```

```json
{
  "data": {
    "type": "thisIsAUserType",
    "id": "1",
    "attributes": {
      "email": "john@doe.com"
    }
  }
}
```

**Comment by seebosmile** [comment]
Thankyou , i solve problems by add   [ 'key' => "places" ]   in parameter.

<code>

    public function allplaces()
    {
        
        $Places = Place::all(); 
        return $this->response->collection($Places, new PlaceTransformer, [ 'key' => "places" ] );
        
        
    }

</code>
