### ISSUE TITLE
[Proposal] Automatically exclude `create` and `edit` from resource routes?

### ISSUE THREAD

**Issue by HipsterJazzbo** [dingo/api#747]
I find that when I'm building `$api-resource()` routes, i nearly always end up passing the option `['except' => ['create', 'edit']]`, because I don't think they make any sense for an API.

Is it worth excluding those by default for API resources? Would certainly make my routes file a lot cleaner.

**Comment by jasonlewis** [comment]
I'd be happy to accept a PR for this, because yes, you're right, they're essentially pointless routes in terms of an API.
