### ISSUE TITLE
Passing security Headers in api issue

### ISSUE THREAD

**Issue by manjeetambab** [dingo/api#748]
We want to pass header in api to check for authentication, Same api we are calling internally by using internal dingo api call in fronted section. 

Basically we tried to check authentication using middleware it worked fine for api call but header authentication is also required for internal dingo api call which shouldn't be the case.

Can we put some condition in middle ware so that header authentication should only apply on direct api call not the internal api call.

**Comment by jasonlewis** [comment]
You're using the packages middleware?

**Comment by manjeetambab** [comment]
No I have created middleware for headers to check the api's.

**Comment by jasonlewis** [comment]
Oh, okay. Well you can by-pass the checks for internal requests by checking the `$request` variables type.

```php
if ($request instanceof \Dingo\Api\Http\InternalRequest) {
    // do not check for the headers
}
```

**Comment by jasonlewis** [comment]
Ignore me. Internal requests aren't run through middlewares.

Is that the issue?

**Comment by manjeetambab** [comment]
see this is my code for api headers to check headers in api in middlware


   public function handle($request, Closure $next)
   {
       $secret = Config::get('app.secret');
       $secretmatch = $request->header('secret');
       $apiurl = Config::get('app.apiurl');
       $baseurl = 'http://'.Request::server("HTTP_HOST");
        if ($apiurl == $baseurl) {
           if($secret == $secretmatch)
           {
               return $next($request);
           }
           else
           {
               return 'invalid';
           }
       }
       return parent::handle($request, $next);

   }



now i wanted the middleware to check only for api domain and not for front domain

**Comment by jasonlewis** [comment]
In your `routes.php`, change `require_once` to `require`. Each time the application is destroyed and recreated the `api_routes.php` file isn't being required again because it's already been required. So the routes are never registered.

**Comment by jasonlewis** [comment]
As before, you should be able to check the `instanceof` the `$request` variable.

Regular requests have a type of `Illuminate\Http\Request`.

API requests have a type of `Dingo\Api\Http\Request`.

So, simply do the following.

```php
public function handle($request, Closure $next)
{
    if ($request instanceof \Dingo\Api\Http\Request)
    {
        $secret = Config::get('app.secret');
        $secretmatch = $request->header('secret');
        $apiurl = Config::get('app.apiurl');
        $baseurl = 'http://'.Request::server("HTTP_HOST");

        if ($apiurl == $baseurl) {
            if($secret == $secretmatch)
            {
               return $next($request);
            }
            else
            {
               return 'invalid';
            }
        }   
    }
    
    return parent::handle($request, $next);
}
```

**Comment by manjeetambab** [comment]
I am getting such an error
FatalErrorException in ApiMiddleware.php line 51: Cannot access parent:: when current class scope has no parent

**Comment by jasonlewis** [comment]
Oh, your last line, should be:

```php
return $next($request);
```

**Comment by manjeetambab** [comment]
Thanks a lot bro........It's working fine.....

**Comment by jasonlewis** [comment]
Excellent! Cheers @manjeetambab! :smile:
