### ISSUE TITLE
Rate Limiting should not apply to Internal Requests

### ISSUE THREAD

**Issue by aleemb** [dingo/api#751]
Not sure if it makes sense to count internal API requests toward the `limit`.

**Comment by lightvision** [comment]
From my point of view it make sense. If you are using your own api through internal requests in order to deploy saas apps it sure make sens. Think about you have several plans based on api usage ...

**Comment by aleemb** [comment]
I believe the more common use-case is to not limit web-form usage (Twitter, Google Search, Analytics, etc). In fact, I cannot think of any service that limits web-form usage along with API usage. So the limit is imposed on direct API calls only. In the interest of sensible defaults, it would be better to cater to the more common use-case.

Hopefully, a few others can chime in with their thoughts? @jasonlewis @lucasmichot @vinkla

**Comment by lucasmichot** [comment]
@aleemb indeed, it does not make sense with an internal request.
A good default would be to skip the rate limiting in this case.

Just my opinion -- @jasonlewis @vinkla ?

**Comment by vinkla** [comment]
I agree with @lucasmichot. Since you have full control over the internal requests anyway.

**Comment by andreygrehov** [comment]
I partially agree. Internal API consuming should be configurable, i.e. one can either rate limit it or disable the rate limiting all together. The reason for that is because internal API requests may potentially be more harmful than external ones.

**Comment by jasonlewis** [comment]
#752 was merged.

**Comment by andreygrehov** [comment]
thank you, @jasonlewis. It's an off-topic, but would be great to plan the 1.0 release, unless it hasn't been yet.
