### ISSUE TITLE
Issues With Ports

### ISSUE THREAD

**Issue by baileylo** [dingo/api#754]
There are a couple different issues with ports that have been brought up before, specifically the last comment in #570.

I ran across this same error and believe I have found the culprit, but want to make sure I'm not doing anything funky.

The domain of the request is validated twice, once by Laravel and once by Dingo. Unfortunately, the validators work differently. Specifically, the Dingo validator(Dingo\Api\Http\Validation\Domain) compares the host header, including port number. The laravel validator(Illuminate\Routing\Matching\HostValidator) on the other hand uses `Request::getHost` which excludes the port.

You should be able to fix the issue by switch your validation to wrap the laravel validator or use `getHost()`.

**Comment by MTon** [comment]
I tried ignoring the port on _Dingo\Api\Http\Validation\Domain_ but the problem seems to be that the  
`$hostRegex` of `Symfony\Component\Routing\CompiledRoute` always contains the port the API-Routes and therefore never matches the `Request::getHost` value.

Any suggestions on this?

**Comment by MTon** [comment]
Sorry for the massive amount of deleted pull-request. I messed up with the code-style-test!

**Comment by baileylo** [comment]
Yeah, I'd remove port from the matching of routes. Though maybe somebody runs their http api from a non standard port and will get mad at you. But that seems really unlikely to me.

**Comment by eduacostam** [comment]
I'm the OP of issue #570, I'll try to test this with my setup tomorrow, it would be really nice to have this working in dingo. I don't think many people would have their api in a non standard port.

Just so you know @MTon, when you mess up something in your PR you can force-push into your fork and the original PR will update with the new code, you don't need to close and make a new one!

**Comment by MTon** [comment]
> Just so you know @MTon, when you mess up something in your PR you can force-push into your fork and the original PR will update with the new code, you don't need to close and make a new one!

Yeah, realized that a little late. Next time  :-)

**Comment by MTon** [comment]
> Yeah, I'd remove port from the matching of routes. Though maybe somebody runs their http api from a non standard port and will get mad at you. But that seems really unlikely to me.

But in this case you probably have a separate laravel instance and routing and even vhost, so the request is unlikely to reach both routes at the same time.
Or am I missing something?
