### ISSUE TITLE
Best Practice for Repository binding

### ISSUE THREAD

**Issue by fbnigha** [dingo/api#756]
I could use some guidance on best practice for setting up repository binding considering API versioning.

Consider the case where we have a V1 API Users controller and a V2 API Users controller. Within the routes.php we have used the api router to set up two different routes based on this premise.

Something akin to:

```php
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('list', ['as' => 'users.list', 'uses' => 'Api\v1\UserController@list']);
});

$api->version('v2', function ($api) {
    $api->get('list', ['as' => 'users.list', 'uses' => 'Api\v2\UserController@list']);
});
```
The V1 Controller is to use the V1 UserRepository and the V2 Controller is to use the V2 UserRepository. The correct repository will then be injected into the controller constructor.

A non API situation would have the UserRepository bound in a service provider. What is the best practice to do this binding when it pertains to the route? The real scope would be larger with various other API version specific repositories that also need to be injected.

I also consider the case where I may do something like:

```php
$api->version('v1', function ($api) {
    $api->get('list', ['as' => 'users.list', 'uses' => 'Api\v1\UserController@list']);
    $api->get('foo', ['as' => 'users.list', 'uses' => 'Api\v1\UserController@foo']);
});

$api->version('v2', function ($api) {
    $api->get('list', ['as' => 'users.list', 'uses' => 'Api\v2\UserController@list']);
    $api->get('foo', ['as' => 'users.list', 'uses' => 'Api\v1\UserController@foo']);
});
```
This case reuses the V1 @foo method for both versions 1 and 2.

**Comment by jasonlewis** [comment]
I'm assuming your repositories implement some sort of contract.

If so this will influence what you do really. If you're interface changes between versions then you'll just need to bind each version and inject it as per normal. There's really no difference there at all.

Also, in the case of re-using certain methods for both versions, you can pass an array of versions to the `version` method if you wish to have routes respond to multiple versions.

```php
$api->version(['v1', 'v2'], function ($api) {
    $api->get('foo', ['as' => 'users.list', 'uses' => 'Api\v1\UserController@foo']);
});
```
