### ISSUE TITLE
New Authentication Provider ( KeyScopes )

### ISSUE THREAD

**Issue by ryanhungate** [dingo/api#761]
Hey @jasonlewis - so I may have been trying to reinvent something that didn't need to be done, but I feel like developers could get more done with something like this.

https://github.com/ryanhungate/api

I'm sure it's not ready yet for prime time but the concept is there.  The basic explanation of this, it's using database records to maintain the API keys and the service scopes... multiple scopes can be added of course and you can specify the service type and the scopes allowed for each scope record:

1. Issue an new API key for a user. Name it.  Users can have multiple API keys.
2. Add Scopes that have a 'service' and a 'scope'.  ( defaults to * on both which would be a wildcard ).
3. Secure routes by passing in another route parameter of "service" and by using the "scope" as usual.

All this really does is allow you to do something like this.

    Add a header :: Authorization scope:my_api_key_in_db

    app('api.router')->version('v1', function ($api) {
        $api->group(['middleware' => 'api.auth', 'providers' => ['scope']], function ($api) {
            $api->group(['prefix' => 'url_prefix', 'service' => 'my_service' , 'namespace' => 'App\Http\Controllers\Api\MyService'], function ($api) {
                $api->group(['scopes' => 'stats.*'], function ($api) {
                    $api->get('stats/today', ['uses' => 'StatsController@today']);
                });
            });
        });
    });

I don't know about you but I like the way this feels so far... it's easy to add database records to this thing and just test out using Postman... let me know if you think it's something that even matters to the project.

**Comment by jasonlewis** [comment]
Kind of sounds like you just needed a custom grant type for OAuth 2.0. In a couple of my own projects I've implemented a simple "key" grant which allows you to issue API keys and have them authenticated via OAuth 2.0.

What is the `service` you're using? What benefits does it have and how does it tie in with `scopes` exactly?

**Comment by ryanhungate** [comment]
Well this is where my ego may have gotten in the way of an already implemented solution, but to be completely honest, I have always just had a really hard time getting on the OAuth bandwagon, and have preferred more simple approaches to authentication like using an old fashioned API key.  This allows the application to generate keys for users, delete keys for users, charge for keys etc...

What i'm doing in this case, is creating a new authentication type named 'scope' which allows the users to have multiple API keys, and each key has access to a service / and a set of scopes that belong to that service alone.  ( of course you can do service = * and scope = * ) for a wildcard...

So Authentication is in the header, instead of 'bearer' it's 'scope:my_api_key'.  The authentication provider that's new here does all that heavy lifting so it will check to make sure that:

1. The routes are protected by a service flag
2. The routes are protected by a scopes flag

In a way this is just a decent role / permissions type of setup... the API key class has methods like: 

    $apiKey->hasScope('scope.1', 'service_1');

I don't know, maybe it's just me but I like having something like this.  It seems to be working quite well, but I'm working on some enhancements to it right now that would be geared towards a super admin perspective allowing the addition / deletion of keys and scopes for users... think of a front end for the back end management too...

**Comment by jasonlewis** [comment]
If it's working for you then there's no point trying to get something else to work. Just keep on keeping on. It sounds like a very flexible system. :+1:
