### ISSUE TITLE
Terminable middlewares are not longer called in lumen -> sessions broken

### ISSUE THREAD

**Issue by wirtsi** [dingo/api#762]
Hi there...

I just came across the issue, that when I use the dingo ServiceProvider in Lumen 5.1, the sessions no longer get written.

After some digging around I figured that this is because terminate method of the StartSession middleware is no longer called.

This seems to do with that the Lumen Adapter of Dingo wipes the middlewares on the application object. This causes an issue in the default Lumen Application

```
 if (count($this->middleware) > 0) {
            $this->callTerminableMiddleware($response);
        }
```

Since this is empty, the middleware is not called and therefore we write our session no longer.

Any idea on how to fix this?

bests

wirtsi

**Comment by hthabet** [comment]
Hi @wirtsi, check this out https://github.com/dingo/api/issues/721

Regards

**Comment by wirtsi** [comment]
ah damn, you are right. thanks for pointing me to this one...
