### ISSUE TITLE
Follow jsonapi spec

### ISSUE THREAD

**Issue by JamesGuthrie** [dingo/api#765]
I see that in #3 there was some deliberation as to how to format JSON responses. The decision was made to use the jsonapi format. I would prefer having the option to return a "simple JSON" format, which is why I have opened #764, but from what I can tell the current implementation of dingo/api does not follow the jsonapi spec at all. In particular, one of the first statements in the spec is: 

```
A document MUST contain at least one of the following top-level members:

data: the document's "primary data"
errors: an array of error objects
meta: a meta object that contains non-standard meta-information.
```

dingo/api's approach of keying the response by the table name from which the entities is fetched and not by `data` clearly flies in the face of the spec. I assume that there was a previous pre 1.0 version of the spec which allowed this, but none of the pre 1.0 versions are publicly available on jsonapi.org, also it makes no sense implementing a pre-1.0 version.

**Comment by bryannielsen** [comment]
I ran into something similar, the latest version of Fractal takes care of all this I think.  
But in order to get it right now you need to use `dev-master` for dingo/api and then specify the fractal version - `"league/fractal": "0.13.*"`

**Comment by JamesGuthrie** [comment]
Thanks for the feedback Bryan! I haven't managed to get it to work quite yet with the latest version of Fractal. It looks to me as though there is an overlap between Fractal's `Serializers` and Dingo's `Formatter`, and that what one would want to do is use Fractal's `JsonApiSerializer`. Unfortunately it doesn't look as though this can be configured in Dingo... Can you confirm this?

**Comment by bryannielsen** [comment]
Oh yea sorry I forgot about that step, this is what modifying the serializer looks like in Lumen for me - 

```
app('Dingo\Api\Transformer\Factory')->setAdapter(function ($app) {
    $fractal = new League\Fractal\Manager;
    $serializer = new \League\Fractal\Serializer\JsonApiSerializer($_ENV['API_DOMAIN']);
    $fractal->setSerializer($serializer);

    return new Dingo\Api\Transformer\Adapter\Fractal($fractal, 'include', ',', false);
});
```

I think there's some mention of that on the [Transformers page](https://github.com/dingo/api/wiki/Transformers) but I may have dug it up from somewhere else.  Hopefully that helps!

**Comment by JamesGuthrie** [comment]
I'm really not having much luck with this. While I can set the adapter, it doesn't have any effect on the output which I'm seeing, as Dingo's formatter is the last thing to touch the json before it is returned.

**Comment by bryannielsen** [comment]
So if you put this in your controller - 

`dd(app('Dingo\Api\Transformer\Factory')->getAdapter()->getFractal()->getSerializer());`

You're getting the default `DataArraySerializer` back?  

If that's the case something must be going awry with how the serializer is getting set in your case.  More details on your setup and the code you're using (and where it's located) might be helpful.  I have only done this in Lumen but maybe someone else has experience with issues in Laravel, though they should be very similar.

**Comment by JamesGuthrie** [comment]
When I put that in my controller, I get back whichever serializer I have configured in my AppServiceProvider, which contains the code that you suggested I use.

**Comment by jasonlewis** [comment]
If you're using transformers correctly then you'll be returning a simple array from your transformer, which when passed to the formatters will simply be formatted as JSON, nothing more.

The formatters do not follow any of the JSON API spec as it's just way to complicated to implement in a simple formatter. The methods you see there for formatting things like models and what not are merely for rapid development.
