### ISSUE TITLE
$api->resource route causes endless loop when called from tests (Lumen 5.1)

### ISSUE THREAD

**Issue by wirtsi** [dingo/api#766]
Hello

this took me a while to figure out: When I got something like this in my routes
```
$api->version('v1', function($api) use ($app){
    $api->group(['prefix'=>'api', 'namespace' => 'FeedApi\Http\Controller'], function($api)
    {
        $api->resource('feed', 'FeedController');
    });
});
```
Then normal browser calls work without any problems (GET, PUT, etc).
When you do this in functional tests
```
$this->get('api/feed')
```
Lumen goes into an endless recursion. Tracing through this, it appears that at the end of the request pipeline, a new request object is created, causing the whole pipeline to be run again

Now with these routes
```
$api->version('v1', function($api) use ($app){
    $api->group(['prefix'=>'api', 'namespace' => 'FeedApi\Http\Controller'], function($api)
    {
        $api->get('feed','FeedController@index');

        $api->get('feed/{id}','FeedController@show');

        $api->post('feed','FeedController@store');

        $api->put('feed/{id}','FeedController@update');

        $api->delete('feed/{id}','FeedController@destroy');
    });
});
```
the test are working, $this->get('api/feed') speaks to the controller, pulls the data and so on

Bests
wirtsi

**Comment by jasonlewis** [comment]
Thanks for the report. Will investigate when I can.

**Comment by jasonlewis** [comment]
Finally getting around to this.

I'm unable to see any sort of endless loop. Even when a controller method internally calls another. For example, this is my `FeedController`:

```php
namespace App\Http\Controllers;

class FeedController extends Controller
{
    use \Dingo\Api\Routing\Helpers;

    public function index()
    {
        return $this->api->get('feed/1');
    }

    public function show($id)
    {
        return ['showing' => $id];
    }
}
```

And my routes...

```php
app('Dingo\Api\Routing\Router')->version('v1', function($api) use ($app) {
    $api->group(['namespace' => 'App\Http\Controllers'], function($api) {
        $api->resource('feed', 'FeedController');
    });
});
```

And my test...

```php
class ExampleTest extends TestCase
{
    public function testBasicExample()
    {
        $this->get('api/feed');

        $this->seeJson(['showing' => '1']);
    }
}
```

The test passes as expected. Even when the `index` method returns its own response I'm seeing tests pass.

Are you still able to produce this error? Ping me here if you are and provide as much code as you can so I can replicate it.
