### ISSUE TITLE
Is it possible to have certain routes only be consumed internally?

### ISSUE THREAD

**Issue by jbardnz** [dingo/api#767]
As the title says, not sure if this is already in the package by default?
If not could it be achieved by some custom middleware?

**Comment by lucasmichot** [comment]
Yeah create your own middleware, it could just return something like:
```php
if ( ! $request instanceof \Dingo\Api\Http\InternalRequest) {
   throw new \Exception('internal api only');
}

return $next($request);
```

**Comment by jbardnz** [comment]
Awesome, this will be really helpful :)

Thanks for the info.
