### ISSUE TITLE
Is it possible to override status code for expired JWT token ?

### ISSUE THREAD

**Issue by mrgodhani** [dingo/api#768]
Hi

Currently if token expires it gives us 400 error. Is it possible to override that status code in Dingo API? 

I tried out making token expire (with same signature)  but it gives me error saying 

"message": "Token Signature could not be verified."

**Comment by jasonlewis** [comment]
Is it from a thrown exception? If so you might (should) be able to catch it by registering a listener.

Use `app('Dingo\Api\Exception\Handler')->register()` to register a custom listener and return an appropriate HTTP response.
