### ISSUE TITLE
[question] internal request performance

### ISSUE THREAD

**Issue by Edwin-Luijten** [dingo/api#769]
Hi guys,

I'm trying to wrap my brain around internal requests. My first thought was that it would have a performance impact because of extra http requests. But on the other hand (don't know for sure) because the request is made on the same network as where the server is this would be minimal right?

If not, then you would need to configure(upgrade) your server to handle more http requests.

Hope anyone could enlighten me on this subject =).

**Comment by JamesGuthrie** [comment]
Internal requests are not sent via http at all, they never leave the application, they directly request the route internally.

**Comment by jasonlewis** [comment]
You shouldn't see any adverse affects from using internal requests as they are merely fired internally through the router. This means they don't reboot the application or anything. It goes straight through the already instantiated router. Should be nice and quick.
