### ISSUE TITLE
Custom route in controller

### ISSUE THREAD

**Issue by christiancannata** [dingo/api#770]
Hi,
Can I create a custom route with a method in my controller and autoload with standard route declaration?
ex:

$api->resource('user', '\Meritocracy\Http\Controllers\UserController');

this loads only standard routes of my UserController, I have a new method that I would to expose as 
/user/1/vacancies

Can I make it?

**Comment by jasonlewis** [comment]
I'm unsure as to what you're after exactly.

You can use regular Laravel routes alongside Dingo routes, just make sure your Dingo API routes are within an API route group so they are routed correctly.
