### ISSUE TITLE
How does the transformer work?

### ISSUE THREAD

**Issue by imamassi** [dingo/api#771]
I tried so hard to know how the transformer work on dingo. This is my code:

(my API Controller)
```php
public function index(Request $request){
        if($request->status){
            $status = explode(',',$request->status);
            $hadits = DB::table('hadits')->whereIn('status',$status)->get();
        } else{
            $hadits = collect(DB::table('hadits')->get());
        }
        foreach($hadits as $single){
            $single->url = 'http://api.carihadits.com/hadits/'.$single->id;
        }
        if($request->paginate == true){
            $hadits = $this->paginate($hadits, $request->perpage ?? 10, $request->page ?? 1, $request->all());
        }
        return $this->response->item($hadits, new HaditsTransformer());
    }
```
```php
class HaditsTransformer extends TransformerAbstract implements Adapter
{
    public function transform($response, $transformer, Binding $binding, Request $request)
    {
        return ['test'];
    }
}
```

Does the return value must be only 'test'? Not the entire 'hadits' object? What did I do wrong there?

**Comment by DavidStrada** [comment]
Bear in mind I just discovered this package ( Dingo ), As far as I have been reading Dingo uses `Fractal` package to performed data onto e.g. JSON API compliant or whatever, you should check [http://fractal.thephpleague.com/transformers/](fractal transformes ) to see how they work.

**Comment by jasonlewis** [comment]
Refer to the Fractal documentation for help on how to use transformers. You do not need to implement your own adapter (what you're doing) unless you really need some sort of custom functionality.

You just need to extend the `TransformerAbstract`, then implement the `transform` method which should receive an instance of the object you pass to it from your controller.

Then you can returned the transformed data from that method.
