### ISSUE TITLE
All routes return 404

### ISSUE THREAD

**Issue by phroggyy** [dingo/api#772]
Somehow, I've followed all the installation instructions, but all my API routes are still returning 404, and I'm tearing my hair out for something that's probably really easy.

My routes file looks as follows:
```php
/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where all of the API routes are registered through the Dingo
| API package. It works just the same way as the standard Lumen and
| Laravel routing, but has its own router with special functions.
*/

$api = $app->make('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('/', function () {
        return [
            'name' => 'John Doe',
        ];
    });
    $api->group(['namespace' => 'App\Http\Controllers\Api'], function ($api) {
        $api->get('skills', 'SkillController@all');
    });
});
```

And then the relevant `.env` variables are:

```
API_DOMAIN=leosjoberg.dev
API_PREFIX=api
```

I have no clue what's happening and don't really see how it could happen, so any and all help on this issue is much appreciated. The only similar issues I found were regarding using custom ports.

**Comment by baileylo** [comment]
You're pinging `api.leosjoberg.dev/`?

**Comment by phroggyy** [comment]
Nope. As to my understanding `API_PREFIX` is just to provide a huge `group('prefix' => env('API_PREFIX'))` wrapper, so it'd go to `leosjoberg.dev/api`

**Comment by phroggyy** [comment]
_Sighs_
I don't know why, but I assumed `$api->version` would set a version prefix for the route, turns out it didn't as I followed down the stack.
