### ISSUE TITLE
Calling collection without return does not use transformer.

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#777]
Hey, so I have a `gallery` item which has many `images` defined via a polymorphic many to many relationship.

If I use an include it works fine, but it seems suboptimal, as this will add all images to the include part using the json serializer. As they are not indexed by id in the `include` part of the response, I would have to loop through all of them to figure which one belongs to which gallery. I fear this will drain performance.

I want to get something like this:

``` javascript
{
"type": "gallery",
"id": "ab2ccbf9-0c24-3745-983a-44b622eb6924",
"attributes": {
  "slug": "omnis",
  "created_at": "2015-12-18 15:01:21",
  "updated_at": "2015-12-18 15:01:21",
 "images":  {
  "data": [
  {
    "type": image,
    "id": "03ebf27f-b494-3ae9-b3c2-a56264d51490",
    "path":"image/path.png"
  },
  {
    "type": image,
    "id": "eccb16b3-fe29-31b1-9004-8b7f586b9ad4",
    "path":"image/path.png"
  }
  ]
 }
}
```

I could achieve something like this by just using the normal laravel relationship in the transformer instead of the include, but this will create 2 problems:

``` php
public function transform(Gallery $gallery)
    {
        return [
            'id'              => $gallery->id,
            'slug'          => $gallery->slug,
            'images'     => $this->collection($gallery->images, new ImageTransformer, function ($resource, $fractal) {
                $fractal->setSerializer(new DataArraySerializer);
            })->getData(),
            'created_at'    => (string)$page->created_at,
            'updated_at'    => (string)$page->updated_at,
        ];
    }
```
1. I can not embed via url, because it will always be included
2. The transformer is actually not applied

Any idea how I can solve this issue?

**Comment by jasonlewis** [comment]
I want to implement a way for folks to manually fire a transformer, as I think it does have a lot of usage in certain situations. This looks like one of them.

I'm away for the next few weeks though so I won't have time to implement anything until earlier in the new year.

**Comment by lukasoppermann** [comment]
Sounds good, thank you very much.

**Comment by bcarroll22** [comment]
In my mind, this could also be related to some of the issues I've had with the package trying to eager load for you. If, for instance, you had the ability to run your query, define your relationships when you ran the query, and then when you call $this->response->item($gallery, new GalleryTransformer), then all it would do is run the transformer and not assume you need things to be loaded for you, I think this problem could be avoided altogether. I suppose if you wanted to manually call transformers you could also still just do...

```
$transformedGallery = new League\Fractal\Resource\Item($gallery, new GalleryTransformer)
```

...right?

**Comment by fantiq** [comment]
```
$user = DB::table('user')->get();
$user = Collecton::make($user);
$this->response->collection($user, new UserTransformer);
```

**Comment by hskrasek** [comment]
@bcarroll22 You're right about the loading issue, its not exactly a Fractal issue as it is an ORM/logic issue. What could be nice, is a way to easily get the available parsed includes in your controller, so that you could eager load vs. having to lazy load.

Something like:

```
$gallery = Gallery::with($this->includes())->find($id);
```

**Comment by hskrasek** [comment]
So I was reminded of a feature that dingo contains, which is eager loading relationships for you. So, now I'm not sure I fully understand the issue at play here

**Comment by lukasoppermann** [comment]
I am not really sure about it either anymore. :(

**Comment by hskrasek** [comment]
@lukasoppermann If you have an example that you could put somewhere that re-creates this issue, might help in figuring out whats going on. Gonna try and re-create myself later today as well

**Comment by bcarroll22** [comment]
It's been a long time since I was using this package and having this issue, but I think the problem that I was having was that I wanted to be able to query the data myself, and choose my own eager loaded includes, and just pass that to dingo's response method and have it just run the transformer, nothing else. If I recall correctly, dingo was doing some internal work to figure out what it should include and then eager loading those things, and it was just buggy. I think there may be an old issue I had open that detailed it more.

**Comment by hskrasek** [comment]
@bcarroll22 Internally Dingo is trying to handle eager loads. I'm not sure I'd say it was buggy, but I don't see a ton of documentation on it, and it makes a lot of assumptions. One of those being, you'd name your includes the same as your relationships.

The package does have the option to disable the eager loading so you can handle it yourself though.

**Comment by bcarroll22** [comment]
Yeah it was a more in depth issue than that. Like I said, I can’t remember
exactly what the issue was, but there was a huge performance impact on
whatever was happening internally. I’ll see if I can dig around and find
the problem I was referencing in my original comment.
