### ISSUE TITLE
Dingo\Api\Provider\LaravelServiceProvider::class

### ISSUE THREAD

**Issue by yaoshanliang** [dingo/api#778]
Why when I use the following, it told me `PHP Fatal error:  Class 'Dingo\Api\Provider\LaravelServiceProvider::class' not found in ...`

    'providers' => [
        Dingo\Api\Provider\LaravelServiceProvider::class
    ]

And 

    'providers' => [
        Dingo\Api\Provider\LaravelServiceProvider
    ]

is ok.

**Comment by lucasmichot** [comment]
Because your version of PHP does not support it
http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class
