### ISSUE TITLE
Application (not API) Exceptions keeps being transformed to JSON

### ISSUE THREAD

**Issue by bahjaat** [dingo/api#784]
Got my API into the same installation as my webapplication.

Defined my API-routes in routes.php below the Laravel routes.
```php
    $api = app('Dingo\Api\Routing\Router');
    app('Dingo\Api\Transformer\Factory')->register('Abc', 'AbcTransformer');
    app('Dingo\Api\Transformer\Factory')->register('Xyz', 'XyzTransformer');
    $api->version(['v1', 'v2'], function ($api) {
        ...
    });
    ...
```
But when I am using my webapp and something went wrong, an Exception is throwing and it is JSON-formatted als the API_DEFAULT_FORMAT option in the configfile.

But I want the regular StackTrace.

Can't figure out where and why this happens.

**Comment by bahjaat** [comment]
Anyone?

**Comment by fbingha** [comment]
I just encountered this when trying to add a few standard HTML routes for static content.

**Comment by jasonlewis** [comment]
The exception handler has been tweaked slightly since this issue was opened. If you're still seeing this issue please provide as much code as you can so I can attempt to reproduce, including versions of this package and Laravel/Lumen.
