### ISSUE TITLE
UnauthorizedHttpException with Laravel 5.2

### ISSUE THREAD

**Issue by LukasMa** [dingo/api#788]
Hi, as I mentioned in #779 there is an issue with JWT-Authentication in Laravel 5.2. After testing a little bit, I found out that it is in fact dingo and not the jwt package that is responsible for this error:
To be a bit more specific:
The file
"vendor\dingo\api\src\Auth\Provider\JWT.php" throws a
"Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException" with message
"Token Signature could not be verified."
 
But as @jasonlewis mentioned in #785 dingo isn't ready for 5.2 yet and might have some issues. 

I just opend this issue, so it doesn't get missed somehow :)

**Comment by andrewmclagan** [comment]
having the same issue

**Comment by dongkaipo** [comment]
+1

**Comment by helloflow** [comment]
+1

**Comment by fbingha** [comment]
There have been no commits to this project since Dec 23rd. Is this project on hold? Any timeline on Laravel 5.2 fixes?

**Comment by jasonlewis** [comment]
I believe this was fixed within the following commit: 5775a31f887ac52999bcac5e589af6cb6c64bae9

I'm able to generate and authenticate with a token on Laravel 5.2 using JWT Auth 0.5.9.

**Comment by andrewmclagan** [comment]
yep, also here

**Comment by jasonlewis** [comment]
@andrewmclagan if you've updated to the latest version please open a new issue if you're encountering something you think is a bug. Provide as many details as you can so I can try and replicate your issue and resolve it ASAP.

**Comment by andrewmclagan** [comment]
Sorry I was agreeing. All ok since 5775a31

**Comment by jasonlewis** [comment]
Okay, cheers for that! :)

**Comment by johannesschobel** [comment]
Is it possible, that the error still exists in Laravel 5.1?

**Comment by erdemdur** [comment]
this error still exist in Lumen 5.2
