### ISSUE TITLE
Question: How can I throttle by the second?

### ISSUE THREAD

**Issue by jaesung2061** [dingo/api#789]
I want to limit a route by the second, not by the minute. How can I achieve this?

**Comment by jasonlewis** [comment]
Should just be able to divide however many seconds you want by 60 to get the desired amount. I would just put the math directly in as the parameter though.

So if you wanted, say, 10 second throttle, you'd use an expires time of `10/60`.

**Comment by jaesung2061** [comment]
Follow up question. Why isn't this snippet within my controller method working?

```
$this->middleware('api.throttle', [
    'limit' => 1,
    'expires' => 15
]);
```

**Comment by jasonlewis** [comment]
Because the parameters aren't actually passed to the middleware like that.

You'd need to use the `Helpers` trait, then you can call the `rateLimit` method (you still need to apply the middleware).

```php
$this->rateLimit(1, 15);
```

First parameter is the limit and the second is expiration.
