### ISSUE TITLE
Get url via route?

### ISSUE THREAD

**Issue by cermat** [dingo/api#792]
How to get route url. Normal laravel route collection we use route('name.something')

Thanks

**Comment by arthurkirkosa** [comment]
```
php artisan api:routes
```

If you defined a name for them in the api routes section you can "call" them the same as you did with the Laravel ones.

**Comment by jasonlewis** [comment]
See the wiki: https://github.com/dingo/api/wiki/Creating-API-Endpoints#named-routes-and-generating-urls
