### ISSUE TITLE
Logging all errors

### ISSUE THREAD

**Issue by joshhornby** [dingo/api#794]
I want to log all 4xx and 5xx errors in my API, I currently throw errors as shown in the docs so for example `throw new StoreResourceFailedException();`

I notice that these errors don't hit Laravels `Exceptions\Handler` report or render methods. Does anyone know a way to easily catch all errors so I can Log them?

**Comment by enjoy2000** [comment]
Did you comment out HttpException::class in $dontReport property?

**Comment by driesvints** [comment]
Dingo has its own exception handler class so adding them to your Laravel's `$dontReport` array won't help. I just wanted to open a ticket myself when I saw this issue.

@jasonlewis any chance there could be some way so we can extend Dingo's exception handler? That way we can filter out exceptions from our log files as well.

**Comment by driesvints** [comment]
Ok, just noticed this issue: #797. Hope it gets merged and tagged soon :smile:

**Comment by jasonlewis** [comment]
Reporting is now passed back up to the Laravel handler so this should no longer be an issue, `$dontReport` will work as per usual.

If you need further customization of the exception handler just extend and rebind it in the container.
