### ISSUE TITLE
$route->uri() returns ? after uri

### ISSUE THREAD

**Issue by 0plus1** [dingo/api#799]
It's not a big deal, more of a curiosity, I've noticed that $route->uri() return uri along with a trailing ?

As defined in Dingo\Api\Routing\Route;

Looks like the line collecting this data is \Dingo\Api\Routing\Adapter\Lumen:131
$uri = ltrim(isset($route['uri']) ? $route['uri'] : $request->getRequestUri(), '/');

Which picks up the Illuminate\Http\Request object.

Can someone explain this behaviour?
Cannot seem to find any information about this one.

Thanks

**Comment by jasonlewis** [comment]
Unsure why it would be adding a `?` to the end. The only manipulation done to the URI is to trim trailing and leading slashes in most cases.

Can you give me some code samples I can try, and your version of Lumen?

**Comment by jasonlewis** [comment]
I think I found the culprit here and have pushed a patch.
