### ISSUE TITLE
Exceptions/Handler.php in lumen

### ISSUE THREAD

**Issue by 0plus1** [dingo/api#801]
Looks like this package skips the lumen Exception/Handler.php file.

In particular I need to add the CORS header to the render method. Looking into the code it looks like the package is using ding/api/src/Exception/Handler.php as it's exception handler. Is there any way to extend this file from the expected lumen Handler?

Thanks

**Comment by 0plus1** [comment]
Looks like #797 does exactly what I am looking for. Guess will wait for new version.

**Comment by mikkokut** [comment]
I actually had the exactly same issue when I developed this solution, I needed cors headers for error responses.

**Comment by jasonlewis** [comment]
Rendering is and will always be handled by Dingo's exception handler. The handler does now fall back on to the Laravel/Lumen handler so exceptions are reported correctly.

If you need further customization of the handler you're free to extend it and rebind it in the container.
