### ISSUE TITLE
Adding Issue #802 to the Wiki

### ISSUE THREAD

**Issue by Deleugpn** [dingo/api#803]
I'm totally new to contributing to Wiki on GitHub so forgive me if I did something (or a lot of things) wrong.

Following on [this answer on StackOverflow](http://stackoverflow.com/a/11481887/1014588), I created a repository at https://github.com/Deleugpn/dingo-api-wiki to add the [Issue #802](https://github.com/dingo/api/issues/802) to the Docs. The [changes can be seen here](https://github.com/Deleugpn/dingo-api-wiki/commit/0546bb22dcd3ecf0b37cd8d42839bc2d2a79343c).

Thank you for your attention.

**Comment by jasonlewis** [comment]
Done. Thanks.

For future reference you can submit documentation PRs to [dingo/api-docs](http://github.com/dingo/api-docs). I can merge it from there to the Wiki here.
