### ISSUE TITLE
Array Combine error when not using v1, v2, ..., vn in API_VERSION

### ISSUE THREAD

**Issue by Deleugpn** [dingo/api#804]
I tried to set the API_VERSION env variable to **develop** and when accessing the API all I would get was 

```array_combine(): Both parameters should have an equal number of elements```

I found out that I'm bound to use the letter **v** followed by a number. Ideally, the error message would be more meaningful in this case, but it seems a silly problem to go about changing source code to achieve a better error message.

Instead, should this be added to the Wiki?

I've been following the Wiki step by step and I've proposed a change in the Wiki for the API_NAME variable. This seems to be a good case for it too, right?

**Comment by jasonlewis** [comment]
I'll work on better reporting for some of these errors so they're more meaningful.

**Comment by jasonlewis** [comment]
Versions are no longer required to begin with `v`.
