### ISSUE TITLE
Error in Dingo\Api\Http\Middleware\Request in lumen 5.2

### ISSUE THREAD

**Issue by tralves** [dingo/api#805]
The problem is that in Lumen 5.2 (for some reason) ``Laravel\Lumen\Application`` no longer implements ``\Illuminate\Contracts\Foundation\Application``.

This causes ``Dingo\Api\Http\Middleware\Request`` constructor to fail.

I fixed it by replacing ``\Illuminate\Contracts\Foundation\Application`` with ``\Illuminate\Contracts\Container\Container``, which will work both on Laravel and Lumen.

I am not happy with this fix, or I would PR it...

**Comment by tralves** [comment]
In case anyone wants it, I fixed this issue [here](https://github.com/tralves/api).

Also, I am happier with this solution now.

**Comment by irazasyed** [comment]
Same here, just came across this issue after switching to Lumen 5.2. Thanks for the solution btw.

**Comment by irazasyed** [comment]
You should open a PR!

**Comment by irazasyed** [comment]
I just opened a PR.

**Comment by joInMontreal** [comment]
@jasonlewis Has this issue been fixed on master ? 
If not, where can I follow the status of this issue ?

Thanks
