### ISSUE TITLE
Transformers not working

### ISSUE THREAD

**Issue by whitefoxy** [dingo/api#807]
When I try to implement transformer in the response I get the next error:

```
{
  "message": "Call to undefined method App\\Http\\Transformer\\UserTransformer::getAvailableIncludes()",
  "code": 1,
  "status_code": 500
}
```

I documentation there are nothing about this.

**Comment by prapats** [comment]
Have you already extended `League\Fractal\TransformerAbstract` in your transformer?

Can you post your `UserTransformer` here?

**Comment by whitefoxy** [comment]
Yes, I have created this class, but it is empty with only `transform` method where I make a debug output to understand how it must work. In documentation is written only 2 words about creating the transformer class.

**Comment by prapats** [comment]
Dingo uses Fractal's transformer, so you might be able to find more information on their website. http://fractal.thephpleague.com/transformers/

**Comment by whitefoxy** [comment]
After reading this page I don't understand why they are better than Eloquent. Transformers are doing the same, but they are implemented not so good and functionality in many times lower.

**Comment by AndyWendt** [comment]
@whitefoxy They do something different than eloquent :smile: 
They are a transformation layer between the database (private api) and the response data (public api).  

It really is a cool concept that allows you to change your database fields without destroying the usability of your api.

So a transformation could work like so: 

```
backend => frontend

id => user_id
name => user_name
phone => telephone
etc...
```

**Comment by whitefoxy** [comment]
@AndyWendt Okey, now I see why they are good. The documentation must be extended.

Now I have 2 problems:
1. How to register the transformer?

```
app('Dingo\Api\Transformer\Factory')->register('User', 'UserTransformer');
return User::all();
```

These code don't work, it return the Eloquent model.

2.
```
$users = User::all();
return $this->response->collection($users, new UserTransformer);
```

These code works, but the response looks like:

```
{
  "data": [
    {
      ...
    }
}
```

How to remove "data" and make in plain array, how do it:
 ```return $this->response->array($users->toArray());```

**Comment by prapats** [comment]
@whitefoxy That's related to Fractal's Serializer again. I think they use `DataArraySerializer` by default, but you can configure the serializer in the config file.
https://github.com/dingo/api/wiki/Configuration#response-transformer

Fractal's Serializer
http://fractal.thephpleague.com/serializers/

**Comment by prapats** [comment]
@AndyWendt @whitefoxy 
From what I understand, you can type-cast your data too in the transformer, but I believe it's better to use `$casts` property in a `Model` instead, and also nest relationships is another benefit. I still wonder are there any benefits using a transformer apart from those cases?

**Comment by AndyWendt** [comment]
@whitefoxy I would recommend leaving `data` since it allows extra attributes to be added like pagination information to the payload.  You  would otherwise be unable to have that extra meta-data.  

See the [json api spec](http://jsonapi.org/) for an example of why you probably want to keep this unless your api is really small.

**Comment by whitefoxy** [comment]
@AndyWendt I just have not seen any API with `data` object. It looks not so good as without this `data`. Meta can also be included into the headers, like Github is doing.

**Comment by AndyWendt** [comment]
@whitefoxy It is probably more prevalent than most know since it allows a good amount of flexibility.  Some things are good to go into the headers, but pagination and related data probably would be better in the payload.  Here is an example of [facebook using the pattern](https://developers.facebook.com/docs/graph-api/using-graph-api#cursors)

**Comment by AndyWendt** [comment]
I also saw SalesForce's API doing something similar: 

```
{
  "totalSize": 31,
  "done": true,
  "records": [
    {
      "attributes": {
        "type": "Opportunity",
        "url": "/services/data/v35.0/sobjects/Opportunity/00661000004drIaAAI"
      },
      "Name": "United Oil Installations"
    },
    {
      "attributes": {
        "type": "Opportunity",
        "url": "/services/data/v35.0/sobjects/Opportunity/00661000004drIbAAI"
      },
      "Name": "Grand Hotels Generator Installations"
    }
  ]
}
```

**Comment by whitefoxy** [comment]
@AndyWendt @prapats Thank you for your help and the detailed description. You have convinced me that transformers is a good thing and that `data` is also good :smile: . This information should be added to the wiki, it will help many others.

**Comment by AndyWendt** [comment]
@whitefoxy would you mind closing this issue, it looks like we have resolved it :smile:,  so that the repo owner doesn't have to?  I have a few repos myself and I know it helps me out when people do this :smile:
