### ISSUE TITLE
A story with 304 status, last-modified header , CORS and Apache

### ISSUE THREAD

**Issue by catalinux** [dingo/api#814]
The Dingo Api Router has a feature that if you called a `setLastModified` it will automatically return a 304 Not modified, next time when you  have a `If-Modified-Since` header yo your request. 

That might be great, till you need to use it with CORS. I have a middleware that ads CORS headers and handles pre-flight calls. The problem comes from apache that strips any other header when you have a 304 status.  That was their way to undestand the HTTP protocol. 

Google Chromes does not care about that and when you have a xhr request he really needs that `Access-Control-Allow-Origin`. 

Question: is there a way to change that 304 status code that the Router makes happen?  In router we have a `            $response->isNotModified($request);` with ads 304 status (Symfony\Component\HttpFoundation\Response)

One solution would be for me to extend de Dingo Router class and change how `    protected function prepareResponse($response, Request $request, $format)` works.

Did you had a similar problem? How did you solve it?

P.S: 204 Status - would pass all header when going through apache
p.s: other solution would be to use nginx, but is not handy in this moment

**Comment by jasonlewis** [comment]
Well, that's painful that Apache does that. I thought it only stripped out non-standard headers, so CORS headers should be fine. That's obviously not the case?

**Comment by catalinux** [comment]
well, not according to apache: https://github.com/apache/httpd/blob/trunk/modules/http/http_filters.c

Should we make a config in .env for this header?

```c
    if (r->status == HTTP_NOT_MODIFIED) {
        apr_table_do((int (*)(void *, const char *, const char *)) form_header_field,
                     (void *) &h, r->headers_out,
                     "Connection",
                     "Keep-Alive",
                     "ETag",
                     "Content-Location",
                     "Expires",
                     "Cache-Control",
                     "Vary",
                     "Warning",
                     "WWW-Authenticate",
                     "Proxy-Authenticate",
                     "Set-Cookie",
                     "Set-Cookie2",
                     NULL);
    }
    else {
        send_all_header_fields(&h, r);
    }

**Comment by jasonlewis** [comment]
Yeah, done a bit of research, Apache is just being silly I think.

If you have to stick with Apache then I'd just rebind the router and replace the `prepareResponse` method with something like this:

```php
protected function prepareResponse($response, Request $request, $format)
{
    $response = parent::prepareResponse($response, $request, $format);

    if ($response->getStatusCode() == 304) {
        $response->setStatusCode(204); // Or 200, not ideal, but eh.
    }

    return $response;
}
```

You can rebind the router in your own service provider (loaded after the Dingo one), just make sure your router extends from the Dingo one.
