### ISSUE TITLE
Custom pagination meta data

### ISSUE THREAD

**Issue by Luddinus** [dingo/api#815]
Hi. I think it should be easy but I don't see the way to add some data to the paginator.

```
public function paginate()
{
   $users = User::paginate(100);

   return $this->response->paginator($users, UserTransformer::class);

   /* returns:
   count: 9
   current_page: 1
   links: {next: "http://localhost/modfie/public/api/agencies/current/modfies?page=2"}
   per_page: 9
   total: 100
   total_pages: 12

   I want to add
   "from: X",
   "to: Y"
   */
}
```

What Can I do?
Thx.

**Comment by Luddinus** [comment]
up

**Comment by Luddinus** [comment]
up++

**Comment by jasonlewis** [comment]
That's all handled by Fractal, Dingo doesn't really have anything to do with that at all.

**Comment by banandam** [comment]
$res =  $this->response->paginator($users, UserTransformer::class);
$res->addMeta('from' , x);
$res->addMeta('to' , y);
return $res;
