### ISSUE TITLE
ValidationHttpException bubbling up to App\Exception\Handler

### ISSUE THREAD

**Issue by michaelstivala** [dingo/api#816]
Hi,

I'm experiencing some strange behaviour when performing internal requests.

I've got an Api controller with a Form Request (extending off Dingo's FormRequest object) that validates. When the validation fails, an InternalHttpRequest is being thrown, instead of a ValidationException.

For some reason the ValidationHttpException thrown by Dingo's FormRequest is bubbling up to my App\Exceptions\Handler class, which is returning an error response. 

I tested Dingo's Dispatcher class below, and since the ValidationHttpException is being caught and handled by my own Handler class then it no longer is being caught as an HttpExceptionInterface, but is being thrown as an InternalHttpException since the Response has already been generated as unsuccessful.

```
protected function dispatch(InternalRequest $request)
    {
        $this->routeStack[] = $this->router->getCurrentRoute();

        $this->clearCachedFacadeInstance();

        try {
            $this->container->instance('request', $request);

            // The router is not throwing a ValidationHttpException as I would expect, it is returning a formatted error response, generated by App\Exception\Handler.php
            $response = $this->router->dispatch($request);

            if (! $response->isSuccessful()) {
                throw new InternalHttpException($response);
            } elseif (! $this->raw) {
                $response = $response->getOriginalContent();
            }

         // The desirable  behaviour (which is to catch this exception and throw it correctly) is not happening
        } catch (HttpExceptionInterface $exception) {
            $this->refreshRequestStack();

            throw $exception;
        }

        $this->refreshRequestStack();

        return $response;
    }
```

I can't figure out the problem - this worked fine before updating to Laravel 5.2. I also can't figure out a workaround.

Any thoughts or help on this issue please?

**Comment by Luddinus** [comment]
same issue here, I want to catch TokenMismatchException, but always returns "{"message":"500 Internal Server Error","status_code":500}"

**Comment by catalinux** [comment]
I have a similar issue. Do you use Lumen or Laravel?

**Comment by Luddinus** [comment]
Me, Laravel

**Comment by jasonlewis** [comment]
> this worked fine before updating to Laravel 5.2

I still haven't had a chance to check everything under 5.2, so expect things to break.

**Comment by michaelstivala** [comment]
Thanks Jason.

Are there plans for this package to be updated to support 5.2 fully?

**Comment by jasonlewis** [comment]
So I've found the cause of this. It seems in 5.2 there's an extra layer of exception handling thrown in to the routing process. Namely, 5.2 uses its own [Pipeline](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Pipeline.php) for the routing. 

Thankfully the fix was simple. All exceptions should now be thrown correctly so that Dingo handles them.

**Comment by michaelstivala** [comment]
Thanks for taking the time Jason.

I've updated to the latest (70d2746) but still seem to be experiencing this InternalHttpException `at Dispatcher->dispatch(object(InternalRequest)) in Dispatcher.php line 435`

Is there anything else I should be doing to get this to work?

**Comment by michaelstivala** [comment]
Actually - never mind the above.

It's not throwing an InternalHttpException anymore - it's throwing the correct Exception - Great!

However... I'm not able to catch the error and handle it how I see fit. It seems that exceptions bubble up to any exception handlers I define in App\Exceptions\Handler *during internal requests*. 

I would expect the exception handler to only be called once the internal request is finished - so that I can handle it accordingly.

For example, I'm throwing a ConflictException. The below exception handler doesn't work as expected:

```
if ($e instanceof ConflictHttpException) {
    flash()->warning("Confict! " . $e->getMessage());

    return back()->withInput();
}
```

What happens instead is a new Exception:

```
Type error: Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given
```

Am I doing something wrong?

Thanks

**Comment by jasonlewis** [comment]
Where are you setting that handler @michaelstivala?

**Comment by michaelstivala** [comment]
I'm setting it in my App\Exceptions\Handler.php file
