### ISSUE TITLE
api:routes fails to resolve constructor containing Auth::user()->id

### ISSUE THREAD

**Issue by sagaio** [dingo/api#817]
Running `php artisan api:routes`:
```
  [ErrorException]
  Trying to get property of non-object
```
Looking further into the logs I see that it's in the constructor it fails, probably because of Auth, but I'm a rookie so I'm not able to confirm anything.

This is my constructor:

```
    protected $user;

    public function __construct()
    {
        $this->user = Auth::user()->id; // Here it's complaining
    }
```

Am I doing something wrong?

**Comment by lucasmichot** [comment]
@sagaio , It means that no user is logged: so `Auth::user()` is null, so your error. 
Make sure the user is authenticated before, suing a middleware for instance

You can try stg like that
```php
protected $user;

public function __construct()
{
   Auth::loginUsingId(1);
    $this->user = Auth::user()->id;
}
```

**Comment by sagaio** [comment]
@lucasmichot 
Thank you! I should've tested this with the usual route:list command instead of going here directly.
