### ISSUE TITLE
doctrine/dbal and dingo/api

### ISSUE THREAD

**Issue by 0plus1** [dingo/api#818]
Hi,

under lumen I wrote a migration to change a database field, which (as per documentation) requires doctrine/dbal.

As soon as I run the migration I am greeted with:

PHP Fatal error:  Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #1 [ <required> array $format ]] in class Dingo\Api\Exception\Handler' in /***/vendor/illuminate/container/Container.php:828

Does anybody have any idea what's up?

**Comment by jasonlewis** [comment]
I know this is a late reply, but if you're still having this issue can you paste the entire stack trace as well as the migration.

Cheers.
