### ISSUE TITLE
BindingResolutionException: Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Auth\Auth, Dingo\Api\Routing\Router].

### ISSUE THREAD

**Issue by camilstaps** [dingo/api#819]
I'm receiving the following error on every route on a clean Lumen 5.2 install when trying to add basic authentication to my project:

    BindingResolutionException in Container.php line 750:
    Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable while building [Dingo\Api\Auth\Auth, Dingo\Api\Routing\Router].

Here are the relevant parts of some of my files: bootstrap/app.php:

    $app->routeMiddleware(['api.auth' => Dingo\Api\Http\Middleware\Auth::class]);
    $app->register(App\Providers\AppServiceProvider::class);
    $app->register(Dingo\Api\Provider\LumenServiceProvider::class);

AppServiceProvider.php:

    public function boot() {
        $this->app[Auth::class]->extend('basic', function($app) {
            return new \Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
        });
    }

routes.php:

    $api->version('v1', ['middleware' => 'api.auth', 'providers' => ['basic']], function ($api) {
        // ...
    }

This is at b36db17, with the fix from #810.

What am I doing wrong?

**Comment by jasonlewis** [comment]
No official support yet so I have no idea. :smile:

**Comment by camilstaps** [comment]
Sorry, didn't realize it wasn't supported yet. We'll switch back to 5.1 :)

**Comment by isometriq** [comment]
I'm using Lumen 5.1 and I have this problem...

I've the narrowed the problem to happen when I inject a dependency to  `Laravel\Lumen\Routing\UrlGenerator` in one of my controller methods or the constructor.

I wanted to use that dependency like this:
$apiUrl = $this->Url->to('/');

Note that this works:
$apiUrl = app('url')->to('/');

The problem happens on the call to `response()` when sending the response, like so:
return $this->response()->created()->setContent($token);

Hope this helps..

**Comment by isometriq** [comment]
BTW, I have no problem other dependencies, like these:
`Illuminate\Http\Request`
`Dingo\Api\Auth\Auth`
`Tymon\JWTAuth\JWTAuth`

**Comment by camilstaps** [comment]
@isometriq this doesn't seem to be the same issue. Please open a new issue, thanks.

**Comment by tyteen4a03** [comment]
Any update on when 5.2 support will arrive?

**Comment by jasonlewis** [comment]
It's supported.

**Comment by tyteen4a03** [comment]
I'm getting this error when I'm following the instructions on the wiki so I was wondering. I'll get a log soon.

**Comment by jasonlewis** [comment]
Open a new issue mate.

**Comment by tyteen4a03** [comment]
Nevermind, there was something wrong with my `config/app.php`. Thanks for the project!
