### ISSUE TITLE
Reusability of Transform Classes [Nested Transformation with Default Includes]

### ISSUE THREAD

**Issue by Deleugpn** [dingo/api#821]
I don't know if I'm facing this approach correctly, but to me it seems like it should be possible to make only one transform for each model. Is that an incorrect assertion?

So far I've tried:

------------------------------------
- Custom method at Transformer

```
	public function transform(Ticket $ticket) {
		$array = [
			'id' => $ticket->id,
			'title' => $ticket->title,
			'status' => $this->transformerMessage($ticket->status)
		];

		if ($ticket->relationLoaded('user'))
			$array = array_merge($array, $this->user($ticket));
		if ($ticket->relationLoaded('interactions'))
			$array = array_merge($array, $this->interactions($ticket));
		return $array;
	}
```

The problem with this approach is that when transforming the related object, I can't trigger the **$defaultIncludes**, that is, the **interactions** will be loaded with no problem, but the **$defaultIncludes** defined inside InteractionTransformer is not triggered.

```
	protected function interactions(Ticket $ticket) {
		$interactionTransform = new InteractionTransformer();
		$array = array();
		foreach ($ticket->interactions as $interaction) {
			$array[] = $interactionTransform->transform($interaction);
		}
		return ['interactions' => $array];
	}
```

------------------------------------
For the sake of testing, I also tried to manually simulate a parse of includes, also with no luck:

```
	public function index($id = null) {
		$tickets = Ticket::with('interactions', 'user')->get();
		$this->response->transformer->getAdapter()->getFractal()->parseIncludes(array('user'));
		return $this->response->collection($tickets, new TicketTransformer());
	}
```

When executing the above code, the **includeUser** method is not triggered.

```
	public function includeUser(Ticket $ticket) {
		return $this->item($ticket->user, new UserTransformer(), 'user');
	}
```

----------------------------------------------

Anyway, to try and explain a little about my problem, what I want is something like this:

- Call transformer from another transformer (and include the **defaultIncludes** from all of them)
- Respond with an Eager Load object (and include them in the transformation only if they're available)

Is this achievable?

Thanks for your attention.

**Comment by jasonlewis** [comment]
I don't think is related to Dingo. Seems more like a Fractal issue.

As to your first point... no, that's not entirely true. You could have several transformers for a single model depending on the situation. You might want to return different data sets for different endpoints, and it's usually easier/nicer to have separate transformers then a bunch of `if` statements.

You shouldn't really need to manually include transformers from inside your transformers. If you need to nest the data, either define them as default includes, or request them when you fetch the data.

If you want some includes to be included for some endpoints but not others, you can set the default includes at runtime to avoid setting them globally.

```php
return $this->response->collection($tickets, (new TicketTransformer)->setDefaultIncludes(['user', 'interactions']));
```
