### ISSUE TITLE
addMeta on array response not possible

### ISSUE THREAD

**Issue by kaiserlos** [dingo/api#825]
I am using the addMeta function within some middlewares. If I get it right it doesn't work on array() responses.

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function addMeta() on null' in /home/vagrant/www/vendor/dingo/api/src/Http/Response.php:264

I tracked this down and it is because the response addMeta function is trying to call $this->binding->addMeta() but for an array response the binding var is null.

**Comment by jasonlewis** [comment]
Yeah you can only add meta to responses that are sent through a transformer. Something you need to check before attempting to do.

**Comment by catalinux** [comment]
If you do not care about performance, you could have on your middleware

```php
       if ($response instanceof Response) {
            /** @var Response $response */
            $c = json_decode($response->getContent());
            $c->meta->yourKey = [];
            $response->setContent(json_encode($c));
        }
```

where `Response` is `Dingo\Api\Http\Response`

**Comment by kaiserlos** [comment]
Thanks, will try!

**Comment by njbarrett** [comment]
Is there a cleaner way of handling this?
