### ISSUE TITLE
Create / Edit method

### ISSUE THREAD

**Issue by Deleugpn** [dingo/api#829]
According to Laravel docs, when accessing **/resource/create** the **resource.create** method is called in the controller. I believe that Dingo's Routing module is redirecting that to **resource.show** and **/resource/{resource}/edit** is giving a 404 directly.

I don't really care about the **resource.{resource}.edit** because it is already throwing an error, but the create one I have to manually throw an error from my controller.

It would be nice to have some sort of controller provided by the Dingo API that we could extend.

```
class DingoController extends Controller {
	final public function create() {
		throw new NotAcceptableHttpException();
	}

 	final public function edit() {
		throw new NotAcceptableHttpException();
	}
}
```

And have those routes properly working.

**Comment by jasonlewis** [comment]
What do you mean by Dingo redirecting to `resource.show`?

**Comment by jasonlewis** [comment]
Personally I just use the `except` with the `create` and `edit` methods when wiring up the routes.

If there's a push for this I'll add it. Seems simple enough to do yourself though.
