### ISSUE TITLE
Request validation allways passes

### ISSUE THREAD

**Issue by HtmHell** [dingo/api#830]
Controller:
```
public function register(RegisterUserRequest $request)
{
	dd('a');
}
```

And for example the email field is required:
```
public function rules()
{
	return [
		'email' => 'required'
	];
}
```

So I send a request without the email, and still getting the "a" response.

I also tried to extend `Dingo\Api\Http\Request` instead of `App\Http\Request`, but still the same.

**Comment by jasonlewis** [comment]
Your form request class should extend `Dingo\Api\Http\FormRequest`.

**Comment by calvinmuller** [comment]
`class OrderRequest extends \Dingo\Api\Http\FormRequest
{
    public function rules()
    {
        return [
            'items' => 'required',
            'email_address' => 'required|email'
        ];
    }

    public function authorize()
    {
        return false;
    }

}`

However it doesn't seem to be getting executed.

`    public function store(OrderRequest $request)
    {}`

Any ideas as to why it wouldn't be executed?

**Comment by jasonlewis** [comment]
Working fine here on both Laravel 5.1 and 5.2.

Anything else you can provide?
