### ISSUE TITLE
Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable

### ISSUE THREAD

**Issue by isometriq** [dingo/api#831]
I'm using Lumen 5.1 and I have this error...
> BindingResolutionException: Target [Dingo\Api\Contract\Routing\Adapter] is not instantiable

I've the narrowed the problem to happen when I inject a dependency to `Laravel\Lumen\Routing\UrlGenerator` in one of my controller methods or the constructor.

I wanted to use that dependency like this:
`$apiUrl = $this->Url->to('/');`

Note that this works:
`$apiUrl = app('url')->to('/');`

The problem happens on the call to response() when sending the response, like so:
`return $this->response()->created()->setContent($token);`

BTW, I have no problem other dependencies, like these:
`Illuminate\Http\Request`
`Dingo\Api\Auth\Auth`
`Tymon\JWTAuth\JWTAuth`

**Comment by jasonlewis** [comment]
Mind pasting the code that's causing the problem. Cheers.

**Comment by jasonlewis** [comment]
This seems to be an issue with how Lumen has depended upon the `Application` instance in the `UrlGenerator`. You can get around this by simply binding the instance manually.

```php
app()->instance('Laravel\Lumen\Application', app());
```
