### ISSUE TITLE
JWTAuth::attempt throws 405 Method Not Allowed Exception.

### ISSUE THREAD

**Issue by ghost** [dingo/api#833]
jwtauth::attempt throws 405 method not allowed exception. In  "login" route its throws exception and on register it works.

<img width="1220" alt="0p85t7h" src="https://cloud.githubusercontent.com/assets/7253727/12668987/538a3a2a-c697-11e5-82ee-4b61f33d6fd3.png">
<img width="688" alt="j2foetm" src="https://cloud.githubusercontent.com/assets/7253727/12668990/55e29f2e-c697-11e5-8919-41084e986c1d.png">
<img width="848" alt="byzcwri" src="https://cloud.githubusercontent.com/assets/7253727/12668991/5a00df80-c697-11e5-8197-9afc6807963f.png">

**Comment by jasonlewis** [comment]
Can you paste the exception please?

Is the method throwing the exception or is the `login` route just never being fired?

Also, from looking at the screenshots, you shouldn't be using `Response::json` anywhere in a Dingo API route.
