### ISSUE TITLE
Lumen 5.2 Support route NotFoundHttpException 

### ISSUE THREAD

**Issue by geocine** [dingo/api#834]
Am I doing anything wrong or missing something? 

I am accessing this via : `php -S localhost:8000 -t public` at `localhost:8000/api/hello`

with configurations:

```
API_STANDARDS_TREE=vnd
API_SUBTYPE=core
API_DOMAIN=api.site.com
API_VERSION=v1
API_NAME="Core API"
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true
```

**routes.php**
```
$api = $app['api.router'];

$api->version('v1',['prefix' => 'api'],function($api){
    $api->get('hello',function(){
       return "hello";
    });
});
```
**bootstrap/app.php**
`
$app->register(Dingo\Api\Provider\LumenServiceProvider::class)
`

**Error:**
```
NotFoundHttpException in RoutesRequests.php line 438:
in RoutesRequests.php line 438
at Application->handleDispatcherResponse(array('0')) in RoutesRequests.php line 377
at Application->Laravel\Lumen\Concerns\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request)) in Request.php line 95
at Request->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Request), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in RoutesRequests.php line 617
at Application->sendThroughPipeline(array('Dingo\Api\Http\Middleware\Request'), object(Closure)) in RoutesRequests.php line 378
at Application->dispatch(null) in RoutesRequests.php line 323
at Application->run() in index.php line 28
```

**Comment by lucasmichot** [comment]
@geocine try
* `$app->register(\Dingo\Api\Provider\LumenServiceProvider::class);` with a backslash before `Dingo` 
* `API_DOMAIN=localhost`

**Comment by geocine** [comment]
@lucasmichot Many thanks! it was the `API_DOMAIN` that was causing the issue.

**Comment by lucasmichot** [comment]
You're welcome!

**Comment by enginkartal** [comment]
I'm getting the same error.I tried to your suggestions but didn't work for me.

**The error is**:
`{"message":"404 Not Found","status_code":404,"debug":{"line":443,"file":"C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(381): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#1 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(629): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#2 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#3 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#4 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Routing\\Router.php(574): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#5 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(123): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#6 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#7 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(150): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#8 C:\\wamp\\www\\works\\yp-api\\vendor\\palanik\\lumen-cors\\LumenCors.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 [internal function]: palanik\\lumen\\Middleware\\LumenCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#10 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#11 C:\\wamp\\www\\works\\yp-api\\vendor\\lucadegasperi\\oauth2-server-laravel\\src\\Middleware\\OAuthExceptionHandlerMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 [internal function]: LucaDegasperi\\OAuth2Server\\Middleware\\OAuthExceptionHandlerMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#14 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#15 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#16 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(124): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#17 C:\\wamp\\www\\works\\yp-api\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(100): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#18 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#19 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(136): call_user_func_array(Array, Array)","#20 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#21 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Routing\\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#22 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#23 C:\\wamp\\www\\works\\yp-api\\vendor\\illuminate\\pipeline\\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#24 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(626): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#25 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#26 C:\\wamp\\www\\works\\yp-api\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(327): Laravel\\Lumen\\Application->dispatch(NULL)","#27 C:\\wamp\\www\\works\\yp-api\\public\\index.php(28): Laravel\\Lumen\\Application->run()","#28 {main}"]}}`

**Comment by duniadua** [comment]
You save my life today, after looking for 4hours for solution..
i have public IP without domain, in my .env still localhost, after i change to IP, the program run now
many thanks

**Comment by LittleHans8** [comment]
Thanks.
