### ISSUE TITLE
How to set up code: in errorFormat

### ISSUE THREAD

**Issue by swansun95** [dingo/api#835]
Hi

in config/api.php, there is a setting key "errorFormat", default is 
`'errorFormat' => [
        'message' => ':message',
        'errors' => ':errors',
        'code' => ':code',
        'status_code' => ':status_code',
        'debug' => ':debug',
    ],`

after i tried to use dingo's response->error() and other methods , looks like only I can setup the "status_code" and "message", is there any way/method to set the code in error response? like 
{
    "code" => 1001,
   "message" => "error message",
   "status_code" => 403
}

thanks?

**Comment by jasonlewis** [comment]
`:code` is a standard replacement so it should work out of the box, assuming your exception has a code associated with it. If it does not have a code then it won't be included.

The `$response->error()` method (and related methods) don't implement the adding of the code. So you'd need to throw the exception yourself.

```php
throw new HttpException(404, 'User not found.', null, [], 5);
```

That should include a `"code": 5` in the error response.

**Comment by swansun95** [comment]
thanks
