### ISSUE TITLE
Getting error in Auth.php during authentication

### ISSUE THREAD

**Issue by michaeltansy** [dingo/api#837]
Hi I got this error

`{"message":"Call to undefined method Closure::authenticate()","code":1,"status_code":500,"debug":{"line":82,"file":"C:\\xampp\\htdocs\\library-api\\vendor\\dingo\\api\\src\\Auth\\Auth.php","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":["#0 {main}"]}}`

how do I resolve this? in line 82, $providers->authenticate method is not found.

**Comment by jasonlewis** [comment]
Just open one issue. :smile:

**Comment by AaronWB** [comment]
how did you solve it
