### ISSUE TITLE
Cant get Basic Auth to work.

### ISSUE THREAD

**Issue by michaeltansy** [dingo/api#839]
Hi I am facing the issue while attempting to access by using api.auth middleware. here's the error

{"message":"Call to undefined method Closure::authenticate()","code":1,"status_code":500,"debug":{"line":82,"file":"C:\\xampp\\htdocs\\library-api\\vendor\\dingo\\api\\src\\Auth\\Auth.php","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":["#0 {main}"]}}

Could you please help me to solve this?

**Comment by JDqv** [comment]
Same here!

**Comment by JDqv** [comment]
Remove from api config  auth array contents if you have them, or just remove whole api config file and run
`php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"`
to create new one. Add your prefix back and version.

Then place this code from wiki in boot method
```
// App\Providers\AppServiceProvider.php
public function boot()
    {
        app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
            return new \Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
        });
    }
```

my guess is that you have a closure in config file somewhere that's why you are getting this error.
like: 
```
'auth' => [
     'basic' => function ($app) {
          return new Dingo\Api\Auth\Provider\Basic($app['auth']);
     }
],
```
you cant do that anymore

**Comment by michaeltansy** [comment]
after executing php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider" , i got this error :

[Symfony\Component\Debug\Exception\FatalErrorException]                      
  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening requi  
  red '' (include_path='C:\xampp\htdocs\library-api\vendor/phpseclib/phpsecli  
  b/phpseclib;.;C:\xampp\php\PEAR')  

do you know how to fix that?

**Comment by michaeltansy** [comment]
@jasonlewis could you please help me out here?

**Comment by jlien-calwater** [comment]
@michaeltansy looks like you might have issue with the existing composer file. You can create the api.php file manually in your config by creating this file here: https://github.com/dingo/api/blob/master/config/api.php

Minimally, you need to set the API_PREFIX in your .env, e.g., API_PREFIX=api

**Comment by jasonlewis** [comment]
Is there an issue here still?
