### ISSUE TITLE
Cannot get at JWT Custom Claims

### ISSUE THREAD

**Issue by bbrink68** [dingo/api#840]
I was curious if I was missing a way, using Dingo - to get at the underlying JWT Auth.  Specifically I am trying to access a custom JWT claim that is set on authentication.  

Using the Dingo Helper class on my Controller, I want to use something like:

```
    $this->auth->getProviderUsed()->auth->getPayload()
```

But because the `auth` member has protected access in `Auth.php`, it will not let me.  Flipping this over to public obviously reveals the payload i am after, but is there some way that I'm not seeing to access this payload data via Dingo without changing core files?

**Comment by catalinux** [comment]
One way:

```php

/** @var Payload $payload */
$token = JWTAuth::getToken();
$payload = JWTAuth::getPayload($token);
$claims = $payload->getClaims();

**Comment by bbrink68** [comment]
Doh! I didn't even think to access JWTAuth directly :/  This works and totally solves my issue, closing this!
