### ISSUE TITLE
Any plans for for supporting the JSend response format?

### ISSUE THREAD

**Issue by Mahmoudz** [dingo/api#841]
I would like to have my response formated like this:
```json
{
    status : "success",
    data : {
        "posts" : [
            { "id" : 1, "title" : "A blog post", "body" : "Some useful content" },
            { "id" : 2, "title" : "Another blog post", "body" : "More content" },
        ]
     }
}
```
Reference: https://labs.omniti.com/labs/jsend
I've checked the issue #125 but seems not supported yet!

**Comment by jasonlewis** [comment]
Is this something that can be done through Fractal/custom transformation layer?
