### ISSUE TITLE
How to integrate Doctrine 2?

### ISSUE THREAD

**Issue by morfin** [dingo/api#842]
Does anybody know if it's possible to use Doctrine collections with Dingo responses and transformers?

I haven't been abled to google information related to Dingo + Doctrine.

Apparently Dingo only deals with \Illuminate\Support\Collection

I will appreciate if somebody points me to the right direction. Any article, tutorial, video related to this topic will be gladly welcome. 

Thanks.

**Comment by jasonlewis** [comment]
I've not done it, but it shouldn't really matter what you want to return. You're either going to return an array, or an object that can be identified for a transformer to convert that into an array.
