### ISSUE TITLE
how to custom AccessDeniedException

### ISSUE THREAD

**Issue by swansun95** [dingo/api#843]
In some login-required APIs, If the user is not login, current API will shows an error
```
{
  "message": "The resource owner or authorization server denied the request.",
  "status_code": 401
}
```

but,  I want to show a custom error instead, like 
```
{
    "message": " Please login first",
    "status_code": 200
}
```

I tried to use try..catch... in controller, but it's not working. here are some codes of my controller,

```
public function __construct(Authorizer $authorizer)
    {
        // Only apply to a subset of methods.
        $this->middleware('api.auth', 
            ['only' => [
                'test2'
                ]]
            );
        
        $this->authorizer = $authorizer;
    }
```

```
public function test2(){
        try {
            $user_id = $this->authorizer->getResourceOwnerId(); 
        }catch (\League\OAuth2\Server\Exception\AccessDeniedException $e) {
            return $this->response->error('please login first', 200);
        }
```

but the try..catch.. seems not working in controller function. 

where can i catch such exception and custom my error info?

thanks

**Comment by catalinux** [comment]
1. First you have to find who throws that exception "The resource owner or authorization server denied the request". It might be in middleware
2. Catch that exception and handle according to your requirements

**Comment by swansun95** [comment]
it is in the Laravel-Oauth2-Server, League\OAuth2\Server\Exception\AccessDeniedException Class to throw the exception.

```
class AccessDeniedException extends OAuthException
{
    /**
     * {@inheritdoc}
     */
    public $httpStatusCode = 401;

    /**
     * {@inheritdoc}
     */
    public $errorType = 'access_denied';

    /**
     * {@inheritdoc}
     */
    public function __construct()
    {
        parent::__construct('The resource owner or authorization server denied the request.');
    }
}
```

do i need to hack that class manually?

thanks

**Comment by swansun95** [comment]
i just took a look at the middleware of laravel-oauth2-server,  the \LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware throws such 401 error if the access_token validation failed.

and base on the instruction of dingo-api, https://github.com/dingo/api/wiki/Authentication,
i have a service provider to extend the "oauth" middleware.


```
class OAuthServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->app[Auth::class]->extend('oauth', function ($app) {

            $provider = new OAuth2($app['oauth2-server.authorizer']->getChecker());

            $provider->setUserResolver(function ($id) {
```


so, what should i do to custom such error?

thanks

**Comment by jasonlewis** [comment]
The exceptions that are thrown by the League's OAuth 2.0 package all extend from the base `OAuthException` class. This exception is [caught and handled](https://github.com/dingo/api/blob/master/src/Auth/Provider/OAuth2.php#L92) by the OAuth 2.0 provider of this package and rethrown as an `UnauthorizedHttpException`.

You can register a handler for the `UnauthorizedHttpException` and return your own custom response. However, you should make sure the response status code is 401 and not 200 like in your original example. I suggest throwing a new `UnauthorizedHttpException` with a different message.

```php
app('api.exception')->register(function (Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException $exception) {
    throw new Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException('Bearer', 'Please login.', $exception);
});
```
