### ISSUE TITLE
Internal Requests - InternalHttpException in Dispatcher.php line 525

### ISSUE THREAD

**Issue by datune** [dingo/api#845]
When running a request internally, passing invalid data on purpose like so: 

```php
        $dispatcher = app('Dingo\Api\Dispatcher');

        try {
            $response = $dispatcher->with(
                [
                    'title'        => '-->AssumeThisIsInvalid<--',
                    'description'  => '',
                    'lang_code'    => 'en'
                ])->post('book');
        }
        catch (Exception $e)
        {
            debug($e);
        }
```

I get the following error message:
```
InternalHttpException in Dispatcher.php line 525
```
Using Postman making the exact same request everything works as expected. The method being called (store()) uses a FormRequest. If I remove the FormRequest, create and run the validator within the store() method, everything works as expected. 

So, the following does NOT work when called internally:
```php
    public function store(StoreBookRequest $request)
    {
        return $request->get('title');
    } 
```
The following does work, whether called internally or not:
```php
    public function store(\Illuminate\Http\Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title'         => 'required|string|max:8',
            'description'   => 'string',
            'lang_code'     => 'required|max:2'
        ]);

        if ($validator->fails()) {
            debug($validator->errors());
        }

        return $request->get('title');
    }
```

I can't be the only one who stumbled upon this issue?

**Comment by bkintanar** [comment]
I can reproduce the above error.

```
Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in api/vendor/dingo/api/src/Dispatcher.php on line 525 and defined
```

**Comment by jasonlewis** [comment]
Are you using the `Dingo\Api\Http\FormRequest` class? This throws an `HttpException` that can be handled properly by Dingo.

**Comment by datune** [comment]
Yes I am using Dingo\Api\Http\FormRequest class, and I still get the same error.

**Comment by datune** [comment]
After updating to the latest dingo build, I now get a different error: ValidationHttpException in FormRequest.php line 22:
