### ISSUE TITLE
API Blueprint not taking response headers in account

### ISSUE THREAD

**Issue by kutagh** [dingo/api#846]
Just to ensure visibility and making the error known here: Currently, when using the annotations in your controllers for generating API Blueprint sources, using a response annotation never includes your headers. For example:

```
@Get("/")
@Version({"v1"})
@Request(headers={"Authorization": "Bearer <token>"})
@Response(201, headers={"Authorization": "Bearer <new generated token>"})
```

Returns an endpoint ```[GET /]``` with request headers 
```
Content-Type: application/json
Authorization: Bearer <token>
```
and response headers
```
Content-Type: application/json
``` 

It is a simple issue to fix, as dingo/blueprint was simply trying to use the wrong variable to print the headers. As such, I've submitted a pull request at https://github.com/dingo/blueprint/pull/25 and dingo/api might need to update the dependency to account for it. In the meantime, users can apply the patch themselves or check out my fork of dingo/blueprint.

**Comment by jasonlewis** [comment]
Will be moving onto Blueprint related things shortly, once I resolve the outstanding issues here. Thanks for the patience. :+1:
