### ISSUE TITLE
Support for Laravel 4.2

### ISSUE THREAD

**Issue by bradsapp** [dingo/api#847]
Is there any support and/or documentation for Laravel 4.2?

**Comment by kutagh** [comment]
Quoting [the installation instructions from the wiki](https://github.com/dingo/api/wiki/Installation):
> To install this package you will need:
* Laravel 5.1+ or Lumen 5.1+
* PHP 5.5.9+

Based on that, I would assume there is no support (otherwise it probably would have been mentioned somewhere).

**Comment by bradsapp** [comment]
Thanks kutagh, I read that as well but was hoping this had been around enough that it would support an older version of Laravel.

**Comment by ganey** [comment]
@bradsapp you can use version 0.8.2, anything higher seems to have issues. I was hoping this would have been mentioned somewhere like here: https://github.com/dingo/api/wiki/Package-Incompatibilities

I was having a similar issue with a project started last year which is now stuck on Laravel 4.2

**Comment by Stanislav-U** [comment]
hi @ganey, I also have a project which uses laravel 4.2. How did you make dingo work except for just using version 0.8.2? I tried it also but can't seem to make it work.

**Comment by ganey** [comment]
@Stanislav-U The code was eventually migrated on to Laravel 5.

I think it just stayed with 0.8.2 and all Controllers just used the ControllerTrait



    use Illuminate\Routing\Controller;
    use Dingo\Api\Routing\ControllerTrait;

    class AddressController extends Controller {

      use ControllerTrait;

      protected static $relations = ['location'];

      /**
       * Display a listing of the resource.
       *
       * @return Response
       */
      public function index()
      {
          return Address::with(static::$relations)->get();
      }

    }

Then had the auth & response formats setup in app/config/packages/dingo/api/config.php with the LeagueOauthProvider for the auth.

**league/oauth2-server:4.0.2**

```

  /*--------------------------------------------------------------------------
  | Response Formats
  |--------------------------------------------------------------------------
  |
  | Responses can be returned in multiple formats by registering different
  | response formatters. You can also customize an existing response
  | formatter.
  |
  */

  'default_format'      => 'json',
  'formats'             => [

    'json' => 'Dingo\Api\Http\ResponseFormat\JsonResponseFormat',

  ]

```


Sorry I can't remember much more, and best of luck getting it working!
