### ISSUE TITLE
Internal Request Dingo\Api\Exception\InternalHttpException when api returns a json

### ISSUE THREAD

**Issue by j1yaktech** [dingo/api#849]
> ErrorException in InternalHttpException.php line 22:
> Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in C:\xampp\htdocs\test\vendor\dingo\api\src\Dispatcher.php on line 525 and defined
> 

Example route:

```
Route::get('/home', 'HomeController@index');
$api->version('v1', function ($api) {
	 $api->get('test', function(){
        return response()->json(['message' => 'Bad request, please verify your request route', 'status_code' => 400],400);   
    });
});
```
Example HomeController:

```
      public function index()
    {
        $dispatcher = app('Dingo\Api\Dispatcher');
        return $dispatcher->get('test');
    }

```
When visit api.localhost.com/home i receive InternalHttpException. why?? is not possible return the original json?

when i use a route in dispatcher that returns a class works ok, but in my api, a lot of end points returns a json.

anybody can explain how works dispatcher??

a lot of thanks

Laravel 5.2

**Comment by jlien-calwater** [comment]
@j1yaktech I don't think you can put a response in route closure any more.

You need to dispatch to the correct route. Try this:

```php
return $dispatcher->get('api/test');

// or double check your route using this command
php artisan api:routes
```

**Comment by jenky** [comment]
The dispatcher will throw InternalHttpException if the response status code is not successful (>= 200 && < 300). I think this is kinda wrong and it make it hard to work with REST API.

**Comment by j1yaktech** [comment]
catch (Dingo\Api\Exception\InternalHttpException $e) dont work

**Comment by jenky** [comment]
I think the only to do it ATM is replace the dispatcher with or own.

**Comment by ivankurn** [comment]
@jenky Could you specify how to do it?

**Comment by jenky** [comment]
@ivankurn Create your own dispatcher that extends to original class and overwrite the `dispatch` method. Then overwrite the dispatcher in the container by registering it on your provider, make sure your provider has been loaded after `dingo/api`'s provider.

**Comment by jasonlewis** [comment]
You do not need to return `response()->json`. I know that's what Laravel says, but the API handles the formatting of the response and it causes some trouble. I could allow it, but it's just easier to not use the `response()->json` method when returning your responses.

Just return whatever it is, how it is. If it's an error, try throwing a `HttpException` instead of building a response. If you need custom headers, simply return a new `Response` instance and adjust the status code/headers how you wish. Avoid using `Response::json`.

**Comment by jasonlewis** [comment]
Oh and the `InternalHttpException` is for when an error response is returned for an internal request. It's so everything is normalized and is meant to make things easier. You can catch this exception in your controller (or route closure) and then act on it.

```php
try {
    app('api.dispatcher')->post('users', ['name' => 'foo', 'password' => 'bar']);
} catch (Dingo\Api\Exception\InternalHttpException $e) {
    $response = $e->getResponse();

    // you can now do whatever you want with the response, check it's content, status code, etc.
}
```
