### ISSUE TITLE
Using OAuth2 Middleware with Laravel Sessions

### ISSUE THREAD

**Issue by lvandyk** [dingo/api#852]
I have a route group using api.auth middleware working nicely with OAuth2. How do I add the 'auth' middleware so that if the user is actually logged in and has a session, they can also reach that route and thus the $this->auth->user() is populated?

E.g. User accesses route via mobile app using token vs user accessing route via browser when logged in (javascript ajax call).

**Comment by jlien-calwater** [comment]
@lvandyk a bit confused here, but to answer your question. You can check if the user is authenticated as you have stated. Refer: https://github.com/dingo/api/wiki/Authentication#retrieving-authenticated-user

**Comment by lvandyk** [comment]
Hi jlien,

This is the controller function:
``` 
public function test() {
    echo $this->auth->user();
}
```

This is the route:
```
$api->version('v1', ['prefix' => 'v1', 'protected' => true, 'middleware' => 'api.auth'], function ($api) {
    $api->get('test', 'App\Http\Controllers\TestController@test');
});
```
This works perfectly with OAuth2 Authorization Header but as soon as I want to also call that route from a logged in user from a normal web login, I try update the middle to have auth as well: 'middleware' => ['api.auth', 'auth']

This does not work as the api.auth either rejects the response before it can even try the other middleware as there is not OAuth2 Authorization headers.

So what Im doing now is this:

```
$api->version('v1', ['prefix' => 'v1', 'protected' => true, 'middleware' => 'api.auth'], function ($api) {
    $api->get('test', 'App\Http\Controllers\TestController@test');
});

$api->version('v1', ['prefix' => 'v1', 'protected' => true, 'middleware' => 'auth'], function ($api) {
    $api->get('test', 'App\Http\Controllers\TestController@test');
});
```

**Comment by jlien-calwater** [comment]
I see the issue.

Don't use $api if you are using Laravel Auth, instead use the usual route.

```php
\\ when using App\User
Route::group(['middleware' => ['web']], function () {  // Laravel 5.2
  Route::get('test', 'TestController@test');
});

\\ when using Oauth
$api->version('v1', ['prefix' => 'v1', 'protected' => true, 'middleware' => 'api.auth'], function ($api) {
    $api->get('test', 'App\Http\Controllers\TestController@test');
});
```

**Comment by zouxycn** [comment]
@lvandyk  I have encountered same situation while using contoller for both web and mobile app.
Do you have better solution for this now?

**Comment by jasonlewis** [comment]
You shouldn't be trying to merge the two authentication mechanisms like that. An API route isn't meant to be viewed through a "web app". Your web app may consume your API. Basically, your regular routes should not point to an API route. That's not how it works.

If you need to hit the API route from your web app route for whatever reason, you might consider firing off an internal request.

So, from your web app:

```php
Route::get('example', ['middleware' => ['web'], function () {
  $user = app('api.dispatcher')->as(Auth::user())->get('user'); 
}]);
```

The `as` method will authenticate you with the API which will allow you to use `$this->auth->user()` in your API controllers still. All subsequent internal requests will then be authenticated as that user.

You can use `as(Auth::user())->once()` to only authenticate for that request only.

**Comment by jlien-calwater** [comment]
@jasonlewis thanks for the heads up!

**Comment by lvandyk** [comment]
Hi Jason, the `as` method is exactly what I need. Thanks!

**Comment by jasonlewis** [comment]
@lvandyk, sorry, that was meant to be `be`, not `as`. :stuck_out_tongue:

**Comment by lvandyk** [comment]
Haha no problem thanks!

**Comment by eleftrik** [comment]
Thank you @jasonlewis, your comments answer to my question: "Can I use Dingo API for Ajax requests, returning JSON, from the browser, checking if user is already authenticated through Laravel Session?" and the answer is "no.", if I'm not wrong. It's a pity, because this package offers everything I'm looking for.
