### ISSUE TITLE
Add support for \Illuminate\Auth\Access\AuthorizationException and such.

### ISSUE THREAD

**Issue by naerymdan** [dingo/api#853]
When using the authorization mechanics from Laravel, a failed Policy check will throw a "\Illuminate\Auth\Access\AuthorizationException" which goes through Dingo and becomes a 500 error instead of a 403.

Ref: https://laravel.com/docs/5.2/authorization#controller-authorization

**Comment by dominikveils** [comment]
Its also require "Illuminate\Http\Exception\HttpResponseException".

It thrown when using FormRequest validation, and Digno does not handle it.

**Comment by jasonlewis** [comment]
Is it worth adding a default handler for the `AuthorizationException` and simply rethrowing an `AccessDeniedException`? You can do it manually like so...

```php
$this->app['api.exception']->register(function (AuthorizationException $exception) {
    throw new AccessDeniedHttpException($exception->getMessage(), $exception);
});
```

@dominikveils, Dingo has its own [`FormRequest`](https://github.com/dingo/api/blob/master/src/Http/FormRequest.php) class you can extend which throws exceptions that can be handled properly.

Or just use a handler like above.
