### ISSUE TITLE
Error serving download 

### ISSUE THREAD

**Issue by ajoslin103** [dingo/api#856]
I am using Laravel 4 & dingo 0.8.3 trying to serve a dynamically created export file as a download in response to a protected route and am getting an error from inside dingo

I know that L4 is out of date, but this project was started over a year ago and is < 2 months away from delivery

Is there any workaround that I can use to get this done?

The file contains dynamically created json 

(in routes.php)

    Route::group([ 'protected' => true ], function(){
        Route::resource('bundle', 'Bundle');
        Route::get('bundle/download/{id}', 'Bundle@download');

(in Bundle.php)

		$contents = $this->createBookletExport($id);
		$nameForFile = $contents->exportName .'.intbnd';
		$pathToFile = "/tmp/".$nameForFile;
		File::put( $pathToFile, json_encode($contents) );
		return Response::download($pathToFile,$nameForFile);

(in laravel.log)

[2016-02-21 13:57:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException'  with message 'Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::getFormatter()' in [...]/vendor/dingo/api/src/Routing/Router.php:220

(from dingo/composer.json)

    "require-dev": {
        "tymon/jwt-auth": "0.4.*",
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.8-dev"
        }
    }

**Comment by ajoslin103** [comment]
I saw a reference somewhere to using an "annotation" to force the use of a Illuminate class rather than the Symphony class.  Does that make sense?  How would I go about doing that?

**Comment by jasonlewis** [comment]
Yeah serving downloads was sketchy back then (it's better now). You might need to make some changes to the Dingo Router if you really want to get by this. It shouldn't be too much of an issue because if you do end up upgrading to Laravel 5.1/5.2 then the issue would be resolved anyway.

Above [Router.php:236](https://github.com/dingo/api/blob/v0.8.2/src/Routing/Router.php#L236) I'd throw in an `if` statement and check the `instanceof` the `$response`. Just check if it's an instance of `Symfony\Component\HttpFoundation\BinaryFileResponse`. If it is just return the response directly without hitting the formatting/morphing.

Let me know how you get on with it.

**Comment by ajoslin103** [comment]
thanks, I really appreciate the tip !

I only get time to work on this project over the weekends — I’ll let you know how I make out

al;

**Comment by ajoslin103** [comment]
No change,

but I think I must have to state somewhere that it’s going to be a BinaryResponse ?

al;

**Comment by ajoslin103** [comment]
I have fixed this -- the answer was NOT to use the Response::download but to use Response::make and add some headers (which I had tried with download)

So this: 

```
    $contents = $this->createBookletExport($id);
    $nameForFile = $contents->exportName .'.intbnd';
    $pathToFile = "/tmp/".$nameForFile;
    File::put( $pathToFile, json_encode($contents) );
    return Response::download($pathToFile,$nameForFile);

```
Became this:

```
    $contents = $this->createBookletExport($id);
    $nameForFile = $contents->exportName .'.intbnd';
    $headers = array('Content-Type' => 'application/octet-stream', 'Content-Disposition' => 'attachment; filename='.$nameForFile);
    return Response::make(json_encode($contents),200,$headers);

```
and Dingo! Bob's yer Uncle !!

:)
