### ISSUE TITLE
Automatically create /relationships/{relatedItem} route

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#857]
Hey,

so to follow the json api specs a route call to `/relationships/{relatedItem}` should return one of 4 very simple results: http://jsonapi.org/format/#fetching-relationships

As every resource with relationships should have that and it is exactly the same for all of them, I think it would be a very good candidate for automation.

Maybe one could set a config option and if it is set to true, those routes & results could be automatically created?

**Comment by jasonlewis** [comment]
I'm not sure it would be that simple...

Plus I don't want to build in too much automation when it comes to routes.

**Comment by lukasoppermann** [comment]
Hmm, I guess since you would need to allow push to those routes as well, it makes sense, I was not thinking of this.
