### ISSUE TITLE
[Question] Timestamp getting formatted

### ISSUE THREAD

**Issue by tomc3** [dingo/api#859]
When i'm using dingo api, somehow timestamp are transformed to something like this in the output.
```json
"updated_at": {
  "date": "2016-02-24 12:46:09.000000",
  "timezone_type": 3,
  "timezone": "UTC"
},
"created_at": {
  "date": "2016-02-24 12:46:09.000000",
  "timezone_type": 3,
  "timezone": "UTC"
}
```

* Is there any way prevent this, and display default value like `created_at: "2016-02-24 12:46:09.000000"` ?
* Also it only happens to `created_at` and `updated_at` timestamps, and nothing happens to those defined in the models.

```php
    public $timestamps = ['d̶o̶n̶e̶_̶a̶t̶', 'a̶p̶p̶r̶o̶v̶e̶d̶_̶a̶t̶', 'created_at', 'updated_at'];
```

**Comment by eduacostam** [comment]
@tomc3 depends on what you want to show.
This is because the Carbon object when casted to JSON returns that representation.

You have multiple ways of solving this:
```
(string) $model->created_at, // or
$model->created_at->toDateTimeString(), // or
$model->created_at->getTimestamp() // to show a UNIX timestamp
```

Hope this helps!

**Comment by tomc3** [comment]
@eduacostam I didn't realize this can be done. This work perfectly well.

Kind Regards,
Tom.
