### ISSUE TITLE
make Login, Register

### ISSUE THREAD

**Issue by michaeltansy** [dingo/api#860]
Can someone please give me an example of creating login and register using basic authentication in Dingo/Api?

**Comment by jasonlewis** [comment]
Basic authentication is relatively straight forward. Registration should be very similar to how you would normally do it. You just need to register the user in your database and return a `201 Created` response.

Example is using a controller implementing the `Helpers` trait.

```php
public function create()
{
    App\User::create(app('request')->input());

    return $this->created();
}
```

For authenticating a request with Basic you'll need to configure the provider.

```php
app('Dingo\Api\Auth\Auth')->extend('basic', function ($app) {
   return new Dingo\Api\Auth\Provider\Basic($app['auth'], 'email');
});
```

You'll then need to make sure you have the `api.auth` middleware on routes that you want to protect.

```php
app('Dingo\Api\Routing\Router')->version('v1', ['middleware' => 'api.auth'], function ($api) {
    $api->get('protected', function () { });
});
```

All routes in the above group would be protected. You would not put your registration route in this group.

Then it's just a matter of using `base64_encode` on your `username:password` string and sending it along as the value to your `Authorization` header.

An example header might look like this:

```
Authorization: Basic dXNlcm5hbWU6aHVudGVyMg==
```

Note that you need the `Basic` prefix for it to work.

Hopefully that should get you started and on the right track.

**Comment by michaeltansy** [comment]
Hi what if I make a route like this /login. I need to return a generated token after checking the credentials right? I was trying to do a login thing and it will return a token and attached it to http header. but that didnt work the way i want to. I barely understand the flow of how do we get that Authorization. but what i am trying to do is we must login first and get the token. how do i suppose to do it using dingo api @jasonlewis ?

**Comment by michaeltansy** [comment]
i already configured the authentication in my provider. and what i am going to do basically is to create a route something like this : 
$api->post('/login' , 'AuthenticateController@login');

what i am about to do is getting the credentials via post method. After getting username:password. We need to attempt the authentication right? and Which function do I have to use in order to attempt the authentication and get a token as a return?

**Comment by jasonlewis** [comment]
You don't need a login route.

Each request to your API needs to be properly authenticated. It's not a one-time login then visit the secure pages type of situation.

To authenticate each request you use the `api.auth` middleware on the endpoints you want protected. Then, once you've enabled the basic authentication provider, you just need to provide your encoded username and password to authenticate yourself.

If you want to use a token to authenticate then you don't want basic authentication. You want either JWT or OAuth. JWT is easier to implement, and if you want to use it, take a look at the [JWT Auth page](https://github.com/tymondesigns/jwt-auth).

**Comment by michaeltansy** [comment]
So is okay if my login code is like this?

if(\Auth::attempt(['email' => $email, 'password' => $password])){
                $credentials = $email . ':' . $password;
                $token = base64_encode($credentials);

                return \Response::json('Basic '.$token, 200)->header('Authorization', 'Basic ' .$token);
            }

I use Auth::attempt from what Laravel have only to check whether the user exist or not. and if the User exists, the system will generate the encoded credentials. @jasonlewis
