### ISSUE TITLE
Can $dispatcher->with(['name' => 'Jason', 'location' => 'Australia'])->get('users');?

### ISSUE THREAD

**Issue by yaoshanliang** [dingo/api#861]
`$dispatcher->with(['name' => 'Jason', 'location' => 'Australia'])->post('users');`is OK;

Now, I just want to get with data, like `$dispatcher->with(['name' => 'Jason', 'location' => 'Australia'])->get('users');`

**Comment by prapats** [comment]
you just have to create another GET endpoint for that.

`GET /api/users`

**Comment by jasonlewis** [comment]
As @prapats has said, just create a new route endpoint, should be good.
