### ISSUE TITLE
Transformer Factory getBinding() made public?

### ISSUE THREAD

**Issue by benswinburne** [dingo/api#862]
I have registered bindings for Model -> Transformers which is obviously a neat key value array of which transformers to use with which model.

However, methods `collection()` and `item()` in  `Dingo\Api\Http\Response\Factory` (via the `Dingo\Api\Routing\Helpers` trait) have prototypes such as 

    public function collection(Collection $collection, $transformer, array $parameters = [], Closure $after = null)

with suggested usage

    return $this->collection($users, new UserTransformer);

But given I have a neat mapping of models to transformers surely it'd be nice if

1. potentially the method could determine the transformer if `$transformer` is omitted
2. potentially we could do something like 

        return $this->collection($users, app('api.transformer')->getBinding($users));

   The downside of 2. is such that `Dingo\Api\Transformer\Factory->getBinding()` is protected and therefore can't be used this way.

Is there a more sensible way of achieving this or could we make `getBinding()` public?

**Comment by jasonlewis** [comment]
If you've registered the bindings with the transformer factory then you can just go right ahead and return the collections instead of using the `$this->collection` method (same with singular items).

It'll get matched with its binding automatically so you don't need to worry about it.

If you need more control over the response then just new up a response instance.

```php
public function index()
{
    return new Dingo\Api\Http\Response(App\User::all(), 201);
}
```

Don't ask me why you'd return a `201 Created` in this instance but it's just an example. If I had the following binding:

```php
app('api.transformer')->register(App\User::class, UserTransformer::class);
```

Then it would automatically be applied to the response.

**Comment by benswinburne** [comment]
Ok, that makes sense, but can you suggest how I might apply the same logic to automatically eager loaded included resources?

Take the following abridged part of a Fractal transformer, extending `Fractal\TransformerAbstract`

    /**
     * Include Applications
     *
     * @return League\Fractal\CollectionResource
     */
    public function includeApplications(User $user)
    {
        $applications = $user->applications;

        return $this->collection($applications, new ApplicationTransformer, 'applications');
    }

Having registered the following binding

    app('api.transformer')->register(App\Application::class, ApplicationTransformer::class, ['key' => 'applications']);

In theory I should be able to 

    return $this->collection($applications);

Or at least get the binding back from the `app('api.transformer')` to do this for me.
