### ISSUE TITLE
Tried to access session data without an active access token

### ISSUE THREAD

**Issue by yaoshanliang** [dingo/api#863]
When I run `php artisan api:routes`， it shows me 

```                                                                        
  [LucaDegasperi\OAuth2Server\Exceptions\NoActiveAccessTokenException]  
  Tried to access session data without an active access token
```

**Comment by jasonlewis** [comment]
What do your routes look like?

Obviously you're running OAuth 2.0., is there any other information you can provide?

**Comment by yaoshanliang** [comment]
Yes, I'm running OAuth 2.0.

When i remove the oauth middleware, it also throw the exception; Maybe access the user info from access_token in my code;

**Comment by jasonlewis** [comment]
The routes command shouldn't need to access the routes, it just reads the available routes.

Are you using controllers by any chance? Doing anything regarding sessions/tokens in a constructor?

**Comment by yaoshanliang** [comment]
My route is like: `Route::controller('user', 'UserController');`...`$api->get('user/info', 'UserController@getUserInfo');`

**Comment by jasonlewis** [comment]
What does the controller look like?

**Comment by yaoshanliang** [comment]
No constructor, some controllers need to access session;

**Comment by jasonlewis** [comment]
So where is this "accessing of the session" taking place? I need to see some more code. I've got no clue as to what is happening because I've got nothing to go on.

**Comment by yaoshanliang** [comment]
For example, in my controller, `$user = Session::get('user');`

**Comment by jasonlewis** [comment]
If this is part of the API then you shouldn't really be storing state between requests. Authenticate each request on it's own.

I still don't know why you'd be seeing this error though.

Can you comment out some route definitions to determine which route/controller is causing the issue? Then paste the route/controller in question.
