### ISSUE TITLE
Named Routes not working

### ISSUE THREAD

**Issue by YouHieng** [dingo/api#868]
It is strange but named route is working when there is a parameter in the route and not working when there is not. Where am I wrong ?

In _routes.php_
```
$api->group(['version' => 'v1'], function($api){
     ...
     $api->group(['prefix' => 'users'], function($api){
          $api->get('/', ['as' => users.index', 'uses' => 'App\Api\V1\Controllers\UserController@index']);
          $api->get('{id}', ['as' => 'users.show', 'uses' => 'App\Api\V1\Controllers\UserController@show']);
          ...
     });
     ...
});
```

And in my Controller, where I want to get the url : 
`$location = app('Dingo\Api\Routing\UrlGenerator')->version('v1')->route('users.show', ['id' => $item->fk_user_id]);`

I got the right route.

But when I wanna get this route : 
`$location = app('Dingo\Api\Routing\UrlGenerator')->version('v1')->route('users.index');`

I got this error 500 message : `Route [users.index] not defined.`

Am I missing something ?

**Comment by catalinux** [comment]
Do you have the same error also if you have other route path than '/'?

**Comment by YouHieng** [comment]
Yes same error.

**Comment by jasonlewis** [comment]
Working fine for me.

What version of Laravel/Dingo are you using?

**Comment by YouHieng** [comment]
Hi,

I am using:
- Lumen v5.2.5
- Dingo API dev-master 3062aac

**Comment by jasonlewis** [comment]
Any chance you can replicate this is a fresh install and get it up on GH so I can see? I'm still unable to replicate this.

**Comment by jenky** [comment]
BTW api routes didn't work with laravel's routes. I can't use `route(..)` or `action(..)` at all.

**Comment by jasonlewis** [comment]
Is this still an issue?

**Comment by SavKS** [comment]
Lumen 5.2, Dingo-api @dev

File: /vendor/dingo/api/src/Routing/Adapter/Lumen.php

Method getIterableRoutes() $collector->getData() returns an array
```php
[
  'POST' => [
    // ... routes array
  ]
]
```
instead of 
```php
[
  // ... routes array
]
```

There is a need to add a nested iterator because of this. It takes only first route from array by default. That's why we need to replace
```php
foreach ($routeData[0] as $uri => $route) {
  $iterable[$version][] = array_shift($route);
}
```
to
```php
foreach ($routeData[0] as $uri => $route) {
  foreach ($route as $_route) {
    $iterable[$version][] = $_route;
  }
}
```

Lumen 5.2 uses nikic/FastRoute v0.7, while Lumen 5.1 — v0.4.
The difference can be seen in method addStaticRoute in /src/DataGenerator/RegexBasedAbstract.php.

v0.4
```php
$this->staticRoutes[$routeStr][$httpMethod] = $handler;
```

v0.7
```php
$this->staticRoutes[$httpMethod][$routeStr] = $handler;
```

**Comment by YouHieng** [comment]
Hi,

SavKS is right, and this is now working.

**Comment by jasonlewis** [comment]
Okay so we're going to need to do something regarding the different Lumen versions then... Awesome.

**Comment by jasonlewis** [comment]
Okay have pushed a fix that now normalizes the static routes array. Let me know if any issues still persist relating to this particular issue.
