### ISSUE TITLE
Add support for the "OPTIONS" HTTP method

### ISSUE THREAD

**Issue by jvanharn** [dingo/api#869]
Add support for the "OPTIONS" API method by adding a new (empty) class "Options" in the "Annotation/Method" namespace.

**Comment by jasonlewis** [comment]
For documenting your API using annotations?

**Comment by jvanharn** [comment]
For documenting the documenting capability of our API, yes. haha
But the question is, is it possible to add some more annotations for different HTTP Methods apart from the currently included Get, Post, Put, Patch, etc.

**Comment by jasonlewis** [comment]
Definitely. What other methods are missing?

You can submit issues/PRs to the [dingo/blueprint](https://github.com/dingo/blueprint) repository if you'd like. There's a few outstanding things I need to address once I finish cleaning up things here.
