### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\TokenGuard' does not have a method 'loginUsingId'

### ISSUE THREAD

**Issue by Fakeronline** [dingo/api#870]
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\TokenGuard' does not have a method 'loginUsingId'

**Comment by Fakeronline** [comment]
in Laravel 5.2

**Comment by jasonlewis** [comment]
Going to need more details please.

What are you trying to do? What code is causing this? Can we see some code? More of the stack trace too.

I'm not a magician.

**Comment by Fakeronline** [comment]
In Laravel 5.2 almost does not apply, and many methods are direct error may is because of the Laralve 5.2 in auth certification replacement, begged the perfect support Laravel 5.2 version of the

**Comment by jasonlewis** [comment]
I'm still not following.

What code causes the above error?
