### ISSUE TITLE
UnitTest

### ISSUE THREAD

**Issue by lucasdealmeida** [dingo/api#872]
I'm trying run a UnitTest but the request always return 404. It's possible running UnitTest?

`1) UserTest::testList
Expected status code 200, got 404.
Failed asserting that false is true.

vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:598
tests/UserTest.php:13`

**Comment by jasonlewis** [comment]
It is indeed possible to test API endpoints.

Please post your test and relevant routes so we can have a look.
