### ISSUE TITLE
404 Not Found - What Am I Doing Wrong??

### ISSUE THREAD

**Issue by houdini3009** [dingo/api#873]
I'm trying to create an endpoint with Dingo API, but every attempt results in a 404. Here's what I'm trying to do:

```
$api = app('api.router');
$api->version('v1', ['prefix' => 'api'], function($api) {
  $api->get('influencers', 'App\Http\Controllers\TestController@index');
});
```

My .env settings:

```
API_PREFIX=api
API_VERSION=v1
API_STRICT=false
```
Shouldn't this load properly when accessing /api/v1/influencers? What am I missing..?

If I delete the $api->get call, then I get a 400 instead of a 404.

**Comment by leepownall** [comment]
I believe it should be available at `/api/influencers`.

**Comment by jasonlewis** [comment]
Version does not get placed in the URI. As Lee has pointed out it should just be `/api/influencers`. The version is altered by using content negotiation, namely, the `Accept` header. Refer to the wiki: https://github.com/dingo/api/wiki/Making-Requests-To-Your-API
