### ISSUE TITLE
Session is saved twice

### ISSUE THREAD

**Issue by Anahkiasen** [dingo/api#874]
Not sure I understand what this code is originally meant to do but in `\Dingo\Api\Http\Middleware\Request::terminate` this is done:

```php
foreach ($middlewares as $middleware) {
            list($name, $parameters) = $this->parseMiddleware($middleware);

            $instance = $this->app->make($name);

            if (method_exists($instance, 'terminate')) {
                $instance->terminate($request, $response);
            }
        }
```

This causes all middlewares to be terminated a second time, it doesn't matter for most but it causes the `StartSession` middleware to save the session twice, _also_ aging flash data twice. Basically flash messages don't work anymore since they're aged twice before anything can happen.

**Comment by Anahkiasen** [comment]
Introduced in 05cbc2918e118ad71a0f44dfd754552c7388c27e

**Comment by jasonlewis** [comment]
Laravel or Lumen?

**Comment by Anahkiasen** [comment]
Laravel 5.2

**Comment by jasonlewis** [comment]
Cheers, I'll take a look, definitely shouldn't terminating them twice.

I'd like to point out that an API shouldn't really save any state between requests either.

**Comment by jasonlewis** [comment]
Are you doing anything else? When I hit an endpoint with it enabled I'm only seeing it terminated once. I threw a `\Log::info('session terminated')` in the `StartSession.php` middleware, it's only logged once per request.

I've also tried with internal requests. Seems to be working fine.

So any code you can provide to help replicate this would be great.

**Comment by andersfloor** [comment]
Thanks for looking into this. I'm encountering the exact same problem and was able to reproduce like this:

Did a new laravel install
Added Dingo with
`composer require dingo/api:1.0.x@dev`

Added provider to app.php

```
(...)
Illuminate\Validation\ValidationServiceProvider::class,
Illuminate\View\ViewServiceProvider::class,
Dingo\Api\Provider\LaravelServiceProvider::class,

/*
 * Application Service Providers...
 */
App\Providers\AppServiceProvider::class,
App\Providers\AuthServiceProvider::class,
(...)
```

Used these settings in .env:

```
API_STANDARDS_TREE=vnd
API_SUBTYPE=testinstall
API_PREFIX=api
API_VERSION=v1
API_NAME=testinstall
API_STRICT=false
```

Set up my routes like this:
```
Route::group(['middleware' => ['web']], function () {

    Route::get('/notify',function(){
        Session::flash('msg','Hey, You have a message to read');
        return Redirect::to('/result');
    });

    Route::get('/result', function () {
        dd(Session::all());
    });

});
```

When I call /notify, it redirects to /results which shows the following information (empty flash):

```
array:3 [▼
  "_token" => "yTp0B8ws7A9pXRo7bM3NjNbJnqn6BbUtqNwCyo5r"
  "flash" => array:2 [▼
    "new" => []
    "old" => []
  ]
  "_previous" => array:1 [▼
    "url" => "http://localhost:8000/notify"
  ]
]
```

This is the result page when i disable (comment out) the Dingo api in app.php:

```
array:4 [▼
  "_token" => "yTp0B8ws7A9pXRo7bM3NjNbJnqn6BbUtqNwCyo5r"
  "flash" => array:2 [▼
    "new" => []
    "old" => array:1 [▼
      0 => "msg"
    ]
  ]
  "_previous" => array:1 [▼
    "url" => "http://localhost:8000/notify"
  ]
  "msg" => "Hey, You have a message to read"
]
```

I agree API's should not save state, but in my case I'm building a Laravel app with a website and API (for mobile app purposes), where the website will be consuming the API. I wish to use flash messaging on the website.

**Comment by jasonlewis** [comment]
Yeah this was an oversight on my behalf, thanks for the code samples. Dingo wasn't checking if the request was an API request before terminating the middleware, so it was occurring twice for non-API routes.

Pushed a patch so that only API requests are terminated by Dingo, since they aren't terminated by Laravel/Lumen.

Let me know if things look better now.

**Comment by arthurkirkosa** [comment]
All tests are fixed for me as well.

**Comment by Anahkiasen** [comment]
Don't have time to check if it fixes it for me on my end but what @jasonlewis describes sounds like what I had (ie. it was happening on web requests, not API ones) so it should be good as well
