### ISSUE TITLE
Undefined Property issue after composer update.

### ISSUE THREAD

**Issue by holoverse** [dingo/api#875]
Ive been using this package in Laravel 5 and its been working like a charm until today.  I ran composer update by accident.  

And now I get this message when trying to access my api route.

{"message":"Undefined property: Illuminate\\Http\\JsonResponse::$exception","status_code":500,"debug":{"line":561,"file":"C:\\wamp\\www\\myapp\\vendor\\dingo\\api\\src\\Routing\\Router.php","class":"ErrorException","trace":["#0 C:\\wamp\\www\\myapp\\vendor\\dingo\\api\\src\\Routing\\Router.php(561): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', 'C:\\\\wamp\\\\www\\\\rai...', 561, Array)","#1 C:\\wamp\\www\\myapp

Something changed inside of a 2 week (original install) period, that broke my app.

**Comment by jasonlewis** [comment]
You're returning a `JsonResponse` from your API somewhere?

I made a change today that checks for any bound exceptions on the response object. This is another reason why folks shouldn't be returning a `JsonResponse`.

**Comment by holoverse** [comment]
Oh man...I didn't know that. Im new to Dingo, and am returning JSON all over the place...lol how should I correctly be responding to requests?

**Comment by holoverse** [comment]
K, nevermind, figured it out

**Comment by jasonlewis** [comment]
Yeah a lot of people do and it causes a lot of troubles. I might throw something in to detect the response and if it's a `JsonResponse` just error out immediately.

From your API, basically, just return whatever it is. If you're not wanting to use transformers, you can safely return the model/array directly from your route/controller method. The API will handle the formatting.

If you're returning an object you need to make sure it implements one of the "arrayable" interfaces.

If you need a custom status code or header, you can return a new `Response` instance. In this case, you can use either `Dingo\Api\Http\Response` or just `Illuminate\Http\Response`, if you use the latter it'll be converted into a Dingo `Response` object.

So, you might want a `201 Created` response.

```php
return new Dingo\Api\Http\Response($user, 201);
```

Where `$user` is a user model instance.

If you're using controllers you have a bunch of helper methods in `Dingo\Api\Routing\Helpers`.

Refer to the Wiki for more.

**Comment by holoverse** [comment]
How can I just return a JSON response.  I have one route that just returns a string in JSON format. 
All I was doing for that route was Response::json("string here");  When I use Dingo\Api\Http\Response it echoes it out.  Which isnt what I want.

**Comment by jasonlewis** [comment]
Good point, guess I've never returned strings. I can look into something though. Strings originally resulted in a JSON response of `{"message":"string here"}`, however, I guess the formatter can be reverted and instead of doing that just encode the string as normal.

Folks often use plain strings for JSON responses?

**Comment by holoverse** [comment]
No probably not.  Im probably just being an idiot. I can easily just do "message"=>"string" instead.
Thanks!

**Comment by morfin** [comment]
Response::json casts objects into arrays automatically.
For some reason, if I pass an object to Dingo\Api\Http\Response, I get a 500 error:
```
ErrorException: md5() expects parameter 1 to be string, object given in /home/vagrant/libre-laravel/vendor/dingo/api/src/Routing/Router.php:608 
```

So my fix was:
```
 if(is_object($data))
{
    $data = (array) $data;
}

return new \Dingo\Api\Http\Response($data,........)
```

**Comment by jasonlewis** [comment]
@morfin, what kind of object exactly?

**Comment by morfin** [comment]
stdClass

**Comment by jasonlewis** [comment]
I've got some ideas... Leave it with me.

**Comment by jasonlewis** [comment]
You can keep using `JsonResponse` now, although I suggest you don't. You also shouldn't be returning objects that aren't "arrayable". There's usually always a better way of doing it.

**Comment by morfin** [comment]
Actually I will only provide Arrayable Objects. I don't need to use JsonResponse, I already switched my code to Dingo Response. It would be nice if Dingo can take of basic Obj->Array casting, though.
