### ISSUE TITLE
Unsupported response object 'Illuminate\Http\JsonResponse'

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#879]
If you find you're now getting this error it's because you're returning a `JsonResponse` from one of your endpoints.

Basically, you shouldn't be. You should simply be returning whatever it is as it is, or using `Dingo\Api\Http\Response` (or `Illuminate\Http\Response`). A `JsonResponse` object hasn't been supported for some time, however, it's come to my attention that a number of folks are using it.

Some examples of valid responses.

```php
return $users; // Where $users is a collection or array of User models.

return new Dingo\Api\Http\Response($user, 201); // Where $user is a User model.

return ['foo' => 'bar'];
```

Or use the response builder.

For more information on responses refer to the Wiki: https://github.com/dingo/api/wiki/Responses

**Comment by jenky** [comment]
So I have to update all my controllers, meh. Without stable release for 1.x brach, it's hard to revert the version tho.

**Comment by jasonlewis** [comment]
Sorry, but it was never intended to be used that way, due to the issues it caused. I've only recently become aware of folks using `JsonResponse`.

If you really want to use `JsonResponse` then I guess you can just require the specific commit (the one before this change) by using `dev-master#commit` in your `composer.json`.

I'd personally just spend several minutes switching everything out.

**Comment by jenky** [comment]
Yeah, I know. But I personally didn't like the json payload was wrapped inside a key ie:
```php
return $users; // Collections
```
would output

```json
{
    "users": [
        {
            "id": 1,
            "first_name": "Harley",
            "last_name": "Koss",
            "email": "Reva34@Hamill.org"
        },
        {
            "id": 2,
            "first_name": "Cade",
            "last_name": "Collier",
            "email": "Upton.Yoshiko@hotmail.com"
        }
    ]
}
```

I guess ``->toArray()`` could make the trick tho.

**Comment by jasonlewis** [comment]
FYI I'm probably about to revert this change. So apologies again if I do. Granted, I'd still prefer people didn't use it.

The way I'm working it at the moment is that it basically decodes the JSON from `JsonResponse` so that the "original content" is a plain array. That way it's normalized for both external and internal requests.

**Comment by jasonlewis** [comment]
Okay pushed the change.

So you *can* keep using `JsonResponse`, but internal requests won't be nearly as useful, as you'll be getting plain arrays instead of the actual model/collection.

As for the models being wrapped, you can simply override the `Json` response formatter to not wrap it with the model name as the key.

You'd just need to replace the `formatEloquentModel` and `formatEloquentCollection` methods, just return `$this->encode` instead of wrapping it in the key.

https://github.com/dingo/api/wiki/Responses#custom-response-formats

**Comment by jenky** [comment]
Thanks, I will make my changes soon.
