### ISSUE TITLE
getController method changed to getControllerInstance

### ISSUE THREAD

**Issue by hananwm** [dingo/api#882]
Dingo\Api\Routing\Route::getController() method no longer exists and was renamed to getControllerInstance().

Dingo\Api\Console\Command\Docs::getControllers() is making use of the old name, needs to be updated to getControllerInstance()

**Comment by wayne5w** [comment]
Just hit this too, thanks for posting.

**Comment by jasonlewis** [comment]
Fix pushed, cheers.
