### ISSUE TITLE
Retrieving the authenticated user causes nginx error

### ISSUE THREAD

**Issue by headcastlab** [dingo/api#884]
Hi,

I have been assigning the authenticated user to a property using the constructor like so:

`    protected $user;

    public function __construct()
    {

        // Fire up the base controller
        parent::__construct();

        // Authenticated user
        $this->user = $this->auth->user();

    }`

The parent class contains no reference to the auth user.

But since I updated yesterday (10/03/16), this method started killing the php-fpm process with the following error:

`recv() failed (104: Connection reset by peer) while reading response header from upstream`

I have worked around the issue by adding the user to the methods that require the authenticated user.

I'm on:
Nginx 1.8.1
PHP 5.6

Using the oauth2 bridge from "lucadegasperi/oauth2-server-laravel": "5.0.*@dev"

Thanks.

**Comment by jasonlewis** [comment]
If you're using the `Helpers` trait then you can use `$this->user` already in your methods.

I'll look into this, but I've been against folks trying to pull the authenticated user in the constructor anyway since it fires the authentication business a little earlier then it's usually fired.
