### ISSUE TITLE
Call to undefined method Dingo\Api\Routing\Route::getController() in Console/Command/Docs.php:153

### ISSUE THREAD

**Issue by obayesshelton** [dingo/api#886]
Hi,

I'm using version `dev-master`  with Laravel version `v5.2.22` and when I run the following I get the bellow error:

`php artisan api:docs --name Example --use-version v1`

**error**

`local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined method Dingo\Api\Routing\Route::getController() in /var/www/example/api/vendor/dingo/api/src/Console/Command/Docs.php:153`

**Comment by jasonlewis** [comment]
Duplicate of #882 and fixed in b9ff594eedea42d5cd78f09b20cbb66dd46b1204. Make sure you `composer update` again.

**Comment by obayesshelton** [comment]
Thanks jason
