### ISSUE TITLE
Undefined property: Illuminate\Http\RedirectResponse::$exception

### ISSUE THREAD

**Issue by amirhabibzadeh** [dingo/api#887]
I used dingo router for my api's but i have laravel normal routing for my admin section . 
laravel redirect until today is working good but today i got this error .
`
line: 563,
file: "/var/www/html/evand/api/vendor/dingo/api/src/Routing/Router.php",
class: "ErrorException",
`
I found where the error is throwing 
`$response->exception` is not defined and its throw exception . 
I dont get the logic of that and why you are add this lines of code .
Can you check that ?
Or am i did something wrong and this is happening .

**Comment by jasonlewis** [comment]
Sounds like you need to `composer update`. [This has been resolved.](https://github.com/dingo/api/commit/f193d08fed417e6055c9a05f66624ae5130f7293#diff-53e2eaefba8d08c4ae2d0d082ef4d2d4R561)
