### ISSUE TITLE
dingo is terminating the route middleware

### ISSUE THREAD

**Issue by kiro64** [dingo/api#888]
i'm just update dingo api package to latest version. it cause  my log server keep produce this log message on every request 
"dingo is terminating the route middleware" 

what does it mean and why dingo log this info message on this release.
![screen shot 2559-03-12 at 10 08 10 pm](https://cloud.githubusercontent.com/assets/8982057/13723701/74cd035a-e89f-11e5-82ce-ac72d2d6bfb5.png)

**Comment by jasonlewis** [comment]
I must have left some sweet debugging code in a commit. My bad. Will get it removed.

**Comment by JustinLien** [comment]
Saw the same thing and found the issue on this commit here: https://github.com/dingo/api/commit/65e8c9e5cd30d40876d9d0be281e6d9f57d62415

**Comment by joshuaziering** [comment]
Just saw this. Is there a PR to fix this yet?

**Comment by jasonlewis** [comment]
Will be doing work on this today sometime, but if you'd like to send a PR then go for it. :+1:

**Comment by JustinLien** [comment]
@jasonlewis https://github.com/dingo/api/pull/897.

**Comment by farhod** [comment]
@kiro64 kiro64 what tool are you using for log ?

**Comment by kiro64** [comment]
@farhod  i use this Package 
https://github.com/ARCANEDEV/LogViewer

**Comment by farhod** [comment]
@kiro64  very helpful, thank you.
