### ISSUE TITLE
Middleware on route doesn't work.

### ISSUE THREAD

**Issue by mrgodhani** [dingo/api#891]
Hi I am using following code below:

```
$api->group(['middleware' => 'api.auth'],function ($api){
        $api->get('users','LaterPosts\Api\Controllers\UserController@getUser');
    });
```

and when I see list for api:routes I see below

https://infinit.io/_/Z9rU83y

Although middleware works when added using constructor in controller.

**Comment by jasonlewis** [comment]
Fixed. Thanks for the report.

**Comment by mrgodhani** [comment]
@jasonlewis After updating the package. Now I get following below:

`"call_user_func_array() expects parameter 1 to be a valid callback, class 'Dingo\Api\Auth\Auth' does not have a method 'handle'"`

**Comment by jasonlewis** [comment]
See #903.
