### ISSUE TITLE
Auth middleware not using passed request

### ISSUE THREAD

**Issue by bramdevries** [dingo/api#894]
I have a project where I wrote a custom middleware that refresh an expired access token. Here's how it works:

```php
if (!$request->headers->has($this->header)) {
    return $next($request);
}

$token = $this->decryptToken($request);

try {
    if (array_has($token, 'access_token')) {
        $request->headers->set('authorization', 'Bearer '.array_get($token, 'access_token'));
    }

    $response = $next($request);
    return $response->header($this->header, $this->encrypter->encrypt($token));
} catch (UnauthorizedHttpException $e) {
    $newToken = $this->proxy->refreshToken(array_get($token, 'refresh_token'));

    if (array_has($newToken, 'access_token')) {
        $request->headers->set('authorization', 'Bearer '.array_get($newToken, 'access_token'));
    }

    $this->container->instance('request', $request);

    $response = $next($request);

    return $response->header($this->header, $this->encrypter->encrypt($newToken));
}
```

1. A request is received with a custom HTTP header that is an encrypted access + refresh token.
2. Request is received by the middleware, let's call it `proxy`.
3. `proxy` middleware decrypts the token and performs the request using a `Bearer access_token`
4. In case of a 401 response the `proxy` tries to refresh the access token using the refresh token. This uses the internal API functionality. 
5. The `Authorization` header of the request is  replaced with the new `access_token`.
6. The request is performed as normal and returns a response with the new encrypted token.

Step 1 to 5 worked, but step 6 kept giving me an unauthorized response. I looked into the `Auth` middleware and noticed that the [`authenticate`](https://github.com/dingo/api/blob/master/src/Http/Middleware/Auth.php#L50) call doesn't use the request provided by the middleware and instead relies on the last [request performed by the `router`](https://github.com/dingo/api/blob/master/src/Auth/Auth.php#L82) which in my case was the internal API call to refresh the token.

I fixed it by rebinding the `request` instance to the previous request, but this feels like hacking.

In my opinion this is a bug, but before I go and make a PR I would like to know if there was a specific reason that the request instance passed via the middleware wasn't used.

**Comment by jasonlewis** [comment]
The internal dispatcher is meant to replace the request stack as it performs internal requests. So when the internal request is dispatched the "current" request should refer to that internal request. Once the request has been sent and you've got the response back then the "current" request should now refer to the initial request.

Sounds like it isn't replacing the requests properly though. I'll investigate.

Just to confirm but you are up to date with this repository?

**Comment by jasonlewis** [comment]
So the issue is because the dispatcher currently clones the initial request. Looking at this now I don't know why it needs to be cloned, as it would just cause issues like the one you're seeing now.

**Comment by jasonlewis** [comment]
Okay I've gone ahead and removed the cloning of the initial request as it was replacing your altered request instance after you dispatched the internal request.

Let me know how this goes for you.

**Comment by bramdevries** [comment]
Works great, thanks!

**Comment by jasonlewis** [comment]
Awesome, thanks for the feedback. :+1:
