### ISSUE TITLE
[Documentation] Mistake in custom throttle example

### ISSUE THREAD

**Issue by mweghorst** [dingo/api#899]
The example of creating a custom throttle has a bug in the import section:

`use Dingo\Api\Http\RateLimit\Throttle;`

should be

`use Dingo\Api\Http\RateLimit\Throttle\Throttle;`

**Comment by jasonlewis** [comment]
Cheers, done. If you see any other errors send them through to [dingo/api-docs](http://github.com/dingo/api-docs).
