### ISSUE TITLE
Errors using middleware with Laravel

### ISSUE THREAD

**Issue by jasonlewis** [dingo/api#903]
A recent commit may have caused issues with middlewares when using Laravel. Will update here when I have more.

**Comment by jenky** [comment]
Yep, completely breaks my app.

**Comment by xuguotao** [comment]
completely break my app too.....

**Comment by jasonlewis** [comment]
Oh and you can use `beta3` until resolved.

**Comment by jasonlewis** [comment]
Can folks try updating to the latest commit (d8ab5f4) and letting me know if there's any more issues.

I'm still tweaking some things, but the middleware should be properly registered on the router now.

**Comment by bbszt** [comment]
call_user_func_array() expects parameter 1 to be a valid callback, class 'Dingo\\Api\\Auth\\Auth' does not have a method 'handle'

when in laravel controller construct function

$this->middleware('api.auth',[])

**Comment by jasonlewis** [comment]
Have you upgraded to latest commit?

**Comment by bbthorntz** [comment]
Still not working for me even with latest commit. App completely broken right now.

**Comment by antennaio** [comment]
Route model binding is no longer working when accessing api endpoints. This is probably related to the latest changes.

**Comment by jasonlewis** [comment]
Okay please try updating again. 78ebdf1 now replaces the controller dispatcher with the adapters so middlewares defined on controllers will be applied correctly.

**Comment by diit** [comment]
To jump in here, had the same error, just updated to 6193841 and is working now.

**Comment by jasonlewis** [comment]
Cheers for the report @diit.

**Comment by jasonlewis** [comment]
@antennaio Route model binding should also be fixed now as of 619384190f9bf32080d4a370cf6d8713043e2557.
