### ISSUE TITLE
Cannot catch exception in middleware

### ISSUE THREAD

**Issue by jenky** [dingo/api#907]
I have a middleware that catch OAuth exception then response the error to my desire format. It worked before but now it isn't. And also all status code now being 500 instead of correct code. I'm using `lucadegasperi/oauth2-server-laravel` package.

**Comment by jenky** [comment]
https://github.com/dingo/api/blob/master/src/Exception/Handler.php#L179-L194

`OAuthException` is not instance `HttpExceptionInterface` so that why it always 500 now. I guess that I have to register an error handler for this.

**Comment by jasonlewis** [comment]
Just register an exception handler for it with the API.
