### ISSUE TITLE
CORS doesnt catch all errros 

### ISSUE THREAD

**Issue by aios** [dingo/api#908]
If i make request without errors on API - all fine
When controller catch error sample 500 CORS middlware doesnt catch them
```
XMLHttpRequest cannot load http://some.com.ua/files/object/1. No 'Access-Control-Allow-Origin' 

header is present on the requested resource. Origin 'http://some.com.ua' is therefore not allowed 

access. The response had HTTP status code 500.
```

**Comment by jasonlewis** [comment]
Not sure I'm following what the issue here is.

**Comment by bdsoha** [comment]
@aios: exception handling was removed from [barryvdh/laravel-cors](https://github.com/barryvdh/laravel-cors/commit/045c14052023dacaa1393f0c8df64134516f9808) recently.
You need to handle CORS errors on your own.

**Comment by aios** [comment]
I am so sorry - i added handlePreflight with middle ware - that issue can
close.

2016-03-29 15:32 GMT+03:00 Dov Benyomin Sohacheski <notifications@github.com
>:

> @aios <https://github.com/aios>: exception handling was removed from
> barryvdh/laravel-cors
> <https://github.com/barryvdh/laravel-cors/commit/045c14052023dacaa1393f0c8df64134516f9808>
> recently.
> You need to handle CORS errors on your own.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dingo/api/issues/908#issuecomment-202872149>
>



-- 
С уважением, Габриелян Д.М.

ICQ:      *3092095*
Skype:  *gt_fios*

**Comment by hskrasek** [comment]
@aios Gonna close this out, if you still are having an issue let us know.
