### ISSUE TITLE
Issue with connecting to another database on a specific model

### ISSUE THREAD

**Issue by kmccarth** [dingo/api#910]
My default database collection is called "mysql". I have one model that uses a different database connection ("wordpress"). On this model, I've added this line:

`protected $connection = 'wordpress';`

When I use this model outside of Dingo, the model uses the "wordpress" connection as expected. However, when I use this model in my API, the model continues to use the "mysql" database.

Any help is appreciated.

edit: I'm using L5.1 and Dingo 0.10

**Comment by jasonlewis** [comment]
That shouldn't happen. Quickly tested this locally and can't see it. Try updating Dingo to the latest `1.0.*@dev` version and let me know if the problem is persisting.

Dingo shouldn't touch your models.

**Comment by kmccarth** [comment]
Thanks @jasonlewis, that did it. We're still on L5.1, so I was hesitant to upgrade. 

Out of sheer curiosity, do you know what area of the Dingo codebase would have changed that now makes it work in 1.0?

**Comment by jasonlewis** [comment]
Honestly I'm not sure. I've never heard of it happening before. I'm not sure where in the codebase Dingo would even try to touch your models. Very strange...
