### ISSUE TITLE
Non-api route problem

### ISSUE THREAD

**Issue by achegedus** [dingo/api#911]
I'm very new to Dingo, and I'm having what is probably a simple problem.  I'm trying to have laravel return a route that is not in the api.  My routes look like this:

    $api = app('Dingo\Api\Routing\Router');
    
    Route::get('/', function () {
        return view('welcome');
    });
    
    $api->version('v1', function ($api) {
        $api->get('reports/', 'App\Api\Controllers\reports@index');
        $api->get('report/{id}', 'App\Api\Controllers\reports@show');
    });

When I go to http://locahost:8000/api/reports, i get the correct api response.  When I go to http://localhost:8000/, though, i get this:

    {"message":"404 Not Found","status_code":404}

Any idea what i'm doing wrong?

Any help would be fantastic.

Thanks!

**Comment by mushu8** [comment]
i have two routing files in my profject, one for the api and another one for the website.
it allows me two have my api files (controllers) under a versioned api namespace
the routing files are loaded as so :
```
public function map(Router $router)
{
    // dingo api need to be out of current namespace
    require app_path('Api/V1/Http/routes.php');

    $router->group(['namespace' => $this->namespace], function ($router) {
        require app_path('Http/routes.php');
    });
}
```
in the app/Providers/RouteServiceProviders.php file

**Comment by jasonlewis** [comment]
Check your `laravel.log` file in `storage/logs` to see what the complete exception is.

Should be working fine though.

**Comment by achegedus** [comment]
@mushu8, I tried your method and I get the same result.  I can't create a route that doesn't use dingo.  

@jasonlewis I checked the logs, nothing is being written to it when i go to /.  I get a 404 in the JSON response, but no exception is being thrown.

Any other ideas?

**Comment by achegedus** [comment]
I turned on debug in dingo and now i see this as a json response when i try to go to the root route:

{"line":161,"file":"\/Users\/adam\/Projects\/SampleReports\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/RouteCollection.php","class":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException","trace":["#0 \/Users\/adam\/Projects\/SampleReports\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(823): Illuminate\\Routing\\RouteCollection->match(Object(Dingo\\Api\\Http\\Request))","#1 \/Users\/adam\/Projects\/SampleReports\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(691): Illuminate\\Routing\\Router->findRoute(Object(Dingo\\Api\\Http\\Request))","#2 \/Users\/adam\/Projects\/SampleReports\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(675): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#3

So the request seems to be getting handed off to the dingo route handler and there's no api route at / so i get a 404.  But i would expect that the Laravel route handler should pick this one up... am i way off base??

Thanks again for the help.

**Comment by jasonlewis** [comment]
How have you configured Dingo? Have you set `API_DOMAIN` by any chance? And `API_PREFIX`?

You only need one. And it looks like you want a prefix. So if you have set `API_DOMAIN` then make sure it's set back to `null`.

**Comment by achegedus** [comment]
Well, I started from scratch, and now it's working fine.  not sure what i screwed up on the last try, but I'm good now.  Thanks!

**Comment by jasonlewis** [comment]
Sounds like both `API_DOMAIN` and `API_PREFIX` were configured to me. Glad it's sorted, cheers!

**Comment by achegedus** [comment]
I went back and looked at my previous project, and you're right @jasonlewis, I had both parameters set.

**Comment by andela-tolotin** [comment]
I think the problem is the documentation. If your domain has port then there's high tendency for your route not to work.

```
$params = [
    'as' => 'api::',
    'version' => 'v1',
    'domain' => env('APP_URL'), // Notice we use the domain WITHOUT port number
    'namespace' => 'App\\Http\\Controllers',
];

$api->group($params, function($api) {
    $api->get('users', 'TestController@show');
});
```

make sure that your `domain` does not contain any port
