### ISSUE TITLE
OAuth, API and Sessions

### ISSUE THREAD

**Issue by wayne5w** [dingo/api#912]
I understand that for an API I am not supposed to use sessions, rather the user is retrieved via the oauth token. This makes sense but I am confused as League\OAuth2\Server\Grant\PasswordGrant creates a SessionEntity, adds the user, and associates the token with the session. 

Also, should one disable sessions entirely for a laravel app which is strictly serving API? If so how? 

I tried commenting \Illuminate\Session\Middleware\StartSession::class in Kernel but an exception was thrown by Request - [2016-03-20 01:21:06] local.ERROR: exception 'RuntimeException' with message 'Session store not set on request.' in /home/vagrant/Code/testQuality/vendor/laravel/framework/src/Illuminate/Http/Request.php:760.

**Comment by jasonlewis** [comment]
OAuth is slightly more complicated than most other mechanisms so it stores the access token and associated details. I wouldn't compare this to application sessions that persist data between requests though.

Disabling sessions is entirely up to you. The best way to do this is to simply set the session driver to `array`, either in your `.env` file or in `config/session.php`.

If you remove the `StartSession` middleware you may need to remove these ones as well:

```php
\Illuminate\View\Middleware\ShareErrorsFromSession::class
\App\Http\Middleware\VerifyCsrfToken::class
```
