### ISSUE TITLE
Paginator transformer problem

### ISSUE THREAD

**Issue by mushu8** [dingo/api#914]
Hi,

i would like to transform objects returned in a paginator : 
i have a thread model and a participant model and each thread has only two participant including the one asking the data.
So i would like to return the thread objects with a property 'participant' as a single User object instead of an array of the two users.

i have this code to get the data : 

```
$threads = Thread::forUser($currentUserId)
        ->with('participants.user')
        ->with(['participants' => function ($query) {
            $query->where('user_id', '!=', $this->user->id);
        }])
        ->latest('updated_at')
        ->Paginate(2);
```

it selects the threads with only the _other_ participant.

My problem is the formatted threads contains an array with the single user instead of the user only…

How can i use a transformer to do this please ?

Is it also possible to customize how the paginator is formatted ?

**Comment by mushu8** [comment]
some clarification :
Thread model has a has_many relationship 'participants'
Participant model has a user property

**Comment by hskrasek** [comment]
@mushu8 Some of your question is a bit reliant on knowing your projects domain/context, and we may not be able to fully help there. But I would recommend checking out [Fractal's page on pagination](http://fractal.thephpleague.com/pagination/) which includes a section on how to use it with Laravel's Paginator

**Comment by specialtactics** [comment]
Closing due to issue age
