### ISSUE TITLE
Custom Throttle and getting User

### ISSUE THREAD

**Issue by Netifriik** [dingo/api#915]
I'm creating a new Throttle for my API but I need to get the User to set the correct limits.
How can I access the users data through `Container $app`?

I tried using `$app->auth->user()` but that was unsuccessful.

**Comment by mushu8** [comment]
you can try this : ```$app['api.auth']->user()``` maybe ?

this is the definition for the static function user() in the facade Api…

**Comment by Netifriik** [comment]
Thank You, it worked.
