### ISSUE TITLE
Route Cache, much slower than without

### ISSUE THREAD

**Issue by wayne5w** [dingo/api#916]
So this is really odd. I've got 168 controllers, most with 5 routes for index, show, store, update, and destroy. I don't use route as I don't want to pay the price for reflection so I have ~680 routes specified in routes, all under dingo ($api). The issue is with the route cache the times via postman are at least 30% slower than without the route cache and this performance is consistent with homestead and AWS/forge.

Any ideas what is going on? The config cache delivers a modest performance improvement, as expected. I traded email with Taylor Otwell and he's never seen this, he always sees a big performance gain from using the route cache.

**Comment by jasonlewis** [comment]
I'll take a look, see what I can find.

**Comment by wayne5w** [comment]
Thanks.

**Comment by wayne5w** [comment]
Any news? Does anyone else have similar behavior with the route cache?

**Comment by jasonlewis** [comment]
Haven't had a chance to replicate this yet, been a little busy with other areas.

**Comment by wayne5w** [comment]
Has anyone else experienced this problem?

**Comment by wayne5w** [comment]
Bump

**Comment by kcalliauw** [comment]
Same problem here

**Comment by realshadow** [comment]
Can confirm the issue. In my case all requests with api:cache are 5 times slower. Would really love to use the cache in production

**Comment by realshadow** [comment]
Bump

**Comment by mxkh** [comment]
@jasonlewis The same issue for me! :(

**Comment by specialtactics** [comment]
I'm aware of the issue @mxkh, unfortunately I think the best solution for this is a complete re-write were we're back to using Laravel's router.
