### ISSUE TITLE
Override "strict" setting for certain routes

### ISSUE THREAD

**Issue by dataknightinc** [dingo/api#917]
It would be nice to have a way to override the "API_STRICT" setting for a particular route or set of routes.  What I want to be able to do is force applications using my API to use strict Accept headers for everything, however, I want them to be able to first interrogate a specific route (or even just /) without requiring the Accept header in order to produce a list of available versions (and statuses of those versions) as well as accepted response formats.

**Comment by dataknightinc** [comment]
I actually just implemented this myself by doing the following:

1. Extend the Dingo\Api\Http\Parsers\Accept class into a new class.
    a. Override the Accept class's __construct() function to include an extra parameter for "strictExceptions".
    b. Override the Accept class's parse() function to check to see if the path/URI and method in the request are in the "strictExceptions" associative array before throwing a BadRequestHttpException().

2. Extend the Dingo\Api\Provider\LumenServiceProvider class into a new class.
    a.  Override boot() and registerHttpValidation() functions so they return an instance of the new Accept class that was created.
    b.  Override setupConfig() to pull 'strictExceptions' configuration settings in to 'api' index.  (Used by Accept class's parse() function)

3. Create a new config within my app to define the 'strictExceptions' array which is an associative array whose keys are URIs whose value is a list of exempted HTTP request methods (or all methods if the list is empty).

**Comment by jasonlewis** [comment]
Hey mate made this way easier if you pull in the latest commits.

Should just have to rebind `Dingo\Api\Http\Parser\Accept` now and all should be sweet.

```php
$app->singleton('Dingo\Api\Http\Parser\Accept', function ($app) {
    return new YourAcceptParserThatExtendsTheDingoOne;
});
```

Let me know how you go.
