### ISSUE TITLE
Cannot link to laravel's routes

### ISSUE THREAD

**Issue by jenky** [dingo/api#918]
I have a normal route like this:

```php
Route::get('browse', [
    'as' => 'browse',
    'uses' => 'HomeController@browse',
]);
```

Normally I can generate url by using `route('browse')` or `action('HomeController@browse')` but now it doesn't work with API's routes.

**Comment by jenky** [comment]
Well, this changes https://github.com/dingo/api/commit/de7bbb4d64777b6cdb7800eab178db867165c3e0 cause the error.

**Comment by jasonlewis** [comment]
Dingo has it's own `UrlGenerator` to help generate links to routes/actions. It's bound as `api.url` in the container.

There's a `version` helper function to shorten the calls somewhat.

```php
app('api.url')->version('v1')->route('api.route.name');

version('v1')->route('api.route.name'); // same as above
```

You need to define the version first so it can pull in the right route collection.

**Comment by jenky** [comment]
I want to generate link for laravel routes, not API routes.

**Comment by hakanersu** [comment]
After update i have this problem too , dingo api routes overwrites laravel routes.

**Comment by jenky** [comment]
Yeah, I've sent a pull request to fix this. Hopefully it will get merged soon.

**Comment by jasonlewis** [comment]
Ah, gotcha, I see now.

I want to look at something else first.

**Comment by jasonlewis** [comment]
Also if you're experiencing issues with the latest commits, which I know a lot are, just roll back to `beta3` for the time being.

Trying to fix one important issue and making about 10 others at the moment. Give me a little more time to sort it though.

**Comment by jasonlewis** [comment]
When you get the chance please pull in the latest commit and let me know if this is resolved. I'm now manually setting the application routes back on the container to trigger the rebinding event so the routes on the generator will remain the same.

**Comment by KhaledSMQ** [comment]
The new update broke all my laravel links :(

**Comment by jasonlewis** [comment]
Going to need more info @KhaledSMQ? You've updated to the latest commits?

**Comment by KhaledSMQ** [comment]
@jasonlewis 

simply routing are not found even the wildcard returning undefined ... any idea or update soon to fix routing issue ?

**Comment by hakanersu** [comment]
As @jasonlewis response above ,already fixed. Just pull latest commits.

**Comment by KhaledSMQ** [comment]
@hakanersu 
i already pulled it yesterday. i think this issue comes with the latest commit but am not sure.

**Comment by KhaledSMQ** [comment]
i can see the correct routing in console ( php artisan route:list , and php artisan api:routes),
this issue make me confused some of routes are working and new routes are not returning 404

**Comment by KhaledSMQ** [comment]
After stopping the Package service providers the laravel routes back to work normally , the package make me feel like trying to create second laravel inside laravel.

**Comment by jasonlewis** [comment]
@KhaledSMQ, are you using Laravel 5.1 or 5.2? So you're saying that Laravel routes are not working?

How have you configured the API? Do you have `API_DOMAIN` and `API_PREFIX` set or just one of them?

**Comment by KhaledSMQ** [comment]
@jasonlewis 

here is my ENV file
```
API_STANDARDS_TREE="vnd"
API_SUBTYPE="khaled"
API_PREFIX="api"
API_DOMAIN="api.myserver.com"
API_VERSION="v1"
API_NAME="My API"
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEFAULT_FORMAT=json
API_DEBUG=true

```

**Comment by jasonlewis** [comment]
You should not be setting a prefix and a domain. One or the other.

**Comment by KhaledSMQ** [comment]
@jasonlewis 
Great it's working now
i have already tried to remove the prefix but didn't work then i return the prefix and remove the domain it's working fine now

i think the problem was from the domain ```API_DOMAIN```

**Comment by amirhabibzadeh** [comment]
I have this error too after lastest commit and from your conversations i noticed, 
when i set `API_DOMAIN` laravel routes are returned undefined , but it works good with setting `API_PREFIX` .
@jasonlewis is it fixeable or i found other solution ?

**Comment by jasonlewis** [comment]
@amirhabibzadeh `API_DOMAIN` should ONLY be used when you're using Laravel and have a virtual host configured for the sub-domain, for example, `api.yourapp.com`.

If you're using `API_DOMAIN` then `API_PREFIX` should be `null`.

If you're API is served from `yourapp.com/api` then you'll want to be using `API_PREFIX`.

**Comment by amirhabibzadeh** [comment]
@jasonlewis thanks for reply ,
I update dingo with composer 2 minutes ago .
I have virtualhost api.mysite.com
And not use api prefix.

NOW 
all routes not working

my config :`laravel 5.1`
this is my `.env`
```
API_STANDARDS_TREE=x
API_SUBTYPE=evand
API_PREFIX=null
API_DOMAIN=api.evand.dev
API_VERSION=v1
API_NAME=Evand API
API_CONDITIONAL_REQUEST=false
API_STRICT=false
API_DEBUG=true
```

this my routes.php
some section
```
//for laravel routes
Route::get('/', function(){
   return 'It's NOT works :(';
});

//for api routes
$api = app(Dingo\Api\Routing\Router::class);
$api->version('v1', ['namespace' => 'Evand\Http\Controllers\V1'], function ($api) {
    $api->get('/apiroute', function(){
        return "it works :)";
    });
});
```
but same code with oldest relase of dingo works fine .

**Comment by jasonlewis** [comment]
There must be something else missing @amirhabibzadeh.

Can you open a new issue with as much info as you can, include errors and stack traces. Even better would be pushing the broken code up so I can pull it down and test it out.
