### ISSUE TITLE
[Documentation] Improve the example for JWT auth provider

### ISSUE THREAD

**Issue by Konafets** [dingo/api#920]
Add the surrounding array to the example

> Once you have the package you can configure the provider in your config/api.php file or in a service provider or bootstrap file.
> 
>     'jwt' => 'Dingo\Api\Auth\Provider\JWT'

should become 

> Once you have the package you can configure the provider in your config/api.php file or in a service provider or bootstrap file.
> 
>     'auth' => [
        'jwt' => Dingo\Api\Auth\Provider\JWT::class
    ],

**Comment by bdsoha** [comment]
+1

**Comment by maurodaprotis** [comment]
+1

**Comment by hskrasek** [comment]
Documentation updated to better reflect the actual config file.
