### ISSUE TITLE
Call to a member function method() on a non-object (null)

### ISSUE THREAD

**Issue by awkwardusername** [dingo/api#923]
On update from 0.10.0 to 1.0.x. Had to rollback to fix it.

Any documentation on this particular upgrade issue?

**Comment by jasonlewis** [comment]
I'm going to need more info...

More stack trace and relevant code please.

**Comment by awkwardusername** [comment]
I'm afraid I can't give anything useful. Rest assured there were no changes of code were done from 0.10.0 to 1.0.x. Just the dingo api version change.

Controller is like this, 

```
use Kaching\AdminSystem\Http\Controllers\Controller;

class DeviceController extends Controller {

public function index()
    {
        $devices = Device::unassigned()->forDeployment()->withDetails()->orderBy('device_name', 'asc')->get();

        return $this->response()->collection($devices, new UnassignedDevicesCompactTransformer);
    }
}
```

Base controller which is extended is,

```
use Dingo\Api\Routing\Helpers;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests, Helpers;
}
```

of which, again, wasn't changed ever since.

**Comment by jasonlewis** [comment]
Enable debug mode for the API and paste the rest of the stack trace.

**Comment by awkwardusername** [comment]
Oops. I've enabled debug mode and it seemed that I have a broken dep. It's all okay now. Thanks.

**Comment by jasonlewis** [comment]
Cheers, always handy to have debug mode enabled in your `.env` for your local developing. :+1:

**Comment by awkwardusername** [comment]
I agree, although I think it makes more sense if dingo uses `APP_DEBUG` instead of an `API_DEBUG` var to check for the environment vars.

Just my two cents tho. Anyways, thanks for your hard work. :smile:
