### ISSUE TITLE
Please upgrade support Laravel 5.2!

### ISSUE THREAD

**Issue by Vagabondtq** [dingo/api#925]
Hey team,

I like, very very like your module, but, i don't use  Laravel 5.2 and some thing more Module support. Please upgrade support Laravel 5.2

**Comment by jasonlewis** [comment]
What troubles are you having with Laravel 5.2? This package should be working in 5.2 right now.

**Comment by paul-crashley** [comment]
It doesn't work for me.

Current stable version (0.10.0) which installed when using composer require has:

```
"illuminate/routing": "5.1.*",
"illuminate/support": "5.1.*",
```

in its requirements.
