### ISSUE TITLE
dingo/api/src/Http/Validation/Prefix.php:55 - explode() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by erroric** [dingo/api#926]
Api is broken after upgrade in my project.
`prefix` instance variable value in `Dingo\Api\Http\Validation\Prefix:55` is `Dingo\Api\Facade\API` instance, instead of string.

Bug occurs, because I have API_PREFIX=api in my.env and class alias with same name `'API'  => Dingo\Api\Facade\API::class` in my app.php config.

In `Dingo\Api\Provider\HttpServiceProvider:59`:
```
$this->app->singleton('Dingo\Api\Http\Validation\Prefix', function ($app) {
    return new Validation\Prefix($this->config('prefix'));
});
```
`config()` method have weird logic - it found that "api" string from config is the name of existing class (API facade alias) and instantiating it instead of just set it as string!

Trying to instantiate with IoC everything from api config strings probably bad idea with unpredictable side effects ...

**Comment by jasonlewis** [comment]
Good pickup, although I found it was case sensitive for me. Regardless, I've gone ahead and changed the logic for the `config` method so it only attempts to instantiate config items that are part of the instantiable array.
