### ISSUE TITLE
Web View Route Not Found 404 Status Code

### ISSUE THREAD

**Issue by zahidaziz16** [dingo/api#928]
Hi,

After updating laravel dingo api package, I notice all my Web View route not found returning 404 status code yet all api routes are working fine. How possible I can resolve this? Do I have to set up any configuration to split up api and web view routes??

**Comment by jasonlewis** [comment]
Yes, make sure you've set either `API_PREFIX` or `API_DOMAIN`. The domain option should only be used IF you're using sub-domain routing in Laravel. Otherwise use a prefix.

**Comment by zahidaziz16** [comment]
Thanks Jason,

That is really helpful..
