### ISSUE TITLE
CORS stop working after dingo update

### ISSUE THREAD

**Issue by sefsinalas** [dingo/api#930]
Hello.

I had a problem with cors and spend two days trying to solve it. Now a finally came to an aproximation of the problem.

**The context:**
1 app in angular + ionic
1 api with lumen + dingo

**The problem:**

The api was working well and then I made:

`composer update dingo/api`

And get this

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing dingo/api (dev-master b36db17)
  - Installing dingo/api (dev-master b049120)
    Downloading: 100%         

Writing lock file
Generating autoload files

```
And then I made composer dump-autoload

And in this point the api was not working anymore. This is what I receive

![captura de pantalla de 2016-03-23 13-56-49](https://cloud.githubusercontent.com/assets/1595040/13993445/2d1daeac-f0ff-11e5-8573-18bcec924136.png)

**Comment by catalinux** [comment]
How did you treat your CORS pre-flight requests?

**Comment by rizkytahara** [comment]
Had the same problem after update, I'm using https://gist.github.com/danharper/06d2386f0b826b669552 for handling the CORS. It was working fine before update..

My client app using Ember CLI and Ember CLI Cordova and was working fine, but get this after update:

```
XMLHttpRequest cannot load http://localhost:91/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

any idea how to make the CORS work again?

**Comment by catalinux** [comment]
It might have to do with the way you add your middleware. I had a similar problem with one of my own middleware that was set wirth $app->middleware and it won't start. 

The solution was here: https://github.com/dingo/api/issues/876 , and it worked!

**Comment by catalinux** [comment]
@sefsinalas  @rizkytahara : could you check if that works for you?

**Comment by rizkytahara** [comment]
just try it, still not working.

config/api.php
```

    'middleware' => [
        \App\Http\V1\Middleware\CorsMiddleware::class
    ],

```

bootstrap/app.php
```

$app->configure('api');

```

it won't get called from the client app, but when I'm using Postman, it works just fine... any more clue?

**Comment by catalinux** [comment]
do you have any errors in  your log file?

**Comment by rizkytahara** [comment]
@catalinux Thanks, it works after I remove and installed again the package

```
composer remove dingo/api
composer require dingo/api:1.0.x@dev
```

move the middleware from `$app->middleware` array to a config file, then call the config file with `$app->configure('api')`


hope that works too for @sefsinalas

**Comment by rizkytahara** [comment]
Btw, a litte OOT; is there a way to automatic call the configuration?
So, I don't have to call with `$app->configure('api')` ? 
I also have an `config/oauth2.php` file that autoloaded without calling it via `$app->configure('oauth2')`

**Comment by jasonlewis** [comment]
@rizkytahara I think I can bootstrap it in the provider actually. I'll look into that.

**Comment by rizkytahara** [comment]
@jasonlewis Thanks :)

**Comment by sefsinalas** [comment]
That works! Thank you! :+1: 

Previously I had this in app.php:

```
$app->middleware([
	'palanik\lumen\Middleware\LumenCors'
]);
```


Now I deleted it. Crated a file config/api.php with this content:

```
<?php

return [

    'middleware' => [
    	'palanik\lumen\Middleware\LumenCors'
    ]

];
```

And added this line to app.php

`$app->configure('api');`

**Comment by jasonlewis** [comment]
Pushed, provider will now configure API on boot.
