### ISSUE TITLE
why method `paginator` not use status code 206?

### ISSUE THREAD

**Issue by tinpont** [dingo/api#934]
`vendor/dingo/api/src/Http/Response/Factory.php` file, line 148
```php
    /**
     * Bind a paginator to a transformer and start building a response.
     *
     * @param \Illuminate\Contracts\Pagination\Paginator $paginator
     * @param object                                     $transformer
     * @param array                                      $parameters
     * @param \Closure                                   $after
     *
     * @return \Dingo\Api\Http\Response
     */
    public function paginator(Paginator $paginator, $transformer, array $parameters = [], Closure $after = null)
    {
        if ($paginator->isEmpty()) {
            $class = get_class($paginator);
        } else {
            $class = get_class($paginator->first());
        }

        $binding = $this->transformer->register($class, $transformer, $parameters, $after);

        return new Response($paginator, 200, [], $binding);
    }
```

> 10.2.7 206 Partial Content

>> The server has fulfilled the partial GET request for the resource. The request MUST have included a Range header field (section 14.35) indicating the desired range, and MAY have included an If-Range header field (section 14.27) to make the request conditional.

**Comment by jasonlewis** [comment]
Append `->setStatusCode(206)`.

A `Range` header isn't included though. So, unless we add that in as well, then it doesn't cover it exactly.

Feel free to PR it all if you think it's possible and the solution is clean.
