### ISSUE TITLE
Dingo\Api\Routing\Helpers trait adds unwanted routes with Dingo\Api\Routing\Router#controller()

### ISSUE THREAD

**Issue by erroric** [dingo/api#937]
When I include Helpers trait in my controllers and use `$router->controller(...)` method in my routes, I getting four unexpected routes:

```
...
GET|HEAD /api/mycontroller/throttles/{one?}/{two?}/{three?}/{four?}/{five?}
GET|HEAD /api/mycontroller/rate-limit/{one?}/{two?}/{three?}/{four?}/{five?}
GET|HEAD /api/mycontroller/scopes/{one?}/{two?}/{three?}/{four?}/{five?}
GET|HEAD /api/mycontroller/authentication-providers/{one?}/{two?}/{three?}/{four?}/{five?}
...
```

because Helpers trait have 4 public methods: 

`getThrottles, getRateLimit, getScopes, getAuthenticationProviders`

which erroneously are recognized as controller actions

probably it should be renamed or filtered inside `controller()` method like `getMethodProperties`

**Comment by jasonlewis** [comment]
Fixed. Was a carry over from when I switched it from a base controller to the helpers trait. Have added the `ControllerInspector` back in.
