### ISSUE TITLE
Bug when define route alias. Action column on routes list return "Closure"

### ISSUE THREAD

**Issue by renanbirlem** [dingo/api#939]
When use route alias, like this:
```
$api->get('users', 
         ['as' => 'users.list', 
          'uses' => 'App\Api\V1\Controllers\UserController@index']);
```

The "Action" column return "Closure".
Have an similar issue here, but dont resolve the problem.

My routes list:
![captura de tela 2016-03-24 as 12 43 19](https://cloud.githubusercontent.com/assets/13525605/14027588/26688dce-f1d7-11e5-8e0f-9b107754a726.png)

Note that when I put an alias, the action of information returns "Closure".

@jasonlewis

**Comment by renanbirlem** [comment]
Someone?

**Comment by jasonlewis** [comment]
Have you upgraded recently? I fixed a related issue in the past week or so.

**Comment by renanbirlem** [comment]
Yes... i don't know what's happening.

![Uploading Captura de Tela 2016-03-29 às 10.59.36.png…]()

**Comment by renanbirlem** [comment]
I found the problem.
i've set "minimum-stability": "dev" and "prefer-stable": true.
The property "prefer-stable" made the package is not updated. I removed it and he updated, causing the error was resolved.
