### ISSUE TITLE
how to add custom field for response json outside data

### ISSUE THREAD

**Issue by ardani** [dingo/api#944]
Hi all.,
i have problem to add custom field like:
`
cols: [],
data: []
`
how to add **cols** outside data using transformer?
thanks

**Comment by catalinux** [comment]
Cant younput them in meta key?

**Comment by ardani** [comment]
hi @catalinux .
i cant because i want create structure like this
```json
{
  "cols" : {
    "userId": {
      "index": 1,
      "type": "number",
      "unique": true,
    },
    "name": {
      "index": 2,
      "type": "string"
    }
  },
  "rows": [
    {
      "userId": 1,
      "name": "Batman"
    },
    {
      "userId": 2,
      "name": "Superman"
    }
  ]
}
```
any suggest for me?

**Comment by catalinux** [comment]
If this is the "main data" of your end pointl you should put it in data key.

Depending on your semantic, it should be a collection in your data or a item. Your data looks to me to be more like an item.

**Comment by jasonlewis** [comment]
I don't think any of the Fractal serializers offer the ability to merge data with the top level out of the box? Probably something you need to look at implementing yourself on the Fractal side of things.
