### ISSUE TITLE
Responding sucess with with custom message

### ISSUE THREAD

**Issue by DrudgeRajen** [dingo/api#948]
I can't find the way of responding success with custom message as like of responding error with custom message. Something like

$this->response->success('sucess_message',200); 

It can be useful when sending custom success message. 

Also, Till now dingo has got four response builder which are used in conjuction with Transformers. 
 what if we need to manipulate data fetched as collection or in another way  for which we cannot use any of the four dingo response builder and send it as response  ??

**Comment by jasonlewis** [comment]
```php
return ['message' => 'success'];
```

By default it will have a `200` status code.

You can PR a `success` method for the factory but it's kind of redundant when you can achieve the same result with less code.

If you don't want to use transformers then don't. You can return models and collections as they are if you wish.

**Comment by DrudgeRajen** [comment]
Actually, my data is as below

`$data = array('mcq_set'=>$mcq_set,'pq_set'=>$pq_set,'sq_set'=>$sq_set);`

and currently i'm returning as 
  `   return Response::json($data);`

how can i use transformer on this type of data ?? And without using transformer i cannot send response right ?? 

Also, 

`return ['message'=>'success']`

will respond as 

```
[
  "Success Message."
]
```

but what i want is

```
{
  "success": {
    "status_code": 200,
    "message": "Mesage has been queued for delivery."
  }
}
```

So, i think adding a method for this will be better .

**Comment by jasonlewis** [comment]
Avoid using `Response::json`, better off without it.

Read up on the Fractal documentation if you'd like to use transformers.

You do not need to use transformers to send a response. You can send a response without them. Usually transformers are useful when you have models and you want to normalize keys and/or values from the database.

```php
return ['message' => 'success'];
```

The above will produce:

```json
{
    "message": "success"
}
```

If you'd like a method you can easily just add your own method to a base controller.

```php
public function success($message)
{
    return [
        'success' => [
            'status_code' => 200,
            'message' => $message
        ]
    ];
}
```

**Comment by alinasiri1367** [comment]
How to use this method???

**Comment by catalinux** [comment]
@alinasiri1367 : can you detail a little bit your question?

Such method should be defined in your controller to map a router entry:

```php
public function success($message)
{
    return [
        'success' => [
            'status_code' => 200,
            'message' => $message
        ]
    ];
}
