### ISSUE TITLE
The difference between Dingo's paginator() and Fractal's paginatedCollection()

### ISSUE THREAD

**Issue by PrimozRome** [dingo/api#954]
As far as I read the docs of both packages Dingo uses Fractal as a transformation layer correct? In both docs I see two different approaches of returning paginated result. Dingo has its of paginator method, example:

```
class UserController extends BaseController
{
    public function index()
    {
        $users = User::paginate(25);

        return $this->response->paginator($users, new UserTransformer);
    }
}
```

and Fractal has it's own paginatedCollection(), example:

```
public function index()
{
	$users = User::paginate(25);
	return $this->fractal->paginatedCollection($users, new UserTransformer);
}
```

What is the difference here?

**Comment by jasonlewis** [comment]
Uh, where is `paginatedCollection` on Fractal? I've not seen it...

Basically if you want to utilize Transformers use the Dingo method. It registers the transformer against the instances within the paginated collection so that it's used during the morphing stage of the response.

**Comment by PrimozRome** [comment]
@jasonlewis I have seen it in this tutorial, see under pagination section https://laravelista.com/laravel-fractal

**Comment by jasonlewis** [comment]
Tutorial is very outdated. Method no longer exists on the latest Fractal AFAIK. That tutorial is from 2014.

**Comment by PrimozRome** [comment]
Thanks
