### ISSUE TITLE
Custom transformer for multiple join table

### ISSUE THREAD

**Issue by michaeltansy** [dingo/api#955]
How do i create a transformer class for join table? Currently i use eloquent relationship. Let say i have user model and userdetail model. Since the transformer always need the model to be defined in transform function, i made a eloquent join table in the transform class. But i think this is not an efficient way to do it since let say if i want to get user data in detail (user join userdetail) and if i only want to get user data (using user model only) then i have to create 2 transformer class for it. Can you please give a solution to this? Thanks @jasonlewis

**Comment by catalinux** [comment]
This is how fractal  works. Including your relationships http://fractal.thephpleague.com/transformers/ can be made by a mix of  using defaultInclude in your transformes and parsign your `includes` parameter from $_GET: http://fractal.thephpleague.com/transformers/

**Comment by jasonlewis** [comment]
Yeah generally with Fractal you'll use relationships to achieve the loading of related data, as @catalinux has pointed out.
