### ISSUE TITLE
 FatalThrowableError in Dispatcher.php line 515: Fatal error: Call to undefined method Illuminate\Http\JsonResponse::getOriginalContent()

### ISSUE THREAD

**Issue by dimassrio** [dingo/api#956]
Trying to consume own api in order to route oAuth2 Access Token. The postLogin have responsibility to get access token so user shouldnt need to expose client_id and secret

```
public function getAccessToken(){
		return \Response::json(\Authorizer::issueAccessToken());
	}

	public function postLogin(Request $request){
		$results = $this->api->post('api/auth/access', ['username'=>$request->input('username'), 'password'=>$request->input('password'), 'client_id'=>env('CLIENT_ID'), 'client_secret'=>env('CLIENT_SECRET'), 'grant_type'=>'password']);
		return $results;
	}
```

Post request directly to the access token function return no error, this is only happening when doing it via dispatcher.

example response when doing direct access via getAccessToken()

`{"access_token":"QM69JFt2WAY8rQ9eLvp5TxgDuuCqNaKZehL7QvJH","token_type":"Bearer","expires_in":3600}`

**Comment by jasonlewis** [comment]
```php
return \Authorizer::issueAccessToken();
```
