### ISSUE TITLE
[Question] Get user available scopes in controller method

### ISSUE THREAD

**Issue by Eke** [dingo/api#957]
Hello,

Is there way to just check if user has scope? 

For example i want to set default include for transformer if user has some kind of scope

**Comment by jasonlewis** [comment]
As in OAuth scopes? Dingo just uses the tokens scopes, so if you're using the bridge package then you can grab the authorizer instance and use the `hasScope` method.

```php
app('oauth2-server.authorizer')->hasScope('foo');
```

**Comment by Eke** [comment]
Thank you. That's what i was looking form
