### ISSUE TITLE
class 'Illuminate\Auth\SessionGuard' does not have a method 'handle'

### ISSUE THREAD

**Issue by arthurkirkosa** [dingo/api#959]
If I use the auth middleware in a controller that is used by the api router ```app('Dingo\Api\Routing\Router')```, I get the following error

> testing.ERROR: ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'handle' in /.../vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:288

```php
public function __construct()
{
    $this->middleware('auth');
}
```

If I comment out the middleware the error goes away.

Laravel: 5.2.29
Dingo: dingo/api dev-master 5e1c083

Anyone else having this issue?

**Comment by jasonlewis** [comment]
Why aren't you using `api.auth`?

Also a full stack trace would help. But, you shouldn't really be using the standard Laravel auth middleware.

**Comment by arthurkirkosa** [comment]
That particular api class is an internal used one and I want to make sure the current user is authenticated.

Does the api.auth middleware attempt the authentication in the same manner as the auth one?
