### ISSUE TITLE
Documentation broken on Lumen 5.1

### ISSUE THREAD

**Issue by Ifnot** [dingo/api#965]
Hi and thanks for theses tools :)

The lastest commit 5e1c0839067e82fdfa8472eb2e3f024a4c3b96ea broke the Lumen compatibility (5.1 on my installation).

Running : `php artisan api:docs`

Thrown : 

    [ReflectionException]
    Class path.base does not exist

I guess the problem is here : https://github.com/dingo/api/commit/5e1c0839067e82fdfa8472eb2e3f024a4c3b96ea#diff-5f0e5ef8cceae6202a7027c98d71c5b4R132

Tried with `--include-path=` the problem is the same.

Full example : `php artisan api:docs --name Example --use-version v1 --include-path=/path/to/my/api`

And as `Dingo\Blueprint\Blueprint::generate()` need a 4th parameter, reverting to commit 9f6978184ca2a8e759696b16ce8ccd36a34eae8d stuck when calling this method with only 3 params.

**Comment by Ifnot** [comment]
And as `Dingo\Blueprint\Blueprint::generate()` need a 4th parameter, reverting to commit 9f6978184ca2a8e759696b16ce8ccd36a34eae8d stuck when calling this method with only 3 params.

**Comment by Ifnot** [comment]
Immediate solution will be to use the helper `base_path()` shared between laravel and lumen.

    return rtrim(base_path($this->option('include-path')));

What do you think about it ?

**Comment by jasonlewis** [comment]
Merged in. Thanks.
