### ISSUE TITLE
Route bindings broken with latest commits

### ISSUE THREAD

**Issue by driesvints** [dingo/api#966]
With the latest commits route binding seems to be broken for us. Apparently you cannot bind anything to route parameters with the Dingo router? We register route bindings with the Laravel router in the `boot` method of the `RouteServiceProvider` and Dingo should pick these bindings up but this doesn't happens apparently. I think the problem is that we register the bindings *after* Dingo has been registered. Is it required to always register the bindings up-front?

**Comment by jasonlewis** [comment]
Just pushed a fix for an issue that may be related. See commit 0e34396a76c01339199eb2c47c9307e504fe349f and try updating to it, let me know if the issue persists.

I just tried it out (ordering the `LaravelServiceProvider` both at the start and end of the array) and it seems to be working fine. The route binding is picked up.

**Comment by driesvints** [comment]
Hey @jasonlewis. I think the bindings are indeed fixed but now with the latest commit almost half of our test suite breaks. Various errors which aren't Dingo related now which we never have before. This definitely happened after 595436348703f03917cad512ee5bb67fcb9004fc because if I downgrade to that commit, everything runs fine. I'll try to see which commit introduces the bug.

**Comment by driesvints** [comment]
Sorry, the commit I referenced above wasn't the one I meant. I'll try to find the commit which introduced the bug.

**Comment by driesvints** [comment]
I really can't see it. My local tests fail because the route bindings aren't being set and my CI builds fail on various other things but it appears that the route bindings *are* being set there (because of some specific tests which are passing). Pulling my hair out over this one.

**Comment by jasonlewis** [comment]
So what's the bug now exactly?

**Comment by jasonlewis** [comment]
Hey @driesvints can you try upgrading to the latest commit and letting me know if issues persist. Cloning the router later on means bindings and such are transferred across but also means the current route instance on the Laravel router remains untouched.

**Comment by driesvints** [comment]
Fixed in the latest commit!
