### ISSUE TITLE
Best way to convert all model attributes to camel case

### ISSUE THREAD

**Issue by andrewmclagan** [dingo/api#970]
When sending responses, I want all model attributes converted to camel case.

what is the best approach to do this?

**Comment by jasonlewis** [comment]
Use a transformer, or, overload the [`toArray`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L2426) method on your model to convert keys to camel case. You can create a new base model that all your other models extend for this.
