### ISSUE TITLE
Some exceptions not reported

### ISSUE THREAD

**Issue by pulkitjalan** [dingo/api#971]
Some of my exceptions are not being logged/reported.

After a bit of digging on `v1.0.0-beta3` `\Dingo\Api\Http\Middleware\Request@handle` has a try catch which is what reports the exception as long as an exception is thrown and the exception is not in my `$dontReport` in `\App\Exceptions\Handler`.

However the `sendRequestThroughRouter` eventually calls `\Dingo\Api\Routing\Router@dispatch` which also has a try catch but this does not report. I am guessing this is where the problem is.

What would you suggest, removing the try catch from `\Dingo\Api\Routing\Router@dispatch` or adding `$this->app['Dingo\Api\Contract\Debug\ExceptionHandler']->report($exception)` into the catch?

**Comment by jasonlewis** [comment]
Indeed reporting should be done there. Pushed a fix.

**Comment by pulkitjalan** [comment]
Great Thanks!
