### ISSUE TITLE
I have wrong for laravel5.1

### ISSUE THREAD

**Issue by xifat** [dingo/api#983]
{
message: "Call to undefined method Dingo\Api\Routing\Route::getAuthProviders()",
code: 1,
status_code: 500,
debug: {
line: 47,
file: "D:\www\laravelapp\app\Http\Middleware\OAuthMiddleware.php",
class: "Symfony\Component\Debug\Exception\FatalErrorException",
trace: [
"#0 {main}"
]
}
}

**Comment by jasonlewis** [comment]
Method is `getAuthenticationProviders` on the route instance. Check your middleware and update it accordingly.
