### ISSUE TITLE
Transformer and model realtionships

### ISSUE THREAD

**Issue by mehrdaad** [dingo/api#986]
I actually don't know whether this is a bug or my misunderstanding. Let me describe:  
I have 2 models `Venue` and `Photo`, in `Venue` I have a method called `photos()` which bring the relationship with `Photo`.  
Not in my transformer I have a `$defaultIncludes` array which one of them is `'photos'`.  
But as soon as I change this to `'photo'` I get an error indicating:  
`Call to undefined method Illuminate\\Database\\Query\\Builder::photo()`.  
As far as I know I can name my includes whatever I like as long as I provide a `includeX` function in that transformer.  
What is the reason for this error?  
My `Photo` and `Venue` relationship is `morphMany`

**Comment by naabster** [comment]
I have stumbled on this as well.

If you try to access any route returning a collection or paginator with an `include` parameter which does not represent a model relationship you get an uncaught exception `Call to undefined method Illuminate\\Database\\Query\\Builder::missingInclude()` which results in an error 500 response:

GET my.api.com/users?include=missingInclude

Controller:

        $users = User::all();
        return $this->response->collection($users, new UserTransformer);

"missingInclude" is not a valid fractal include and obviously not a eloquent relationship, but something anybody can add to an url.

The reason for this: in Dingo\Api\Transformer\Adapter\Fractal@transform the eager loads are performed for collections and paginators without checking if the relationship exists.

A workaround is to disable eager loading in your service provider / bootstrap file:

        // disable eager loading for Transformers
        $this->app['Dingo\Api\Transformer\Factory']->setAdapter(function ($app) {
            return new Fractal(new Manager, 'include', ',', false);
        });


I am not sure what would be the best way to handle this - maybe restricting eager loading to the `$availableIncludes` properties of the `$transformer`?

**Comment by ymhuang0808** [comment]
Dingo API provides the eager loading feature. Therefore, the relationship function name which is defined in `$defaultIncludes` array will be called. 

If the include key in the transformer is not different from the relationship function name, you can assign the key-value array in `$defaultIncludes`. The key is the relationship function name, the value is the include key name.

**Comment by mehrdaad** [comment]
@ymhuang0808 acting on what you said, takes responsibility of api which is providing response, to several clients and controllers.  
Which requires the developer always eager load the relationship and iterate ovr relationship, with or without necessity which will result un-maintainable code.

**Comment by nschirmer** [comment]
Thank you, @ymhuang0808! I happened to google this issue last night, found this 3-month old post, and you happened to give the perfect solution just hours before I got there.

Turning the `$defaultIncludes` array into a key/value pair worked beautifully.

**Comment by ymhuang0808** [comment]
Hi, @mehrdaad
Sorry, I have no idea why it will result unmaintainable code. Could you give examples or more details? As far as I know, Dingo API supports to [disable the eager loading](https://github.com/dingo/api/blob/b0491204a4f9c6ac305f344a0d30954175002364/src/Transformer/Adapter/Fractal.php#L209).

@nschirmer , you're welcome. I have the same problem about the relationship function, so I traced code and found it supports key-value array from [here](https://github.com/dingo/api/blob/b0491204a4f9c6ac305f344a0d30954175002364/src/Transformer/Adapter/Fractal.php#L197). Perhaps, the feature can be added into wiki, it may help others.

**Comment by nschirmer** [comment]
@ymhuang0808 It really threw me off because it worked one way, but not another... From within one of my Transformers, Users, I have an includeJobRequests, which returns an actual Fractal Collection. When I pull in my user and return the User item through Dingo, it works fine, as the included JobRequests properly include the Addresses within the `$defaultIncludes`.

But then, in my API route for pulling in only job requests, returning (from the controller) the `$this->request->collection($jobRequests, JobRequestsTransformers);` was failing on the Addresses within `$defaultIncludes`

So it seems Dingo request Fractals work differently than how raw Fractals would work. I'm glad you were able to trace the issue down! Definitely something worth mentioning in the wiki.

**Comment by ymhuang0808** [comment]
@nschirmer , Could you show the error message or debug trace?

Dingo API provides default transformation layer, `Dingo\Api\Transformer\Adapter\Fractal`. The `Fractal` uses Fractal's manager, item and collection. If you would like to know the implementation, you may trace [Fractal.php](https://github.com/dingo/api/blob/master/src/Transformer/Adapter/Fractal.php)

**Comment by springjk** [comment]
@ymhuang0808 @nschirmer Hi, guys. This question bothers me for days, and i also found this way in debugging: `$defaultIncludes` can set a key-value array, but in` $availableIncludes`, it's not work.

> `protected $defaultIncludes = ['salaryItems' => 'salary_items'];`
 
it's work fine.

> `protected $availableIncludes = ['salaryItems' => 'salary_items'];`

it's will display  `Call to undefined method Illuminate\\Database\\Query\\Builder::salary_items()`


My model function name is camel_case like `public function salaryItems()`, but i want dingo-api output all field is snake_case (include relationship), is there any idea other than overwrite function of `TransformerAbstract`?

**Comment by hasaezs** [comment]
@springjk Were you able to solve this problem? I have the same issue.

**Comment by springjk** [comment]
@hasaezs yeah, this is my solution.

>app/Http/Transformers/OverrideTransformerAbstract.php

```php
<?php

namespace App\Http\Transformers;

use League\Fractal\Scope;
use League\Fractal\TransformerAbstract;

/**
 * this class override function includeResourceIfAvailable from TransformerAbstract
 * the purpose is modify orm relation field to snake case
 * the only change is line 90 
 * 
 * https://github.com/dingo/api/issues/986
 *
 * @package App\Http\Transformers
 */
class OverrideTransformerAbstract extends TransformerAbstract
{
    /**
     * jsut copy original function
     *
     * @param Scope $scope
     * @param mixed $data
     *
     * @return array|bool
     */
    public function processIncludedResources(Scope $scope, $data)
    {
        $includedData = [];

        $includes = $this->figureOutWhichIncludes($scope);

        foreach ($includes as $include) {
            $includedData = $this->includeResourceIfAvailable($scope, $data, $includedData, $include);
        }

        return $includedData === [] ? false : $includedData;
    }

    /**
     * jsut copy original function
     *
     * @param Scope $scope
     *
     * @return array
     */
    public function figureOutWhichIncludes(Scope $scope)
    {
        $includes = $this->getDefaultIncludes();

        foreach ($this->getAvailableIncludes() as $include) {
            if ($scope->isRequested($include)) {
                $includes[] = $include;
            }
        }

        foreach ($includes as $include) {
            if ($scope->isExcluded($include)) {
                $includes = array_diff($includes, [$include]);
            }
        }

        return $includes;
    }


    /**
     * override the original function，add array key to snake case
     *
     * @param Scope  $scope
     * @param mixed  $data
     * @param array  $includedData
     * @param string $include
     *
     * @return array
     */
    protected function includeResourceIfAvailable(
        Scope $scope,
        $data,
        $includedData,
        $include
    ) {
        if ($resource = $this->callIncludeMethod($scope, $include, $data)) {
            $childScope = $scope->embedChildScope($include, $resource);
            ## add snake_case 
            $includedData[snake_case($include)] = $childScope->toArray();
        }

        return $includedData;
    }
}
```

>app/Http/Transformers/CompanyTransformer.php

```php
<?php

namespace App\Http\Transformers;

use App\Company;

class CompanyTransformer extends OverrideTransformerAbstract
{
    protected $defaultIncludes = ['trade', 'businessLicence'];

    public function transform(Company $company)
    {
        return [
            'id'                   => $company['id'],
            'full_name'            => $company['full_name'],
            'short_name'           => $company['short_name'],
            'legal_representative' => $company['legal_representative'],
            'address'              => $company['address'],
            'phone'                => $company['phone'],
        ];
    }

    public function includeTrade(Company $company)
    {
        return $this->item($company->trade, new TradeTransformer());
    }

    public function includeBusinessLicence(Company $company)
    {
        return $this->item($company->businessLicence, new AttachmentTransformer());
    }
}
```


> Return like this

```json
{
    "data": {
        "id": 1,
        "full_name": "google-inc",
        "short_name": "google",
        "legal_representative": "jack",
        "address": "xxxxxxxxxxxxxxx",
        "phone": 123456789,
        "business_licence": {
            "data": {
                "id": 1,
                "name": "test.jpg",
                "url": "xxxxxxx"
            }
        }
    }
}
```
