### ISSUE TITLE
Token invalidation

### ISSUE THREAD

**Issue by vkosachev** [dingo/api#991]
Hi, I noticed that token is not being invalidated when CACHE_DRIVER = array.
Is this expected behaviour or it is a bug?

**Invalidation example:**
```php
    public function logout(Request $request)
    {
        try{
            $token = JWTAuth::getToken();
            JWTAuth::invalidate($token);
        }catch (\Exception $e)
        {
            return $this->response->error("Oops!", ['Something went wrong']);
        }

        return $this->response->array(['data' => 'OK'], 200);

    }
```

**Comment by catalinux** [comment]
What do you mean it does not invalidate?  
Invalidation works by adding that token in a blacklist kept in the cache. If you use a array cache driver that blacklist will be available only that call.

**Comment by vkosachev** [comment]
@catalinux guess you are right, wa my misuderstanding how the array driver worked.
