### ISSUE TITLE
Adding routeMiddleware

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#993]
Hey,

somehow creating new routeMiddleware does not work. I do not get an error, but the middleware does not kick in. Using a global middleware works fine.

I am thinking it might be to do with dingo having a different router? How do I register route middleware?

Any ideas? I am using Lumen 5.2.6.

**Comment by jycr753** [comment]
Just place the middle ware in the api.php file:

```
 'middleware' => [
    ],
```

**Comment by lukasoppermann** [comment]
Hey, so I got it working by using the fully qualified namespace:

```php
    $api->group([
        'namespace' => 'App\Api\V1\Controllers',
        'middleware' => [
            App\Http\Middleware\TestingMiddleware::class
        ],
    ], function($api){
```

Adding it to the middleware array does have a disadvantage, it is called for every route, not just the one I want.
