### ISSUE TITLE
Exception handler is mangling JsonResponse's

### ISSUE THREAD

**Issue by Blizzke** [dingo/api#994]
When returning a JsonResponse from a registered handler, it is [mangled by the Dingo handler](https://github.com/dingo/api/blob/master/src/Exception/Handler.php#L135) into a regular internal server error as it is not a `Illuminate\Http\Response`. Wouldn't it be better to check for an instance of `Symfony\Component\HttpFoundation\Response` here?

**Comment by ChitaGideon** [comment]
When I try to use `redirect` to handle exception , I get the same trouble.
The RedirectResponse has been converted to Response ,and I have unexpected content.

**Comment by hskrasek** [comment]
@Blizzke You are correct, plan on fixing it up.
