### ISSUE TITLE
Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in vendor/dingo/api/src/Dispatcher.php on line 543 and defined

### ISSUE THREAD

**Issue by mohammedibrahim** [dingo/api#998]
Hello there,

I am trying to make and internal request but it ends with this error
```
Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in /var/www/htr/api/vendor/dingo/api/src/Dispatcher.php on line 543 and defined

```
here is my routes.php

```
$api->version('v1', ['middleware' => 'guest', 'protected' => false], function ($api) {
    $api->group(['prefix' => 'v1',], function ($api) {
        $api->post('register', '\App\Http\Controllers\APIs\ApiAuthController@register');
    });
});
```

The internal request

```
        $response = $this->api->version(env('API_VERSION', 'v1'))->post(env('API_VERSION', 'v1').'/register', [
            'name' => $user->name,
            'email' => $user->email,
            'password' => Hash::make('123456')
        ]);
```

**Comment by aleemb** [comment]
I see the same thing in my validation method, which on failed validation throws

    throw new ValidationHttpException($validator->errors());

Error happened when I updated from L5.1 to L5.2 along with dingo/api (both beta3 and latest).

**Comment by kaiserlos** [comment]
My error: feels like it is kind of the same

Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Symfony\Component\HttpFoundation\Response given, called in /home/vagrant/www2/vendor/dingo/api/src/Dispatcher.php on line 543 in /home/vagrant/www2/vendor/dingo/api/src/Exception/InternalHttpException.php:22

**Comment by hskrasek** [comment]
Believe this is the same or related to #1024 and #1014

**Comment by hskrasek** [comment]
Having a hard time re-creating this issue. I just tagged [1.0.0-beta4](https://github.com/dingo/api/releases/tag/v1.0.0-beta4 ), @kaiserlos, @aleemb and @mohammedibrahim could y'all check this newly tagged version, and see if the issue still exists?

**Comment by kaiserlos** [comment]
will try today.

**Comment by kaiserlos** [comment]
Does not work with 1.0.0-beta4 and beta5

Some bits you can use to reproduce:

Function doing an internal request to the dingo api:
```
<?php

namespace App\Http\Controllers;

use Dingo\Api\Dispatcher;


class TestController extends BaseController {

	public function __construct(Dispatcher $api) {
		$this->api = $api;

        if(Auth::check())
            $this->api->be(Auth::user());
	}

	public function apiDebug() {
		try {
            $response = $this->api->with(['username' => 'abc'])->post('api/user');
           	print_r($response);
        } catch(\Exception $e) {
            print_r($e);
        }
	}
}
?>
```


The api function should implement this form request for validation
```
<?php

namespace App\Http\Requests\Api;

use App\Http\Requests\Request;
use Dingo\Api\Http\FormRequest;

class StoreUserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }


    public function messages()
    {
        return trans('validation.user');
    }
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
          
                'username' => 'required|username|min:4|max:20|unique:users',
                'email' => 'required|email|max:255|unique:users',
                'terms' => 'required',
                'password' => 'required|min:6|confirmed',
                
            
        ];
    }
}

?>
```

**Comment by aleemb** [comment]
@hskrasek 

In my case, the internal request was throwing a validation exception and my Exception handler was doing a redirect.

However, I read on some other issues here that an Internal request should not do redirects. I suppose that makes sense. I ended up rewriting the logic so that the redirects only happen at the HTTP request level and side-stepped this issue.

Reading @mohammedibrahim initial report, it appears he was doing something similar because of the `Illuminate\Http\RedirectResponse` message in the error.

Not sure if this is the same use case for others or what would be the correct way to handle RedirectResponse from Internal API requests.

**Comment by hskrasek** [comment]
You can see my changes in the mentioned commits, but I've update InternalHttpException to type hint the base symfony response. I also made it to where only 400+ status code response will throw the exception. So basically Ok and Redirect responses will bubble all the way up through the dispatcher.
