### ISSUE TITLE
Nested transformer include issue

### ISSUE THREAD

**Issue by fbingha** [dingo/api#999]
Not sure if this is a dingo or fractal issue.

I have a transformer that has 4 available includes.

In my transformer, I have an api call:

$parkinfo = json_decode($this->api->raw()->get('options/park-info/lite')->getContent());

This api call has a transformer as well. When I have the api call functioning, the top level transformer does not process its includes. If I comment out this API call, the top level transformer does process its includes.

It seems to me that the nested transformer is wiping out the top level transformer's available includes so that the top level transformer does not include as asked. My guess is that the same fractal manager is being used by both transformers resulting in the second transformer resetting requestIncludes to an empty array.

**Comment by assembledadam** [comment]
You should probably provide a larger context - where's the parent API call?  Where do you define the includes?

I know that Fractal includes are sensitive to an 'include' GET query string, that can optionally be disabled.

**Comment by fbingha** [comment]
The parent API call is the root call and the includes are on the query string, using 'include'. Within the root call's transform, before the root does the transformation (important part) I am including more information from an internal API call and it is the internal API call, which has its own transformer that is wiping out the includes for the root API call. It still appears that same manager instance is being used for both API calls, which is allowing the state of the root call to be altered by the second usage of the manager.

Regardless, I worked around it by setting the root's defaultIncludes, at runtime, to be the includes on the querystring, instead of allowing it to detect the includes. It is ugly as the default includes shouldn't be used this way.

**Comment by hskrasek** [comment]
Due to how the internal API calls are made, this is kinda expected behavior. Something to look into though as an improvement, see if we can "reinstance" the manage for the internal call and reset the includes only for that call.

It gets tricky though, because if you havent already transformed the "parent" API call, we run the risk of wiping out the includes before they are needed for the parent call.
